README.md
Added basic information to the project readme file.
For now just how to start the project and the contributing guidelines we have so far.
=> Add starting guidelines for contributing

src/pages/installation.md
- Creates a draft for Installation Page content
=> Draft for Installation Page

public/index.css, src/layouts/Main.astro
- Add View Port Meta Tag
- Update Pre elements width to avoid overflow
- Remove empty style block
Executed Manually
=> Fix responsiveness for pages

src/pages/quick-start.md
Added content to quick-start page. Let me know if their is other information that should be added.
=> quick-start page

public/index.css, src/pages/index.md
Made landing page image responsive. #28
=> Landing page image

src/pages/core-concepts/astro-components.md
- Edit the info that's already here
- Tried to clarify some terminology 
- add some missing documentation
/cc @snowpackjs/docs
=> new astro component syntax doc

src/pages/guides/deploy.md
Added the instructions for using a `netlify.toml` and an `.nvmrc` file.
=> Update Netlify deploy configuration directions

package.json, yarn.lock
This just sets up a command for automatically formatting files in the repo with prettier. 
From #50
=> Add `yarn format` script

src/components/SiteSidebar.astro
=> Fix sidebar hover for dark theme

package.json, src/pages/core-concepts/astro-components.md, src/pages/guides/markdown-content.md, src/pages/guides/styling.md, src/pages/installation.md, src/pages/reference/cli-reference.md
There's some ambiguity in the broken links for some yet unwritten pages:
Also:
- VSCode extension links 404 for the link check tool 
- Heroku signup page 500's
- etc...
```
yarn lint:linkcheck:local
yarn run v1.22.10
$ blc -ro --user-agent 'broken-link-checker/0.7.8' 'http://localhost:3000'
Getting links from: http://localhost:3000/
├───OK─── http://localhost:3000/installation
├───OK─── http://localhost:3000/quick-start
├───OK─── http://localhost:3000/examples
├───OK─── http://localhost:3000/core-concepts/project-structure
├───OK─── http://localhost:3000/core-concepts/astro-components
├───OK─── http://localhost:3000/core-concepts/astro-pages
├───OK─── http://localhost:3000/core-concepts/layouts
├───OK─── http://localhost:3000/core-concepts/collections
├───OK─── …
```
=> Fix some of the broken links

public/theme.css, src/components/SiteSidebar.astro
Oops it looks like we missed a bit of styling in #63 / #61 -- I definitely want to rework the styles using HSLA so that adding additional colors to the theme is as simple and understandable as possible!
=> Fix "active page" background in sidebar on dark mode

package.json, src/pages/guides/data-fetching.md
=> Add `node-fetch` documentation until astro#140 is fixed and we have global `fetch`

src/pages/core-concepts/astro-components.md
=> Fixed example code

src/pages/en/guides/deploy.md, src/pages/en/guides/markdown-content.md, src/pages/en/guides/styling.md, src/pages/en/reference/builtin-components.md, src/pages/es/guides/deploy.md
Some changes made in the astro repo were deleted in the main repo before being migrated. These are those changes.
=> Migration from astro repo

src/pages/en/guides/markdown-content.md
Was searching for this feature and found it in the blog example. It's awesome, but wasn't yet documented!
=> Use components in markdown

src/pages/de/core-concepts/project-structure.md, src/pages/en/core-concepts/project-structure.md, src/pages/es/core-concepts/project-structure.md
- Fix the link to the installation guide on the project structure page
- I have confirmed that all the links work in my local environment.
=> Fix the link to the installation guide on the project structure page

src/pages/en/guides/environment-variables.md
Updates `import.meta.env` docs to align with https://github.com/withastro/astro/pull/2612 in `v0.23.0`
=> Update environment variables guide

src/pages/en/migrate.md
Preview: https://deploy-preview-159--astro-docs-2.netlify.app/en/migrate/#deprecated-astroresolve
=> Update migrate to clarify asset import docs

src/config.ts, src/pages/en/integrations/integrations.md
New integrations page added separately here. (Not yet in sidebar, but will new proposed landing page has its updated location.)
=> New Integrations page, linked to in sidebar

src/pages/en/core-concepts/project-structure.md
=> Quick typo fix in project-structure

netlify.toml
To address some old links to Quick Start from older websites/tutorials
=> Created a Netlify redirect for old quick start page

src/pages/en/integrations/integrations.md
Adding another video example: Astro + Figma!
=> New integration - Astro + Figma video series

package.json, public/index.css, scripts/docgen.mjs, src/pages/en/reference/configuration-reference.md, yarn.lock
=> auto-generate configuration reference page from TS types

README.md, src/pages/en/reference/cli-reference.md, src/pages/en/reference/configuration-reference.md
- Add `--host` to CLI reference
- Add `host` to configuration reference
- Deprecate `--hostname` from configuration reference
- Misc: update README to recommend pnpm. Notice the lock file while working 🙃
=> Add new `--host` API option

src/pages/en/comparing-astro-vs-other-tools.md
Makes for a nicer sidebar, also extracted the most common differences that kept getting repeated throughout each framework and put them at the very top in a "usually this is the difference" section.
=> Astro vs X - Better sidebars via changing heading levels

public/theme.css, src/components/LeftSidebar/LeftSidebar.astro, src/components/LeftSidebar/SidebarSectionToggle.css, src/components/LeftSidebar/SidebarSectionToggle.tsx, src/config.ts
- Reorganize the sidebar based on feedback from @sarah11918 
- Give guidance on new pages to add, convert, merge together, etc.
=> Reorg the sidebar with guidance

src/pages/en/core-concepts/partial-hydration.md
=> Missing word in docs

src/pages/en/guides/markdown-content.md
Applied a small part explaining about YAML in the frontmatter, and how it can be used to organise the page's meta data
=> Updated content to inc YAML content

src/pages/en/guides/integrations-guide.md
Docs for https://github.com/withastro/astro/pull/2849. Still marked as experimental for the time being.
=> Adds `astro add` docs to integrations

astro.config.ts, package.json, pnpm-lock.yaml
- Looks good to me, but wanted to give others a chance to look as well
=> update to astro v0.25

src/pages/en/guides/imports.md
In the course of editing all the current pages, I thought an example of referencing some files in public would be useful.
=> Static Assets - added section for public folder

src/pages/pt-br/getting-started.md
* Removed mentions and links to pages that no longer exists.
* Updated broken links.
=> docs(i18n-pt-BR): Fix PT-BR broken links

src/config.ts
This reverts commit 580efa9299f6d60c2fb162a04e93d618b170a6aa.
=> Revert "update sidebar"

src/pages/en/guides/markdown-content.md
source: https://docs.astro.build/en/reference/configuration-reference/#markdownsyntaxhighlight
=> Fix syntax highlighting config

src/pages/pt-BR/getting-started.md
Hey there,
A tiny change to improve undertanding 🚀 !
=> fix encontre to ache

src/pages/index.astro
Based on a convo in Discord. See the "files changed" tab for context and reasoning, left as a comment in the codebase.
=> stop auto-directing based on language, always show english by default

src/pages/en/guides/imports.md
=> Fix : Few Typos

src/pages/en/core-concepts/routing.md
Following changes from #341 to `routing` page on line 259
=> Updating Astro.request.params to Astro.params

src/pages/en/core-concepts/astro-components.md
When helping out in a support thread, I noticed that these docs are out of date.
=> Update script information in components page

src/pages/en/core-concepts/routing.md, src/pages/en/guides/markdown-content.md, src/pages/en/guides/rss.md, src/pages/en/reference/api-reference.md
(And, a couple of other pases where fetchContent was in use.)
Should close: https://github.com/withastro/docs/issues/362
=> updated RSS to replace fetchContent with glob

src/i18n/translations.ts
I know it's just a small contribution but I hope it helps <3
=> Added german translation in `translation.ts`

src/pages/en/core-concepts/project-structure.md
Was setting up astro when I noticed this link 404s 😅
=> Fix broken link to manual install

src/pages/en/core-concepts/astro-components.md
Refs https://github.com/withastro/astro/issues/2238
Is this reasonable to add here?
=> Update astro-components.md to warn usage of named slots

src/pages/es/comparing-astro-vs-other-tools.md, src/pages/es/core-concepts/astro-components.md, src/pages/es/getting-started.md, src/pages/es/installation.md, src/pages/es/quick-start.md
✅ fix Spanish translations and some typos
=> fix typos and update language translations

src/pages/en/core-concepts/framework-components.md
=> Update framework-components.md in tandem with #371

src/pages/en/guides/server-side-rendering.md
- Specify what an API route is
- Add the example filename to match the previous example
- Add `async` in the function declaration so that it's a working example
=> API route clarification

src/pages/en/getting-started.md
We've had some changes since this page was built, so here's a suggested draft to make it more in keeping with what's all going on now!  Open to suggestions... this is just to get the ball rolling.
=> Refreshed getting started 

src/pages/en/editor-setup.md
Minor polish to the page: typo fix, link to the new TypeScript page to check off an old TODO, added Gitpod to the bottom.
=> Editor setup polish

src/pages/en/core-concepts/partial-hydration.md, src/pages/en/editor-setup.md, src/pages/en/getting-started.md, src/pages/en/integrations/integrations.md
added i18nReady true to frontmatter for testing
=> i18nReady test: some pages with frontmatter Boolean

astro.config.ts, package.json, pnpm-lock.yaml
- Removed `mode: 'mdx'` because it's no longer necessary
- Formatted
- Moved `remark-gfm` and `remark-smartypants` to `remarkPlugins`
- Added plugins to package.json
=> Some fixes in the astro config

src/pages/en/core-concepts/framework-components.md
Some small edits to polish the page
=> Minor editing of framework components for readability

src/pages/en/core-concepts/layouts.md, src/pages/en/guides/configuring-astro.md, src/pages/en/guides/data-fetching.md, src/pages/en/guides/environment-variables.md, src/pages/en/guides/imports.md
Some edits in text, some for cosmetic purposes because there's a lot going on with all the bits of code close together and all the `import[dot]meta[dot]env`.
=> Minor edits for readability improvements - Environment variables

src/pages/en/guides/integrations-guide.md, src/pages/en/guides/typescript.md
One in Integrations Guide, one in TypeScript page
=> Typo Fixes - very minor

src/pages/en/core-concepts/astro-components.md
Mostly adding lists to things that now exist (integrations, directives page) and an example of `set:html`
=> Minor additions to components - mostly links

src/i18n/README.md
Discord is blocked in some places, so this suggests an alternative engagement path for those impacted.
=> Add note to i18n guide for folks who can’t access Discord

src/pages/en/reference/integrations-reference.md
Adds missing documentation for the `astro:build:setup` integration hook, and adds the new pages param to the types
Depends on https://github.com/withastro/astro/pull/3286
=> docs: add missing build:setup docs, and add new pages param

src/pages/en/guides/publish-to-npm.md
Adds an integration page link, and a few other minor bits of polish.
=> Minor polishing - Publish to npm page

README.md, src/i18n/README.md
- Link to the i18n guide from the main repo README
- Reorder the i18n guide sections slightly to get the key engagement section up top
- Add a link to our snazzy new overview issue 🥳
=> Tweak i18n guide

src/i18n/zh-TW/ui.ts, src/pages/zh-TW/getting-started.md
=> Update zh-tw translations

src/pages/en/reference/cli-reference.md
This is a companion to https://github.com/withastro/astro/pull/3256, documenting how to enable/disable anonymous telemetry.
=> Telemetry docs

scripts/github-translation-status.mjs, src/i18n/README.md
This PR updates the list of supported languages for translation
- in the i18n guide
- in the translation issue updater
=> Update supported languages

src/i18n/es/docsearch.ts
Added file with Spanish translations corresponding to docsearch.
=> Add docsearch translation in spanish

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/install/auto.md
Adding the `install/auto.md` page in pt-BR and `nav.ts` text for it as well!
=> i18n(pt-BR): Adding `install/auto.md` page

src/i18n/es/nav.ts, src/i18n/es/ui.ts, src/pages/es/install/auto.md
=> i18n(es): translate `install/auto.md`

src/i18n/es/ui.ts
=> i18n(es): translate `ui.ts`

src/i18n/es/nav.ts, src/pages/es/editor-setup.md
=> i18n(es): translate `editor-setup.md`

src/pages/es/integrations/integrations.md
=> i18n(es): translate `integrations/integrations.md`

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/core-concepts/partial-hydration.md, src/pages/pt-BR/core-concepts/project-structure.md
Translations for `partial-hydration.md` and `project-structure.md`. I also made a small change and added new translations to nav.ts.
=> i18n(pt-BR): Adding `partial-hydration.md` & `project-structure.md` 

src/i18n/pt-BR/nav.ts, src/i18n/pt-BR/ui.ts, src/pages/pt-BR/editor-setup.md, src/pages/pt-BR/integrations/integrations.md
Translations for `editor-setup.md` and `integrations.md`. Also updated `ui.ts` with the "Astro Docs on GitHub" translation.
=> i18n(pt-BR): Adding `editor-setup.md` & `integrations.md` translations + `ui.ts` update

src/pages/en/guides/integrations-guide.md
This is mostly an excuse to test our automated updating system for @hippotastic , but the link is potentially a helpful addition anyway.
=> Added external link to npm

src/pages/en/integrations/integrations.md
Again, mostly for @hippotastic ! Hoping that this triggers an update to the status of some already-translated pages, and tells the translators this page needs updating.
=> Improving Built With Astro wording

src/pages/de/editor-setup.md
=> i18n(de): Add `editor-setup.md` translation

src/pages/pt-BR/integrations/integrations.md
This small PR makes `integrations.md` up-to-date with the English version.
=> i18n(pt-BR): Update integrations.md

src/pages/es/install/manual.md
=> i18n(es): translate install/manual.md

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/core-concepts/astro-components.md, src/pages/pt-BR/core-concepts/astro-pages.md
Translations for both `astro-components.md` and `astro-pages.md`.
=> i18n(pt-BR): Add `astro-components.md` & `astro-pages.md` translations

.gitignore
Adding each config and log files from popular tools to avoid being pushed unexpectedly into the repo
- removing outdated `.snowpack/`
- adding filter for yarn package manager lock file `yarn.lock`
- adding filter for PNPM log file `pnpm-debug.log`
- Adding filters for some of the more "popular" IDE's (including online ones)
=> Updating `.gitignore` to be more strict and avoid undesired changes

src/pages/en/guides/markdown-content.md
"There's a rat in separate." 😄
=> copyedit: seperate -> separate

src/pages/en/guides/deploy.md
Astro now works zero-config on Vercel! 🎉 
- https://github.com/vercel/vercel/pull/7747
- https://astro-template.vercel.app/
=> Update Vercel deployment docs for zero-config.

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/core-concepts/framework-components.md, src/pages/pt-BR/core-concepts/layouts.md
Translations for both `layouts.md` and `framework.components.md` pages.
=> i18n(pt-BR): Add `layouts.md` and `framework.components.md` translations

src/i18n/es/nav.ts, src/pages/es/integrations/integrations.md
=> i18n(es): update side nav and fix es/slug

public/index.css, src/pages/en/reference/adapter-reference.md, src/pages/en/reference/cli-reference.md, src/pages/en/reference/directives-reference.md, src/pages/en/reference/integrations-reference.md
- What does this PR change? Adds backticks in the `reference/` directory.
Closes #509 
Before:
After:
=> Code as headings

src/pages/en/guides/server-side-rendering.md, src/pages/en/guides/typescript.md, src/pages/en/install/auto.md, src/pages/en/install/manual.md, src/pages/en/migrate.md
- What does this PR change? Final pass for code used in headings, adding backticks to them
- Did you change something visual? see #509
=> Code as heading: final pass

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/guides/integrations-guide.md, src/pages/pt-BR/guides/server-side-rendering.md
Added `integrations-guide.md` and `server-side-rendering.md` translations
=> i18n(pt-BR): Add `integrations-guide.md` and `server-side-rendering.md` translations

src/components/Header/Search.tsx
=> change class to className

src/pages/en/core-concepts/astro-components.md
Perry is a platypus, not a _platipus_
=> minor: Change 'platipus' to 'platypus' in `astro-components.md`

src/pages/en/guides/rss.md
This PR makes the section's name in the comment the same as the actual heading name.
=> minor: Change section name in comment

src/i18n/fr/nav.ts, src/pages/fr/guides/server-side-rendering.md
- What does this PR change? Changing `Interprétation côté serveur` and `Affichage côté serveur` to `Rendu côté serveur` it's official name given in French.
=> i18n(fr): Updating `server-side-rendering.md` to fix wording issues

src/pages/de/install/auto.md, src/pages/en/guides/integrations-guide.md, src/pages/en/install/auto.md, src/pages/en/reference/configuration-reference.md, src/pages/en/reference/integrations-reference.md, src/pages/es/install/auto.md, src/pages/pt-BR/guides/integrations-guide.md, src/pages/pt-BR/install/auto.md, src/pages/zh-CN/install/auto.md
Removing all references to the `@astrojs/turbolinks` integration
=> removing all references to the Turbolinks integration

src/i18n/zh-CN/ui.ts
zh-CN `<ThemeToggleButton>` a11y labels
ref https://github.com/withastro/docs/pull/418
=> chore(ui): zh-CN `<ThemeToggleButton>` a11y labels

src/pages/en/reference/directives-reference.md
Astro isn't "awsome", it's **_AWESOME!_**
=> minor: Fix typo on `directives-reference.md`

src/pages/pt-BR/core-concepts/framework-components.md, src/pages/pt-BR/core-concepts/partial-hydration.md
Update for the PT-BR version of `framework-components.md` and `partial-hydration.md`. I also did some changes and fixes based on what the PT-BR translation team agreed upon based on our translation guide.
=> i18n(pt-BR): Update `framework-components.md` and `partial-hydration.md` pages

src/i18n/de/ui.ts
I choosed to stay with the english word "Theme" because "Thema" sounds a little bit to formal to me. What are your thoughts about it?
- I added the german translation for the new theme toggle
- Nope
=> i18n(de): add theme toggle translation

src/pages/en/core-concepts/routing.md
@aFuzzyBear and I struggled to get pagination working after reading the docs. This addresses a few of our painpoints:
- explain the file naming structure up-front
- change from the Pokemon API demo to a hard-coded list. This should clarify what your array should look like, and where `page.data` is sourcing its data from
- tweak the "page prop" docs to highlight next and previous URLs
=> Edit: improve pagination explanation + example

src/pages/en/guides/debugging.md
=> fix typo on `debugging.md`

src/pages/ja/install/manual.md
- Translated the manual install page into Japanese.
=> i18n(ja): Add Japanese `install/manual.md`

src/i18n/ja/ui.ts
=> i18n(ja): Add Japanese translation to `ui.ts`

src/i18n/es/nav.ts, src/pages/es/core-concepts/partial-hydration.md
Adds `core-concepts/partial-hydration` page in Spanish.
=> i18n(es): add `core-concepts/partial-hydration`

src/pages/en/guides/publish-to-npm.md
Replace `npm` with `pnpm` in https://github.com/withastro/docs/blob/main/src/pages/en/guides/publish-to-npm.md.
The PR fixes a type where `npm` is used instead of `pnpm` in one command.
=> Fix type in `pnpm` command [EN]

src/pages/fr/guides/imports.md
- What does this PR change? Removing a space preventing the link from being formatted
=> i18n(fr): Removing space breaking link from formatting properly

src/pages/fr/guides/imports.md
- What does this PR change? same than #639 but another time
=> i18n(fr): Removing space breaking link number 2, i missed one too

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/guides/aliases.md
Adds the pt-BR version of `aliases.md` page.
=> i18n(pt-BR): add `aliases.md`

src/pages/fr/core-concepts/astro-pages.md
- What does this PR change? Adding content from both #482 and #554 into the french translation
=> i18n(fr): Updating `astro-pages.md` to reflect latest changes

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/reference/adapter-reference.md, src/pages/pt-BR/reference/integrations-reference.md
Update both `adapter-reference.md` and `integrations-reference.md` based on #645
=> i18n(pt-BR): Update `adapter-reference.md` and `integrations-reference.md`

src/pages/en/core-concepts/project-structure.md
- What does this PR change? Change some of the syntax from `project-structure.md` to suit more in the given context, some suggested by @jbrains
=> minor: Change the syntax for some `project-structure.md` sentences to be more accurate

src/pages/fr/core-concepts/astro-components.md
- What does this PR change? Update the current french translation with latest change on this page
=> i18n(fr): Update `astro-components.md` to follow changes from #522

src/pages/pt-BR/reference/integrations-reference.md
Updated `integrations-reference.md` based on #667 changes
=> i18n(pt-BR): Update `integrations-reference.md`

src/pages/fr/guides/rss.md
- What does this PR change? Adds `/fr/guides/rss.md` to the french translation.
=> i18n(fr): Adding `rss.md` translation

src/pages/fr/core-concepts/routing.md
- What does this PR change? Adds `/fr/guides/routing.md` to the french translation.
=> i18n(fr): Adding `routing.md` translation

src/pages/de/core-concepts/astro-components.md
- Add German translation for `core-concepts/astro-components.md`
I am not quite sure about "Komponenteneigenschaften". That's why I added "(Props)" after the heading for clarification. Using "Eigenschaften" alone further in the text could also be confusing. I would be grateful for any feedback from other German speakers/readers.
=> i18n(de): add `core-concepts/astro-components.md`

src/pages/ja/comparing-astro-vs-other-tools.md
- Translated the Astro vs. X page into Japanese.
=> i18n(ja): Add Japanese `comparing-astro-vs-other-tools.md`

src/pages/fr/guides/publish-to-npm.md
- What does this PR change? Adds `/fr/guides/publish-to-npm.md` to the french translation.
=> i18n(fr): Adding `publish-to-npm.md` translation

src/pages/fr/guides/environment-variables.md, src/pages/fr/guides/rss.md
- What does this PR change? Adds `/fr/guides/environment-variables.md` to the french translation.
=> i18n(fr): Adding `environment-variables.md` translation

src/pages/fr/guides/configuring-astro.md
- What does this PR change? Apply fixes reported by @jbrains on the last PR after it was merged, which was relevant to do modifications as theses part contain inconsistency / errors on translation which doesn't make sense
cc @Olyno for notifying me on this, thank you
=> i18n(fr): Fixing small issues on `configuring-astro.md`

src/pages/en/reference/cli-reference.md
Let's see who the first to notice is... 🚀
=> Marking cli-reference i18nReady

src/pages/en/guides/markdown-content.md
- We have all-new helpers for getting raw markdown content! This updates the imported markdown docs to explain how they work + common usage examples
- Add `rawContent()` explainer with "minutes read" example
- Add `rawContent.html()` explainer with "summary" example
- For discussion: **should we ditch the bulleted format and use level 4 headers now?** The examples are still readable, but not super scannable anymore
=> New: markdown `rawContent()` and `compiledContent()` helpers

src/pages/de/core-concepts/astro-pages.md
- Add German translation for `core-concepts/astro-pages.md`
=> i18n(de): add `core-concepts/astro-pages.md`

src/pages/pt-BR/guides/markdown-content.md
Update pt-BR `markdown-content.md` based on #668 changes.
=> i18n(pt-BR): Update `markdown-content.md`

src/pages/fr/install/auto.md
- What does this PR change? Adds `/fr/install/auto.md` to the french translation.
=> i18n(fr): Adding `install/auto.md` translation

src/pages/fr/install/manual.md
- What does this PR change? Adds `/fr/install/manual.md` to the french translation.
=> i18n(fr): Adding `install/manual.md` translation

src/pages/fr/integrations/integrations.md
- What does this PR change? Adds `/fr/integrations/integrations.md` to the french translation.
=> i18n(fr): Adding `integrations.md` translation

src/pages/fr/editor-setup.md
- What does this PR change? Adds `/fr/editor-setup.md` to the french translation.
=> i18n(fr): Adding `editor-setup.md` translation

src/pages/fr/guides/markdown-content.md
- What does this PR change? Updating `/fr/guides/markdown-content.md` from changes by #668
=> i18n(fr): Update `markdown-content.md` to latest changes

src/i18n/es/nav.ts, src/pages/es/guides/markdown-content.md
- translates `guides/markdown-content.md` to Spanish
- updates `guides/markdown-content.md` to match #668
=> i18n(es): translate markdown-content

src/pages/pt-BR/guides/styling.md
PR #633 added new content to styling page.
=> i18n(pt-BR): update `styling.md` page

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/reference/cli-reference.md
Adds the pt-BR `cli-reference.md` page
=> i18n(pt-BR): Add `cli-reference.md` translation

src/i18n/pt-BR/nav.ts, src/pages/pt-BR/migrate.md
PT-BR translation for`migrate.md`
=> i18n(pt-BR) Add `migrate.md` translation

src/pages/ja/core-concepts/astro-pages.md
- Translated the Astro Pages page into Japanese.
=> i18n(ja): Add Japanese `core-concepts/astro-pages.md`

src/pages/hu/getting-started.md
=> i18n(pages-hu): Fix typo

src/pages/en/core-concepts/partial-hydration.md
Some wording updates based docs feedback on Ben's live stream.
Should be updated in all languages.  :)
=> Text improvements to Partial Hydration

src/pages/ja/core-concepts/layouts.md
- Translated the layouts page into Japanese.
=> i18n(ja): Add Japanese `core-concepts/layouts.md`

src/pages/es/core-concepts/astro-pages.md
- Update `core-concepts/astro-pages.md` to match #554
=> i18n(es): update `astro-pages.md`

src/i18n/es/ui.ts, src/pages/es/core-concepts/routing.md
- Updates `core-concepts/routing.md` to match #608 and #611
=> i18n(es): Update `core-concepts/routing.md`

src/pages/es/core-concepts/partial-hydration.md
- Update `partial-hydration.md` to match changes in #699
=> i18n(es): Update `partial-hydration.md`

src/i18n/es/nav.ts, src/pages/es/guides/data-fetching.md
- adds Spanish page for`guides/data-fetching.md`
=> i18n(es): add `data-fetching.md`

src/pages/ja/guides/configuring-astro.md
- Translated configuring-astro.md to Japanese.
=> i18n(ja): Add Japanese configuring-astro.md

src/pages/fr/guides/data-fetching.md
- What does this PR change? Adds `/fr/guides/data-fetching.md` to the french translation.
=> i18n(fr): Adding `data-fetching.md` translation

src/pages/pt-BR/guides/styling.md
Updated PT-BR `styling.md` based on #694 changes.
=> i18n(pt-BR): Update `styling.md` based on #694 changes

src/i18n/es/nav.ts, src/pages/es/guides/environment-variables.md
- adds `guides/environment-variables.md` in spanish
- adds page to `nav.ts`
=> i18n(es): add `guides/environment-variables.md`

src/i18n/es/nav.ts, src/pages/es/guides/imports.md
- adds guides/imports to Spanish
- adds static assets to nav.ts
=> i18n(es): add `guides/imports.md`

src/pages/pt-BR/reference/api-reference.md
Updated the PT-BR `api-reference.md` page based on #740 changes.
=> i18n(pt-BR): Update `api-reference.md` based on #740 changes

src/pages/en/guides/markdown-content.md
Converted bullet points from Importing Markdown section into subsections. Fixes #669
N/A
=> Convert bullet points to subsections in Importing Markdown

src/pages/en/guides/troubleshooting.md
Add a note (gotcha) regarding using Astro with Berry.
=> Add gotcha regarding usage of Astro with Berry

src/pages/pt-BR/guides/troubleshooting.md
Updated PT-BR `troubleshooting.md` page based on #749 changes.
=> i18n(pt-BR): Update `troubleshooting.md` based on #749 changes

src/components/HeadSEO.astro, src/components/Header/Header.astro, src/components/LeftSidebar/LeftSidebar.astro, src/components/PageContent/PageContent.astro, src/components/RightSidebar/RightSidebar.astro, src/components/TabGroup/InstallGuideTabGroup.astro, src/i18n/util.ts, src/layouts/MainLayout.astro, src/layouts/SplashLayout.astro
#747 updates our advice on how to import JS/TS/JSX/TSX files. We had a bit of a mixed bag, so this PR removes any remaining extensions from imports like that so we’re now complying with our own advice.
=> Practice what we preach: remove extensions from ts(x) imports 🧹

src/pages/en/guides/deploy.md
Add Deno Deploy documentation in the Deploy section.
Inspired on: https://www.elian.codes/blog/22-05-06-deploying-astro-on-deno/
=> Add Deno Deploy using deployctl to Deploy docs

src/pages/pt-BR/reference/api-reference.md
Updated PT-BR `api-reference.md` page based on #742 changes.
=> i18n(pt-BR): Update `api-reference.md` based on #742 changes

src/pages/pt-BR/migrate.md
Updated PT-BR `migrate.md` page based on #764 changes.
=> i18n(pt-BR): Update `migrate.md` based on #764 changes

src/pages/pt-BR/reference/configuration-reference.md
Updated PT-BR `configuration-reference.md` page based on #769 changes.
=> i18n(pt-BR): Update `configuration-reference.md` based on #769 changes

src/pages/pt-BR/guides/troubleshooting.md
Updated pt-BR `troubleshooting.md` page based on #780 changes.
=> i18n(pt-BR): Update `troubleshooting.md` based on #780 changes

src/pages/en/guides/server-side-rendering.md
- added a link to the Cloudflare adaptor along side the other adaptors in the SSR section 🙂 (I assume it is in alphabetical order)
=> feat: include cloudflare adaptor in SSR links

src/pages/pt-BR/reference/integrations-reference.md
Updated PT-BR `integrations-reference.md` page based on #704 changes
=> i18n(pt-BR): Update `integrations-reference.md` based on #704 changes

README.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX187NQHkSfVa4eubeC8uo9HOcp2wc3NTf%252B8%253D%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hKgsmEB)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1p1L2u3SsxjTcoDaQvPLk0531Rfqz5mrKnAOgD2Ye1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=kHQ2N1H)
- Moving content out of main README.md and into CONTRIBUTING.md
In general, trying to sequester relevant info on CONTRIBUTING.md, leaving README cleaner and friendlier. 
(Corresponding change to …
=> README.md slim-down

CONTRIBUTING.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1p1L2u3SPp1L2u3S25Rs1L2a3S4hOyxK5s0RTp1L2u3SAACeFcs8UcJvQxoYe1Q2u3A4l%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Jf3-GGi)
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX187NQHkSfVa4eubeC8uo9HOcp2wc3NTf%252B8%253D%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=hKgsmEB)
- This incorporates some of the material previously existing at README.md
- Also adds new content re: what is a helpful PR vs Issue vs Discussion to encourage and organize productive …
=> CONTRIBUTING.md beef-up

src/pages/es/core-concepts/astro-components.md, src/pages/es/core-concepts/framework-components.md, src/pages/es/core-concepts/project-structure.md, src/pages/es/core-concepts/routing.md, src/pages/es/editor-setup.md, src/pages/es/getting-started.md, src/pages/es/guides/data-fetching.md, src/pages/es/guides/environment-variables.md, src/pages/es/guides/imports.md, src/pages/es/guides/markdown-content.md, src/pages/es/install/auto.md, src/pages/es/integrations/integrations.md
- Update `core-concepts/astro-components.md`
- Update `core-concepts/framework-components.md`
- Update `core-concepts/project-structure.md`
- Update `core-concepts/routing.md`
- Update `editor-setup.md`
- Update `getting-started.md`
- Update `guides/data-fetching.md`
- Update `guides/environment-variables.md`
- Update `guides/imports.md`
- Update `guides/markdown-content.md`
- Update `install/auto.md`
- Update `integrations/integrations.md`
To match with the latest changes in #761 (including previous changes).
=> i18n(es): update pages

src/pages/en/guides/server-side-rendering.md
This PR changes the adding an adapter example import statement from kebab-case to camelCase.
=> Docs: change adapter import from kebab-case to camelCase

src/pages/robots.txt.ts
- What does this PR change? Changes `User-Agent` to `User-agent` in [src/pages/robots.txt.ts](https://github.com/withastro/docs/compare/main...Chrissdroid:user-agent-fix?expand=1#diff-c6abf67041f3fd19ce1c5ba12b5758fa25beacbb8aa25db2ca655bf639e4c431)
Fixes #836
=> fix: Typo for `User-agent`

src/pages/[lang]/404.astro, src/pages/robots.txt.ts
The current 404 page on the docs site fails to redirect to the homepage. This creates a recursive 404 loop and hampers the UX. 
This PR addresses this issue by utilising the `getLanguageFromURL()` function to identify the correct locale and redirect to the appropriate homepage (with that locale). 
No visual changes have been made in this PR.
=> Fix recursive 404

src/pages/pt-br/core-concepts/framework-components.md
Updated PT-BR `framework-components.md` page based on #824 changes.
=> i18n(pt-BR): Update `framework-components.md` based on #824 changes.

src/pages/fr/core-concepts/project-structure.md
- What does this PR change? Updates content from `src/pages/fr/core-concepts/project-structure.md` to reflect changes from withastro#761
=> i18n(fr): Updating `project-structure` translation

src/pages/fr/core-concepts/routing.md
- What does this PR change? Updates content from `src/pages/fr/core-concepts/routing.md` to reflect changes from withastro#761
=> i18n(fr): Updating `routing` translation

src/pages/fr/editor-setup.md
- What does this PR change? Updates content from `src/pages/fr/editor-setup.md` to reflect changes from withastro#761
=> i18n(fr): Updating `editor-setup` translation

src/pages/fr/getting-started.md
- What does this PR change? Updates content from `src/pages/fr/getting-started.md` to reflect changes from withastro#761
=> i18n(fr): Updating `getting-started` translation

src/pages/en/reference/integrations-reference.md
- Closes #806
- Clarifies the limitations of the `injectScript('page-ssr'...` method
=> Improve `injectScript` documentation

src/pages/zh-cn/guides/aliases.md
=> docs(zh-cn): translate aliases

src/pages/zh-cn/guides/environment-variables.md
=> docs(zh): translate env-var

src/pages/pt-br/guides/aliases.md
Updated PT-BR `aliases.md` page based on #871 changes.
=> Update PT-BR `aliases.md` page based on #871 changes

src/pages/en/migrate.md
- Removes redundant phrases.
- Before:
- After:
=> correct #887: redundant latest / most up-to-date

src/pages/pt-br/reference/integrations-reference.md
Updated PT-BR `integrations-reference.md` page based on #850 changes.
=> i18n(pt-BR): Update `integrations-reference.md` based on #850 changes

src/pages/pt-br/editor-setup.md
Updated PT-BR `editor-setup.md` page based on #831 changes.
=> i18n(pt-BR): Update `editor-setup.md` based on #831 changes

.github/PULL_REQUEST_TEMPLATE.md
- Adds a prompt for an issue number if the PR should close one
- Switches the list to a “Delete any that don’t apply” to get around the “tasks UI” GitHub associates with checklists
=> Improve GitHub PR template

.github/workflows/discord-congrats.yml, scripts/congrats-bot.mjs
- Don’t cancel the congrats bot if two commits overlap
- Improve the message posted to Discord to thank commit co-authors 🥳
=> Thank co-authors in DocsBot messages

src/pages/es/core-concepts/astro-components.md, src/pages/es/core-concepts/astro-pages.md, src/pages/es/core-concepts/layouts.md
- update `astro-components.md` to match with latest changes in #787 
- update `layouts.md` to match with latest changes in #917 
- update `astro-pages.md` to match with latest changes in #895
=> i18n(es): Update `astro-components.md`, `layouts.md` and `astro-pages.md`

src/pages/en/guides/typescript.md
This PR introduces a mention of TypeScript usage for a `astro.config` file within the TypeScript section.
=> Mention Astro config TypeScript usage in TS section

src/pages/ja/core-concepts/astro-pages.md
- Update Japanese `astro-pages.md` https://github.com/withastro/docs/pull/895
=> i18n(ja): Update Japanese `astro-pages.md`

src/pages/en/core-concepts/astro-pages.md
This PR adds the missing period in the sentence "Read more about Routing in Astro"
=> minor: Add missing period to `astro-pages.md`

src/pages/pt-br/migrate.md
Updated PT-BR `migrate.md` page based on #888 changes.
=> i18n(pt-BR): Update `migrate.md` based on #888 changes

src/pages/pt-br/core-concepts/astro-components.md
Updated PT-BR `astro-components.md` based on #787 changes.
=> i18n(pt-BR): Update `astro-components.md` based on #787 changes

src/pages/pt-br/core-concepts/astro-pages.md
Updated PT-BR `astro-pages.md` page based on #895 changes.
=> i18n(pt-BR): Update `astro-pages.md` based on #895 changes

src/pages/pt-br/guides/configuring-astro.md
Updated PT-BR `configuring-astro.md` page based on #931 changes.
=> i18n(pt-BR): Update `configuring-astro.md` based on #931 changes

src/pages/pt-br/reference/configuration-reference.md
Updated PT-BR `configuration-reference.md` page based on #949 changes.
=> i18n(pt-BR): Update `configuration-reference.md` based on #949 changes

src/pages/ja/migrate.md
- Corrected wording to match the updated link. #954
=> i18n(ja): Update Japanese `migrate.md`

src/i18n/README.md
Old link was relative but not to proper location.
=> Update i18n README: link to CONTRIBUTING

src/pages/de/guides/aliases.md
- Updates the German version to incorporate the latest changes to the English page.
=> i18n(de-DE): Update `aliases.md`

src/pages/de/core-concepts/astro-components.md
- Updates German translation to incorporate recent changes to the English page.
=> i18n(de-DE): Update `astro-components.md`

src/pages/de/editor-setup.md
- Updates the German version to incorporate the latest changes to the English page.
=> i18n(de-DE): Update `editor-setup.md`

src/pages/de/reference/configuration-reference.md
- Updates the German version to incorporate recent changes to the English page.
=> i18n(de-DE): Update `configuration-reference.md`

src/pages/de/core-concepts/layouts.md
- Updates the German version to incorporate the latest changes to the English page.
=> i18n(de-DE): Update `layouts.md`

src/pages/en/guides/deploy/netlify.md
- Closes #988 
- Add a note regarding Netlify Functions to our deploy guide. #988 suggested adding this toe the adapter README, but the [original issue](https://discord.com/channels/830184174198718474/995986253784825967/995989611409068042) was raised by someone with a static build, so I thought this might be the best catch-all location. (Maybe we also need to confirm at some point if `netlify/functions` works when you’re using the adapter for SSR Astro itself generates functions. Shouldn’t block this though.)
=> Add note about Netlify functions to deploy guide

src/pages/de/reference/configuration-reference.md
- Adds even more recent changes to the German version of our configuration reference page. Those were added between filing and merging of my previous PR! 😄
=> i18n(de-DE): Add markdown mode to config reference

MAINTAINERS.md
This PR introduces mention of the `.patch` trick to lookup a commit author's name and email.
=> Add mention of patchfile

src/pages/en/guides/typescript.md
I didn't catch this in time for its first merge. After sitting on it, I really would like the word "that" in there!
=> Minor wording change: TypeScript page

src/pages/en/guides/deploy/aws.md
- Add Amplify to AWS deploy guide
=> add aws amplify section to `aws.md`

src/pages/en/core-concepts/routing.md
- was missing async keyword in function, added it
=> Added async keyword to function

src/pages/de/core-concepts/layouts.md, src/pages/de/guides/markdown-content.md, src/pages/de/reference/configuration-reference.md
- Add German translation for `markdown-content.md`.
- Update links from other pages to this page based on the new translated headings.
=> i18n(de-DE): Translate `markdown-content.md`

src/pages/en/guides/markdown-content.md
Document this PR: https://github.com/withastro/astro/pull/3588
=> document 'file' property for markdown templates

src/i18n/pt-br/ui.ts, src/pages/pt-br/core-concepts/routing.md, src/pages/pt-br/guides/aliases.md, src/pages/pt-br/guides/configuring-astro.md, src/pages/pt-br/guides/environment-variables.md, src/pages/pt-br/guides/integrations-guide.md, src/pages/pt-br/guides/markdown-content.md, src/pages/pt-br/guides/server-side-rendering.md, src/pages/pt-br/guides/troubleshooting.md, src/pages/pt-br/guides/typescript.md, src/pages/pt-br/integrations/integrations.md, src/pages/pt-br/migrate.md, src/pages/pt-br/reference/adapter-reference.md, src/pages/pt-br/reference/api-reference.md, src/pages/pt-br/reference/configuration-reference.md, src/pages/pt-br/reference/integrations-reference.md
This PR updates all the PT-BR pages that needed to be updated.
=> i18n(pt-BR): Update PT-BR pages

src/pages/en/editor-setup.md
Adds links and information about using Neovim to develop with Astro!
=> Add Neovim Documentation

src/pages/en/reference/api-reference.md
- Adds docs for the new `Astro.clientAddress` feature in PR: https://github.com/withastro/astro/pull/3973
=> Add docs on Astro.clientAddress

src/pages/de/core-concepts/routing.md
- Adds German translation for `routing.md`.
=> i18n(de-DE): Translate `routing.md`

.github/labeler.yml, .github/workflows/labeler.yml
- Closes #1052
- Adds a labeler action
Note: yolo PR I was not able to test this locally 😅
=> add labeler action

WRITING.md
- Closes #1053
- Update WRITING.md with guidance on the `<Badge />` and `<Since />` components
=> Add guides on using `<Badge />` and `<Since />`

src/pages/zh-cn/guides/aliases.md
=> docs(cn): update aliases

CONTRIBUTING.md
Probably needs editing, but just to get the ball rolling with an explicit note re: triggering (or not!) a translation status updating.
=> [CONTRIBUTING.md] - quick update re: triggering i18n or not

src/pages/ja/guides/aliases.md
- Translated  import aliases page(ja/guides/aliases) into Japanese.
=> i18n(ja): Add Japanese `guides/aliases.md`

src/pages/en/core-concepts/partial-hydration.md
- Fixed a typo.
- "opt-in" is a compound word that requires a hyphen.
=> Fixed typo

src/pages/en/core-concepts/partial-hydration.md
This is a minor, typo PR! Do not disturb Translation status issue!
=> [minor: revert typo fix] partial hydration page

src/pages/zh-cn/guides/imports.md
=> docs(cn): update import

src/pages/zh-cn/guides/environment-variables.md
=> docs(cn): update envvironment variables

src/pages/zh-cn/guides/configuring-astro.md
=> docs(cn): update configuring astro

src/pages/zh-cn/getting-started.md
=> docs(cn): update getting-started

src/pages/zh-cn/core-concepts/routing.md
=> docs(cn): update routing

src/pages/zh-cn/core-concepts/project-structure.md
=> docs(cn): update project structure

MAINTAINERS.md
- Closes #1061 
This PR adds external resources for learning more about accessibility to the Maintainers Manual, my writing isn't the best so please don't spare this PR of suggestions and changes! :raised_hands:
=> Add accessibility guidance to the Maintainers Manual

src/pages/en/guides/deploy/deno.md, src/pages/en/guides/deploy/netlify.md, src/pages/en/guides/deploy/vercel.md, src/pages/en/guides/server-side-rendering.md
- Updates SSR and deploy examples to include the new `output: "server"` Astro config option
=> Adds the new `output` flag to SSR config examples

src/pages/en/concepts/why-astro.md
- Content fixes (broken links, typos, etc.)
- Makes the links in the "Astro is..." list actually work.
=> Add missing fragment links

src/pages/en/guides/configuring-astro.md
- Fixed indentation of some snippets.
=> Add code snippet titles to `configuring-astro.md`

src/pages/en/core-concepts/routing.md
- Removed stray leading slashes from existing file names.
=> Add code snippet titles to `routing.md`

src/pages/en/core-concepts/astro-pages.md
=> Add code snippet titles to `astro-pages.md`

src/pages/en/guides/markdown-content.md
=> Add code snippet titles to `markdown-content.md`

src/pages/en/install/manual.md
- Added a highlighting language to an `astro.config.mjs` and a `robots.txt` snippet. As there is no proper language for `robots.txt`, used `diff` to get at least comment highlighting.
=> Add code snippet titles to `install/manual.md`

src/pages/en/guides/styling.md
- Added missing syntax highlighting language to shell code blocks to get proper terminal styling.
=> Add code snippet titles to `styling.md`

src/pages/en/guides/data-fetching.md
- Completed partial file name with full path.
=> Add code snippet titles to `data-fetching.md`

src/pages/en/guides/environment-variables.md
- Added a `# Supported file names:` line before the list of `.env` file name variants that were previously a bit lost.
=> Add code snippet titles to `environment-variables.md`

src/pages/en/guides/aliases.md
- Removed unnecessary project folder name from existing file paths.
- Fixed a little typo (VSCode -> VS Code) along the way.
=> Add code snippet titles to `aliases.md`

src/pages/en/guides/server-side-rendering.md
=> Add code snippet titles to `server-side-rendering.md`

src/pages/en/guides/typescript.md
=> Add code snippet titles to `typescript.md`

src/pages/en/core-concepts/astro-components.md
=> Add code snippet titles to `astro-components.md`

src/pages/en/core-concepts/framework-components.md
=> Add code snippet titles to `framework-components.md`

src/pages/en/tutorial/2-astro-pages/index.md, src/pages/en/tutorial/3-components/index.md, src/pages/en/tutorial/4-markdown/index.md, src/pages/en/tutorial/5-astro-api/index.md
For @delucis to merge into the `tutorial` branch. Everyone else, just ignore.  😄
=> [chore for Chris] resolve merge conflicts

src/pages/en/guides/deploy.md, src/pages/en/guides/deploy/aws.md, src/pages/en/guides/deploy/buddy.md, src/pages/en/guides/deploy/cloudflare.md, src/pages/en/guides/deploy/deno.md, src/pages/en/guides/deploy/flightcontrol.md, src/pages/en/guides/deploy/github.md, src/pages/en/guides/deploy/gitlab.md, src/pages/en/guides/deploy/google-cloud.md, src/pages/en/guides/deploy/google-firebase.md, src/pages/en/guides/deploy/heroku.md, src/pages/en/guides/deploy/layer-zero.md, src/pages/en/guides/deploy/microsoft-azure.md, src/pages/en/guides/deploy/netlify.md, src/pages/en/guides/deploy/render.md, src/pages/en/guides/deploy/surge.md, src/pages/en/guides/deploy/vercel.md
=> [i18n] deploy pages marked i18n ready

src/pages/en/guides/server-side-rendering.md
Fixed "challange" typo in code example
Fixed a typo in the example code on the server-side rendering page.
=> Fixed typo in server side rendering page

src/pages/en/guides/aliases.md
=> Mark code in `aliases.md`

src/pages/en/guides/environment-variables.md
=> Mark code in `environment-variables.md`

src/pages/en/core-concepts/astro-components.md
=> Mark code in `astro-components.md`

src/pages/en/install/manual.md
=> Mark code in `manual.md`

src/pages/en/concepts/islands.md
=> Mark code in `islands.md`

src/pages/en/core-concepts/astro-pages.md
=> Mark code in `astro-pages.md`

src/pages/en/core-concepts/layouts.md
=> Mark code in `layouts.md`

src/pages/en/guides/typescript.md
=> Mark code in `typescript.md`

src/pages/en/core-concepts/routing.md
=> Mark code in `routing.md`

src/pages/en/guides/markdown-content.md
=> Mark code in `markdown-content.md`

src/pages/en/reference/directives-reference.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18mCifP2FNvSQU6xhgzCJGDXhoGydrYew%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Yq6PLqW)
Adds additional data types that can be serialized when using `define:vars`
- Closes # #717
=> Add Content surrounding serializable values

src/pages/en/guides/server-side-rendering.md
- I also fixed some formatting issues in the code blocks on this one.
=> Mark code in `server-side-rendering.md`

src/pages/en/guides/configuring-astro.md
=> Mark code in `configuring-astro.md`

src/pages/en/guides/styling.md
=> Mark code in `styling.md`

src/pages/en/guides/rss.md
- Closes #1082 
- Update RSS codeblock example to use `post.url` variable
=> rss: change post.frontmatter.slug to post.url

src/pages/en/reference/integrations-reference.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX182PvMq6SruIqYyzi24uFc2ayTi3axzw%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=k0WxZHI)
Fixes Links on integrations page to be pointed internally to the corresponding integrations pages within the docs
- Closes #1183
=> Corrected Links on Integrations Page

src/pages/en/reference/integrations-reference.md
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX13uxjnxKBnhxcMztYx7AOOzNDm2ARdRo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Rxqsvy8)
- Closes  #756 
Re-pointed the import to the correct location
=> Nit: Updated import statement with correct point

src/pages/es/core-concepts/astro-pages.md
- Update `astro-pages.md` to match #1169
=> i18n(es): update astro-pages

src/pages/en/guides/markdown-content.md
Proposing we change `regular` to `standard` when comparing .md vs .mdx.
Based on the discussion had on discord
- Changes the reference terminology used.
=> Improved Markdown description

src/pages/en/guides/markdown-content.md
Added a `:::note` to the main markdown page linking to the MDX config section.
=> Add note about MDX configuration

src/i18n/es/nav.ts, src/pages/es/reference/integrations-reference.md
- merge this before Sarah figures this out 😇
=> i18n(es): `integrations-reference.md`

src/pages/en/guides/imports.md
- ~~Closes #~~ (Should not close the issue yet, but references #1154)
- The PR makes changes to the [other assets](https://docs.astro.build/en/guides/imports/#other-assets) section of the docs. In order to improve on the promotion of accessibility, I added an alt attribute to the image tag and then added a small note underneath to encourage its use
=> Added alt attribute to <img> tag and added note

src/pages/en/guides/images.md
=> Fix typo on `images.md`

src/pages/en/guides/deploy/github.md
- Update GitHub Pages deployment to use the official [`withastro/action`](https://github.com/withastro/action) GitHub Action
=> Update GitHub Action deploy steps

src/pages/en/reference/api-reference.md
- Adds `Astro.generator` to API Reference
- Follows https://github.com/withastro/astro/pull/4012
=> Add `Astro.generator` to API reference

src/pages/en/core-concepts/astro-components.md
- Closes #1180
This just adds a note to the Astro components page for dynamic HTML tags. I wasn't sure about the positioning of it, but it seemed like it made the most sense in the dynamic HTML section.
=> Add note on dynamic HTML tags

src/pages/en/core-concepts/sharing-state.md
Add FAQ: "Can I use Nano Stores in `.astro` files or other serverside components?"
=> "Can I use Nano Stores in `.astro` files?"

src/pages/en/guides/troubleshooting.md
- Closes #1239
Fixed a typo in the troubleshoot section of the docs. Removed an unwanted "is".
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix
=> Fixed: Typo in Troubleshoot section

src/pages/en/guides/data-fetching.md
=> Correct code sample title in data fetching page

src/i18n/fr/README.md
- Just fixed some French spelling mistakes
=> i18n(fr): Fix typo

WRITING.md
This does NOT yet do Hippo justice, but I wanted something very quick and simple to start that addresses the majority of our casual contributors' use cases. There are "lies of ommission" and simplifications because as a public-facing document, it is better that it be clear and not overwhelming than exhaustively comprehensive.
To start, just wanted to document:
- adding a filename as a title (either as attribute or within the code sample)
- entire line highlighting via curly braces (default, or +/- "diff" style)
- text highlighting (change in background color) via quotation marks or via regular expressions within slashes (nothing fancy shown!)
I'll be adding to this, and comments/suggestions/additions are also welcome! I *think* this organization makes sense …
=> [WRITING] code authoring syntax

src/i18n/es/nav.ts, src/pages/es/guides/images.md
=> i18n(es): translate images guide

src/pages/en/migrate.md
- What does this PR change? Set the correct markdown component name in the migration guide.
=> [migration guide] fix markdown component name

src/pages/es/core-concepts/framework-components.md
- Update `framework-components.md` #1272
=> i18n(es): update framework components

src/pages/es/core-concepts/layouts.md
=> i18n(es): update layouts

src/pages/es/core-concepts/astro-components.md
- updated content
- update `astro-components.md` #1253
=> i18n(es): update astro-components

src/pages/es/core-concepts/routing.md
=> i18n(es): update routing

src/pages/ja/getting-started.md
- Updated Japanese `getting-started.md` to match the English update
- https://github.com/withastro/docs/commit/2ec991dbf46a37f5fb181760dba8f2ac6d5504c2
- https://github.com/withastro/docs/commit/1e417f16d1517da0fc649e6037b28d987765627d
=> i18n(ja): Update Japanese `getting-started.md`

src/pages/es/editor-setup.md
- Update `editor-setup.md` #1235
=> i18n(es): update editor-setup

src/pages/en/concepts/mpa-vs-spa.md
This PR adds a small note explaining why MPAs have better accessibility than SPAs.
=> Note explaining why MPAs are more accessible

scripts/github-translation-status.mjs
Officialise our Arabic language support by enabling tracking of translations in #438
=> Track Arabic translations!

src/i18n/de/nav.ts, src/pages/de/concepts/islands.md
Create and localise /de/concepts/islands.md.
- Create and localise /de/concepts/islands.md.
- Checked with pnpm dev
=> i18n(de-DE): Translate `concepts/islands.md`

src/components/HeadCommon.astro
- Migrates from GTM to Fathom Analytics.  This is the same GDPR-compliant analytics tool used on the new astro.build site
Bonus: using the same Fathom project allows us to properly track users moving between the landing page and docs site all while respecting user privacy and international requirements 🚀
=> Migrating to Fathom Analytics

src/pages/de/core-concepts/layouts.md
- Updates German translation to match the current English version of the page.
=> i18n(de): Update `core-concepts/layouts.md`

src/pages/de/core-concepts/astro-pages.md
- Updates German translation to match the current English version of the page.
=> i18n(de): Update `core-concepts/astro-pages.md`

src/pages/de/guides/configuring-astro.md, src/pages/de/reference/configuration-reference.md
Add german translation for guides/configuring-astro.md
=> i18n(de): Update guides/configuring-astro.md

src/pages/de/core-concepts/routing.md
- Updates German translation to match the current English version of the page.
=> i18n(de): Update `core-concepts/routing.md`

src/pages/de/guides/data-fetching.md
Add german translation for guides/data-fetching
=> i18n(de): Add translation for data-fetching.md

src/pages/de/guides/deploy.md
The PR merges the full translated content of the deploy overview page in german.
=> i18n(de): adding deploy overview page

src/pages/es/guides/deploy/github.md
=> i18n(es): add github pages

src/pages/de/guides/rss.md
Add translation for guides/rss.md
=> i18n(de): Add guides/rss translation

src/i18n/de/README.md
- Adds first version of our German i18n guide for translators. Only visible in the GitHub repo.
=> Add first version of German i18n guide

src/pages/en/core-concepts/astro-components.md
Closing `</p>` tags so Shiki doesn't make weird highlighting choices!
=> Fix code sample on `astro-components.md`

src/pages/de/getting-started.md
- Updates the German page with the latest changes made to the English version.
=> i18n(de): Update `getting-started.md`

src/i18n/de/nav.ts, src/pages/de/concepts/why-astro.md
Adding a german translation for concepts/why-astro
=> i18n(de): Added german translation for concepts/why-astro 

src/pages/es/guides/deploy/layer-zero.md
- What does this PR change?  Adds Layer0 deploy guide in Spanish
=> i18n(es): add layer0

src/pages/es/guides/deploy/microsoft-azure.md
- What does this PR change?  Adds Microsoft Azure deploy guide in Spanish
=> i18n(es): add microsoft azure

src/pages/es/guides/deploy/render.md
=> i18n(es): add render

src/pages/es/guides/deploy/flightcontrol.md
- Adds `flightcontrol.md` in spanish
=> i18n(es): add flightcontrol

src/pages/es/guides/deploy/heroku.md
=> i18n(es): add heroku guide

src/i18n/de/nav.ts, src/pages/de/concepts/mpa-vs-spa.md, src/pages/de/concepts/why-astro.md
Translated `concepts/mpa-vs-spa` into german
=> i18n(de): Translated concepts/mpa-vs-spa into german

src/pages/es/guides/deploy.md
=> i18n(es): Update deploy.md

WRITING.md
- ~~Closes #~~ Closes no open issues.
The last bullet point under **Text Highlighting** had a closing bracket at the end and no opening bracket.
=> docs: removed single closing parentheses.

src/pages/es/guides/deploy/deno.md
=> i18n(es): add deno guide

src/pages/en/core-concepts/layouts.md
Fix the incorrect import path in code snippets
=> Fix the incorrect import path in code snippets

src/pages/es/guides/deploy.md, src/pages/es/guides/typescript.md, src/pages/es/install/auto.md, src/pages/es/install/manual.md, src/pages/es/integrations/integrations.md, src/pages/es/reference/api-reference.md, src/pages/es/reference/configuration-reference.md
Puts the remaining files up to date, in spanish:
- guides/typescript.md
- install/auto.md
- install/manual.md
- integrations/integrations.md
- reference/api-reference.md
- reference/configuration-reference.md
=> i18n(es): Update remaining files

src/pages/en/reference/api-reference.md
Close https://github.com/withastro/astro/issues/4361
Note that search parameters are not available in SSG, but available in SSR
=> Note Astro.request.url search parameters

src/pages/en/guides/server-side-rendering.md
Adds a missing `await` in the documentation code sample.
=> docs: add missing await

CONTRIBUTING.md
Add links to the `MAINTAINERS.md` and `SUPPORTSQUAD.md` manuals inside `CONTRIBUTING.md`
=> Update `CONTRIBUTING.md` with new manuals links

src/pages/es/concepts/mpa-vs-spa.md, src/pages/es/core-concepts/astro-components.md, src/pages/es/core-concepts/layouts.md, src/pages/es/guides/markdown-content.md, src/pages/es/guides/typescript.md
Updates Spanish docs to match latest changes
=> i18n(es): update content

src/pages/en/core-concepts/routing.md
This is an update for the following conversation: https://github.com/withastro/docs/pull/1256
Couldn't update my initial PR, because I've deleted my fork.
=> How to create an index.html at root level via getStaticPaths()

src/pages/en/reference/directives-reference.md
The `.mdx` page already mentions that this is supported, but I figured it was worth mentioning it in the directives page since it currently just says directives are supported in `.astro` files which misled me.
=> Mention that directives are supported in .mdx

src/pages/en/core-concepts/framework-components.md
=> Update UI Frameworks docs to include `alpineJS` integration

src/pages/es/guides/deploy/cloudflare.md
=> i18n(es): add cloudflare guide

src/pages/en/guides/images.md, src/pages/en/guides/integrations-guide/image.md
- Adds docs for changes of https://github.com/withastro/astro/pull/4511
- Also see https://github.com/withastro/astro/issues/4291
=> docs(image): add note about error if alt is missing

src/pages/en/core-concepts/framework-components.md, src/pages/es/guides/images.md
- Added caution note regarding alt text
=> i18n(es): update image.md

src/pages/en/guides/styling.md
=> Fix links to vite noExternal option

src/pages/en/guides/images.md
=> Typo in filename

src/pages/en/guides/imports.md
- Comment references a presumably outdated value of the variable
- This PR brings the comment in line with the variable names
=> minor: Fix variable reference in comment

TRANSLATING.md
Added some more content to the i18n guide, now covering components and asides. As always, feel free to improve my horrible writing 😅
=> Add components and asides guidance to `TRANSLATING.md`

src/pages/en/migrate.md
- Closes #1419
- The migration page documents what you might run into while upgrading Astro. Now it also describes _how_ to upgrade Astro!
=> Include upgrade commands on migrate page

src/pages/es/reference/api-reference.md
Updates the api-reference page to have the latest copy about a note related to options that modifies the `Astro.request.url` object
=> i18n(es): update api-reference.md

src/pages/pt-br/guides/deploy/buddy.md
- Closes # 
- What does this PR change? Translation buddy.md from English to pt-br.
- Did you change something visual? No.
=> i18n(pt-br): Create buddy.md

src/i18n/es/nav.ts, src/pages/es/core-concepts/framework-components.md, src/pages/es/guides/markdown-content.md
- Changes the title of the page
=> i18n(es): update framework-components title

src/pages/es/core-concepts/project-structure.md
- Update with [these changes](https://github.com/withastro/docs/commits/main/src/pages/en/core-concepts/project-structure.md?since=2022-06-20T19:19:22.000Z)
=> i18n(es): update project-structure

src/pages/es/concepts/mpa-vs-spa.md
- Update with [these changes](https://github.com/withastro/docs/commit/ed7b6dc67d91bc82112ea75056f46c1b96be2331)
=> i18n(es):  update mpa-vs-spa

src/pages/es/guides/data-fetching.md
- Update with [these changes](https://github.com/withastro/docs/commit/1330eaf2c8149b4b6fe3399ce3fe2e3c4a2fa9fd)
=> i18n(es): update `data fetching` page

src/pages/es/guides/images.md
- Keeping up to date the page with the English content
- Rephrasing several paragraphs on the page for more clear context.
=> i18n(es): update the images guide.

src/pages/en/guides/deploy/cloudflare.md
=> A very minor typofix (min{m,}imum)

README.md
Changes the description of what Astro is in the README, because I don't think "site builder" is accurate (makes me think of wix, squarespace, weebly, etc). I swapped it out with the description from the [main repo](https://github.com/withastro/astro), but I'm not certain that's the best option. Happy to hear other suggestions too :) And if you think "site builder" is fine I'm happy to close the PR as well.
=> Clarify what Astro is in the README

src/pages/es/guides/integrations-guide.md
-  Update with [these changes](https://github.com/withastro/docs/commit/a1e16efe72a5e0579cf6b3a398c7be6b15ee8019)
=> i18n(es): update `integrations guide` page

src/pages/es/guides/publish-to-npm.md
- Update with [these changes](https://github.com/withastro/docs/commit/62470c5bdc9bb714a350c27a64152d9d42062750).
=> Update `publish to npm` page

src/pages/es/guides/rss.md
-  Update with [these changes](https://github.com/withastro/docs/commit/a1e16efe72a5e0579cf6b3a398c7be6b15ee8019)
=> i18n(es): update `rss` page

src/pages/es/guides/deploy/aws.md
- Adds AWS deploy page in spanish
=> i18n(es): add aws page 

src/pages/es/guides/styling.md
-  Update with [these changes](https://github.com/withastro/docs/commit/b26a057f415f5f0e005b078057a293e5d17470b8)
=> i18n(es): update `styling` page

public/index.css, public/theme.css, src/components/DeployGuidesNav.astro, src/components/IslandsDiagram.astro, src/components/LeftSidebar/LeftSidebar.astro, src/components/LeftSidebar/SidebarContent.astro, src/components/RightSidebar/CommunityMenu.astro, src/components/RightSidebar/RightSidebar.astro, src/components/RightSidebar/TableOfContents.css
- This PR tweaks the design of our sidebars following some recent discussion
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img alt="" src="https://user-images.githubusercontent.com/357379/189190604-9580f689-e7c3-47d7-8efe-771f390c8705.png">
<td><img alt="" src="https://user-images.githubusercontent.com/357379/189190682-705ca778-adaf-4270-89cb-741545512749.png">
</table>
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img alt="" src="https://user-images.githubusercontent.com/357379/189191141-56b2e2e4-a7f0-4708-b09e-e2c9f3c839b3.png">
<td><img alt="" src="https://user-images.githubusercontent.com/357379/189191138-d370558e-b204-4f74-aecf-d4f5aa15a115.png">
</table>
=> Small sidebar design refresh

src/pages/es/install/auto.md
-  Update with [these changes](https://github.com/withastro/docs/commit/a1e16efe72a5e0579cf6b3a398c7be6b15ee8019)
=> i18n(es): update `auto` page

src/pages/es/install/manual.md
-  Update with [these changes](https://github.com/withastro/docs/commits/main/src/pages/en/install/manual.md?since=2022-08-24T23:34:17.000Z)
=> i18n(es): update `manual` page

src/pages/es/guides/server-side-rendering.md
-  Update with [these changes](https://github.com/withastro/docs/commits/main/src/pages/en/guides/server-side-rendering.md?since=2022-08-22T23:11:59.000Z)
=> i18n(es): update `server side rendering` page

MAINTAINERS.md
This PR adds instructions on how to manually update the Translation Status Overview Issue.
=> Add how to manually update the Translation Status Overview Issue

src/pages/en/guides/typescript.md
Add some information about our new tsconfig.json bases that users should extend from instead of writing their own
=> Add information about TypeScript templates

src/pages/en/guides/fonts.md
- Add Fonts guide to pages ready for translation
a.k.a. desperately try to slow down the Spanish-language translators
=> minor: Mark fonts guide as ready for translation

src/pages/en/core-concepts/sharing-state.md, src/pages/zh-cn/core-concepts/sharing-state.md
- Minor content fixes:  path label change
- change from "clientStore" -> "src/cartStore" to match source code
Updated all language md file found.
=> Update: sharing-state.md.  Fix ref(s) for "cartStore" in code example

src/pages/en/install/auto.md
Remove redundant sentences from the `pnpm run dev` and `yarn run dev` code blocks.
=> Minor fix the `en/install/auto.md` .

src/pages/es/core-concepts/routing.md
-  Update with [these changes](https://github.com/withastro/docs/commit/bdd67f186fa39e0159840ca995722b409b7b3af5)
=> i18n(es): update `core-concepts/routing` page

src/pages/en/reference/integrations-reference.md
This PR changes a typo in the code snippet. 
```diff
- fs.writeFile()
+ writeFile()
```
=> Fix typo in the integration guide code snippets

src/i18n/fr/README.md
Fix some typos in the i18n(fr) README
=> i18n(fr): Fix typos on README

src/pages/en/guides/data-fetching.md
Destructure catalogue from data returned from catalogueApi
- Closes # 
=> typo: Update catalogueApi query

src/pages/es/guides/typescript.md
- Keeping up to date the page with the English content
- Rephrasing several paragraphs on the page for more clear context
=>  i18n(es): update the TypeScript guide.

src/pages/pt-br/concepts/mpa-vs-spa.md
Updated PT-BR `mpa-vs-spa.md` page. Yup, we have gone full circle, now I get to translate my own writing...
=> i18n(pt-BR): Update `mpa-vs-spa.md` translation

src/pages/en/core-concepts/sharing-state.md
This one has been battle-tested enough. Details! In Asides! Tabs and looping video... what more could our translators ask for??
=> [i18nReady] Sharing State

src/i18n/es/nav.ts, src/pages/es/guides/fonts.md
- Adds the `migrate.md` spanish translation
=> i18n(es): add fonts.md

src/pages/zh-cn/reference/integrations-reference.md
update `integrations-reference`
=> docs(zh-cn): update `integrations-reference`

src/pages/es/guides/server-side-rendering.md
- Updates the server-side-rendering page to have the latest copy about what it is need it to enable SSR
=> i18n(es): update server-side-rendering.md

src/pages/en/guides/troubleshooting.md
- Adds a workaround for [#4220](https://github.com/withastro/astro/issues/4220). To be removed when that is fixed!
=> Troubleshooting: Invalid hook call

src/i18n/es/nav.ts, src/pages/es/core-concepts/sharing-state.md
- Adds `sharing-state.md` in spanish
=> i18n(es): add sharing-state.md

src/pages/es/getting-started.md
- Update `es/getting-started.md` to match the source English content by removing excess information and update the heading levels where needed.
=> i18n(es): update `getting-started`

src/pages/es/core-concepts/astro-components.md, src/pages/es/guides/imports.md, src/pages/es/guides/styling.md, src/pages/es/guides/troubleshooting.md, src/pages/es/guides/typescript.md
Update the translated content on the `/es/.../astro-components.md` to the latest.
=> i18n(es): update the `astro-components.md` page.

src/pages/es/concepts/why-astro.md
Update the translated content on the /es/.../why-astro.md to have the latest one.
=> i18n(es): update the why-astro.md page.

src/pages/es/getting-started.md, src/pages/es/reference/cli-reference.md
Update the Spanish translation for `cli-reference.md` to match the English source material.
=> i18n(es): update the `cli-reference.md` translation

src/pages/zh-cn/reference/directives-reference.md
=> docs(zh-cn): update directives-refernence

src/pages/zh-cn/reference/adapter-reference.md
=> docs(zh-cn): update adapter-reference

src/pages/en/guides/publish-to-npm.md
Looks like commands were copied from https://github.com/withastro/docs/blob/62470c5/src/pages/en/guides/publish-to-npm.md?plain=1#L22-L29 & only the first command (for npm) was changed from `my-new-component-directory` to `demo`, all 3 should say `demo`.
=> Creating a package: fix commands (minor)

src/components/Header/HeaderButton.css, src/components/Header/LanguageSelect.css, src/components/Header/Search.astro
Made the search bar pilled shaped and larger, made the language select shorter and truncated. Swapped out the backgrounds between the two.
Fixes (small) part of #618 
| --- | --- |
| ![](https://user-images.githubusercontent.com/9084735/190931793-248e39d4-ff5e-4d9d-b7c8-301be972745f.png) | ![](https://user-images.githubusercontent.com/9084735/190931779-aee1bd5c-9e09-4f4b-a7fe-de369c703d76.png) |
=> Make search input more noticeable

src/pages/zh-cn/reference/configuration-reference.md
update configuration-reference
=> docs(zh-cn): update configuration-reference

src/pages/zh-cn/reference/api-reference.md
=> docs(zh-cn): update api reference

src/pages/zh-cn/core-concepts/astro-components.md, src/pages/zh-cn/guides/imports.md, src/pages/zh-cn/guides/styling.md, src/pages/zh-cn/guides/troubleshooting.md, src/pages/zh-cn/guides/typescript.md
=> docs(zh-cn): update astro-components

src/pages/zh-cn/core-concepts/layouts.md
=> docs(zh-cn): update layouts

src/pages/zh-cn/core-concepts/project-structure.md
=> docs(zh-cn): update project-structure

src/pages/zh-cn/core-concepts/framework-components.md
=> docs(zh-cn): update framework- components

src/pages/es/core-concepts/astro-components.md, src/pages/es/core-concepts/astro-pages.md, src/pages/es/core-concepts/framework-components.md, src/pages/es/core-concepts/layouts.md, src/pages/es/guides/configuring-astro.md, src/pages/es/guides/environment-variables.md, src/pages/es/guides/rss.md, src/pages/es/reference/integrations-reference.md
- update `core-concepts/astro-components.md` to match #1538 
- update `reference/integrations-reference.md` to match #1580
- update `core-concepts/framework-components` to match #1510
- update `core-concepts/layouts` to match #1510
- update `guides/configuring-astro` to match #1567
- update `core-concepts/astro-pages` to match #1538
- update `guides/environment-variables` to match #1567
- update `guides/rss` to match #1538
=> i18n(es): update multiple pages

src/pages/es/reference/integrations-reference.md
- Updates reference/directives-reference to match #1572
=> i18n(es): update the `integrations-reference` page.

src/pages/es/reference/directives-reference.md
- Updates `reference/directives-reference` to match #1568
=> i18n(es): update the `directives-reference` page.

src/pages/es/guides/publish-to-npm.md
replace my-new-component-directory with demo
- What does this PR change? replace my-new-component-directory with demo to reference multiple packages
=> i18n(es): Update guides/publish-to-npm

src/pages/es/install/auto.md
deleted 2 comments on the code that starts at line ~72 
- What does this PR change? deleted comments (create new project with pnmp + create new project with yarn)
=> i18n(es): Update auto.md

src/i18n/es/nav.ts, src/pages/es/guides/aliases.md, src/pages/es/guides/typescript.md
- Minor content fixes (typos)
- Change the title from "Aliases" to "Alias". The plural of "alias" is also "alias".
- Change "aliases" from nav
- Change "aliases" from typescript page
=> i18n(es): Update of aliases and typescript pages.

netlify.toml
- Fixes the link to https://docs.astro.build/core-concepts/component-hydration/ with a redirect
=> Redirect to the updated component hydration docs

.github/PULL_REQUEST_TEMPLATE.md, .github/hacktoberfest.md, .github/labeler.yml
=> Set up Hacktoberfest infrastructure

src/pages/es/install/manual.md
- What does this PR change? adds create tsconfig.json section and updates the file structure at section 7
=> i18n(es): Update install/manual

src/pages/zh-tw/core-concepts/layouts.md
- Add `src/pages/zh-tw/core-concepts/layouts.md` translation
=> i18n(zh-tw) Add `layouts.md` translation

README.md
Just adds a link to the Hacktoberfest guide to the README so it's easier to point people to (and make a video about!)
=> Add Hacktoberfest to the README

src/pages/es/guides/typescript.md
Update the translation on the typescript guide to match the English source material as close as possible.
=> i18n(es): update `typescript.md`

src/i18n/de/README.md
Introducing a paragraph for handling overloaded terms of complex semantics.
The proposed instruction should clarify why adapting some untranslated terminology
leads to better readability and reduced cognitive load.
=> i18n(de): add instructions for handling overloaded terms

src/pages/zh-cn/concepts/mpa-vs-spa.md
- Add mpa-vs-spa.md translation
=> i18n(zh-cn): Add mpa-vs-spa.md translation

TRANSLATING.md
=> Link to Hacktoberfest guide at the top of TRANSLATING.md

.github/labeler.yml
This labeler is more trouble than it’s worth :knife:
=> Don’t auto-label Hacktoberfest PRs

README.md
Will also help us remember to remove it!  😅
=> Call more attention to README Hacktoberfest link

src/pages/es/core-concepts/astro-components.md, src/pages/es/guides/typescript.md
- What does this PR change? delete reference of exporting Props when using TypeScript + small change on typescript.md (everything else seems to be updated on that file)
`hackoberfest-accepted`
=> i18n(es): Update astro components

src/pages/es/core-concepts/sharing-state.md
- Relates to https://github.com/withastro/docs/issues/438
- Update translation for `src/pages/en/core-concepts/sharing-state.md`
🙏🏽 <kbd>hacktoberfest-accepted</kbd>
=> i18n(es): Update sharing-state.md translation

src/pages/en/reference/api-reference.md
- Fix md links syntax of astrocookie docs section
=> docs: Fix md links of astrocookies

src/pages/es/guides/styling.md
- What does this PR change? Translated content for latest updated on #1648 
Please label for `hacktoberfest-accepted`.
=> i18n(es): update translation for `styling.md`

src/pages/pt-br/guides/deploy/netlify.md, src/pages/pt-br/reference/configuration-reference.md
Add pt-BR [`deploy/netlify.md`](https://docs.astro.build/en/guides/deploy/netlify/) translation.
I'm participating in Hacktoberfest, so if PR is ok, I'd like it to be labeled as `hacktoberfest-accepted`.
=> i18n(pt-BR): Add `deploy/netlify.md` translation

src/pages/en/reference/cli-reference.md
=> revert `###` to `<h3>` 😇

src/pages/es/guides/integrations-guide.md
- What does this PR change? Made a few changes to the previous translation of `integrations-guide.md`.
Please labeled this PR with `hacktoberfest-accepted`.
=> i18n(es): update `integrations-guide.md`

src/pages/es/reference/integrations-reference.md
- Updates some missing lines on `integrations-reference.md` so it mirrors the `en` file
Please label for hacktoberfest 🎃 👻
=> i18n(es): update `integrations-reference.md`

src/pages/en/guides/typescript.md
- Closes #1482
- Explains that TypeScript helps prevent errors, motivating the Component Props section later on
- Clarifies that the VSCode extension gives you type hints whether or not you write TypeScript
- Clarifies that Astro always treats your component code as TypeScript, even. if you leave out a `tsconfig.json`
=> Revise and elaborate TypeScript intro

src/components/ContributorList.astro
ContributorList: Save cellular data and improve load time by specifying image size in URL
| ---    | ---   |
| ![image](https://user-images.githubusercontent.com/37726261/193602322-79fb4c48-80de-486b-937f-7a98a4caf1f1.png) | ![image](https://user-images.githubusercontent.com/37726261/193602437-2016eebd-2929-4532-8d89-274155ff2ae4.png) |
I'm participating in Hacktoberfest, so if PR is ok, I'd like it to be labeled as hacktoberfest-accepted.
=> perf(ContributorList): save cellular data and improve load time by specifying image size in URL

src/pages/es/guides/troubleshooting.md
remove hook troubleshooting entry
- What does this PR change? delete invalid hook call section
`hacktoberfest-accepted`
=> i18n(es): Update guides/troubleshooting

src/pages/es/guides/deploy/gitlab.md
- What does this PR change? Give us a brief description. Updates GitLab guide with #1693
=> i18n(es): improve gitlab deploy documentation

src/pages/es/getting-started.md
- Added missing punctuation marks
- Minimal fixes
Please label this PR with `hacktoberfest-accepted` if get approved. 🎃
=> i18n(es): update `getting-started.md`

src/pages/en/guides/deploy/github.md
- Closes #1714 
- This PR adds documentation about the optional arguments that the withastro/action github action can take
- I'd like the `hacktoberfest-accepted` tag to be added to this PR
=> Document Astro GitHub Action inputs

src/pages/pt-br/core-concepts/astro-components.md
=> i18n(pt-BR): Fix typo `astro-components.md`

src/pages/en/guides/content.md
I'm not confident about this page, but it serves as a kind of NWTWWHB hub to show people that content is a focus. As we get the tutorial and CMS guides in, I think it will come into its own, and we can focus on linking out to examples.
=> Revising the content page

src/pages/es/reference/configuration-reference.md
- What does this PR change? Small fixes to `configuration-reference.md`
Please label this as `hacktoberfest-accepted`
=> i18n(es): update to `configuration-reference`

src/pages/en/guides/deploy/deno.md
Fixes a typo in the npm deploy script to match with command given later on in the docs
=> consistent deno deploy script

.github/hacktoberfest.md
Add hacktoberfest reviewer to the list
=> add hacktoberfest reviewer

src/pages/pt-br/guides/deploy/vercel.md, src/pages/pt-br/reference/configuration-reference.md
Add pt-BR [deploy/vercel.md](https://docs.astro.build/en/guides/deploy/vercel/) translation.
I'm participating in Hacktoberfest, so if PR is ok, I'd like it to be labeled as hacktoberfest-accepted.
=> i18n(pt-BR): Add deploy/vercel.md translation

src/pages/es/getting-started.md
- What does this PR change? Updated `getting-started.md` based on this commit https://github.com/withastro/docs/commit/d1bb8830e2715701e7d0fe52bc0105058898ac26
Please label this as `hacktoberfest-accepted`
=> i18n(es): update to `getting started`

TRANSLATING.md
Fixed a couple of broken links that I spotted whilst reading the guide.
P.s. I'm participating in Hacktoberfest and speak English & Spanish. Would be happy to help out with some translations, or reviewing PRs of Spanish translations 🙂
=> fix: broken TRANSLATING guide links

src/pages/en/core-concepts/layouts.md
- Closes #1781
Improvements in markdown layouts example.
before:
Now:
And, i am taking part in hacktoberfest!!
=> docs: improvements for layouts page

src/pages/es/guides/deploy/deno.md
- Updates `deploy/deno.md` guide in spanish.
Please add hacktoberfest label 🎃
=> i18n(es): Update `deploy/deno.md`

TRANSLATING.md
More content to `TRANSLATING.md`! New section explaining our minimum quality standards and a new Translation Tip about what is a good or bad adaptation.
=> [i18n Guide] Add minimum quality standards and good/bad adaptation

src/pages/en/comparing-astro-vs-other-tools.md, src/pages/en/guides/deploy.md, src/pages/en/guides/markdown-content.md, src/pages/en/guides/rss.md, src/pages/en/guides/server-side-rendering.md, src/pages/en/reference/adapter-reference.md
Found some places where various "adaptor" related resources could be better connected to one another.
* Added a link from [reference/adapter-reference](https://docs.astro.build/en/reference/adapter-reference/) to the [SSR guide](https://docs.astro.build/en/guides/server-side-rendering/), as there was otherwise no convenient path from `reference/adapter-reference` to other adapter docs.
* Added some new headers to [guides/server-side-rendering](https://docs.astro.build/en/guides/server-side-rendering/), in part so I could link directly to `#adding-an-adapter`, but also because I think it will scan better / more useful TOC in the sidebar.
Also:
- Founds some links that needed hashes
- Changed a few hashes
Preview …
=> Better "Adaptor" links

src/pages/en/reference/integrations-reference.md
Add missing comma in code example in `astro:server:setup` `server` option code example
Minor change but I'm taking part in Hacktoberfest anyway if possible😅
=> docs: add missing comma in code example

src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/0-introduction/index.md, src/pages/en/tutorial/1-setup/index.md, src/pages/en/tutorial/2-pages/index.md, src/pages/en/tutorial/3-components/index.md, src/pages/en/tutorial/4-layouts/index.md, src/pages/en/tutorial/5-astro-api/index.md, src/pages/en/tutorial/6-islands/index.md
Choosing a structure for the x.0 "Check In" pages that works both in the navigation sidebar and for social images.
=> [tutorial] updated page titles and descriptions for unit check ins

src/pages/en/guides/deploy/vercel.md, src/pages/es/guides/deploy/vercel.md, src/pages/pt-br/guides/deploy/vercel.md
- JSON example included a trailing comma which is invalid syntax
=> Fix JSON syntax typo in Vercel deploy guide

src/pages/en/tutorial/3-components/index.md
=> Fix unit number in title

src/pages/en/tutorial/1-setup/1.md
- Removes a “Test your knowledge” box in the tutorial that was empty
=> Remove empty test your knowledge box

src/pages/en/core-concepts/endpoints.md
Very minor fix.
Before:
```js
export async function get({ params, request }) => {
// ...                                         ^^
// no closing `}`
```
After:
```js
export async function get({ params, request }) {
// ...
}
```
=> Fix example

src/pages/en/core-concepts/endpoints.md
```` ```js ```` --> ```` ```ts ````
Super minor, ran cross these while working on another change.
=> Code block language fixes

src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/0-introduction/index.md, src/pages/en/tutorial/1-setup/3.md, src/pages/en/tutorial/1-setup/5.md
- Fix a few links within the tutorial (probably leftover from when there were fewer steps?)
- Two grammar fixes / changes
=> Tutorial: fix a few links within the tutorial, typos / grammer

src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/1-setup/2.md, src/pages/en/tutorial/4-layouts/1.md, src/pages/en/tutorial/stackblitz.md
=> Missing word; spelling

src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/1-setup/4.md, src/pages/en/tutorial/1-setup/5.md, src/pages/en/tutorial/1-setup/6.md, src/pages/en/tutorial/2-pages/1.md, src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/2-pages/5.md, src/pages/en/tutorial/5-astro-api/4.md, src/pages/en/tutorial/6-islands/2.md, src/pages/en/tutorial/stackblitz.md
Many of these were found using https://github.com/tbroadley/spellchecker-cli (disclaimer: this just popped up in a Google search and I decided to give it a whirl):
```sh
pnpm install --global spellchecker-cli
cd src/pages/en/tutorial
spellchecker --ignore 'PreCheck' 'StackBlitz' 'Netlify' 'Astro' "Astro's" 'repo' 'RSS' 'dev' 'UI' 'MultipleChoice' 'frontmatter' 'unitTitle' 'Preact' 'templating' 'YAML' 'JSX' 'stylesheet' '&nbsp' --files '**/*.md'
```
=> Tutorial: more spelling fixes

src/pages/en/tutorial/0-introduction/index.md, src/pages/en/tutorial/1-setup/1.md, src/pages/en/tutorial/1-setup/2.md, src/pages/en/tutorial/1-setup/3.md, src/pages/en/tutorial/1-setup/4.md, src/pages/en/tutorial/1-setup/5.md, src/pages/en/tutorial/1-setup/6.md, src/pages/en/tutorial/2-pages/1.md, src/pages/en/tutorial/2-pages/2.md, src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/2-pages/5.md, src/pages/en/tutorial/2-pages/index.md, src/pages/en/tutorial/3-components/1.md, src/pages/en/tutorial/3-components/3.md, src/pages/en/tutorial/3-components/4.md, src/pages/en/tutorial/3-components/index.md, src/pages/en/tutorial/4-layouts/1.md, src/pages/en/tutorial/4-layouts/index.md, src/pages/en/tutorial/6-islands/1.md, src/pages/en/tutorial/6-islands/2.md, src/pages/en/tutorial/stackblitz.md
- Capitalize bullet list items
- Normalize spacing around `<PreCheck>` tags
=> Capitalize bullet list items

src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/2-pages/5.md
Now, all new lines on frontmatter build on the existing ones.
=> [tutorial] added full frontmatter to code examples ch 2.3 - 2.5

src/pages/en/tutorial/1-setup/4.md
Removes the off ramp and confusing checklist item 😅 from 1.4
=> [tutorial] removed confusing items in 1.4

src/pages/en/tutorial/2-pages/3.md
Instructs the user to "guess" rather than "write" a response. Also gives a hint that the answer might be "nothing."
=> [tutorial] less confusing self-quiz instruction

src/pages/en/tutorial/2-pages/1.md, src/pages/en/tutorial/2-pages/2.md, src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/2-pages/5.md, src/pages/en/tutorial/3-components/1.md, src/pages/en/tutorial/3-components/2.md, src/pages/en/tutorial/3-components/3.md, src/pages/en/tutorial/3-components/4.md, src/pages/en/tutorial/4-layouts/1.md, src/pages/en/tutorial/4-layouts/2.md, src/pages/en/tutorial/4-layouts/3.md, src/pages/en/tutorial/5-astro-api/1.md, src/pages/en/tutorial/5-astro-api/2.md, src/pages/en/tutorial/5-astro-api/3.md, src/pages/en/tutorial/5-astro-api/4.md, src/pages/en/tutorial/6-islands/1.md, src/pages/en/tutorial/6-islands/2.md, src/pages/en/tutorial/6-islands/3.md
All checklists updated for brevity Units 2 - 6 inclusive. (Did not yet revisit Units 0 and 1 yet, since other work on those units being done.)
=> [tutorial] updated Units 2-6 checklists

src/pages/en/core-concepts/routing.md
on the first code example for ssr the h1 tag didn't have an ending tag, just another opening tag which I believe is just a simple error which I fixed.
- Closes # 
- What does this PR change? Added closing line to h1 tag in code example.
=> fixed code example

src/pages/pt-br/guides/deploy/render.md
-  Add page render.md traslated to PT-BR
=> Add render.md PT-BR translation

src/pages/es/concepts/islands.md
- What does this PR change? This fixes indentation based on this commit https://github.com/withastro/docs/commit/6b72121bde88ce334380592b4a55ca1cc142aacb#diff-81da64b5a4079d074a3e448dd6631b356c2bd853484080aa48bb605e118e16f3
=> i18n(es): Minor update to `islands.md`

src/pages/es/core-concepts/astro-components.md
- Updates `astro-components.md` spanish translation
=> i18n(es): Update `astro-components.md`

src/pages/es/core-concepts/layouts.md
- Updates `layouts.md` spanish translation
=> i18n(es): Update `layouts.md`

src/pages/es/core-concepts/sharing-state.md
- Updates `sharing-state.md` spanish translation
=> i18n(es): Update `sharing-state.md`

src/pages/es/guides/server-side-rendering.md
- Updates `server-side-rendering.md` spanish translation
=> i18n(es): Update `server-side-rendering.md`

src/pages/es/guides/data-fetching.md
- Updates `data-fetching.md` spanish translation
=> i18n(es): Update `data-fetching.md`

src/pages/es/guides/deploy/deno.md, src/pages/es/guides/deploy/gitlab.md, src/pages/es/guides/deploy/layer-zero.md, src/pages/es/guides/deploy/netlify.md, src/pages/es/guides/deploy/surge.md, src/pages/es/guides/deploy/vercel.md
- Updates `guides/deploy/deno.md` spanish translation
- Updates `guides/deploy/gitlab.md` spanish translation
- Updates `guides/deploy/layer-zero.md` spanish translation
- Updates `guides/deploy/netlify.md` spanish translation
- Updates `guides/deploy/surge.md` spanish translation
- Updates `guides/deploy/vercel.md` spanish translation
=> i18n(es): Update multiple deploy guides

src/pages/es/reference/cli-reference.md
- Updates `cli-reference.md` spanish translation
=> i18n(es): Update `cli-reference.md`

src/pages/zh-tw/core-concepts/project-structure.md
- Update the `/src/pages/zh-tw/core-concepts/project-structure.md` with `tsconfig.json` section.
=> i18n(zh-tw): Update `project-structure.md`

src/pages/en/tutorial/1-setup/1.md, src/pages/en/tutorial/1-setup/5.md
Reworks some Q's in Ch1 to be multiple choice, for better UX.
=> Ch1 multiple choice rework

src/pages/en/tutorial/0-introduction/index.md
This adds a preview of the completed project to the homepage. (We'd previously used the Stackblitz preview, but its call-to-action button distracted some readers and it doesn't work on all browsers.)
=> [tutorial] Add iframe to homepage

src/pages/en/tutorial/2-pages/2.md, src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/2-pages/5.md
- Corrects the `</blog>` tag to `</a>`
- Based on feedback, remove the tricky bulletStyle CSS example (requires single quotes within double quotes)
- Create pages before linking to them and classes before styling them
=> [tutorial] Chapter 2 corrections/improvements

src/pages/en/tutorial/0-introduction/index.md
Make the iframe a bit taller, so you can see the bottom edge on smaller screens.
=> [tutorial] Change iframe aspect ratio

src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/1-setup/index.md, src/pages/en/tutorial/2-pages/1.md
- Rephrase the introductions so that it doesn't seem _required_ to deploy
- Preface the Publishing section on 2.1 to be on condition that you've followed from Unit 1
- Replaced "tools and accounts" to "tools", now that we're only actually setting up one account as part of deployment
=> [tutorial] Preface publishing on 2.1

src/components/tutorial/StackblitzIntro.astro
- Fixes a period that was inside a link, moving it outside. Thrilling stuff 🥳
=> tutorial: Fix period inside link

src/pages/es/guides/markdown-content.md
- Updates `markdown-content.md` spanish translation
=> i18n(es): Update `markdown-content.md`

src/i18n/fr/README.md
=> i18n(fr): fix typo in glossary

src/pages/es/reference/configuration-reference.md
- Updates `configuration-reference.md` spanish translation
=> i18n(es): Update `configuration-reference.md`

src/pages/es/reference/adapter-reference.md
- Updates `adapter-reference.md` spanish translation
=> i18n(es): Update `adapter-reference.md`

src/pages/es/guides/rss.md
- Updates `rss.md` spanish translation
=> i18n(es): Update `rss.md`

src/pages/es/reference/api-reference.md
- Updates `api-reference.md` spanish translation
=> i18n(es): Update `api-reference.md`

src/i18n/de/README.md
- Adds more common translation issues based on the experience from past PR reviews.
=> i18n(de): Add common issues in translation guide

.npmrc, astro.config.ts, package.json, pnpm-lock.yaml
- Remove `shamefully-hoist` in `.npmrc`
- Add missing dependencies
- All scripts should work as before
- This removes the need for `--shamefully-hoist` in Astro's smoke test
=> Remove shamefully-hoist

src/i18n/fr/README.md, src/pages/fr/getting-started.md
- Translate https://docs.astro.build/fr/getting-started/ from en page.
- A few changes in the French Glossary Readme.
=> i18n(fr): Update Getting Started and Glossary

src/pages/fr/guides/imports.md
Use `:::note` syntax.
- Minor content fix
Before:
After:
=> typo: Fix aside in French Imports page

src/pages/[lang]/404.astro
- Tracks a 404 event in Fathom analytics whenever anyone lands on one of our 404 pages.
=> Track a 404 event to help find common 404 URLs

src/components/tutorial/MultipleChoice.astro, src/components/tutorial/Option.astro, src/pages/en/tutorial/0-introduction/1.md, src/pages/en/tutorial/1-setup/1.md, src/pages/en/tutorial/1-setup/5.md
- Fix indentation on a few last `<MultipleChoice>` instances that weren’t nested under their numbered question.
- Remove the “What’s all the interactive quizzes?” `<details>` in 0.1 as discussed.
- Flip the `box-shadow` direction on the submit button in `<MultipleChoice>` so it matches the checklist buttons (and the `<Box>`) direction.
- Update the letters in the `<MultipleChoice>` options so that they look more like the checklist buttons (including bounce! 🏀💨)
=> Tutorial: better multiple choice styles & remove content

src/pages/fr/core-concepts/astro-components.md, src/pages/fr/core-concepts/framework-components.md, src/pages/fr/core-concepts/layouts.md, src/pages/fr/guides/markdown-content.md
- Grammatical fixes
- Do not translate `slot` in French.
=> i18n(fr): Update astro-components in French

src/components/tutorial/Lede.astro, src/pages/en/tutorial/0-introduction/index.md
- Remove iframe
- Resize lede
- Wording tweaks
=> [tutorial] Homepage tweaks

src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/2-pages/5.md, src/pages/en/tutorial/3-components/3.md, src/pages/en/tutorial/3-components/4.md, src/pages/en/tutorial/5-astro-api/2.md
=> typo in tutorials

src/pages/pt-br/guides/deploy/google-firebase.md
- Add google-firebase.md pt-br translation
=> i18n(pt-br): google-firebase.md deploy page

src/pages/pt-br/guides/deploy/surge.md
- Create a pt-br translation for surge.md
=> i18n(pt-br): surge.md 

src/i18n/de/nav.ts, src/pages/de/guides/testing.md
German translation for testing guide https://docs.astro.build/de/guides/testing/
=> i18n(de): add translation for testing-guide

src/pages/en/tutorial/2-pages/3.md
Fixed small typo.
operatingSytem to operatingSystem
- Closes # 
- 
operatingSytem to operatingSystem
=> [typo fix] operatingSystem

src/i18n/pt-br/ui.ts
- Closes # 
hacktoberfest-accepted
=> i18n(pt-br): Translate integration guide changelog label

src/pages/en/tutorial/1-setup/5.md
Improving a multiple choice question that *used* to be "put these things in order" that didn't translate well to being turned into MC.
=> [tutorial] Redo MC question 1.5

src/pages/en/tutorial/2-pages/4.md, src/pages/en/tutorial/3-components/3.md
- Moves the first `<style>` inside the HTML, to avoid the formatter issue.
- Moves imports to the top of a sample
=> [Tutorial] Style placement correction

src/pages/es/reference/configuration-reference.md, src/pages/es/reference/directives-reference.md
Updates `configuration-reference.md` and `directives-reference.md` with latest changes.
=> i18n(es): update reference files to latest changes

src/pages/en/guides/markdown-content.md
=> Switched to backticks for filename formatting.

src/pages/en/core-concepts/astro-components.md
Hi! I think I might have caught a small typo on the closing tag, please disregard if I am mistaken.
closing tag typo
=> Fix typo in code example

src/pages/en/tutorial/3-components/3.md
The tutorial docs ([here](https://docs.astro.build/en/tutorial/3-components/3/#try-it-yourself---update-your-pages)) display incorrect diffs
=> fix diffs in tutorial code

src/pages/en/tutorial/5-astro-api/2.md
Closes Issue #1949 
Thanks for catching these, @ScriptRaccoon!  🚀
=> [tutorial] file name typo fixes

src/pages/pt-br/concepts/islands.md
As you can see by her twitter account https://twitter.com/ksylor, she identifies as she/her. In Portuguese we have different names for male and female job descriptions, in this case arquitetO (male) and arquitetA (female).
=> Fix pronouns in Portuguese for Katie Sylor-Miller

.github/hacktoberfest.md
Updated the Hacktoberfest reviewer list with my contributions
=> add hacktoberfest contributions

src/pages/en/tutorial/1-setup/2.md, src/pages/en/tutorial/2-pages/1.md, src/pages/en/tutorial/6-islands/1.md
- Make sure we also show macOS keyboard shortcuts where relevant
- Tweak some of the wording around shortcuts
- Fix some indentation
- Remove a stray backtick
=> Tutorial: Keyboard shortcut improvements & minor fixes

src/pages/en/tutorial/5-astro-api/2.md
- Closes # 
- What does this PR change? Give us a brief description.\
Corrects one of the tutorial's routes so that it doesn't return a 404 page when copy and pasted into a browser's address bar.
No
=> corrected one of the tutorial's routes

README.md
Add edit with codesandbox  button
I have been using codesandbox a lot for my open-source contributions, and I think it's really cool. Astro doc contributors can work seamlessly, and I wanted to add it here as an option. 
- Closes # 
=> Edit docs with Codesandbox repos

src/pages/en/tutorial/3-components/2.md
Quick edit to tutorial code sample Check In on 3-2: Removes the individual page navigation links because the Navigation component is now used.
=> [tutorial] 3-2 code sample fix

src/pages/en/tutorial/3-components/4.md
Some quick fixes because of earlier content restructuring, where it was referencing things that no longer happen before.
=> [tutorial ] 3-4 edits based on page reordering

src/i18n/fr/README.md
Add a french word for "Re-render"
=> i18n(fr): add new word to glossary

src/pages/en/tutorial/2-pages/5.md, src/pages/en/tutorial/3-components/3.md, src/pages/en/tutorial/4-layouts/3.md, src/pages/en/tutorial/5-astro-api/3.md
I fixed some typos in the tutorial.
=> [tutorial] fix some typos

src/pages/en/tutorial/2-pages/2.md, src/pages/en/tutorial/2-pages/3.md, src/pages/en/tutorial/3-components/3.md, src/pages/en/tutorial/3-components/4.md, src/pages/en/tutorial/5-astro-api/3.md
Fixed indentation in some code snippets to make them consistent with other code.
=> [tutorial] fix indentation in some code snippets

src/pages/en/tutorial/4-layouts/2.md, src/pages/en/tutorial/5-astro-api/2.md, src/pages/en/tutorial/6-islands/1.md
Removed some unnecessary code in code snippets.
=> [tutorial] remove some unnecessary code

src/pages/en/tutorial/2-pages/2.md, src/pages/en/tutorial/2-pages/3.md
The first test in 2-2 is about `.astro` files, which has not yet been discussed. So I moved this test to 2-3 where it seems more appropriate.
=> [tutorial] move the first test in 2-2 to 2-3

src/pages/en/tutorial/2-pages/2.md
- Change the [Test your knowledge quiz question and answers on the Markdown tutorial page](https://docs.astro.build/en/tutorial/2-pages/2/#test-your-knowledge)
- It was previously about YAML frontmatter, which had not been introduced
- It was previously the exact same as in the following page's [Test your knowledge section](https://docs.astro.build/en/tutorial/2-pages/3/#test-your-knowledge)
Just wanted to add that this tutorial is fantastic and just what I need to get more colleagues on board with Astro!
=> Change quiz question for Markdown tutorial page

src/i18n/es/nav.ts, src/i18n/es/ui.ts, src/pages/es/guides/cms.md
- What does this PR change? Translated `cmd.md` to spanish  based on https://github.com/withastro/docs/pull/1975
=> i18n(es): Translate `cms.md` 

src/pages/es/guides/deploy/edgio.md
- What does this PR change? Translation of `edgio.md` based on https://github.com/withastro/docs/pull/1939
=> i18n(es): Translate of `edgio.md`

src/pages/es/guides/configuring-astro.md
- What does this PR change? Update of `configuring-astro.md` based on this changes dfb0c78c00c30e6b4601d64009348aafa928a0ae
=> i18n(es): update `configuring-astro.md`

src/pages/en/tutorial/5-astro-api/3.md
- Missing word in descriptive text
- Typos in tags in code block
=> Fix minor typos in Astro API tutorial page

src/pages/en/tutorial/2-pages/4.md
- Removed one of the duplicate title tags.
- Made a diff in code more explicit.
- Added the `font-style` defined at the top of the page to the subsequent styles.
=> [tutorial] fix code snippets in 2-4

src/pages/en/tutorial/3-components/3.md
Styles for html, body, etc. in 3-3 are different from those added in 2-5, so I corrected them to match.
---
By the way, thanks for the great tutorial. I enjoyed it very much. Sorry for all the PR, but this is the last one! 😆
=> [tutorial] update global.css in 3-3

src/pages/en/tutorial/4-layouts/1.md
Added a diff to make it easier to see where changes have been made.
=> [tutorial] add a diff in 4-1 for clarity

src/pages/en/tutorial/6-islands/3.md
Maybe still a little underwhelming, but #NWTWWHB? 😅 
Also, importantly, includes a checklist so that the Unit 6 circle can actually be all green! ✅
=> [tutorial] heartier congrats page

src/pages/en/guides/testing.md
Updated suggested `test:e2e` script to call `playwright test`. The existing guide fails due to missing arg.
=> fix playwright test:e2e script

src/pages/en/tutorial/3-components/2.md
We received a Feedback Fish that in 3-2, we didn't really introduce or explain props before using them.
This adds a minimal introduction to the Social Media component where before there was none, only instructions starting at step 1.
=> [tutorial] 3-2 Introduce props

src/pages/es/guides/imports.md
- What does this PR change? Give us a brief description. Update of `imports.md`
=> i18n(es): Update `imports.md`

scripts/generate-integration-pages.ts
- Closes #967 
- Probably needs a lot of refactoring but the main idea is there 😇
=> add remark plugin to replace asides

src/i18n/zh-cn/nav.ts, src/i18n/zh-cn/ui.ts, src/pages/zh-cn/guides/cms.md
Translate cms.md, add corresponding ui and nav strings
=> i18n(zh-cn): Translate CMS guide, UI and nav strings

src/pages/en/reference/api-reference.md
The update the [`AstroInstance`](https://github.com/withastro/astro/blob/main/packages/astro/src/@types/astro.ts#L983-L986) interface
=> Update `AstroInstance` interface reference

src/pages/en/guides/imports.md
- Closes #2019
Preview [here](https://deploy-preview-2028--astro-docs-2.netlify.app/en/guides/imports/#astroglob)
=> Document Astro component import via `Astro.glob`

src/pages/es/guides/typescript.md, src/pages/es/install/manual.md
- What does this PR change? Update `typescript.md` & `manual.md` based on this commit 5721d825a04a8a3d51292a12a53254aa84b84204
=> i18n(es): Update `typescript.md` & `manual.md`

src/pages/es/reference/api-reference.md
- What does this PR change? Update of `api-reference.md` based on this commit da3725bf4e3a24647ee240a3816cc5d72e31d9e6
=> i18n(es): Update of `api-reference.md`

src/i18n/ja/ui.ts
- Updated the contents of the right sidebar to the latest version.
=> i18n(ja): Update rightSidebar.* in ui.ts

src/pages/es/guides/imports.md, src/pages/es/guides/troubleshooting.md, src/pages/es/guides/typescript.md
- What does this PR change? Update of `imports.md`, `troubleshooting.md` and `typescript.md` based on this commits 38799aebb23d1140499d6fbb9b82b5c89d128273, 8a04b61ea9dea49fd408531c19448cc1adc70c58 and 4fb086712cfed4342e5e3cdea2d2ef71267dce77
=> i18n(es): Update `imports.md`, `troubleshooting.md` and `typescript.md`

src/pages/en/tutorial/4-layouts/3.md
Improved multiple choice questions for section 4-3. One was previously questionable, but all were a hold-over from conversion from fill-in-the-blank format. So, I took the opportunity to provide better answers for all the questions in the process.
=> [tutorial] 4-3 update multiple choice answers

src/pages/es/core-concepts/layouts.md
- It's not much, but it's honest work
=> i18n(es): Update layouts.md

src/pages/en/guides/integrations-guide/image.md
- What does this PR change? 
- I noticed a typo while reading through documentation. 
**Before**
**After**
=> Address typo

src/pages/en/tutorial/3-components/3.md
- What does this PR change? 
Fix the import route in the Header component when importing the Navigation component
=> Fix import link for Header component in tutorial 3

src/pages/en/guides/cms/netlify-cms.md, src/pages/en/guides/cms/sanity.md, src/pages/en/guides/cms/wordpress.md, src/pages/en/integrations/integrations.md
This moves relevant content out of `integrations/integrations` hidden page an onto the appropriate CMS guides
=> [integrations/integrations] add integrations to cms pages

src/pages/zh-cn/concepts/islands.md
=> i18n(zh-ch): fix typo in islands.md

src/pages/en/guides/cms/storyblok.md
- Adds `axios` and `vite` to pnpm installs
=> fix pnpm installs in storyblok guide

src/pages/en/tutorial/3-components/4.md
- `<header>` -> `</header>` in the tutorial
- 
https://pr.new/withastro/docs/edit/jasikpark-patch-1/src/pages/en/tutorial/3-components/4.md?initialPath=%2Fen%2Ftutorial%2F3-components%2F4%2F
=> Fix typo: `<header>` -> `</header>`

src/pages/en/core-concepts/sharing-state.md
Solid stores are getters, applied changes to reflect that.
=> Sharing State: fix nanostore usage in Solid examples

src/pages/fr/core-concepts/sharing-state.md
=> i18n(fr): update sharing state

package.json, pnpm-lock.yaml, src/components/Checklist.astro, src/components/tutorial/CompletionConfetti.astro, src/components/tutorial/StackblitzIntro.astro, src/pages/en/tutorial/6-islands/3.md
Updates to the tutorial completion page:
- Add a link to the final version of the tutorial code on GitHub and StackBlitz
- Add confetti on page load to celebrate 🎊
=> Add final code check link & confetti to tutorial completion page

src/pages/en/tutorial/4-layouts/3.md
=> Delete duplicate 'you'

src/i18n/de/nav.ts, src/pages/de/guides/cms.md
German guide for https://docs.astro.build/de/guides/cms/
=> docs(de): add cms guide

src/pages/en/guides/troubleshooting.md
Amends a typo in the English troubleshooting guide.
=> Amend typo in the troubleshooting EN guide

src/env.d.ts, tsconfig.json
- Closes #2116
- Fixes our TypeScript configuration to properly handle Preact components
=> Fix tsconfig for Preact JSX & move ambient types to `env.d.ts`

src/pages/es/reference/api-reference.md
- Minor content fixes
- Fix typos
=> i18n(es): typo in api-reference/#astrourl

src/pages/en/concepts/why-astro.md
x Minor content fixes (broken links, typos, etc.)
x New or updated content
- Closes #2066  
- What does this PR change? This pr updates the content-focused tip section to include other community frameworks besides Next.js.
=> updated web frameworks to include others

src/pages/en/guides/cms/wordpress.md
- I added a few links to community resources at the suggestion of @sarah11918  that I built with some support from WP Engine. We'll do our best to keep the linked post current with the latest and greatest in Astro. I also included a link to the starter project that the post references, which I'll continue to expand. I tried to keep parallel structures with other CMS pages that had linked starters, but feel free to remove that if needed. I submitted it to the themes directory as well. If you all are open to additional contributions on this page, I'd love to be involved. 🙌 TY for considering these resources 🚀
=> Add WordPress resources

src/pages/en/guides/cms/storyblok.md
- Complete review of the page ✨
- Closes #2127
=> Review Storyblok page

src/pages/ja/guides/aliases.md
=> i18n(ja): Update aliases.md

src/pages/en/reference/cli-reference.md
- Came up in https://github.com/withastro/rfcs/discussions/405#discussioncomment-4323822 that you can disable telemetry by setting an environment variable as well as running `astro telemetry disable`. This notes that in the CLI reference. Didn’t go into any detail as it’s already kind of out of place in the CLI reference, but we don’t have anywhere better for this. Let me know if you think this deserves more.
=> Document disabling telemetry with an environment variable

src/pages/en/guides/cms/wordpress.md
Update a backtick to hide URL for inline code link on `_fields`
Before on prod
After
=> reformat backtick

src/i18n/ja/ui.ts
=> i18n(ja): Update ui.ts

src/pages/fr/install/manual.md
- Small typo
- Missing files in directory tree, which might be confusing
=> i18n(fr): Fix typo and directory tree in install/manual.md

src/pages/zh-cn/concepts/mpa-vs-spa.md
=> i18n(zh): Typo fix in mpa-vs-spa.md

src/pages/en/guides/content-collections.md
Add the missing backtick for inline code.
=> Add missing backtick

src/pages/en/guides/content-collections.md
=> Fix example code in guide

src/pages/en/guides/content-collections.md
- `Markdown or MDX fields` -> `Markdown or MDX files`
- Make the sample directory name consistent with the code
=> Fix typos in content-collections.md

src/pages/en/tutorial/3-components/4.md
Fixing import statement in the docs
- Closes #2181
- What does this PR change?  Fixes import statement in the docs.
- Did you change something visual? No
=> Fix: import statement

src/pages/es/core-concepts/layouts.md
- Translate URL name and remove duplicate code title
=> i18n(es): translate url and remove duplicate code title

src/pages/es/core-concepts/project-structure.md, src/pages/es/core-concepts/routing.md, src/pages/es/core-concepts/sharing-state.md, src/pages/es/guides/deploy/buddy.md, src/pages/es/guides/deploy/edgio.md, src/pages/es/guides/deploy/vercel.md
- What does this PR change? Give us a brief description. 
Multiple updates as follows:
- `project-structure.md` based on this commit 79bdbb9ff909981606a62e276922a16bcd74e47c
- `routing.md` based on these commits c3b6a318f5c76fe817144c8760919ef24d2ecf35 & 79bdbb9ff909981606a62e276922a16bcd74e47c
- `sharing-state.md` based on this commit 36fd85a3d7051fc6b91be51e3847985452b70244
- `buddy.md` based on this commit b2eef6b76e2ccbaea7a0e84b25e73ff7ef21218e
- `edgio.md` based on this commit ce366938e7eef4e3aa8e03c0962661bac526ffa1
- `vercel.md` based on this commit e6f4c3c6f6db9756519619f64abffc451e71cee9
=> i18n(es): Update of `project-structure.md`, `routing.md`, `sharing-state.md`, `buddy.md`, `edgio.md` & `vercel.md`

astro.config.ts, package.json, pnpm-lock.yaml
Remove a remark plugin used for the first version of error reference but which is no longer needed now that we have separate pages for each error.
=> Remove unused custom heading ID remark plugin

src/pages/en/guides/content-collections.md
Fixes typo in a content collections example.
=> fix typo in content collections example

src/pages/es/guides/deploy/kinsta.md
=> i18n(es): add `kinsta.md`

WRITING.md
Added some extra info re: creating custom Tab components, including how to force a particular ordering of tabs.
=> [WRITING.md] Added note about ordering of Tabs component

src/pages/es/guides/fonts.md
Upadate Spanish translation for `fonts.md`
=> i18n(es): Update translation fonts.md

src/pages/es/reference/configuration-reference.md
Update Spanish translation for page `configuration-reference.md`
=> i18n(es): Update configuration-reference.md

src/pages/es/editor-setup.md
Update Spanish translation for the page `editor-setup.md`
=> i18n(es): Update translation editor-setup.md

src/pages/en/guides/cms/contentful.md
- Closes #2179
- What does this PR change? Give us a brief description. fix typo in imported type in code example
=> fix typo in `BlogPost` interface code example

src/pages/ja/editor-setup.md
- Update editor-setup.md.
- Corresponds to https://github.com/withastro/docs/pull/2219.
=> i18n(ja): Update editor-setup.md

src/pages/en/core-concepts/astro-components.md
- Update `Comments` section in astro-components page.
- Showcase different commenting types in Astro files JSX part.
- Add caution of which comments are included into browser DOM and which is not.
- https://deploy-preview-2229--astro-docs-2.netlify.app/en/core-concepts/astro-components/#comments
=> docs: update en astro-components about code comments

src/pages/es/core-concepts/astro-components.md
Update Spanish translation for `astro-components.md`
=> i18n(es): Update astro-components.md

src/pages/en/guides/markdown-content.md
=> Fix typos in markdown-content.md

src/pages/es/guides/deploy/netlify.md
=> i18n(es): update netlify.md

src/pages/en/guides/cms/wordpress.md
=> Fix typo in wordpress.md

src/pages/es/reference/error-reference.md
- adds `reference/error-reference.md` in Spanish
=> i18n(es): add error-reference

src/pages/en/reference/cli-reference.md
- Add `astro sync` CLI reference
=> `astro sync` CLI reference

src/pages/en/install/auto.mdx, src/pages/en/install/manual.mdx
Both CLI and manual installation now have the same title to help give the illusion of tabs
Discussion for reference: https://discord.com/channels/830184174198718474/830184175176122389/1058459575789027338
I chose "Installation" because it is consistent with the sidebar as well, as it does in most other pages.
Can be  changed if there is a better name, I guess "Installation (automatic)" could work as well
=> Consistent installation title

src/pages/en/guides/typescript.mdx
=> Fix typo in Typescript guide

src/pages/en/install/auto.mdx, src/pages/en/install/manual.mdx
Reverts withastro/docs#2262 — see https://github.com/withastro/docs/pull/2262#issuecomment-1368137847
=> Revert "Consistent installation title"

src/i18n/pt-br/nav.ts, src/pages/pt-br/guides/client-side-scripts.mdx
- 
Add PT-BR `client-side-scripts.mdx` translation.
=> i18n(pt-BR): Add `client-side-scripts.mdx` translation

src/pages/en/getting-started.mdx
Tiny change to a heading on the getting started page to provide a more helpful left sidebar link.
"Learn More" -> "What's New?"
=> [getting started] emphasize what's new!

src/pages/zh-cn/guides/testing.mdx
=> i18n(zh-cn): Add testing.mdx

src/pages/en/guides/styling.mdx
Correct Vite Docs url for importing assets as url
=> update link to correct resource

src/pages/fr/concepts/islands.mdx
Just changing a little line, and adding :
```mdx
ins="client:load"
```
I am based on [this comparison](https://github.com/pioupia/astro-docs/compare/69274b8...6b72121#diff-81da64b5a4079d074a3e448dd6631b356c2bd853484080aa48bb605e118e16f3) perform for the modifications. If there are any shortcomings in the content, please let me know.
=> i18n(fr): Update 'islands concept' page in French

src/pages/es/guides/aliases.mdx
Adding `?url` to the file name imported at line 44 and 19, like it is at line 15.
=> i18n(es): Fix missing file name query

src/pages/fr/concepts/why-astro.mdx
Just updating a part of a sentence.
I am based on [this comparison](https://github.com/pioupia/astro-docs/compare/2ec991d...5bc3f2d#diff-c5fd2554a9b061936e33418528f90aca9960275ce101bc3248ece1e95d566f57) perform for the modifications. If there are any shortcomings in the content, please let me know.
=> i18n(fr): Update why-astro.mdx

.github/workflows/ci.yml, package.json, src/components/Aside.astro, src/components/ContributorList.astro, src/components/DeployGuidesNav.astro, src/components/HeadCommon.astro, src/components/Header/ThemeToggleButton.tsx, src/components/IntegrationsNav.astro, src/components/LeftSidebar/LeftSidebar.astro, src/components/NavGrid/Card.astro, src/components/NavGrid/CardsNav.astro, src/components/Video.astro, src/components/tabs/TabbedContent.astro, src/components/tutorial/TutorialNav.astro, src/i18n/util.ts, src/layouts/BaseLayout.astro, src/layouts/DeployGuideLayout.astro, src/layouts/MainLayout.astro, src/pages/[lang]/404.astro, src/pages/[lang]/[...fallback].astro
This adds `astro check` to the CI, to make sure we don't have type issues in the docs's source code. This PR also fixes some type issues that were preventing it from passing correctly on the current version
=> ci(check): Add `astro check` step

src/pages/es/core-concepts/project-structure.mdx, src/pages/es/guides/rss.mdx, src/pages/es/guides/server-side-rendering.mdx, src/pages/es/guides/styling.mdx, src/pages/es/guides/troubleshooting.mdx
Update of multiple files based on these commits as follows:
-`project-structure.mdx` -> 7abc2abe98077d7596ebbd38b979b62c5d20ba4b
-`rss.mdx` -> 5f95eab79001c5d4a498622bc4ed2cc9e57b2ddc
-`server-side-rendering.mdx` -> 7bf163628ba2785c0c76444bace3e27d907f9365 & 1ec486ceb485eb8835b68481df0cdce594728411
-`styling.mdx` -> 09ddfaba8e605193448bdacbd5136a03b8cfc588
- `troubleshooting.mdx` -> 2d16d221e2cb9baff84bf1347062ad82cd058f83 & 7abc2abe98077d7596ebbd38b979b62c5d20ba4b
=> i18n(es): Update of `project-structure.mdx`, `rss.mdx`, `server-side-rendering.mdx`, `styling.mdx` and `troubleshooting.mdx`

src/pages/en/guides/migrate-to-astro.mdx
Fixed a small typo, Tailwind was referred to as Taliwind
=> change Taliwind to Tailwind

src/i18n/ja/docsearch.ts
- Update docsearch.ts.
- Corresponds to https://github.com/withastro/docs/pull/2086.
=> i18n(ja): Update docsearch.ts

src/pages/de/install/manual.mdx, src/pages/en/guides/deploy/netlify.mdx, src/pages/en/install/auto.mdx, src/pages/en/install/manual.mdx, src/pages/en/tutorial/1-setup/1.mdx, src/pages/es/guides/deploy/netlify.mdx, src/pages/es/install/auto.mdx, src/pages/es/install/manual.mdx, src/pages/fr/guides/deploy/netlify.mdx, src/pages/fr/install/auto.mdx, src/pages/fr/install/manual.mdx, src/pages/ja/install/auto.mdx, src/pages/ja/install/manual.mdx, src/pages/pt-br/guides/deploy/netlify.mdx, src/pages/pt-br/install/auto.mdx, src/pages/pt-br/install/manual.mdx, src/pages/ru/install/auto.mdx, src/pages/zh-cn/install/auto.mdx, src/pages/zh-cn/install/manual.mdx, src/pages/zh-tw/install/auto.mdx, src/pages/zh-tw/install/manual.mdx
Updates everywhere that mentions the Node versions Astro supports to show the new v2 range of `v16.12.0` or higher.
=> [i18nIgnore] Update supported Node versions

src/pages/pt-br/core-concepts/endpoints.mdx, src/pages/pt-br/reference/api-reference.mdx
Updated PT-BR translations for `endpoints.mdx` and `api-reference.mdx`.
=> i18n(pt-BR): Update `endpoints.mdx` and `api-reference.mdx` translations

src/pages/fr/guides/deploy/github.mdx
I updated the translation of the page `github.mdx` in French
=> i18n(fr): Update github.mdx

src/pages/pt-br/migrate.mdx, src/pages/pt-br/reference/configuration-reference.mdx, src/pages/pt-br/reference/directives-reference.mdx
Updated PT-BR `configuration-reference.mdx` and `directives-reference.mdx` translations.
=> i18n(pt-BR): Update `(configuration/directives)-reference.mdx` translations

src/pages/fr/core-concepts/astro-components.mdx, src/pages/fr/core-concepts/framework-components.mdx, src/pages/fr/core-concepts/layouts.mdx, src/pages/fr/guides/markdown-content.mdx
Update astro-components.mdx in French
=> i18n(fr): Update astro-components.mdx

src/pages/en/install/auto.mdx
=> Corrects misspelling of "repository" 

src/pages/en/tutorial/5-astro-api/1.mdx
Updates the image used in the code snippet for the fourth blog post. The original image no longer exists, and this updates with a new one.
=> [tutorial] Update outdated image src

src/pages/en/guides/content-collections.mdx
adds missing comma to tsconfig.json example
=> add comma to tsconfig.json example

src/pages/en/tutorial/0-introduction/1.mdx, src/pages/en/tutorial/1-setup/1.mdx, src/pages/en/tutorial/1-setup/4.mdx, src/pages/en/tutorial/1-setup/5.mdx, src/pages/en/tutorial/2-pages/1.mdx, src/pages/en/tutorial/2-pages/2.mdx, src/pages/en/tutorial/2-pages/4.mdx, src/pages/en/tutorial/2-pages/index.mdx, src/pages/en/tutorial/3-components/1.mdx, src/pages/en/tutorial/3-components/3.mdx, src/pages/en/tutorial/3-components/index.mdx, src/pages/en/tutorial/4-layouts/2.mdx, src/pages/en/tutorial/4-layouts/3.mdx, src/pages/en/tutorial/4-layouts/index.mdx, src/pages/en/tutorial/5-astro-api/2.mdx, src/pages/en/tutorial/5-astro-api/3.mdx, src/pages/en/tutorial/5-astro-api/4.mdx, src/pages/en/tutorial/5-astro-api/index.mdx, src/pages/en/tutorial/6-islands/1.mdx, src/pages/en/tutorial/6-islands/2.mdx
Gave a pass at the tutorial, focusing on small improvements in text (fixing typos, adding serial commas, etc.).
=> [Tutorial] Fix typos

src/pages/ja/core-concepts/project-structure.mdx
- Update project-structure.mdx.
- Corresponds to https://github.com/withastro/docs/pull/2339/files.
=> i18n(ja): Update project-structure.mdx

src/components/CMSGuidesNav.astro, src/components/Header/Search.astro, src/components/UIString.astro, src/components/tutorial/TutorialNav.astro, src/pages/[lang]/[...fallback].astro, tsconfig.json
Update the tsconfig.json to Astro's presets instead of manually writing things
=> feat(tsconfig): Use Astro's tsconfig preset

src/pages/en/guides/cms/ghost.mdx
for ghost integrations with Astro. I think *contentful* was added mistakenly removing *contentful*.
- npm
- pnpm
- yarn
=> Correcting Ghost dependencies integration commands

src/pages/en/guides/migrate-to-astro/from-gridsome.mdx
- Extend community resources list for "Migrating from Gridsome" page with new community content
=> Add a link to blog post about migration from Gridsome

src/pages/fr/install/auto.mdx, src/pages/fr/install/manual.mdx, src/pages/fr/integrations/integrations.mdx, src/pages/fr/reference/publish-to-npm.mdx
Update `publish-to-npm.mdx`, `integrations.mdx`, `manual.mdx` and `auto.mdx`
=> i18n(fr): Update `publish-to-npm.mdx`, `integrations.mdx`, `manual.mdx` and `auto.mdx`

src/pages/pt-br/guides/markdown-content.mdx, src/pages/pt-br/guides/styling.mdx
Updated PT-BR `styling.mdx` and `markdown-content.mdx` translations
=> i18n(pt-BR): Update `styling.mdx` and `markdown-content.mdx` translations

src/pages/en/guides/content-collections.mdx
=> fix: typos in content collections docs

src/pages/es/core-concepts/astro-pages.mdx, src/pages/es/guides/markdown-content.mdx, src/pages/es/guides/rss.mdx, src/pages/es/guides/styling.mdx, src/pages/es/install/auto.mdx
Multiple updates of pages based on the following info:
-astro-pages.mdx → 1d0823fab64c8e2601c3347309efd4ee78a221de
-markdown-content.mdx → 1d0823fab64c8e2601c3347309efd4ee78a221de
-rss.mdx → d373149aee53cf21fb4530034bfaa9f916a9d02f & 3ff3fa2a4acd8366f529040ed539ef8022bdfd9e
-styling.mdx → 1d0823fab64c8e2601c3347309efd4ee78a221de
-auto.mdx → e49d2de03f0b044e2dbd19a9b04476c4a4d63158
=> i18n(es): update of  `astro-pages.mdx`, `markdown-content.mdx`, `rss.mdx`, `styling.mdx` & `auto.mdx`

src/pages/en/tutorial/5-astro-api/3.mdx
- Fix tutorial 5 typo
-  fix typo from MarkdownLayoutPost to MarkdownPostLayout
=> doc: Fix tutorial 5 typo

src/pages/pt-br/reference/api-reference.mdx
Updated PT-BR `api-reference.mdx` translation.
=> i18n(pt-BR): Update `api-reference.mdx` translation

src/pages/en/tutorial/2-pages/3.mdx
Corrects a code snippet in one of the tutorial self-check excercises. Was missing `const` before statements.
=> [tutorial] correct code sippet

src/pages/en/tutorial/2-pages/3.mdx
"frontmattter" -> "frontmatter"
=> [i18nIgnore] [tutorial] tiny typo tweak

src/pages/de/getting-started.mdx
What kind of changes does this PR include?
- Translated content (getting-started) V2 notice in German
Description
See (en) PR: https://github.com/withastro/docs/pull/2436
=> i18n(de): Add v2 callout to landing page

src/pages/zh-cn/guides/client-side-scripts.mdx, src/pages/zh-cn/guides/deploy/cloudflare.mdx, src/pages/zh-cn/guides/testing.mdx
=> i18n(zh-cn): fix some typos

src/pages/en/guides/testing.mdx
Set `i18nReady: true` for `/guides/testing.mdx` -- open for business!  :rocket:
=> [testing guide] accepting translations!

src/pages/de/core-concepts/endpoints.mdx, src/pages/en/guides/cms/contentful.mdx, src/pages/en/guides/cms/wordpress.mdx, src/pages/en/guides/content-collections.mdx, src/pages/en/guides/deploy/cleavr.mdx, src/pages/en/guides/integrations-guide/mdx.mdx, src/pages/en/guides/upgrade-to/v1.mdx, src/pages/en/reference/api-reference.mdx, src/pages/en/reference/integrations-reference.mdx, src/pages/en/reference/publish-to-npm.mdx, src/pages/en/tutorial/2-pages/3.mdx, src/pages/en/tutorial/5-astro-api/2.mdx
This PR fixes various typos found in .mdx content files.
=> [i18nIgnore] Fixing typos

src/pages/en/guides/migrate-to-astro/from-nextjs.mdx
Requested by @sarah11918 – https://twitter.com/sarah11918/status/1616159813020303368
- Add link to https://ericclemmons.com/blog/converting-nextjs-to-astro
=> Add blog post link for converting Next.js

src/pages/en/guides/server-side-rendering.mdx
Updated **SSR: Prerendering** section to include the keywords Hybrid Rendering and clarify how it works.
=> Update prerendering section

src/pages/es/guides/testing.mdx
Added Spanish translation for `testing.mdx`.
=> i18n(es): Add translate page /guides/testing/

src/pages/en/guides/upgrade-to/v2.mdx
Unifies the usage of Node.js -> Node on the upgrade page.
This PR _might_ be motivated by wanting to be included in the launch day docs festivities!
=> Node.js/Node Consistency

src/pages/en/guides/upgrade-to/v2.mdx
- I thought it would be better to use `const` here, since it is unlikely that you will reassign other values to `allPosts`.
=> Use const instead of let

src/pages/en/guides/upgrade-to/v2.mdx
- Update the range of lines to be deleted to include the closing curly brace (and comma).
before | after
--- | ---
=> Correct the range of lines to be deleted

src/pages/en/guides/upgrade-to/v2.mdx
- Indent with two spaces for consistency.
=> Upgrade guide: fix indentation of code sample

src/pages/es/guides/deploy/sst.mdx
Added spanish translation for `page/guides/deploy/sst.mdx`
=> i18n(es): Add page `/guides/deploy/sst.mdx`

TRANSLATING.md
Add the new section "Pull Request Recommendations" with advice on PR size, title, description, and commits.
=> [i18n Guide] Add PR Recommendations

src/pages/fr/core-concepts/sharing-state.mdx
Adding "Vue's reactivity API link" about the last enhancement https://github.com/withastro/docs/commits/main/src/pages/en/core-concepts/sharing-state.mdx?since=2022-11-22T20:40:30.000Z
=> i18n(fr): Updated core-concepts/sharing-state.mdx

src/pages/fr/core-concepts/project-structure.mdx
About this enhancement https://github.com/withastro/docs/commits/main/src/pages/en/core-concepts/project-structure.mdx?since=2022-06-26T22:11:11.000Z
=> i18n(fr): core-concepts/project-structure.mdx

src/pages/fr/core-concepts/routing.mdx
About this update https://github.com/withastro/docs/commits/main/src/pages/en/core-concepts/routing.mdx?since=2022-06-26T22:23:34.000Z
=> i18n(fr): Update core-concepts/routing.mdx

src/pages/en/tutorial/4-layouts/3.mdx, src/pages/en/tutorial/5-astro-api/3.mdx
- What does this PR change? 
The suggested posts / md files in the tutorial don't have a `postImage` key set in the frontmatter. This PR updates the code snippets to use `image` key instead.
=> Update tutorial snippets

src/pages/en/guides/upgrade-to/v2.mdx
- What does this PR change? The pagesGlobToRssItems function returns a Promise, which causes an error ("[RSS] Invalid or missing options") unless the promise is resolved.
=> fix pagesGlobToRssItems example in v2 upgrade guide

src/pages/en/guides/content-collections.mdx
- Fixes typos on the Content Collections page
=> typo: Its -> It's

src/pages/es/guides/configuring-astro.mdx
Update of `configuring-astro.mdx` based on this commit c845737a332b74136d8894071435db67c76b04d5.
=> i18n(es): Update of `configuring-astro.mdx`

CONTRIBUTING.md, README.md
This PR adds a Codeflow button to the `README` and mentions it as an alternative in the `COTRIBUTING` file.
---
**💙 Before**
---
**💙 After**
=> Adds Codeflow

src/pages/es/guides/testing.mdx
Update file `guides/testing.mdx` based on https://github.com/withastro/docs/commit/4e1da50535443c816159f350e8b4f0685029a123
=> i18n(es): Update `testing.mdx`

src/pages/en/guides/cms/contentful.mdx
- Fixes a broken code sample in the contentful guide (following [this support thread](https://discord.com/channels/830184174198718474/1069749081548791839))
=> Correct code sample in Contentful guide

src/pages/ja/guides/testing.mdx
=> i18n(ja): Add testing.mdx

src/pages/zh-cn/guides/migrate-to-astro.mdx
- Change the word Taliwind to Tailwind
- Change the word Taliwind to Tailwind
=> docs: Taliwind to Tailwind

src/pages/en/reference/api-reference.mdx
Close https://github.com/withastro/astro/issues/5912
We may fix this in the future, but it's slightly complex at the moment, so noting a workaround for now.
=> Note Code component Shiki edge case

src/pages/en/guides/cms/netlify-cms.mdx
Closes # 
- N/A
What does this PR change? Give us a brief description.
- Added Netlify CMS / Astro integration tutorial I found helpful on Youtube.
Did you change something visual? A before/after screenshot can be helpful.
- N/A
=> Netlify CMS Integration - Youtube Tutorial

src/pages/zh-cn/editor-setup.mdx
- Fixes typo on the Editor Setup page
=> i18n(zh-cn): fix typo Miscrosoft -> Microsoft

src/pages/zh-cn/guides/cms.mdx
=> i18n(zh-cn): remove x

src/pages/en/guides/content-collections.mdx
=> CC Migration Guide: two missing "this becomes"

src/pages/en/tutorial/2-pages/1.mdx
Addresses this Feedback Fish:
> Nice intro, very supportive of people new to web dev!
> 
> With that in mind has the concept of routes been introduced yet in 2.1? There's a note that says "Astro uses standard HTML <a> elements to navigate between routes", but I'm not sure people will know what a route is yet.
Changes "routes" there to pages, and adds additional context to the note - it's implied that we're contrasting Astro's links to other framework's link systems, but if you're new to frameworks in general this isn't apparent.
=> Tutorial 2.1 - Don't use the term "routes" before introducing it

src/pages/en/guides/server-side-rendering.mdx
- Adds an example of how to enable prerendering on MDX pages when using SSR.
=> Add note about prerendering MDX files

src/pages/en/editor-setup.mdx
This PRs changes a paragraph with more up-to-date info about the currently in Early Access JetBrains plugin for Astro, with guidance on how to install it and which IDEs can benefit from it.
=> Add info about JetBrains Astro plugin
