withastro/docs

public/index.css
src/layouts/Main.astro

Compare the PR preview to the main branch's preview to see the styling changes.
Changes made:
- Increase sidebar width
- Increase article content width
- Remove `align-items: center` from article content
I made modifications to this because I felt the content seemed a bit "smushed" together and it was a bit cramped.

increase width for sidebar and article content, remove center align

---

README.md
package.json
snowpack.config.mjs
src/components/ArticleFooter.astro
src/components/AvatarList.astro
src/layouts/Main.astro
yarn.lock

Currently the images are hotlinked, so it might be the case where it makes more sense to pull in the images as assets programmatically and then reference them locally, but that's for once Astro has images figured out a bit more.
I fixed the editHref to actually point to this repo
There needs to be a Github Personal Access Token with `public_repo` permissions set to `SNOWPACK_PUBLIC_GITHUB_TOKEN` to remove Github rate limiting. 
```.env
// .env
SNOWPACK_PUBLIC_GITHUB_TOKEN=username:token
```

Implement basic AvatarList.astro

---

src/pages/guides/deploy.md

It turns out that `.nojekyll` is necessary to enable `/_astro/*` URLs, so this adds a note about that.
See https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

Update GitHub Pages deployment guide

---

src/pages/core-concepts/astro-pages.md
src/pages/core-concepts/collections.md
src/pages/core-concepts/layouts.md
src/pages/core-concepts/ui-renderers.md
src/pages/guides/styling.md
src/pages/reference/api-reference.md
src/pages/reference/cli-reference.md
src/pages/reference/renderer-reference.md

Hi,
I found broken links in the documentation and fixed them. In addition, I've made a few changes to make it more maintainable.
I also noticed the following (I didn't know how to deal with it, so I left it alone):
- There is no appropriate link for `[dev server](./dev.md)` on `src/pages/reference/cli-reference.md`
- `src/pages/core-concepts/ui-renderers.md` appears to be a stale version of  `src/pages/reference/renderer-reference.md`

Improve usage of links

---

src/components/AvatarList.astro

Make the error reporting just a **bit** clearer for `AvatarList.astro` since there's currently no reference to the file to tell you where the error is coming from.
This honestly might be something to add to `astro` by default: prefixing `console.log` in the build with the component it printed from, or at least a custom logger that people can opt in to

Add link the AvatarList.astro component on error.

---

src/layouts/Main.astro
src/pages/guides/markdown-content.md
src/pages/index.astro

This PR removes the astro warnings for using the old loading directive syntax.

Fix astro warnings `:directive` -> `client:directive`

---

src/pages/core-concepts/astro-components.md

The named slots update works great! However, if you paste the example as-is from the docs, it produces an error.
`<slot name="footer">`
Should be corrected to:
`<slot name="footer" />`

Fix typo in named slots example

---

src/components/AvatarList.astro

Changes:
- Adds a link to the git blame for the file if there are more than 3 contributors
- Links to the git blame for the file if we weren't able to fetch contributors using the git API, rather than just leaving the spot empty.

Link to git blame page in AvatarList

---

public/index.css
src/components/EditOnGithub.tsx
src/components/MenuToggle.tsx
src/layouts/Main.astro

I figure it'd be a good idea to implement the CSS along these lines: https://adrianroselli.com/2021/06/using-css-to-enforce-accessibility.html, though it's a bit messy at the moment, the basic setup is done for making the sidebar navigation visible on mobile, but I haven't figured out the grid and everything.
Also topical: https://inclusive-components.design/menus-menu-buttons/#navigationmenubuttons
Fixes #29

Add the basic idea for showing the sidebar on mobile

---

src/pages/core-concepts/project-structure.md

Order of links reflects their order in the sidebar

Fix link destinations/order in Project Structure

---

src/layouts/MainLayout.astro

**Describe the bug**
The "Edit this page" button is broken. 
e.g. go to 
`https://docs.astro.build/en/getting-started/`
click
"Edit this page"
get redirected to 
`https://github.com/withastro/astro/blob/main/src/pages/en/getting-started.md`
**Expected behavior**
Get redirected to 
`https://github.com/withastro/docs/blob/main/src/pages/en/getting-started.md`
**Pull Request**
This patch changes githubEditUrl to reflect the new docs location.

fix: update githubEditUrl

---

.github/labeler.yml

Since this repo is all about the documentation, every PR is about the docs so this rule isn't needed anymore

Remove unneeded labelling rule

---

README.md

Adds "Discuss the docs" to the Next Steps section, with a Discord invitation link directly to our #docs channel (no expiry, unlimited users, so should be fine as a permanent link).
I tested this anonymously, and this should allow users, even not logged in, to enter our Discord directly into our #docs channel (as unverified, read-only users until an account is confirmed), which I think could be helpful for making sure that (potential) contributors are aware of the specific channel and are encouraged to collaborate there.

Add a Next Step - "Discuss the docs"

---

src/pages/en/guides/markdown-content.md

Some editing to the section Markdown draft posts, including the warning that Astro.fetchContent() currently fetches data from ALL posts, including draft posts.
(I'm also testing the "edit this page" feature.)

Added Markdown draft posts are not excluded from Astro.fetchContent()

---

src/pages/de/installation.md
src/pages/en/installation.md
src/pages/es/installation.md
src/pages/hu/installation.md
src/pages/ja/installation.md

I hope the change was as easy as removing the linked word "snowpack" in all the other languages too. I will post on the docs-i18n channel to ask others to look over their language, just in case.
Note: not every language had this file, and of the ones that did, not every file included this specific configuration. I believe I caught all the existing ones.

removed link to "snowpack" configuration in Installation Guide

---

src/config.ts
src/pages/ja/core-concepts/project-structure.md

- Translated the project structure page into Japanese.
- I have confirmed that all the links work in my local environment.

Add Japanese project structure page

---

src/pages/en/reference/api-reference.md

- Improved readability of code comment regarding front matter.
- Added new lines between separate actions within code.
- Added trailing commas to the fewer examples that did not have it.
- Removed `<body>` from examples to avoid distractions (the pattern is also not found on any other page).

Cleanup code blocks in API Reference

---

src/pages/en/guides/markdown-content.md

Just "freshened up" the URL used for the remote Mardown fetching examples. Now points to astro/docs instead of snowpackjs/snowpack.

updated url in code example to Astro (instead of Snowpack)

---

src/pages/en/reference/api-reference.md

Added a quick array example to getStaticPaths() for those who want to generate data based on a set of locally available ones, but do not use fetch or other functions to retrieve them.

Added array example to getStaticPaths()

---

public/index.css

Before (thead color bleeds into tbody):
After (better separation of the first thead from tbody rows):
Also removes some unused style declarations.

Update index.css tbody tr

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/migrate.md

Just took the issue from the migration doc and added to the astro component section in regular docs, so that someone can (hopefully?) see it even if they're not doing a migration.

copied "imports on top" issue into regular docs

---

src/pages/en/guides/environment-variables.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/styling.md

Related to removing "new features" from the migration guide https://github.com/withastro/docs/pull/145 .
Where not already documented, the features have been added or incorporated into existing sections in /guides/ (without yet consideration for whether they ultimately belong there, or in /reference/ instead). Edited only if (and as much as) required to fit with existing material for now.

added new features from migration guide into regular docs guides

---

src/pages/en/guides/styling.md

There was info in the migration guide that was not yet available directly in the Styling page re: tailwind/autoprefixer/postcss (so it would be easy to miss if you *weren't* actually migrating, but just going straight to docs with a new project).
The styling page should now at least have the same information as the migration guide, with code samples copied over to match.

updated code samples to match migration guide

---

src/pages/en/guides/aliases.md

Hi,
I noticed that the docs have wrong example on using aliases and I wanted to make a quick fix

Fix alias guide to use correct syntax in examples

---

src/pages/en/core-concepts/astro-components-new.md
src/pages/en/core-concepts/astro-pages-new.md
src/pages/en/core-concepts/layouts-new.md
src/pages/en/core-concepts/project-structure-new.md
src/pages/en/guides/manual-setup-new.md
src/pages/en/installation-new.md

@FredKSchott - here are my proposed edits to your edits!  For your consideration. :)
Once we are happy with these files:
- CORE CONCEPTS: The following -new pages can be renamed and replace the existing pages, no changes to sidebar (yet):
-- Project Structure
-- Components
-- Pages
-- Layouts
(No changes yet to ...)
-- (Routing: we discussed moving "Routing" out of Core Concepts)
-- (Partial Hydration: to be discussed separately)
- SETUP Section updates:
-- Installation can be replaced with installation-new (renamed to remove -new)
-- manual-setup-new can be added to the sidebar (rename the file to remove -new and make sure Installation links to it properly)
-- Quick Start can be deleted and removed from the sidebar

Sarah's edits to new core concepts and installation guides

---

src/pages/en/getting-started.md

D'oh! Old getting starting page still references Quick Start page. Have changed this to point to the Installation Guide.

Updates link now that Quick Start page is gone

---

src/config.ts
src/pages/en/core-concepts/layouts.md
src/pages/en/guides/slots.md

The more detailed content about slots had been removed when making the core concepts more "core concept-y" and someone had been looking for it. 
So, to have the material still available, I've added a slot section in Guides that is first-pass edited. But, as I rework the guides it will be improved.

reintroduced section on slots for now

---

src/pages/en/reference/api-reference.md

Added a small/temporary note in the API reference page with a link to the `Astro.resolve()` anchor tag in the migration guide.

Add quick note about Astro.resolve

---

src/pages/en/comparing-astro-vs-other-tools.md

This brings back the Astro syntax VS JSX chart, and I think makes sense to include it in "Astro vs X" along with comparing to other site building tools.
Also changes header levels to make the right sidebar cleaner and easier to navigate, I think. Open to feedback!

Proposed new Astro v X to include jsx chart

---

src/pages/en/migrate.md

- The part of the migration docs that discuss moving from the old `resolve("file.js")` to the new `import "./file.js"` incorrectly refer to Javascript optimizations as CSS.
- This PR fixes that.

Fixed docs incorrectly referring to JS as CSS

---

scripts/docgen.mjs

- JSDoc fails to parse this line: `@type {undefined|((page: string) => boolean)}`.
- The reason is that `((page: string) => boolean)` isn't valid JSDoc.
- JSDoc has no syntax for inline function declarations like this.
- To work around this, we add support for a `@typeraw` tag which JSDoc parses as plain text. 
- This should hopefully be needed very rarely.

[autogen] Handle advanced jsdoc types with the `@typeraw` tag

---

src/pages/en/guides/markdown-content.md

I've updated this (now includes components in markdown! yay!) and also reorganized to I think be more user-friendly.
Instead of starting with parsers/config, it starts with more immediate user-centric concerns like making a page/blog post (as users will be able to do even without touching any config), then makes its way into configuration options.
This is still a lot of content, and not sure whether we want this eventually trimmed to put some stuff more in reference. But I think this organization at least will be more immediately useful.

New draft of Markdown Guide

---

src/pages/de/guides/styling.md
src/pages/en/guides/styling.md

ESM imports are the best approach for tailwind style imports to make sure HMR updates are picked up properly
Note: this only works properly with static build, that will be the default in 0.24+ so its probably best to hold on merging this docs update in until 0.24 is released
[Released PR](https://github.com/withastro/astro/pull/2740) updating the `with-tailwindcss` example project as well

Updates tailwind docs for 0.24

---

scripts/docgen.mjs
src/components/Badge.astro
src/components/Since.astro
src/components/UIString.astro
src/i18n/data.ts
src/i18n/translations.ts
src/i18n/util.ts
src/pages/en/reference/configuration-reference.md

The main outcome of this PR is to handle the `@version` tag in auto-generated API reference pages (as per @FredKSchott’s suggestion from #209), but it does also add some more general purpose architecture to help that will need reviewing.
1. Adds a `<Since>` component for rendering a message based on the `@version` tag in the reference JSDoc source.
[See it in action on the deploy preview →](https://deploy-preview-215--astro-docs-2.netlify.app/en/reference/configuration-reference/#host)
```astro
<Since v="0.23.0" />
```
**Added in:** v0.23.0
- If the `v` prop indicates a version that matches the latest minor version of `astro`, the component also displays a badge reading “NEW” to highlight new API features. In other words any API added in say 0.24.0 will be labelled “NEW” until 0.25.0 is …

Add “Added in v...” entries to API reference

---

src/pages/en/guides/manual-setup.md

Add a simple astro configuration file to the instructions to resolve development errors that show up without including this file.

Update the manual-setup.md instructions

---

src/pages/en/migrate.md

> __Important__: This should not be merged until 0.24 is released. That's why it's in draft mode.
This does 2 things:
- Changes the "Planned deprecations" section to "Migrate to v0.24" to match the other migration sections. Changes language to past tense rather than future.
- Adds a notice at the top to use the `--legacy-build` flag if needed and to file issues if bugs are encountered.

Document fallback behavior for 0.24

---

public/index.css
public/theme.css
src/components/Card.astro
src/components/HeadCommon.astro
src/components/Header/Header.astro
src/components/Header/LanguageSelect.css
src/components/Header/Search.css
src/components/LeftSidebar/SidebarSectionToggle.css
src/components/PageContent/ArticleNavigationButton.astro
src/layouts/MainLayout.astro

Following on from #198, this PR proposes theming changes to the docs site to bring it slightly closer to the main astro.build site.
Key changes:
- Use a gradient background. The light and dark variants draw on gradients used on the astro.build home page introducing subtle purples in the light theme and leaning into a night sky blue in the dark theme 🌟 
- In the light theme in particular many of the grey shades now have a subtly purple hue to vibe with the background.
- Code blocks now have a neon-y glow that is particularly visible in the dark theme.
- The dark theme Algolia DocSearch modal has been updated to match.
- The link cards on the Themes page have been tweaked to fit with the other changes.
Obviously this is all just me tinkering, so feel free to push back or reject any or all …

Make docs styling slightly fancier 💅

---

public/index.css

Fix RTL css `.header-link.depth-*`
**Before**: 
**After**:

fix rtl headers

---

src/components/LeftSidebar/SidebarContent.astro

The production build/hosting use a trailing slash but the nav links don't. This cases an extra 301 redirect request for every link.
This fixes the problem by adding the slash to the end of the sidebar links. I checked all the links and nothing is broken with this change.

add trailing slash for sidebar links

---

src/pages/en/core-concepts/framework-components.md
src/pages/en/guides/manual-setup.md

Slipping this in as a PR to the integration-docs branch, so that it's all contained together.
Updates some exisiting guides that currently explain how to add/update/edit the list of renderers in `astro.config.mjs`. Now, they contain instructions for/links to adding integrations.

Updated to existing pages w old render config instructions

---

src/components/Header/Search.css

Just noticed that the hovered item in the search modal with the light theme currently uses an illegible text colour. This PR fixes that.
| before | after |
|--------|-------|
| ![Screen Shot 2022-03-22 at 10 09 11](https://user-images.githubusercontent.com/357379/159445918-01373486-2d39-4d5e-91fd-f06bba9d8791.png) | ![Screen Shot 2022-03-22 at 10 09 26](https://user-images.githubusercontent.com/357379/159445928-b35a90f7-feb9-4fd6-9c74-66a30d00a444.png) |

Fix white on light grey text in DocSearch modal

---

src/pages/en/guides/publish-to-npm.md
src/pages/en/integrations/integrations.md

The new integrations library on astro.build will be live soon 🚀 [Related PR](https://github.com/withastro/astro.build/pull/50)
This adds docs to the "Publish to NPM" page describing what data we pull from NPM packages and what keywords we look for to organize them into integrations

Adding docs for the new integrations library

---

src/pages/en/reference/integrations-reference.md

This pull requests fixes broken examples links in the docs for the new integration system:
```diff
- lit/index.js
+ lit/src/index.ts
```

fix: broken examples links

---

src/pages/en/guides/deploy.md

Correcting the [Vercel-from-Git instructions](https://docs.astro.build/en/guides/deploy/#git) to use `dist` rather than `./dist` for the `Output Directory` settings. Using `./dist` will result in a deployment that renders a 404 for the home page.

Correction to Vercel-from-Git deploy instructions

---

src/config.ts
src/pages/en/guides/server-side-rendering.md
src/pages/en/reference/adapter-reference.md

This documents how to setup and use SSR features in Astro.

Server-side rendering docs

---

src/pages/en/core-concepts/framework-components.md

Fixes a link on the "Framework Components" concepts page which currently 404s:
1. click the link:
1. it 404s:

Fix broken link on "Framework Components" page

---

src/pages/en/reference/cli-reference.md

Just minor fixes, and updated to the same verb tense throughout all the commands.

CLI Reference - Quick typo/edits

---

src/config.ts
src/pages/en/editor-setup.md

Initial Editor Setup page draft, to highlight the Astro VS code extension

Editor Setup page w VS Code Extension info

---

scripts/docgen.mjs
src/pages/en/guides/configuring-astro.md
src/pages/en/migrate.md
src/pages/en/reference/configuration-reference.md

Includes the docgen file, but NOT the configuration-reference file, since it is auto-generated.
NOTE: I think the docgen file will address the top of the page config example in /reference/configuration-reference but this page ALSO contains `astro.config.js` in the section "project root." So, whatever generates that description should be updated.

Changed all astro.config references to .mjs

---

src/pages/en/guides/environment-variables.md

Should now render Environment Variables page in the same way api-reference renders.
ALSO: removed the reference to how variables were previously set in snowpack, because I think it's safe now.
@natemoo-re can you please review the current page for overall accuracy. I believe everything on this page is pretty much the same as on Vite's own page https://vitejs.dev/guide/env-and-mode.html and doesn't mention anything that appears Astro-specific. Is that how it should work? Is there anything to call attention to that is different than just "how it works in Vite?"

Replaced import.meta.env to render properly

---

src/pages/en/reference/api-reference.md

Updates API reference page to bring it inline with v1.0.0 Beta changes.

Update API Reference

---

src/config.ts

Looks like these got removed unintentionally by a merge or something. Adding them back here.

Add SSR doc links to the sidebar

---

src/layouts/InstallLayout.astro

Replaces the initial paragraph talking about “Astro CSS” in the installation guide.
> Astro CSS works by scanning all of your HTML files, JavaScript components, and any other templates for class names, generating the corresponding styles and then writing them to a static CSS file.
> Ready to install Astro? Follow our automatic or manual set-up guide to get started.

Quick fix to replace first paragraph in Install guide

---

astro.config.ts
public/index.css
src/components/RightSidebar/TableOfContents.tsx

Nesting the anchor inside the heading was causing it to be picked up by Google, but also could have a11y consequences if it was read by a screenreader as part of the heading.
This PR moves the anchor link out of the heading element and follows the guidance in this article to also make the links more accessible: https://amberwilson.co.uk/blog/are-your-anchor-links-accessible/
TLDR: This uses a structure like:
```html
<h2 id="id">Exciting New Feature</h2>
<a href="#id">
<span aria-hidden="true">#</span>
<span class="sr-only">Section titled Exciting New Feature</span>
</a>
```
1. Moving the link after the heading means the link itself isn’t read out in a screen reader table of contents, won’t be picked up by search engine crawlers, and as a bonus means we don’t need to strip it out when …

Fix anchor links

---

src/pages/en/core-concepts/routing.md

changing `Astro.reqest.params` to `Astro.request.params`

Fixing a typo in `routing.md` for `Astro.reqest.params`

---

src/pages/en/core-concepts/framework-components.md

Emergency fix replacing braces so that the page at least builds.

Temp fix: escape markdown in client:media directive example

---

astro.config.ts
src/pages/en/core-concepts/framework-components.md

Found the culprit! The auto-generated `sr-only` labels were not escaping any curly braces. Fixed this by adding the `is:raw` directive to any labels that are created.

fix: escape `sr-only` labels

---

src/pages/en/reference/configuration-reference.md

Fixes an outdated "see also" reference to the recently renamed config option.

Update `buildOptions.pageUrlFormat` to `build.format`

---

src/pages/en/comparing-astro-vs-other-tools.md

This might deserve a section on another page like `/component-syntax`, but it's a start.
> Just use `<head>`
doesn't convey that Astro doesn't duplicate `<head>` elements in child components of layouts in a way that `react-helmet` does
It was a bit confusing wording wise equating the two, so I added a caveat.
From what I understand, the current recommendation to add to `<head>` from a lower component is:
```astro
// MainLayout.astro
<HTML>
<head>
<title>tada this is my title in regular head</title>
<slot name="head/>
</head>
<body>
<main>
<slot/>
</main>
</body>
</html>
```
and then in `Component.astro`
```astro
<Fragment slot="head">
<title>this is a different title now :D</title>
</Fragment>
```

Improve `<head>` docs reference

---

src/pages/en/comparing-astro-vs-other-tools.md

Not 100% necessary and likely a temporary home for this concept, so take it or leave it! But as it has come up in support, this seemed like a quick way to have something to point people to and fits with the row above it for inline functions.
At the very least, it would create a search hit for "conditional rendering" and might help community members.

Added to .astro vs .jsx table: conditional rendering

---

src/pages/en/guides/markdown-content.md

I added this in [august 2021](https://github.com/withastro/astro/pull/1148/files#r690872040) because there was [a bug](https://github.com/withastro/astro/issues/1147) that would render `\n` as a literal newline, even inside code blocks. This should no longer be the case, so I'm removing it.
Also, now I get to be in the face pile :)

Remove unnecessary backslash

---

src/pages/en/core-concepts/routing.md

All routing examples still had `Astro.request.params`, though I'm happy to report that the console message was helpful in reminding me that this is deprecated! 😄

changed Astro.request.params to Astro.params in Routing doc

---

src/pages/en/guides/markdown-content.md

Not sure when was this update but TS is confirming it.

docs: markdownOptions renamed to markdown

---

src/pages/en/integrations/integrations.md

- Design buddy is a platform to get job on ui/ux
- Design build brings remote job to your door step
- Added Design buddy to the amazing list of Builtwith Atro to inspire others

Added a new site built with Astro

---

src/pages/en/migrate.md

Taking some feedback from Discord, our Migration Guides are great about noting what has changed but are lacking a bit on the "migration" piece.
This PR is intended to refresh our migration guide and clarify exactly _how_ one can expect to migrate from deprecated APIs to their replacements.

WIP: update migration guide for clarity

---

src/pages/en/guides/styling.md

Adding docs for advanced CSS imports using `?raw` and `?url`, related astro [PR #3020](https://github.com/withastro/astro/pull/3020)
**Unless you're building a component library, this probably isn't the feature you were looking for 😄**

Adding docs for ?url and ?css imports

---

src/pages/en/comparing-astro-vs-other-tools.md

Quick update for consideration based on @Princesseuh 's suggestion to have our IDE support link go to our new editor page (instead of to the VS code extension on the marketplace).

Update text and link for IDE support in vs. JSX chart

---

src/pages/en/guides/styling.md

A couple of users have asked recently about advice on setting and consuming postcss within their projects.
Since we can use `@container` and `@layer` queries, for backwards support users would need to install `postcss-preset-env` to their projects.
This short addition to the Styling Guide should suffice.

Add PostCSS usage notes to page

---

src/pages/en/guides/environment-variables.md

Refs https://github.com/withastro/docs/pull/286
There were still some remaining `import.meta.env` instead of `import[dot]meta[dot]env`.

Update environment-variables.md (Follow up #286)

---

src/pages/en/core-concepts/astro-pages.md

The Non-HTML Pages section in the Pages documentation asks the user to pass the old `--experimental-static-build` flag to use the feature. The notice is longer relevant. This PR removes that notice.

Removed notice from the Non HTML Pages section in the Pages documentation

---

src/pages/en/reference/api-reference.md
src/pages/es/reference/api-reference.md

[PR #3087](https://github.com/withastro/astro/pull/3087) updates `getStaticPaths()` to support numeric route parameters, ex: including a year/month/day in a blog post URL

Updating docs to list numbers as valid route params in getStaticPaths()

---

src/pages/en/core-concepts/framework-components.md

@hippotastic [noted on Discord](https://discord.com/channels/830184174198718474/830184175176122389/964827331640303636) that there’s no mention of the examples on astro.new on the frameworks page, so he hadn’t found it. This PR adds a note saying you can find examples of each framework in use there.

Add note about astro.new templates to Framework guide

---

src/components/HeadSEO.astro
src/config.ts
src/i18n/translations.ts

See https://discord.com/channels/830184174198718474/853350631389265940/966255545390624800 for context
Moves the Open Graph image source and alt text into the translations dictionary to support translating alt text. Moving the `src` here too is primarily to keep these two bits of content together so they get updated together, but in theory it would also support localising the OG image if it included text.

Make OG image translatable

---

src/pages/en/guides/deploy.md

Netlify requires additional settings if using `pnpm`. This PR adds notes for `pnpm` users when deploying to Netlify.

Added notes for pnpm users when deploying to Netlify

---

src/pages/en/guides/typescript.md

Without `https` it evaluates to `https://docs.astro.build/en/guides/typescript/astro.new`.

Fix external link to `astro.new`

---

src/pages/en/reference/api-reference.md
src/pages/es/reference/api-reference.md

Examples have couple issues:
- [es]: formatting issue
- [en]: typo or missed bracket, that lead to syntax error

fix(api-reference.md): fix typo

---

public/index.css
src/components/Header/Header.astro
src/components/LeftSidebar/Sponsors.astro

Right to left languages have a problem with some components styling, this PR fixes the problems I have encountered:
* "on this page" component border direction
* sponsors component direction 
* adding dir and lang attributes in HTML for sponsors and logo components
The expected behaviour would be something like what React.js docs does:
Fortunately, [CSS Logical Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties) help us fix this!
As you can see, I added explicit lang and dir attributes to sponsors and logo components, the lang attribute makes clear for screen readers it is in English, and not the person's specific language ([See Language of Parts on W3 website](https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html)). Sure, I could have used …

Improve docs rtl language support and acessibility

---

src/pages/en/core-concepts/component-hydration.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/core-concepts/layouts.md
src/pages/en/guides/configuring-astro.md
src/pages/en/guides/debugging.md
src/pages/en/guides/deploy.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/styling.md
src/pages/en/migrate.md

Used the new link checker to do an audit for broken links and fixed them. Scoped this to the `/en/` pages given the likely future upheaval that awaits other languages.
I did also remove one link completely because I don’t think anything like what it linked to exists any more.
```
*** Found 69 broken links in total:
[404] 47 broken page links
[ # ] 22 broken fragment links
```
```
*** Found 51 broken links in total:
[404] 35 broken page links
[ # ] 16 broken fragment links
```

Fix broken links

---

src/pages/en/install/manual.md

Because of `---` being present on the default frontmatter comment, I had a confusing initial experience while trying to copy and paste the content for my first page, in VSCode with the Astro plugin installed. I spent like 20 minutes digging around until I could understand what was going on. This PR fixes that initial experience by providing a valid synonym that doesn't include the triple dashes. More info about the issue in here: https://github.com/withastro/language-tools/issues/248

Fix initial manual page experience

---

src/pages/en/guides/markdown-content.md

Instructions still referred to buildOptions for setting draft posts.

updated Markdown drafts config instructions

---

src/pages/en/reference/api-reference.md

I'm unfamiliar with TypeScript, but it looks like the interface `CustomDataFile` is defined in a code sample, but then referenced as `<CustomFile>` just below. Maybe I'm just misunderstanding this code, though!

Fix typo: CustomFile --> CustomDataFile

---

src/pages/en/install/manual.md

Our current instructions only include dev/build/preview scripts, but then we send the user back to Step 3 of the automatic install instructions: "run start."
(This also matches the package.json scripts generated by `create-astro` / in our starter templates.)

Add start script to manual install instructions

---

src/components/TabBox.astro

Closes #387
Turned out `TabBox.astro` _imports_ the Markdown component, but didn’t actually use it, so this was an easy fix.

Remove unused imports from TabBox.astro

---

src/pages/en/core-concepts/partial-hydration.md

Page had a mix of island and islands when using the phrase "islands architecture." Now it does not.  :)

Consistent reference to islands architecture

---

src/pages/en/core-concepts/layouts.md
src/pages/en/guides/configuring-astro.md
src/pages/en/guides/data-fetching.md
src/pages/en/guides/imports.md

Only for the most minor of typo fixes, to keep them in one place and avoid excessive PR traffic.

Typo Fixes during final walk-throughs

---

src/pages/en/reference/integrations-reference.md

**Motivation:** Hackathon participants were confused how integrations should be built. This PR introduces detailed docs and examples for each API hook!

Edit: Add full hooks API reference for integrations

---

src/components/ImportMetaEnv.astro
src/pages/en/guides/environment-variables.md
src/pages/en/reference/api-reference.md

This fixes the need to write `import[dot]meta[dot]env` by adding an `<ImportMetaEnv />` component to render the correct string for us.
This works but inline components seem to trip up Markdown parsing slightly so some paragraphs need wrapping in explicit `<p>` tags. (Each opening `<p>` is followed by an empty new line as otherwise the _rest_ of the paragraph won’t be parsed…)
It’s clunky on the authoring side, but it does mean we can provide much more readable docs.
H/T to @Princesseuh for the component idea.
---
Relevant pages in the preview:
- Environment Variables: https://deploy-preview-412--astro-docs-2.netlify.app/en/guides/environment-variables/#getting-environment-variables
- Runtime API: https://deploy-preview-412--astro-docs-2.netlify.app/en/reference/api-reference/#importmeta

Use a component to render `import.meta.env`

---

src/pages/en/reference/directives-reference.md

The directives-reference page linked back to info about CSS styling, but not to our info about scripts in Astro components.

added link: directives reference back to scripts

---

src/pages/en/guides/integrations-guide.md

This adds a call-out link on the Integrations Guide in the docs, making sure people know that they can find specific integration about each integration itself by going to astro.build/integrations and clicking through to each integration's own GitHub repository.

Linked to integrations page from the Integrations Guide

---

src/pages/en/guides/styling.md

In response to a support thread, this both makes it explicit that an imported CSS file must follow the same rules as any other ESM import and links back to the page/section explaining the Astro component script.

Added explicit warning re: importing CSS files at the top

---

public/index.css
src/components/RightSidebar/TableOfContents.tsx

Adds styling indicating the part of the docs you're currently reading as you scroll the page. This only works for desktop, on mobile you can't see the table of contents as you scroll, so I didn't include it. Solution for #400 
See the gif as an example:
The performance difference on Lighthouse (looks like the preview deploy is slower but the other metrics are the same, so I think it doesn't really impact the overall performance, needs further testing):
| Preview  | Official |
| ![image](https://user-images.githubusercontent.com/61414485/166170523-274092d2-4e93-4351-a832-96301fa565ea.png)  | ![image](https://user-images.githubusercontent.com/61414485/166170539-002dd120-c178-4390-91e3-60aa88340537.png)  |
This is not 100% yet. I think there are some …

Add visual indicator to the table of contents

---

src/pages/en/install/auto.md

These instructions walk through the new create-astro wizard.
Looking for feedback! 
(I am undecided as to whether I like the steps of the wizard showing up in the right sidebar because of the header level. It wasn't my intention, but now that I see them there, I think I like them?)

Updated auto install instructions to match new create-astro wizard

---

src/pages/en/guides/environment-variables.md
src/pages/en/guides/rss.md

This documents our shiny new `@astrojs/rss` package (coming soon to an `npm` near you 👀 ). Some notable additions:
- **New "Using `@astrojs/rss`"** on our RSS guide
- **Revisions to the old `getStaticPaths` docs.** This will _not_ be removed for Astro 1.0, so we'll maintain this documentation for legacy purposes. 
- **A new "default environment variables" section** on our env variable docs. We introduced a new `import.meta.env.SITE` variable to pull off RSS, so I felt this deserved some documentation.

Feat: New RSS package!

---

.github/workflows/discord-congrats.yml

Adds the same awesome Discord notification on push/PR merge that we already have for `withastro/astro`, but this time for `withastro/docs`!
Note: This workflow requires a new Discord webhook to be created that posts to the `#docs` channel, and the webhook URL to be added to this repo under Settings -> Secrets -> Actions -> New repository secret with the name `DISCORD_WEBHOOK_CONGRATS`. Afterwards, you can merge this PR and will receive instant congratulations for it! 🎉

Feat: Add Discord Notification on Push

---

.github/actions/install/action.yml
.github/workflows/translation-status.yml
package.json
pnpm-lock.yaml
scripts/github-translation-status.mjs
scripts/lib/github-issues.mjs
scripts/lib/output.mjs

Adds a script that creates or updates a special "Translation Status Overview" summary issue on GitHub that provides an overview of the current Astro documentation translation status.
Also adds a GitHub workflow that runs this script on every push to the `main` branch.
An example of the summary issue maintained by this script can be seen here:
https://github.com/hippotastic/astro-docs/issues/2

Feat: Add translation status script and workflow

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/core-concepts/astro-pages.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/core-concepts/layouts.md
src/pages/en/core-concepts/project-structure.md
src/pages/en/guides/configuring-astro.md
src/pages/en/guides/imports.md
src/pages/en/guides/integrations-guide.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/server-side-rendering.md
src/pages/en/install/auto.md
src/pages/en/install/manual.md
src/pages/en/migrate.md

Set first batch of mostly core pages as i18nReady!
These pages should now be automatically listed at https://github.com/withastro/docs/issues/438 for translator reference.
Thanks, @hippotastic !

i18nReady: true for first batch of pages

---

scripts/github-translation-status.mjs

This PR adds a few little details to our new automated i18n tracker.
You can see a live preview of the changes here: https://github.com/delucis/docs/issues/1
- Adds a “Create page” link next to missing content:
This links to a GitHub UI for creating a new file with the correct name and pre-fills it with the basic Markdown frontmatter
- Displays each language’s full name in the todos list:
- Fixes the i18n guide link in the intro (h/t @hippotastic)
- Adds the emoji to the subheadings in each language’s todo section

Polish to the automated i18n issue

---

scripts/github-translation-status.mjs

Fixes mobile rendering of the “Create page” buttons in the i18n tracking issue. #446 added these but used normal spaces in the button text causing it to wrap across lines on narrow viewports. This replaces those with non-breaking spaces so the whole button always wraps together.

Prevent create page button breaking across lines

---

src/pages/en/core-concepts/framework-components.md

Adding a small slash to avoid being redirected to `https://docs.astro.build/en/core-concepts/framework-components/en/reference/directives-reference/#client-directives` and not `https://docs.astro.build/en/reference/directives-reference/#client-directives`

Adding missing slash before link to avoid wrong linking

---

src/i18n/fr/docsearch.ts
src/i18n/fr/nav.ts
src/i18n/fr/ui.ts
src/pages/fr/getting-started.md

Upgrading the translation to reflect latest changes.
Files affected:
- `getting-started.md`: Updates on the text and syntax made in the english version
- `nav.ts`: Adding all routes translation for future use when they'll be added
- `ui.ts`: Adding all ui components translations for a better experience
- `docsearch.ts`: Adding Algogia's docsearch translation according to [theirs doc](https://docsearch.algolia.com/docs/api/#translations)
Feel free to review changes and additions, open to discussion on the syntax and changes in sentences which could be misleading

i18n(fr): Updating `getting-started.md` and UI elements translation. 

---

src/i18n/fr/ui.ts

Adding line translation for the key `rightSidebar.github` in french added in #451

i18n(fr): Add rightSidebar.github for UI components translation

---

src/pages/en/guides/rss.md

@bholmesdev - please check this, and adjust as necessary to get it to render properly.  This might require fiddling, but the ideas are:
1. Where ever you're seeing `{{}}` in the preview render instead of `import.meta.env`, then you need to import (I've done) and use (I've done) this component instead of typing the phrase out directly. The rest of the expression can be passed as the`path=" "` attribute, and it will be formatted as code.
2. This component must be inside an HTML element, and can't be written inside regular Markdown. I've tried the simplest version first (just `<p>` tags enclosing the single line it's in). If this isn't sufficient, or screws up the rest of the rendering, then you'll have to "work your way out" converting larger and larger chunks to HTML until you have the …

import and use ImportMetaEnv component

---

src/pages/en/guides/rss.md

We discovered that `canonicalUrl` did _not_ work as expected in the `@astrojs/rss` package. So, we're asking users to apply this value manually as a required prop.
**Changes made**
- rename `canonicalUrl` option to `site`
- add note that `import.meta.env.SITE` only works in the latest 1.0 beta
- add `site` to all code examples, with explainer comments where applicable

Edit: make RSS canonicalUrl required

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/guides/markdown-content.md
src/pages/en/migrate.md
src/pages/en/reference/directives-reference.md

Updating files from the `/en/` docs regarding self closing tags technically wrong (according to spec) when specified in the docs
- changing `<slot>` to `<slot />`
- ~changing `<img>` to `<img />`~ — reverted
- changing `<Markdown>` to `<Markdown />`
- ~changing `<meta>` to `<meta />`~ — reverted
(contain also change for `migrate.md` removing useless spaces at end of line, (ty my IDE))

Adding slashes for tags when needed according to HTML's spec

---

scripts/github-translation-status.mjs

Repo-wide search & replace actions like fixing certain broken links could cause outdated translations to be suddenly considered "up to date". This PR fixes this logic and only allows "major" commits to cause a translation to become up to date.
Important: Please edit the summary issue https://github.com/withastro/docs/issues/438 and remove the footer section with the JSON state before merging this PR. This will cause all the i18n page freshness dates to be recalculated. This should also cause the `ja/getting-started.md` page to become outdated again after merging this PR.
I also added an automatic fallback to `withastro/docs` if the `GITHUB_REPOSITORY` env variable is not set, which makes running the script locally to test it more seamless.

Fix: Ignore minor updates when determining i18n freshness

---

.github/workflows/ci.yml
scripts/lint-linkcheck.mjs

This adds our link checker to the CI workflow. It shows up independently from the slug checker in the PR & push checks.
If any broken links are found, it returns an error code, which causes the CI check to show a red cross. It also attempts to find the Markdown source files containing the broken links and annotates the lines containing the broken links. The annotations can be seen in the "changed files" view of PRs and commits.

Feat: Add link checker to CI workflow

---

src/pages/fr/core-concepts/astro-components.md
src/pages/fr/core-concepts/astro-pages.md

Adding both `core-concepts/astro-components.md` & `core-concepts/astro-pages.md` into the french translation.
Open and ready for review !

i18n(fr): Adding `astro-components.md` & `astro-pages.md` translations

---

public/index.css
src/components/LeftSidebar/LeftSidebar.astro
src/components/RightSidebar/RightSidebar.astro

The docs are currently using the default scrollbar on the [`RightSidebar.astro`](https://github.com/withastro/docs/blob/main/src/components/RightSidebar/RightSidebar.astro) component. The default scrollbar is fine for the page itself, but on the table of contents, it creates an unpleasant look on larger pages. 
This PR adds the same custom scrollbar used on the [`LeftSidebar.astro`](https://github.com/withastro/docs/blob/main/src/components/LeftSidebar/LeftSidebar.astro) component as a starting point. 
I think it is worth discussing if we should maintain this more discrete scrollbar styling or change for one that is always visible.
| Astro docs  (current) | Nuxt.js docs | Astro docs (PR) |
| ------------- | ------------- |  ------------- |
| …

Improve "On this page" scrollbar

---

src/pages/pt-BR/install/manual.md

Portuguese translation for `install/manual.md` page.

i18n(pt-BR): Add `install/manual.md` page

---

src/components/TabGroup/InstallGuideTabGroup.astro

The tab group component used on the install pages was missing the trailing slash of the pages' canonical URLs, causing an inconsistency with the left sidebar URLs. This PR fixes the inconsistency.

Fix: Use canonical URLs in tab group component

---

src/i18n/de/ui.ts

Adds missing German strings to UI dictionary.

i18n(de): Add translations for `i18n/de/ui.ts`

---

src/pages/en/core-concepts/astro-pages.md

User reports that the terminology surround the use of "File Routes" was ambiguous and can cause some degree of confusion as a result.
Having seen where they are coming from, I have added some phrases to help reduce the ambiguity surrounding the terms used. 
Also took the opportunity to fix some of the tense and grammar on the page,
See comments: https://discord.com/channels/830184174198718474/853350631389265940/972847968724070491
Raised by; F5 S6

Minor changes - based on suggestions made by F5 S6

---

scripts/github-translation-status.mjs

Did you ever wish you could quickly jump to any existing translation right from the `Translation status by content` table in our [translation status overview issue](https://github.com/withastro/docs/issues/438)?
Well, today's your lucky day, because this PR adds that feature! No more clicks on 🔄 and ✔ symbols that do nothing - now they take you to the translated page!
Oh, and I've also made some previously invisible non-breaking spaces more visible to stop eslint from yelling at me. And fixed a bug that could cause links to the source change history for outdated translations to start at the wrong date.

Feat: Add links to translated pages in status table

---

src/pages/en/guides/integrations-guide.md

Instead of linking to the npm front page, this changes the integrations guide link to use a targeted search for the recommended astro integration keyword (`astro-component`): https://www.npmjs.com/search?q=keywords:astro-component&ranking=popularity
Thoughts on whether that is helpful?

Use a more targeted npm link for integrations

---

astro.config.ts

Disable `remark-smartypants`’s `dashes` option so that `--` is preserved (important for CLI flags for example.)

Don’t convert “--” to “—”

---

syntax-highlighting-theme.ts

We had a user run into an issue where they mistook `|` for `/` because it was being italicised by our syntax highlighter (see [Discord support thread](https://discord.com/channels/830184174198718474/973143587044864040)). That doesn’t seem great, so I suggest removing that italic styling.
Here’s the offending code sample:
| before | after |
|---|---|
| ![Screen Shot 2022-05-09 at 16 31 49](https://user-images.githubusercontent.com/357379/167432805-637b0b19-562d-47de-8326-b8dc926b08d2.png) | ![Screen Shot 2022-05-09 at 16 30 58](https://user-images.githubusercontent.com/357379/167432693-f04f55f0-98d6-46db-bf5a-3873d2ccafbf.png) |
It does impact elsewhere, like this below. Anyone know if there’s a way to target those things separately?
| before | after |
|---|---|
| ![Screen Shot 2022-05-09 …

Don’t italicise keywords in syntax highlighter

---

public/index.css
public/theme.css

I know we discussed this in #198, but seeing as #224 was closed on the basis that I’m “ON THE CASE, ON THE REG,” here I am! On the case!
The current link colour provides insufficient colour contrast in light mode by *quite a bit*. [Guidelines](https://webaim.org/articles/contrast/) require a minimum contrast of 4.5:1 for text content, but the orange links are only around 2.5:1, even lower for inline code snippets within links.
This PR switches links in the body content to use a purple instead of the current orange, which provides a passing colour ratio:
|---|---|
| <img width="694" alt="image" src="https://user-images.githubusercontent.com/357379/165913576-ab671b25-7291-4c33-8fac-ac939aff1ca2.png"> | <img width="664" alt="image" …

fix(a11y): Purple links in light mode for accessible contrast

---

src/pages/pt-BR/install/auto.md

Spotted by @victor0x16 
Typo: `succeso` -> `sucesso`

i18n(pt-BR): Fix typo on `install/auto.md`

---

.github/workflows/translation-status.yml
scripts/github-translation-status.mjs

This PR adds support for two new optional env variables to the translation status script:
- `ISSUE_NUMBER`: If set, the script skips the issue search and uses the given issue number. If this optional env variable is set in the workflow and the referenced issue is not found, the script will throw an error and abort.
- `ISSUE_TITLE`: I'm making this configurable through env variables as well in case we want to change the issue title in the future. This is especially important because the script validates the issue title to avoid accidentally changing the wrong issue.
I'm also updating the workflow to set the new `ISSUE_NUMBER` env variable to our existing issue #438. This should hopefully reduce the amount of rate limiting that occurs in our workflow.

Feat: Allow skipping issue search by configuring issue number

---

.github/workflows/translation-status.yml

My previous commit that added a fixed issue number to the translation status workflow caused workflow runs in forks to fail because an issue with number 438 does not exist there.
This PR fixes that by checking the repository owner and only using our hardcoded issue number if it's `withastro`. Workflow runs in forks will revert to the previous behavior which searches for the correct issue number based on the issue title.

Fix: Make translation status work again in forks

---

src/pages/en/core-concepts/astro-components.md

Adding more information regarding #521 
Including:
- Typescript support status with RFC link
- Script behavior depending of being `is:inline` or with `define:vars` attribute
- Exemples added for a better understanding
- Mention of multiple `<script>` tags on the same component not being an issue
- Note about defining other attribute than directives ones will break the bundling

Adding more accurate information about client side scripts

---

src/pages/en/reference/api-reference.md

This same caveat appears in the docs section on Markdown but not in the API section.

Add caveat about potential <Markdown /> deprecation

---

src/components/Header/Header.astro

The docs logo at the top-left currently always links to `https://docs.astro.build/` which gets redirected to the English version of the docs. This change means that we link to the current language, e.g. `https://docs.astro.build/fr/` to keep users on their current language if they use that link.
H/T to @hippotastic for spotting this.

Use language-specific link from docs logo

---

src/pages/en/guides/styling.md

Some minor fixes to this page. 
Notably, the link at the top of the page mentioning Tailwind now goes to our Tailwind Integration (instead of tailwind.org itself). We need to get users there more quickly, because that's where (not here!) we document instructions for each specific integrations, and Tailwind is a BIG one!

CSS Styling page final polish

---

src/components/Header/Search.tsx

Aria-label attribute cann't be used on a span with no valid role attribute. So I add `searchbox` role for it.

perf(a11y): add searchbox role

---

src/pages/en/comparing-astro-vs-other-tools.md
src/pages/en/core-concepts/astro-components.md
src/pages/en/core-concepts/astro-pages.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/core-concepts/layouts.md
src/pages/en/core-concepts/project-structure.md
src/pages/en/core-concepts/routing.md
src/pages/en/editor-setup.md
src/pages/en/getting-started.md
src/pages/en/guides/data-fetching.md
src/pages/en/guides/deploy.md
src/pages/en/guides/imports.md
src/pages/en/guides/integrations-guide.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/publish-to-npm.md
src/pages/en/guides/rss.md
src/pages/en/guides/styling.md
src/pages/en/guides/typescript.md
src/pages/en/install/auto.md
src/pages/en/install/manual.md
src/pages/en/integrations/integrations.md
src/pages/en/migrate.md
src/pages/en/reference/api-reference.md
src/pages/en/reference/cli-reference.md
src/pages/en/reference/directives-reference.md
src/pages/en/reference/integrations-reference.md

- What does this PR change? change *"small"* parts of the `/en/` docs links to include backslashes when needed to avoid unnessessary redirections.

minor: adding end-slashes when needed

---

src/pages/en/guides/environment-variables.md

On the current docs, the base config link doesn't work because it is using Markdown syntax inside HTML. This PR fixes this changing the Markdown link with an HTML `<a>` tag.
Original:
PR:

minor: Fix base config option link on `enviroment-variables.md`

---

src/pages/de/getting-started.md
src/pages/en/getting-started.md
src/pages/en/guides/deploy.md
src/pages/es/getting-started.md
src/pages/fr/getting-started.md
src/pages/ja/getting-started.md
src/pages/pt-BR/getting-started.md
src/pages/zh-TW/getting-started.md

As per the `install/auto` docs:
> No need to create a new directory first! The wizard will create a project folder for you.
But on the Getting Started page we still include an initial `mkdir && cd` step. This PR removes that from all languages that currently include it.

minor: Remove mkdir step from Getting Started install summary

---

src/components/PageContent/ArticleNavigationButton.astro
src/components/PageContent/PageContent.astro

This PR fixes two small bugs in the prev/next links in the page footer:
- The links were not using the proper canonical URLs of the target pages due to missing trailing slashes.
- The `rel="..."` attribute of the links was always set to `prev`, even for the `next` links.

Prev/next nav: Add trailing slash, use `rel` prop

---

src/pages/en/core-concepts/partial-hydration.md

- Replaces the static islands architecture image with our new, accessible `IslandsDiagram` component, allowing its contents to be translated in i18n versions of the page.

Replace image with translatable IslandsDiagram

---

src/pages/en/reference/cli-reference.md

Closes #516 
Some missing commands/flags to the cli-reference.
Would still be nice to explore automating this as mentioned in #209, but this is a manual fix for what @tony-sull has identified as currently missing.

Added commands/flags to cli-reference

---

src/components/RightSidebar/ThemeToggleButton.tsx

- Fixes a bug in the theme toggle control that prevented its `title` attributes from being used - instead, the title of the entire table of contents aka right sidebar popped up. Bug was confirmed on Chrome and Firefox:
- This PR fixes this by moving the title attribute up in the tree to make it work.
(In both screenshots, please imagine a mouse cursor pointing to the little sun icon.)
**Important:** I don't know if it would be a good idea to also move the `aria-label` attribute. I've kept it at the actual input element because this is the element with the semantic `checked` attribute and I was hoping that a screen reader would read this as something like "Checked option: Use dark theme". If anyone with access to a screen reader can verify if this is the correct solution, that would be …

Fix: Place theme toggle title attribute correctly

---

src/pages/en/reference/integrations-reference.md

Some colons were positioned after the bold markup, so they weren't bold as well. Now all my precious colons are bold.

minor: Fix colons position on `integrations-reference.md`

---

src/pages/en/reference/api-reference.md

I've updated the documentation so that it's more clear for developers on how they should be grabbing the current pathname.
The previous iteration of the docs is ambiguous  and implies that `Astro.site.pathname` will return the current pathname when it should be `Astro.canonicalURL.pathname`.

♻️ update instructions for grabbing the pathname

---

src/pages/en/guides/styling.md

The old `svelte-style` link header id was incorrect (probably because they changed the page), this PR simply adds the new link.

Update svelte styling docs link on `styling.md`

---

src/pages/en/guides/styling.md

- Resolves https://github.com/withastro/astro/issues/3226
- Break out separate section for importing stylesheets from an npm packages
- Change "import a Stylesheet" heading to "import a local stylesheet"
- Change "Load an External Stylesheet" to "Load a static stylesheet via "link" tags." _External_ might be confused to mean _npm package,_ so this title change should help!

New: add CSS-via-npm-packages guide

---

src/i18n/en/nav.ts

This only moves where the Routing page shows up in the Left Sidebar. The file stays in the same location, so no links should have to change. (No RIP link checker! 😅 )
Moving into Learn for now, tabling a later discussion on WHERE EXACTLY.
Also removing placeholders for hypothetical pages that have been scrapped and will not be written.
- [X ] Changes to the docs site code

Moves the Routing page's sidebar entry into Learn > Basics

---

src/pages/en/reference/integrations-reference.md

supersedes https://github.com/withastro/docs/pull/654
Adds the missing `routes` on the `astro:build:done` integration hook: for context https://github.com/withastro/astro/pull/3438#issuecomment-1136473008
No, just the signature for `astro:build:done` integration hook, adding the missing routes

docs(en): update integration-reference build end hook

---

src/pages/fr/guides/typescript.md

- What does this PR change? Adds `/fr/guides/typescript.md` to the french translation.

i18n(fr): Adding `typescript.md` translation

---

src/pages/en/migrate.md

The migration guide mentions to remove the `hoist` attribute from `<script>` tags when upgrading, but doesn't mention removing `type="module"` which causes unexpected behaviour when not removed.
Changes: 
Adds mention that, like hoist, type="module" should be removed as its default behaviour now
Also, links directly to the section in docs that does fully document current behaviour.
NOTE: No need to fully explain behaviour here on this page. It's well documented at the (now added) link in docs proper. And, this page is just for "steps to take to upgrade" so it only needs to exist in "do this!" form.
- [ X] New or updated content

migration guide improvement re: `<script type="module">`

---

src/pages/fr/getting-started.md

- What does this PR change? Normalize `/fr/getting-started.md` to the newer Astro's FR translation conventions defined by the french community glossary

i18n(fr): Normalize `getting-started.md` with newer pages

---

scripts/docgen.mjs

This file is auto-generated (never manually edited) in English, but we decided that translations would be manual.
Adding `i18nReady: true` to the generated header so that this page shows up in our pinned status tracking issue for translators.
Paging Dr. @delucis for approval. 😄

update the config-reference generated header for i18n

---

package.json
pnpm-lock.yaml

This updates the `package.json` to list PNPM version 7.0 as the supported engine.
Why the update to 7.0?  [Astro core](https://github.com/withastro/astro) requires the latest version of PNPM for some monorepo improvements, using the same version here helps make sure we don't run into lock file versioning issues when bouncing between `core` and `docs`

Updating PNPM engine version to 7.0 to match astro core

---

src/pages/en/guides/markdown-content.md

- Removes duplicate word "should" in `<Markdown />` component warning blocks

typo: Remove duplicate "should" text

---

.eslintignore
.eslintrc.js
package.json
pnpm-lock.yaml
scripts/lib/linkcheck/base/base.ts
scripts/lib/linkcheck/checks/target-exists.ts
scripts/lib/linkcheck/steps/find-issues.ts
scripts/lib/linkcheck/steps/output-issues.ts
src/components/Card.astro
src/components/HeadCommon.astro
src/components/LeftSidebar/LeftSidebar.astro
src/components/TabBox.astro
src/pages/index.astro

close #634
This PR introduces ESLint to the project. And, add the npm script `"lint:eslint"` to run ESLint.
I also made some simple fixes to some of the warned files.
However, the eslint configuration may need to be changed. Currently, it is based on the recommended configuration of eslint and each eslint plugin.
There are no visual changes.

Use eslint

---

src/components/Header/Header.astro
src/components/Header/LanguageSelect.css
src/components/LeftSidebar/LeftSidebar.astro
src/components/RightSidebar/RightSidebar.astro
src/layouts/MainLayout.astro

General accessibility improvements to the issues found in #620. No visible changes other than the focus indicators described below.
Reordered right sidebar to come before the main page content. This makes the DOM order more sensible. No CSS changes were necessary because it already has a grid-column set.
This also affects the "More" list and the theme button, which I feel like do not belong inside a "table of contents" section, but I didn't want to make huge visual changes.
Also removed the `title` attribute from both sidebars because it didn't make sense to me and was causing duplicate announcements in NVDA.
Fixed accessible name. Previously, NVDA was announcing the entire contents of the `nav` instead of just "Site navigation" or "Table of contents".
Added visible focus indicator to …

fix: Improve a11y

---

src/pages/pt-BR/guides/rss.md

i18n(pt-BR): Update `rss.md` based on #679 changes

---

src/components/RightSidebar/RightSidebar.astro

This PR adds padding to the `RightSidebar` component, so the component scrollbar (and the page scrollbar) don't overlap (if they're overlapping you can only drag the page scrollbar). This change only affects Firefox, since Chrome scrollbars automatically add padding to elements, unlike Firefox. This is important because some people can't use the mouse scroll wheel or are in their sister's laptops where the touchpad doesn't work well (this is not personal experience)
Here's a gif demonstrating what happens:
|  Before  | PR  |
|------------|-------|
| ![](https://i.imgur.com/zYYGGyu.png) | ![](https://i.imgur.com/Pp4Te9u.png)  |
Before merging, I want to confirm two things:
- Does this same problem happen in other non-Chromium browsers like Safari?
- Maybe we should add padding not only in …

Fix scrollbar overlapping issue on Firefox

---

README.md

Added note re: only add new content in English
Additionally: 
- adjusted call to create Issues and highlighted Discussions as an alternative for providing ideas/feedback
- updated example PR title/description to be a typo fix, not something that involves adding a new language and making changes to a sidebar (since our process for doing those things is now so much more involved than when that example was written, and we no longer want to encourage people adding a new language themselves!  😅 )

Add i18n instructions for English PRs to README

---

src/pages/en/reference/api-reference.md

In response to https://github.com/withastro/docs/issues/595 re: non-working code example 
- [ x] New or updated content
The offending code example has been commented out, pending a bug fix.https://github.com/withastro/astro/issues/3562
As noted in the code itself, in order to comment out code that had its own code comments... I had to get creative. Please take care when reverting.

commenting out broken astro.self example

---

src/components/RightSidebar/CommunityMenu.astro

On 800px screens unwanted `padding-left` was being applied, this PR fixes this edge-case:
| Current  | PR |
| ![NOHlkhB](https://user-images.githubusercontent.com/61414485/172948950-66108446-cfe7-41de-b234-64bfa0f52128.png)  | ![3u0uUmr](https://user-images.githubusercontent.com/61414485/172949102-55e90f3b-a6b9-4d96-8482-e75c6154edf3.png)  |

Fix `CommunityMenu` padding edge-case

---

src/pages/en/core-concepts/routing.md

`acess` => `access`
I really don't want to be the annoying person who just fixes typos, but I noticed one while reading the docs.
Fixes typo in `acess` => `access`

Fix typo in Routing guide

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
src/i18n/README.md

- [ X] New or updated content
Adds 2 new pages to the repository: CONTRIBUTING.md and CODE_OF_CONDUCT.md
COC: copied from withastro/astro. We can discuss the possibility of an automated mirroring to replace this.
CONTRIBUTING: Only a basic skeleton of a page to start, BUT we needed a place to document the new `Aside` usage without the main README getting cluttered.
(Also updated README section on contributing with a note to consult CONTRIBUTING.md for specific items of note. This will get better!  😅 )

Added two basic COC & CONTRIBUTING pages

---

src/pages/en/guides/troubleshooting.md

- Added a link to Svelte `onMount` docs, since Vue and React's equivalent APIs are also linked.
- Also added a period because other sentences in "Solution" have the period in the end(??).

add link to Svelte onMount docs

---

src/pages/en/reference/api-reference.md

It's a bit confusing that `id: 3` is a number whereas the other two are strings. When I first read this I thought it was a bug until I read above where it mentioned that strings and numbers can be used as parameters. I think it'd be nice to reflect that in the code block as well just to make it concrete.

♻️ clarify that a string or number can be used

---

src/pages/en/guides/server-side-rendering.md

Proposes a fix to https://github.com/withastro/docs/issues/793
- Change "is enabled" to "can be enabled", as SSR is not enabled by default
- Describe what a runtime is
- Add an explanation for why we need an adapter: it provides a runtime
- Clarification that if you don't need SSR, you don't need an adapter

Clarify why you need an adapter

---

src/pages/en/reference/integrations-reference.md

- update to `en` integration API reference: add `routes` to `astro:build:done` hook
- include `RouteData` type references to understand metadata options available
- chore: fix missing newlines on "when" and "why" sections. These were likely broken with the recent markdown enhancements in the latest beta.

Edit: add "routes" to `astro:build:done` integration API reference

---

src/components/Aside.astro

This PR fixes two small colour contrast issues in text within the new Aside component I spotted while investigating #620 (thanks @mayank99!)
Inside the Aside component
- text in bullet points is now the same colour as surrounding body copy (I’d intended this initially but messed up the CSS selector)
- text in inline `<code>` snippets is now a little brighter in dark mode to ensure sufficient contrast

a11y: Fix contrast issues in Aside component

---

package.json
pnpm-lock.yaml
src/components/ImportMetaEnv.astro
src/pages/en/guides/environment-variables.md
src/pages/en/reference/api-reference.md
src/pages/es/guides/environment-variables.md
src/pages/fr/guides/environment-variables.md
src/pages/pt-BR/guides/environment-variables.md
src/pages/pt-BR/reference/api-reference.md

- Fixes https://github.com/withastro/docs/issues/612.
- Updates Astro to `1.0.0-beta.51`, which includes a fix that allows using `import.meta.env` directly in Markdown code. As this fix made our clever workaround of using an `ImportMetaEnv` Astro component unnecessary, I've removed the component and replaced all references to it with plain Markdown.
- I've also converted unnecessary HTML tags (`<p>`, `<ul>`/`<li>` etc.) to their proper Markdown variants.
- Marking this as "Minor" to avoid affecting translation up-to-dateness. I have also updated the translated content, so this change does not cause todos for translators.

Minor: Remove import.meta.env workaround, use Markdown syntax

---

astro.config.ts
package.json
plugins/remark-fallback-lang.ts
pnpm-lock.yaml

- Fixes https://github.com/withastro/docs/issues/646.
- Adds an `(EN)` suffix to the link text of links pointing to pages that have not been translated yet.

Feat: Add fallback language indicator to links

---

src/components/Header/SidebarToggle.tsx

This PR changes the mobile hamburger menu behavior (before, it collapsed all sections), opening the current page section by default on mobile. I believe this small change improves the mobile navigation UX a lot. Example gif (as you can see, my sister's laptop isn't fast):
NOTE: When we are on `deploy/(service)` or `install/manual` no page is highlighted as the current one, is this something we can easily change as part of this PR (or should we tackle this as a separate issue/PR), so when we are on "nested pages" we are still highlighting the deploy/install page link?

Sidebar: Open current page section on mobile

---

src/pages/en/guides/typescript.md

Add "outDir": "./dist" to tsconfig.json to fix "Cannot write file '.../astro.config.mjs" because it would overwrite input file.` error.

Add "outDir": "./dist" to tsconfig.json

---

src/components/LeftSidebar/SidebarContent.astro

- Closes #905 
- #849 introduced a small bug that the current page item’s text was white even when in light mode. This fixes that.

Fix current sidebar item text colour in light mode

---

netlify.toml

#849 moved the deploy guides from `/[lang]/deploy/[service]` to `/[lang]/guides/deploy/[service]` causing some 404s from old links like in Discord threads. This Netlify redirect makes sure we redirect from the old URLs to the new ones.

Redirect to the new deploy guides location

---

src/pages/en/core-concepts/layouts.md

"See the example above for how to..." prompted me to reorder the layout examples (so that we don't need to do that!)
Now: 
- examples are more sequential and meaningful given the explanations by moving Nested Layout section to the end
- took out "Example" from all the code sample file names, because I don't think we do that elsewhere
- corrected some typos (e.g. `/layout/` vs `/layouts/` in some places)

Reorder Layout page examples

---

src/pages/pt-br/guides/typescript.md

Updated PT-BR `typescript.md` page based on #853 changes

i18n(pt-BR) Update `typescript.md` based on #853 changes

---

src/pages/en/guides/typescript.md

Fixes `extention` -> `extension`

minor: Fix typo on `typescript.md`

---

src/pages/en/guides/deploy/netlify.md

- Closes #884 
Adds back info about specifying a Node.js version on Netlify if you have an older project using a legacy build image. (Was previously commented out as part of the older page's restructuring. This updates and reintroduces it.)

Netlify deploy page - added Nodejs version info

---

src/pages/en/guides/markdown-content.md

- Closes #910 
Simplifies wording for Markdown drafts, and provides a short example of filtering as well as a link back to `Astro.glob()`

Updated markdown draft explanation with example

---

public/index.css
public/theme.css
src/components/Header/Header.astro
src/components/LeftSidebar/LeftSidebar.astro
src/components/PageContent/PageContent.astro
src/components/RightSidebar/RightSidebar.astro
src/components/RightSidebar/TableOfContents.css
src/components/RightSidebar/TableOfContents.tsx
src/layouts/MainLayout.astro
src/layouts/SplashLayout.astro

- Improves the sticky TOC on mobile devices like iOS Safari:
- The TOC was not sticky on iOS Safari before, now it is
- Scroll anchors are no longer obscured by sticky elements
- You can now tap on top of the screen to go to the beginning of the page again
- The dynamically resizing Safari tab bar now works again instead of being stuck in the expanded state
- Improves the sticky TOC on all devices with medium viewports:
- Instead of the TOC being below the article heading and scrolling/stopping out of sync with the left sidebar, it is now always at the top of the main column (as discussed on Discord) and scrolls in sync with the left sidebar.
- Cleanup: Reduced magic numbers across the CSS code by moving them to clearly named variables in …

Improve sticky TOC on mobile devices and medium viewports

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/install/manual.md

Changes:
`astro-components.md`: `using the using (...)` -> `using the (...)`
`manual.md`: `Next steps` -> `Next Steps`

Fix typos on `astro-components.md` and `manual.md`

---

public/index.css
public/theme.css
src/components/Header/Header.astro
src/components/LeftSidebar/LeftSidebar.astro
src/components/PageContent/PageContent.astro
src/components/RightSidebar/RightSidebar.astro
src/components/RightSidebar/TableOfContents.css
src/layouts/MainLayout.astro

- Instead of having our header navigation disappear when scrolling on wide viewports, this PR changes all of our headers to a fixed position, effectively unifying our header behavior for all devices & viewport widths.
- As discussed on Discord, this allows the Search bar to be always easily accessible without having to scroll up.
- Unifying the header positioning also allowed to clean up our CSS code quite a bit, removing the now unnecessary grid layout and improving the browser's ability to keep the current scroll position when resizing the viewport. It's still possible for the content to jump a bit when any of the sidebars disappear, but it's a lot better than before.

Use fixed header navigation on all devices

---

public/index.css

- This PR adds some “quick wins” in terms of vertical spacing in our main content styles, improving list spacing and spacing around headings.
Here’s one before/after example:
| before | after |
|---|---|
| <img width="810" alt="image" src="https://user-images.githubusercontent.com/357379/178007967-891d4899-25cf-485f-9811-d9339ba625be.png"> | <img width="794" alt="image" src="https://user-images.githubusercontent.com/357379/178007896-f77a89b7-a092-42e4-97a0-002d7c1f3ef0.png"> |

Overhaul of vertical spacing

---

src/pages/en/guides/typescript.md

This type assertion was missing from the "TypeScript" page, while it's present
at other places. The assertion is necessary to have proper type info in the component itself.

Add type assertion to Astro.props

---

scripts/lib/github-issues.mjs

In #954 I extracted a function from the translation status checker to a separate module so I could re-use it in the page generator. I messed up the updated import inside the translation status script, leaving out the `.mjs` extension which is required.
This PR fixes that.

Fix import in translation status script

---

src/pages/en/reference/adapter-reference.md
src/pages/en/reference/integrations-reference.md

- Add "installation via astro add" instructions for integration authors
- Add "installation via astro add" instructions for adapter authors

New: `astro add` support instructions for integrations and adapters

---

src/pages/en/guides/configuring-astro.md

According to Rollup's documentation `entryFileNames`, `chunkFileNames`, and `assetFileNames` should be defined in an `output` object. For instance, note what's described for [emitted assets](https://rollupjs.org/guide/en/#outputassetfilenames). This change, that has been tested, fixes this minor omission.

Proper Rollup output configuration options

---

src/pages/en/core-concepts/sharing-state.md

@FredKSchott  Just a quick update to the one page that currently links to the page `en/core-concepts/partial-hydration`.
You may want to look at the link text to make sure that's still what you want it to say, but at least the link itself is correct.

Patch to WIP-WHY-ASTRO branch: fix link: partial-hydration -> islands

---

src/pages/en/guides/typescript.md

- Closes #984
- Adds a “Built-in attribute types” subheading to the Typescript page’s “Component Props” section that explains how to use and also extend Astro’s built-in JSX definitions.
@Princesseuh I tried these examples out in the docs repo and it seems to work without the need for the `///` directive. Would you mind reading through this and letting me know if you think this covers what you imagined? 💜

Document use of Astro’s JSX types

---

package.json

Adds `react`, `react-dom`, and `@types/react` to optional peer deps. This should fix install errors after the react -> preact compat refactor!

Add react to optional peer deps

---

.npmrc
package.json

Adds `strict-peer-dependencies=false` to our `.npmrc`. This prevents install failures for `react` and `react-dom`. Note: we tried to explicitly silence failures for React in this PR #1028, but it seems this wont affect nested package peer dependencies 😢

Set strict-peer-dependencies=false to fix `react` dep errors

---

src/pages/en/core-concepts/framework-components.md
src/pages/es/core-concepts/framework-components.md
src/pages/fr/core-concepts/framework-components.md
src/pages/pt-br/core-concepts/framework-components.md
src/pages/zh-cn/core-concepts/framework-components.md

- Closes #1025
- Reformat codeblocks in `core-concepts/framework-components.md` for every available language

fix: Reformat code samples on UI frameworks page

---

src/components/IntegrationsNav.astro

This PR changes the card's links to your current page language so that we can use fallback pages for languages where the individual integrations pages aren't translated yet without breaking the link checker.

Change `<IntegrationsNav>` links to the current page language

---

src/pages/en/migrate.md

Adds the beginnings of a RC migration guide so we can update it incrementally as upstream PRs get merged & released.
Only includes Vite 3 so far as other changes are pending upstream PRs (Markdown component, Astro.url, etc.)

Add stub Release Candidate migration guide

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/guides/troubleshooting.md

- Removes tips/warnings that import statements must go on top of your `.astro` files!
- Replaces old debugging tip with new "unexpected export" tip
- Blocked by https://github.com/withastro/compiler/pull/463

Remove "imports on top" warning

---

src/components/RightSidebar/ContributeMenu.astro
src/components/RightSidebar/RightSidebar.astro

This PR removes the "translate this page" link on the `<ContributeMenu>` component for translated, non-i18nReady, and fallback pages (if they aren't `i18nReady`).
| `i18nReady: false`  |  Fallback  |  Translated  |
| ------------------- | ------------------- | ------------------- |
|  ![image](https://user-images.githubusercontent.com/61414485/180251304-3bfffd35-9f95-4e66-8f6f-144f5b343181.png) |  ![image](https://user-images.githubusercontent.com/61414485/180251886-1be01842-2b17-490a-bafc-566d8a090866.png) | ![image](https://user-images.githubusercontent.com/61414485/180252305-bb744b8f-b9f3-45ca-9e4a-fc8f10b01434.png) |

Remove translate link in non-`i18nReady`, fallback and translated pages

---

src/layouts/SplashLayout.astro

- Closes #1050 
The 404 page content was being hidden because of CSS conflicts, this PR simplifies the SplashLayout code so that the 404 page is visible again. We can discuss if we want the 404 page content aligned to the middle or left, I just went with what was more similar to what we already had.
| docs.astro.build  |  Deploy Preview  |
| ------------------- | ------------------- |
| ![image](https://user-images.githubusercontent.com/61414485/180206364-1d2f5192-d012-4432-b6ba-0b6174314451.png) |  ![image](https://user-images.githubusercontent.com/61414485/180206410-e2684dab-3679-4579-b26a-5fe2e0ea435d.png) |

Fix invisible 404 page

---

src/i18n/README.md

Starts to address issues of i18n guidance for translators.
- Adds more explicit warning re: when NOT translate
- Inclues link to CONTRIBUTING to see more about when things are/aren't marked for translation (TODO: which will include description of using phrases like "minor" and "typo" there, since it's really the English contributors who need to know about this).
- TODO: move this file, probably just to `src` like the other READMES until we decide on a better location for all the README guides?

[i18n README]: Adds extra warning re: do not translate

---

src/pages/en/migrate.md
src/pages/en/reference/api-reference.md

- Docs PR for RFC https://github.com/withastro/rfcs/pull/232
- Marks `Astro.canonicalURL` as deprecated
- Adds new documentation for `Astro.url`

deprecate Astro.canonicalURL & add Astro.url

---

.github/labeler.yml
.github/workflows/pr-labeler.yml

- Github action that labels i18n to all `.md` files in pages except for pages in `/en/`
**Note**: This is not a YOLO PR. This was tested in a copy of the docs repo. I couldn't get the action to include the i18n folder without failing but "not worse than what we had before" 😅

add i18n labeler

---

src/pages/en/core-concepts/project-structure.md

- Fixed a typo.
- A compound predicate with only two verb phrases requires no punctuation to separate them. Hence removed the unnecessary comma.

Fixed unnecessary comma usage

---

src/pages/en/core-concepts/project-structure.md

- Fixed grammar related to article usage
- An article like "a/an" or "the" should be used before a singular countable noun to establish what the noun refers to. Hence added "a" before the nouns.

Fixed article usage

---

src/pages/en/getting-started.md

- Fixed article usage problem in docs.
- An article like "a/an" or "the" should be used before a singular countable noun to establish the reference to the noun. Hence added "the" before the noun.

Fixed article usage problem

---

src/pages/en/comparing-astro-vs-other-tools.md

- "built-in" and "time-consuming" are compound words that require a hyphen.
- "built-in" is used with a hyphen in some places and without a hyphen in other places.
- "use case" doesn't require a hyphen.

Fixed compound words grammar usage

---

.eslintrc.js

- Updates our ESLint configuration to support TypeScript syntax in `<script>` tags in Astro components now that that is possible. See background on Discord: <https://discord.com/channels/830184174198718474/878341752799494154/1000124056483401908>

Configure ESLint to parse Typescript in `<script>` tags

---

src/pages/en/core-concepts/astro-pages.md
src/pages/en/core-concepts/routing.md

Explicitly mentions using a standard HTML `<a>` tag for linking to other pages on your site. There is no provided `<Link>` component.
To close #992

Clarify linking between pages

---

src/pages/en/guides/markdown-content.md
src/pages/en/migrate.md
src/pages/en/reference/configuration-reference.md

Updating the docs to reflect the new "legacy" mode for Astro-flavored markdown in [PR #4016](https://github.com/withastro/astro/pull/4016)
- Deprecates the "Authoring markdown" section with a note on how to re-enable the features until they are removed in a future Astro release (no timeline on that, I'd guess 2.0?)
- Adds configuration docs for the new `legacy.astroFlavoredMarkdown` flag

Deprecating the "Authoring markdown" section and adding config docs for the new legacy flag

---

.gitignore
package.json
pnpm-lock.yaml
src/components/ContributorList.astro
src/components/Since.astro
src/components/Version.astro
src/util.ts

- Adds a `cachedFetch()` function to `utils.ts` which uses `@11ty/eleventy-fetch` to cache `fetch()` calls.
- Mimics the `Response` object returned by the `fetch()` API.
- Hopefully makes Astro Docs builds and Netlify deploys more resilient.

Add `cachedFetch()` function to speed up builds

---

src/pages/en/guides/markdown-content.md

Stop-gap to make sure Markdown JSX and components REALLY looks deprecated:
- without yet breaking existing anchor links, so change goes through quickly and 
- while still keeping these features visible (albeit achieved through MDX now).
-

[Markdown content] md to mdx

---

src/pages/en/migrate.md

Removes the `pnpm i -D astro@next--rc` command from migration as it is no longer needed

Remove pre-rc upgrade command

---

src/pages/en/guides/rss.md

Vite's `globEager` is deprecated as per Vite's TypeScript docs. The suggested change as per TS & Vite's [Official Docs](https://vitejs.dev/guide/features.html#glob-import) is to use `import.meta.glob('....', { eager: true })` instead, having the exact same output.

Docs: Update deprecated usage of import.vite.globEager

---

src/components/ContributorList.astro
src/components/Since.astro
src/components/Version.astro
src/util-server.ts
src/util.ts

- Fixes a hydration issue preventing the TOC from updating.
- In PR #1120, I added an import from `@11ty/eleventy-fetch` to `util.ts`, which is both being used in the frontmatter scripts of `.astro` files, but also in our TOC preact component. Apparently tree-shaking isn't being applied properly in this case, so hydration of the TOC component failed.
- I fixed the issue by moving the import and the code using it into a new `util-server.ts` file that is only referenced by server-side code.

Fix hydration by moving code into server-side file

---

src/pages/en/guides/markdown-content.md
src/pages/en/migrate.md

Adds a section to the migration guide re: converting an existing `.md` file to `.mdx`
- includes reminder to update any `Astro.glob()` statments.
This looks long, and I don't like that. We could hide it in a `<details>`?  😅  But, I think this is helpful to people with existing "Astro Flavored Markdown" files who now want to convert to `.mdx`.  Even some of our more experiences users were not sure what to do.
And of course, once we reintroduce `layout:`, this whole matter is much simpler, and much of this can be removed/streamlined. I'm only thinking of helping people immediately. And, I think this at least does that.

[migration guide] added md to mdx checklist section

---

src/pages/en/concepts/islands.md

Add code snippet titles to `islands.md`

---

src/pages/en/guides/typescript.md

Added instructions on how to use multiple JSX frameworks at the same time with full TS support. Also added some info about `@types/react` mistakenly typing `.vue` files when installed

Add instructions on how to use multiple frameworks at the same time in TypeScript

---

src/i18n/de/ui.ts

- Making changes regarding #1041
-  Is  `navbar.a11yTitle` making sense when using a German Screen Reader? I would say so but I haven't tested it yet.

i18n(de): Nav a11y changes

---

src/pages/en/migrate.md

relies on https://github.com/withastro/astro/pull/4088
Since @bholmesdev gave us `layout:` in MDX, we no longer have to tell people to use a Layout component when converting their `.md` files to `.mdx`
This removes that step, and updates the MDX code sample to show no `<Layout>` component being used, in favour of `layout:` in the frontmatter (which should be what they had before).
NOTE: While there is more exciting MDX layout stuff possible now, for the purposes of just explicitly explaining how to convert an *existing* Astro `.md` file to a working `.mdx` file, we don't need to mention that.

[migration guide] Moving to MDX does NOT require changing layout

---

integrations/astro-code-snippets.ts
src/components/CodeSnippet/CodeSnippet.astro
src/components/CodeSnippet/shiki-line.ts
src/components/CodeSnippet/types.ts
src/pages/en/migrate.md

- Improved the inline marking authoring experience by adding support for plaintext matches in addition to the existing regular expressions.
- Here's an overview of the new plaintext matching syntax options:
- `"Astro.props"`
(if no marker type prefix is given, it defaults to `mark`)
- `ins="<Button />"`
(matches will be marked with "inserted" style)
- `del="<p class=\"hi\">"`
(special chars in the search string can be escaped by `\`)
- `del='<p class="hi">'`
(use single quotes to make it easier to match double quotes)
- Marked `migrate.md` using all available syntax options as an example.

Allow inline marking of plaintext strings

---

src/components/CodeSnippet/shiki-line.ts
src/components/CodeSnippet/types.ts

- Fixes cases where Shiki tokens contain additional styles like bold or italics. Before this fix, such tokens were not recognized and removed from the output in the code snippet marking phase.
- Before:
- After:

Fix Shiki tokens with styles other than `color`

---

src/pages/en/guides/data-fetching.md

Mark code in `data-fetching.md`

---

src/pages/en/guides/deploy/github.md

- New or updated content 🎉 
- Closes #1164
- What does this PR change?  I updated GitHub Action workflow to deploy Astro on GitHub Pages. GitHub officially supports deploying static websites written in any framework on GitHub Pages. There's a specific one that works well for Astro. 
- Did you change something visual? 
**BEFORE**
**AFTER**
Working examples:
From engineer at GitHub on the Pages-Actions team: https://github.com/tcbyrd/astro-portfolio-demo/blob/main/.github/workflows/astro-build.yml
My own repo: https://github.com/blackgirlbytes/blackgyalbites-astro has a working example as well

New GitHub action workflow for pages

---

src/pages/en/install/auto.md
src/pages/en/install/manual.md

Installing Astro with Node.js version 16.5.0 fails:
> error @astrojs/telemetry@0.4.1: The engine "node" is incompatible with this
> module. Expected version "^14.18.0 || >=16.12.0". Got "16.5.0"
Update the docs to reflect the minimum required Node.js versions.
Update the docs to reflect the minimum required Node.js versions.

Fix wrong Node.js version numbers

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/troubleshooting.md

Apologize that this took a bit of a turn...
MAIN CHANGE: Brings the `astro vs jsx` chart into `astro-components`, since it currently lives on a page that is no longer linked to on our site. Location of the chart on this page is my proposal, but open to feedback.
FALLOUT:
- `astro-components`: reorganizes headings to address everything falling under "Component Overview". Mostly brings every heading level up one, makes for a nicer right sidebar TOC.
- `troubleshooting`: updates link to this chart and while right there, I noticed reference to old components in Markdown to fix, which should now refer to using components in MDX. (The tip is still appropriate, only to MDX instead of Markdown.)
- `markdown-content`: Adds a new `MDX` section, with analogous "using …

Moving astro vs jsx comparison (formerly chart) and resulting fallout

---

src/pages/en/guides/images.md

Fix one typo in the images page on the mdx integration. Uses `@astrojs/image/component` instead of `@astrojs/image/components` for importing `<Image />`.

Fix typo in images guide

---

src/pages/en/comparing-astro-vs-other-tools.md

This small PR changes "offers" to "provide "to fix a typo in the Hugo vs. Astro comparison (it should have been "offer", not "offers") and add more word variety (offer is used in the previous sentence).

fix comparison typo

---

src/pages/en/concepts/islands.md
src/pages/en/core-concepts/astro-components.md

Removes hyphens from the phrase "ahead of time" on two pages where it doesn't seem necessary.

Remove hyphens from phrase ahead-of-time

---

src/pages/en/guides/typescript.md

In https://github.com/withastro/astro/pull/4171, we're including a new `.d.ts` file inside people's projects that will replace the usage of the `types` field inside `tsconfig.json`. The reasons for this change are outlined in the PR. So this is the docs part of that effort 😄

Add mention of new `env.d.ts` file to TypeScript page

---

src/pages/en/guides/markdown-content.md
src/pages/en/migrate.md
src/pages/es/guides/markdown-content.md

I did remove the text with the Release Candidate. However I still added:
> The Astro v1.0 *(and all the Release Candidates for it)* introduces some changes [...]
However maybe we could even remove that little notice as normally you don't install a RC when there's the actual release already.

Remove RC when talking about Astro v1

---

src/pages/en/guides/markdown-content.md

- Change "Markdown props" -> "Markdown layout props" for clarity
- Remove `.astro` object from Markdown
- Introduce new props alongside `content`: `headings`, `rawContent`, and `compiledContent`
- Update old `getHeaders` -> `getHeadings`

New Markdown layout props API

---

src/pages/en/core-concepts/astro-components.md

Phrase had the word "can" two times.
- ~~Closes #~~ Closes no open issue
In the section concerning [JSX-like expressions](https://docs.astro.build/en/core-concepts/astro-components/#jsx-like-expressions) the word "can" appears twice. Removed one so that the phrase "You can can define local JavaScript variables..." reads better.

Fixed typo in JSX-like Expressions

---

src/pages/en/core-concepts/astro-components.md

- ~~Closes #~~ Closes no open issues
In [this section](https://docs.astro.build/en/core-concepts/astro-components/#differences-between-astro-and-jsx) the phrase reads "...but there a couple of key differences between .astro files and JSX." I added the word "are" so that it then reads as "...but there are a couple of key differences between .astro files and JSX."

Fixed typo in differences between astro and jsx

---

src/pages/en/guides/images.md

Fixed the Picture component example of the `formats` prop where the array should be wrapped in curly braces.
formats={["avif", "webp"]} instead of format=["...", "..."]
Fixed the Picture component example of the `formats` prop where the array should be wrapped in curly braces.
Ex: formats={["avif", "webp"]} instead of format=["...", "..."]

Updated images.md Picture's formats prop

---

src/pages/ja/core-concepts/astro-pages.md

- Updated Japanese astro-pages.md to match the English update
- https://github.com/withastro/docs/commit/c09a2f5c083cd5d80c96098c936022f90d488bdf
- https://github.com/withastro/docs/commit/55b0e331d59961b976fdcef64d1b0d1da4bcdf1f

i18n(ja): Update Japanese `astro-pages.md`

---

src/pages/en/guides/deploy/cloudflare.md

This PR Update Cloudflare's adapter usage in Astro docs
- Closes # 

[Docs]: Update Cloudflare docs to show adapter support

---

src/pages/en/guides/aliases.md

Closes https://github.com/withastro/astro/issues/3729
Added a note block to show `baseUrl` is required to be set for import aliases to work. Astro would skip aliases if not set based on https://github.com/withastro/astro/blob/e918b3883e156a0de2148517b619a2cf451917d2/packages/astro/src/vite-plugin-config-alias/index.ts#L39.

Note baseUrl is required for aliases

---

src/pages/en/comparing-astro-vs-other-tools.md

This adds an "unmaintained content" aside to the top of a page that exists in Docs but is not currently linked to, as it is still being discovered by search engines. Since we haven't yet decided what to do with this page, this notice informs readers that it is simply unmaintained, not hidden for any nefarious reasons!

Adding an "unmaintained content" aside

---

src/pages/en/guides/deploy/vercel.md

Removed the bullet point because the environment variable is not needed anymore. See https://github.com/withastro/astro/pull/4020

Remove `ENABLE_VC_BUILD` from vercel deployment guide

---

src/pages/en/core-concepts/framework-components.md

Added a line with a link to AlpineJS installation instructions (adding a `<script>` to head) because not having an official Astro integration to install led to questions and confusion.

[AlpineJS] Add comment and link to AlpineJS installation

---

src/pages/en/core-concepts/layouts.md
src/pages/en/guides/markdown-content.md

Change all references to the Markdown layout `Astro.props.content` property to `Astro.props.frontmatter`. Both will continue to work, but `frontmatter` should be the new recommendation. Seemed a _bit_ much to add deprecation notices everywhere, so I'm voting for a clean sweep for 1.0 stable here!

Markdown `content` prop -> `frontmatter` prop

---

src/pages/en/guides/markdown-content.md
src/pages/en/reference/api-reference.md

Picks up the last few pieces from #1107 that weren’t done yet:
- API reference: `getHeaders()` -> `getHeadings()`
- Use “headings” over “headers” in Markdown guide
- Use a codeblock for the return type to avoid awkward linebreaks.

`getHeadings` clean up

---

src/pages/zh-cn/editor-setup.md

I fixed a formatting misalignment caused by a markdown syntax error.
This is what it looked like before the modification. This paragraph puzzled me for a long time until I realized that it was misaligned.
And here is what the page looks like after I modified it.

i18n(zh-CN): Misalignment caused by grammatical errors for `editor-setup.md`

---

src/pages/zh-cn/core-concepts/framework-components.md

- fix ghost word
- change the word `字` to `子` in [`向框架组件传递字组件`](https://docs.astro.build/zh-cn/core-concepts/framework-components/#%E5%90%91%E6%A1%86%E6%9E%B6%E7%BB%84%E4%BB%B6%E4%BC%A0%E9%80%92%E5%AD%97%E7%BB%84%E4%BB%B6)

i18n(zh-cn): fix ghost word

---

src/pages/zh-cn/core-concepts/framework-components.md
src/pages/zh-cn/guides/markdown-content.md

- reverse the unnecessary code translation
- The code block translation is not necessary, and it is strange to translate `slug` to `蛞蝓`.
- Link: https://docs.astro.build/zh-cn/guides/markdown-content/#%E5%AF%BC%E5%85%A5-markdown

i18n(zh-cn): reverse the unnecessary translation

---

src/pages/en/guides/server-side-rendering.md

Noticed we were still pointing to the adapter packages on GitHub from the SSR page. This updates those links to use the docs versions of those READMEs.

Use docs integration guides instead of GitHub links

---

package.json
pnpm-lock.yaml
scripts/lib/github-get.mjs

Adds retry logic to our `githubGet` helper to try and mitigate the regular CI failures we get for “Invalid response body” when generating integration pages. Here’s a recent example: <https://github.com/withastro/docs/runs/7837529942?check_suite_focus=true#step:4:18>

Add retry logic to fetch

---

scripts/github-translation-status.mjs

- Fixes broken link to i18n guide.
- Selects the correct plural form of `need(s) updating` based on the number of pages.

Fix i18n guide link, fix `need(s) updating` plural

---

MAINTAINERS.md
src/components/FallbackNotice.astro

- Fixes more broken links to the moved i18n guide, including the language fallback notice box and the maintainers guide.

Fix more broken links to moved i18n guide

---

src/pages/en/guides/deploy/cloudflare.md

Troubleshooting section wasn't intended to be for SSR only, so hoisting the heading level!

Fix heading level in Cloudflare deploy guide

---

src/pages/de/guides/deploy/github.md
src/pages/en/guides/deploy/github.md

This PR adds a German translation of the guide for deploying Astro sites to GitHub pages.
It also removes a superfluous closing bracket.

i18n(de): add GitHub pages deploy guide

---

scripts/docgen.mjs
scripts/generate-integration-pages.ts
src/components/DontEditWarning.astro
src/layouts/MainLayout.astro
src/pages/en/guides/integrations-guide/cloudflare.md
src/pages/en/guides/integrations-guide/deno.md
src/pages/en/guides/integrations-guide/image.md
src/pages/en/guides/integrations-guide/lit.md
src/pages/en/guides/integrations-guide/mdx.md
src/pages/en/guides/integrations-guide/netlify.md
src/pages/en/guides/integrations-guide/node.md
src/pages/en/guides/integrations-guide/partytown.md
src/pages/en/guides/integrations-guide/preact.md
src/pages/en/guides/integrations-guide/prefetch.md
src/pages/en/guides/integrations-guide/react.md
src/pages/en/guides/integrations-guide/sitemap.md
src/pages/en/guides/integrations-guide/solid-js.md
src/pages/en/guides/integrations-guide/svelte.md
src/pages/en/guides/integrations-guide/tailwind.md
src/pages/en/guides/integrations-guide/vercel.md
src/pages/en/guides/integrations-guide/vue.md
src/pages/en/reference/configuration-reference.md

This PR changes the configuration reference "edit this page" link to the proper Astro type definitions file instead of the docs generated file that shouldn't be changed. Also, a dev-only warning as added so none of us forget about this:
Note: The comments we have in the file don't show up in GitHub's Markdown Preview, so it's easy to don't see them. Now, having the weird `<DontEditWarning/>` we have an extra security/warning layer.
Observations:
- Before, we added `README.md` to pages' "edit this page" link with the custom `githubURL` prop by default. Instead of doing this, I opted for adding the `hasREADME` frontmatter prop so we can opt-in/out of this behavior as we please, we can sure discuss what could be the best approach here.
- I tried a few methods …

Improve configuration reference warning and edit this page link

---

src/pages/en/guides/imports.md

Astro doesn't support CSS-in-JS for `.astro` files, and it only supports _some_ CSS-in-JS for framework components. This PR removes the mention of CSS-in-JS.
We may also want to outline the extent of its support in framework components, but for now this removes a misleading statement.

Remove CSS-in-JS reference

---

src/components/tabs/Tabs.module.css
src/components/tabs/Tabs.tsx

- Updated `Tabs` component, adding a fancy animation when the user switches tabs.
- Adds fancy tab switching animation to... one of the many different tabs components. This one seemed the most general, so it was the one I modified.
Before:
https://user-images.githubusercontent.com/74938858/183867083-b67d32b2-2864-4c15-ba9d-ba9000c71a60.mov
After:
https://user-images.githubusercontent.com/74938858/183866697-3f469246-7f1a-4b7c-bde0-bfe4b030afb8.mov
Some of the CSS I had to change seemed kinda sketchy, so LMK if something's broken. I also changed the focus styles from applying on `:focus` to on `:focus-visible` (which has slightly lower browser support - [around 89% according to caniuse](https://caniuse.com/css-focus-visible) because it was running the effect).
Fun fact: this was the first …

Make the tabs fancy

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/guides/typescript.md

Remove `as Props` from typescript guide

---

src/pages/en/guides/markdown-content.md

It looks like https://github.com/withastro/astro/pull/4138 is going to make it in the next minor release, so i'm reopening this PR in order to document the new options!
That Astro PR adds the possibility to use remark rehype options in the Astro config, for instance if a user wants to translate automatically generated elements related to the footnotes. This Astro docs PR adds the relevant docs.

Add remark rehype options to markdown content docs

---

src/pages/en/guides/markdown-content.md

We have a new way to preserver Astro's default remark plugins when you apply your own: `extends`! https://github.com/withastro/astro/pull/4474.
This PR addresses a couple concerns:
- Add short explainers on remark and rehype based on [the MDX docs](https://docs.astro.build/en/guides/integrations-guide/mdx/#remarkplugins). New markdown users _probably_ don't know what these plugins can do or where to find a list of popular options (I definitely didn't a month ago). This should make plugins easier to understand.
- Move tip on Astro's defaults to in-line explainer
- Replace `remark-autolink-headings` example with `remark-toc`. Autolink headings is the one plugin we _shouldn't_ recommend, since it conflicts with Astro's own heading ID plugin 😅 
- Add new code examples …

New `remark` and `rehype` plugin explainer with `extends`

---

src/pages/en/guides/deploy/github.md

- Closes #1355 and #1376
- Reorder steps: Pushing and committing the workflow before setting up pages in the repository throws an [error](https://github.com/kevinzunigacuellar/gh-pages-rep/runs/7964873732?check_suite_focus=true#step:2:27)
```shell
Failed to create deployment (status: 404) with build version 
fcb3c6ad752990f1ea041c7971c0c3f71ac43117. Ensure GitHub Pages has been enabled.
```
- Switch **Source** from branch to Github Actions: deploying from branch uses Jekyll to deploy [(error link)](https://github.com/kevinzunigacuellar/gh-pages-rep/runs/7964905392?check_suite_focus=true)
- Add a caution aside for people that added base only to deploy to GitHub pages to update their routes relative to `base`.
- Added a fancy codeblock title

fix github pages deploy guide

---

src/pages/es/core-concepts/astro-components.md

added note on dynamic vs reactive values
- Update Astro Components (JSX-like Expressions section) with a note on dynamic vs reactive values

i18n(es): astro-components update

---

src/pages/en/core-concepts/framework-components.md

I fixed a typo. `about about ` -> `about ` in the page `https://docs.astro.build/en/core-concepts/framework-components/`. Before and after images below.

Fix typo `about about ` -> `about `

---

src/pages/en/guides/publish-to-npm.md

- Updates the list of `package.json` used to populate the [Integrations Catalog](https://astro.build/integrations)
- astro.build looks for the `withastro` keyword now as well, `astro-component` is a little confusing depending on the type of integration or adapter
[Related PR](https://github.com/withastro/astro/pull/4558) adding the `withastro` keyword to all adapters

Updating the list of keywords used for the integrations catalog

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/core-concepts/astro-pages.md
src/pages/en/guides/server-side-rendering.md

- Moves the _Modifying `<head>`_ section into the Layouts section of `/core-concepts/astro-pages`
- Clarifies that there is no special handling of the `<head>` tag
This addresses #1378.
The behavior of the `<head>` tag has little to do with the difference between JSX and Astro components. It does have to do with certain libraries within the React ecosystem, but that is not due to the JSX syntax. Documenting `<head>` makes more sense in the Layouts section of `Astro Pages`, because we recommend using the tag in a Layout, so I moved it there. (I could also see moving this to its own section within `Astro Pages`).
The section itself was unclear, as #1378 describes. Astro does not have any special handling of `<head>`, and I updated the wording to make that more …

Modifying `<head>`: clarity and placement in the docs

---

src/pages/en/guides/server-side-rendering.md

Recently discovered that layouts and components can't use SSR features. This wasn't previously mentioned in the docs, so I'm adding a little warning for this.
Matthew's comment on the subject ("Is not being able to use SSR features on layouts expected behavior?"): 
> It's because of streaming. You can only send headers / status code once and by the time we render a layout the headers are already sent. so it is intentional, but unfortunate.
NOTE: I tested all three features listed below and all of them didn't seem to work. I did expect that `Astro.request.headers.get` or `Astro.redirect` would work, but that doesn't seem to be the case. I appreciate someone double-checking this so we are sure I haven't made a mistake here.

Add warning about SSR features inside layouts

---

src/pages/en/getting-started.md

a11y guidelines state that heading levels should increment by one level at a time (e.g. `<h4>` must be preceded by an `<h3>`) We were using `<h4>` for the first two headings on the docs homepage, which violates that rule. I suspect this was to keep these headings out of the sidebar or for stylistic reasons (smaller font size).
I’ve switched back to `<h2>` to fix this a11y issue (it impacts Lighthouse scores amongst other things), and used a literal `<h2>` tag for the first mini section to avoid that showing up in the table of contents.

minor: Fix heading levels on docs homepage

---

src/i18n/ja/nav.ts

- Japanese navigation has been updated to match the English navigation.
- https://github.com/withastro/docs/pull/1440

i18n(ja): Update Japanese `nav.ts`

---

src/pages/en/core-concepts/project-structure.md

- Closes #1435 
- Explains that there are two options for specifying dependencies, and recommends `dependencies` as per #4544
- Note that our [package publishing docs](https://docs.astro.build/en/guides/publish-to-npm/) may have different advice. That page needs a complete overhaul, so I'm leaving it for now.

Recommend using `dependencies` over `devDependencies` in package.json

---

src/pages/es/core-concepts/astro-components.md
src/pages/es/core-concepts/astro-pages.md

- Moved "modificando `<head>`" to Astro Pages (taking that out from Astro components)
- Update Astro Components with "Etiquetas dinámicas" section that contains a note on variables

i18n(es): Update astro components and astro pages

---

src/pages/es/guides/deploy.md
src/pages/es/guides/deploy/cloudflare.md
src/pages/es/guides/deploy/deno.md
src/pages/es/guides/deploy/flightcontrol.md
src/pages/es/guides/deploy/github.md
src/pages/es/guides/deploy/netlify.md
src/pages/es/guides/deploy/vercel.md

- Update with these changes:
- [guides/deploy.md](https://github.com/withastro/docs/commits/main/src/pages/en/guides/deploy.md?since=2022-08-24T23:34:17.000Z)
- [guides/deploy/cloudflare.md](https://github.com/withastro/docs/commits/main/src/pages/en/guides/deploy/cloudflare.md?since=2022-08-27T23:04:47.000Z)
- [guides/deploy/deno.md](https://github.com/withastro/docs/commits/main/src/pages/en/guides/deploy/deno.md?since=2022-08-24T21:23:17.000Z)
- [guides/deploy/github.md](https://github.com/withastro/docs/commits/main/src/pages/en/guides/deploy/github.md?since=2022-08-18T22:00:08.000Z)
- [guides/deploy/netlify.md](https://github.com/withastro/docs/commits/main/src/pages/en/guides/deploy/netlify.md?since=2022-08-20T08:32:29.000Z)
- …

i18n(es): update deploy guides

---

TRANSLATING.md

This PR adds a few more things to our i18n guide:
- Add guidance for glossaries/style guides at `i18n/README.md` 
- Add code samples guidance.
- Emphasize Discord participation.
- Emphasize reviews.
- Mention that now that the "Translate this page" button disappears for pages that are not available, you can use the Docs as a way to quickly see if a page is available.
- Reorder headings.
- Review tips and shoutout!

Further expand `TRANSLATING.md` with more tips and guidance

---

src/pages/en/guides/configuring-astro.md
src/pages/en/guides/styling.md

- Two small content tweaks to support https://github.com/withastro/astro/pull/4662
- We still mention one Common JS file that uses `.js` in [the Layer0 deploy guide](https://docs.astro.build/en/guides/deploy/layer-zero/), but this seems to be a file their CLI creates, so I’ve left that as is. Let’s see if we get any bug reports.
- There’s also a line that needs changing in the Tailwind integration README. Going to request that happen as part of @natemoo-re’s astro PR.

Small updates to prepare for examples using `"type": "module"`

---

src/pages/en/concepts/why-astro.md
src/pages/en/core-concepts/astro-pages.md
src/pages/en/core-concepts/framework-components.md
src/pages/en/core-concepts/layouts.md

- Closes #1154 
This PR adds more accessibility info to different pages, solving the issues we found in our content accessibility audit.

Add more accessibility sprinkles

---

src/pages/en/guides/integrations-guide.md
src/pages/es/guides/integrations-guide.md

- Delete mention of the `--experimental-integrations` flag which is no longer needed.
- The Spanish translation also included this information and is otherwise completely up-to-date so I’ve removed this there too.
- `fr`, `pt-BR` and `zh-CN` also still include this, but those pages also need other updates, so I’ll leave that to our translators

Delete outdated mention of `--experimental-integrations`

---

src/pages/en/guides/environment-variables.md

- Env-vars examples have been removed in this PR (https://github.com/withastro/astro/pull/4606), therefore the link in the documentation in no longer leading anywhere.

Remove broken link to env-vars examples

---

src/pages/en/guides/markdown-content.md

Did you know we have a helper for type-safe markdown layouts? Well, yeah we do! This adds a little example for type safety to our existing `layout` section.

new: add `MarkdownLayoutProps` example to layout

---

.github/workflows/discord-congrats.yml

#1199 added a CI task to automatically format our source code with Prettier after each commit merges into `main`. This PR adds a check to our congrats bot action so that when a `[ci] format` commit lands, we don’t congratulate the bot on Discord.

Skip congrats bot action on `[ci] format` commits

---

src/components/Footer/Footer.astro
src/i18n/en/ui.ts
src/layouts/MainLayout.astro
src/layouts/SplashLayout.astro

Adds a minimal footer to the docs site with a link to [the updated astro.build privacy policy](https://astro.build/privacy/).
The link label can be translated in the `ui.ts` i18n files under the key `footer.privacyPolicy`.

Add footer with link to astro.build privacy policy

---

src/pages/en/concepts/mpa-vs-spa.md

Correct typo: "Wordpress" -> "WordPress".
Fixes a typo.

Correct typo in docs

---

src/pages/en/reference/integrations-reference.md

Fix ignored word "start" and unexpected line break after second colon in markdown link title
Before
After

fix ignored word after colon

---

src/pages/en/reference/directives-reference.md

- To address #1407, explain that `defer` and similar attributes don't work on inlined scripts
- Explain _why_ `define:vars` implies `is:inline`.

Script is:inline clarifications

---

src/pages/en/guides/configuring-astro.md
src/pages/en/guides/environment-variables.md

We closed #785 as the corresponding feature was closed, but the note about Astro being unable to load env variables is still important information, even if we don't have a workaround. This PR restores that note and adds a corresponding one to the environmental variables change.
I could see us only wanting one of those two messages, or rather wanting this to be in Troubleshooting. Let me know!
@natemoo-re, if there's currently a workaround to access env variables in Astro, let me know.

Environment variables can't be used in config files

---

src/pages/en/reference/api-reference.md

- Minor content fixes
`params` only accepts strings, but the documentation says that numbers are allowed as well.
Closes #1591

Only Strings are accepted as parameters.

---

src/pages/en/core-concepts/astro-components.md

Matthew clarified in [a support thread](https://discord.com/channels/830184174198718474/1021446382982266910/1021468769102598206) the other day that the dynamic tag pattern we document won’t work for components using `client:*` hydration directives.
This PR updates that section in the component docs to note this limitation.

Add clarification to dynamic tags about hydration directives

---

src/pages/en/core-concepts/project-structure.md

Adds a new (recommended) file to the tree diagram and includes a file description for `tsconfig.json`. 
This follows a recent docs addition which adds a step in manual-install to create this file. We should now be including this in our standard project structure, too. Since not absolutely required, but since we are saying elsewhere it's pretty much needed, I chose to label it as "recommended" and updated the label for the `astro.config.mjs` file to match. (Less confusing than having two different labels when people are likely to also need the astro config file at some point, too -- *"What's the difference between optional and recommended??"*)
Also includes some minor text edits to match current usage and existing page titles:
- updates old wording of "frontend …

[add] Include tsconfig.json on project structure page

---

src/pages/en/reference/directives-reference.md

- This pairs with a new feature in https://github.com/withastro/astro/pull/4832

Document new types for set:html

---

src/pages/en/reference/api-reference.md

Docs for how `Astro.glob()` treats `.astro` and other file formats got displaced when documenting `Astro.props`. This PR moves them back up to the correct location on the page.

API reference: fix displaced `Astro.glob()` subheadings

---

src/pages/en/guides/troubleshooting.md

- `yarnrc.yml` was missing initial dot, should be `.yarnrc.yml`
- Reference: https://yarnpkg.com/configuration/yarnrc

Fix: `yarnrc.yml` --> `.yarnrc.yml`

---

src/pages/en/install/auto.md
src/pages/en/integrations/integrations.md

Added a brief mention about `--template` to the auto install page, and a shell example to the hidden `integrations.md` page.
Not sure if that's the best place to do it, but I didn't want to clutter the install page, and at least it will show up in search now.

Document `create-astro --template`

---

src/pages/en/core-concepts/sharing-state.md

It can be a bit confusing as to why React and Solid were not mentioned--is sharing state between these two not as seamless as it is between the others? Hope that this slight change in wording can help.
Alternatives could be ".. sharing state between the supported frameworks ..", " .. Astro's supported frameworks .. "
- Small wording change in the Nanostores docs

Docs: Nanostores/Clarification on supported frameworks

---

src/pages/en/core-concepts/astro-components.md
src/pages/en/guides/typescript.md

- Removes `export` requirement for the `Props` interface. You no longer need it for types to work!

Edit: remove `export` requirement for `Props`

---

src/pages/en/reference/api-reference.md

Docs for `Astro.cookies`
Docs for https://github.com/withastro/astro/pull/4876

Add API reference for Astro.cookies

---

src/pages/en/guides/styling.md

- Closes #1642
- Introduces the two relevant cascading order factors: specificity and order of appearance
- Describes the precedence of scoped styles, imported styles, and link tag styles relative to each other
- Shows examples for each feature
- Explains that the later imported style has higher precedence
- Explains [as per this comment](https://github.com/withastro/docs/issues/1642#issuecomment-1262917210) that when a component imports styles, they're imported at the same time as the component, and shows an example of this being relevant

Documenting Cascading Order: Introduction and Examples

---

scripts/congrats-bot.mjs

- Replaces the message breaking `--` with `––` instead, as to not break discord markdown.
- Closes #1615  

Changes breaking text in congrats-bot.mjs script

---

src/pages/en/core-concepts/endpoints.md

This PR removes `localhost:3000` from some links, fixing them.

Fix `endpoints.md` links

---

src/pages/de/guides/deploy/github.md
src/pages/en/guides/deploy/github.md
src/pages/es/guides/deploy/github.md
src/pages/fr/guides/deploy/github.md

This should avoid the error message about "txt" not being a supported language for Markdown code. I've changed every lanaguage, so am using the `en-only` keyword to prevent a status update trigger.

[error msg fix] change "txt" lang to "js" in Github deploy instructions [en-only]

---

src/pages/en/guides/deploy/gitlab.md

As noted on #1382:
- The documentation had an unclear explanation to why we need to set `dist` to `public` and `public` to another value.
- The given `astro.config.mjs` example did not reflect the steps in the guide
This PR include my attempt to better explain that `public` is required to be the output folder for GitLab Pages, with links to the documentation to the `public` directory and an example of a `astro.config.mjs` after setting `public` to `static` and `build` to `public`. Some of the phrases are based on the example repo files, as is the decision to use `public` as `static` in the example.
It also includes useful comments that were on ".gitlab-ci.yml" from the example repo.
Finally, it fixes a small typo (removing the dot from `.site`)
I'm taking part on …

Improve deploy/gitlab.md documentation

---

src/pages/en/guides/troubleshooting.md

- Since [this fix](https://github.com/withastro/astro/pull/4831) was merged, we no longer need to document this gotcha.
That said, maybe we should keep it and say that it was fixed in 1.3.0?

Remove Invalid Hook troubleshooting entry now that it's fixed

---

package.json
pnpm-lock.yaml
src/pages/open-graph/[...path].ts

- Closes #1695 
- Removes an `import.meta.glob` call that was tanking dev server performance on start up
- The workaround is not particularly pretty. Basically I hand-roll a minimal version of Astro’s glob + parse Markdown pipeline that does just what we need in this context: globs all the `.md` pages, parses their frontmatter with `gray-matter` and gives us `title` and `description`. At least in my local tests, this resolves our issues although obviously it’s not battle tested, so a Windows test might throw up some path weirdness?

Workaround for `import.meta.glob` perf issue

---

src/pages/es/guides/typescript.md

- What does this PR change? Give us a brief description. Update TypeScript guide to #1699

i18n(es): revise and elaborate typescript intro

---

src/pages/es/install/auto.md
src/pages/es/install/manual.md

- Minimal changes to keep it similar to the english version
- Minimal changes to keep `install/auto.md` and `install/manual.md` similar
- Like the `auto` version using the word `comenzar` and the `manual` one using `empezar`. Now both uses the same word
- Change `Typescript` with `TypeScript`
- Added missing punctuation marks
- Minimal fixes
Please label this PR with `hacktoberfest-accepted` if get approved. 🎃

i18n(es): update `install/auto.md` and `install/manual.md`

---

src/pages/pt-br/guides/deploy/github.md

This PR updates the pt-BR translation for `deploy/github.md`.
I was unsure on the best way to translate "optional inputs", since "opções opcionais" would sound repetitive. I decided on "parâmetros" but I'm not sure if this is a technical term being used in the wrong context, so I would appreciate feedback on that.
I'm also unsure if it should be "o lockfile" or "a lockfile", but since in earlier translation we decided on "...escaneia por uma lockfile para detectar..." I decided to use "a lockfile".
I'm still taking part on hacktoberfest :jack_o_lantern:

i18n(pt-BR): update deploy/github.md translation

---

src/pages/es/core-concepts/astro-components.md
src/pages/es/core-concepts/astro-pages.md
src/pages/es/core-concepts/framework-components.md
src/pages/es/core-concepts/project-structure.md
src/pages/es/core-concepts/routing.md
src/pages/es/core-concepts/sharing-state.md
src/pages/es/guides/configuring-astro.md
src/pages/es/guides/data-fetching.md
src/pages/es/guides/deploy.md
src/pages/es/guides/environment-variables.md
src/pages/es/guides/images.md
src/pages/es/guides/imports.md
src/pages/es/guides/markdown-content.md
src/pages/es/guides/publish-to-npm.md
src/pages/es/guides/rss.md
src/pages/es/guides/server-side-rendering.md
src/pages/es/guides/styling.md
src/pages/es/guides/troubleshooting.md
src/pages/es/integrations/integrations.md
src/pages/es/reference/adapter-reference.md
src/pages/es/reference/api-reference.md
src/pages/es/reference/configuration-reference.md
src/pages/es/reference/directives-reference.md
src/pages/es/reference/integrations-reference.md

- Check and fix minor grammar typos for core-concepts pages
- Check and fix minor grammar typos for reference pages
- Check and fix minor grammar typos for integrations page
- Check and fix minor grammar typos for astro guides pages

i18n(es): check grammar for core-concepts, reference, and integrations pages

---

src/pages/en/guides/deploy/deno.md

The corrected version of #1783, inserting a missing comma to a `package.json` example.

fix: missing package.json example comma

---

src/pages/en/core-concepts/endpoints.md
src/pages/en/reference/api-reference.md

New feature docs for https://github.com/withastro/astro/pull/4986
Add API reference for endpoint context
The docs are pretty simple for now. Let me know if there's anything that can be improved!
Once the heading names are confirmed, I'll also update https://github.com/withastro/astro/pull/4986 to have the JSDoc point to the anticipated link.

Add endpoint context API

---

src/pages/en/core-concepts/sharing-state.md
src/pages/en/guides/deploy/layer-zero.md
src/pages/en/guides/deploy/netlify.md
src/pages/en/guides/deploy/surge.md
src/pages/en/guides/deploy/vercel.md
src/pages/en/guides/fonts.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/rss.md
src/pages/en/guides/styling.md
src/pages/en/migrate.md
src/pages/en/reference/api-reference.md

In all code samples within `./src/pages/en/**/*.md`, I changed:
`npm i` --> `npm install`
`pnpm i` --> `pnpm install`
For consistency, in line with how it most often appears in the docs.
Find:
```
\b(p?npm) i 
```
Replace:
```
$1 install 
```

`npm i` --> `npm install`

---

src/pages/en/concepts/islands.md
src/pages/en/core-concepts/endpoints.md
src/pages/en/core-concepts/layouts.md
src/pages/en/getting-started.md
src/pages/en/guides/data-fetching.md
src/pages/en/guides/deploy.md
src/pages/en/guides/deploy/deno.md
src/pages/en/guides/deploy/gitlab.md
src/pages/en/guides/integrations-guide/deno.md
src/pages/en/guides/integrations-guide/image.md
src/pages/en/guides/integrations-guide/mdx.md
src/pages/en/guides/integrations-guide/netlify.md
src/pages/en/guides/markdown-content.md
src/pages/en/guides/rss.md
src/pages/en/guides/server-side-rendering.md
src/pages/en/reference/api-reference.md
src/pages/en/reference/configuration-reference.md
src/pages/en/reference/integrations-reference.md

Found and fixed various indentation issues.
Many of these were found using this regex:
```
^(?!\d+\. +[^ \n])(?!setup: \|)[^ \n].+\n+ {3,}
```
(could also be written `^(?!\d+\. +[^ \n]|setup: \|)[^ \n].+\n+ {3,}`)
I changed some tabs to spaces -- when they were located with the regex above -- but I'm leaving the bulk of that work for another PR.
Whenever I was unsure, I looked at other code samples and the `withastro/astro` codebase to see which formatting conventions are (seemingly) preferred by Astro maintainers.

Indentation fixes

---

package.json
pnpm-lock.yaml

- Updates Astro to `1.4.7` (latest release)
This is needed for work on offline support since `vite-plugin-pwa` needs Vite `3.1.0` or greater, and Astro `1.2.1` (what the docs site is currently on) uses Vite `3.0.9`. I figured it would be much easier to get this done quickly in a separate pr to keep things tidy.

Upgrade to Astro 1.4.7

---

package.json
src/pages/open-graph/[...path].ts

It makes the `lint:linkcheck` command run 2 times faster by disabling OG image generation.
| ------ | ----- |
| ![Before](https://user-images.githubusercontent.com/37726261/194965964-5032c239-6443-4055-a5de-e82de792c1a3.png) | ![After](https://user-images.githubusercontent.com/37726261/194965998-bf427680-ff97-40bf-8b03-c74b4745a273.png) |
I'm participating in Hacktoberfest, so if PR is ok, I'd like it to be labeled as hacktoberfest-accepted.

ci: make linkcheck 2 times faster

---

src/pages/en/core-concepts/framework-components.md

- Replace a Caution which made it seem like the component framework JavaScript was sent on page load
- Add a client:only example to the code snippet, because we mention that "most directives" render the component on the server
- Make the intro more concise

Revise hydration section

---

src/pages/en/tutorial/1-setup/3.md

Adding a step to install the Astro extension when you first open the project in VSCode

Tutorial: add step to install astro extension

---

package.json
pnpm-lock.yaml
src/pages/open-graph/[...path].ts

After merging #1089 I noticed Open Graph images weren’t showing correctly for some pages in the tutorial because they use `/directory/index.md` naming for some pages and this was not handled correctly (generating `/directory/index.png` images instead of the expected `/directory.png`).
This PR fixes that by tweaking some logic in our endpoint but mainly by upgrading `astro-og-canvas` where I fixed the core logic (https://github.com/delucis/astro-og-canvas/commit/98be21325b1ea6c176ad563e96af0ba333b899c2).

Fix OG image generation for pages like `index.md`

---

src/pages/zh-cn/concepts/islands.md

it's markdown syntax error. add space after '**' to fix it.

i18n(zh-cn): Fix markdown typo

---

src/pages/en/reference/api-reference.md

Minor, `import { APIContext }` --> `import type { APIContext }`

Use `import type` for `APIContext` imports in reference

---

src/pages/en/tutorial/2-pages/3.md
src/pages/en/tutorial/4-layouts/1.md
src/pages/en/tutorial/5-astro-api/3.md

Replaced "JSX-like expressions" with "JavaScript expressions" in the two places it showed up.
Also, removed an internal link.

[tutorial] removed references to JSX

---

src/pages/en/tutorial/2-pages/3.md
src/pages/en/tutorial/2-pages/4.md
src/pages/en/tutorial/2-pages/5.md
src/pages/en/tutorial/3-components/2.md
src/pages/en/tutorial/3-components/3.md
src/pages/en/tutorial/4-layouts/1.md
src/pages/en/tutorial/4-layouts/2.md
src/pages/en/tutorial/5-astro-api/1.md
src/pages/en/tutorial/5-astro-api/2.md
src/pages/en/tutorial/5-astro-api/3.md

One of our participants noticed that we had inconsistent semicolon usage. This PR adds missing semicolons, and also fixes the `title`/`pageTitle` inconsistency in Chapter 5.

[tutorial] Consistent semicolons

---

src/components/tutorial/StackblitzIntro.astro
src/pages/en/tutorial/0-introduction/index.md
src/pages/en/tutorial/2-pages/index.md
src/pages/en/tutorial/3-components/index.md
src/pages/en/tutorial/4-layouts/index.md
src/pages/en/tutorial/5-astro-api/index.md
src/pages/en/tutorial/6-islands/index.md

Added a StackblitzIntro component so we can tweak this later on.

[tutorial] Replace StackBlitz embeds with links

---

src/pages/en/guides/styling.md

- Closes #995 
- Adds a new section on the Styling page, per [this comment](https://github.com/withastro/docs/pull/1011#issuecomment-1185737025)
- I focused on passing `class`, but made it clear that all HTML attributes don't automatically pass through
- Shows two examples: one where you don't destructure props at all, and one where you destructure but rename

Add a section on passing a class to a child component

---

src/pages/en/tutorial/1-setup/1.md
src/pages/en/tutorial/1-setup/2.md
src/pages/en/tutorial/1-setup/4.md
src/pages/en/tutorial/1-setup/5.md
src/pages/en/tutorial/1-setup/index.md

This addresses the feedback that the interleaved Stackblitz instructions were confusing. It pulls out the Stackblitz instructions into a single `<details>` on the Check In page. It also tells the user to log in _after_ opening Stackblitz with `astro.new`, instead of before.

[tutorial] Pull out and simplify Stackblitz instructions

---

src/components/Checklist.astro

Following up on some feedback that it wasn’t obvious that you could interact with the checklists in the tutorial. This PR tweaks the styling of the check marks in the `<Checklist>` component with the aim of making them look more clickable.
|---|---|
| ![image](https://user-images.githubusercontent.com/357379/197224298-cddbd22f-d204-4e81-ac4b-7bdfee5a8b14.png) | ![image](https://user-images.githubusercontent.com/357379/197224549-561b4865-2703-40d4-8456-f244244ce645.png) |
| ![image](https://user-images.githubusercontent.com/357379/197224351-08d43fbd-9a8b-4a82-a8f1-8403d0669a7c.png) | ![image](https://user-images.githubusercontent.com/357379/197224606-faa03dd9-770b-4137-8dfd-640d0b7c7a1c.png) |

Chonkier checklist checkmarks

---

src/pages/en/guides/integrations-guide/mdx.md
src/pages/en/guides/markdown-content.md
src/pages/en/reference/configuration-reference.md

1. Use `extendDefaultPlugins: true` in more code samples. There were a few that I didn't add it to.
My thought process when evaluating each one was basically: Would I expect this code sample to drop the default plugins as a side effect of adding a new plugin? Or, will I likely be carefully considering the behavior of the code sample, such that I am likely to understand that it drops the default plugins?
Another motivation for these changes is to reduce the likelihood of new users blinding copying these code samples, then being confused as to why they can no longer use GitHub-flavored Markdown.
2. Plus more extendDefaultPlugins cross-linking (minor). One indentation fix.
---
Preview links:
- [/en/guides/integrations-guide/mdx/](https://deploy-preview-1777--astro-doc …

Use `extendDefaultPlugins` in more code samples

---

src/components/tutorial/StackblitzIntro.astro
src/pages/en/tutorial/0-introduction/index.md
src/pages/en/tutorial/2-pages/index.md
src/pages/en/tutorial/3-components/index.md
src/pages/en/tutorial/4-layouts/index.md
src/pages/en/tutorial/5-astro-api/index.md
src/pages/en/tutorial/6-islands/index.md

Changes the `StackblitzIntro` component to take a GitHub tree branch and generate both a GitHub and StackBlitz link from it.

[tutorial] Use GitHub branches to generate StackBlitz links

---

src/pages/de/guides/integrations-guide.md

This PR covers the german translation for https://docs.astro.build/de/guides/integrations-guide/

docs(de): add german integrations guide

---

src/components/IntegrationsNav.astro
src/components/PageContent/PageContent.astro
src/i18n/en/ui.ts
src/layouts/IntegrationLayout.astro

I found myself needing to consult the changelogs for several Astro integrations over the weekend and realised they are not always easy to find: some integrations include a link at the bottom of the README, some don’t.
This PR adds a Changelog link as part of the header section in the integration guide layout:
I also tweaked how we format the integration names subtly to improve how they break in narrower spaces.
|--------|-------|
| <img width="324" alt="image" src="https://user-images.githubusercontent.com/357379/197498551-2674a63d-a1e5-4ae3-b5f7-07a29630c28a.png"> | <img width="323" alt="image" src="https://user-images.githubusercontent.com/357379/197498489-d8490b42-c831-4f38-8f95-6cb98d4fcd2f.png"> |

Add Changelog link to integration pages & tweak styles

---

src/i18n/de/nav.ts
src/pages/de/guides/fonts.md

- New or updated content `/de/fonts.md`
The PR adds the German Translation for the missing [Fonts](https://docs.astro.build/de/guides/fonts/) Page

i18n(de): add `fonts.md` translation

---

src/pages/en/guides/images.md

- Moves alt text from an image integration caution into its own section
- Addresses #1892 from the docs side (we still need to update the integration documentation)
- Fixes the code samples so that they're copy-pastable and include alt text

Images guide fixes

---

src/pages/de/core-concepts/framework-components.md

This PR will add german translation for the framework-components guide

docs(de): translate framework-components guide

---

src/pages/en/guides/deploy/cloudflare.md

While reviewing a translation PR I noticed some formatting was off in the Cloudflare deploy guide. This PR fixes that.
While there I also tried to polish the page structure a little. Notably the “How to deploy an SSR site” does not actually cover deploying a site, only how to configure the adapter. I haven’t updated that subheading but do now say to use the other deployment approaches in the intro for that section.

Fix formatting & slightly polish Cloudflare deploy guide

---

src/components/PageContent/PageContent.astro
src/components/tabs/TabbedContent.astro
src/components/tutorial/MobileTutorialNav.astro
src/components/tutorial/RightSidebar.astro
src/components/tutorial/TutorialNav.astro
src/i18n/en/ui.ts
src/layouts/MainLayout.astro
src/layouts/TutorialLayout.astro
src/pages/en/tutorial/0-introduction/1.md

- Adds a collapsible menu similar to our existing “On this page” component on smaller screens to show the tutorial tracker

Show tutorial navigation on smaller screens

---

src/components/PageContent/PageContent.astro

This is a small formatting fix to make our format CI task happy. Wrapping with `<>...</>` Shouldn’t strictly speaking be necessary in `.astro` but looks like Prettier is confused in this context without it and wrapping with a fragment is harmless, so I’m adding this to get CI passing.

Hot fix to make Prettier happy

---

scripts/generate-integration-pages.ts

- Changes to the docs site code (specifically to `scripts/generate-integration-pages.ts`, which is called by `pnpm run docgen:integrations`)
- [I noticed](https://github.com/withastro/docs/pull/1886#issuecomment-1290997156) that a link hash was disappearing somewhere between `withastro/astro` and `withastro`docs`:
```diff
- https://docs.astro.build/en/reference/configuration-reference/#markdownextenddefaultplugins
+                         /en/reference/configuration-reference/
```
- Tracked down the source of the issue, this PR fixes it (confirmed locally).
- Also made a very minor change to an unrelated regex in the same script, to reduce the chance of it erroneously matching in the future.
- Tempting to figure out how to test this script, but I gather it will be retired sometime in the …

`docgen:integrations`: don't strip hashes from links

---

public/theme.css
src/components/Checklist.astro
src/components/tutorial/MultipleChoice.astro
src/components/tutorial/Option.astro

- I forgot to make the `<MultipleChoice>` submit button “pop” in the right direction as part of #1908 — this PR fixes that.
- I’ve also switched up the transition style so it uses the same “bounce” easing as our other buttons for consistency.
- These transitions were active even for users who prefer reduced motion, so I’ve fixed that, disabling animations when appropriate.

More `<MultipleChoice>` polish

---

src/pages/en/tutorial/2-pages/4.md
src/pages/en/tutorial/2-pages/5.md
src/pages/en/tutorial/3-components/2.md

- Updates the styling used in the tutorial project up to and including lesson 3.2
- Main aim is to make things look a little more minimal while still preserving the same basic learning flow
- I have tweaked a few bits of markup too where it seemed we could do better: use `<footer>` in the footer component for example.
I have been updating the example repo as I go, so you can get a glimpse by looking at the `unit-4/start` branch on StackBlitz: https://stackblitz.com/github/withastro/blog-tutorial-demo/tree/unit-4/start (N.B. this does still include the hamburger/nav styles, which I haven’t tackled yet)
Here’s a taste:

Initial work overhauling styles for the tutorial project

---

netlify.toml

Netlify recently [introduced out-of-the-box support for deploying with `pnpm`](https://www.netlify.com/blog/how-to-use-pnpm-with-netlify-build/), so we no longer need our workaround in `netlify.toml`.

Remove Netlify pnpm workaround that is no longer needed

---

src/pages/en/guides/testing.md

As the example is describing a test with Playwright, I guess it would be nice to mention it also in the testing-libs at the beginning.

docs(en): mention playwright in testing guide

---

src/pages/en/guides/testing.md

Fixing small typo in testing guide

docs(en): fix typo in testing guide

---

src/pages/en/tutorial/2-pages/4.md
src/pages/en/tutorial/2-pages/5.md
src/pages/en/tutorial/3-components/3.md

#1921 reported we were still talking about `<h1>`s being blue in the tutorial and I’d missed this “Analyze the pattern” where we show that a local `<style>` tag on the About page overrides `global.css` in #1920. This PR patches that up by setting an extra big font-size on the about page and pointing out to the reader that _that_ overrides the smaller font-size in the global styles.
I have the equivalent changes to https://github.com/withastro/blog-tutorial-demo cued up ready to go.

Tutorial: Ensure style conflict for a teachable moment!

---

src/pages/en/reference/directives-reference.md

- Closes #1918 
Removes misleading line about SCSS in `is:inline` styles. Waiting for confirmation that there isn't other "pre-processing" happening.

remove pre-process line

---

src/pages/en/guides/images.md

Wanted to make the links back to the full list of properties that the `<Image />` and `<Picture />` components can take clearer. Current guide focuses on the minimum required attribures for basic usage, but it should be easy for a reader to get to the full list of attributes available.

links to full list of Image/Picture component properties

---

src/pages/en/guides/images.md

After updating the Integration README with more technical details, a revisit of the Images Guide to nudge the focus here more towards "guidance" than detailed specs.
- stronger statement re: images in public or remote for use in Markdown 
- more honest, and better exposure to when you can/can't use the image integration
- increased linking to "all other properties" in the integration READMEso that other, non-required attribures are exposed
- more explicit sending ppl to remote integration images from the CMS/CDN section
- a missing section for `<Picture />` images from public
- added the quirk re: remote images' `format` when using `<Picture />`
- new `(required attributes: )` under each heading vs listing properties out in longer paragraph form
- links back to …

Image Guide -- more guidance!

---

astro.config.ts
package.json
pnpm-lock.yaml

This removes a configuration fix added in #1895, and upgrades to Astro 1.6.0 which automates the fix by default.

Remove Vite SSR fix

---

src/pages/en/tutorial/5-astro-api/2.md

This PR fixes a small typo in the last `Test your knowledge` section in the tutorial - [Generate tag pages](https://docs.astro.build/en/tutorial/5-astro-api/2/), specifically the second question in that knowledge section. The `params` option had a typo, it was spelled `parames` and not `params`.

[tutorial] Fix typo in Test your knowledge option

---

src/pages/en/guides/configuring-astro.md

- Addresses https://github.com/withastro/astro/issues/5265
- Expands on `import.meta.url` section to warn against Vite-specific `import.meta` properties

Edit: callout Vite `import.meta` properties are inaccessible in config

---

src/pages/en/guides/imports.md
src/pages/en/guides/troubleshooting.md

- Closes #1959
- Adds a _`document` (or `window`) is not defined_ common error, describing the possibility of the error in both Astro components and framework components
- Combines the new content with the "unable to render component" entry, and removes that entry. (In my testing, using `document` or `window` in a framework component would give you the "_ is not defined" error, not the "unable to render component" error)

Add "document is not defined" troubleshooting entry

---

astro.config.ts
integrations/sitemap.ts
netlify.toml
src/pages/[lang]/tutorial.astro

- Add a Netlify redirect for an old `renderer-reference` URL
- Add a route with a `<meta>` refresh redirect for `/[lang]/tutorial`
We may one day _have_ an actual `/tutorial` landing page potentially, so using a `.astro` route with `<meta>` seemed safer than configuring a Netlify redirect we’d be more likely to forget to remove.
These URLs were 404s but should now work:
- https://deploy-preview-1976--astro-docs-2.netlify.app/reference/renderer-reference/
- https://deploy-preview-1976--astro-docs-2.netlify.app/en/tutorial/

Set up redirects based on 404 data & filter sitemap

---

src/pages/en/tutorial/5-astro-api/2.md

to remove error generated when copy and pasting tutorial code
- Closes # 
Updates the highlighted insert range of the Advanced JavaScript: Generate pages from existing tags's second list item to remove error generated when copy and pasting tutorial code.
No.

updated highlighted insert range

---

src/pages/en/guides/imports.md

Closes #1274
Closes #1784
Adding a section on extending file support. Based on @delucis's recommendation, I tried to combine a generic "You can add any plugin you like" guide with a specific "YML import" guide.
1. I refer to https://vitejs.dev/guide/using-plugins.html#finding-plugins if users want to learn where to find plugins, as it mentions all the important parts:
- where to find official plugins
- where to find community created plugins
- where to check for Rollup plugin compatibility
2. Also I felt it appropriate to note that you should...
> Refer to your plugin's documentation to learn what configuration options it has
...as many plugins seem to have additional config options, and some even have a slightly different installation process. Most however seem …

Add Imports section: Extending file type support

---

src/pages/en/tutorial/5-astro-api/2.md

Makes a clear instruction to ensure that every Markdown blot post written includes tags by adding a new Step 1 to the instructions for generating tag pages. 
In order to keep the code as simple as possible for generating tag pages, I did not include any conditional (if no tag) logic. Some readers are encountering errors in this line, that is likely caused by having created their own content for blog posts that does not include a `tags` array. (I suspect this is why only *some* people are encountering this error.)
There is a line in the previous section that says "make sure to include all these front matter properties" but that might not be strong enough, and I'll consider revisiting that page, too.

[tutorial] Added step: checking for tags

---

src/pages/en/tutorial/1-setup/2.md
src/pages/en/tutorial/5-astro-api/4.md

I noticed that PackageManagerTabs component is used for the first command in 1-2, but not where the other npm commands are used. So, for consistency, I've updated 1-2 and 5-4 to use this component.

[tutorial] use PackageManagerTabs in 1-2 and 5-4

---

src/pages/en/tutorial/0-introduction/1.md

Fixes link on 0-1. Was missing the `github.com`

[tutorial] 0-1 Correct link to docs repo issues

---

src/pages/en/guides/markdown-content.md

Add Astro and React component usage example in the MDX docs. This was pretty hard to figure out even though the docs say it's possible. And there is confusion with the old `setup: |` syntax that is [spread](https://github.com/snowpackjs/astro/issues/491) [across](https://craigglennie.com/posts/2021/rewriting-in-astro) the internet already.
The only component usage example I could find in the existing docs comes from the migration guide converting an old React `.md` to `.mdx` in https://docs.astro.build/en/migrate/#converting-existing-md-files-to-mdx
Relevant docs:
- https://docs.astro.build/en/guides/markdown-content/#using-components-in-mdx
- This PR adds an example here
- https://docs.astro.build/en/guides/integrations-guide/mdx/#components
- It would be nice to …

Add component usage example in the MDX docs

---

src/pages/en/guides/typescript.md
src/pages/en/install/manual.md

- Closes #1607 
- Remove the suggestion to use `"types"` in the TypeScript guide.
- Update the manual installation guide to advise users to create `src/env.d.ts` like our starter projects instead of setting `"types"` in `tsconfig.json`
- [Manual install guide: TS set up](https://deploy-preview-2026--astro-docs-2.netlify.app/en/install/manual/#6-add-typescript-support)
- [TS guide](https://deploy-preview-2026--astro-docs-2.netlify.app/en/guides/typescript/#setup) (removed content only)

Improve documentation around setting up ambient types

---

src/pages/en/guides/troubleshooting.md

Add troubleshooting guidance based on @Princesseuh’s suggestion for users who have a Content Security Policy that disallows the use of inline scripts.

Add troubleshooting guidance for CSPs without unsafe-inline

---

src/pages/ja/getting-started.md

- Updated getting-started.md to match the latest English version.
- Improved some existing translations.

i18n(ja): Update getting-started.md

---

src/pages/es/guides/markdown-content.md
src/pages/es/guides/troubleshooting.md
src/pages/es/guides/typescript.md
src/pages/es/reference/api-reference.md

- Improves spanish translation for `markdown-content.md`, `troubleshooting.md`, `typescript.md` and `api-reference.md`

i18n(es): Improve translations

---

src/pages/en/tutorial/5-astro-api/2.md

Adds an extra paragraph to step 1 to:
- customize the tags listed out manually, if you have customized your posts and do not have the example Markdown files
- check manually that every post does have at least one tag, written as an array
This makes the manual step more illustrative if the reader has chosen their own Markdown content for their tutorial blog posts. And, following this extra step prevents errors occuring because the code itself is not (yet!) forgiving about posts that do not contain tags. 
(Follow up task will be to make the code handle posts without tags, but that also requires updating the project code repo on GitHub and rebasing, so this is the quicker, immediate fix.)

[tutorial] added extra note to check tags, update manually

---

src/components/tabs/TabbedContent.astro

We use a `.content` class on our main page content and instruct DocSearch to use this to find content. We don’t want to include the tutorial navigation tabs in search results and also don’t want styles from the global `.content` bleeding into them, so this renames `.content` to `.panels`.

Use unique class name in tutorial nav tabs

---

src/components/Header/DocSearch.tsx

#2071 introduced a bug where the hashes in links to search results were lost, meaning you’d always just jump to the top of pages. This fixes that!

Fix search result links by reintroducing URL hash

---

src/pages/en/guides/cms/contentful.md

Correct en-only typo in Contentful CMS Guide from "Use can use" to "You can use"
This changes a one word typo from "Use" to "You" in the Contentful CMS guide en version.

Correct en-only typo in Contentful CMS Guide

---

src/pages/en/core-concepts/layouts.md

First PR. I am going through all the docs. I really like them :) 
It looks like all of the titles and subtitles are written in **title case**. [This](https://docs.astro.build/en/core-concepts/layouts/#importing-layouts-manually-mdx) one was not. 
I updated it to be title case :) 
- There is no Issue Number. I just directly made a PR.
> Screenshot of the "Importing layouts manually (MDX)" section written in the "non-title case" format.

Update `Importing layouts manually (MDX)` subtitle to be title case

---

public/theme.css
src/components/Header/DocSearch.css
src/components/Header/DocSearch.tsx
src/components/Header/Search.astro
src/i18n/en/docsearch.ts
src/i18n/translation-checkers.ts

1. Adds a small component with useful links to the bottom of search results:
2. Refreshes the theming inside the search modal to improve several details:
- In light mode, highlight the portion of text matching the search query like we do in dark mode
- In dark mode, style the keyboard shortcut buttons appropriately
- Tweak the style of individual search results
- Fix contrast issues with muted secondary text in the modal
Here are some before/after screenshots:
| Before (light) | After (light) | Before (dark) | After (dark) |
|----------------|---------------|---------------|--------------|
| ![image](https://user-images.githubusercontent.com/357379/203138823-919e7f88-d33a-4d5a-b8a0-4e664e1da8c8.png) | …

Improve DocSearch modal

---

src/pages/en/guides/styling.md
src/pages/en/tutorial/2-pages/3.md
src/pages/en/tutorial/2-pages/5.md
src/pages/en/tutorial/3-components/2.md
src/pages/en/tutorial/3-components/4.md
src/pages/en/tutorial/4-layouts/2.md

Went through the top 60 search terms for the past 30 days to try to see what might be improved through some strategic content tweaks.
Most of this boils down to:
1. Use terms we want to match as high as possible in the page hierarchy for results we want to show. For example, if a user searches for “style”, make sure “style” is in the page title or `<h2>` for results we want them to see.
2. _Avoid_ terms in the same places if we don’t want that content to rank highly in search. For example, if a user searches for “style” and we don’t want our tutorial page “Add a Gangnam Style translation blog post” to match, we could rename it to “Add a lyrics translation blog post”.
Here are all my tweaks:
- **Avoid “global” in tutorial page title**
Ranks …

Strategic content tweaks for better search results

---

src/pages/en/core-concepts/astro-pages.md
src/pages/en/tutorial/3-components/1.md
src/pages/en/tutorial/3-components/2.md

- Remove “link” from page titles in tutorial lessons
- Add a “Link between pages” subheading to our “Pages” page to help that content stand out
Probably not a silver bullet because “Link between pages” is `<h3>` and there are some `<h2>`s containing “link” in the tutorial, but should be a start. We can re-evaluate if we want to do more after re-crawling.

Tweaks to improve “link” search results

---

src/components/RightSidebar/RightSidebar.astro
src/components/tutorial/FeedbackButton.astro
src/i18n/en/ui.ts

- Add the Feedback Fish button to the right sidebar across the whole site
- Make the “Give us feedback” label translatable
Example of location:
Worth noting that this sidebar is not visible at narrower viewport widths. We don’t show any of the “extra” (non-ToC) stuff on smaller screens and the approach I took for small screens in the tutorial isn’t an option because that space is used by the current heading text next to “On this page”.
My take is that gathering feedback outside of the tutorial is slightly less crucial, so maybe only showing on wider screens is OK and NWTWWHB? Otherwise, we may need to spend more time thinking. One option could be to move the entire “extra” sidebar stuff to the bottom of each page.

Add Feedback Fish across whole docs site

---

src/components/RightSidebar/CommunityMenu.astro
src/components/RightSidebar/RightSidebar.astro
src/components/tutorial/FeedbackButton.astro

Realised this was easier than I expected!
- Moved the feedback button into the community menu so it moves just like the community menu does as @sarah11918 suggested.
- Tweaked how we load the Feedback Fish script so we only load it once.
One thing to consider: because we’re using the left sidebar, on tutorial pages we now have TWO feedback buttons on smaller screens:
Is that an issue? The left sidebar is usually scrolled up so most likely you wouldn’t see both at once.

Show Feedback Fish in left sidebar on narrower screens

---

src/i18n/en/nav.ts
src/pages/en/core-concepts/astro-components.md
src/pages/en/guides/client-side-scripts.md
src/pages/en/reference/directives-reference.md

- Simplifies the [“Client-side scripts” section](https://deploy-preview-2102--astro-docs-2.netlify.app/en/core-concepts/astro-components/#client-side-scripts) of the Components guide
- Adds a new guide to writing `<scripts>` — https://deploy-preview-2102--astro-docs-2.netlify.app/en/guides/client-side-scripts/
Includes guidance on:
- Adding event listeners from a `<script>`
- Writing a custom element
- Passing variables from component frontmatter to a script (_without_ `define:vars`)
- Moves detailed content on script bundling and loading out of the Components guide to the new page
- Closes #2100
How does this feel? It’s a slightly 50-50 page with a reference-y first half and guide-y second half. 
Are the examples clear and helpful? I tried to pick things I could …

Add new “Scripts and Event Handling” guide

---

src/pages/en/guides/markdown-content.md

A mismatched backtick quote character broke syntax highlighting in the MDX box.

Fix mismatched quote in MDX docs

---

src/pages/en/install/manual.md

The example file structure shown as the last step in the manual install instructions was missing `env.d.ts`. This adds that.

add env.d.ts to project directory tree in manual install

---

src/pages/en/core-concepts/routing.md

-  New or updated content
- Closes #2077 
Originally, I got confused about because the [Rest Parameters](http://localhost:3000/en/core-concepts/routing/#rest-parameters) docs used the word `...params` in the description, but `...path` in the code example. 
I was also going to add [this tip](https://user-images.githubusercontent.com/17516559/204306968-1d587030-e2f4-4172-ba98-cda55fe183cb.png), but I decided to bold something else, instead.

#2077 `/routing/#rest-parameters` Minor update + link to MDN docs.

---

public/index.css
src/components/RightSidebar/CommunityMenu.astro
src/components/RightSidebar/ContributeMenu.astro
src/components/RightSidebar/EditButton.astro
src/components/RightSidebar/RightSidebar.astro
src/components/RightSidebar/TableOfContents.css
src/components/RightSidebar/TableOfContents.tsx
src/components/tutorial/TutorialNav.astro
src/layouts/MainLayout.astro
src/util/generateToc.ts

1. Refactor the HTML structure of table of contents
2. Since the HTML structure is changed, some changes to css is needed so we can keep the UI same as before
- Closes https://github.com/withastro/docs/issues/2099

Add heading level hierarchy to table of contents

---

astro.config.ts
package.json
pnpm-lock.yaml
scripts/error-docgen.mjs
src/pages/en/reference/error-reference.md

Use a remark plugin to generate custom ids for the headings in the error reference so we can refer to them by their name instead of the title. 
This has the following benefits:
- Links will never change
- Which mean, we can link to errors from other Astro projects without worrying about links breaking if the title change
- Links to specific errors are independent on the language, so it'll be easier to link to them in the user's language in the future (well the path still changes, but we could hardcode in other projects that one if needed)

Generate custom anchors for errors so we can refer to them statically

---

src/pages/en/tutorial/5-astro-api/3.md

The tutorial code snippet was missing an `alt` attribute for the image in `5-astro-api/3`. This adds `alt={frontmatter.image.alt}` in both places the code is shown.
Also removes the `<h1>` because it is being provided by `<BaseLayout>`

[tutorial] adds alt text to image in code sample

---

src/pages/en/tutorial/6-islands/2.md

Adds a missing `/` in a closing `<header>` tag in `6-islands-2`

[tutorial] fixes closing tag notation

---

src/pages/en/guides/styling.md

Close https://github.com/withastro/astro/issues/5112
Clarify that the issue is expected behaviour and how to prevent it if it happens.
Question: Should we show the user how to filter out the scoped class? It might involve regex replace that maybe even make sense to export out from Astro as an API, but it also feels like a bandaid API to the problem. I'm slightly leaning to not for now unless more people hit this edge case.

Note scoped classes passed to child components

---

package.json
pnpm-lock.yaml
scripts/lib/linkcheck/checks/good-link-label.ts
scripts/lint-linkcheck.ts
src/pages/en/guides/deploy/buddy.md

- Closes #2123 
- Adds a check to our link linter that fails if a link’s text is `read more`, `here` or `more`
- Fixes two links in the Buddy deploy guide that were just labelled “here”
- Up for including other tests here if we can think of any, but this has already caught a couple of issues!

 Add linter check that fails for nondescript link labels

---

src/pages/ja/guides/configuring-astro.md
src/pages/ja/guides/environment-variables.md

- Update environment-variables.md.

i18n(ja): Update environment-variables.md and part of configuring-astro.md

---

.github/workflows/ci.yml
package.json
pnpm-lock.yaml
src/util/generateToc.test.ts
src/util/generateToc.ts

- Add Vitest to run unit tests
- Include a unit test for [`generateToc`](https://github.com/withastro/docs/blob/main/src/util/generateToc.ts) introduced in https://github.com/withastro/docs/pull/2101
- Enable CI for unit tests.

Add vitest unit tests

---

src/pages/ja/guides/configuring-astro.md

- Update configuring-astro.md.

i18n(ja): Update configuring-astro.md

---

src/i18n/ja/nav.ts

i18n(ja): Update nav.ts

---

WRITING.md

Added a brief section on "Voice" to the guide with two points:
- using "you" (if needed) instead of *we*, *we'll*, *us*, *let's* etc. (You are not there with the reader at this exact moment.) And, I can't believe it needs to be said not to use *I*, but that came up in something I read/watched so apparently it's a thing.  😅 
- some general guidance re: exclamation points.
(NB: Voice and tone are similar, but since we have a section for Tone that says "mostly follow Google", for now I'm using this section "Voice" for more technical, specific to us, points.)

[WRITING.md] new section for voice

---

src/pages/en/guides/migrate-to-astro.md
src/pages/en/guides/migration-guide/from-gatsby.md
src/pages/en/guides/migration-guide/from-nextjs.md

Per prior discussions with @sarah11918, these are my edits to her work on Astro migration guides from Gatsby. These edits have left me feeling relatively happy with the Gatsby guide, and I think it should be ready for another pass of reviews.
A few questions I had along the way:
1. Is the code highlighting/naming correct in all code blocks?
2. Are we happy with the current iteration of the `<Image>` component? It's one of the only instances without a before/after
3. Are we happy with the length? It got _long_ quick.
This PR also adds in a few comments regarding the NextJS migration guide that I will be tackling next.

Migration guides from

---

scripts/github-translation-status.mjs

This PR gives the i18n status issue a light refresh now we have so much more content than when we first started.
- Show the breakdown by language first, before the table of by-page data
- Inside a language’s details, show “Needs updating” pages ahead of “Missing”
- `<h2>` instead of `<h3>` for the section headings
- Show a progress bar made of emoji in each language’s header & include the done count
Here’s how the new by-language section looks:

i18n Status Issue design refresh

---

src/pages/en/reference/api-reference.md

- Clarifies docs on `Astro.site` when `site` is undefined in the Astro config,

docs: fix Astro.site docs on undefined configs

---

src/pages/en/guides/typescript.md

The PR adds 'type' to the `import { HTMLAttributes } from 'astro/types'` from `Built-in HTML attributes` section.

Use type import in “Built-in HTML attributes” example

---

src/pages/en/guides/cms/wordpress.md

This PR fixes the broken `Layout` component import route in the [Using the WordPress API to generate pages](https://docs.astro.build/en/guides/cms/wordpress/#using-the-wordpress-api-to-generate-pages) section's code example:
* Layout route: `src/layouts/Layout.astro`
* Dino page route: `src/pages/dinos/[slug].astro`
We need to go 2 directory levels up to be able to import the `Layout` in the `[slug].astro` file.

Fix import route in the WordPress connection guide

---

src/components/FileTree.astro

- Fixes a bug where items in the FileTree could break to a new line inelegantly in Safari/iOS:

Fix `<FileTree>` overflow bug in Safari/iOS

---

src/pages/en/guides/deploy/deno.md
src/pages/es/guides/deploy/deno.md

- Bumps the `actions/checkout` version for the deno deploy guide

chore: bump `actions/checkout` in deno deploy guide

---

src/pages/en/guides/deploy/github.md
src/pages/es/guides/deploy/github.md
src/pages/pt-br/guides/deploy/github.md
src/pages/zh-cn/guides/deploy/github.md

- Primarily, update the script so it reflects that users should now use actions/checkout@v3 instead of v2, which was recently merged in https://github.com/withastro/action/pull/17
- Script is now a 1:1 match with the one found in [withastro/action](https://github.com/withastro/action) repository
Thanks!

chore: bump actions/checkout in GitHub deploy guide 

---

src/pages/en/guides/content-collections.md

Old: 
New:
Fixes a broken code highlight regex.
I'm not sure what exactly the cause of the issue was - it might have been a typo (the square brackets), or depending on how the code that tests the regex works, it might have been the use of a capturing group instead of a non-capturing group (a group that starts with `?:`).

Fix highlight regex for `CollectionEntry` code example

---

src/components/tabs/TypeScriptSettingTabs.astro
src/pages/en/guides/content-collections.md

Choose your own TypeScript adventure!
Added more specific advice for configuring TypeScript based on one's current Astro project's existing `tsconfig`. For example, the existing guidance to add `strictNullChecks: true` wasn't applicable if a project was already using Astro's `strict` or `strictest` setting.
Also includes a new tab component, but not in the order I want?  😅  PR'ing to get help correcting the tab order, and so we can work on the wording!
Deploy preview: https://deploy-preview-2209--astro-docs-2.netlify.app/en/guides/content-collections/

[content collections] added typescript settings guidance via tabs

---

src/pages/en/guides/content-collections.md

- Documents that you can provide a function to customize how slugs are generated for each entry in a content collection.
- [Relevant RFC section for reference](https://github.com/withastro/rfcs/blob/main/proposals/0027-content-collections.md#custom-slugs)
Deploy preview: https://deploy-preview-2214--astro-docs-2.netlify.app/en/guides/content-collections/#custom-entry-slugs

Document custom slugs for content collection entries

---

src/pages/en/editor-setup.md

I have updated the editor-setup.md page and linked to the JetBrains WebStorm roadmap for release 2023.1 which will include support for Astro.

Include JetBrains WebStorm roadmap in editor setup

---

src/pages/en/tutorial/5-astro-api/3.md

This PR fixes the misaligned code block diff markings to cover the entirety of `div` and `style` tags in unit 5 section 3 of the tutorial:
https://docs.astro.build/en/tutorial/5-astro-api/3/#challenge-include-tags-in-your-blog-post-layout
_Before_:
_After_:

fix: misaligned code block diff markings in the tutorial

---

src/pages/es/reference/errors/config-legacy-key.md
src/pages/es/reference/errors/config-not-found.md
src/pages/es/reference/errors/csssyntax-error.md

- add `reference/errors/config-legacy-key.md`
- add `reference/errors/config-not-found.md`
- add `reference/errors/csssyntax-error.md`

i18n(es): add multiple error pages

---

src/pages/en/guides/cms/wordpress.md
src/pages/es/concepts/mpa-vs-spa.md
src/pages/fr/concepts/mpa-vs-spa.md
src/pages/pt-br/integrations/integrations.md

- Minor content fixes
Properly [capitalize](https://developer.wordpress.org/reference/functions/capital_p_dangit/
) the "p" in WordPress.

fix: capitalize the P in WordPress

---

astro.config.ts
plugins/rehype-i18n-autolink-headings.ts
plugins/remark-fallback-lang.ts
src/i18n/en/ui.ts
src/i18n/pt-br/ui.ts
src/i18n/translation-checkers.ts
src/i18n/util.ts

- Closes #1586 
This PR adds a new rehype plugin to translate the screen reader anchor labels injected by `rehype-autolink-headings`. If the current language doesn't have a translation yet, it will fallback to English.
| PT-BR (translated)  | ES (fallback) |
| ![image](https://user-images.githubusercontent.com/61414485/209818306-455fcc49-ea36-477f-bfed-8296bb707084.png) | ![image](https://user-images.githubusercontent.com/61414485/209818386-eb7c836b-4892-42ce-b330-19fa1fad0d24.png) |

Add i18n for screen reader section labels

---

netlify.toml

To solve out-of-memory issues when building docs we set a `NODE_OPTIONS` environment variable in Netlify’s dashboard to increase the default memory limit. This worked fine in internal tests because those of us trying it out are included in the Netlify team. Now that external contributors are triggering deploys, Netlify is not using the environment variable for those builds because it considers all environment variables as “sensitive” (which some are, like our GitHub API key). Without `NODE_OPTIONS` the build fails (see #2251 for example).
This fix moves where we set the variable directly into the build command specified in `netlify.toml`. I would expect Netlify to then use `NODE_OPTIONS` correctly for all PRs.

Fix out-of-memory Netlify deploys for external contributors

---

src/pages/ja/concepts/islands.mdx

- Update islands.mdx.
- Improve some existing translations.

i18n(ja): Update islands.mdx

---

src/pages/en/guides/troubleshooting.mdx

Closes #2150 (The documentation issue; the greater conversation is ongoing elsewhere.)
As per @delucis suggestion and @matthewp approval, removes a problematic workaround that does not work in every case, and instead just leaves the suggestion to update your CSP.
(Note: eventually error messages will make their way to the Error Reference page. But, at least this removes potentially harmful advice for now.)

[troubleshooting] remove suggested workaround re: executing inline scripts

---

src/pages/en/guides/content-collections.mdx

`slug` is not available in `data` because it's a direct child of `post`.

fix `post.slug` in example

---

src/pages/ja/core-concepts/project-structure.mdx

- Update project-structure.mdx.
- Improve some existing translations.

i18n(ja): Update project-structure.mdx

---

src/pages/en/tutorial/0-introduction/1.mdx

- Fix a typo in "About this Tutorial" page: a URL to the GitHub repo
- before: https://github.com/withastro/astro/docs/issues (404)
- after: https://github.com/withastro/docs/issues

Fix a typo in "About this Tutorial" page: a URL to the GitHub repo

---

src/pages/en/guides/migrate-to-astro/from-nuxtjs.mdx

This PR changes a mention of React in the Nuxt guide to more accurately say "Vue", since Nuxt is the Vue meta-framework.

chore: change mention of Nuxt's framework from React to Vue

---

src/util/getPageCategory.ts

Addresses some recent poor search results reported in #2042 
We add a hidden element to pages that Algolia picks up and uses to extract that page’s category, e.g.
```html
<span id="docsearch-lvl0" hidden>Learn</span>
```
Due to a bug in our category utility, we were categorising error reference pages as “Reference”. This PR fixes that so that these pages now contain:
```html
<span id="docsearch-lvl0" hidden>Error Reference</span>
```
Will still need to reevaluate these search terms (`getStaticPaths` and `slots` are current known issues) once this is live to see if the “Error Reference” category needs demoting in Algolia’s crawler logic.

Fix categorisation of error reference pages for Algolia

---

src/components/TabGroup/InstallGuideTabGroup.astro
src/components/TabGroup/TabGroup.css
src/components/tabs/Tabs.module.css

- Tweaks the design of the Tabs and TabGroup components to align their left edge.
- Sorry if this was intentional😅, but only the left side of the Tabs component was outside of the container, which was a bit odd to me, so I created this PR to fix that.
- (Update) Found that TabGroup had the same style, so I updated it as well for consistency.
- This may be a PR based on my personal preference, so feel free to close it if it is inappropriate🙏
Tabs
| --- | --- |
| ![mobile-before](https://user-images.githubusercontent.com/7889778/210168598-8fdf1edb-8b26-441b-b948-0da9c1f3b920.png) | ![mobile-after](https://user-images.githubusercontent.com/7889778/210168611-419065b2-0eb8-4d00-80dd-b4dbe20595b1.png) |
TabGroup
| --- | --- | …

Align left edge of Tabs and TabGroup

---

src/pages/en/guides/server-side-rendering.mdx

- Documents `prerender` feature, originally added experimentally in v1.7.0 but unflagged in v2.0.0-beta.0.
- Added to Server-Side Rendering guide

Add `prerender` section

---

scripts/generate-integration-pages.ts
src/pages/en/guides/integrations-guide/alpinejs.mdx
src/pages/en/guides/integrations-guide/image.mdx
src/pages/en/guides/integrations-guide/mdx.mdx

Lots of links to other docs pages and local links (those starting with `#`) were being wrongly prepended by the `absoluteLinks` remark plugin. I couldn't find a reason as to why the `absoluteLinks` remark plugin exists in the first place, taking a look at #954, I guess it was fixing something related to Markdown footnotes (maybe we can remove it?). Changed a line to make it ignore the links I didn't want it to change, but perhaps this can cause another problem. - I did some tests and couldn't find any broken links from the change in the remark plugin.
Additionally, I found out the Alpine.js integration changelog wasn't being deleted, so I made a small change to ensure its deletion as well.

Fix integrations absolute links and changelog generation errors

---

scripts/github-translation-status.mjs

Adds a new keyword for ignoring commits in our i18n status tracker: commits containing `i18nIgnore` will be now also be ignored. Allows us to stop abusing other keywords like `typo` or `en-only`.

Ignore commits containing `i18nIgnore` in i18n status tracker

---

src/pages/es/guides/markdown-content.mdx
src/pages/ja/guides/markdown-content.mdx

Spanish & Japanese translations of the Markdown content include text linking to a MDX subheading which no longer exists.
These paragraphs were wholesale removed here: https://github.com/withastro/docs/pull/2280/files#diff-5aa3990791d164a679ef35f083c2cc0e6afb3d4b007445fba1ee0d5adf9df89dL434-L442
So I think we can do the same here, fixing the broken link, but using the new `i18nIgnore` keyword to avoid marking these pages as updated as they do still need some work.

[i18nIgnore] Delete outdated content with broken link in es/ja

---

src/pages/en/tutorial/0-introduction/1.mdx
src/pages/en/tutorial/1-setup/2.mdx
src/pages/en/tutorial/1-setup/4.mdx
src/pages/en/tutorial/1-setup/index.mdx
src/pages/en/tutorial/2-pages/1.mdx

This applies the "quick wins" feedback from @hippotastic after taking the tutorial.
Specifically:
- Fixes `localhost:3000` to no longer be `https:` 
- Gives a little more context re: WHY you might want to use the checklists/tutorial tracker.
- Correctly states the cause/effect of the GitHub/Netlify deployment relationship
- Minimally refers to "lessons" inside of "Unit 1" since, as Hippo points out, we use numbers for both Units and pages inside units. This provides at least a vocab early on to distinguish. (*Not sure I'm entirely happy yet, since Unit 0 is not named as such, so Hippo's totally right, when you're IN Unit 0, you only see a 0 and a 1 for those current lesson pages. You don't know that you aren't IN unit 1 when you're on Unit …

[tutorial] quick fixes from Hippo feedback

---

src/pages/en/tutorial/2-pages/5.mdx

Quick fix because `code styling` doesn't seem to work inside our spoiler text for Analyze the Pattern in our tutorial.
Without backticks:

[tutorial] remove backticks inside spoiler text

---

MAINTAINERS.md
package.json
pnpm-lock.yaml
src/pages/en/migrate.mdx
src/pages/ru/guides/markdown-content.mdx

- Removes links to the AFMD config entry in the `/en/` migration guide.
- Mark the migration guide as `i18nReady: false` — we’ll change this once the v1 -> v2 guide replaces this
- Removes links to the AFMD config entry in the `/ru/` Markdown Content guide.
- Uninstalls a direct dependency `MAINTAINERS.md` said was only needed for AFMD and updated that note
Does _not_ change Spanish, Portuguese, French, and Chinese pages as these should not cause any broken links. I think it’s safe to leave these as is until they get a proper refresh.

[i18nIgnore] Prep to remove `astroFlavoredMarkdown` in reference

---

src/pages/en/reference/integrations-reference.mdx

`pages` is undocumented in the [`astro:build:done` hook reference](https://docs.astro.build/en/reference/integrations-reference/#astrobuilddone). This is being officially removed for Astro 2.0, so let's update the quick reference to match!

Fix: remove `pages` from quick reference

---

src/pages/en/guides/markdown-content.mdx

Minor content fixes (broken links, typos, etc.)

Fix typo in markdown-content.mdx

---

src/pages/en/guides/markdown-content.mdx

- Add SmartyPants back to Markdown plugin defaults

Add SmartyPants back to Markdown defaults

---

src/pages/en/tutorial/5-astro-api/3.mdx

`BlogPostLayout.astro` included `src={frontmater.postImage}`. Corrected to `src={frontmatter.image.url}`

[tutorial] Fix code sample typo in 5-3

---

src/pages/en/tutorial/5-astro-api/2.mdx

Removes some empty `{ }` from `getStaticPaths()` function in a couple of places.

[tutorial] remove unnecessary {}

---

src/pages/[...slug].astro

While updating an `Astro.glob()` call as part of #2133, I messed up one of the patterns so that a dynamic route we use to redirect from routes like `/reference/configuration-reference` to `/en/reference/configuration-reference` wasn’t working properly. Noticed it today after spotting an increase in docs 404s since #2133 merged. This PR fixes the glob pattern.

Fix dynamic redirect route

---

src/pages/en/guides/typescript.mdx
src/pages/es/guides/typescript.mdx
src/pages/ja/guides/typescript.mdx
src/pages/pt-br/guides/typescript.mdx
src/pages/zh-cn/guides/typescript.mdx

Reflects the upcoming breaking change in https://github.com/withastro/astro/pull/5724. The troubleshooting section isn't an issue anymore as it has been fixed by Volar.
I also removed it for the translated docs.

[i18nIgnore] Remove Vue TypeScript troubleshooting section

---

src/pages/en/core-concepts/project-structure.mdx
src/pages/en/getting-started.mdx
src/pages/en/guides/migrate-to-astro/from-docusaurus.mdx
src/pages/en/guides/migrate-to-astro/from-eleventy.mdx
src/pages/en/guides/migrate-to-astro/from-gatsby.mdx
src/pages/en/guides/migrate-to-astro/from-gridsome.mdx
src/pages/en/guides/migrate-to-astro/from-hugo.mdx
src/pages/en/guides/migrate-to-astro/from-jekyll.mdx
src/pages/en/guides/migrate-to-astro/from-nextjs.mdx
src/pages/en/guides/migrate-to-astro/from-nuxtjs.mdx
src/pages/en/guides/migrate-to-astro/from-pelican.mdx
src/pages/en/guides/migrate-to-astro/from-sveltekit.mdx
src/pages/en/guides/migrate-to-astro/from-vuepress.mdx
src/pages/en/guides/migrate-to-astro/from-wordpress.mdx
src/pages/en/guides/troubleshooting.mdx
src/pages/en/install/auto.mdx
src/pages/en/install/manual.mdx
src/pages/en/integrations/integrations.mdx

This fixes the instructions for running create astro with a template flag in the migration guides.
It also adds the example we have for starting a new project from any GitHub template from the hidden `integrations/integrations` page to Auto install, to better surface these instructions.
Lastly, it changes *most* instances of `create-astro` to `create astro`, since we are usually referring to the command to run, not the name of the package itself. (This has caused confusion in the past, so doing this while I'm here, but can be talked out of that change.) Admittedly, some of these occurances (both changed, and not changed) were judgment calls. Mostly based on what I thought might be least confusing to the reader. e.g. If the name of the wizard shows up JUST BEFORE they need to run the …

update create astro and template flag instructions

---

src/pages/en/guides/content-collections.mdx
src/pages/en/reference/api-reference.mdx

- Add `z.object` wrapper around schema definitions. This is now a required wrapper!

[Content collections] `z.object` wrapper for schemas

---

src/pages/en/guides/content-collections.mdx
src/pages/en/reference/cli-reference.mdx

- Add `.astro` directory explanation and setup
- tip to add to `gitignore`
- note on `reference` type setup

[Content collections] Add `.astro` directory setup

---

src/pages/en/guides/content-collections.mdx
src/pages/en/reference/api-reference.mdx
src/pages/en/reference/cli-reference.mdx

Remove experimental from content collections!

---

src/pages/en/core-concepts/framework-components.mdx

Removes integration installation instructions from the UI Framework components page because:
- duplication! These instructions are detailed elsewhere. Why maintain in 2 places?
- outdated! These instructions pre-dated the `astro add` command, and so were showing users more complicated, manual instructions when most shouldn't need them.

remove outdated (and duplicated!) installation instructions

---

src/pages/en/guides/integrations-guide.mdx

Warning is scary, not helpful!
- `astro add` is more reliable/familiar to users than at the time of this warning
- Houston walks a user through the changes to their file
- the integration READMEs show manual installation and what a properly installed and configured integration should look like, in case a user needs to compare.
Removing the scary warning as a quick fix not to scare off new users. Will revisit this page with more intention in the future.

remove scary warning

---

src/pages/pt-br/core-concepts/framework-components.mdx
src/pages/pt-br/guides/configuring-astro.mdx
src/pages/pt-br/guides/deploy.mdx
src/pages/pt-br/guides/deploy/gitlab.mdx
src/pages/pt-br/guides/deploy/netlify.mdx
src/pages/pt-br/guides/deploy/vercel.mdx
src/pages/pt-br/guides/environment-variables.mdx
src/pages/pt-br/guides/server-side-rendering.mdx
src/pages/pt-br/integrations/integrations.mdx
src/pages/pt-br/reference/adapter-reference.mdx

Updated PT-BR translations for:
- `framework-components.mdx`
- `configuring-astro.mdx`
- `deploy.mdx`
- `gitlab.mdx`
- `netlify.mdx`
- `vercel.mdx`
- `environment-variables.mdx`
- `server-side-rendering.mdx`
- `integrations.mdx`
- `adapter-reference.mdx`

i18n(pt-BR): Update `framework-components.mdx` and +9 translations

---

src/components/Since.astro
src/i18n/en/ui.ts

Adds a "beta" tag to the `<Since />` component. Without this, it's unclear that a `v2.0.0` feature isn't actually available yet.

Add beta tag detection in `<Since>`

---

src/pages/en/tutorial/5-astro-api/1.mdx

- Follow up to #2382 
- The tutorial is using an image from astro.build but because these are optimized with `@astrojs/image` they are liable to change filename, breaking the tutorial. This PR switches to using [a static image](https://docs.astro.build/default-og-image.png) within the docs site instead.

Use more reliable image source for tutorial

---

src/util.ts

This PR improves our sidebar subpages handling, now making it work for pages with technically infinite segments, so `en/example/[subpage-1]/[subpage-2]/[subpage-3]/[subpage-4]` will still be considered a subpage of `en/example/`, not only `en/example/[subpage]`.
This improves the navigation experience by highlighting the current main page in the sidebar and also collapsing the page section on mobile. I also added the missing "CMS" and "Migrate to Astro" to the subpages regex.
| ![5zcVqgU](https://user-images.githubusercontent.com/61414485/212682662-b348f34a-193e-4539-8dd4-28c51ffbbeef.gif) | ![UEpLS0S](https://user-images.githubusercontent.com/61414485/212682498-d8e57132-e8b0-48b0-9a28-9b653aada6c4.gif) | …

Improve subpages handling and add missing pages

---

src/pages/en/install/auto.mdx
src/pages/en/install/manual.mdx

- Supersedes #2326 
The “fake” tab pattern in the install guides has been tripping us up a bit. These are two separate pages, so let’s treat them that way properly! This also gives us some leeway to stress preferences a bit and encourage use of the `create astro` guide which is generally the better DX.

Remove fake tabs from install guides

---

src/pages/en/guides/rss.mdx
src/pages/en/tutorial/5-astro-api/4.mdx

- Updates for https://github.com/withastro/astro/pull/5851
- Change `import.meta.env.SITE` to new `context.site`
- Update leading example to use content collections
- Add new "using content collections" section to "Generating items"
- Update glob import instructions to recommend the `pagesGlobToRssItems()` function
- Update "including full post content" with content collections instructions. **The `markdown-it` recommendation may change** once we support an `html` output for content collections!

Revamped RSS instructions for content collections

---

src/pages/en/core-concepts/astro-pages.mdx
src/pages/en/guides/markdown-content.mdx
src/pages/en/guides/styling.mdx

This PR starts to sprinkle in content collections in appropriate places throughout the docs.
1. Markdown/MDX: Content collections is now the recommended suggestion for creating pages, so it is now listed under the `## Markdown and MDX Pages` heading.
1. Pages: Content collections is now mentioned in Pages
1. Styling of content collections came up in discussion, which is really no different than styling your Markdown content anywhere it occurs. So, in order to support new collections users this PR adds a section on Markdown styling to the Styling page. And, the Markdown/MDX page links TO it, rather than duplicating content.
TODO: Link to this new styling markdown section FROM the content collections page itself. This page already has a complicated PR in the works, so this will be added …

content collections in styling, markdown pages

---

WRITING.md
src/components/Since.astro
src/pages/en/guides/rss.mdx

- Adds a `<Since />` component to the new RSS docs to indicate the feature is new (in beta!)
- Adds a minimal note to the same docs showing the old behaviour for people using older versions. Maybe not needed? Excessively polite?
- Updates `<Since />` so we can use it in cases like this where we’re documenting changes to packages other than `astro`: `<Since v="2.0.0" pkg="@astrojs/rss" />`
- Updates `WRITING.md` to document these changes
This does slightly change the output of `<Since />` as it could now be talking about different packages:
|---|---|
| <img width="171" alt="image" src="https://user-images.githubusercontent.com/357379/213693084-f8170c8d-dd68-40f5-8b59-360a81fca2d4.png"> | <img width="209" …

Document version of RSS package needed for new features

---

src/i18n/en/nav.ts
src/pages/en/core-concepts/astro-pages.mdx
src/pages/en/guides/content-collections.mdx
src/pages/en/reference/api-reference.mdx
src/pages/es/reference/api-reference.mdx
src/pages/pt-br/reference/api-reference.mdx

- updated content
As a part of my v2.0 readiness docs pass, I took a look at the content collections guide and had some suggestions for how to improve the guide. My edits focused on three main areas:
1. **Improve readability and ordering:** Since this is meant to be a guide, I took a serious look at how the information is presented and in what order. Instead of jumping the user immediately into TypeScript configuration, the guide now introduces the concepts more slowly, building as it goes. The goal is to define terms early, introduce new concepts one at a time, and not overwhelm.
2. **Collect concepts into a single place:** I took a look at places where concepts were explained across multiple sections, and did my best to bring them into a single section. This is feedback we've gotten …

Fred's edit pass on content collections guide

---

src/pages/pt-br/guides/deploy/cloudflare.mdx
src/pages/pt-br/guides/deploy/deno.mdx
src/pages/pt-br/guides/deploy/kinsta.mdx
src/pages/pt-br/guides/deploy/microsoft-azure.mdx

Add PT-BR translations for the final missing deploy pages: `cloudflare.mdx`, `kinsta.mdx`, `microsoft-azure.mdx` and `deno.mdx`

i18n(pt-BR): Add final missing deploy pages translations

---

src/pages/en/guides/testing.mdx

Since we have a `with-vitest` starter example template, added a very short (stubby!) section on Vitest to the testing page, with a link to the example. (From Feedback Fish suggestion.)

[testing guide] add link to Vitest starter template

---

src/pages/en/core-concepts/sharing-state.mdx

- Closes #2453 
It adds a [link](https://vuejs.org/guide/scaling-up/state-management.html#simple-state-management-with-reactivity-api) to the alternatives listed on the Nano Stores docs pointing to the `reactive()` Vue docs.
No, I did not.

Add Vue's reactivity API to sharing state      alternatives list

---

src/pages/en/guides/server-side-rendering.mdx
src/pages/en/guides/upgrade-to/v2.mdx

Updates the Server-Side Rendering: Prerendering section title to use "Hybrid Rendering" for consistency
Updates captialization from "Hybrid Rendering" to "hybrid rendering"

Renamed prerendering section to hybrid rendering

---

src/pages/fr/core-concepts/layouts.mdx

About a recent change for an HTML meta to link.
Due to this enhancement : https://github.com/withastro/docs/commit/8be0113a223a10587712caf791b074f046b104d3
```diff
-  <meta rel="canonical" href={new URL(url, Astro.site).pathname}>
+  <link rel="canonical" href={new URL(url, Astro.site).pathname}>
```

i18n(fr): Update core-concepts/layouts.mdx

---

src/pages/es/reference/errors/content-schema-contains-slug-error.mdx
src/pages/es/reference/errors/invalid-content-entry-frontmatter-error.mdx
src/pages/es/reference/errors/invalid-content-entry-slug-error.mdx

Added error pages: 
1. `content-schema-contains-slug-error.mdx`
2. `invalid-content-entry-frontmatter-error.mdx`
3. `invalid-content-entry-slug-error.mdx`

i18n(es): Added error pages

---

src/pages/en/guides/deploy/render.mdx

This PR is a follow-up of https://github.com/withastro/astro/issues/6004 and this [Discord support thread](https://discord.com/channels/830184174198718474/1068446497353498666).
It is currently not possible to deploy a project using Astro 2.0 to Render by blindly following the guide due to the fact that Astro 2.0 requires at least Node.js 16.12.0 and Render [using by default Node.js version 14](https://render.com/docs/node-version).
The proposed change is *heavily* inspired by the existing [Cloudflare Pages deploy guide](https://docs.astro.build/en/guides/deploy/cloudflare/) which has the same issue that is solved using an environment variable specifying the Node.js version added after clicking on an `Advanced` button in the UI, which is the exact same process on …

Update Render deploy guide to account for Astro 2.0 Node.js version requirement

---

src/pages/en/guides/deploy/gitlab.mdx

- Minor content fix (wrong version in gitlab yaml)
As of Astro Version 2.0.0, a node version >= 16 is required, which means that `node:lts` is better suited than `node:14` in the deploy file `.gitlab-ci.yml` for GitLab. This ensures that people who copy the file from the docs won't end up with a broken CI/CD pipeline.

Updates Node Version requirements in GitLab deploy

---

src/pages/en/reference/api-reference.mdx

Replace mention of the removed `slug()` function used with content collection in beta with the `slug`-property in frontmatter released in 2.0.0.
Related withastro/astro#5941

Update API reference with new slug frontmatter property

---

src/pages/en/guides/configuring-astro.mdx

delete `(` that should not exist in mjs config intelliSense

fix: delete `(` that should not exist in mjs config intellisense

---

src/pages/en/guides/testing.mdx

- Although this is very trivial, while translating testing.mdx, I found that one of html attributes in the code sample was enclosed in single quotes. Since there seems to be no particular reason to use single quotes here, I have changed them to double quotes for consistency.

Use double quotes to enclose html attributes for consistency

---

src/pages/en/guides/markdown-content.mdx

- Minor content fixes (broken links, **typos**, etc.)
Fix the missed closing `</p>` tag
```html
<p>{frontmatter.description}<p>
```
to
```html
<p>{frontmatter.description}</p>
```
Yes, you can find my change [here](https://deploy-preview-2527--astro-docs-2.netlify.app/en/guides/markdown-content/#frontmatter-layout)

Fix `</p>` typo in markdown-content.mdx code example

---

src/i18n/translation-checkers.ts
src/i18n/util.ts

- Fix importsNotUsedAsValues error in i18n/translation-checkers.ts and i18n/util.ts.

Fix `importsNotUsedAsValues` error in src/i18n

---

src/pages/en/reference/publish-to-npm.mdx

- Add the `withastro` keyword in one additional place in the npm publishing guide. We mention this elsewhere in the guide but missed this one spot.

Add `withastro` keyword to npm publishing guide

---

src/pages/en/tutorial/2-pages/2.mdx

Addresses this Feedback Fish:
> In those example, the images are not being rendered...
If a reader doesn't know what frontmatter is, they might expect the image to be rendered alongside the rest of the document. (This is especially true since the title _does_ show up, as we have it in both the frontmatter and the body.)
This change briefly introduces frontmatter and tells the reader not to expect the image to show up.

Tutorial 2.2 - Explain Frontmatter

---

src/pages/en/guides/cms/storyblok.mdx

- Updates the `getStaticPaths` example to call the API _after_ the paths are generated, on each resulting page. This allows Storyblok Bridge to work. Thanks to Storyblok's @manuelschroederdev for this fix!
- Removes the `undefined` route generation. This no longer works, as we need a slug to be passed through to the page. The user can specify their own `index.astro` page if they want the `undefined`/home route, and this isn't integral to learning Storyblok.

Correct Storyblok SSG sample

---

src/pages/es/guides/markdown-content.mdx
src/pages/es/reference/errors/content-schema-contains-slug-error.mdx
src/pages/es/reference/errors/invalid-content-entry-slug-error.mdx
src/pages/es/reference/publish-to-npm.mdx

Multiple page updates based on these commits as follows:
- - markdown-content.mdx → 471f2388d6ef0d60211eea75afd683c6138d415d & f3b0625a51f54636e203f8650352cb7fc4c443b6
- - content-schema-containts-slug-error.mdx → 0de27116b410c0e68d3702ff6f944edc5235a12b
- - invalid-content-entry-slug-error.mdx → 0de27116b410c0e68d3702ff6f944edc5235a12b
- - publish-to-npm.mdx → e58d23c63167bcf2c96e9a8a7f171f63f3286b21, 9d4bd688365a562ccf013310d8840f3271c232d9 & c5f02333db29b2810d986025d9f418d22f7693a0
`cloudflare.mdx` doesn't need update to spanish cause they fixed small typos which were translated properly based on these commits  471f2388d6ef0d60211eea75afd683c6138d415d & …

i18n(es): Update of `markdown-content.mdx`, `content-schema-containts-slug-error.mdx`, `invalid-content-entry-slug-error.mdx` and `publish-to-npm.mdx`

---

src/pages/pt-br/reference/errors/mdx-integration-missing-error.mdx
src/pages/pt-br/reference/errors/missing-media-query-directive.mdx
src/pages/pt-br/reference/errors/no-adapter-installed.mdx
src/pages/pt-br/reference/errors/no-client-entrypoint.mdx
src/pages/pt-br/reference/errors/no-client-only-hint.mdx
src/pages/pt-br/reference/errors/no-matching-import.mdx
src/pages/pt-br/reference/errors/no-matching-renderer.mdx
src/pages/pt-br/reference/errors/no-matching-static-path-found.mdx
src/pages/pt-br/reference/errors/only-response-can-be-returned.mdx
src/pages/pt-br/reference/errors/page-number-param-not-found.mdx
src/pages/pt-br/reference/errors/reserved-slot-name.mdx
src/pages/pt-br/reference/errors/static-client-address-not-available.mdx
src/pages/pt-br/reference/errors/static-redirect-not-available.mdx

Added translations for:
- `mdx-integration-missing-error.mdx`
- `missing-media-query-directive.mdx`
- `no-adapter-installed.mdx`
- `no-client-entrypoint.mdx`
- `no-client-only-hint.mdx`
- `no-matching-import.mdx`
- `no-matching-renderer.mdx`
- `no-matching-static-path-found.mdx`
- `only-response-can-be-returned.mdx`
- `reserved-slot-name.mdx`
- `static-client-address-not-available.mdx`
- `static-redirect-not-available.mdx`

i18n(pt-BR): Add error reference pages translations PART THREE

---

src/pages/ja/core-concepts/astro-pages.mdx

- Update astro-pages.mdx.
- https://github.com/withastro/docs/pull/2409
- https://github.com/withastro/docs/pull/2371

i18n(ja): Update astro-pages.mdx

---

src/pages/en/guides/typescript.mdx
src/pages/es/guides/typescript.mdx
src/pages/ja/guides/typescript.mdx
src/pages/pt-br/guides/typescript.mdx
src/pages/zh-cn/guides/typescript.mdx

- Fix code example in docs
- Code example for [Built-in HTML attributes](https://docs.astro.build/en/guides/typescript/#built-in-html-attributes) throws error via linting and `astro check`
- Error: `Spread types may only be created from object types.`
**Current example:**
```astro
---
import type { HTMLAttributes } from 'astro/types'
// use a `type`
type Props = HTMLAttributes<'a'>;
// or extend with an `interface`
interface Props extends HTMLAttributes<'a'> {
myProp?: boolean;
}
const { href, ...attrs } = Astro.props;
---
<a {href} {...attrs}>
<slot />
</a>
```
**Change added to docs via this PR in files where section is present:**
```astro
---
import type { HTMLAttributes } from 'astro/types'
// use a `type`
type Props = HTMLAttributes<'a'>;
// or extend with an `interface`
interface …
```

fix: code example for built-in html attributes

---

src/pages/en/guides/images.mdx
src/pages/fr/guides/client-side-scripts.mdx

- Replaces https://github.com/withastro/docs/pull/2415
- Closes #2586 
- Documents the `?url` workaround for using image imports with `<img>` when the image integration is installed
- We could also document the `rocket.src` workaround, but I chose to go with one recommended solution for this PR.

Warning for using `<img>` with the image integration installed

---

astro.config.ts
src/pages/en/guides/configuring-astro.mdx
src/pages/en/guides/environment-variables.mdx

- Closes #2506, but **doesn't** add a caution box to the integration API reference. That's because this doesn't have anything to do with integrations specifically, but rather the Astro config file.
- Documents the `loadEnv` workaround for accessing environment variables in the Astro config file. This comes up often in support, but is missing from our docs.
- Updates wording to implicate that `import.meta.env` **is** available - it just doesn't have `.env` variables on it. This is why we can use `import.meta.env.MODE` to tell `loadEnv` to grab the right `.env` files.

Documents `loadEnv` workaround 

---

src/pages/en/guides/deploy/cloudflare.mdx

- New or **updated** content
When Cloudflare's Auto Minify setting is enabled for HTML, client-side hydration may not function properly as the HTML does not match the one it expected to find. After using Astro + Cloudflare + Vue myself, I ran into this issue, and when digging into I found this thread: https://github.com/vuejs/vitepress/issues/1143#issuecomment-1210294112
Vitepress actually has this in the docs, so I figured it may save others some trouble if we add it to the Astro docs as well.

Covered Auto Minify settings

---

src/pages/en/guides/content-collections.mdx

Highlight the necessity to use a rest parameter when using subdirectories to organize collections.
I updated the docs to include a hint to highlight the necessity of a rest parameter when using subdirectories to organize collections. 
This wasn't really obvious to me since the error that was thrown (`Expected "slug" to match "[^\/#\?]+?", but got "foo/bar"`) when starting `dev` and trying to `build` only gave some kind of hint to what went wrong.
The blog starter template helped me clarify. In hindsight it was clear that this was necessary but I thought it would be a good addition to the docs since others might run into the same issue.
Thanks btw. for the amazingly wonderful great work you guys are doing 🥳

Add hint for rest parameter subdirectory necessity

---

src/pages/en/guides/integrations-guide.mdx

Closes: https://github.com/withastro/docs/issues/2612
Adds a section explaining how to manually remove an integration

Add section on removing an integration

---

src/pages/en/guides/configuring-astro.mdx

Added the frontmatter to codesample.
This makes the Astro codesample highlights work again

Add frontmatter to make code highlight work

---

src/pages/en/guides/configuring-astro.mdx

Revert #2637 to change the code block extension to `js` instead of adding a frontmatter

Change code block extension to make syntax highlighting work in `configuring-astro.mdx`

---

src/pages/en/guides/markdown-content.mdx

Minor content fixes (broken links, typos, etc.):
- use `defineConfig` consistently
- use the code "title" when not used
---
I find it confusing, when the docs sometimes use one pattern and other times something else. This changes it to use defineConfig everywhere on this page.

docs: markdown-content: use `defineConfig` consistently

---

src/content/docs/en/guides/deploy/sst.mdx

create-sst@2.0 and sst@2.0  were released last week, so there's no need to use create-sst@rc anymore.

SST deploy: no need for create-sst@rc anymore

---

package.json
pnpm-lock.yaml

Upgrade vite to 4.1 which should make build less likely to OOM.
Also upgraded vitest so that internally it uses the same vite version.

Bump vite to 4.1

---

src/content/docs/en/guides/images.mdx

- 
- Addresses #2620 along with https://github.com/withastro/astro/pull/6290
- Removes "local" to describe images in path, to reduce confusion as they're treated like remote images
- Reorders to remote -> src -> path to match https://github.com/withastro/astro/pull/6290

Image guide tweak for images in path clarity

---

src/content/docs/en/guides/cms/contentful.mdx

Addresses Feedback Fish:
> https://docs.astro.build/en/guides/cms/contentful/#fetching-data
The code block has two errors in it. The `BlogPost` interface has a `title` and `content` key but towards the bottom `item.fields.name` is used instead of `items.field.title`. Also, where it sets the html to the article, `items.fields.content` is used instead of `item.fields.content`.

Contentful: Correct code sample

---

src/pages/open-graph/[...path].ts

This pull request resolves a font rendering issue with Open Graph images that are generated for Korean pages.
I discovered that the matching Korean fonts do not exist which caused this error:
I added Noto Sans KR fonts and the result is:

Fix font rendering problem with og images for Korean pages

---

src/content/docs/en/guides/cms/storyblok.mdx

Using this example I ran into an issue with the static site build (astro build) where the directly imported Page component was in the wrong position in the generated bundle causing a "Cannot access '$$Page' before initialization" error.  Switching to use the StoryblokComponent resolved the issue.  See example on the storyblok/stpryblok astro Readme: https://github.com/storyblok/storyblok-astro#2-getting-storyblok-stories-and-using-the-storyblok-bridge
- Closes # 
-  Updates single page code example.

Update example for Generating Pages

---

src/content/docs/en/guides/markdown-content.mdx

- 
- Addresses Feedback Fish:
> remark-toc  ... other than adding to the config, what else is there??? I do that and it does not show up on my page. This is not clear.
- Adds a note that remark-toc expects a "toc" or "table of contents" heading by default in order to show the table of contents.
- Adds a remark-toc customization to the Customizing a plugin example

Remark-toc heading disclaimer

---

scripts/lib/translation-status/template.html
scripts/translation-status.ts

- Add meta tags
- Tweak some styles
- Use more accessible mark-up than was possible on GitHub
Mostly very subtle visually. Here is before on the left and after on the right:
Similarly for the table that is just slightly tweaked:
Some of the key stuff is invisible changes to mark-up to use `aria-hidden="true"` on emoji and avoid abusing the `<code>` element like we used to to get a kind of “button” styling.

Small tweaks to the new i18n status page

---

src/content/docs/es/reference/errors/unknown-clierror.mdx
src/content/docs/es/reference/errors/unknown-compiler-error.mdx
src/content/docs/es/reference/errors/unknown-config-error.mdx
src/content/docs/es/reference/errors/unknown-content-collection-error.mdx

Translated the following pages:
- `unknown-clierror.mdx`
- `unknown-compiler-error.mdx`
- `unknown-config-error.mdx`
- `unknown-content-collection-error.mdx`

i18n(es): Translated pages

---

src/content/docs/en/reference/integrations-reference.mdx

- Closes #2721
- Removes the parameters from `astro:build:start` in the integrations reference, to match the current APIO

Remove parameters from astro:build:start

---

src/content/docs/en/guides/imports.mdx
src/content/docs/en/reference/api-reference.mdx

It was pointed out on Discord that this example renders multiple h1 tags, which is bad for accessibility. This PR changes them to h2s.

Fix multiple `h1`s in glob example

---

src/content/docs/en/guides/content-collections.mdx

Coming from the blog tutorial, there are some slight changes to the conversion doc to make it 100% clear what needs to be done. Specifically [the new branch references the publish date](https://github.com/withastro/blog-tutorial-demo/blob/content-collections/src/content/config.ts#L6) as an actual `z.date()` object. If users are coming over form the tutorial, they'll have written their dates as `publishDate: 2022-02-03` not `publishDate: "2022-02-03"`. Copying the code as is with the transformation will actually cause a build error.
I left the old transformation in there as a comment, because it's difficult to know what a user would actually use, and seeing the transformation is helpful to show that types can be transformed.
With the RSS …

Make collection conversion more clear against the existing tutorial

---

.github/workflows/ci.yml

- Tells GitHub Actions to run our CI tasks for a “merge group”
- Unlocks Merge Queues, see: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

Enable CI for `merge_group`

---

src/content/docs/en/reference/cli-reference.mdx

This PR adds some content to a tip of the CLI.
The tip says that `astro build` and `astro dev` run the `sync` command. Although, `astro check` does the same. This PR adds this information to the website.

add `astro check` to CLI tip

---

src/content/docs/en/guides/testing.mdx

- `npm run cypress` failed for me, because the spec file the guide had me create was named `index.spec.ts`, but cypress was looking for `index.cy.ts`. Therefore, I updated the guide to state that you should create an `index.cy.ts` file instead.
- The guide was using `.ts` extensions in some places, and `.js` extensions in others. Therefore, I changed the `.ts` extensions to `.js` to make it more consistent.

Minor fix to file extensions in cypress section

---

src/content/docs/en/guides/content-collections.mdx

For Astro newcomers it might not be clear what the consequences of this statement are:
> Content collections are stored outside of the `src/pages/` directory
Therefore I'd like to add an explicit sentence spelling out the consequence of using content collections that there will be no automatically generated routes for collection items.

docs: clarify manual routing for content collections

---

src/components/CodeSnippet/CodeSnippet.astro

- Closes #1790 (and maybe #2726?)
- Changes how the glow around our code samples is rendered. Previously this used the `drop-shadow` CSS filter which has poor performance in some browsers. I’ve replaced this with several `box-shadow`s tweaked to try and replicate roughly the same effect. This isn’t quite possible but hopefully folks agree the difference is small enough to be OK for the performance gain.
|---|---|
| <img width="575" alt="image" src="https://user-images.githubusercontent.com/357379/222277408-e5e00eab-dfd2-4191-b286-3a4133638cb6.png"> | <img width="575" alt="image" src="https://user-images.githubusercontent.com/357379/222277503-f86340e2-f775-4155-a9be-27b98730db70.png"> |
| <img width="575" alt="image" …

Replace `drop-shadow` with `box-shadow` in `<CodeSnippet>`

---

src/content/docs/en/guides/cms/tina-cms.mdx

- Minor content fixes (broken links, typos, etc.) -> broken link.
This caused privacy error in Chrome browsers when trying to open the link.
Your connection is not private
Attackers might be trying to steal your information from www.tina.io (for example, passwords, messages or credit cards). Learn more NET::ERR_CERT_AUTHORITY_INVALID

Fix: broken link - removed www. from https link

---

src/content/docs/en/reference/integrations-reference.mdx

Fixes a typo of the type of `'astro:build:start'` in the "Quick API Reference" section.

Fixes a typo of the type of `'astro:build:start'`

---

src/i18n/en/nav.ts

Puts the Image Service API reference page in the sidebar

[assets] add Image API to reference navigation

---

src/content/docs/en/recipes/build-forms.mdx

- Closes # 
Adding return before Astro.redirect activates the redirect property. Otherwise, it doesn't work.
I just added `return`.

Add return before Astro.redirect

---

src/content/docs/en/guides/integrations-guide/sitemap.mdx

Switch syntax highlighting to yaml
Changes the syntax highlighting for sitemap docs to `yaml` instead of none.

Get rid of ‘txt not found’

---

src/content/docs/en/recipes/docker.mdx

This pull request is a fix for a configuration issue in the Nginx file. 
The current Nginx configuration does not automatically serve index.html files in subdirectories such as /dist/about/index.html, resulting in a "301 Moved Permanently" error when attempting to access the /about URL (for example). This error creates an issue when using a reverse proxy upstream, because Nginx redirects us to an URL with the container's port.

Fix of the Nginx configuration file

---

src/content/docs/en/recipes.mdx
src/content/docs/es/guides/integrations-guide.mdx
src/content/docs/es/guides/server-side-rendering.mdx
src/content/docs/es/reference/configuration-reference.mdx
src/i18n/es/nav.ts

Updated files as the following list:
- `configuration-reference.mdx` -> 2c7e9f3d2a0d3548427495d7be30bb340ac13e98
- `server-side-rendering.mdx` -> 60f35d65a6ef99bb13fafbbc312c332213ab5a70
-  `integrations-guide.mdx` -> 60f35d65a6ef99bb13fafbbc312c332213ab5a70

i18n(es): Update of `configuration-reference.mdx`, `server-side-rendering.mdx` & `integrations-guide.mdx`

---

public/index.css
src/components/Checklist.astro
src/components/tutorial/Box.astro
src/components/tutorial/TutorialNav.astro
src/components/tutorial/UnitProgressIcon.astro

A few changes to get our tutorial ready for translations and to improve accessibility.
- Added RTL styles to `<Box/>` and `<Checklist/>` components:
| ![image](https://user-images.githubusercontent.com/61414485/225082788-2b091f44-e716-45d6-a58e-c6a7297c6ae8.png) | ![image](https://user-images.githubusercontent.com/61414485/225081647-f16be2aa-ae11-400f-b0f2-a312e21e922d.png) |
- Increased `line-height` for lists with `<kbd/>` elements
| ![image](https://user-images.githubusercontent.com/61414485/225083484-c1033bce-8e99-425c-bf0b-6e431fb284e9.png) | ![image](https://user-images.githubusercontent.com/61414485/225083269-e1352861-ce22-4c6f-8ecd-688a81926e93.p …

Tutorial Styling Improvements

---

package.json
pnpm-lock.yaml

Upgrades to the latest version of `astro-og-canvas` which manually frees memory after generating each image. #2856 builds were erroring and my working hypothesis is that we were hitting an internal memory limit in canvaskit-wasm.
I’m testing this update against the changes in #2856 in #2869.

Bump `astro-og-canvas` to 0.1.7

---

src/content/docs/en/reference/api-reference.mdx

The example shows how to get entries by `id`, but the function is actually designed to retrieve entries by their `slug`. I have updated the example code and the function type signature to reflect the correct usage.

Fix `getEntryBySlug` function usage example

---

src/content/docs/en/guides/markdown-content.mdx

Remove old `extendDefaultPlugins` option from config examples for remark plugins
With the changes to markdown plugin configuration in 2.0 the second MDX  example in step 2 of [this section](https://docs.astro.build/en/guides/markdown-content/#modifying-frontmatter-programmatically) may be redundant since the first example will now work with MDX by default, should it be removed too?

Remove old `extendDefaultPlugins` from examples

---

netlify.toml
src/components/HeadCommon.astro
src/components/LeftSidebar/LeftSidebar.astro
src/layouts/BaseLayout.astro

- Improve UX while browsing the docs site!
- Add local cache headers for all statically generated (fingerprinted!) assets
- Inline a few very small scripts that were important to be inlined for reducing thrash on load
- ~~Move `index.css` and `theme.css` out of `public/` and into `src/` so that they get automatic fingerprinting for free.~~ CSS Ordering issues, had to revert this.
- Replace `scrollIntoView` sidebar scroll position method with a LocalStorage approach which has zero flash of unscrolled content (Note: I can still see some flash of unscrolled content on "Fast 3G" while the sidebar loads in, since this script runs inline but only after its fully populated. Maybe there's some hack where we could give it a min-height that can be scrolled _before_ the content loads in? I'll leave …

improve performance, fix flash of content on load

---

src/content/docs/en/reference/image-service-reference.mdx

https://github.com/withastro/astro/pull/6555 adds a new hook to the Image Service API that can be used to validate and augment the passed options. The built-in services uses this hook to set the default format as `webp` if the user hasn't passed a format, for example.
It takes the same `options` as the other hooks, so an `ImageTransform` and it returns an ImageTransform as well. Returning an `ImageTransform` is mandatory, so the implementation should probably always end with `return options;`
This PR additionally contain some misc fix to the rest of the file

feat(image_services): Add mention of new validateOptions hook

---

src/content/docs/en/guides/typescript.mdx

In TypeScript 5.0, the latest version, the team deprecated `importsNotUsedAsValue` in favour of a boolean `verbatimModuleSyntax`. It does the same thing, it's just easier to use.
This PR updates our guidance to show both the new and old options.

Document `verbatimModuleSyntax` for TS 5.0 users

---

src/content/docs/en/guides/assets.mdx

https://github.com/withastro/astro/pull/6627 changes how frontmatter images work so they're now relative to the current file instead of `src/assets`. People can still use `src/assets` through the provided alias `~/assets/` or through pathing to it relatively.

Update assets guide to mention that images in the frontmatter are relative to the current file

---

netlify.toml

I noticed we don’t currently have a server-side redirect for folks visiting https://docs.astro.build
Instead, the page has to load, then the `<meta>` redirect is used to take us to the English landing page. This can be a little slow, so I’ve updated the Netlify config to do this redirect on the server instead of in the browser.

Redirect `/` to `/en/getting-started/` in Netlify config

---

src/content/docs/en/guides/imports.mdx

- Updates the Imports page to make it clear that Astro already supports multiple runtimes, using adapters
- Replace the links to Deno and Cloudflare homepages with links to our adapters

Astro is _already_ compatible with multiple runtimes

---

.github/workflows/discord-i18n-ping.yml

- Changes the GitHub Actions workflow to run at `0 10 * * TUE`, which is 10:00 UTC, instead of 0:00 UTC like before.

Change Translation Tuesday bot post time to 10:00 UTC

---

src/content/docs/en/reference/integrations-reference.mdx

- Remove suggestion that `astro:server` integration hooks run in "preview" mode. They only run in dev!

Fix: remove "preview" mode from `astro:server` docs

---

src/content/docs/en/guides/typescript.mdx

Our tooling does not automatically uses `type Params` to type `Astro.params`. It never has, actually. Additionally, the two slash commands were in the wrong spot

fix: Fix InferGetStaticPropsType example

---

src/content/docs/en/guides/typescript.mdx

This updates the `getStaticPaths` example in the TypeScript guide to be fully typed. The syntax does look weird because of `satisfies`, but it's important to show that this is the best way to type `getStaticPaths`, because typing it normally (using `: GetStaticPaths`) breaks `InferGetStaticParamsType` (and its Props equivalent) since it works by inferring the return value (which typing it directly removes the ability to)

fix(typescript): Update getStaticPaths option to be fully typed

---

src/content/docs/en/recipes/add-yaml-support.mdx

- Closes #3019
- What does this PR change? Add a note for typing yaml files
> While you can now import YAML data in your Astro project, your editor will not provide types for the imported data. To add types, create a `*.d.ts` file in your project and add the following:
>    ```ts
>    // specify the file extension you want to import
>    declare module "*.yml" {
>      const value: any; // Add better type definitions here if desired
>      export default value;
>    }
>    ```
>    This will allow your editor to provide type hints for your YAML data.

Add note on yaml types

---

src/content/docs/zh-cn/core-concepts/astro-components.mdx

Typo: `frontmatter scispt` -> `frontmatter script`

Fix typo in `zh-cn` -> `astro-components.mdx`

---

src/content/docs/en/guides/testing.mdx

- wrong function name in doc's testing section
- Closes #3070 
- What does this PR change? Give us a brief description: Change function name from playwright one to cypress one.
- Did you change something visual? A before/after screenshot can be helpful: I think it's not need a screenshot because basically changed a word.

docs: fix typo, wrong hint function name

---

src/content/docs/en/guides/assets.mdx
src/content/docs/en/reference/image-service-reference.mdx

https://github.com/withastro/astro/pull/6848 updates the configuration setting for the image service to be an object of the following shape : `service: {entrypoint: string, config: Record<string, any>}` instead of just being a string. This allow user to pass configuration to the image service. For instance, Vercel uses this to provide a list of allowed widths.
This PR updates the Assets and Image Service pages to include this new information and all the associated utilities it added. Additionally, this PR adds an example for `validateOptions`, as it was previously missing.

docs: update assets related pages for new configuration shape

---

src/content/docs/en/guides/assets.mdx

- Closes #3143  
- What does this PR change? Updates the Astro Assets `sharp` image service import into `astro.config.mjs` since `getSharpImageService` isn't a function that exists. It should instead be replaced with `sharpImageService`.

Update Assets image service import

---

src/content/docs/en/core-concepts/endpoints.mdx

- I found some issues in the example code in the [params and Dynamic routing](https://docs.astro.build/en/core-concepts/endpoints/#params-and-dynamic-routing) section while browsing through the documentation. The expected result mentioned in the documentation for the file path `src/pages/[id].json.ts` and the routes generated by the `getStaticPaths()` function is _**“This will generate three JSON endpoints at build time: `/api/1.json, /api/2.json, /api/3.json`.”**_  However, the actual result generated by the example code is **_`/0.json, /1.json, /2.json`._**
- So I modified the file path in the sample code in the document to `scr/pages/api/[id].json.ts`, and changed the expected generated JSON endpoints in the document to the actual ones that will be …

Fix the example code errors in the Endpoints section

---

src/components/RecipeLinks.astro

- Updates `<RecipeLink>` to work better with our i18n system
- Slugs can be set using their translation path, e.g. `pt-br/recipes/foo`, even if the translation doesn’t exist yet — we’ll grab the English title in this case.
- When a recipe hasn’t been translated yet, the link will be shown with an `(EN)` suffix on non-English pages like we do for other links on the site.
Here’s an example of the component on the Polish endpoints guide, which hasn’t been translated yet: 
This PR should unblock proper `<RecipeLink>` usage in #3044.

Refactor `<RecipeLink>` to handle i18n

---

src/content/docs/en/guides/assets.mdx

https://github.com/withastro/astro/pull/6995 updates the utilities methods to come from `astro/config` instead of `astro/assets`, since the later didn't work

fix: update sharpImageService example to come from the right place

---

src/components/CodeSnippet/copy-button.ts
src/components/CodeSnippet/shiki-block.ts
src/components/CodeSnippet/shiki-line.ts
src/components/RightSidebar/TableOfContents.tsx
src/util/html-entities.ts

- Yet another fix for #3186 😁 
- Closes #3186
- Also closes #3190
- @MoustaphaDev’s PR #3189 could still be useful: this PR applies a patch for the two problematic characters we currently have (`<` and `&`) but it may make sense to use that more robust solution — we could rebase that PR onto this one

Fix escaped code in code copy button

---

src/content/docs/en/guides/backend/google-firebase.mdx
src/content/docs/en/guides/deploy/google-firebase.mdx

We currently have two separate Firebase pages: a Firebase Hosting deployment guide and a Firebase backend services recipe for authentication.
This PR adds a prominent link to the other one on each of the pages.
Out of scope, for future follow up: 
- we can discuss whether one single Firebase page makes more sense, or whether continuing to separate our content by user goal (e.g. Deploy your site, add a backend service) makes more sense.

Link Firebase pages to each other

---

src/util/getPageCategory.ts

Updates our search category definitions:
- All "special" guides, including new ones that never got special categories, as well as individual recipes, are now "Recipes" (instead of Deploy Guide, Integration Guide, e.g.)
- Also categorizes our Upgrade Guides (to v1, v2)
Will need to re-run Algolia to pick up the changes. 
Currently:
("Deploy Guide" too specific, "Learn" too general. Both will now show up under "Recipes")

add recipes as search category

---

src/components/CodeSnippet/shiki-line.ts

Fix #3215
Closes #3217 
Fix shiki inline highlight through `CodeSnippet.astro`. The code before used to anticipate rehype to encode the HTML entities, now with `rehype-optimize-static` it doesn't as it uses `set:html` instead, which skips through rehype rendering, but through Astro instead.
Before
After
NOTE: If one day we remove `rehype-optimize-static`, the highlighting offset problem will return. I can't seem to find a way to fix both at once. For now I added comments, to link the two cases together.

fix: handle inline highlight due to rehype-optimize-static

---

src/content/docs/en/guides/middleware.mdx

remove typo `9` at the beginning of a sentence in locals section
- removes typo `9` at the beginning of a sentence in the locals section

en-only: fix typo in  middleware.mdx

---

src/content/docs/en/core-concepts/project-structure.mdx

- Closes #2797
- What does this PR change? Adds a section "Feature Directories" to the project structure guide to describe `src/content` & `src/assets`

Add feature directories to project structure guide

---

src/content/docs/en/guides/server-side-rendering.mdx

Annoyingly, here's a PR to your branch, @matthewp :sweat_smile: 
See what you think about updating the entire hybrid rendering section to make the two flow better together.

Update the entire hybrid rendering section

---

src/content/docs/en/guides/middleware.mdx

@ematipico I think it's now easier to say right when we define `onRequest()` that a response is required, and perhaps it fits better up there because it is required. 
What do you think about a change in where the information goes like this?

change where required response is mentioned

---

src/content/docs/zh-cn/reference/errors/invalid-component-args.mdx
src/content/docs/zh-cn/reference/errors/invalid-prerender-export.mdx
src/content/docs/zh-cn/reference/errors/no-adapter-installed.mdx
src/content/docs/zh-cn/reference/errors/no-matching-import.mdx
src/content/docs/zh-cn/reference/errors/reserved-slot-name.mdx

Added 5 Astro error translations:
`reserved-slot-name.mdx` (E03016)
`no-adapter-installed.mdx`(E03017)
`no-matching-import.mdx`(E03018)
`invalid-prerender-export.mdx`(E03019)
`invalid-component-args.mdx`(E03020)

i18n(zh-cn): Add 5 error translations

---

src/content/docs/en/reference/directives-reference.mdx

- Closes #3165
> Using define:vars in a <style> within a component markup still bundles the component styles, i.e., contrary to what's documented. Please refer to the #3165 for more details.

fix: removes wrong inline style info

---

src/content/docs/en/core-concepts/astro-syntax.mdx

- Closes https://github.com/withastro/docs/issues/3269
Removed the example where you should wrap elements inside in a fragment in order to avoid errors with the old compiler, there's no need to use fragments to use JSX expressions.

Update: `astro-syntax.mdx`

---

src/components/RecipeLinks.astro

- Uses the page’s language in links generated by the `<RecipeLinks>` component, even if the link is to fallback content. (Currently it uses the `/en/` on non-English pages, breaking our link checks.)
- Unblocks #3214

Fix bug in how recipe links handles fallback slugs

---

src/components/HeadCommon.astro

Updates how the Fathom Analytics script is loaded.
**Why?** Fathom recently ran into an issue with some events being lost when the script is loaded via a custom subdomain.  The bug is specifically related to SSL certificates sometimes not auto-renewing on time, ours hasn't been impacted yet so we shouldn't have lost any analytics data to date.

Moving off of custom domains for Fathom analytics

---

src/content/docs/en/guides/content-collections.mdx

- What does this PR change? Adds a link to the MDX integration to the "Content Collections" guide. Change inspired by a [Support thread](https://discord.com/channels/830184174198718474/1111363939691921450/1111363939691921450) as we previously didn't mention the MDX integration despite mentioning MDX a lot.

Link to MDX integration

---

src/content/docs/en/guides/content-collections.mdx

Someone was getting an error setting up their content collections with `type: content` because they hadn't yet upgraded to 2.5.0.
This quick change explicitly says that the `type` property was added in 2.5.0. We shouldn't need this for very long, and we can figure out a better way to handle changes like this. But there will still be some people on other pre 2.5 versions of Astro who may run into this issue if they just try setting up content collections from scratch with our existing docs, not realizing this isn't just how it always was.

content collections `type` only v2.5.0+

---

src/content/docs/en/guides/cms/payload.mdx

Directs users to payloads installation guide when mentioned in step 3 on [this page](https://docs.astro.build/en/guides/cms/payload/#prerequisites).

docs: direct users to payloads install instead of home page

---

src/content/docs/en/guides/fonts.mdx

The link titled ‘Fonts catalogue’ points to a 404 page: https://fontsource.org/fonts 
I have edited it to point to the main page which still has the catalogue search filter.
Fixed broken link
- Closes # 

Removed link to missing 404 page

---

src/content/docs/en/tutorial/5-astro-api/2.mdx

There was a missing semi column when importing `BlogPost` in the final code sample.

Fix typo in `src/content/docs/en/tutorial/5-astro-api/2.mdx`

---

src/content/docs/fr/reference/errors/config-legacy-key.mdx
src/content/docs/fr/reference/errors/config-not-found.mdx
src/content/docs/fr/reference/errors/invalid-frontmatter-injection-error.mdx
src/content/docs/fr/reference/errors/markdown-frontmatter-parse-error.mdx
src/content/docs/fr/reference/errors/mdx-integration-missing-error.mdx
src/content/docs/fr/reference/errors/unknown-config-error.mdx
src/content/docs/fr/reference/errors/unknown-markdown-error.mdx

- Translated:
- markdown errors
To do:
- Astro errors
Done:
- misc. errors: #3386
Note: this PR doesn’t depend on part 1 in any way, I’m just splitting it for ease of review

i18n(fr): create error code references part 2

---

src/content/docs/fr/reference/error-reference.mdx
src/content/docs/fr/reference/errors/collection-does-not-exist-error.mdx
src/content/docs/fr/reference/errors/content-collection-type-mismatch-error.mdx
src/content/docs/fr/reference/errors/content-schema-contains-slug-error.mdx
src/content/docs/fr/reference/errors/csssyntax-error.mdx
src/content/docs/fr/reference/errors/data-collection-entry-parse-error.mdx
src/content/docs/fr/reference/errors/generate-content-types-error.mdx
src/content/docs/fr/reference/errors/invalid-content-entry-frontmatter-error.mdx
src/content/docs/fr/reference/errors/invalid-content-entry-slug-error.mdx
src/content/docs/fr/reference/errors/mixed-content-data-collection-error.mdx
src/content/docs/fr/reference/errors/unknown-clierror.mdx
src/content/docs/fr/reference/errors/unknown-content-collection-error.mdx
src/content/docs/fr/reference/errors/unknown-csserror.mdx

- Updated main `error-reference.mdx` page to have new error links
- Translated:
- content collection errors
- cli errors
- css errors
To do:
- Astro errors
- Markdown errors: #3387

i18n(fr): create error code references part 1

---

src/content/docs/en/guides/content-collections.mdx

- Replaces filter back to what it was previous to https://github.com/withastro/docs/pull/2371. Filtering to non-drafts makes sense too, but currently either the variable name (and the copy above) or the filter should change for consistency.
- @FredKSchott, were you thinking of maybe changing it to be non-draft entries?

Update content-collections.mdx: true drafts

---

src/content/docs/en/guides/assets.mdx

Minor content update to the experimental assets page.
Updates the suggestion to use store images in `src/assets/` to be strong-ish, with a reason, but clearly optional.
Also removes suggestion that images MUST be in this folder to work in component files and Markdown.

[assets] folder recommendation updated

---

src/content/docs/en/concepts/mpa-vs-spa.mdx

This PR aims to achieve consistency in the wording of "a SPA" and "an SPA" in the en [SPA vs MPA](https://github.com/withastro/docs/blob/main/src/content/docs/en/concepts/mpa-vs-spa.mdx) concept page. In some instances the wording "an SPA" is used and in others "a SPA" is used. "an SPA" seems to appear more commonly.
This PR changes the two instances of "a SPA" to "an SPA" to achieve consistency.

Achieve consistency with indefinite article in MPA vs SPA concept en-only

---

src/content/docs/en/guides/backend/xata.mdx

Hey folks, here I am again 🥳
Trying to fill up that stub for Xata as I promised.
-  Updated content
Adds a quick start guide with Xata.
- [Backend Service Guide: Xata](https://deploy-preview-3207--astro-docs-2.netlify.app/en/guides/backend/xata/)

Add Xata guide to BE Recipe section

---

src/content/docs/es/reference/error-reference.mdx
src/content/docs/es/reference/errors/invalid-dynamic-route.mdx

Translated `invalid-dyndamic-route.mdx` to spanish and added the reference to `error-reference.mdx`

i18n(es): Translated `invalid-dyndamic-route.mdx`

---

src/content/docs/en/reference/errors/locals-not-serializable.mdx

This error has been removed from Astro, so won’t update with changes made there. I still think we should keep the page around in case someone running an old version of Astro runs into the error, so fixing the message formatting in docs.

Fix formatting on an error page

---

src/content/docs/es/reference/configuration-reference.mdx
src/content/docs/es/reference/errors/locals-not-serializable.mdx

Updated `locals-not-serializable.mdx` & `configuration-reference.mdx`.
* `locals-not-serializable.mdx` -> [`d8a80f0`](https://github.com/withastro/docs/commit/d8a80f01dfc19ae6d2cf039e6e6e93f3e400bc01)
* `configuration-reference.mdx` -> [`5e76ca4`](https://github.com/withastro/docs/commit/5e76ca4701b0c3e52aa6bfb286974b528d99cc4d)

i18n(es): Updated `locals-not-serializable.mdx` & `configuration-reference.mdx`

---

src/content/docs/es/guides/server-side-rendering.mdx
src/content/docs/es/reference/errors/csssyntax-error.mdx

Updated `server-side-rendering.mdx` with the commit [`278f33e`](https://github.com/withastro/docs/commit/278f33ec366aa379e1919be63418d67fa28e48f2) & `csssyntax-error.mdx`
> The update of `csssyntax-error.mdx` is to show this page as updated because the translation update against the original would have no change.

i18n(es): Updated `server-side-rendering.mdx` & `csssyntax-error.mdx`

---

src/content/docs/en/guides/server-side-rendering.mdx

There is a naming error in the code section of the topic Including Promise Directly.
After the fetch request in .then method, response was catched using `resp` variable but then its usage was done with `response` variable.
- Closes # 

Update server-side-rendering.mdx => variable naming bug fix in Including Promise Directly code section

---

src/content/docs/en/guides/fonts.mdx

We later found out the font should yes be extended from Tailwind so that it remains in the Preflight, according to Tailwind docs:
https://tailwindcss.com/docs/font-family#customizing-the-default-font

Revert "changed fontFamily Tailwind configuration"

---

src/content/docs/es/reference/errors/content-schema-contains-slug-error.mdx

Updated `content-schema-contains-slug-error.mdx` based on this commit 772051ff623275c954eee95ed94dab3fa8980cf2

i18n(es): Updated `content-schema-contains-slug-error.mdx`

---

src/content/docs/en/guides/styling.mdx

- replaces link to raw GitHub page to documented Tailwind Integration page
- Closes #3553

docs: update Tailwind link

---

src/content/docs/en/core-concepts/astro-syntax.mdx
src/content/docs/en/guides/backend/google-firebase.mdx
src/content/docs/en/guides/backend/xata.mdx
src/content/docs/en/guides/cms/cloudcannon.mdx
src/content/docs/en/guides/cms/crystallize.mdx
src/content/docs/en/guides/cms/decap-cms.mdx
src/content/docs/en/guides/cms/directus.mdx
src/content/docs/en/guides/cms/frontmatter-cms.mdx
src/content/docs/en/guides/cms/keystonejs.mdx
src/content/docs/en/guides/cms/payload.mdx
src/content/docs/en/guides/cms/prismic.mdx
src/content/docs/en/guides/cms/sanity.mdx
src/content/docs/en/guides/cms/spinal.mdx
src/content/docs/en/guides/content-collections.mdx
src/content/docs/en/guides/integrations-guide/markdoc.mdx
src/content/docs/en/guides/middleware.mdx
src/content/docs/en/guides/migrate-to-astro/from-gitbook.mdx
src/content/docs/en/recipes.mdx
src/content/docs/en/recipes/build-forms-api.mdx
src/content/docs/en/recipes/build-forms.mdx
src/content/docs/en/recipes/bun.mdx
src/content/docs/en/recipes/captcha.mdx
src/content/docs/en/recipes/docker.mdx
src/content/docs/en/recipes/external-links.mdx
src/content/docs/en/recipes/i18n.mdx
src/content/docs/en/recipes/reading-time.mdx
src/content/docs/en/reference/image-service-reference.mdx

This marks 27 more pages `i18nReady: true`!
Notably not transated:
- Content Colletions
- Middleware
- Astro Syntax
- Firebase
- All the Recipes!!
Also marks some stubs for translation, which will be great first time PRs for people! (Maybe figure out a way to highlight and guide people toward `stub: true` when searching for ones to translate?)
Notably NOT yet marked:
- Experimental Assets, as this page will need to change significantly for V3 anyway
- Builder.io, as there's an existing full-guide PR being edited right now.

Release the translators!

---

scripts/generate-integration-pages.ts

Updates our remark pipeline that pulls in integration READMEs from the Astro repo to remove any `` we might want to use there.
Other kinds of HTML comments could still cause errors, but because remark treats HTML comments as just part of a generic HTML node, which we manipulate with a regular expression, I’m hesitant to commit to a blanket “strip comments” plugin. If we can get CI running so these problems get caught in `astro`, I don’t think failing on an unexpected HTML comment is too bad. Then we can evaluate if the comment is needed and if so, update this code again to handle it.
This only applies to the integration page docgen. We build Markdown ourselves for the configuration and error reference, so don’t think we’ll see the same issue.

Strip `prettier-ignore` comments when building integration docs

---

src/content/docs/en/core-concepts/astro-components.mdx

- What does this PR change? Adds a warning to specify that usage of named slots has to be top-level.

Add warning about named slot usage

---

scripts/generate-integration-pages.ts

Removes the Markdoc integration from the set of pages not ready for i18n in the generator script for integration READMEs.
#3578 changed this manually but we need this change to make sure the CI bot doesn’t try to flip it back every day.

Remove Markdoc from `i18nNotReady` in docgen script

---

scripts/docgen.mjs
scripts/error-docgen.mjs

Currently, our documentation generation scripts fetch data from the `witastro/astro#main` to build our integration pages, configuration reference, and error pages.
This PR updates the configuration reference and error reference docgen scripts to use `SOURCE_REPO` and `SOURCE_BRANCH` environment variables if set, in line with how the integration page generator already works.
This will unlock testing in the main Astro repo as we can set those environment variables there and be able to test `astro` PR changes in `astro` rather than waiting for builds to fail in the docs repo.

Support using specific branch when running `docgen` scripts

---

src/content/docs/es/tutorial/2-pages/1.mdx
src/content/docs/es/tutorial/2-pages/2.mdx
src/content/docs/es/tutorial/2-pages/4.mdx

Fix typos in `tutorial`, the use of `usted` has been changed to `tú`.

i18n(es): Fix typos in `tutorial`

---

src/content/docs/en/guides/cms/strapi.mdx
src/content/docs/es/guides/cms/strapi.mdx

This change fixes an error when trying to display the article image following the Strapi guide. Looks like by default media is not sideloaded when fetching a list of records.
[Relevant Strapi docs](https://docs.strapi.io/dev-docs/api/rest#relations-population)
The error in question:

Fix Strapi guide image loading

---

src/content/docs/en/guides/middleware.mdx

A (maybe not-so-brief) description:
- Fixed a few cases where the `title` for code blocks was incorrectly spelled `tilte` instead
- Fixed `MiddlewareResponseHandler` being incorrectly referred to as `MiddlewareRequestHandler` instead
- Fixed a line comment that should've been a block comment and was cutting off the end of the line
- Replaced `html.replace` with `html.replaceAll` in the "redacting sensitive information" example
- Added a missing `title`
- Removed a draft version of the example for chaining middleware
- Fixed inconsistent indentation and formatting
- Added missing semicolons
- Removed extraneous spaces
- A few grammar fixes
I see that there may be conflicts once #3514 gets merged, so I'm ready to fix them.

Fix several issues in the middleware documentation

---

contributor-guides/writing-and-style-guide.md

When the new page was created, half of the content was never included. This recovers that missing content for the writing guide.

recover missing content from writing guide

---

src/content/docs/es/guides/server-side-rendering.mdx
src/content/docs/es/reference/publish-to-npm.mdx

Updated `publish-to-npm.mdx` & `server-side-rendering.mdx`
`publish-to-npm.mdx`
* [`f079d91`](https://github.com/withastro/docs/commit/f079d91844071800d53bd32191bd1fedb3baf5ce)
`server-side-rendering.mdx`
* [`c9e4190`](https://github.com/withastro/docs/commit/c9e4190b93eddcae595c2498e67257161c0de4df)
* [`326dd21`](https://github.com/withastro/docs/commit/326dd2188d6ee9eeff87bd44d67f08453b9bd5fa)

i18n(es): Updated `publish-to-npm.mdx` & `server-side-rendering.mdx`

---

src/content/docs/en/guides/content-collections.mdx

In the migrating from file based routing guide, the "src/pages/tags/[tag].astro" code example is missing the import statements in the frontmatter. If someone were copying and pasting from the given examples, they would probably get confused as to hwy the build is now broken. This PR just adds the missing import statements in.

Add imports to src/pages/tags/[tag].astro example

---

src/content/docs/en/core-concepts/routing.mdx

Since the list of route priority levels immediately precedes this, this language might make it clearer that file-based routes take precedence over redirects at the same route priority level.
A change to docs text for clarity relating to route priority levels and redirects

Clarify that file-based routes supersede redirects per priority level

---

contributor-guides/astro-maintainers-guide-to-docs.md

Added examples to the co-authored-by instructions, using peeps I often want to add anyway. :smile:

Revise co-authored-by instruction in maintainers guide

---

src/content/docs/en/reference/integrations-reference.mdx

- Closes withastro/astro#7642
- Improves docs for the `injectRoute` integration API to clarify how to specify the path to injected entrypoints. The user in the issue above was confused by the current docs and I’ve been repeatedly confused by them too.

Improve `injectRoute` docs

---

src/components/Version.astro

Turns out adding retrying logic didn't really fix this for us, now I changed the `AbortError` to a normal `Error` so that when it fails it will actually retry. And with +5 retries, to be sure.
From what I understood from Eleventy Fetch docs, it won't cache a failed response, so I guess we're fine in this aspect!

Remove abort when `<Version />` fetch fails

---

netlify.toml
src/content/docs/en/guides/view-transitions.mdx
src/content/docs/en/reference/configuration-reference.mdx
src/i18n/en/nav.ts

Renames the main page and tweaks some wording throughout to hit "View Transitions" harder than "Client-side routing" for 2.9.
This also updates the config reference locally, which I'll also do at the source in a separate PR to match.

swap client-side routing with view transitions

---

src/content/docs/ja/tutorial/2-pages/index.mdx
src/content/docs/ja/tutorial/3-components/index.mdx
src/content/docs/ja/tutorial/4-layouts/index.mdx

- Remove `<StackblitzIntro>` (https://github.com/withastro/docs/pull/3770).
- Need to wait for the review result of https://github.com/withastro/docs/pull/3738 before merging.

i18n(ja): Remove <StackblitzIntro> from tutorial

---

src/content/docs/en/guides/view-transitions.mdx

This slightly tweaks and reorganizes the new View Transitions page based on early feedback:
- emphasizes the "happy path" - SPA mode and defaults!
- describes naming transitions before the animations (since that was found to be more useful)
- makes it clearer that you do not need any transition directives, so that maybe people will start without jumping into using them.
- removes the "on a single page" section as that will be less common, and reduces it to a mention
cc @Yan-Thomas for review based on his experience!

Nudge towards View Transitions defaults

---

src/content/docs/en/reference/directives-reference.mdx

- (very) minor content fixes (broken links, typos, etc.)
Currently, the documentation on `class:list` doesn't mention anything about how it handles false values.
This was an issue when it stringified `false`, diverging in behavior from the `clsx` package the documentation references (https://github.com/withastro/astro/issues/3920);
while that since has since been fixed (https://github.com/withastro/astro/pull/3922), there's still no mention of how it handles such values in the documentation. This PR adds a note of how it handles `false` (as well as `null`) in the docs, as observed in the source code at https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/util.ts#L19.

chore(en): describe more accepted `class:list` value kinds

---

src/content/docs/en/guides/cms/wordpress.mdx

_Added a couple of sentences to the section on embeddable content with information on how get smaller sizes of the featured image (the code that is there gets the full size image which is often too large)._

Update WordPress.mdx to describe how to get smaller image sizes

---

src/content/docs/zh-cn/reference/errors/collection-does-not-exist-error.mdx
src/content/docs/zh-cn/reference/errors/content-collection-type-mismatch-error.mdx
src/content/docs/zh-cn/reference/errors/data-collection-entry-parse-error.mdx
src/content/docs/zh-cn/reference/errors/duplicate-content-entry-slug-error.mdx
src/content/docs/zh-cn/reference/errors/mixed-content-data-collection-error.mdx
src/content/docs/zh-cn/reference/errors/unsupported-config-transform-error.mdx

Translate the following sections into Chinese(Simplified):
- [CollectionDoesNotExistError](https://docs.astro.build/en/reference/errors/collection-does-not-exist-error/)
- [MixedContentDataCollectionError](https://docs.astro.build/en/reference/errors/mixed-content-data-collection-error/)
- [ContentCollectionTypeMismatchError](https://docs.astro.build/en/reference/errors/content-collection-type-mismatch-error/)
- [DataCollectionEntryParseError](https://docs.astro.build/en/reference/errors/data-collection-entry-parse-error/)
- [DuplicateContentEntrySlugError](https://docs.astro.build/en/reference/errors/duplicate-content-entry-slug-error/)
- [UnsupportedConfigTransformError](https://docs.astro.build/en/reference/errors/unsupported-config-transfor …

i18n(zh-cn): translate the rest sections of `Reference/Error Reference/Content Colletion Errors` into Chinese(Simplified)

---

src/content/docs/en/guides/markdown-content.mdx

- Closes #3930
- It adds a note `aside` to the `markdown-content` page that warns users that if they are using content collections, they should instead be reading the `content-collections` page if they want to modify their frontmatter programmatically.

add: note to direct users to modifiyng frontmatter with remark

---

src/content/docs/en/guides/deploy/space.mdx

I found that the old Space document links are invalid When I translated Chinese version(#4008). So I fix it to make them all be right.

chore: Fix the missing links for `guides/deploy/space.mdx`

---

src/content/docs/en/core-concepts/astro-components.mdx

Adds example on how to transfer slots from one component to another using a `<slot name="name" slot="name""/>` tag
- Closes: https://github.com/withastro/docs/issues/4034
- https://deploy-preview-4045--astro-docs-2.netlify.app/en/core-concepts/astro-components/#transferring-slots
Let me know if any of this could be worded better, I originally called this pattern "slot drilling" but I think "slot transferring" is a better word for explaining what is happening.

transferring slots

---

src/content/docs/en/guides/environment-variables.mdx

- Closes #3049
This Pull request explains how to access environment variables in SSR mode. Feel free to add sugggestions, maybe we also should have a section on environment variables in the Deno adapter guide? 
Here's a complete list of how we can use environment variables in different adapters:
| Adapter | Usage |
| --- | --- |
| Node | `process.env` |
| Netlify | `process.env` |
| Vercel | `process.env` |
| Cloudflare | `import.meta.env` |
| Deno | `Deno.env.get` |

Explain how to get environment variables in SSR mode

---

src/content/docs/en/guides/cms/caisy.mdx
src/content/docs/en/guides/cms/cloudcannon.mdx
src/content/docs/en/guides/cms/crystallize.mdx
src/content/docs/en/guides/cms/decap-cms.mdx
src/content/docs/en/guides/cms/directus.mdx
src/content/docs/en/guides/cms/keystonejs.mdx
src/content/docs/en/guides/cms/microcms.mdx
src/content/docs/en/guides/cms/payload.mdx
src/content/docs/en/guides/cms/prismic.mdx
src/content/docs/en/guides/cms/sanity.mdx
src/content/docs/en/guides/cms/spinal.mdx

- Marks short CMS stubs as not ready for translation.
- I used [a GitHub search](https://github.com/search?q=repo%3Awithastro%2Fdocs+path%3Aen%2F**%2F*.mdx+%22i18nReady%3A+true%22+%22stub%3A+true%22&type=code&ref=advsearch) to find pages with `stub: true` and `i18nReady: true`
- There are a few migration guide “stubs” marked as translation-ready, but I left these as they’re bigger pages with more content that could be actually useful to translate.

Mark CMS stubs as `i18nReady: false`

---

src/content/docs/en/recipes.mdx

Removes [Add authentication with Prisma and Planetscale](https://www.thomasledoux.be/blog/authentication-astro-prisma-planetscale) from the community resources section. It doesn't hash passwords which is a must when implementing password based authentication.

Remove authentication recipe

---

src/util/isSubPage.ts

"Add a backend service" subpages were not being marked, so no item would be highlighted in the sidebar when accessing a page like `/backend/google-firebase/`. This PR fixes this behavior.
**Before**
**After**

Add `backend/` pages to subpage handling

---

src/content/docs/es/guides/fonts.mdx

- What does this PR change? Fixed a typographical error in the font usage guide in the Spanish documentation.
- Did you change something visual? No, it's a text correction.
- Corrected a grammatical error in the font usage guide of the Spanish documentation by removing redundant phrasing. The phrase "para una fuente local para una fuente local" was revised to "para una fuente local" to improve clarity and readability.
- Modified the content in the section related to using local font files.

Fix typo in font usage guide for Spanish documentation

---

scripts/lib/translation-status/builder.ts

This PR adds a rudimentary version of the custom tracker syntax to help with the 3.0 PRs changing lots of translations to fix links (LOOKING AT YOU 3.0 IMAGE GUIDE).
This allows you to add a `@tracker-major:(list of file paths separated by ;)` to a final squashed commit description (the one you have to confirm before you merge) that makes all changes be considered minor except the ones you have explicitly marked as major.
🚨 **THE FILE PATH HAS TO INCLUDE EVERYTHING (SEE BELOW)** 🚨 
Example:
**PR updates the pages (br/1.mdx, br/2.mdx), but also updates the link to another page that isn't fully updated yet (br/3.mdx).**
Using: `@tracker-major:./src/content/docs/br/1.mdx;./src/content/docs/br/2.mdx`, `br/3.mdx` continues to be marked as outdated.
More info in …

Add basic custom Translation Tracker syntax

---

src/content/docs/en/reference/image-service-reference.mdx

After the recent update to allow remote images, the Image Service reference page ended up being outdated. Notably, we now pass the entire `image` config to hooks instead of just the service config, so that they can access `domains` and `remotePatterns`. Some misc fixes were also included

fix(assets): Fix outdated image service page

---

src/content/docs/en/guides/content-collections.mdx
src/content/docs/en/guides/markdown-content.mdx
src/content/docs/en/reference/cli-reference.mdx

- Close https://github.com/withastro/docs/issues/4318
- Remove references of markdown and MDX draft features.
- Add a new small paragraph about content collections draft filtering where it's available in dev, but not in prod.

Remove markdown draft reference

---

src/content/docs/zh-cn/guides/images.mdx

i18n(zh-cn): Update zh from upstream

---

src/content/docs/en/reference/adapter-reference.mdx

- New content
This PR adds more information to the `functionPerRoute` option, in regards to the serverless environments.

chore: supplement `functionPerRoute` docs

---

src/content/docs/en/guides/client-side-scripts.mdx

Fix type issue number cannot be assigned to string.
- Fix minor type issue.

Fix number cannot be assigned to string issue in script example

---

package.json
pnpm-lock.yaml
scripts/lib/translation-status/builder.ts

Now the directive also accepts glob patterns! Which will come in handy to deal with the 3.0 docs.
See the comment added to code plus the base PR for this feature for me instructions on how to test: https://github.com/withastro/docs/pull/4267
Note that minimatch glob syntax is a bit different from some other libraries, so check their docs first to be sure!

Add glob matching to `@tracker-major` directive

---

src/content/docs/en/guides/view-transitions.mdx

Adds a section to the View Transitions v3 upgrade guide about updating your import source from `astro:components` => `astro:transitions`. This one was late in the game, so we missed it!

Add ViewTransition component import to v3 upgrade guide

---

src/content/docs/en/core-concepts/endpoints.mdx

- Minor content fix (typo)
- Closes # 
- This PR simply fixed the typo in the phrase "Here, it returns an Response object...", I changed an to a.
- Yes i did.

Fix typo in endpoints.mdx

---

src/content/docs/en/guides/upgrade-to/v3.mdx

- Update the 3.0 Blog post link in v3.mdx

Update the 3.0 Blog post link in v3.mdx

---

src/content/docs/zh-cn/guides/images.mdx

Update `guides/images.mdx` since #4462

i18n(zh-cn): Update `guides/images.mdx`

---

src/content/docs/en/guides/imports.mdx

Without this change, I get the following error:
```
Type 'ImageMetadata' is not assignable to type 'string'.ts(2322)
astro-jsx.d.ts(701, 3): The expected type comes from property 'src' which is declared here on type 'ImgHTMLAttributes'
```
It is also how it is documented in https://docs.astro.build/en/guides/images/#images-in-astro-files

guides/import: Add `.src` to `src={imgReference.src} `

---

src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx

* Changed the `Add integrations and dependencies` section to use Fragments like the previous section. 
* This should also automatically change all tabs/fragments to the same package manager

Use Fragments

---

.github/actions/install/action.yml

Revert Node version to 18, since 20 is very buggy

fix: revert Node to 18 for CI

---

src/components/Header/ThemeToggleButton.tsx

**Note:** This PR is a temporary fix until the issue with `setTheme` is fixed. 
**Current Status:** 
- On first load or when refreshing the browser, `setTheme` isn't setting the `theme` value.
- This leads to `theme` being 'undefined', causing the `.theme-dark` class to be added. 
- This PR doesn't solve the `setTheme` problem directly. Instead, it checks to ensure the theme is set to either "dark" or "light". 
- ![CleanShot 2023-09-08 at 08 50 46@2x](https://github.com/withastro/docs/assets/20273871/58b01e23-d0ab-4091-8cc9-85cbec40fae1) 
- ![CleanShot 2023-09-08 at 08 51 29@2x](https://github.com/withastro/docs/assets/20273871/a9fd3625-68e6-4033-af01-ed5e0165c2f6)
- Something else:
- Minor tweak to prevent the flash of the dark theme. 
- Added a check to ensure the theme value is 'light' …

Fix: Flash of Dark Theme

---

src/content/docs/en/core-concepts/astro-pages.mdx

Adds an example when describing use an `<a>` tag for page links:  `<a href="/authors/sonali>` to demonstrate that the `href` value should be a URL and not a file path.

[astro-pages.mdx] add example for internal page links

---

src/content/docs/en/guides/cms/storyblok.mdx

For retrieving stories, instead of `cdn/stories/blog`, you need to call `cdn/stories`
Fix a typo for calling api

fix Api call for retrieving stories

---

.github/labeler.yml

- Fixes a labeler issue that prevented any i18n PRs from being labeled.
- Bug was accidentally introduced in https://github.com/withastro/docs/pull/4609 due to a misunderstanding of how the "any" logic works. I checked the action's source code to debug the issue and found this solution.

Fix labeler not labeling i18n PRs properly

---

src/content/docs/zh-cn/core-concepts/astro-pages.mdx

update `core-concepts/astro-pages.mdx` since #4610

i18n(zh-cn): update `core-concepts/astro-pages.mdx`

---

src/content/docs/es/core-concepts/astro-components.mdx

Instead of highlighting the desired code, which is `<slot name="head"/>` and `<slot />`, the `</head>` and `</body>` code sections are being highlighted incorrectly. Because of simple spacing.

i18n(es): Fixed highlighted part

---

src/content/docs/en/tutorial/5-astro-api/4.mdx

After following the [rss-feed blog tutorial](https://docs.astro.build/en/tutorial/5-astro-api/4/#install-astros-rss-package) I came across an issue.
**Issue:**
When running `npm run build` then `npm run preview`, rss.xml file does not seem to be created, as /rss.xml on local returns a 404.
**Potential solution:**
This issue was solved after lowercasing GET()
from:
`export async function GET() {`
to:
`export async function get() {`
by finding and applying [koba-masa's suggestion on Astro discord channel](https://discord.com/channels/830184174198718474/1147825423594565752/1147825423594565752)

fix: generate rss.xml file by lowercasing get() function

---

src/content/docs/es/recipes/bun.mdx
src/content/docs/es/reference/cli-reference.mdx

**What kind of changes does this PR include?**
Fix typos
**Description**
Fix typos in the following pages:
- src/content/docs/es/recipes/bun.mdx
- src/content/docs/es/reference/cli-reference.mdx

i18n(es): Fix typos in some pages

---

src/content/docs/en/tutorial/1-setup/index.mdx
src/content/docs/en/tutorial/2-pages/1.mdx
src/content/docs/en/tutorial/2-pages/2.mdx
src/content/docs/en/tutorial/2-pages/3.mdx
src/content/docs/en/tutorial/2-pages/4.mdx
src/content/docs/en/tutorial/2-pages/5.mdx
src/content/docs/en/tutorial/2-pages/index.mdx
src/content/docs/en/tutorial/3-components/1.mdx
src/content/docs/en/tutorial/3-components/2.mdx
src/content/docs/en/tutorial/3-components/3.mdx
src/content/docs/en/tutorial/3-components/index.mdx
src/content/docs/en/tutorial/4-layouts/1.mdx
src/content/docs/en/tutorial/4-layouts/2.mdx
src/content/docs/en/tutorial/4-layouts/3.mdx
src/content/docs/en/tutorial/4-layouts/index.mdx
src/content/docs/en/tutorial/5-astro-api/1.mdx
src/content/docs/en/tutorial/5-astro-api/3.mdx
src/content/docs/en/tutorial/5-astro-api/index.mdx
src/content/docs/en/tutorial/6-islands/1.mdx
src/content/docs/en/tutorial/6-islands/index.mdx

Noticed that some "we/let's" still made it past our editing process for the tutorial, and this isn't the voice we use!
Mostly converts "we" to "you". "Let's" is trickier, but "you will" or "it's time to" usually works!

[tutorial] consistent voice

---

src/content/docs/es/reference/error-reference.mdx
src/content/docs/es/reference/errors/expected-image.mdx
src/content/docs/es/reference/errors/local-image-used-wrongly.mdx

Updating `error-reference.mdx`, `local-image-used-wrongly.mdx` and `expected-image.mdx` pages translation from this commit: https://github.com/withastro/docs/commit/106bdf93ebc68c885850e043a2310779011d6b1e.

I18n(es): Updating some pages translation

---

package.json
scripts/error-docgen.mjs
src/content/docs/en/reference/errors/expected-image.mdx
src/content/docs/en/reference/errors/unsupported-config-transform-error.mdx

With the new image component, we're adding more errors that have angle brackets in them (ex: `<Image />`). MDX doesn't like this, so we escaped them previously and it'd all work nicely, but then it seems like something changed and now it doesn't work. Not sure. This fixes everything, though.
This PR also updates the `packageManager` field, the old version of `pnpm` used didn't support Node 20.

fix(errors): Fix error formatting not properly handling angle brackets

---

src/content/docs/en/guides/testing.mdx

The older link reference returns a 404 if JavaScript is disabled (as was in my case), or redirects you to a resource which _still_ does not directly mention how to use a development server with Playwright. I found an updated—and IMO, better—resource for the same.
N/A
__PS__: Since this is simply a change in the URL ref, LMK if it’s OK for me to update it in the other languages too, in which case I’ll also update the PR title. I didn’t want to cause any unnecessary trouble for the translators.
💖

[en-only] Fix broken URL reference in testing docs

---

src/content/docs/en/guides/images.mdx

- Adds an extra step for updating the `env.d.ts` file or the `tsconfig.json` file, which had special `@astrojs/image` types in them some of the time. You can see a reference to them in the old [integration readme](https://github.com/withastro/astro/blob/670ef109dbbc07f53c7758bad6098186719fdeb2/packages/integrations/image/README.md#update-envdts).
I was just upgrading an old project to Astro 3 and ran into this missing step, so I figured it should add it (hopefully this PR doesn't rot for months this time... 😅).
Also, I'm not entirely sure how the code block diff highlighting works, so please feel free to fix it if I did it wrong.

Add `env.d.ts` changes to  V3 `@astrojs/image` migration 

---

src/content/docs/en/guides/images.mdx
src/content/docs/es/guides/images.mdx
src/content/docs/ja/guides/images.mdx
src/content/docs/zh-cn/guides/images.mdx

Fixes the typo in section https://docs.astro.build/de/guides/images/#remove-astrojsimage for langauges:
- English
- Spanish
- Chinese Simplified
- Japanese
I checked all languages and these are my findings:
| Language | Code | Status |
| --- | --- | --- |
English | en | original typo
Deutsch | de | no translation, inherited from EN
Portuguese | pt-br | fixed by the pt-br contributor
Spanish | es | translated but inherited the typo
Chinese Simplified | zh-cn | translated but inherited the typo
Taiwanese Mandarin | zh-tw  | no translation, inherited from EN
French | fr  | no translation, inherited from EN
Hindi | hi  | no translation, inherited from EN
Arabic | ar  | no translation, inherited from EN
Japanese | jp | translated but inherited …

Fix typo from drc to src

---

src/content/docs/en/tutorial/6-islands/3.mdx

This adds two simple buttons to the end of tutorial. No external styles or anything, just imports the standard button component and passing in the share links with the following text URL encoded
```text
Just finished learning how to build my first Astro blog! 
Check it out at https://docs.astro.build/!
```
Here's a screenshot of the website
I took the creative liberty of adding the text to invite the user to share, please do tell me if you want me to change it, but I think it's fun 😄 
>Congratulations on completing the Astro blog tutorial! Share your achievement with the world and let everyone know you’re an 🧑‍🚀Astronaut now!
- Closes Issue #4044

Add share links at the end of the tutorial

---

src/content/docs/en/guides/backend/google-firebase.mdx

- In most places the file and endpoint was called `signin.ts`. Changed the two places that inconsistency referenced `login` and `login.ts`.
- After review by TheOtterlord, changed `logout` to `signout` in two places as well

typo: incorrect filename in google-firebase.mdx

---

src/content/docs/en/guides/upgrade-to/v3.mdx

I updated the content collection config path from `astro.config.mjs` to `src/content/config.ts` for the code example for this [page](https://deploy-preview-4898--astro-docs-2.netlify.app/en/guides/upgrade-to/v3/#what-should-i-do-6)
- Closes #4875

Fix Incorrect content collection config path in upgrade guide

---

src/content/docs/en/guides/typescript.mdx

This PR removes the mention of `tsc --noEmit` in both the `package.json` example and note for astro check docs in the Type Checking section for astro 3. 
[Link to page with the fix](https://deploy-preview-4899--astro-docs-2.netlify.app/en/guides/typescript/#type-checking)
- Closes #4789

Updating outdated information for astro check documentation for Astro 3 

---

src/content/docs/en/guides/view-transitions.mdx

Clarified the relationship of the new router API with the browser history API.
Triggered by [user adding own back function](https://github.com/withastro/roadmap/discussions/653#discussioncomment-7149625)

Clarify the relationship with the browser history API

---

src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx
src/content/docs/zh-cn/tutorial/6-islands/1.mdx

i18n(zh-cn): update tutorial

---

contributor-guides/astro-maintainers-guide-to-docs.md

Adds a link to https://co-author-generator.netlify.app/ in addition to the existing manual instructions for how to add co-author credit when performing the Squash and Merge action.
Built by @kevinzunigacuellar :raised_hands: :rocket:

[maintainers guide] add link to Kevin's co-author generator

---

src/content/docs/en/core-concepts/astro-pages.mdx

- Added missing word `directory`. Alternatively, the word `the` could be removed.

typo: missing word in astro-pages.mdx en-only

---

.github/workflows/welcome-bot.yml

- This PR adds a GitHub action, which comments on PRs from first-time contributors to welcome them.
- Comments with a message based on our current “Next Steps” section in the PR template, which we’re removing in #4946 
- Tested in a test repo during Talking & Doc’ing! Comments look something like this:

Add first-time contributor action

---

src/content/docs/fr/install/manual.mdx

Update `install/manual` in French language. Missed one line : 
```diff
+ :::note[Important]
+ Astro doit être installé localement, pas globalement. Assurez-vous que vous n'exécutez pas `npm install -g astro` `pnpm add -g astro` ou `yarn add global astro`.
+ :::
```
I am participating in the Hacktoberfest!
- [i18n(fr): Update install/manual in French language](https://github.com/withastro/docs/commit/95aac997e625a4105e8f68266c9085359445cbe7)
hmhm, nope!

i18n(fr): Update `install/manual` in French language

---

src/content/docs/zh-cn/guides/deploy/cloudflare.mdx
src/content/docs/zh-cn/guides/view-transitions.mdx

Updated translation based on source texts at [9049c78](https://github.com/withastro/docs/tree/9049c78bf535b132d706a8b534f040c27958988d).
| File | Source | Source Diff | Other Links |
| --- | --- | --- | --- |
| `guides/deploy/cloudflare.mdx` | [source@`9049c78`](https://github.com/withastro/docs/blob/9049c78bf535b132d706a8b534f040c27958988d/src/content/docs/en/guides/deploy/cloudflare.mdx) | [`57d124a..9049c78`](https://i18n-tools.genteure.com/diff#withastro/docs/57d124a0451093fc8382f024f556dc9821783b7b..9049c78bf535b132d706a8b534f040c27958988d/src/content/docs/en/guides/deploy/cloudflare.mdx) | [blame@`9049c78`](https://github.com/withastro/docs/blame/9049c78bf535b132d706a8b534f040c27958988d/src/content/docs/en/guides/deploy/cloudflare.mdx) <br> …

i18n(zh-CN): Update `view-transitions.mdx`, `cloudflare.mdx`

---

src/content/docs/en/reference/cli-reference.mdx

- This PR updates the CLI reference to mention the new `--outDir` CLI flag added in https://github.com/withastro/astro/pull/8808
- While there, I also removed the flags subsection under `astro build`, which was left in a slightly odd shape when the `--drafts` flag was removed. It now links to common flags with the same style as the docs for `astro preview` do.

Document `--outDir` CLI flag

---

plugins/rehype-autolink-config.ts

- Fixes a typo in the spelling of the `xmlns` attribute of the generated svg element. The attribute was spelled `xlmns`. Fixed to the proper `xmlns`.

Fix(rehype-autolink-config.ts): Typo in the xmlns svg element attribute

---

src/content/docs/en/guides/markdown-content.mdx

I found valuable information on how Astro generates anchor IDs in the German translation for [Heading IDs](https://docs.astro.build/de/guides/markdown-content/#%C3%BCberschriften-ids). However, this part was missing in the English version, which is why I am submitting this PR to address it.
- Suggested label: `hacktoberfest-accepted`

use standard example.com domain for code sample

---

src/content/docs/en/reference/api-reference.mdx

Fixing a minor inconsistency in reference docs, so that `getEntries()` returns `Array<CollectionEntry>` - not a single entry.

Reference:  `getEntries()` would return `Array<CollectionEntry>` - not a single entry

---

src/content/docs/zh-cn/recipes/reading-time.mdx

Mostly rewording and restructuring sentences.
Source: https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/reading-time.mdx
While doing the translation I found the npm package `reading-time` does not seems to output a `text` property, maybe this doc is outdated? I was checking if their `text` output is translated or not since it was translated in this page.

i18n(zh-CN): improve translation for `reading-time.mdx`

---

src/i18n/zh-cn/nav.ts
src/i18n/zh-cn/ui.ts

Improve translation for website UI and navigation.
Navigation (`nav.ts`): added spaces between English alphabet and Chinese characters.
Website UI (`ui.ts`):
- Changed translation for `a11y.sectionLink` to `段落标题`, this string is used in a "hidden" `<span is:raw class="sr-only">` for screen readers to read, this new translation sounds much more natural after being concatenated with the section title. 
- Removed the colon in `leftSidebar.sponsoredBy`. The English text does not contain a colon.
- Replaced "页", "篇" in `stub.*` with "指南" as the translation for "guide".
- Replaced "博客" with "文章" as the emphasis is on "post" rather than "blog".
- Minor wording and formatting changes.

i18n(zh-CN): improve translation for `ui.ts`, `nav.ts`

---

src/content/docs/es/guides/images.mdx

Updated `images` based on these commits:
- b91953c694b46b1488b0d7685dfe3be17163165d
- 9c0810ef47ef433b5a16eae24d0fc50fd9db9261
**Note:** Added missing documentations regarding <Picture />

i18n(es): Update `images`

---

scripts/generate-integration-pages.ts

The adapters repo is introducing a private package for testing that does not need to be processed by docs.
Currently, smoke tests are failing because `generate-integration-pages.ts` attempts to create a markdown file for the internal test-utils package.
None

fix(integration pages ci): ignore private packages

---

src/content/docs/en/tutorials/add-content-collections.mdx

Added missing backticks at the end of a code block and fixed identation.
- Suggested label: tutorial

fix: missing backticks in code block and indentation in `add-content-collection`

---

src/content/docs/es/reference/errors/unsupported-image-conversion.mdx

Translated `unsupported-image-conversion` error to spanish.

i18n(es): Translate `unsupported-image-conversion`

---

src/content/docs/es/guides/integrations-guide/cloudflare.mdx
src/content/docs/es/guides/integrations-guide/netlify.mdx
src/content/docs/es/guides/integrations-guide/sitemap.mdx

Updated `cloudflare`, `sitemap` & `/integrations-guide/netlify` based on these commits:
- 4d2d8a1a6dfef7f2acdf28737f656e384ca18c79
- b384847cdbaf16b57f2e67f95a01cef2c660b256

i18n(es): Update `cloudflare`, `sitemap` & `/integrations-guide/netlify`

---

src/content/docs/es/tutorials/add-content-collections.mdx

- Add spanish translate file for `Tutorials -> Add content collections`.
- Suggested label: i18n, i18n-es
> Optionaly, would be great if this PR may participate for the `hacktoberfest`.

i18n(es): add-content-collections

---

src/content/docs/en/guides/images.mdx

Updates the Default Image Service section in our Images guide:
- Adds h3s for discoverability now that there are two sub-sections: Squoosh and noop
- The only place we had documented configuring a noop service for an environment/adapter that did not support it was in the upgrade from v2 section, so this moves it to docs proper
Should be checked and vetted to make sure advice is still appropriate (e.g. used to refer to Vercel and Netlify edge environments; is the pnpm warning still appropriate?).
Direct preview link: https://deploy-preview-5189--astro-docs-2.netlify.app/en/guides/images/#default-image-service

[images] updates Default Image Service section

---

src/content/docs/ko/guides/typescript.mdx

Corrects a link pointing to an English heading instead of a translated one.
If I'm right, all the link checks should pass.

i18n(ko) typescript.mdx link heading fix

---

src/content/docs/en/guides/cms/directus.mdx
src/content/docs/es/guides/cms/directus.mdx
src/content/docs/zh-cn/guides/cms/directus.mdx

The link for the guide doesn't exist anymore on the Directus website. The example still does.

[i18nIgnore] chore: remove non-existent link

---

src/content/docs/zh-cn/guides/deploy.mdx

fix some typos in `guides/deploy.mdx`
None

i18n(zh-cn): fix some typos in `guides/deploy.mdx`

---

src/content/docs/en/guides/upgrade-to/v2.mdx

The link for this very old page (upgrade from v1 to v2) is going to eventually cause problems. This removes the specific heading that will change and simply directs to the page itself.

upgrade to v2 - future proof link
