withastro/docs

src/pages/ja/core-concepts/layouts.mdx
- Update layouts.mdx.
- Correspondes to https://github.com/withastro/docs/pull/2428.
=> i18n(ja): Update layouts.mdx

src/pages/ja/guides/configuring-astro.mdx
- Update configuring-astro.mdx.
- Correspondes to https://github.com/withastro/docs/pull/2500.
=> i18n(ja): Update configuring-astro.mdx

src/pages/en/guides/server-side-rendering.mdx
Follow up to #2539 . Now I know what those little `{2}` flags mean! :)
=> Fix line highlights in prerendering examples

src/pages/en/guides/rss.mdx
Change the highlighted line 14 to line 15.
Before (The highlighted line is the commented line) :
After :
=> Fix: Change the highlighted line 14 to line 15

src/pages/en/tutorial/2-pages/3.mdx
- This pull request contains minor grammar fixes to improve the clarity and readability of the text. The changes are purely cosmetic and do not affect the functionality of the code.
- Clarified phrasing and sentence structure for english only
I hope these changes will make the text easier to understand for all users. Thank you for considering this pull request.
=> fix the answer in tutorial question with minor addition (en-only) [i18nIgnore]

src/pages/es/reference/api-reference.mdx
Update of `api.reference.mdx` based on this commit 34537534e3ef9b1920b7aadfd0723e7ac3dc2cc1
=> i18n(es): Update of `api.reference.mdx`.

src/pages/en/reference/directives-reference.mdx
- Closes #2480 
- Clarifies under Client Directives that they must be placed on an imported component.
=> Client directive disclaimer: component must be imported

src/pages/fr/core-concepts/endpoints.mdx, src/pages/fr/guides/client-side-scripts.mdx
Translation of `client-side-scripts.mdx` to french.
=> i18n(fr): Translation of `client-side-scripts.mdx`

src/pages/es/guides/troubleshooting.mdx
Changed for improved readability and updated with translation of new content.
Changed text for improved readability and updated with translation of new content.
=> i18n(es): Update troubleshooting.mdx

src/pages/zh-cn/guides/rss.mdx
https://github.com/withastro/docs/pull/2300 related
=> i18n(zh-cn): [rss] Add to package on GitHub

src/pages/zh-cn/concepts/mpa-vs-spa.mdx
- No space after Chinese period
- Fix typo
- Fix word error
- Fix proper name translation
=> i18n(zh-cn): update `mpa-vs-spa`

src/pages/en/editor-setup.mdx
- Add PackageManagerTabs for prettier
=> Add PackageManagerTabs for prettier

src/pages/en/reference/api-reference.mdx
- Minor content updates
- Closes #2558
- Adds `Astro.redirect()` to the API reference page
- Change the link under context.redirect() from the SSR guide to this new API reference section
=> Redirect api reference

src/pages/en/reference/directives-reference.mdx
Closes: https://github.com/withastro/docs/issues/2422
Added a JSON-LD script example `set:html` reference
=> Add JSON-LD example to set:html reference

src/pages/en/guides/server-side-rendering.mdx
=> Correct `Response` -> "endpoint context" in SSR endpoint introduction

src/pages/en/guides/testing.mdx
- Adds an import statement in the given test example, since this was missing
=> add import to testing example

src/pages/en/tutorial/6-islands/2.mdx
- Closes #2146 using the suggested changes
=> Tutorial: Change theme toggle from div to button

src/pages/en/guides/markdown-content.mdx
Changes old `export default {}` to newer `defineConfig({})`
=> Update Astro Config examples to `defineConfig`

src/pages/en/guides/rss.mdx
Add missing imports from `astro:content`
=> Add missing imports from `astro:content`

src/pages/en/install/auto.mdx
- Updates the create astro completion message to the latest version.
- The latest message can be found in https://github.com/withastro/astro/blob/79f49acbe13673bfc27e794bcfae518f38c4a4fe/packages/create-astro/src/messages.ts#L118
- Removes the apostrophe around "Next steps" since create astro does not currently output "Next steps".
- The previous message can be found in https://github.com/withastro/astro/blob/a4f24266c0ca262df7c4e040a6fbb3559747b43a/packages/create-astro/src/index.ts#L363
For reference, here is a screenshot of the latest create astro run on my machine:
=> Update liftoff message in auto.mdx

src/pages/zh-cn/reference/publish-to-npm.mdx
**What kind of changes does this PR include?**
Update publish-to-npm.mdx FileTree
**Description**
Just doc
=> i18n(zh-cn): Update publish-to-npm.mdx

src/components/DeployGuidesNav.astro, src/pages/en/guides/deploy/google-cloud.mdx
- Added SSR to Google Cloud deploy category
- Rewrote the Google Cloud Run deploy guides and included `Dockerfile` samples. 
- *Newer Ideas always welcome as well*
I'm also the original writer of the previous version of this guide ([see this PR](<https://github.com/withastro/astro/pull/1533>)), but it was kind of getting outdated
=> GCP Deploy guide update

src/pages/en/tutorial/1-setup/2.mdx
- Addresses this Feedback Fish
> create-astro asked me if I was going to use TypeScript and the answer "Relaxed" wasn't there.
- Changes "Empty Project" to "Empty" to reflect the new wording
=> Tutorial: Update installation instructions to match new create-astro

src/pages/zh-cn/reference/publish-to-npm.mdx
- Fix the md hierarchy
- https://github.com/withastro/docs/pull/2648
=> i18n(zh-cn): update publish to npm guide 

src/pages/en/guides/cms/storyblok.mdx
Fixes a typo reported via Feedback Fish.
=> Fix Storyblok CMS guide typo

src/pages/en/tutorial/2-pages/2.mdx
Corrects a filepath in the tutorial reported via Feedback Fish.
=> Fix filepath typo in tutorial

src/pages/zh-cn/core-concepts/project-structure.mdx
- Update project-structure.mdx
- Add `tsconfig.json`
- Add FileTree
=> i18n(zh-cn): Update project-structure.mdx

netlify.toml
- Three small redirects to catch a few 404s we saw recently
=> Add redirects based on 404 audit

src/content/docs/en/tutorial/6-islands/3.mdx
- Links to the migration guide from the end of the tutorial
=> Tutorial: Add link to content collections migration guide

src/content/docs/en/guides/cms/storyblok.mdx
- Add a new community article to the Storyblok guide
- Remove period at the end of bullet
=> Add community article to Storyblok guide

src/content/docs/es/guides/deploy/sst.mdx
Update of `sst.mdx` based on this commit 774297c8ee7f34cbdb60bf7e3613e17d1ff5be1c
=> i18n(es): Update of `sst.mdx`

src/content/docs/en/integrations/integrations.mdx
Since last week, the elian.codes website uses other integrations, I've updated them
Updates the elian.codes production site integrations
=> Update ElianCodes integrations

scripts/github-translation-status.mjs
Add Korean translations to the Status Overview Issue.
=> Track Korean Translations in Status Overview Issue

src/content/docs/en/guides/cms/sanity.mdx
=> Add official Sanity guide

src/components/tutorial/FeedbackButton.astro, src/i18n/en/ui.ts, src/i18n/zh-cn/ui.ts
- Add i18n key [feedback.success] 
- Add zh-cn translations
=> Add missing i18n key to Feedback Fish and add zh-cn translations

src/i18n/ja/nav.ts
- Update nav.ts based on https://github.com/withastro/docs/tree/reorg-incl-recipes.
=> i18n(ja): Update nav.ts based on reorg-incl-recipes

src/content/docs/en/guides/markdown-content.mdx
Before | After
-------|------
- Closes #2713
=> [i18nIgnore] Fix broken syntax highlight in code block

src/content/docs/en/guides/upgrade-to/v2.mdx
This PR marks the "Upgrade to v2" as ready for translators to jump in! ✨
=> Mark `upgrade-to/v2` as ready for translation

src/content/docs/en/guides/typescript.mdx
=> Extending `window` and `globalThis`

TRANSLATING.md
=> Link to new translation status overview in TRANSLATION.md

src/i18n/de/nav.ts
- Fixed the route name for a renamed translated guide page.
=> i18n(de): navigation route name

src/content/docs/zh-cn/guides/testing.mdx, src/i18n/ar/ui.ts, src/i18n/en/ui.ts, src/i18n/es/ui.ts, src/i18n/ja/ui.ts, src/i18n/pl/ui.ts, src/i18n/pt-br/ui.ts
- fix typo and grammar
- Related: https://github.com/withastro/docs/pull/2720
=> [i18nIgnore]Fix typo and grammar

src/content/docs/en/guides/testing.mdx
=> docs: add testing guide for cypress

package.json, pnpm-lock.yaml
- The `@astrojs/markdoc` PR (https://github.com/withastro/astro/pull/6209) includes changes to the MDX internals. Since docs is on an older version of MDX, our smoke tests aren't able to resolve versions correctly. This should fix us!
=> chore: bump to MDX 0.17

src/content/docs/en/guides/rss.mdx
- added fix for the sentence from `your of` to `of your`
=> Fix sentence in rss.mdx

src/content/docs/en/guides/deploy/google-cloud.mdx
Updates title in tip and update style/typo's in `Dockerfile`'s
=> docs: deploy: GCP typo fixes

package.json, pnpm-lock.yaml
Upgrade astro to 2.0.17 to improve build speed (I hope this works)
EDIT: Looks like this bring down the build times from 355s to 343s only (on Netlify) 😦 Maybe better than nothing
=> Upgrade astro to 2.0.17

src/content/docs/pt-br/guides/typescript.mdx
- This PR corrects the translation of some words into Portuguese.
=> typo: update typescript docs.

src/content/docs/zh-cn/reference/integrations-reference.mdx
- Fix `astro:build:start` params
=> i18n(zh-cn): Update integrations-reference.mdx

src/content/docs/zh-cn/integrations/integrations.mdx
- update `integrations/integrations.mdx`
=> i18n(zh-cn): update `integrations/integrations.mdx`

src/content/docs/en/recipes/build-forms-api.mdx, src/content/docs/en/recipes/build-forms.mdx
To be merged after #2550
These are the two forms recipes from #2550, in their own PR. The first ex
=> Add a recipe for HTML forms and a recipe for JS forms

src/content/docs/en/guides/cms/wordpress.mdx
Just a simple typo fix. From "dinosuars" to "dinosaurs" on the URL for the example blog.
=> Fix dinosaur API URL typo

src/content/docs/en/guides/assets.mdx
Content Layout Shift -> Cumulative Layout Shift
=> Cumulative Layout Shift

src/content/docs/en/guides/cms/spinal.mdx, src/content/docs/en/guides/cms/wordpress.mdx, src/content/docs/en/recipes.mdx
- Adds three recipes to start the community recipe section.
- The Swup recipe is old, but has been cited recently and often in our Discord as helpful.
=> Add three recipes to start the community recipe section

src/content/docs/en/guides/assets.mdx, src/content/docs/en/reference/image-service-reference.mdx
- Corrects the code sample in image-service-reference
- Adds a "Using sharp" section to the experimental assets guide that explains how to install and use sharp
=> Experimental assets: document how to use Sharp

RECIPES.md, src/content/docs/en/recipes.mdx
- Adds a RECIPES.md file to explain how to contribute to our Recipes section.
=> Add RECIPES.md

src/content/docs/en/guides/assets.mdx
- Document how `src/env.d.ts` will get updated when enabling the assets feature (and how to do it manually if you want)
=> Note that env.d.ts needs updating for assets support

src/content/docs/en/guides/upgrade-to/v2.mdx
fix typo: 'Astro 2.0' to 'Astro v2.0'
=> fix typo: 'Astro 2.0' to 'Astro v2.0'

src/content/docs/en/recipes.mdx
=> Add two community recipes

src/content/docs/en/reference/integrations-reference.mdx, src/content/docs/es/reference/integrations-reference.mdx, src/content/docs/pt-br/reference/integrations-reference.mdx, src/content/docs/zh-cn/reference/integrations-reference.mdx
- Closes #2861
Fixes a link in the Integration API reference for the `RouteData` type.
=> [i18nIgnore] Fix link in integration API reference

src/content/docs/en/guides/cms/tina-cms.mdx
Removing erroneous 'npm', 'pnpm', and 'yarn' word from the 'dev' script in package.json
=> Correcting script command in package.json

src/content/docs/en/concepts/why-astro.mdx
=> fix typo: missing apostrophe

src/content/docs/en/guides/migrate-to-astro/from-docusaurus.mdx, src/content/docs/en/guides/migrate-to-astro/from-jekyll.mdx, src/content/docs/en/guides/migrate-to-astro/from-vuepress.mdx
- What does this PR change? Fixes links to the themes categories for migration pages.
=> Fix links to theme categories

src/content/docs/en/guides/cms/wordpress.mdx
As above.
Fixed `set:html` with incorrect JSX syntax.
=> Fixed incorrect code example

src/content/docs/en/guides/styling.mdx
Discord thread link: https://discordapp.com/channels/830184174198718474/1075913546883407972
- Replaces #2774
- Adds an inline styles section that shows an example of style objects
=> Add inline styles section to Styling

src/content/docs/en/guides/assets.mdx
=> Update assets.mdx (en-only)

src/content/docs/en/guides/environment-variables.mdx
- An extra "the" was included, so it was removed.
=> docs(en): fix typo

src/content/docs/en/tutorial/6-islands/1.mdx
**Closes**: #2871 
Avoid hydration mismatch error in tutorial example, initialize greeting state using the first message in messages instead of a random message
=> Fix hydration mismatch error in tutorial example

src/content/docs/en/recipes.mdx
=> recipe: add community recipe

src/content/docs/en/guides/assets.mdx, src/content/docs/en/reference/image-service-reference.mdx
- Clarifies that `<Image />` and `getImage()` don't work on the client
- Improves wording about the remote endpoint and how its role in transforming the image
- Links to an example that uses `validateOptions`
=> Clarify experimental assets docs

.github/workflows/discord-i18n-ping.yml
- Uses a new Discord webhook set in the repo secrets so the “Translation Tuesday” bot will post to the `#docs-i18n` channel instead of `#docs`
=> Make “Translation Tuesday” bot post to #docs-i18n

src/content/docs/en/recipes/bun.mdx
Adds the recipe for using Astro with Bun
- Closes #2768
=> Add Bun recipe

src/content/docs/en/guides/content-collections.mdx
This PR fixes the guide that transforms the blog tutorial project into an app that uses Content Collections.
Without the added instructions, the project throws errors on blog posts and on tag pages.
Well, I extended the guide, so it kind of is a visual change :)
=> Fix missing changes in the content collections guide

src/content/docs/de/guides/deploy/google-cloud.mdx, src/content/docs/en/guides/deploy/google-cloud.mdx, src/content/docs/en/recipes/bun.mdx, src/content/docs/en/recipes/docker.mdx, src/content/docs/es/guides/deploy/google-cloud.mdx
Fixes all my Markdown link mistakes 🤦‍♂️ I also updated the i18n versions
@Yan-Thomas thanks for noticing!
=> fix bad markdown formatting in links

scripts/tuesday-bot.ts
- Attempts to enable i18n-gang role ping and remove embeds by changing webhook content syntax.
=> Try to fix Translation Tuesday role ping, remove embeds

src/content/docs/zh-cn/reference/error-reference.mdx
- Follow: https://github.com/withastro/docs/commit/be4d982ec6b38ac9eda38d8e9c0b030d89053983
=> i18n(zh-cn): update error-reference.mdx

RECIPES.md
Restructuing Recipes.md to go in order from most-likely to least-likely need for info. Also adding some nuance esp. surrounding community recipes (most common!) and editing/PRing existing recipes to update/correct.
WIP, will want @Jutanium to contribute!
=> [recipes.md] initial edits to recipes guide

CONTRIBUTING.md
Added specific ways people can contribute beyond just filing issues and PRs, to highlight what we'd like people to (know they can) do!
=> [contributing guide] added ways to contribute

src/content/docs/en/guides/content-collections.mdx
This PR fixes the guide that transforms the blog tutorial project into an app that uses Content Collections.
Without the added instructions, post links doesn't work on tag pages.
=> Fix missing changes in the content collections migration guide

src/content/docs/en/recipes/captcha.mdx
The previous description didn't mention the key task we're teaching - it isn't the captcha verification, but the API Routes.
=> Rewrite the description for "Verify a Captcha"

src/content/docs/en/guides/content.mdx
- fixes broken link at content.mdx for opening community integrations with css+ui category filtered
=> en-only fix: broken link at content.mdx

WRITING.md
Adds some initial recipe writing guidance to our existing writing guide.
This is to be added to over time, but captures some recent discussion/decisions in our official guide!
=> [WRITING.md] adds recipe writing examples

src/content/docs/de/concepts/islands.mdx, src/content/docs/de/core-concepts/framework-components.mdx, src/content/docs/en/concepts/islands.mdx, src/content/docs/en/core-concepts/framework-components.mdx, src/content/docs/es/concepts/islands.mdx, src/content/docs/es/core-concepts/framework-components.mdx, src/content/docs/es/guides/integrations-guide/react.mdx, src/content/docs/fr/concepts/islands.mdx, src/content/docs/fr/core-concepts/framework-components.mdx, src/content/docs/ja/concepts/islands.mdx, src/content/docs/pt-br/concepts/islands.mdx, src/content/docs/pt-br/core-concepts/framework-components.mdx, src/content/docs/ru/concepts/islands.mdx, src/content/docs/zh-cn/concepts/islands.mdx, src/content/docs/zh-cn/core-concepts/framework-components.mdx, src/content/docs/zh-tw/concepts/islands.mdx
Updated the react docs url in various places.
=> Updated the react docs url to the new one in various places

src/content/docs/en/guides/troubleshooting.mdx
Adds a section "Creating minimal reproductions" to the troubleshooting docs page
- Closes #695
=> add minimal examples guide

src/content/docs/en/reference/integrations-reference.mdx
- Minor content fixes (typo)
- Adds missing "to" preposition.
=> doc: fixes typo in astro:build:ssr

scripts/tuesday-bot.ts
- What does this PR change? Filter out empty entries like the one here.
=> Fix webhook by filtering empty arrays

src/content/docs/en/guides/integrations-guide/node.mdx
Fixes  typo: servering -> serving
=> en-only typo: servering -> serving

src/content/docs/es/guides/migrate-to-astro/from-docusaurus.mdx
Translated `from-docusaurus.mdx` to spanish
=> i18n(es): Translated `from-docusaurus.mdx`

src/content/docs/es/reference/errors/markdown-image-not-found.mdx
Translated `markdown-image-not-found.mdx` to spanish
=> i18n(es): Translated `markdown-image-not-found.mdx`

src/content/docs/es/guides/migrate-to-astro/from-vuepress.mdx
Translated `from-vuepress.mdx` to spanish 😃
=> i18n(es): Translated `from-vuepress.mdx`

src/content/docs/es/guides/server-side-rendering.mdx
Fixed a component that was not properly closed in the `server-side-rendering.mdx` file.
=> i18n(es): Fix translation in `server-side-rendering.mdx`

src/content/docs/es/guides/migrate-to-astro/from-sveltekit.mdx
Translated `from-sveltekit.mdx` to spanish
=> i18n(es): Translated `from-sveltekit.mdx`

src/content/docs/es/guides/migrate-to-astro/from-eleventy.mdx
Translated `from-eleventy.mdx` to spanish 😁
=> i18n(es): Translated `from-eleventy.mdx`

src/content/docs/es/reference/errors/page-number-param-not-found.mdx
Fixed a translation in the `page-number-param-not-found.mdx` file.
=> i18n(es): Fix translation in `page-number-param-not-found.mdx`

src/content/docs/zh-cn/guides/integrations-guide/node.mdx
- Closes # 
- Translated `node.mdx`
=> i18n(zh-cn):  Translated `node.mdx`

src/content/docs/en/reference/configuration-reference.mdx, src/content/docs/es/reference/errors/expected-image-options.mdx, src/content/docs/es/reference/errors/expected-image.mdx
Translated `expected-image-options.mdx` and `expected-image.mdx` to spanish
=> i18n(es): Translated `expected-image-options.mdx` and `expected-image.mdx`

src/content/docs/en/guides/markdown-content.mdx
- Closes #3128
This PR corrects a sample code under [#markdown-plugins](https://docs.astro.build/en/guides/markdown-content/#markdown-plugins).
=> Fix incorrect Markdown plugins sample code

src/content/docs/en/guides/backend/appwriteio.mdx
Changesa link from 'AppWrite' to 'Appwrite' 😄
=> Change Appwrite typo

src/content/docs/en/guides/backend/google-firebase.mdx
- Add a community resource for firebase
=> add community resource for firebase

WRITING.md
- Adds maintainer docs for the `<RecipeLink>` component to `WRITING.md`
=> Document how to use the `<RecipeLink>` component

src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx
Fixed wrong ref in `from-nuxt.mdx`
=> Fixed wrong ref in `from-nuxt.mdx`

astro.config.ts, package.json, plugins/rehype-optimize-static.ts, pnpm-lock.yaml
Optimize static subtrees of the MDX intermediate hast as `set:html` prop to reduce final AST size
=> Optimize static mdx

TRANSLATING.md
there's some pages already translated in korean.
so please add korean in README.md 🤗
it can be make more passion about astro to korean developers! 
thanks for read my propose! 
propose to add korean about astro translation languages
=> how about add korean in translation languages

src/content/docs/en/guides/backend/google-firebase.mdx
- Fixes the Firebase `description` which mentions Supabase 😅
=> Fix Firebase guide description

src/content/docs/ja/guides/backend.mdx, src/content/docs/ja/guides/cms.mdx, src/content/docs/ja/guides/migrate-to-astro.mdx
- Update the translation about stubs based on the discussion in https://github.com/withastro/docs/pull/3194/files#r1186786190
=> i18n(ja): Update the translation about stubs

src/content/docs/fr/guides/deploy/google-firebase.mdx
Need to be updated after [this issue was closed](https://github.com/withastro/docs/issues/3236). 
PR to init the file and be ready to receive the new text.
=> i18n(fr): Added `Google Firebase`

src/content/docs/en/getting-started.mdx, src/content/docs/en/install/manual.mdx
- Closes #3045 
- What does this PR change? I added a note to the getting started page and manual install guide warning users to not install Astro globally.
=> Add Note to Install Locally

src/content/docs/ko/guides/aliases.mdx, src/i18n/ko/nav.ts
Translated `guides/aliase.mdx`.
=> i18n(ko): Translated guides/aliase.mdx

src/content/docs/en/guides/backend/google-firebase.mdx
The code snippet has a small typo (a missing double quote), this PR fixes that.
- Did you change something visual? A before/after screenshot can be helpful.  **NO**
=> Fix missing quote typo in code sample

src/content/docs/fr/guides/backend.mdx, src/i18n/fr/nav.ts
Translated `backend.mdx` content to french
=> i18n(fr): Translation of `backend.mdx`

src/content/docs/ja/contribute.mdx
- Update contribute.mdx.
- Corresponds to https://github.com/withastro/docs/pull/3322.
=> i18n(ja): Update contribute.mdx

src/content/docs/en/guides/cms/contentful.mdx
- In some parts of the code in contentful.mdx, the`BlogPost` type was written as `blogPost`, so these are corrected.
=> Fix typos in guides/cms/contentful.mdx

src/content/docs/en/guides/cms/statamic.mdx
Fixing a typo
There was a typo in the docs
=> Statamic - typo fix

src/content/docs/fr/contribute.mdx, src/content/docs/fr/getting-started.mdx
Updated the `contribute.mdx` and `getting-started.mdx` translations to match English modifications. 
This is my first PR, please let me know if I did something wrong! :-)
=> i18n(fr): Update `contribute.mdx` and `getting-started.mdx` translations

src/content/docs/zh-cn/install/manual.mdx
=> i18n(zh-cn): Update manual.mdx

src/content/docs/zh-cn/editor-setup.mdx
=> i18n(zh-cn): Update editor-setup.mdx

src/content/docs/zh-cn/getting-started.mdx
=> i18n(zh-cn): Update getting-started.mdx

src/content/docs/zh-cn/contribute.mdx
=> i18n(zh-cn): Update contribute.mdx

src/content/docs/en/guides/content-collections.mdx
- What does this PR change? It fixes the buggy example at https://docs.astro.build/en/guides/content-collections/#accessing-referenced-data , currently `<h1>{blogPost.data.title}</h1>` would fire fatal error with undefined `blogPost`.
- Did you change something visual? Nope.
=> Fixing content collections guide "Accessing referenced data" example

src/content/docs/en/recipes/docker.mdx
- Updated NGINX example to include EXPOSE. Without it, anyone the `Dockerfile` will close immediately after running. This will be helpful for anyone new with Docker.
=> Update NGINX example

src/content/docs/es/core-concepts/endpoints.mdx
Updated `endpoints.mdx` based on this commit 046e0af9329b5f23bbc8dcde58681a4d956f3261
=> i18n(es): Updated `endpoints.mdx`

src/content/docs/en/guides/migrate-to-astro/from-vuepress.mdx
Fix typo in `from-vuepress.mdx`
=> i18n(en): Fix typo in `from-vuepress.mdx`

src/content/docs/es/reference/directives-reference.mdx
Updated `directives-reference.mdx` based on this commit 9b641f07955566962ec3df58b44e37c9b9e7e046
=> i18n(es): Updated `directives-reference.mdx`

src/content/docs/es/reference/error-reference.mdx
Updated `error-reference.mdx`
* [05eac77](https://github.com/withastro/docs/commit/05eac779ae7f433955fd1d8909273eb32ac6f479)
=> i18n(es): Updated `error-reference.mdx`

src/content/docs/es/reference/api-reference.mdx
Updated `api-reference.mdx`
* [3c5bdc8](https://github.com/withastro/docs/commit/3c5bdc8e5fa5b92677bb986e2f686e7daca2edb3#diff-42959260ea642887b866e8e276a4520c1f112356eb9c15b31e510132a481aed6)
* [c793420](https://github.com/withastro/docs/commit/c79342060d9a1094ca33dadd609ce72bac4709a7)
=> i18n(es): Updated `api-reference.mdx`

src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/es/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/es/guides/server-side-rendering.mdx, src/content/docs/es/guides/upgrade-to/v2.mdx
Updated `from-gatsby.mdx`,`from-nuxtjsmdx`, `from-nextjs.mdx`, `server-side-rendering.mdx` & `v2.mdx` based on this commit 0b7b49471a1b0fdcb64a667a0a87b2de8617f4fe
=> i18n(es): Updated `from-gatsby.mdx`,`from-nuxtjsmdx`, `from-nextjs.mdx`, `server-side-rendering.mdx` & `v2.mdx`

src/content/docs/es/guides/styling.mdx
Updated `styling.mdx` with the commit [`aedcab5`](https://github.com/withastro/docs/commit/aedcab56a9a83ea17ce123e2ffab1b24f8be2355)
=> i18n(es): Updated `styling.mdx`

src/content/docs/es/reference/integrations-reference.mdx
Updated `integrations-reference.mdx` with the commit [`9b641f0`](https://github.com/withastro/docs/commit/9b641f07955566962ec3df58b44e37c9b9e7e046#diff-4aa2d04c24b155473112c2cc7104df7627bfa0a40dc156564828ca6c2dd48a65)
=> i18n(es): Updated `integrations-reference.mdx`

src/content/docs/es/guides/migrate-to-astro/from-pelican.mdx, src/content/docs/es/guides/migrate-to-astro/from-vuepress.mdx
Updated `from-pelican.mdx & `from-vuepress.mdx` based on this commit ad666cb07cb3a95e34e4567a10b5f19b138feb8f
=> i18n(es): Updated `from-pelican.mdx` & `from-vuepress.mdx`

src/content/docs/es/guides/migrate-to-astro/from-gitbook.mdx
Updated `from-gitbook.mdx` based on this commit ad666cb07cb3a95e34e4567a10b5f19b138feb8f
=> i18n(es): Updated `from-gitbook.mdx`

src/content/docs/es/guides/migrate-to-astro/from-docusaurus.mdx
Updated `from-docusaurus.mdx` based on this commit ad666cb07cb3a95e34e4567a10b5f19b138feb8f
=> i18n(es): Updated `from-docusaurus.mdx`

src/content/docs/es/guides/integrations-guide/netlify.mdx
* [669b6d5](https://github.com/withastro/docs/commit/669b6d5e254fb873807fb43ed78331e2b32797dd)
=> i18n(es): Updated `netlify.mdx`

src/content/docs/es/guides/cms/contentful.mdx
Updated `contentful.mdx`
* [c793420](https://github.com/withastro/docs/commit/c79342060d9a1094ca33dadd609ce72bac4709a7#diff-7f4550f0c31345b1ef85a70b5f4f2b11ab0fc191dda80a3af7afa6e77ab527ac)
=> i18n(es): Updated `contentful.mdx`

src/content/docs/es/guides/deploy/google-firebase.mdx
Updated `google-firebase.mdx`
* [`e2cac20`](https://github.com/withastro/docs/commit/e2cac2007884b15432229357ed57028e8af446f1)
=> i18n(es): Updated `google-firebase.mdx`

src/content/docs/es/reference/configuration-reference.mdx
Updated `configuration-reference.mdx`
* [527bd31](https://github.com/withastro/docs/commit/527bd31af0b7c1af4b7270e5426edbcd0b78e9cc)
=> i18n(es): Updated `configuration-reference.mdx`

src/content/docs/ko/core-concepts/project-structure.mdx
- Updated `project-structure.mdx`
=> i18n(ko): Update the outdated ko/project-structure.mdx

src/content/docs/en/guides/server-side-rendering.mdx, src/content/docs/es/guides/server-side-rendering.mdx
=> Fix error content

src/content/docs/es/reference/error-reference.mdx, src/content/docs/es/reference/errors/unsupported-config-transform-error.mdx
Translated `unsupported-config-transform-error.mdx` to spanish and added reference
=> i18n(es): Translated `unsupported-config-transform-error.mdx`

src/content/docs/en/guides/cms/contentful.mdx
- What does this PR change? Fix `properties` typo
=> typo: properties

src/content/docs/en/guides/deploy/netlify.mdx
Specified exact CLI command "netlify login"
Specified exact CLI command "netlify login"
=> Update netlify.mdx, specified exact CLI command "netlify login"

src/content/docs/en/guides/server-side-rendering.mdx
For some reason there was an `@version 2.0.0` in the middle of the text.
=> Fix typo "version" in `server-side-rendering.mdx`

src/content/docs/en/contribute.mdx
Removed an unecessary blockquote mentioning the main Astro repo again.
=> Remove duplicate mention in `contribute.mdx`

src/content/docs/es/contribute.mdx
Updated `contribute.mdx` based on these commits 99fe714562b35720768a9e8d93185f2672b8bb32, 762eceb4e8b6d8f5382f0df788d28fa2f778718b & 38f70780398b3a59697d0be8a4eff013a234e8df
=> i18n(es): Updated `contribute.mdx`

src/content/docs/en/guides/server-side-rendering.mdx
Fix typo in `server-side-rendering.mdx`
=> Fix typo in `server-side-rendering.mdx`

src/content/docs/es/guides/deploy/netlify.mdx, src/content/docs/es/guides/server-side-rendering.mdx
Updated `netlify.mdx` based on this commit b2390b58726e8928c86d415e29e2883b8d194458 & `server-side-rendering.mdx` based on these commits 278f33ec366aa379e1919be63418d67fa28e48f2, a6ca6f780e996a7812a193174dde1718dd683102 & 8500b624490f88498b7d24a1c45d6350cfd094fd
=> i18n(es): Updated `netlify.mdx` & `server-side-rendering.mdx`

src/i18n/en/nav.ts, src/i18n/ja/nav.ts, src/i18n/zh-cn/nav.ts
- Closes #3510
- What does this PR change? Removes "experimental" from sidebar titles for the middleware page.
=> Update nav labels for middleware

src/content/docs/en/guides/middleware.mdx
Add a missing "await" in the middleware sample code, because response.text() returns a Promise.
=> Fix missing await in middleware example

src/content/docs/en/guides/backend/google-firebase.mdx
Adds bold and italic text in navigating sections or buttons.
(conform with rest of guides)
**Page of interest**: https://deploy-preview-3544--astro-docs-2.netlify.app/en/guides/backend/google-firebase/
=> docs: improve readability on the Firebase guide

src/content/docs/es/reference/errors/csssyntax-error.mdx
Updated `csssyntax-error.mdx` based on this commit 82dff8245ac898d011bd55d546d59fc1160b2d19
=> i18n(es): Updated `csssyntax-error.mdx`

src/content/docs/en/tutorial/3-components/2.mdx
- Minor content fixes
I just found it when I'm translating this page into Chinese.
- fix a typo in `src/content/docs/en/tutorial/3-components/2.mdx`
=> docs(tutorial): minor typo fix

src/content/docs/en/guides/cms/payload.mdx
This pull request adds a new community resource to the Payload CMS guide.
Astroad is a convenient template that provides an easy development environment and VPS deployment for Astro and Payload CMS using Docker. I believe that it would be a valuable addition to the "Community Resources" section of the guide, providing users with another useful template to help them get started with Astro and Payload CMS.
You can find more information about astroad at the following link: https://github.com/mooxl/astroad
=> Add astroad to community resources of the PayloadCMS guide

src/content/docs/es/tutorial/3-components/2.mdx
Updated `2.mdx` file from tutorial/3-components based on this commit 0a7f9201d1180496c5a354076dc97ce585d045c5
=> i18n(es): Updated `tutorial/3-components/2.mdx`

src/content/docs/es/guides/integrations-guide/cloudflare.mdx, src/content/docs/es/guides/integrations-guide/deno.mdx, src/content/docs/es/guides/integrations-guide/image.mdx
Updated `cloudflare.mdx`, `deno.mdx` & `image.mdx` based on this commit b384e457a33924532ca327a18faf99536a8829f1
=> i18n(es): Updated `cloudflare.mdx`, `deno.mdx` & `image.mdx`

src/content/docs/es/guides/cms/decap-cms.mdx
Translated `decap-cms.mdx` to spanish
=> i18n(es): Translated `decap-cms.mdx`

src/content/docs/es/guides/cms/crystallize.mdx
Translated `crystallize.mdx` to spanish
=> i18n(es): Translated `crystallize.mdx`

src/content/docs/en/recipes/build-forms.mdx
Spotted misplaced backticks while translating this file to spanish.
=> Fix: fixed misplaced backticks

src/content/docs/es/guides/integrations-guide/partytown.mdx, src/content/docs/es/guides/integrations-guide/prefetch.mdx, src/content/docs/es/guides/integrations-guide/sitemap.mdx, src/content/docs/es/guides/integrations-guide/solid-js.mdx
Updated `solid-js.mdx`, `sitemap.mdx`, `prefetch.mdx` & `partytown.mdx`
* [`b384e45`](https://github.com/withastro/docs/commit/b384e457a33924532ca327a18faf99536a8829f1#diff-592f0f9cd6a36d0b3669dc6b46ffe75ea24f13a80cc31659d9f856ea5435c4d6)
=> i18n(es): Updated `solid-js.mdx`, `sitemap.mdx`, `prefetch.mdx` & `partytown.mdx`

src/content/docs/es/recipes.mdx
=> i18n(es): Translated `recipes.mdx`

src/content/docs/es/guides/cms/payload.mdx
Translated `payload.cms` to spanish.
=> i18n(es): Translated `payload.cms`

src/content/docs/es/guides/middleware.mdx
=> i18n(es): Translated `middleware.mdx`

src/content/docs/es/guides/cms/frontmatter-cms.mdx
Translated `frontmatter-cms.mdx` to spanish.
=> i18n(es):  Translated `frontmatter-cms.mdx`

src/content/docs/es/recipes/build-forms-api.mdx
Translated `build-forms-api.mdx` to spanish.
=> i18n(es): Translated `build-forms-api.mdx`

src/content/docs/es/recipes/build-forms.mdx
Translated recipe `build-forms.mdx` to spanish
=> i18n(es): Translated recipe `build-forms.mdx`

src/content/docs/es/core-concepts/framework-components.mdx, src/content/docs/es/editor-setup.mdx, src/content/docs/es/guides/deploy.mdx, src/content/docs/es/guides/deploy/kinsta.mdx, src/content/docs/es/guides/environment-variables.mdx, src/content/docs/es/guides/imports.mdx, src/content/docs/es/guides/integrations-guide/deno.mdx, src/content/docs/es/guides/integrations-guide/partytown.mdx, src/content/docs/es/guides/integrations-guide/preact.mdx, src/content/docs/es/guides/integrations-guide/vue.mdx, src/content/docs/es/guides/migrate-to-astro.mdx, src/content/docs/es/guides/testing.mdx, src/content/docs/es/reference/api-reference.mdx, src/content/docs/es/reference/cli-reference.mdx, src/content/docs/es/reference/configuration-reference.mdx, src/content/docs/es/reference/directives-reference.mdx, src/content/docs/es/reference/error-reference.mdx, src/content/docs/es/reference/errors/invalid-content-entry-frontmatter-error.mdx, src/content/docs/es/reference/errors/markdown-content-schema-validation-error.mdx, src/content/docs/es/reference/publish-to-npm.mdx, src/content/docs/es/tutorial/2-pages/3.mdx
=> i18n(es): Fix various typos

src/content/docs/es/reference/image-service-reference.mdx
Translated `image-service-reference.mdx` to spanish.
=> i18n(es): Translated `image-service-reference.mdx`

src/content/docs/es/tutorial/6-islands/2.mdx
Updated `6-islands/2.mdx`
* [`7019ad3`](https://github.com/withastro/docs/commit/7019ad36c57a3d67808d9761b77530fb9ef4f6a7)
=> i18n(es): Updated `6-islands/2.mdx`

src/content/docs/en/tutorial/4-layouts/1.mdx
I agree with the tutorial feedback, this option is weird and I don't remember writing it. Delete!
=> [tutorial] update quiz option

src/content/docs/es/guides/configuring-astro.mdx
Updated `confugiring-astro.mdx` based on this commit 1cb53e0711f2222d6c761ef63c8542a240cfe248
=> i18n(es): Updated `configuring-astro.mdx`

src/content/docs/es/guides/data-fetching.mdx
- Updated the graphql example from this [commit](https://github.com/withastro/docs/commit/6b4fc99ee1924298ab1904be42c715f27000a001).
=> i18n(es): Updated graphql example

src/content/docs/es/tutorial/4-layouts/1.mdx
Updated `4-layouts/1.mdx`
* [`ff29ef0`](https://github.com/withastro/docs/commit/ff29ef04ec96fe49f470e380cc9ed8710dfd300f)
=> i18n(es): Updated `4-layouts/1.mdx`

src/content/docs/es/guides/middleware.mdx
Updated `middleware.mdx` based on this commit 22c58ac6580b01cfaa3005af0f494ced9f2fde8a
=> i18n(es): Updated `middleware.mdx`

src/content/docs/ja/tutorial/1-setup/index.mdx
- Add tutorial/1-setup/index.mdx.
=> i18n(ja): Add tutorial/1-setup/index.mdx

src/content/docs/ja/tutorial/1-setup/3.mdx
=> i18n(ja): Add tutorial/1-setup/3.mdx

src/content/docs/ja/tutorial/2-pages/index.mdx
- Add tutorial/2-pages/index.mdx.
=> i18n(ja): Add tutorial/2-pages/index.mdx

src/content/docs/es/guides/integrations-guide/vercel.mdx
Updated `vercel.mdx` based on this commit c0ef26d2dacc3b7cebca4cad6e88bae393048feb
=> i18n(es): Updated `vercel.mdx`

src/content/docs/es/reference/cli-reference.mdx
Updated `cli-reference.mdx` based on this commit 2ee39246d2396a5e4f4c9dd0e9256180f32214b7
=> i18n(es): Updated `cli-reference.mdx`

src/content/docs/es/guides/integrations-guide/cloudflare.mdx, src/content/docs/es/guides/integrations-guide/markdoc.mdx, src/content/docs/es/guides/integrations-guide/node.mdx
Updated `cloudflare.mdx`, `markdoc.mdx` & `node.mdx` based on this commit f66fe8951974904483380563db4b5617a546d1e2 & f6b534cf6ca2f0400c44f2e90a8faa5cbea10ba9
=> i18n(es): Updated `cloudflare.mdx`, `markdoc.mdx` & `node.mdx`

src/content/docs/es/guides/middleware.mdx, src/content/docs/es/reference/integrations-reference.mdx
Updated `middleware.mdx` & `integrations-reference.mdx` based on this commit e52561db526dccf3e08ae5fce9b685ce2168b923
=> i18n(es): Updated `middleware.mdx` & `integrations-reference.mdx`

src/content/docs/en/tutorial/2-pages/2.mdx
- Fix some typos in tutorial 2-2.
=> Fix some typos in tutorial 2-2

src/components/Version.astro
After all those years in this vital industry, I finally added retry logic to the Version component. No more build errors, the world is saved!
Note: I noticed some layout shifting while opening the Integrations pages in dev mode, but building locally and previewing made this disappear, so I guess it's fine.
=> Finally add retry logic to Version component

src/content/docs/es/guides/integrations-guide/prefetch.mdx, src/content/docs/es/reference/configuration-reference.mdx
Updated `prefetch.mdx`
`prefetch.mdx`
* [`f6563bb`](https://github.com/withastro/docs/commit/f6563bbd815168345e402fd56204013797c262e8)
`configuration-reference.mdx`
* [`e724d5e`](https://github.com/withastro/docs/commit/e724d5ed5821e888f56d64113bebe330dd6c28a8)
=> i18n(es): Updated `prefetch.mdx` & `configuration-reference.mdx`

src/content/docs/es/core-concepts/astro-syntax.mdx
Updated `astro-syntax.mdx`
As this page was previously translated, there is no update commit in the tracking page, so there is no commit referenced.
https://github.com/withastro/docs/blob/1c986c4707f3e2f22ee0032bb1b5121aa7f18aea/src/content/docs/en/core-concepts/astro-syntax.mdx
=> i18n(es): Updated `astro-syntax.mdx`

src/util/getContributors.ts
Small fix to an ESLint error that was showing up in every PR.
=> Remove ESLint issue

src/content/docs/es/guides/markdown-content.mdx
Fixed typo in `markdown-content.mdx`
=> i18n(es): Fixed typo in `markdown-content.mdx`

src/content/docs/ja/tutorial/2-pages/3.mdx
=> i18n(ja): Add tutorial/2-pages/3.mdx

src/content/docs/ja/tutorial/2-pages/5.mdx
=> i18n(ja): Add tutorial/2-pages/5.mdx

src/content/docs/ja/tutorial/3-components/index.mdx
- Add tutorial/3-components/index.mdx.
=> i18n(ja): Add tutorial/3-components/index.mdx

src/content/docs/es/reference/errors/unsupported-image-format.mdx
Updated `unsupported-image-format.mdx` based on this commit f61156fd82df2b15ef60140490c821ee051e1811
=> i18(es: Updated `unsupported-image-format.mdx`

src/content/docs/es/guides/integrations-guide/image.mdx, src/content/docs/es/guides/integrations-guide/netlify.mdx
Updated `image.mdx` & `netlify.mdx` based on this commit 8fbd915f1a6ac3da4d827490655fccc431ce22f8
=> i18n(es): Updated `image.mdx` & `netlify.mdx`

src/content/docs/en/tutorial/3-components/2.mdx, src/content/docs/en/tutorial/3-components/3.mdx, src/content/docs/es/tutorial/3-components/2.mdx, src/content/docs/es/tutorial/3-components/3.mdx
- Fix indentation in tutorial 3-2.
=> Fix indentation in tutorial 3-2 and 3-3

src/content/docs/ja/tutorial/3-components/2.mdx
- Add tutorial/3-components/2.mdx.
=> i18n(ja): Add tutorial/3-components/2.mdx

src/content/docs/en/tutorial/4-layouts/2.mdx
=> Fix typos in tutorial 4-2

src/content/docs/en/reference/api-reference.mdx
- What does this PR change? Corrects `context.locals` to specify it can be used in API endpoints.
=> Update context.locals reference

src/content/docs/en/guides/client-side-routing.mdx
=> draft edits

src/content/docs/pt-br/contribute.mdx
Updated `contribute.mdx` based on this commit 99fe714562b35720768a9e8d93185f2672b8bb32 and others missing parts.
=> i18n(pt-BR): Updated `contribute.mdx`

src/content/docs/es/reference/adapter-reference.mdx
Updated `adapter-reference.mdx` based on this commit b6e62022b217495b3d259bbf3038dba53a1e4b48
=> i18n(es): Updated `adapter-reference.mdx`

src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/es/guides/migrate-to-astro/from-nuxtjs.mdx
Updated `from-gatsby.mdx`, `from-nextjs.mdx` & `from-nuxtjs.mdx` based on this commit 80cfa58648c40b88d95304a7d57da7557ad4322e
=> i18n(es): Updated `from-gatsby.mdx`, `from-nextjs.mdx` & `from-nuxtjs.mdx`

src/content/docs/en/tutorial/4-layouts/3.mdx
- Updated the explanation at the beginning since it is slightly out of sync with the content of Tutorial 4-2.
- I thought it was a little difficult to understand what "achieve that" in line 28 meant, so replaced that with a more concrete description of what we want to do next.
=> Improve tutorial 4-3

src/content/docs/es/tutorial/2-pages/index.mdx, src/content/docs/es/tutorial/3-components/index.mdx, src/content/docs/es/tutorial/4-layouts/index.mdx, src/content/docs/es/tutorial/5-astro-api/index.mdx, src/content/docs/es/tutorial/6-islands/3.mdx, src/content/docs/es/tutorial/6-islands/index.mdx
Updated tutorials and translated missing content based on this closed [PR](https://github.com/withastro/docs/pull/3770)
=> i18n(es): Updated tutorials

src/content/docs/es/guides/integrations-guide/netlify.mdx
- [04e45d2](https://github.com/withastro/docs/commit/04e45d26d79c2b30fcc74838b90a4fb947e9231b)
- [cdca3fc](https://github.com/withastro/docs/commit/cdca3fc3c168c5f607224664cac33abfd8eaa0fe)
=> i18n(es): `netlify.mdx` update

src/content/docs/en/tutorial/6-islands/2.mdx, src/content/docs/es/tutorial/6-islands/2.mdx
- Fix indentation in tutorial 6-2.
| before | after |
| --- | --- |
| ![Screenshot 2023-07-24 at 0 34 16](https://github.com/withastro/docs/assets/7889778/8a8b1723-519a-4be2-9156-f670961e4e3a) | ![Screenshot 2023-07-24 at 0 34 02](https://github.com/withastro/docs/assets/7889778/e8e0eb30-7bab-4bbe-ae2b-5788d22d4fad) |
=> Fix indentation in tutorial 6-2

src/content/docs/pt-br/guides/deploy/google-firebase.mdx
- Changes of `guides/deploy/google-firebase.mdx` based on 29aae1bdf726826b6effdc9aed7b142b7974e065, and e2cac2007884b15432229357ed57028e8af446f1
=> i18n(pt-BR): Updated `guides/deploy/google-firebase.mdx`

src/content/docs/pt-br/guides/configuring-astro.mdx
- Updated `guides/configuring-astro.mdx` based on 1cb53e0711f2222d6c761ef63c8542a240cfe248
=> i18n(pt-BR): Updated `guides/configuring-astro.mdx`

src/content/docs/pt-br/core-concepts/routing.mdx
- Updated `/core-concepts/routing.mdx` based on c3471b6f50d1714b4568564a85b8da3b06048ae9
=> i18n(pt-BR): Updated `/core-concepts/routing.mdx`

src/content/docs/ja/tutorial/0-introduction/1.mdx, src/content/docs/ja/tutorial/0-introduction/index.mdx, src/content/docs/ja/tutorial/1-setup/3.mdx, src/content/docs/ja/tutorial/1-setup/index.mdx, src/content/docs/ja/tutorial/2-pages/2.mdx, src/content/docs/ja/tutorial/2-pages/3.mdx, src/content/docs/ja/tutorial/2-pages/4.mdx, src/content/docs/ja/tutorial/3-components/4.mdx
- Stylistic adjustments, typo corrections, etc.
- https://github.com/withastro/docs/commit/b86a0ec1ddeb22c46900ab62679201db341314c5
- https://github.com/withastro/docs/commit/a5139ab2deea0ad554bedf8d0d8aba228172c200
- チェックリスト、description、確認テストの口調統一
=> i18n(ja): Tweak the Japanese tutorial

src/content/docs/es/tutorial/1-setup/index.mdx
Updated `/1-setup/index.mdx` based on this commit c66ae77f06ea158b7f9475ab6a745eeb395cef48
=> i18n(es): Updated `/1-setup/index.mdx`

src/content/docs/pt-br/guides/integrations-guide/deno.mdx
- Updated `guides/integrations-guide/deno.mdx` based on b384e457a33924532ca327a18faf99536a8829f1
=> i18n(pt-BR): Updated `guides/integrations-guide/deno.mdx`

src/content/docs/pt-br/guides/deploy/netlify.mdx
- Updated `guides/deploy/netlify.mdx` based on b2390b58726e8928c86d415e29e2883b8d194458
=> i18n(pt-BR): Updated `guides/deploy/netlify.mdx`

src/content/docs/pt-br/guides/environment-variables.mdx
- Updated `guides/environment-variables.mdx` based on 5f678d6b3fc60d40abab6089c4e55a67ac093b6b
=> i18n(pt-BR): Updated `guides/environment-variables.mdx`

src/content/docs/pt-br/guides/deploy/kinsta.mdx
- Updated `/guides/deploy/kinsta.mdx` based on fadae4274c54d07dd3be000aec28fb54fcc2cfcd
=> i18n(pt-BR): Updated `/guides/deploy/kinsta.mdx`

src/content/docs/pt-br/guides/fonts.mdx
- Updated `guides/fonts.mdx` based on bea5d83cdb2ee6419da64ad3f396459bc403196a, and 9173597418df8c94d6b3b76e1aed9e41e25ca183
=> i18n(pt-BR): Updated `guides/fonts.mdx`

src/content/docs/pt-br/guides/images.mdx
- Updated `guides/images.mdx` based on 81c1a6413da5a9e7b3b546d2f954bc60ddfb8083, e1a3bd1949531b4cb21699863543e60a229f94df, 4dbf4c6bdfd83b4f125ebd4bbfe499a57b78248f, 8077640390594eab66c6497d5e9146c2e5bef371, and e0f40c552bd60c4922b8c49e01ff7c185e79e878
=> i18n(pt-BR): Updated `guides/images.mdx`

src/content/docs/pt-br/core-concepts/endpoints.mdx
- Updated `core-concepts/endpoints.mdx` based on dd6c16bcb158cc386eb678a5a9d57e177e763c39, 829b66397ad31b2e3921af7f96d5aed7677e8ddf, and minor fixes
=> i18n(pt-BR): Updated `core-concepts/endpoints.mdx`

src/content/docs/pt-br/core-concepts/sharing-state.mdx
- Updated `core-concepts/sharing-state.mdx` based on e5ecc42ba415067a434321c0e64816025505bc89 and minor fixes
=> i18n(pt-BR): Updated `core-concepts/sharing-state.mdx`

src/content/docs/pt-br/guides/markdown-content.mdx
- Updated `guides/markdown-content.mdx` based on e177bd4fe25e2b6adb5f0596c58a95dde388ec4f, 1d43ca26e826d30a174633ba6bab97e060a773c3, 895c4b93df05a1a4a43cdaf152c63ecc99a25ac2, b42a52b6d247c1b7342ce9f7e529338e6811fc58, 450d18a1dbb2810b389714fd6686f8d59c07642c, 00031d5a0f90ed1e8f1f5b28ebf48739de1bb713, fdc858fc32334220dfdc02a2fd42e8c60684c5fb, 94ad137ea760728f025e74079a7e7ba4170959b1, ecadebecd7f2ae7408b714c47b7fb4c164e6f207, d48cb6db1ecb17bf92391cb7e89d07bab1b052d8, and 716cd0deaa33e1af87a55421dd061f5d7e24f00a.
- I've found a unused import here https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/markdown-content.mdx#L505C10-L505C26 that might be good to remove (PR not created yet).
=> i18n(pt-BR): Updated `guides/markdown-content.mdx`

src/content/docs/ja/tutorial/5-astro-api/3.mdx
- Add tutorial/5-astro-api/3.mdx.
=> i18n(ja): Add tutorial/5-astro-api/3.mdx

src/content/docs/ja/tutorial/5-astro-api/4.mdx
- Add tutorial/5-astro-api/4.mdx.
=> i18n(ja): Add tutorial/5-astro-api/4.mdx

src/content/docs/ja/tutorial/6-islands/index.mdx
- Add tutorial/6-islands/index.mdx.
=> i18n(ja): Add tutorial/6-islands/index.mdx

src/content/docs/ja/tutorial/6-islands/1.mdx
- Add tutorial/6-islands/1.mdx.
=> i18n(ja): Add tutorial/6-islands/1.mdx

src/content/docs/ja/tutorial/6-islands/2.mdx
- Add tutorial/6-islands/2.mdx.
=> i18n(ja): Add tutorial/6-islands/2.mdx

src/content/docs/ja/tutorial/6-islands/3.mdx
- Add tutorial/6-islands/3.mdx.
=> i18n(ja): Add tutorial/6-islands/3.mdx

src/content/docs/en/recipes.mdx
This pull request adds a community recipe on how to set up micro-frontends using Astro and EcmaScript Modules.
=> Add community recipe for micro-frontends

src/content/docs/pt-br/guides/data-fetching.mdx
- Updated `guides/data-fetching.mdx` based on f222da46c26f7542473ec71685ec853b4c9fe580
=> i18n(pt-BR): Updated `guides/data-fetching.mdx`

src/content/docs/pt-br/guides/rss.mdx
- Updated `guides/rss.mdx` based on 4af6dfc80d4e51e5aac1bd20a9348dc4fb4c676b
=> i18n(pt-BR): Updated `guides/rss.mdx`

src/content/docs/en/core-concepts/layouts.mdx, src/content/docs/en/core-concepts/project-structure.mdx
Changes to `project-structure.mdx`:
- Emphasized that this guide is simply conventions.
- Layouts are NOT "special".
Changes to `layouts.mdx`:
- Mentioned that layouts can be colocated with pages using `_`.
- More importantly, mentioned "global styles" and "meta tags" so it shows up in search.
Hopefully addresses https://github.com/withastro/docs/issues/1479#issuecomment-1654033757.
=> clarify file conventions and layouts

src/components/RecipesNav.astro
Fix to an `astro check` issue because we now have more pages than TypeScript can handle 💅
=> Fix union type check

contributor-guides/writing-and-style-guide.md
=> fix typo in writing-and-style-guide.md

src/content/docs/zh-cn/guides/integrations-guide/solid-js.mdx, src/content/docs/zh-cn/guides/integrations-guide/vue.mdx
- New content
- Translate following mdx content to Chinese.
- **`guides/integrations-guide/vue.mdx`**
- **`guides/integrations-guide/solid-js.mdx`**
=> i18n(zh-cn): Translate `guides/integrations-guide/vue.mdx & solid-js.mdx`

src/content/docs/pt-br/reference/errors/unsupported-image-format.mdx
- Updated `reference/errors/unsupported-image-format.mdx` based on commits in the original pages (see the commit history for more references)
=> i18n(pt-BR): Updated `reference/errors/unsupported-image-format.mdx`

src/content/docs/pt-br/reference/publish-to-npm.mdx
- Updated `reference/publish-to-npm.mdx` based on commits in the original pages (see the commit history for more references)
=> i18n(pt-BR): Updated `reference/publish-to-npm.mdx`

src/content/docs/pt-br/reference/directives-reference.mdx, src/content/docs/pt-br/reference/integrations-reference.mdx
- Updated `reference/directives-reference.mdx`, and `reference/integrations-reference.mdx` based on commits in the original pages (see the commit history for more references)
=> i18n(pt-BR): Updated `reference/directives-reference.mdx`, and `reference/integrations-reference.mdx`

src/content/docs/zh-cn/guides/cms/crystallize.mdx
=> i18n(zh-cn): translate crystallize.mdx

src/content/docs/zh-cn/guides/imports.mdx
Translated content
update imports.mdx
=> i18n(zh-cn): update imports.mdx

src/content/docs/zh-cn/guides/cms/directus.mdx
=> i18n(zh-cn): translate directus.md

src/content/docs/ja/tutorial/2-pages/3.mdx
- Update tutorial/2-pages/3.mdx.
- Fix closing brace position.
- Related to https://discord.com/channels/830184174198718474/972429103821111326/1135545126979129444.
=> i18n(ja): Update tutorial/2-pages/3.mdx

src/content/docs/zh-cn/guides/cms/decap-cms.mdx
=> i18n(zh-cn): translate decap-cms.md

src/content/docs/en/guides/assets.mdx
Docs incorrectly describe Squoosh as working in "all JavaScript environments" when there are, in fact, limitations. This removes that statement, and makes a slightly stronger push for installing sharp in a Node environment.
=> [experimental assets] remove misleading Squoosh message

src/content/docs/zh-cn/guides/typescript.mdx
- update the translation,fix some problems of format.
- update `guides/typescript.mdx`
=> i18n(zh-cn): update `guides/typescript.mdx`

src/content/docs/pt-br/guides/deploy/aws.mdx
- Updated `guides/deploy/aws.mdx` based on commits in the original pages (see the commit history for more references)
=> i18n(pt-BR): Updated `guides/deploy/aws.mdx`

src/content/docs/es/core-concepts/routing.mdx
=> i18n(es): Update core-concepts/routing

src/content/docs/zh-cn/guides/client-side-scripts.mdx
- Update /guides/client-side-scripts.mdx
=> i18n(zh-cn): Update /guides/client-side-scripts.mdx

src/content/docs/zh-cn/core-concepts/routing.mdx
- Update routing.mdx
- Follow up: https://github.com/withastro/docs/commit/8fccdc9f7615a2282bd6936179f1becbeaf6de7b
=> i18n(zh-cn): Update routing.mdx

src/content/docs/pt-br/core-concepts/routing.mdx
Update line highlight to [match english source](https://github.com/withastro/docs/commits/main/src/content/docs/en/core-concepts/routing.mdx?since=2023-07-24T01:00:01.000Z).
Before:
After:
=> i18n(pt-BR): Update `core-concepts/routing.mdx` translation

src/content/docs/zh-cn/reference/api-reference.mdx
=> i18n(zh-cn): Update api-reference.mdx

src/content/docs/zh-cn/guides/deploy/deno.mdx
Translate `guides/deploy/deno.mdx` content to Chinese.
=> i18n(zh-cn): Translate `guides/deploy/deno.mdx`

src/content/docs/en/guides/content-collections.mdx
- What does this PR change? Based on a feedback fish we reviews on Talking & Docin', update the rest parameter to be consistent with usage on the page
=> Update rest paramter for consistency

src/content/docs/es/guides/deploy/space.mdx, src/content/docs/es/guides/integrations-guide/netlify.mdx, src/content/docs/es/reference/api-reference.mdx
Updated `api-reference.mdx` -> d051604d4402e506fc7d3c5d98ad8a3e35e06307, `netlify.mdx` -> 2d64ee32da9aaa93b965e44cfc367bf3973a18e0 & `space.mdx` -> 4398dd1d49c7ffe582025b42cf42d4a11def9bb3
=> i18n(es): Updated `api-reference.mdx`, `netlify.mdx` & `space.mdx`

src/content/docs/es/tutorial/2-pages/2.mdx, src/content/docs/es/tutorial/4-layouts/2.mdx
Updated `tutorial/2-pages/2.mdx` & `tutorial/2-layouts/2.mdx`
=> i18n(es): Updated `tutorial/2-pages/2.mdx` & `tutorial/2-layouts/2.mdx`

src/content/docs/es/guides/view-transitions.mdx
Updated `view-transitions.mdx` based on this commit 62d78104e0a6e032acb424efa4bdac5730e275be
=> i18n(es): Updated `view-transitions.mdx`

src/content/docs/zh-cn/reference/image-service-reference.mdx
- translate reference/image-service-reference.mdx
=> i18n(zh-cn): translate reference/image-service-reference.mdx

src/content/docs/zh-cn/guides/cms/microcms.mdx
- translate guides/cms/microcms.mdx
=> i18n(zh-cn): translate guides/cms/microcms.mdx

src/content/docs/zh-cn/guides/deploy/vercel.mdx
Update `guides/deploy/vercel.mdx`
=> i18n(zh-cn): Update `guides/deploy/vercel.mdx`

src/content/docs/de/guides/typescript.mdx, src/content/docs/en/guides/typescript.mdx, src/content/docs/en/install/manual.mdx, src/content/docs/es/guides/typescript.mdx, src/content/docs/fr/install/manual.mdx, src/content/docs/it/install/manual.mdx, src/content/docs/ja/install/manual.mdx, src/content/docs/ko/install/manual.mdx, src/content/docs/pl/install/manual.mdx, src/content/docs/pt-br/guides/typescript.mdx, src/content/docs/pt-br/install/manual.mdx, src/content/docs/zh-cn/guides/typescript.mdx, src/content/docs/zh-cn/install/manual.mdx
- removing trailing commas in `tsconfig.json`
- Closes #4037
=> remove trailing comma in `tsconfig`

src/content/docs/en/recipes/docker.mdx
- Closes #4036 
- Improve Docker documentation according to feedback from Feedback Fish
=> Update documentation for Docker

scripts/error-docgen.mjs
Change to an internal scripts.
Relevant PR https://github.com/withastro/astro/pull/7949
It updates the script based on the structure of the object. I tested the script locally and it works. Please double check and merge it.
=> chore: update docgen error script

src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
=> Fix typo in `from-create-react-app.mdx`

src/content/docs/ja/editor-setup.mdx
- Remove leading whitespace.
- Update editor-setup.mdx.
- Corresponds to #3260.
=> i18n(ja): Update editor-setup.mdx

src/content/docs/pt-br/reference/error-reference.mdx
- Updated `reference/error-reference.mdx` based on commits in the original pages (see the commit history for more references)
=> i18n(pt-BR): Updated `reference/error-reference.mdx`

src/content/docs/en/guides/content-collections.mdx
- Changed `type: content` to `type: 'content'` as used everywhere
=> Fix inline code string with quotes

src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
=> Fix the typo command in `from-create-react-app.mdx`

src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx
- Translated content!
- Update netlify.mdx
=> i18n(zh-cn): Update netlify.mdx

src/content/docs/zh-cn/core-concepts/endpoints.mdx
Update example code since #3950
=> i18n(zh-cn): Update `core-concepts/endpoints.mdx`

src/content/docs/en/recipes.mdx
Adds 2 new community recipes:
- [Add username and password authentication with Lucia](https://lucia-auth.com/guidebook/sign-in-with-username-and-password/astro)
- [Add Github OAuth with Lucia](https://lucia-auth.com/guidebook/github-oauth/astro)
[Lucia](https://lucia-auth.com) is a TypeScript auth library that supports Astro
=> Add recipes on implementing authentication with Lucia

src/content/docs/es/guides/integrations-guide/lit.mdx, src/content/docs/es/recipes.mdx, src/content/docs/es/reference/api-reference.mdx
Updated `lit.mdx`, `recipes.mdx` & `api-reference.mdx`
`lit.mdx` -> [`acb8df1`](https://github.com/withastro/docs/commit/acb8df1f6cdfcaea6bfd436960fa506c1e80a0b6)
`recipes.mdx` -> [`a9c14ec`](https://github.com/withastro/docs/commit/a9c14ec003bba7a9fc4580d928d4f607bf3a855f) & [`96556b5`](https://github.com/withastro/docs/commit/96556b5aad9fbfe707c11be6eb45a77be585c1d9)
`api-reference.mdx` -> [`d051604`](https://github.com/withastro/docs/commit/d051604d4402e506fc7d3c5d98ad8a3e35e06307) & [`7ad75d4`](https://github.com/withastro/docs/commit/7ad75d4518401fe2320b49865b94f75f3d877cfe)
=> i18n(es): Updated `lit.mdx`, `recipes.mdx` & `api-reference.mdx`

src/content/docs/zh-cn/guides/integrations-guide/partytown.mdx
- translate guides/integrations-guide/partytown.mdx
=> i18n(zh-cn): translate guides/integrations-guide/partytown.mdx

src/content/docs/zh-cn/recipes.mdx
=> i18n(zh-cn): update recipes.mdx

src/content/docs/es/guides/integrations-guide/markdoc.mdx
Updated `markdoc.mdx` based on this commit 7986533f24ab018cf033ee0cdfcae058406406e2
=> i18n(es): Updated `markdoc.mdx`

src/content/docs/en/core-concepts/endpoints.mdx
Fixes the example of how to use the `APIRoute` type.
=> fix: APIRoute example

src/content/docs/en/guides/configuring-astro.mdx
- Closes https://github.com/withastro/astro/issues/6241
- The example in the [Environment Variables](https://docs.astro.build/en/guides/configuring-astro/#environment-variables) section was misleading because using `import.meta.env` is not supported in the config file. This value was always set to `'development'`, which was confusing users.
=> Update Environment Variables example

src/content/docs/en/recipes.mdx
- New community recipe added
- Added a community recipe for Integrating Sentry with Astro.
=> docs: :memo: integrate sentry with astro community recipe added

src/i18n/pt-br/README.md
Adds a PT-BR translation README
=> i18n(pt-BR): Add PT-BR translation README

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx
Update `integrations-guide/cloudflare.mdx` since #4162
=> i18n(zh-cn): Update `integrations-guide/cloudflare.mdx`

src/content/docs/zh-cn/guides/configuring-astro.mdx
Update `configuration-astro.mdx` since #4168
=> i18n(zh-cn): Update `configuration-astro.mdx`

src/content/docs/es/guides/integrations-guide/cloudflare.mdx, src/content/docs/es/recipes.mdx
Update `cloudflare.mdx` & `recipes.mdx`
`cloudflare.mdx` -> [`bb297aa`](https://github.com/withastro/docs/commit/bb297aa8454059fefd557630309ab4091d6f5dcc) & [`f275f8f`](https://github.com/withastro/docs/commit/f275f8f3e51bf04ae79e3217a1dcaf4bb90d49c8)
`recipes.mdx` -> [`f0b8c13`](https://github.com/withastro/docs/commit/f0b8c13b7122e08e564c8cf036e0ee8e21a1b036)
=> i18n(es): Update `cloudflare.mdx` & `recipes.mdx`

src/content/docs/it/guides/backend.mdx
translated `docs/guides/backend.mdx`
=> i18n(it): translate docs/guides/backend.mdx

src/content/docs/it/guides/backend/supabase.mdx
- Added Italian translation of `guides/backend/supabase`
=> i18n(it): Added translation of `guides/backend/supabase`

src/content/docs/it/concepts/islands.mdx
translated `docs/concepts/islands.mdx`
=> i18n(it): translate docs/concepts/islands.mdx

src/content/docs/pt-br/core-concepts/endpoints.mdx
Fix syntax on APIRoute example
Changes from e93972727b54b241893e9937d928f2edfb9a8499
=> i18n(pt-BR): Update `core-concepts/endpoints.mdx` translation

src/content/docs/pt-br/recipes.mdx
Added link to post about Sentry integration
Changes from f0b8c13b7122e08e564c8cf036e0ee8e21a1b036
=> i18n(pt-BR): Update `recipes.mdx` translation

src/content/docs/pt-br/guides/configuring-astro.mdx
Fix an example on the configuration (#4168)
Changes from 2e5da1bb6ef0c8b0f17b0b3aaa4fc53424d38f9b
=> i18n(pt-BR): Update `guides/configuring-astro.mdx` translation

src/content/docs/pt-br/reference/configuration-reference.mdx
- Document new `experimental.optimizeHoistedScript` feature.
Original changes from commit https://github.com/withastro/docs/commit/e6e76200f3f79765d22f0d1979f7766069acee6e
=> i18n(pt-BR): Update `configuration-reference.mdx` translation

src/content/docs/en/guides/environment-variables.mdx
- Closes #4030 
This PR adds an example of how to use default environment variables. Feel free to add suggestions if anything can be done better. The example is simple and small, so it's readable in mobile devices.
=> Add example for default environment variables

src/content/docs/en/guides/backend/google-firebase.mdx, src/content/docs/es/guides/backend/google-firebase.mdx, src/content/docs/zh-cn/guides/backend/google-firebase.mdx
- Minor content fixes 
Updated `yarn install` with `yarn add` while adding new packages.
=> Docs: updated yarn install with yarn add while adding new packages

src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx
Update `guides/integrations-guide/netlify.mdx` since #4192
=> i18n(zh-cn): Update `guides/integrations-guide/netlify.mdx`

src/content/docs/zh-cn/guides/configuring-astro.mdx, src/content/docs/zh-cn/guides/environment-variables.mdx
Update `guides/environment-variables.mdx` since #4188
=> i18n(zh-cn): Update `guides/environment-variables.mdx`

scripts/lib/translation-status/builder.ts
- all code on main was failing in eslint CI, adding this line for now, will make docs pass again
=> bug: disable formatting rule (temp)

src/content/docs/en/guides/backend/google-firebase.mdx
Rename of placeholder variables for Firebase .env so the user isn't left wondering why we're mapping `PRIVATE_KEY_ID`  to `YOUR_SPACE_ID`, etc.
Nope!
=> Fix FIREBASE_$VAR .env Naming

src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx, src/content/docs/zh-cn/guides/integrations-guide/sitemap.mdx
Update `integrations-guide/netfliy.mdx` and `integrations-guide/sitemap.mdx` since #4210
=> i18n(zh-cn): Update `integrations-guide/netfliy.mdx` and `integrations-guide/sitemap.mdx`

src/content/docs/ja/tutorial/5-astro-api/1.mdx
- Delete unnecessary text
- Remove en text on ja page
=> i18n(ja): Remove en text for ja

src/content/docs/en/tutorial/3-components/1.mdx
Update the link in `Resources` section in `tutorial/3-components/1.mdx`
=> Update the link in `Resources` section in `tutorial/3-components/1.mdx`

src/content/docs/en/reference/integrations-reference.mdx
Adds a more thorough example of how to add a client directive.
=> fix: show how client directives should be added

src/content/docs/pt-br/tutorial/1-setup/1.mdx, src/content/docs/pt-br/tutorial/1-setup/2.mdx, src/content/docs/pt-br/tutorial/1-setup/index.mdx
PT-BR translation for the first half of `setup-1`.
=> i18n(pt-BR): Translate tutorial `setup-1` first half

src/content/docs/pt-br/tutorial/1-setup/3.mdx, src/content/docs/pt-br/tutorial/1-setup/4.mdx, src/content/docs/pt-br/tutorial/1-setup/5.mdx
PT-BR translation for the second half of `setup-1`.
=> i18n(pt-BR): Translate tutorial `setup-1` second half

src/content/docs/pt-br/tutorial/2-pages/1.mdx, src/content/docs/pt-br/tutorial/2-pages/2.mdx, src/content/docs/pt-br/tutorial/2-pages/index.mdx
PT-BR translation for the first half of `pages-2`.
=> i18n(pt-BR): Translate tutorial `pages-2` first half 

src/content/docs/es/reference/integrations-reference.mdx, src/content/docs/es/tutorial/3-components/1.mdx
Updated `integrations-reference.mdx` & `/3-components/1.mdx` based on these 2 commits e2ab3a8d7d77b3c25074b9427b0a145d881c611f & d20654c7e9df486f97bf8ec2727820007d2dd959
=> i18n(es): Updated `integrations-reference.mdx` & `/3-components/1.mdx`

src/content/docs/zh-cn/guides/integrations-guide/react.mdx
Update `integrations-guide/react.mdx` since #4248
=> i18n(zh-cn): Update `integrations-guide/react.mdx`

src/content/docs/zh-cn/reference/integrations-reference.mdx
Update `reference/integrations-reference.mdx` since #4257
=> i18n(zh-cn): Update `reference/integrations-reference.mdx`

src/content/docs/zh-cn/guides/deploy/cloudflare.mdx
Update `guides/deploy/cloudflare.mdx` since #4249
=> i18n(zh-cn): Update `guides/deploy/cloudflare.mdx`

src/content/docs/zh-cn/tutorial/3-components/2.mdx
Update `zh-cn/tutorial/3-components/2.mdx`
=> i18n(zh-cn): Update `tutorial/3-components/2.mdx`

src/content/docs/pt-br/recipes/call-endpoints.mdx, src/content/docs/pt-br/recipes/external-links.mdx, src/content/docs/pt-br/recipes/sharing-state.mdx
Translation for the 3 recipes:
- https://docs.astro.build/pt-br/recipes/sharing-state/
- https://docs.astro.build/pt-br/recipes/call-endpoints/
- https://docs.astro.build/pt-br/recipes/external-links/
because they are small and mostly code, i included them all on this PR
=>  i18n(pt-BR): translation to recipes

src/content/docs/ja/recipes.mdx, src/i18n/ja/nav.ts
- Add recipes.mdx and update nav.ts.
=> i18n(ja): Add recipes.mdx and update nav.ts

src/content/docs/es/core-concepts/layouts.mdx, src/content/docs/es/guides/deploy/cloudflare.mdx, src/content/docs/es/guides/integrations-guide/react.mdx
Updated `layouts.mdx`,`cloudflare.mdx` & `react.mdx` based on these commits:
`layouts.mdx` -> bd877303a6ce3ef1ace9c85688df15cd1ec0a1f6 & e832eedb3c34c29630e753b6e46135d366fcf7f0
`cloudflare.mdx` -> b2fb8f8afabab3d113658e7e659cf3ca2e2a73dd
`react.mdx` -> 4b33a6231bb5cf245fc6904a1cb011c6a8ddc682
=> i18n(es): Updated `layouts.mdx`,`cloudflare.mdx` & `react.mdx`

src/content/docs/ja/getting-started.mdx
- Update getting-started.mdx.
- https://github.com/withastro/docs/pull/3688
=> i18n(ja): Update getting-started.mdx

src/content/docs/zh-cn/tutorial/3-components/1.mdx
Update `tutorial/3-components/1.mdx` since #4258
=> i18n(zh-cn): Update `tutorial/3-components/1.mdx`

src/i18n/ja/nav.ts, src/i18n/ja/ui.ts
=> i18n(ja): Update ui.ts and nav.ts

src/i18n/es/ui.ts
=> i18n(es): Update `ui.ts`

src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx
- Update `zh-cn/tutorial/5-astro-api/3.mdx`
- Follow up: #3784
=> i18n(zh-cn): Update routing pattern name and fix minor formatting in `tutorial/5-astro-api/3.mdx`

src/content/docs/zh-cn/tutorial/3-components/1.mdx
Update the content of the tip in `zh-cn/tutorial/3-components/1.mdx`
=> i18n(zh-cn): Update the content of the tip in `tutorial/3-components/1.mdx`

src/content/docs/en/guides/cms/keystatic.mdx
- Fix for malformed markdown link
=> Fix typo in Keystatic guide

src/content/docs/ja/reference/errors/static-redirect-not-available.mdx
- Add static-redirect-not-available.mdx.
=> i18n(ja): Add static-redirect-not-available.mdx

src/content/docs/ja/tutorial/3-components/1.mdx
- Update tutorial/3-components/1.mdx.
- https://github.com/withastro/docs/pull/4258
=> i18n(ja): Update tutorial/3-components/1.mdx

src/content/docs/en/reference/adapter-reference.mdx
This PR adds new content for the Adapters.
Implementation code PR https://github.com/withastro/astro/pull/7839 for reference. 
I discussed with @sarah11918 the level of detail for the new content. Please let me know if I need to change something. 
Plus, I would like to create a guide about the `edgeMiddleware`, because it requires more explanation. Where can I do that?
=> feat: document adapter features

src/content/docs/zh-cn/reference/image-service-reference.mdx
Update `reference/image-service-reference.mdx` since #4300
=> i18n(zh-cn): Update `reference/image-service-reference.mdx`

src/content/docs/pt-br/tutorial/2-pages/3.mdx, src/content/docs/pt-br/tutorial/2-pages/4.mdx, src/content/docs/pt-br/tutorial/2-pages/5.mdx
PT-BR translation for the second half of `pages-2`.
=> i18n(pt-BR): Translate tutorial `pages-2` second half

src/content/docs/pt-br/guides/deploy/cloudflare.mdx, src/content/docs/pt-br/guides/environment-variables.mdx
- Updated `guides/deploy/cloudflare.mdx` & `guides/environment-variables.mdx` based on changes in the original page (listed in the commit history).
=> i18n(pt-BR): Updated `guides/deploy/cloudflare.mdx` & `guides/environment-variables.mdx`

src/content/docs/pt-br/reference/configuration-reference.mdx
- Updated `reference/configuration-reference.mdx` based on changes in the original page (listed in the commit history).
=> i18n(pt-BR): Updated `reference/configuration-reference.mdx`

src/content/docs/pt-br/tutorial/4-layouts/1.mdx, src/content/docs/pt-br/tutorial/4-layouts/index.mdx
PT-BR translation for tutorial unit `4-layouts` first half
=> i18n(pt-BR): Translate tutorial `4-layouts` first half

src/content/docs/pt-br/tutorial/4-layouts/2.mdx, src/content/docs/pt-br/tutorial/4-layouts/3.mdx
PT-BR translation for unit `4-layouts` second half.
=> i18n(pt-BR): Translate tutorial `4-layouts` second half

src/content/docs/pt-br/tutorial/3-components/3.mdx, src/content/docs/pt-br/tutorial/3-components/4.mdx
PT-BR translation for unit `3-components` second half.
=> i18n(pt-BR): Translate tutorial `3-components` second half

src/content/docs/pt-br/tutorial/3-components/1.mdx, src/content/docs/pt-br/tutorial/3-components/2.mdx, src/content/docs/pt-br/tutorial/3-components/index.mdx
PT-BR translation for unit `3-components` first half
=> i18n(pt-BR): Translate tutorial `3-components` first half

src/content/docs/pt-br/reference/integrations-reference.mdx
- Updated `reference/integrations-reference.mdx` based on changes in the original page (listed in the commit history).
=> i18n(pt-BR): Updated `reference/integrations-reference.mdx`

src/content/docs/zh-cn/tutorial/3-components/3.mdx
Update `tutorial/3-components/3.mdx` since #4261
=> i18n(zh-cn): Update `tutorial/3-components/3.mdx`

src/content/docs/zh-cn/core-concepts/sharing-state.mdx
Update `core-concepts/sharing-state.mdx` since #4150
=> i18n(zh-cn): Update `core-concepts/sharing-state.mdx`

src/content/docs/pt-br/tutorial/5-astro-api/3.mdx, src/content/docs/pt-br/tutorial/5-astro-api/4.mdx
PT-BR translation for tutorial unit `5-astro-api` second half.
=> i18n(pt-BR): Translate tutorial `5-astro-api` second half

src/content/docs/pt-br/tutorial/6-islands/1.mdx, src/content/docs/pt-br/tutorial/6-islands/index.mdx
PT-BR translation for tutorial unit `6-islands` first half
=> i18n(pt-BR): Translate tutorial `6-islands` first half

src/content/docs/pt-br/tutorial/6-islands/2.mdx, src/content/docs/pt-br/tutorial/6-islands/3.mdx
PT-BR translation for tutorial unit `6-islands` second half
IT'S DONE
=> i18n(pt-BR): Translate tutorial `6-islands` second half

src/content/docs/pt-br/guides/view-transitions.mdx
- Updates `guides/view-transitions.mdx` based on changes in the original page.
=> i18n(pt-BR): Updated `guides/view-transitions.mdx`

src/content/docs/es/reference/image-service-reference.mdx
Fix typo in `image-service-reference`
=> i18n(es): Fix typo in `image-service-reference`

src/content/docs/en/guides/cms/tina-cms.mdx
- Changes to the docs site code 
Added a link to the TinaCMS + Astro Documentation page (a link to starter repo).
=> Added Community Resource Link

src/content/docs/zh-cn/guides/cms/tina-cms.mdx
Update `cms/tina-cms.mdx` since #4443
=> i18n(zh-cn): Update `cms/tina-cms.mdx`

src/content/docs/en/core-concepts/endpoints.mdx, src/content/docs/es/core-concepts/endpoints.mdx, src/content/docs/pt-br/core-concepts/endpoints.mdx, src/content/docs/zh-cn/core-concepts/endpoints.mdx
=> [i18nIgnore] Typo in `endpoints`

src/content/docs/en/recipes/docker.mdx
Improved Nginx configuration to handle and display a 404 error gracefully. 
Previously, the existing Nginx configuration was causing a 500 error when we attempted to access a non-existing page. With this update, Nginx will serve a custom 404.html page from the Astro site to provide a better user experience.
=> Update docker.mdx - Nginx 404 config

src/content/docs/de/getting-started.mdx
- updates the tip on the Getting Started page to refer to the new v3 changes instead of v2
=> i18n(de): update getting started tip for v3

src/content/docs/zh-cn/recipes.mdx
Update `recipes.mdx` since #4471
=> i18n(zh-cn): Update `recipes.mdx`

src/content/docs/zh-cn/guides/images.mdx, src/content/docs/zh-cn/guides/typescript.mdx, src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
Translate content added in #4446, #4447, #4495 and #4498.
=> i18n(zh-CN): Update translations in `v3.mdx`, `images.mdx` and `typescript.mdx`

src/content/docs/es/guides/upgrade-to/v3.mdx
Update `v3.mdx` based on these 3 commits 74ea897129b26b4146d1f22a80cfde7bace23a27, 6fda2c960ac425b7609bcf81c0cd4b5dbbdf84a8 & a4b7585d27e75cd0e5e351e0fe34ab1dadf4c407
=> i18n(es): Update `v3.mdx`

src/content/docs/es/reference/configuration-reference.mdx, src/content/docs/es/reference/image-service-reference.mdx
Updated `configuration-reference.mdx` & `image-service-reference.mdx` based on this commit 8bd5080562f395a7b80243019acb75262318e26a
=> i18n(es): Update `configuration-reference.mdx` & `image-service-reference.mdx`

src/content/docs/es/guides/images.mdx
Updated `images.mdx` based on these 2 commits 1d8d51dca8ebd9df74ca627280aaba020d4474ce & a4b7585d27e75cd0e5e351e0fe34ab1dadf4c407
=> i18n(es): Update `images.mdx`

src/content/docs/en/recipes/docker.mdx
I previously created PR #4191, which has since been merged. However, we overlooked a minor error in the description, which states:
> multi-stage builds, optimizes the build process for your site by only reinstalling the npm dependencies when the source code changes
but this statement is not correct! The advanced Dockerfile optimizes the build process by **not reinstallling** the npm dependencies when only the source code changes.
This PR fixes that description.
=> Fixing Docker multi-stage build description

src/content/docs/it/tutorial/0-introduction/1.mdx, src/content/docs/it/tutorial/0-introduction/index.mdx
- Translated tutorial introduction: index.mdx + 1.mdx
=> i18n(it): translated tutorial introduction

src/content/docs/zh-cn/guides/imports.mdx
Update `guides/imports.mdx` since #4515
=> i18n(zh-cn): Update `guides/imports.mdx`

src/content/docs/zh-cn/recipes/docker.mdx
Update `recipes/docker.mdx` since #4523
=> i18n(zh-cn): Update `recipes/docker.mdx`

src/content/docs/en/guides/server-side-rendering.mdx
Replace `diff` suffix in code block to `js` and set right line number for highlight.
=> Fix the missing highlight for example codes

src/content/docs/ja/guides/view-transitions.mdx
- Update view-transitions.mdx.
- https://github.com/withastro/docs/pull/4441
=> i18n(ja): Update view-transitions.mdx

src/content/docs/ja/recipes.mdx
- Update recipes.mdx.
- https://github.com/withastro/docs/pull/4526
- https://github.com/withastro/docs/pull/4499
=> i18n(ja): Update recipes.mdx

src/content/docs/zh-cn/guides/migrate-to-astro/from-create-react-app.mdx
update `guides/migrate-to-astro/from-create-react-app.mdx` since #4538
=> i18n(zh-cn): update `guides/migrate-to-astro/from-create-react-app.mdx`

src/content/docs/zh-cn/guides/cms/tina-cms.mdx
update `guides/cms/tina-cms.mdx` since #4563
=> i18n(zh-cn): update `guides/cms/tina-cms.mdx`

src/content/docs/zh-cn/tutorial/2-pages/1.mdx
- What does this PR change? change the sentence '将你的网站的更新版本部署并部署到线上' to '将你网站的更新版本部署到网上', become the old sentence is not suit for Chinese.
=> i18n(zh-CN):Update 1.mdx in chinese

src/content/docs/ja/guides/fonts.mdx
=> 18n(ja): Update fonts.mdx

src/content/docs/en/tutorial/1-setup/2.mdx
=> fix: typo in port number

src/content/docs/en/recipes/bun.mdx
This both "stubs"/scrubs the existing content as it's no longer entirely correct and helpful with Bun's new Astro support AND it marks `i18nReady:false` for the moment, since we expect @TheOtterlord to contribute more content shortly.
**When this page is updated again, please flip back to `true` so it will be translated!**
**Also, any existing Bun translations should be moved to `/old-translations/` so that everyone defaults to the English until the new docs are translated.**
=> [bun recipe] stubbin' stubbun

src/content/docs/es/guides/integrations-guide/cloudflare.mdx, src/content/docs/es/guides/integrations-guide/tailwind.mdx, src/content/docs/es/guides/integrations-guide/vercel.mdx
Update `tailwind.mdx`, `vercel.mdx` & `cloudflare.mdx` [`e984390`](https://github.com/withastro/docs/commit/e98439058164ee2643455114d2d1d1277e7e9d97)
=> i18n(es): Update `tailwind.mdx`, `vercel.mdx` & `cloudflare.mdx`

src/content/docs/zh-cn/reference/errors/missing-sharp.mdx
update `reference/errors/missing-sharp.mdx` since #4586
=> i18n(zh-cn): update `reference/errors/missing-sharp.mdx`

src/content/docs/zh-cn/recipes/build-forms-api.mdx
update `recipes/build-forms-api.mdx` since #4576
=> i18n(zh-cn): update `recipes/build-forms-api.mdx`

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx, src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx, src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
update `cloudflare.mdx`, `tailwind.mdx` and `vercel.mdx` guides since #4494
=> i18n(zh-cn): update `cloudflare.mdx`, `tailwind.mdx` and `vercel.mdx` guides

src/content/docs/zh-cn/guides/cms/storyblok.mdx
update `guides/cms/storyblok.mdx` since #4009, #4634
=> i18n(zh-cn): update `guides/cms/storyblok.mdx`

src/content/docs/zh-cn/guides/backend/xata.mdx
update `guides/backend/xata.mdx` since #4570
=> i18n(zh-cn): update `guides/backend/xata.mdx`

src/content/docs/ja/guides/deploy/buddy.mdx
- Add Japanese `guides/deploy/buddy.mdx`
=> i18n(ja): Add new guides/deploy/buddy.mdx translation

src/content/docs/zh-cn/recipes/bun.mdx
Translate the brand new `recipes/bun.mdx` since #4631
=> i18n(zh-cn): Translate the brand new `recipes/bun.mdx`

src/content/docs/es/guides/cms/storyblok.mdx
- 
Update `storyblok.mdx` [`f3e1ff0`](https://github.com/withastro/docs/commit/f3e1ff0ffa9f35db170b691d9ba7cce774102717)
The changes from commit [`bcebcef`](https://github.com/withastro/docs/commit/bcebcef797661b91a49f58f3de59fb6ffa0a2099) were not needed to be applied.
=> i18n(es): Update `storyblok.mdx`

src/content/docs/en/recipes/add-yaml-support.mdx
This changes `add-yaml-support.mdx` to `i18nReady: true`, so translators can... well, translate it.
=> Add `add-yaml-support.mdx` to our translation-ready pages

src/content/docs/fr/core-concepts/astro-pages.mdx
Updating the `astro-pages` page translation from this compare: https://github.com/withastro/docs/compare/19fa02fbe282556a2747f1db79933bea28f9ddea...cf7974088b2fe47c6c5740452ddbec00afb5a15d#diff-85eb439ff43e13e5b39e64643bcf1de374e59033ceee9ca99eb481f7b6d15951
=> i18n(fr): Updating `astro-pages` translation

src/content/docs/en/recipes/bun.mdx
- What does this PR change? I left this out the original guide, forgetting the Bun types package existed. This will help both  checks & editor tooling for TypeScript when using Bun's own runtime APIs.
=> Add bun-types to recipe

src/content/docs/zh-cn/recipes/bun.mdx
Update `bun.mdx` to match [`src/content/docs/en/recipes/bun.mdx`@`ed01461`](https://github.com/withastro/docs/blame/ed01461fc976e6f263b77054c91685c00c6fe765/src/content/docs/en/recipes/bun.mdx)
=> i18n(zh-CN): Update `bun.mdx` translation

src/content/docs/zh-cn/recipes/add-yaml-support.mdx
Translate `recipes/add-yaml-support.mdx` to Chinese.
=> i18n(zh-cn): Translate `recipes/add-yaml-support.mdx`

src/content/docs/es/recipes/add-yaml-support.mdx
Translate `add-yaml-support.mdx`
=> i18n(es): Translate `add-yaml-support.mdx`

src/content/docs/zh-cn/guides/migrate-to-astro/from-jekyll.mdx
update `guides/migrate-to-astro/from-jekyll.mdx` since #4572
=> i18n(zh-cn): update `guides/migrate-to-astro/from-jekyll.mdx`

src/content/docs/es/tutorial/6-islands/1.mdx
What kind of changes does this PR include?
Minor content fixes (broken links, typos, etc.)
Description
What does this PR change?: This PR fixes the punctuation in the user greeting spanish message to adhere to proper grammatical rules.
Did you change something visual?: N/A
=> Fix incorrect punctuation in greeting spanish message

src/content/docs/es/core-concepts/layouts.mdx
It's the same as yesterday's pull request #4668. The part should be highlighted, plus I've added spaces in a block which makes it not so close together and it's like in the English documentation.
=> i18n(es): Fixed highlighted layouts.mdx

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx
update `guides/integrations-guide/cloudflare.mdx` since #4665
=> i18n(zh-cn): update `guides/integrations-guide/cloudflare.mdx`

src/i18n/fr/ui.ts
I've finished translating the `ui.ts` file because its [translation was incomplete](https://i18n.docs.astro.build/).
=> i18n(fr): Updating ui elements translation

src/content/docs/en/tutorial/2-pages/2.mdx
Add a short, reassuring note when checking the preview of a new `.md` blog post (without yet any layout), that content may not appear properly formatted, but don't worry!
=> [tutorial] add note re: markdown rendering

src/content/docs/es/reference/errors/expected-image.mdx, src/content/docs/es/reference/errors/unsupported-config-transform-error.mdx
Updated `expected-image.mdx` & `unsupported-config-transform-error.mdx` based on this commit e75ecc8b0ae90c86421de0e113726342fb8c982a
=> i18n(es): Update `expected-image.mdx` & `unsupported-config-transform-error.mdx`

src/content/docs/es/guides/integrations-guide/vercel.mdx
Updated `vercel.mdx` based on these 2 commits 9a069be8145cd4fa4c1b7ef4c714661840449532 & 29c3a3eb2a17a550d382f0af005f418d54de9ca3
=> i18n(es): Update `vercel.mdx`

src/content/docs/es/reference/configuration-reference.mdx
Updated `configuration-reference.mdx` based on this commit d7b595797aed5c3740700af7d1aa82414fcac285
=> i18n(es): Update `configuration-reference.mdx`

src/content/docs/en/recipes/bun.mdx, src/content/docs/es/recipes/bun.mdx, src/content/docs/zh-cn/recipes/bun.mdx
- Added missing quotation marks for `types`
```ts title="tsconfig.json"
"compilerOptions": {
"types": ["bun-types"]
}
```
=> [i18nIgnore] Add missing quotation marks

src/components/tutorial/FeedbackButton.astro, src/content/docs/ru/concepts/why-astro.mdx
- Fix two ahref audit issues:
- multiple `h1` elements on the page
- bad link
=> fix ahref audit issues

src/content/docs/zh-tw/getting-started.mdx, src/i18n/zh-tw/ui.ts
- Update `getting-started.mdx`
- Update `ui.ts`
> Note: Some changes in `ui.ts` are made to follow the translation guide (withastro/docs#4696), which might be changed after the guide is done.
=> i18n(zh-TW): Update `getting-started.mdx` and `ui.ts`

src/content/docs/ja/reference/configuration-reference.mdx
- Update configuration-reference.mdx.
- https://github.com/withastro/docs/pull/4692
=> i18n(ja): Update configuration-reference.mdx

src/content/docs/de/guides/configuring-astro.mdx, src/content/docs/en/guides/configuring-astro.mdx, src/content/docs/es/guides/configuring-astro.mdx, src/content/docs/ja/guides/configuring-astro.mdx, src/content/docs/pt-br/guides/configuring-astro.mdx, src/content/docs/zh-cn/guides/configuring-astro.mdx
- Closes https://github.com/withastro/docs/issues/4469
=> [i18nIgnore] correct extension when overriding file names

.github/PULL_REQUEST_TEMPLATE.md
Updates the PR template to separate out the related PR issue and/or implementation PR so that it is easier to see and less one big chunk of commented out code.
=> [PR template]  separate section for related issues/PRs

src/content/docs/ja/reference/error-reference.mdx
- Update error-reference.mdx.
- https://github.com/withastro/docs/pull/4691
=> i18n(ja): Update error-reference.mdx

src/i18n/de/nav.ts
- Updated and then reordered the German translation for 'nav.ts' so that it matches the current order of navigation (used [English](https://github.com/withastro/docs/blob/ca7a3dd0a4a8456dd8aca4beb3729af3342a56f0/src/i18n/en/nav.ts) and [Spanish](https://github.com/withastro/docs/blob/ca7a3dd0a4a8456dd8aca4beb3729af3342a56f0/src/i18n/es/nav.ts) versions for reference)
=> i18n(de): Update `nav.ts` translation

src/content/docs/en/tutorial/2-pages/index.mdx, src/content/docs/en/tutorial/3-components/index.mdx, src/content/docs/en/tutorial/4-layouts/index.mdx, src/content/docs/en/tutorial/5-astro-api/index.mdx, src/content/docs/en/tutorial/6-islands/3.mdx, src/content/docs/en/tutorial/6-islands/index.mdx
This removes the mentions at the beginning of each unit to finding the tutorial code at that stage. For better maintenance, we've decided to only maintain the completed, final tutorial product.
Before:
After:
=> [tutorial] remove check-in to in-progress branches

src/content/docs/en/guides/integrations-guide/node.mdx
Changed subheading to follow the same patter as other integrations subheadings.
- Closes Issue https://github.com/withastro/docs/issues/4629
=> fix: fix subheading inconsistency

src/content/docs/zh-cn/guides/integrations-guide/node.mdx
update `guides/integrations-guide/node.mdx` since #4755
=> i18n(zh-cn): update `guides/integrations-guide/node.mdx`

src/content/docs/zh-cn/recipes/i18n.mdx
update `recipes/i18n.mdx` since #4771
=> i18n(zh-cn): update `recipes/i18n.mdx`

src/content/docs/fr/guides/integrations-guide/tailwind.mdx
- New Translated content tailwind mdx file
=> i18n(fr) Translated tailwind mdx

src/content/docs/es/tutorial/6-islands/1.mdx
Updated `/tutorial/6-islands/1.mdx` based on this commit 063395463fd1bb5c039c38943d083e3afebac044
=> i18n(es): Update `/tutorial/6-islands/1.mdx`

src/content/docs/ja/guides/images.mdx
- Update images.mdx.
- https://github.com/withastro/docs/pull/4724
=> i18n(ja): Update images.mdx

src/content/docs/es/recipes/call-endpoints.mdx
Simple Spanish writing fix for the JSON .stringify method at _src/content/docs/es/recipes/call-endpoints.msx_ .
=> Fixed JSON.stringify method typing error

src/content/docs/zh-cn/reference/error-reference.mdx, src/content/docs/zh-cn/reference/errors/image-not-found.mdx, src/content/docs/zh-cn/reference/errors/markdown-image-not-found.mdx, src/content/docs/zh-cn/reference/errors/no-image-metadata.mdx
update error reference docs since #4785
=> i18n(zh-cn): update error reference docs

src/content/docs/es/guides/data-fetching.mdx, src/content/docs/es/reference/api-reference.mdx
Updated `data-fetching,mdx & `api-reference.mdx` based on this commit 94b907ab245629462dc804836c5671b11d008d6f
=> i18n(es): Update `data-fetching.mdx` & `api-reference.mdx`

src/content/docs/es/guides/configuring-astro.mdx
The language used in the `astro.config.mjs` example has been corrected, it is currently set to `astro` and has been changed to `js`.
=> i18n(es): configuring-astro.mdx

src/content/docs/en/guides/deploy/github.mdx
- [`withastro/action@v1`](https://github.com/withastro/action/releases/tag/v1.0.0) has been released and is now the default.
- Inputs have been updated to reflect the latest changes
- [Original `withastro/action` PR](https://github.com/withastro/action/pull/27)
=> Update GitHub Pages deployment guide

src/content/docs/zh-cn/guides/deploy/github.mdx
update `guides/deploy/github.mdx` since #4817
=> i18n(zh-cn): update `guides/deploy/github.mdx`

src/content/docs/zh-cn/guides/data-fetching.mdx, src/content/docs/zh-cn/reference/api-reference.mdx
=> i18n(zh-cn): remove `h` import

src/content/docs/fr/guides/deploy/github.mdx
=> i18n(fr) Update deploy github guide

src/content/docs/fr/guides/data-fetching.mdx
=> i18n(fr) Update data-fetching file

scripts/generate-integration-pages.ts
- Updated the integration script for when it's running in CI:
- If it's the astro repo, use the env variables to select the right branch.
- Or if it's a fork!
- If the adapters repo, do the same.
=> Integration pages script, handle different CI repos

src/content/docs/en/guides/troubleshooting.mdx
Improved advice [WRITTEN BY CHRIS](https://discord.com/channels/830184174198718474/830184175176122389/1156664124542025748) re: using `console.log` and moved "debugging tips and tricks" higher up the page to make it easier to find!
=> [ troubleshooting.mdx] improved console.log example

src/content/docs/en/guides/deploy/deno.mdx, src/content/docs/en/guides/imports.mdx
- Fix deno adapter link
- https://github.com/withastro/docs/pull/4741
=> Fix deno adapter link

src/content/docs/ja/guides/imports.mdx
- Update imports.mdx.
- https://github.com/withastro/docs/pull/4838
=> i18n(ja): Update imports.mdx

src/content/docs/ja/guides/server-side-rendering.mdx
- Update server-side-rendering.mdx.
- https://github.com/withastro/docs/pull/4741
=> i18n(ja): Update server-side-rendering.mdx

src/content/docs/zh-cn/guides/integrations-guide/node.mdx, src/content/docs/zh-cn/guides/integrations-guide/partytown.mdx, src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
=> i18n(zh-CN): Update node.mdx, partytown.mdx, preact.mdx

src/content/docs/zh-cn/guides/deploy/deno.mdx, src/content/docs/zh-cn/guides/imports.mdx
=> i18n(zh-CN): Update imports.mdx, deploy/deno.mdx

src/content/docs/zh-cn/guides/integrations-guide/svelte.mdx, src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx, src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx, src/content/docs/zh-cn/guides/integrations-guide/vue.mdx
=> i18n(zh-CN): Update svelte.mdx, tailwind.mdx, vercel.mdx, vue.mdx

src/content/docs/zh-cn/guides/integrations-guide/lit.mdx, src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx, src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
=> i18n(zh-CN): Update lit.mdx, markdoc.mdx, mdx.mdx

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx
=> i18n(zh-CN): Update cloudflare.mdx

src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx, src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx
Update changes made in #4842 and #4843
=> i18n(zh-CN): Update alpinejs.mdx and netlify.mdx

src/content/docs/zh-cn/guides/integrations-guide/prefetch.mdx, src/content/docs/zh-cn/guides/integrations-guide/react.mdx, src/content/docs/zh-cn/guides/integrations-guide/sitemap.mdx, src/content/docs/zh-cn/guides/integrations-guide/solid-js.mdx
=> i18n(zh-CN): Update prefetch.mdx, react.mdx, sitemap.mdx, solid-js.mdx

src/content/docs/zh-cn/tutorial/5-astro-api/2.mdx
=> i18n(zh-CN): Update tutorial\5-astro-api\2.mdx

src/content/docs/en/guides/content-collections.mdx
Tell users to upgrade to `v3` or later instead
- Closes Issue #4869
Happened to have Discord open when you sent out the message lol
💖
=> [en-only] Tell users to upgrade to `v3` or later instead

src/content/docs/es/guides/integrations-guide/mdx.mdx, src/content/docs/es/guides/integrations-guide/node.mdx, src/content/docs/es/guides/integrations-guide/partytown.mdx
Updated `mdx`, `node` & `partytown` based on this commit 90ef084a50d5087d54ff1187a01ec9ef3e18b204
=> i18n(es): Update `mdx`, `node` & `partytown`

src/content/docs/es/guides/integrations-guide/preact.mdx, src/content/docs/es/guides/integrations-guide/prefetch.mdx, src/content/docs/es/guides/integrations-guide/react.mdx, src/content/docs/es/guides/integrations-guide/sitemap.mdx, src/content/docs/es/guides/integrations-guide/solid-js.mdx, src/content/docs/es/guides/integrations-guide/svelte.mdx, src/content/docs/es/guides/integrations-guide/tailwind.mdx, src/content/docs/es/guides/integrations-guide/vercel.mdx, src/content/docs/es/guides/integrations-guide/vue.mdx
Updated of multiple pages: `preact`, `prefetch`, `react`,  `sitemap`, `solid-js`, `svelte`, `tailwind`, `vue` & `vercel` based on this commit 90ef084a50d5087d54ff1187a01ec9ef3e18b204
=> i18n(es): Update of multiple pages

src/content/docs/en/guides/view-transitions.mdx
Replaced an undefined abbreviation that maybe unknown or misleading
=> write out the CSR abbreviation

src/content/docs/fr/guides/integrations-guide/tailwind.mdx
=> i18n(fr) Update tailwind.mdx

src/content/docs/es/tutorial/5-astro-api/1.mdx
- Minor content fixes(typo)
- Spanish tutorial error type (in english tutorial is well).
- Change double quotes in a sentence by single quotes.
- Open Issue #4800 
Here’s what will happen next:
1. Our GitHub bots will run to check your changes.
If they spot any broken links you will see some error messages on this PR.
Don’t hesitate to ask any questions if you’re not sure what these mean!
2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳
3. One or more of our maintainers will take a look and may ask you to make changes.
We try to be responsive, but don’t worry if this takes a day or two.
-->
=> typo: double quotes fix

src/content/docs/fr/getting-started.mdx, src/i18n/fr/README.md
- Update `getting-started` file to integrate the v3 banner
- Add a new word to glossary
- Replace a MD title by an HTML title to be iso with the rest of the docs
J'ai décidé d'intégrer `upgrade` au glossaire afin d'être sûr de sa tournure dans la documentation, afin qu'on utilise bien sa signification `mise à niveau` et non `améliorer`, n'hésitez pas à me faire part de vos retours :)
=> i18n(fr): Update `getting-started` translation and glossary

src/content/docs/en/guides/cms/strapi.mdx
Fixes a typo on the code example
=> fix example typo

src/content/docs/es/guides/testing.mdx
The following has been changed to conform to the English documentation.
- `index.spec.js` to `index.cy.js`.
- `:::tip[falla el test]` to `:::note[falla el test]`
- Updated `playwright.config.ts`
=> i18n(es): testing.mdx

src/content/docs/zh-cn/guides/cms/strapi.mdx
update `guides/cms/strapi.mdx`
#4903
=> i18n(zh-cn): update `guides/cms/strapi.mdx`

src/content/docs/es/guides/backend/google-firebase.mdx, src/content/docs/es/guides/cms/strapi.mdx, src/content/docs/es/tutorial/6-islands/3.mdx
Updated `google-firebase.mdx` & `6-islands/3.mdx` based on these commits:
- 41bb76de7833d1787595dc8cd6541b2334fde5c2
- d61fcd881d9f96330a5265fc22544c2a9861efdd
I'm taking part of the `hacktoberfest`. Could you please kindly add the `hacktoberfest-accepted` tag?
=> i18n(es): Update `google-firebase.mdx` & `6-islands/3.mdx`

.github/hacktoberfest.md
More explicit instructions to help us verify reviews!
=> i18n review instructions update for Hacktoberfest

src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
update `guides/upgrade-to/v3.mdx`
#4898
=> i18n(zh-cn): update `guides/upgrade-to/v3.mdx`

src/content/docs/zh-cn/tutorial/6-islands/3.mdx
update `tutorial/6-islands/3.mdx`
#4915
=> i18n(zh-cn): update `tutorial/6-islands/3.mdx`

src/content/docs/zh-cn/guides/cms/wordpress.mdx
update `guides/cms/wordpress.mdx`
#4909
=> i18n(zh-cn): update `guides/cms/wordpress.mdx`

src/content/docs/zh-cn/guides/backend/google-firebase.mdx
update `guides/backend/google-firebase.mdx`
=> i18n(zh-cn): update `guides/backend/google-firebase.mdx`

src/content/docs/zh-cn/reference/errors/collection-does-not-exist-error.mdx
update `reference/errors/collection-does-not-exist-error.mdx`
#4797
=> i18n(zh-cn): update `reference/errors/collection-does-not-exist-error.mdx`

src/content/docs/zh-tw/tutorial/1-setup/1.mdx, src/content/docs/zh-tw/tutorial/1-setup/2.mdx, src/content/docs/zh-tw/tutorial/1-setup/3.mdx, src/content/docs/zh-tw/tutorial/1-setup/4.mdx, src/content/docs/zh-tw/tutorial/1-setup/5.mdx, src/content/docs/zh-tw/tutorial/1-setup/index.mdx
- Translate `tutorial/1-setup/` into zh-tw (traditional Chinese)
- Follow the [issue](https://github.com/withastro/docs/pull/4743), this PR will be merged into the WIP branch of zh-tw turorial.
=> i18n(zh-tw): translate tutorial/1-setup into zh-tw

src/content/docs/es/guides/integrations-guide/preact.mdx
- [69c3ebd](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7#diff-050a5e9d3249cd33faea2e712b82960938528ae6e28d294f94bb20fe7b592e26)
=> i18n(es): update `preact.mdx`

src/content/docs/en/tutorial/5-astro-api/3.mdx, src/content/docs/en/tutorial/6-islands/1.mdx
Update the code example to match the question. The question asks "What would it look like to define an array of all your tags, then display them in a list on this page?", but the code example skips ahead to show the dynamic solution.
=> Docs - Tutorial Updates

src/content/docs/fr/reference/errors/collection-does-not-exist-error.mdx
I'm taking part in hacktobefest 🎊
=> i18n(fr): Update `collection-does-not-exist-error.mdx` translation

src/content/docs/es/tutorial/5-astro-api/3.mdx, src/content/docs/es/tutorial/6-islands/1.mdx
Updated `/6-islands/1.mdx` & `/5-astro-api/3.mdx` based on this commit 9ec3861c8f24aaeedebeb08e5f018e7213146faf
Could you please kindly add `hacktober-accepted` tag?
=> i18n(es): update `/6-islands/1.mdx` & `/5-astro-api/3.mdx`

src/content/docs/es/guides/environment-variables.mdx
- [69c3ebd](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7#diff-e5afe89538d79a61ba763693ce8702800a5489beac44d3c5be2317ee73924c0f)
=> i18n(es):  update `environment-variables.mdx`

src/content/docs/es/guides/environment-variables.mdx, src/content/docs/es/guides/integrations-guide/cloudflare.mdx
- [69c3ebd](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7)
=> i18n(es): update `cloudflare.mdx`

src/content/docs/es/guides/integrations-guide/alpinejs.mdx
- [69c3ebd](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7)
- [90ef084](https://github.com/withastro/docs/commit/90ef084a50d5087d54ff1187a01ec9ef3e18b204)
- [6f4636f](https://github.com/withastro/docs/commit/6f4636f24e0b434c2d09c5bc406af709de5a10ba)
=> i18n(es): update `alpinejs.mdx`

src/content/docs/zh-cn/guides/environment-variables.mdx, src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx, src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx, src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
update integration docs 
#4868
=> i18n(zh-cn): update integration docs 

src/content/docs/ja/guides/markdown-content.mdx
- Update markdown-content.mdx.
- https://github.com/withastro/docs/pull/3136
- https://github.com/withastro/docs/pull/3203
- https://github.com/withastro/docs/pull/3270
- https://github.com/withastro/docs/pull/3988
- https://github.com/withastro/docs/pull/4357
- https://github.com/withastro/docs/pull/4166
=> i18n(ja): Update markdown-content.mdx

src/content/docs/es/guides/view-transitions.mdx
- [3e971f7](https://github.com/withastro/docs/commit/3e971f7562df41555aa9cd4d0ce56df32145017c)
=> i18n(es): update `view-transitions.mdx`

contributor-guides/translating-astro-docs.md
update link that take you to the wrong path
N/A
=> docs: update broken link

src/content/docs/es/core-concepts/project-structure.mdx, src/content/docs/es/core-concepts/routing.mdx, src/content/docs/es/getting-started.mdx, src/content/docs/es/guides/configuring-astro.mdx
Fix typos `getting-started.mdx`, `project-structure.mdx`, `routing.mdx` & `configuring-astro.mdx`
=> i18n(es): Fix typos `getting-started.mdx`, `project-structure.mdx`, `routing.mdx` & `configuring-astro.mdx`

src/content/docs/es/guides/backend/google-firebase.mdx
- What does this PR change? 
- Update #4808
=> i18n(es): Update `google-firebase.mdx`

src/content/docs/es/guides/imports.mdx
Another type of markdown support has been added
=> i18n(es): Update imports.mdx

src/content/docs/es/guides/integrations-guide/cloudflare.mdx
Fixing typos in the Spanish translation. As well as the inline code tag for .astro.
I'm participating in the HacktoberFest
=> i18n(es): Fix typos `cloudflare.mdx`

src/content/docs/ja/guides/upgrade-to/v3.mdx
- Update v3.mdx.
- Corresponds to #4898 .
=> i18n(ja): Update v3.mdx

src/content/docs/fr/guides/deploy/google-firebase.mdx
This PR update links
I'm taking part in hacktobefest 🎊
=> i18n(fr): Update `google-firebase.mdx` translation

src/content/docs/it/tutorial/1-setup/4.mdx, src/content/docs/it/tutorial/1-setup/5.mdx
Added Italian translations for page 4 and 5 of the setup section of the tutorial
=> i18n(it): tutorial setup - page 4 and 5

src/content/docs/en/guides/view-transitions.mdx
- An example of using transitions router with a react component.
- A note about its behavior with server renders.
- https://github.com/withastro/astro/pull/8771
=> Usage of transitions router in a framework component

src/content/docs/de/guides/upgrade-to/v3.mdx
- Adding guides/upgrade-to/v3.mdx German translation.
I am participating in the Hacktoberfest! 🚀☕
=> i18n(de): Adding guides/upgrade-to/v3.mdx German translation

src/content/docs/es/guides/deploy/cloudflare.mdx
Updated `cloudflare.mdx` based on this commit 9c97b909cdba9c2b448a7dc3f61151e9e613098c
=> i18n(es): Update `cloudflare`

src/content/docs/zh-cn/guides/client-side-scripts.mdx
update `guides/client-side-scripts.mdx`
#4974
=> i18n(zh-cn): update `guides/client-side-scripts.mdx`

src/content/docs/ja/tutorial/2-pages/index.mdx
- Update tutorial/2-pages/index.mdx
- #4700 
- #4753
I'm in hackthoberfest! 🎃
=> i18n(ja): Update `tutorial/2-pages/index.mdx`

src/content/docs/en/recipes/modified-time.mdx
Modified Time recipe is now `i18nReady: true`
=> [i18nIgnore] Make `modified-time.mdx` ready for translation

.github/hacktoberfest.md, src/content/docs/de/guides/upgrade-to/v3.mdx
[Link](https://github.com/withastro/docs/pull/4995#pullrequestreview-1663444651) to review 🙌
=> Hacktober reviewed Translation PR #4995

src/content/docs/en/concepts/islands.mdx
- Fix small grammatical error in `en/concepts/islands`
=> Fix: grammatical error in `concepts/islands`

.github/hacktoberfest.md
Hello,
I'm participating to Hacktoberfest, thank you for the opportunity!
I made a review to the #4944 Translation PR.
=> Hacktoberfest Translation PR Review #4944

src/content/docs/en/guides/content-collections.mdx
the use of 'including' here suggested other supported formats. This should make it clear that only these two formats are currently supported.
- Closes #
=> Removing misleading 'including'

src/content/docs/de/guides/backend.mdx
What kind of changes does this PR include?
Translated content
Description
Add new German translation for backend.mdx
I'm taking part in Hacktoberfest 🙌
Related Issue / Implementation PR
Marked as missing in [Translation Tracker](https://i18n.docs.astro.build/)
=> i18n(de): Added backend.mdx docs translation

README.md, src/content/docs/en/guides/typescript.mdx
This improves the TS guide on global types declaration. For context:
- Suggested label: [improve documentation](https://github.com/withastro/docs/issues?q=is%3Aopen+label%3A%22improve+documentation%22+sort%3Aupdated-desc)
=> feat: improve typescript global types guide

README.md
Current Navigation for CONTRIBUTING.md through [Make a Fix or Contribution](https://github.com/withastro/docs#make-a-fix-or-contribution) points to 404
- This PR updates URL for CONTRIBUTING.md in README.md
Yes I am taking part in Hacktoberfest
- Closes #5064 
- Suggested label:  typo/link/grammar - quick fix!
=> fix: update URL for CONTRIBUTING.md in `README`

src/content/docs/es/guides/markdown-content.mdx
Updated `markdown-content` based on this commit b193c2cbf96af949e74907963fc8ad2b98e53e94
=> i18n(es): Update `markdown-content`

src/content/docs/es/guides/integrations-guide/cloudflare.mdx, src/content/docs/es/guides/integrations-guide/tailwind.mdx
Updated `cloudflare` & `tailwind` based on this commit ad0a45f8c966ea74b3a60f3afe0c220e9af66c39
=> i18n(es): Update `cloudflare` & `tailwind`

src/content/docs/zh-cn/guides/styling.mdx
update `guides/styling.mdx`
#4910
=> i18n(zh-cn): update `guides/styling.mdx`

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx, src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx
update integrations docs
#5016
=> i18n(zh-cn): update integrations docs

src/content/docs/fr/concepts/islands.mdx
Update the `concepts/islands.mdx` file translation.
I am participating in the Hacktoberfest!
=> i18n(fr): Update the translation of the `concepts/islands.mdx` file

src/i18n/es/nav.ts
=> i18n(es): Fix typos in `nav.ts`

src/i18n/es/nav.ts
=> i18n(es): Update `nav.ts`

src/content/docs/fr/guides/deploy/cloudflare.mdx
i18n(fr): Add `deploy/cloudflare.mdx` in French language
I am participating in the Hacktoberfest! 🎃
- [i18n(fr): Add deploy/cloudflare.mdx in French language](https://github.com/withastro/docs/commit/fb3897ac1d575b57bf00aeffc5a784544f42c40c)
Related issues & labels (optional)
Related to this issue https://github.com/withastro/docs/issues/4984, don't close it.
=> i18n(fr): Add `deploy/cloudflare.mdx` in French language

src/content/docs/zh-cn/guides/cms/buttercms.mdx, src/content/docs/zh-cn/guides/cms/frontmatter-cms.mdx, src/content/docs/zh-cn/guides/cms/payload.mdx, src/content/docs/zh-cn/guides/deploy/space.mdx, src/content/docs/zh-cn/guides/integrations-guide.mdx, src/content/docs/zh-cn/guides/middleware.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/zh-cn/guides/rss.mdx, src/content/docs/zh-cn/guides/server-side-rendering.mdx, src/content/docs/zh-cn/guides/upgrade-to/v3.mdx, src/content/docs/zh-cn/recipes/add-yaml-support.mdx, src/content/docs/zh-cn/recipes/i18n.mdx, src/content/docs/zh-cn/tutorial/3-components/4.mdx, src/content/docs/zh-cn/tutorial/5-astro-api/1.mdx
Update `zh-cn` docs pages based on https://github.com/withastro/docs/pull/4805, https://github.com/withastro/docs/commit/91a669dc3c0ca0a53d86709cc9c95ebf9242c8f8.
=> i18n(zh-CN): update identation and formatting.

src/content/docs/zh-cn/reference/api-reference.mdx
update `reference/api-reference.mdx`
#4677
=> i18n(zh-cn): update `reference/api-reference.mdx`

src/content/docs/es/recipes/i18n.mdx, src/content/docs/es/tutorial/3-components/4.mdx, src/content/docs/es/tutorial/5-astro-api/1.mdx
Updated `i18n`, `3-components/4` & `5-astro-api/1`
=> i18n(es): Update `i18n`, `3-components/4` & `5-astro-api/1`

src/content/docs/es/guides/rss.mdx, src/content/docs/es/guides/server-side-rendering.mdx, src/content/docs/es/guides/upgrade-to/v3.mdx, src/content/docs/es/recipes/add-yaml-support.mdx
Updated `rss`, `server-side-rendering`, `v3` & `add-yaml-support`
=> i18n(es): Update `rss`, `server-side-rendering`, `v3` & `add-yaml-support`

src/content/docs/es/guides/deploy/space.mdx, src/content/docs/es/guides/integrations-guide.mdx, src/content/docs/es/guides/middleware.mdx
Updated `space`, `integrations-guide` & `middleware` 
=> i18n(es): Update `space`, `integrations-guide` & `middleware`

src/content/docs/es/guides/cms/buttercms.mdx, src/content/docs/es/guides/cms/frontmatter-cms.mdx, src/content/docs/es/guides/cms/payload.mdx
Updated `buttercms`, `frontmatter-cms` & `payload` 
=> i18n(es): Update `buttercms`, `frontmatter-cms` & `payload`

contributor-guides/writing-and-style-guide.md, src/content/docs/ja/editor-setup.mdx, src/content/docs/ja/guides/images.mdx
This PR fix the typo seen in various files
```pseudo
backround > background
ReactImgage > ReactImage
Extentions > Extensions
```
- Closes #
=> Chore :Fix typos in multiple files

src/content/docs/es/guides/deploy/netlify.mdx
Update `netlify` based on this commit 3d1a57fa584d184032a968a92de9c5b93663b8e1
=> i18n(es): Update `/deploy/netlify`

src/content/docs/es/guides/deploy/github.mdx
Updated `github` based on this commit 2ba7eb99e2c980e4ccce09ad667fd12a2863868a
=> i18n(es): Update `github`

src/i18n/hi/nav.ts
This PR performs a translation change in the left sidebar
Yes, I am taking part in Hacktoberfest 2023
This PR does not resolves an Issue but updates nav.ts from [Translation Tracker](https://i18n.docs.astro.build/) under Hindi Dropdown
=> i18n(hi): update `nav.ts` for hindi translated content

src/content/docs/en/core-concepts/astro-pages.mdx
typo: change `<! DOCTYPE html>` to `<!DOCTYPE html>`
=> typo: change `<! DOCTYPE html>` to `<!DOCTYPE html>`

src/content/docs/en/recipes/build-custom-img-component.mdx
Add the missing space to fix the indentation issue.
None
=> Fix the indentation typo for code block

.github/hacktoberfest.md
[Link](https://github.com/withastro/docs/pull/4928#discussion_r1349638608) to review comment
=> Hacktoberfest reviewed a translation PR #4928

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/es/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
Future proofing some links! Instead of going to a specific spot on the page (which will be near the top of the new page anyway), just goes to the page itself! Will make other PRs link checks pass
=> [i18nIgnore] remove specific heading from links that will change

src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx, src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx, src/content/docs/zh-cn/guides/integrations-guide/vue.mdx
=> i18n(zh-cn): update integration docs

src/content/docs/en/guides/cms/keystatic.mdx
Add tab component to tip in Keystatic page
- Closes #
=> Add tab component to Keystatic CMS guide

src/content/docs/en/core-concepts/astro-pages.mdx
=> Fix small typo

src/content/docs/en/guides/middleware.mdx
This PR updates a reference to `MiddlewareResponseHandler` in the docs. Previously, the text before an example referred to `MiddlewareResponseHandler` as `MiddlewareRequestHandler`, but this change should make the text match with the code sample that follows.
N/A
=> Update MiddlewareResponseHandler docs reference

src/content/docs/en/reference/dev-overlay-plugin-reference.mdx
https://github.com/withastro/astro/pull/8968 updates the event names and add a new event, this is the according docs for that!
https://github.com/withastro/astro/pull/8968
=> feat: add new events and update event names for the overlay

src/i18n/ko/README.md
update korean translation guide glossary based on discussion in the #5068
=> i18n(ko): Update translation guide

src/content/docs/zh-cn/reference/errors/no-adapter-installed.mdx
- Update no-adapter-installed.mdx
- https://github.com/withastro/docs/pull/5224
=> i18n(zh-cn): Update no-adapter-installed.mdx

src/content/docs/zh-cn/guides/view-transitions.mdx
- Update view-transitions.mdx
- https://github.com/withastro/docs/commit/0763a9db68d1b91e328f9b5de705a87d6802e272
=> i18n(zh-cn): Update view-transitions.mdx

src/content/docs/zh-cn/recipes/build-custom-img-component.mdx
- Update build-custom-img-component.mdx
- https://github.com/withastro/docs/pull/5237
=> i18n(zh-cn): Update build-custom-img-component.mdx

src/content/docs/zh-cn/guides/configuring-astro.mdx, src/content/docs/zh-cn/guides/environment-variables.mdx
- Update environment-variables.mdx
- Update configuring-astro.mdx
- Fix #4110
- https://github.com/withastro/docs/issues/4110
- https://github.com/withastro/docs/pull/5222
- https://github.com/withastro/docs/pull/5258
=> i18n(zh-cn): Update environment-variables.mdx & configuring-astro.mdx

src/content/docs/fr/recipes.mdx
Adding  `recipes.mdx` in French language
=> i18n(fr): Add `recipes.mdx` in French language

src/content/docs/zh-cn/guides/content-collections.mdx
Update `guides/content-collections.mdx`
#5234
=> i18n(zh-cn): Update `guides/content-collections.mdx`

src/content/docs/es/guides/configuring-astro.mdx
Updated `configuring-astro` based on this commit 6254ac195412c97c4079ebf5131517c0f3b6c958
=> i18n(es): Update `configuring-astro`

.github/PULL_REQUEST_TEMPLATE.md
Removed comments of hacktoberfest from PR Template
- Closes #5273 
=> Remove Hacktoberfest mention from PR template

src/content/docs/es/recipes/build-custom-img-component.mdx
Updated `build-custom-image-component` based on these 2 commits 0b15f9ad841d51fa23e2c60cb6a0f8a8ebde8aa8 & 6cf14fb681ae086ec0017c25f39efeb62d6fd96a
=> i18n(es): Update `build-custom-image-component`

src/content/docs/es/guides/middleware.mdx
Updated `middleware` based on this commit 54447097ee69b7897f9107fc6d6dabaef146671f
=> i18n(es): Update `middleware`

src/content/docs/es/guides/integrations-guide/vercel.mdx
Updated `vercel`based on this commit 65103ed882e659a2827b2b58221221a270ae26af
=> i18n(es): Update `vercel`

src/content/docs/es/guides/view-transitions.mdx, src/content/docs/es/reference/api-reference.mdx
`api-reference.mdx` [`2be7e9f`](https://github.com/withastro/docs/commit/2be7e9f20c3b2550cef9a2747ec303a2c6c24fe2), [`3433810`](https://github.com/withastro/docs/commit/34338107bd809b9255fed094f14dbbd22e92b084) & [`a9a2779`](https://github.com/withastro/docs/commit/a9a27799a59aa390931e48ed1ca39693efc6eea4)
`view-transitions` Fix typo
=> i18n(es): Update `api-reference.mdx` & `view-transitions.mdx`

src/content/docs/ko/recipes/bun.mdx
- Translated `recipes/bun.mdx`
`i18n/ko` 디렉토리의 가이드와 기존에 번역된 페이지들을 참고하여 번역해 봤습니다. 기본 규칙 중 쉬운 이해를 우선시하기 위해 최대한 단순하고 일관성 있게 풀어봤는데, 어색한 부분이 있을 수 있습니다. 피드백 부탁드려요.
=> i18n(ko-KR): Add new `bun.mdx` translation

src/content/docs/en/guides/markdown-content.mdx
Adds a note on how to link to headings in pages
related to https://github.com/withastro/starlight/pull/1010
=> add note on linking to headings

src/content/docs/en/tutorials/add-view-transitions.mdx
Fixing a typo (controling -> controlling)
- Closes #
=> fix controling -> controlling

src/content/docs/en/reference/integrations-reference.mdx
Adds a new section and a link to an article on how to build your own Astro integration
=> [integrations-reference] add Community Resource section and link

src/content/docs/es/core-concepts/astro-components.mdx, src/content/docs/es/guides/cms/storyblok.mdx, src/content/docs/es/guides/cms/tina-cms.mdx
Updated `astro-components`, `storyblok` & `tina-cms` based on these commit:
- 6d176e584381f7528f87080d94218686eae3d49b
- 22282e22fd2d4c9f053c9d78414b153b0f3bec5f
- 56aa7792222373ac41009225cd13fe83b1703d2f
=> i18n(es): Update `astro-components`, `storyblok` & `tina-cms`

src/content/docs/fr/guides/configuring-astro.mdx
Update with minor correction for the last version to configuring-astro.mdx L120 and L158
=> i18n(fr) Update translation configuring-astro.mdx

src/content/docs/fr/core-concepts/astro-components.mdx
Minor update for fr translation L260
=> i18n(fr) Update fr translation astro-components.mdx

src/content/docs/fr/guides/environment-variables.mdx
Update minor translation #5222
=> i18n(fr) Update environment-variables.mdx

src/content/docs/fr/guides/deploy/gitlab.mdx
Update tranlation with code exemple and minor update for french translation.
=> i18n(fr) Update fr translation gitlab.mdx

src/content/docs/fr/guides/deploy/github.mdx
Minor update to fr translation file github.mdx L32
=> i18n(fr) Minor update github.mdx

src/content/docs/fr/guides/cms/wordpress.mdx
Minor update with #5244
L178-179
=> i18n(fr) Update wordpress.mdx

src/content/docs/fr/guides/backend/xata.mdx
=> i18n(fr) Update xata.mdx

src/content/docs/fr/guides/middleware.mdx
=> i18n(fr) Update `middleware.mdx`

src/content/docs/fr/editor-setup.mdx
Update minor translation with #5284 and #5363
L39 &78
=> i18n(fr) editor-setup.mdx

src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
Update translation with PRs #4980 #5016 #5118 #5133
=> i18n(fr) Update french translation `cloudflare.mdx`

src/content/docs/es/editor-setup.mdx
Updated `editor-setup` based on this commit e40533d3dd77fd95a39990520cc7919d3824bea8
=> i18n(es): Update `editor-setup`

src/content/docs/fr/core-concepts/astro-pages.mdx
Update documentation with multiple fix and add partial page
=> i18n(fr) Update fr translation astro-pages.mdx

src/content/docs/zh-cn/reference/cli-reference.mdx
update `reference/cli-reference.mdx`
#5268
=> i18n(zh-cn): update `reference/cli-reference.mdx`

src/content/docs/zh-cn/guides/view-transitions.mdx
update `guides/view-transitions.mdx`
#5299
=> i18n(zh-cn): update `guides/view-transitions.mdx`

src/content/docs/zh-cn/guides/integrations-guide/prefetch.mdx, src/content/docs/zh-cn/guides/prefetch.mdx, src/i18n/zh-cn/nav.ts
- translate `guides/prefetch.mdx` to Chinese version.
- update `guides/integrations-guide/prefetch.mdx`.
Note that **this PR should be merged after #5349** 
#5324
=> i18n(zh-cn): translate `guides/prefetch.mdx` and update `guides/integrations-guide/prefetch.mdx`

src/content/docs/zh-cn/recipes/streaming-improve-page-performance.mdx
translate `recipes/streaming-improve-page-performance.mdx` to Chinese version.
#4667
=> i18n(zh-cn): translate `recipes/streaming-improve-page-performance.mdx`

src/i18n/fr/nav.ts
Update Nav.ts with last version
=> i18n(fr) Update `nav.ts`

src/content/docs/fr/recipes.mdx
=> i18n(fr) Update `recipes.mdx`

src/content/docs/fr/guides/deploy/space.mdx
=> i18n(fr) Update `space.mdx`

README.md, contributor-guides/translating-astro-docs.md
Removing Hacktoberfest text in `README.md` file and in `contributor-guides/translating-astro-docs.md`. I leaved `.github/hacktoberfest.md` file for futures events. 💜
- Closes #
=> Removing Hacktoberfest 2023 text 💜

src/content/docs/en/core-concepts/astro-components.mdx, src/content/docs/en/core-concepts/astro-pages.mdx, src/content/docs/en/core-concepts/astro-syntax.mdx, src/content/docs/en/core-concepts/routing.mdx, src/content/docs/en/core-concepts/sharing-state.mdx, src/content/docs/en/guides/images.mdx, src/content/docs/en/guides/imports.mdx, src/content/docs/en/guides/internationalization.mdx, src/content/docs/en/reference/api-reference.mdx, src/content/docs/en/tutorial/2-pages/3.mdx
Some changes to code snippet syntax (mostly titles) in preparation for Hippo's proposed changes to Expressive Code.
Ideally, we'd replace every code snippet in docs with the `title=""` syntax, but this is the minimum viable change for now to let @hippotastic  make his changes.
=> [code-example-syntax] hippo-proof code examples

src/content/docs/en/reference/configuration-reference.mdx, src/content/docs/zh-cn/reference/configuration-reference.mdx
=> [i18nIgnore] typo fix - default

src/content/docs/es/reference/integrations-reference.mdx
Updated `integrations-reference` based on this commit c53ff7937a38185d63612981f8a870df75f8dc85
=> i18n(es): Update `integrations-reference`

src/content/docs/es/tutorial/2-pages/3.mdx
Updated `/2-pages/3` based on this commit 5ce13aadf0b14a5f3cc2e201b4d7e16f61fcab86
=> i18n(es): Update `/2-pages/3`

src/content/docs/es/reference/api-reference.mdx
Updated `api-reference` based on this commit 5ce13aadf0b14a5f3cc2e201b4d7e16f61fcab86
=> i18n(es): Update `api-reference`

src/content/docs/es/guides/imports.mdx
Update `imports` based on this commit 5ce13aadf0b14a5f3cc2e201b4d7e16f61fcab86
=> i18n(es): Update `imports`

src/content/docs/es/core-concepts/routing.mdx, src/content/docs/es/core-concepts/sharing-state.mdx, src/content/docs/es/guides/images.mdx
Updated `routing`, `sharing-state` & `images` based on this commit 5ce13aadf0b14a5f3cc2e201b4d7e16f61fcab86
=> i18n(es): Update `routing`, `sharing-state` & `images`

src/content/docs/es/core-concepts/astro-components.mdx, src/content/docs/es/core-concepts/astro-pages.mdx, src/content/docs/es/core-concepts/astro-syntax.mdx
Updated `astro-components`, `astro-pages` & `astro-syntax` based on this commit 5ce13aadf0b14a5f3cc2e201b4d7e16f61fcab86
=> i18n(es): Update `astro-components`, `astro-pages` & `astro-syntax`

src/content/docs/fr/guides/environment-variables.mdx
Minor fix commit f765b7c PR #5417 for `environment-variables.mdx` file
=> i18n(fr) fix translation with last PR #5417 `environment-variables.mdx`

src/content/docs/fr/recipes/modified-time.mdx
Add french translation for modified-time.mdx file
=> i18(fr) Create `modified-time.mdx`

src/content/docs/fr/recipes/build-custom-img-component.mdx
Add french translation for build-custom-img-component.mdx file
=> i18n(fr) Create `build-custom-img-component.mdx`

src/content/docs/fr/recipes/add-yaml-support.mdx
Add french translation for add-yaml-support.mdx
=> i18n(fr) Create `add-yaml-support.mdx`

src/content/docs/fr/guides/cms/frontmatter-cms.mdx
Add french translation for frontmatter-cms.mdx file
=> i18n(fr) Create `frontmatter-cms.mdx`

src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
=> i18n(fr) Update `cloudflare.mdx`

src/content/docs/zh-cn/guides/server-side-rendering.mdx
update `guides/server-side-rendering.mdx`
#5430
=> i18n(zh-cn): update `guides/server-side-rendering.mdx`

src/content/docs/zh-cn/guides/integrations-guide/svelte.mdx
update `guides/integrations-guide/svelte.mdx`
#5429
=> i18n(zh-cn): update `guides/integrations-guide/svelte.mdx`

src/content/docs/fr/recipes/streaming-improve-page-performance.mdx
Add french translation for streaming-improve-page-performance.mdx file
=> i18n(fr) Create `streaming-improve-page-performance.mdx`

src/content/docs/en/reference/integrations-reference.mdx
Typo, fix spelling for SerializedSSRManifest
=> fix(type_no-ticket): Typo, fix spelling for SerializedSSRManifest

src/content/docs/es/concepts/why-astro.mdx
=> i18n(es): Fix typo in `why-astro.mdx`

src/content/docs/es/guides/environment-variables.mdx, src/content/docs/es/guides/images.mdx, src/content/docs/es/reference/api-reference.mdx
`environment-variables.mdx` [`f765b7c`](https://github.com/withastro/docs/commit/f765b7c634cf8dc4d5b04bda0838894011c2b606)
`images.mdx` & `api-reference.mdx` [`30e7e3e`](https://github.com/withastro/docs/commit/30e7e3e033800e1f971d46c7363a552aa37b982a#diff-9ea5d63bc29a5a013378b352f2b77fffd61f773692ff6c329a3cc9292552ac23)
=> i18n(es): Update `environment-variables.mdx`, `images.mdx` & `api-reference.mdx`

src/content/docs/es/guides/images.mdx
=> i18n(es): Update `images`

src/content/docs/es/core-concepts/astro-components.mdx
=> i18n(es): Update `astro-components`

src/content/docs/fr/reference/error-reference.mdx
Update transltion for error-reference.mdx file
=> i18n(fr) Update `error-reference.mdx`

src/content/docs/es/recipes/dynamically-importing-images.mdx
Translated `dynamically-importing-images` to spanish
=> i18n(es): Translate `dynamically-importing-images`

.github/workflows/welcome-bot.yml
This PR fixes the first interaction workflow action which has been [failing](https://github.com/withastro/docs/actions/workflows/welcome-bot.yml) for a few days now.
- We tested the change in the Starlight repo before pushing it here.
- https://github.com/withastro/starlight/pull/1139 contains all the informations regarding the change.
- The main visual difference is that the comment is now a comment in the PR instead of a review comment.
- Here is [an exemple](https://github.com/withastro/starlight/pull/1152#issuecomment-1826513291) of such a comment in the Starlight repo.
=> ci: fix first interaction action

src/content/docs/en/guides/internationalization.mdx
This reverts commit 1582697ebacad27cee94f02ac1e865a39097281b.
- Closes #
=> Revert "feat(i18n): add documentation for refined locales"

src/content/docs/en/guides/integrations-guide.mdx
Upgrade Integrations guide with both Manual and Automatic install
=> add integration upgrade guide

.vscode/extensions.json
Add MDX extension to recommended plugins. So it's easier to install when we're sharing codespaces!
=> chore: add MDX to recommended plugins

src/content/docs/en/guides/deploy/netlify.mdx
1. adatper > adapter
2. Updated second adapter link to `https://docs.astro.build/en/guides/integrations-guide/netlify/` like the one above
3. Removed spaces from start of `npm install @astrojs/netlify` block
=> [i18nIgnore] Update netlify.mdx

src/content/docs/en/guides/internationalization.mdx, src/content/docs/en/guides/typescript.mdx, src/content/docs/en/recipes/bun.mdx, src/content/docs/en/reference/error-reference.mdx, src/content/docs/en/reference/errors/get-static-paths-removed-rsshelper.mdx, src/content/docs/en/reference/errors/image-missing-alt.mdx, src/content/docs/es/guides/integrations-guide/netlify.mdx, src/content/docs/es/guides/middleware.mdx, src/content/docs/es/reference/adapter-reference.mdx, src/content/docs/es/reference/api-reference.mdx
Just updates the glossary branch to match main, to help with an existing PR
- Closes #
=> update glossary branch

src/content/docs/fr/guides/cms/strapi.mdx
Add `cms/strapi.mdx` in French language
No related issues. /
=> i18n(fr): Add `cms/strapi.mdx` in French language

contributor-guides/translating-astro-docs.md
This PR adds a new section in the internationalization guide, answering the long asked "What should I translate next". The view count stats are based on our page analytics.
=> "What to translate next?" guide

src/content/docs/ja/guides/deploy/microsoft-azure.mdx
I have reflected the following updates to the Japanese page of `/guides/deploy/microsoft-azure.mdx`.
- https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/microsoft-azure.mdx?since=2023-01-16T14:25:51.000Z
- https://github.com/withastro/docs/pull/2912
- https://github.com/withastro/docs/pull/5057
- Closes #
=> i18n(ja): Update `/guides/deploy/microsoft-azure.mdx`

contributor-guides/glossary.md
Add the first terms to start the glossary page.
- Related to: #5035
=> glossary: add “Components” and "Islands"

src/content/docs/fr/core-concepts/astro-syntax.mdx, src/content/docs/fr/core-concepts/sharing-state.mdx, src/content/docs/fr/editor-setup.mdx
Very very minor update
- astro-syntax
- sharing-state
- editor setup
=> i18n(fr) Update minor multiple files

src/content/docs/fr/concepts/islands.mdx, src/content/docs/fr/guides/migrate-to-astro.mdx
=> i18n(fr) Update islands.mdx

src/content/docs/fr/contribute.mdx
Update with last version
I have deliberately not removed the various links at the bottom of the page pointing to FR help.
=> i18n(fr) Update contribute.mdx

src/content/docs/fr/guides/cms/storyblok.mdx
Add `guides/cms/storyblok` in French language
i18n label.
=> i18n(fr): Add `guides/cms/storyblok` in French language

src/content/docs/fr/tutorials/add-content-collections.mdx
Add french translation for add-content-collections file
=> i18n(fr) Create `add-content-collections.mdx`

src/content/docs/en/guides/upgrade-to/v4.mdx
Since `i18n` still needs configuring, just not within `experimental`, this adds the config at the root level to show where it goes.
- Closes #
=> [v4 upgrade] show i18n config added back

src/content/docs/fr/guides/cms/kontent-ai.mdx
Add guides/cms/kontent-ai in French language
=> i18n(fr): Add guides/cms/kontent-ai in French language

src/content/docs/fr/guides/cms/ghost.mdx
Add french translation for `ghost.mdx`
=> i18n(fr) Add french translation for `ghost.mdx`

src/content/docs/fr/guides/cms/statamic.mdx
Add french translation for `statamic.mdx`
=> i18n(fr) Add french translation for `statamic.mdx`

src/content/docs/fr/guides/cms/hygraph.mdx
i18n(fr) Add french translation for `hygraph.mdx`
=> i18n(fr) Add french translation for `hygraph.mdx`

src/content/docs/fr/core-concepts/framework-components.mdx
Update french translation for framework-components file
=> i18n(fr) Update french translation `framework-components.mdx`

src/content/docs/en/guides/upgrade-to/v4.mdx
- Condensing spaces between two or more lines into one line
- Shorten long links
- Closes #
=> fix(docs): shorten meaninglessly long code

src/content/docs/pt-br/getting-started.mdx
This PR uncomments the 4.0 banner in the PT-BR `getting-started` page.
=> i18n(pt-BR): Uncomment 4.0 banner

src/content/docs/es/getting-started.mdx
This page is missing attributes in the frontmatter to remove the TOC, editUrl and Next.
=> i18n(es): Fix `getting-started.mdx`

src/content/docs/es/concepts/why-astro.mdx
Pequeño error ortográfico
- Closes #
=> i18n(es): Update why-astro.mdx

src/content/docs/es/guides/configuring-astro.mdx
- [dd07cd5](https://github.com/withastro/docs/commit/dd07cd595001c35cb40a9787af3cd6a1b669bb4e)
- [0a62d07](https://github.com/withastro/docs/commit/0a62d07c9ed95d7846cfc3bb4a4bab97310e78e2#diff-7b8e14eba72baf08b3e043b5209fd9a26286c82337757b4e69f1bec5d933aaaa)
=> i18n(es): update `configuring-astro.mdx`

src/content/docs/es/core-concepts/astro-components.mdx
- [3dfbaf4](https://github.com/withastro/docs/commit/3dfbaf43121c5eb6f560e3a777813e12e1c1b3f7)
=> i18n(es): update `astro-components.mdx`

src/content/docs/es/contribute.mdx
- [cb85996](https://github.com/withastro/docs/commit/cb85996cc5137e9126a9190f804e3a1f4d1ad8aa#diff-72966c51e2aea4840294ab0cd021072fbbc81f2fc9a094305687e2ec4ea0729c)
=> i18n(es): update `contribute.mdx`

src/content/docs/es/guides/integrations-guide/mdx.mdx
- [af207cc](https://github.com/withastro/docs/commit/af207cc6b6a33b8bd36926d1d5409e9d6fb77c49#diff-3614dd525e1ec7062f2a33621e0f0d124a86bbd8e1494e14c995baba0328b250)
=> i18n(es): update `mdx.mdx`

src/content/docs/es/guides/deploy.mdx
- [524a986](https://github.com/withastro/docs/commit/524a9866682d2cd35fab4caef8d690cc89df832d#diff-6eb18230889b3d6c9a8e5fd02c62d046a6d338820af26c3dfd1a131fa878d5bf)
=> i18n(es): update `deploy.mdx`

src/content/docs/es/guides/deploy/deno.mdx
- [9165fd7](https://github.com/withastro/docs/commit/9165fd746c62981a525adbbaa31db5f191c628cb)
=> i18n(es): update `deno.mdx`

src/content/docs/es/guides/deploy/github.mdx
- Fix typo
- [56ba19d](https://github.com/withastro/docs/commit/56ba19dd4f81c65617f2cb40c7aee55ba96472a8#diff-3bf8939d031116668fc00fb2c41ceef305576a7b89b25bc00cce4a1c10d3f2a3)
=> i18n(es): update `github.mdx` (typo)

src/content/docs/es/guides/deploy/aws.mdx
- [b297812](https://github.com/withastro/docs/commit/b297812a8900f8fd5f447165be1842a420ba790c)
=> i18n(es): update `aws.mdx`

src/content/docs/es/guides/middleware.mdx
- [a668483](https://github.com/withastro/docs/commit/a668483de3bf957392508d6cc2a86eeb1b1f3fa0)
- [5e4f070](https://github.com/withastro/docs/commit/5e4f070637f51a772a8d029a4967c2c505329ae6)
=> i18n(es): update `middleware.mdx`

src/content/docs/es/guides/migrate-to-astro/from-create-react-app.mdx
- Fix typos
- [cbefaaa](https://github.com/withastro/docs/commit/cbefaaa0a3792dbbf65664082c02bbf4f1526c05)
=> i18n(es): update `from-create-react-app.mdx` (typos)

src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx
Hi team, watching the commits history for this page I saw that is already updated. For the next time were I should announce the issue? Thanks! 🙌
- [56ba19d](https://github.com/withastro/docs/commit/56ba19dd4f81c65617f2cb40c7aee55ba96472a8)
- [b5f2233](https://github.com/withastro/docs/commit/b5f2233786266b122f63fa144026fbd9e00df544#diff-8495ce8f95e3ba48b1c49c87bed82602dd9d1ffa06eb70a596a3757b834380a0)
- [7eae012](https://github.com/withastro/docs/commit/7eae012ac8f3a9dfe405a35938ae1a91a41ef4de#diff-8495ce8f95e3ba48b1c49c87bed82602dd9d1ffa06eb70a596a3757b834380a0)
=> i18n(es): already updated `from-gatsby.mdx`

src/content/docs/es/guides/typescript.mdx
- Fix typos
- [cf9f93c](https://github.com/withastro/docs/commit/cf9f93cde979a2e4c05757a52fc0898798c9a532#diff-3326736e17eb78ddba38aacdf7709e5a5a4f2bc05d0db8d5fcf54088c6c0d532)
- [a5026b1](https://github.com/withastro/docs/commit/a5026b110fafa916f9a05f1c15b01df4ab4679c5)
- [0a62d07](https://github.com/withastro/docs/commit/0a62d07c9ed95d7846cfc3bb4a4bab97310e78e2#diff-3326736e17eb78ddba38aacdf7709e5a5a4f2bc05d0db8d5fcf54088c6c0d532)
=> i18n(es): update `typescript.mdx`

src/content/docs/es/reference/errors/image-missing-alt.mdx
- [9f0607d](https://github.com/withastro/docs/commit/9f0607d3552d8e12b629bce35033867c7dec6f35#diff-8fddfc0568890034334a885701122324badfab3d2741e7a26ad79949214ffbd4)
- [a4fe776](https://github.com/withastro/docs/commit/a4fe77693b97db1ed76f72e251824c0c17631ee9#diff-58c8e26996fa6d7a150c29e6c2563a87e8bb45ec90db85ddd36f15d4708ab2fe)
=> i18n(es): update `image-missing-alt.mdx`

src/content/docs/es/recipes/dynamically-importing-images.mdx
- Fix typo
- [3795132](https://github.com/withastro/docs/commit/3795132d12d83e847be04bf2eae7fc632d337538#diff-5718624c7c5962b4313676b70b451b0d73980eba993bba980bc02252d989811d)
- [9bd0908](https://github.com/withastro/docs/commit/9bd09082d1538cb9944bb3d2f279dfa7a37d8ae1)
=> i18n(es): update `dynamically-importing-images.mdx` (typo)

src/content/docs/es/tutorial/2-pages/1.mdx
- Fix typo
- [56ba19d](https://github.com/withastro/docs/commit/56ba19dd4f81c65617f2cb40c7aee55ba96472a8#diff-1e1b8a7670431b932fc9fc439dce7f76c79b4624d6f1bcf67508f9d7d7668c95)
=> i18n(es): update `1.mdx` (typo)

src/content/docs/es/tutorials/add-content-collections.mdx
- [2beab0c](https://github.com/withastro/docs/commit/2beab0cc52569b5fb7b1599ac8f22c846221d22d)
- [0a62d07](https://github.com/withastro/docs/commit/0a62d07c9ed95d7846cfc3bb4a4bab97310e78e2#diff-ec9625e9b89360bd7a29d0d392017cbb704e8890a12534044ca2374dddb9fdb5)
=> i18n(es): update `add-content-collections.mdx`

src/content/docs/es/reference/adapter-reference.mdx
- [b2874b8](https://github.com/withastro/docs/commit/b2874b8d86118b5e35680a2b9e515fafa1aceae3)
=> i18n(es): update `adapter-reference.mdx`

src/content/docs/es/guides/integrations-guide/node.mdx
- Note: Please check line 196 if is well translated!
- [0867a54](https://github.com/withastro/docs/commit/0867a543d02d6afd0751af7c212801461a7d0eb2)
=> i18n(es): update `node.mdx`

src/content/docs/es/guides/migrate-to-astro/from-nuxtjs.mdx
- [5e255fb](https://github.com/withastro/docs/commit/5e255fb9d2cca36e595cefd076f19a6d6e37bf95)
=> i18n(es): update `from-nuxtjs.mdx`

.github/ISSUE_TEMPLATE/CONTENT.yml
This sets the StackBlitz field as not required, plus tweaks some wording to make this issue for reporting incorrect content. I'll add another template itself specifically for new content requests, so this one does not have to pull double duty.
- Closes #
=> [issue template] - remove Stackblitz requirement for content issues

.github/ISSUE_TEMPLATE/BUGS.yml
Only updates the title of the bug issue template, making it clear this is not about content!
- Closes #
=> [bug issue template] updates title - not about content!

.github/ISSUE_TEMPLATE/REQUEST.yml
This creates a new issues template specifically for new content requests, separate from reporting incorrect content
- Closes #
=> [issue template] Create REQUEST

src/content/docs/es/guides/integrations-guide/alpinejs.mdx, src/content/docs/es/guides/integrations-guide/lit.mdx, src/content/docs/es/guides/integrations-guide/markdoc.mdx, src/content/docs/es/recipes/sharing-state.mdx
`sharing-state.mdx` [`3795132`](https://github.com/withastro/docs/commit/3795132d12d83e847be04bf2eae7fc632d337538)
`alpinejs.mdx` [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c)
`lit.mdx` [`90ef084`](https://github.com/withastro/docs/commit/90ef084a50d5087d54ff1187a01ec9ef3e18b204#diff-b1bfd3239c9a42cffa1d43d2769131514b54731e9cd0d83f00f4e4d37771fdc6) & [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c)
`markdoc.mdx` [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c#diff-458e8e35fd99d649500911d9c81832d87acef32df3ffa5fb73d198dc7889dccd)
=> i18n(es): Update `sharing-state.mdx`, `alpinejs.mdx`, `lit.mdx` & `markdoc.mdx`

src/content/docs/es/guides/integrations-guide/lit.mdx, src/content/docs/es/guides/integrations-guide/mdx.mdx, src/content/docs/es/guides/integrations-guide/node.mdx, src/content/docs/es/guides/integrations-guide/partytown.mdx, src/content/docs/es/guides/integrations-guide/preact.mdx, src/content/docs/es/guides/integrations-guide/react.mdx, src/content/docs/es/guides/integrations-guide/svelte.mdx, src/content/docs/es/guides/integrations-guide/vue.mdx
`mdx.mdx` [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c)
`node.mdx` [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c#diff-2baf0337989d9330951e059b8c2f826e965ad359e8e4fa988e3ba52940ed7bde)
`partytown.mdx` [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c#diff-592f0f9cd6a36d0b3669dc6b46ffe75ea24f13a80cc31659d9f856ea5435c4d6)
`preact.mdx` [`69c3ebd`](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7#diff-050a5e9d3249cd33faea2e712b82960938528ae6e28d294f94bb20fe7b592e26) & [`57eab37`](https://github.com/withastro/docs/commit/57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c#diff-050a5e9d3249cd33faea2e712b82960938528ae6e28d294f94bb20fe7b5 …
=> i18n(es): Update `mdx.mdx`, `node.mdx`, `partytown.mdx`, `preact.mdx`, `react.mdx` & fix typos

src/content/docs/es/guides/integrations-guide/mdx.mdx, src/content/docs/es/guides/integrations-guide/netlify.mdx
Updated `mdx` & `netlify` based on this commit 57eab3751f07e9b51e3ea3e8ffb5e5b09df4040c
=> i18n(es): Update `mdx` and `netlify`

src/content/docs/en/guides/markdown-content.mdx, src/content/docs/es/guides/markdown-content.mdx, src/content/docs/fr/guides/markdown-content.mdx, src/content/docs/zh-cn/guides/markdown-content.mdx
Your link is out of date and unavailable.
N/A
=> [i18nIgnore] fix shikiji dual themes docs link

src/content/docs/es/guides/cms/wordpress.mdx
Update `wordpress` based on this commit 8baf01e2c3e47a7877dcb19c22b7091a4b5a8a1c
=> i18n(es): Update `wordpress`

src/content/docs/es/reference/errors/middleware-cant-be-loaded.mdx
Translate `middleware-cant-be-loaded.mdx`
=> i18n(es): Translate `middleware-cant-be-loaded.mdx`

src/content/docs/es/guides/integrations-guide/prefetch.mdx
I forgot to add the translation to the block in this [PR](https://github.com/withastro/docs/pull/5842)
=> i18n(es): Fix typo in `prefetch.mdx`

src/content/docs/zh-cn/reference/configuration-reference.mdx
- Update configuration-reference.mdx
- https://github.com/withastro/docs/pull/5836
=> i18n(zh-cn): Update configuration-reference.mdx

src/components/starlight/MarkdownContent.astro, src/i18n/en/ui.ts
This PR updates the following titles
- Other to More integrations
- [Integration preview](https://docs-git-more-integrations-astrodotbuild.vercel.app/en/guides/integrations-guide/preact/#changelog)
=> Update other integration title

src/content/docs/ko/guides/typescript.mdx
-  update `typescript.mdx`
- #5765
- Closes #
=> i18n(ko-KR): update `typescript.mdx`

src/content/docs/ko/core-concepts/layouts.mdx
- update `layouts.mdx`
- #5698 
- Closes #
=> i18n(ko-KR): update `layouts.mdx`

src/content/docs/ko/core-concepts/astro-pages.mdx
- update `astro-pages.mdx`
- #5765 
- Closes #
=> i18n(ko-KR): update `astro-pages.mdx`

src/content/docs/zh-cn/guides/deploy/heroku.mdx
Update `guides/deploy/heroku.mdx`
Upstream PR:
- #5904
- Closes #
=> i18n(zh-cn): Update `guides/deploy/heroku.mdx`
