withastro/docs

- src/content/docs/en/recipes/build-custom-img-component.mdx
Local images have to be imported, we don't support linking to images in `public` like that at the moment
> fix: import images inside the custom image component recipe

- src/content/docs/en/guides/cms/wordpress.mdx
Adds my name to resources, as it wasn't listed
Added my name to an article listed in WordPress resources that I wrote, but I wasn't mentioned by name (every other resource has its author mentioned by name).
> Adds me as an author for an article that was already listed

- src/content/docs/en/guides/configuring-astro.mdx
Fix import meta env reference in configuring-astro.mdx
Fix https://github.com/withastro/docs/issues/4110
- Closes #4110
- https://github.com/withastro/docs/pull/5222
> Fix import meta env reference in configuring-astro.mdx

- src/content/docs/en/reference/cli-reference.mdx
What the title says, the reference was outdated for Astro 3
> fix: `astro check` watches all files, not just Astro files

- src/content/docs/es/guides/integrations-guide/markdoc.mdx
- src/content/docs/es/guides/integrations-guide/mdx.mdx
- src/content/docs/es/guides/integrations-guide/vue.mdx
Updated `markdoc`, `mdx` & `vue` based on this commit 3a466f740bdf9375d57122e8cba4344467027912
> i18n(es): Update `markdoc`, `mdx` & `vue`

- src/content/docs/en/editor-setup.mdx
- src/content/docs/en/guides/backend/google-firebase.mdx
- src/content/docs/en/guides/backend/supabase.mdx
- src/content/docs/en/guides/cms/buttercms.mdx
- src/content/docs/en/guides/cms/contentful.mdx
- src/content/docs/en/guides/cms/ghost.mdx
- src/content/docs/en/guides/cms/keystatic.mdx
- src/content/docs/en/guides/cms/kontent-ai.mdx
- src/content/docs/en/guides/cms/storyblok.mdx
- src/content/docs/en/guides/configuring-astro.mdx
- src/content/docs/en/guides/deploy/cloudflare.mdx
- src/content/docs/en/guides/fonts.mdx
- src/content/docs/en/guides/images.mdx
- src/content/docs/en/guides/rss.mdx
- src/content/docs/en/guides/server-side-rendering.mdx
- src/content/docs/en/guides/typescript.mdx
- src/content/docs/en/guides/upgrade-to/v2.mdx
- src/content/docs/en/guides/upgrade-to/v3.mdx
- src/content/docs/en/install/manual.mdx
- src/content/docs/en/recipes/modified-time.mdx
- src/content/docs/en/recipes/reading-time.mdx
- src/content/docs/en/recipes/sharing-state.mdx
- src/content/docs/en/reference/api-reference.mdx
- src/content/docs/en/tutorial/5-astro-api/4.mdx
- src/content/docs/en/tutorials/add-content-collections.mdx
- src/content/docs/en/tutorials/add-view-transitions.mdx
I found that many package installation snippets use `pnpm install <pkg>` instead of `pnpm add <pkg>`.
According to pnpm's documentation:
- [`pnpm install`](https://pnpm.io/cli/install) is used for installing **all** dependencies for a project
- [`pnpm add <pkg>`](https://pnpm.io/cli/add) is used for installing certain package(s)
This PR changes those to the latter ✍️
> [i18nIgnore] Fix pnpm command typos

- src/content/docs/en/reference/image-service-reference.mdx
Hi, [this section](https://docs.astro.build/en/reference/image-service-reference/#local-services) links to a file that was moved in this [PR](https://github.com/withastro/astro/commit/47ea310f01d06ed1562c790bec348718a2fa8277#diff-21b2586f5098a49b303cfb11dc00fb9ba1083168994d488f6bac1243b8d29253)
broken url:
https://github.com/withastro/astro/blob/main/packages/astro/src/assets/image-endpoint.ts
new url:
https://github.com/withastro/astro/blob/main/packages/astro/src/assets/endpoint/generic.ts
> fix: broken link in `reference/image-service-reference`

- src/content/docs/en/recipes/tailwind-rendered-markdown.mdx
- fix `pnpm install -D` to `pnpm add -D`
- trim some tail spaces
- Closes #
> Fix typo in installing tailwind typography and trim tail spaces

- src/content/docs/en/recipes.mdx
_Adding a new "Community Recipe" with the following details -_
**Title -** How to Send Any Data to Your RSS Feed? A Guide with Astro + RSS 
**URL -** https://aritraroy.live/tutorial/blogs/2023/how-to-send-any-data-to-rss-feed/
_What does it do?_
According to [@astrojs/rss](https://www.npmjs.com/package/@astrojs/rss#rssfeeditem) documentation, one can send these specific items to RSS feed -
**Required Parameters**
• title: title of the blog post
• description: description of the post
• pubDate: publication date of the blog post
• link: link to the blog post
**Optional Parameters**
• categories: Catergories related to the post in an array
• author: email address of the author of the post
• commentsUrl: URL of a web page that contains comments on the item
• source: An object that defines the …
> Adding new "Community Recipe" about Astro + RSS

- scripts/docgen.mjs
- src/content/docs/en/reference/configuration-reference.mdx
- Updates our configuration reference generation script to add support for `@kind h4` (and other heading levels) in addition to our existing `@kind heading` support.
- Accompanies https://github.com/withastro/astro/pull/9052 and already includes a preview of what those updates would look like with this new version of the script.
- Also refactored this script a bunch because it was kind of gnarly how some of that was written.
> Refactor Configuration Reference docgen script

- src/content/docs/en/editor-setup.mdx
Instructions to configure Emacs to work with Astro Language Server
None
> Adds configuring instructions for Emacs

- src/content/docs/fr/guides/deploy/netlify.mdx
Update with last modif #5113 and #4859
> i18n(fr) Update Fr translation netlify.mdx

- src/content/docs/en/guides/content-collections.mdx
Removed unused import in `content-collections`
> [i18nIgnore] remove unused import in content collections guide

- src/content/docs/en/guides/markdown-content.mdx
Mention shikiji in *Markdown & MDX* page, because astro uses shikiji since pull [#8502](https://github.com/withastro/astro/pull/8502)
> Mention shikiji in Markdown & MDX page

- src/content/docs/en/guides/cms/tina-cms.mdx
Before the change, docs in `tina-cms.mdx` stated that after executing `yarn dlx @tinacms/cli@latest init` one should be able to see the `admin` folder in the root of the project - that doesn't happen until execution of the updated `dev` script.
- Suggested label: [improve documentation](https://github.com/withastro/docs/labels/improve%20documentation)
> Tina CMS: clarify admin folder info

- src/content/docs/zh-cn/editor-setup.mdx
update `editor-setup.mdx`
#5284
#5363
> i18n(zh-cn): update `editor-setup.mdx`

- src/i18n/hi/nav.ts
Description (required)
This PR performs a translation change in the documentation navigation bar
Suggested label: i18n
> i18n (hi): update `nav.ts` for hindi translated content

- src/content/docs/fr/guides/deploy/microsoft-azure.mdx
> i18n(fr) Update `microsoft-azure.mdx`

- src/content/docs/fr/reference/errors/collection-does-not-exist-error.mdx
> i18n(fr) Update `collection-does-not-exist-error.mdx`

- src/content/docs/en/guides/images.mdx
- src/content/docs/en/reference/api-reference.mdx
Remove experimental flag from the Picture component.
> Remove experimental badge from the Picture component

- src/content/docs/en/guides/view-transitions.mdx
- Spotted two small typos in the new View Transitions docs for 3.6! This fixes them.
> fix: Two little v3.6 typos

- src/content/docs/en/guides/server-side-rendering.mdx
This PR fixes the broken import statement in the [Manual Install](https://docs.astro.build/en/guides/server-side-rendering/#manual-install) section of [On⁠-⁠demand Rendering Adapters](https://docs.astro.build/en/guides/server-side-rendering).
It causes an error when starting the development server.
```
[astro] Unable to load your Astro config
error   Failed to resolve entry for package "@astrojs/vercel". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@astrojs/vercel" package
```
> Fix broken import statement in server-side-rendering.mdx

- public/robots.txt
- src/pages/robots.txt.ts
`robots.txt` can be a simple file in `/public` rather than an endpoint. This also unblocks https://github.com/withastro/astro/pull/9181 which we'll be removing support for returning simple objects from endpoints. 
- Closes n/a
- Suggested label: n/a
> Simplify robots.txt

- src/content/docs/en/reference/api-reference.mdx
Add the missing '(' in function definition on code example.
> Fix typo in code example

- src/content/docs/en/guides/images.mdx
This PR adds the missing `sizes` attribute to Image's widths example.
- Closes #5473
> Add missing `sizes` attribute to Image's widths example

- src/content/docs/zh-cn/concepts/why-astro.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-hugo.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-pelican.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-wordpress.mdx
Update translation based on #5428
`<strong>`s are used in some places because markdown bold syntax are not being rendered correctly in certain cases, example:
**Astro 是一个集多功能于一体的 Web 框架。**它内置包含了你构建网站所需的一切。
> i18n(zh-CN): Update why-astro.mdx, and 10 other pages with link to it

- src/content/docs/en/guides/deploy/aws.mdx
I have added instructions on how to handle the most common error responses.
By default, CloudFront will show an ugly XML error message saying that the content was not found (when the URL doesn't exist) and a 403 message when the content is private.
These two custom error messages were the ones I encountered when I tried to deploy my Astro blog to AWS following the official docs.
> Add instructions on how to setup CloudFront Error Pages

- src/content/docs/en/guides/internationalization.mdx
RFC change: https://github.com/withastro/roadmap/pull/734/commits/089253d317e4327ee4e3b93eb303ddc28859952b
This PR updates the page to use the new `routing` object. The old `routingStrategy` has been removed.
Here's how the old configuration is mapped to the new one
```diff
export default defineConfig({
experimental: {
i18n: {
-          routingStrategy: "prefix-always",
+          routing: {
+              prefixDefaultLocale: true,
+          }  
}
}
})
```
```diff
export default defineConfig({
experimental: {
i18n: {
-          routingStrategy: "prefix-other-locales",
+          routing: {
+              prefixDefaultLocale: false,
+          }  
}
}
})
```
Also, it's worth noting that `routing` contains a key called [`strategy`](https://github.com/withastro/astro/blob/8deeb313ca98f74a9 …
> refactor(i18n): remove `routingStrategy` in favour of `routing` object

- src/content/docs/en/reference/api-reference.mdx
Update the title for one of the methods that was missing the `` ` ` ``.
Since I was already fixing a markdown formatting I also:
- Removed a chunk of newlines that were unnecessary
- Aligned a table
- Added `;` to the imports that were missing
- Removed unnecessary indentation from one of the examples
> Fix stylying and formatting on API reference

- src/content/docs/en/core-concepts/astro-syntax.mdx
- src/content/docs/en/core-concepts/framework-components.mdx
- src/content/docs/en/core-concepts/sharing-state.mdx
- src/content/docs/en/guides/cms/builderio.mdx
- src/content/docs/en/guides/cms/caisy.mdx
- src/content/docs/en/guides/cms/keystatic.mdx
- src/content/docs/en/guides/cms/kontent-ai.mdx
- src/content/docs/en/guides/deploy.mdx
- src/content/docs/en/guides/deploy/github.mdx
- src/content/docs/en/guides/images.mdx
- src/content/docs/en/guides/imports.mdx
- src/content/docs/en/guides/integrations-guide.mdx
- src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/en/guides/testing.mdx
- src/content/docs/en/guides/view-transitions.mdx
- src/content/docs/en/reference/cli-reference.mdx
- src/content/docs/en/tutorial/1-setup/1.mdx
- src/content/docs/en/tutorial/1-setup/5.mdx
- src/content/docs/en/tutorial/1-setup/index.mdx
- src/content/docs/en/tutorial/2-pages/1.mdx
- src/content/docs/en/tutorial/3-components/3.mdx
- src/content/docs/en/tutorial/3-components/4.mdx
- src/content/docs/en/tutorial/4-layouts/2.mdx
- src/content/docs/en/tutorial/5-astro-api/4.mdx
This changes all of our aside (e.g. "tip", "note" etc.) custom titles to sentence case.
The Astro Docs site automatically converts all text written as a `:::note[custom title]` to uppercase, as a design choice.
Starlight, however, displays text exactly as written. Moreover, the design choice for Starlight is to NOT show this text as all upper case. So, existing asides had to be checked to make sure all custom title text was written in sentence case.
We used @vasfvitor 's find and replace algorithm to convert every custom title to sentence case, then manually inspected for proper nouns (e.g. Astro, StackBlitz, RSS) and manually added capitals.
> updates all aside text to sentence case

- src/content/docs/en/getting-started.mdx
Update `getting-started.mdx` file in `src/content/docs/en/` to correct the link to be consistent with the content.
- The original content is linked to the Astro theme page, but suggest it would be better to be linked to the actual tutorial page in Astro docs.
```md
[Build a Blog Tutorial]
(https://astro.build/themes/) --> (https://docs.astro.build/en/tutorial/0-introduction/)
```
> fix: Fix a link in getting-started.mdx

- .github/labeler.yml
This change adds the `glossary` label to any PR that modifies a glossary page in any language.
I can strictly limit this to the English translation on request from the i18n maintainers!
- Suggested label: `glossary` (however recursive), `ci`
> Add `glossary` label to labeler action

- src/content/docs/en/core-concepts/sharing-state.mdx
- src/content/docs/en/recipes/build-custom-img-component.mdx
- src/content/docs/en/recipes/build-forms-api.mdx
- src/content/docs/en/recipes/build-forms.mdx
- src/content/docs/en/recipes/dynamically-importing-images.mdx
- src/content/docs/en/recipes/external-links.mdx
- src/content/docs/en/recipes/modified-time.mdx
- src/content/docs/en/recipes/reading-time.mdx
- src/content/docs/en/recipes/sharing-state.mdx
- src/content/docs/en/recipes/tailwind-rendered-markdown.mdx
This PR changes all Title-Case recipe titles to Sentence-case.
It also adds missing punctuation to unify all the recipe descriptions (terminal periods).
- Suggested label: typo/grammar fix
> Unify recipe titles into sentence-case and add missing punctuation

- src/components/Version.astro
- src/components/starlight/Hero/FacePile.astro
- src/util-server.ts
This PR updates our `cachedFetch()` utility to use `p-retry` to automatically retry up to 10 times if a fetch fails. We were already using this strategy in the `<Version>` component — wrapping `cachedFetch()` in a retry — and this is now our default behaviour, so I refactored that component to remove the now redundant retry logic.
Should help with some flaky GitHub API calls we’ve been encountering (with so many contributors, we now need 8 calls just to get them all, so the chance of one flaking out has increased).
I’ve also switched the face pile component used in the new landing page hero to use `cachedFetch()` instead of a plain `fetch()`.
> Refactor `cachedFetch()` to always retry failed fetches

- src/content/docs/es/core-concepts/sharing-state.mdx
- src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/es/guides/view-transitions.mdx
- src/content/docs/es/recipes/sharing-state.mdx
- src/content/docs/es/tutorials/add-view-transitions.mdx
`sharing-state.mdx` [`3795132`](https://github.com/withastro/docs/commit/3795132d12d83e847be04bf2eae7fc632d337538#diff-83382bff225a8224ef90326f3c9569a018757ba23a7bdb689845540b35fcee4b)
`from-nextjs.mdx` [`a59604e`](https://github.com/withastro/docs/commit/a59604e1233057c182261a89e5ba9cbf80332625)
`add-view-transitions.mdx` [`479cffa`](https://github.com/withastro/docs/commit/479cffaa1338496971e0deaa5731b5c2a3d6604c) & [`13a0db8`](https://github.com/withastro/docs/commit/13a0db86f1bb949b073948810b2e5392a1021c2c)
`view-transitions.mdx` [`acfc72b`](https://github.com/withastro/docs/commit/acfc72b467a1260b727f1c5603a4ddefd7d49f7b)
> [!NOTE]
> In this [PR](https://github.com/withastro/docs/pull/5798) I changed the title `Comparte el estado entre componentes de Astro` to `Comparte el estado …
> i18n(es): Update `sharing-state.mdx`, `from-nextjs.mdx`, `add-view-transitions.mdx` & `view-transitions.mdx`

- src/content/docs/en/core-concepts/astro-components.mdx
- src/content/docs/es/core-concepts/astro-components.mdx
- src/content/docs/fr/core-concepts/astro-components.mdx
- src/content/docs/ko/core-concepts/astro-components.mdx
- src/content/docs/ru/core-concepts/astro-components.mdx
- src/content/docs/zh-cn/core-concepts/astro-components.mdx
Fixes a small issue in rows selected in a code block, off-by-one errors.
> [i18nIgnore] Fix highlighted code errors

- src/content/docs/en/guides/images.mdx
Following a discussion from Discord, it updates the background image format to use webp instead avif because:
- Avif is not the most standard format, with known issues on MS Edge
- A lot of beginners use this code snippet as is so it would be better to give them a "fully working" code
- This snippet must show we can pass a custom format. Even if webp is the default, it shows that it can be set
- Closes N/A
- Suggested label: code snippet update, low effort
> Update example to use webp instead of avif

- src/content/docs/en/core-concepts/project-structure.mdx
Adds a short clarification about the timing of when assets from public are copied into the build folder.
- Closes #5464
> public files copied before build

- src/content/docs/en/tutorials/add-view-transitions.mdx
It seems there's currently an issue with displaying View Transition events inside Markdown, causing this reported issue:
This PR fixes this in docs by wrapping it around with backticks. I'll make an repro and report as bug later.
- Closes #
> Fix issue with rendering VT events

- src/content/docs/en/guides/internationalization.mdx
This PR fixes two typos in the **Internationalization** guide:
- Fix wrong import for `getLocaleByPath` in example code:
Imported from `astro:18n`, should be from `astro:i18n`.
- Fix wrong prototype for `getRelativeLocaleUrlList`:
First argument is `locale: string`, should be `path?: string` (from [Astro's source code](https://github.com/withastro/astro/blob/4660aaa4051bd23fb77811968bbe56e2021161a2/packages/astro/client.d.ts#L221)).
- Fix wrong prototype for `getAbsoluteLocaleUrlList`:
First argument is `locale: string`, should be `path?: string` (from [Astro's source code](https://github.com/withastro/astro/blob/4660aaa4051bd23fb77811968bbe56e2021161a2/packages/astro/client.d.ts#L229)).
- Suggested label: `improve documentation`
> Fix typos in Internationalization guide

- src/content/docs/en/recipes/dynamically-importing-images.mdx
As of Astro v4.0, which now uses Vite 5, the `import.meta.glob<>()` API no longer returns `any` and now returns `unknown` unless a generic is specified. This PR updates the dynamic image import recipe to reflect these changes. It also fixes indentation and unnecessary whitespace in the recipe.
Affected page: [Modified](https://docs-git-fork-voxelmc-fix-image-import-recipe-astrodotbuild.vercel.app/en/recipes/dynamically-importing-images/#_top)
- Closes #5695 
- Suggested label: improve documentation
> Fix Formatting and Update Dynamic Image Import Recipe for Vite 5

- src/content/docs/zh-cn/core-concepts/project-structure.mdx
Update `core-concepts/project-structure.mdx`
Upstream PRs:
- #4166
- #5880
- Closes #
> i18n(zh-cn): Update `core-concepts/project-structure.mdx`

- src/content/docs/en/guides/deploy/heroku.mdx
Until someone can contribute an updated guide, adds deprecation notice to the Deploy to Heroku page.
- Closes #5657
> Add deprecated warning to Heroku deploy

- src/content/docs/en/core-concepts/astro-components.mdx
This adds another example to the section on named slots that shows using the named slot attribute on the Fragment component (`<Fragment slot="header">`) because the only existing examples showed adding the attribute to HTML elements.
In response to a request from an issue. Also note that this pattern is used and documented in the AstroWind template: https://astrowind.vercel.app/astrowind-template-in-depth , so it seemed reasonable to include an example here!
Am open to refining this example, or choosing a better one. Note that this one adds style classes (not style attributes) and therefore is maybe reflective of how it might be used, but not copy/pasteable. We could also choose to show inline styles if we cared instead.
Direct deploy preview: …
> [astro-components] add named slots example using Fragment

- src/content/docs/en/recipes/bun.mdx
- src/content/docs/es/recipes/bun.mdx
- src/content/docs/it/recipes/bun.mdx
- src/content/docs/ja/recipes/bun.mdx
- src/content/docs/ko/recipes/bun.mdx
- src/content/docs/zh-cn/recipes/bun.mdx
Update to use new @types/bun package instead of `bun-types` which will be deprecated in the future.
https://bun.sh/blog/bun-v1.0.19#re-introducing-types-bun-formerly-bun-types
- Closes #
- Suggested label: documentation
I have updated the link and installation on all languages that bun recipe is available because only requires to update the link, delete `tsconfig` configuration and update shell command.
> [i18nIgnore] New bun types package @types/bun

- src/content/docs/en/guides/integrations-guide/tailwind.mdx
Add new `nesting` option documentation.
- Closes #
Core PR: https://github.com/withastro/astro/pull/9529
The core PR is already merged, but I think it's fine even if we document this later.
> Add tailwind integration new nesting option

- src/content/docs/en/guides/integrations-guide/alpinejs.mdx
- src/content/docs/en/guides/integrations-guide/cloudflare.mdx
- src/content/docs/en/guides/integrations-guide/lit.mdx
- src/content/docs/en/guides/integrations-guide/markdoc.mdx
- src/content/docs/en/guides/integrations-guide/mdx.mdx
- src/content/docs/en/guides/integrations-guide/netlify.mdx
- src/content/docs/en/guides/integrations-guide/node.mdx
- src/content/docs/en/guides/integrations-guide/partytown.mdx
- src/content/docs/en/guides/integrations-guide/preact.mdx
- src/content/docs/en/guides/integrations-guide/react.mdx
- src/content/docs/en/guides/integrations-guide/sitemap.mdx
- src/content/docs/en/guides/integrations-guide/solid-js.mdx
- src/content/docs/en/guides/integrations-guide/svelte.mdx
- src/content/docs/en/guides/integrations-guide/tailwind.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
- src/content/docs/en/guides/integrations-guide/vue.mdx
I have updated every integration guide with a standardized version of the installation steps outlined below.
I also updated the formatting to be consistent with the rest of the `docs` (at least in the installation sections, I did not go past that)
This is meant for #5978
---
>Astro includes a CLI tool for adding first-party integrations: `astro add`. This command will:
>
>1. (Optionally) Install all necessary dependencies and peer dependencies
>2. (Also optionally) Update your `astro.config.*` file to apply this integration
>
>To install `@astrojs/_`, run the following from your project directory and follow the prompts:
>Add the _ adapter to enable SSR in your Astro project with the `astro add` command.
>This will install `@astrojs/_` and make the appropriate changes to your …
> Standardize the Integration Installation Steps 

- src/content/docs/zh-cn/guides/configuring-astro.mdx
Update `guides/configuring-astro.mdx`
Upstream PR:
- #6006
- Closes #
> i18n(zh-cn): Update `guides/configuring-astro.mdx`

- src/content/docs/fr/core-concepts/astro-components.mdx
Update French translation with #5712, #5817 and #5968
> i18n(fr) Update  `astro-components.mdx`

- src/content/docs/en/reference/cli-reference.mdx
`--host` and `--port` works for `astro preview` for a very long time (since the command existed?). I moved the two flags under `dev` flags to common flags. And roughly updated the "dev server" phrase to "dev server and preview server".
- Closes #
The Astro core PR that updated the flags is https://github.com/withastro/astro/pull/9572. We don't have to align the merge release with it though. I think it's more of missing docs.
> Document --host and --port flags for preview

- src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx
> i18n(zh-cn): Update cloudflare.mdx

- src/content/docs/en/reference/directives-reference.mdx
Documentation for optional root margin on client visible. This documents this pr https://github.com/withastro/astro/pull/9363
This documents the PR https://github.com/withastro/astro/pull/9363 for astro. It shouldn't be merged before the PR is merged. The change is for having root margin as a possiblity. 
- Suggested label: merge-on-release, add new content,
> Update directives-reference.mdx with optional root margin

- src/content/docs/en/guides/integrations-guide/vercel.mdx
Vercel has deprecated the framework-integrated API in favor of a framework-agnostic library that we don't need to document.
- https://github.com/withastro/astro/pull/9598
> Update vercel.mdx - Vercel Speed Insights API is deprecated

- src/content/docs/zh-cn/recipes/dynamically-importing-images.mdx
Compare to the English version, the indentation of directory structure is not correct, `assets` should be under the `src`.
- Closes #
> i18n(zh-cn): Fix indentation of directory structure

- src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
- Update vercel.mdx
- Fix code block
- https://github.com/withastro/docs/pull/6082
> i18n(zh-cn): Update vercel.mdx

- src/content/docs/en/guides/integrations-guide/sitemap.mdx
After review, decided to revert the change made in #6134 and that it's correct to show the `index` for the sitemap.
TRANSLATORS: this file has been changed *twice*, but ultimately there is no change to this file content. If your translation tracker needs updating to show that this file is up to date, you can make a PR adding or removing a blank line at the end.
> [sitemap.mdx] Revert change in #6134

- src/content/docs/en/guides/migrate-to-astro/from-docusaurus.mdx
This page updates our guidance migrating from Docusarus to:
- mention Starlight in an appropriate spot
- remove outdated info re: using `src/pages` for content 
- add that Astro Docs runs on Starlight
cc @delucis for any other specific changes while we're on this page.
> [from-docusaurus.mdx]: refresh with more Starlight-specific text

- src/content/docs/fr/guides/integrations-guide/tailwind.mdx
There is a typo in the `tailwind.mdx` translation in french:
"éfinissez" should be "définissez"
- Closes #
> [i18nIgnore] i18n(fr): fix a typo in tailwind.mdx

- src/content/docs/en/guides/integrations-guide.mdx
Changes aside from "INTEGRATIONS DIRECTORY" to "Integrations directory".
> [i18nIgnore] Fix aside casing in `integrations-guide.mdx`

- src/components/ReadMore.astro
- src/components/RecipeLinks.astro
- src/content/docs/en/core-concepts/astro-components.mdx
- src/content/docs/en/core-concepts/astro-pages.mdx
- src/content/docs/en/core-concepts/framework-components.mdx
- src/content/docs/en/core-concepts/layouts.mdx
- src/content/docs/en/core-concepts/routing.mdx
- src/content/docs/en/editor-setup.mdx
- src/content/docs/en/guides/client-side-scripts.mdx
- src/content/docs/en/guides/configuring-astro.mdx
- src/content/docs/en/guides/content.mdx
- src/content/docs/en/guides/deploy/cloudflare.mdx
- src/content/docs/en/guides/deploy/deno.mdx
- src/content/docs/en/guides/deploy/netlify.mdx
- src/content/docs/en/guides/deploy/vercel.mdx
- src/content/docs/en/guides/imports.mdx
- src/content/docs/en/guides/integrations-guide/markdoc.mdx
- src/content/docs/en/guides/integrations-guide/mdx.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
- src/content/docs/en/guides/markdown-content.mdx
- src/content/docs/en/guides/styling.mdx
- src/content/docs/en/guides/typescript.mdx
- src/content/docs/en/install/auto.mdx
- src/content/docs/en/install/manual.mdx
- src/content/docs/en/recipes/i18n.mdx
- src/content/docs/en/reference/api-reference.mdx
- src/content/docs/en/reference/cli-reference.mdx
- src/content/docs/en/reference/directives-reference.mdx
- src/content/docs/en/tutorials/add-view-transitions.mdx
- Replaces our 📚 bullets with a `<ReadMore>` component that adds a stylized open book icon to text instead.
Usage:
```diff
- 📚 Learn more about [emoji](#emoji)
+ import ReadMore from '~/components/ReadMore.astro';
+
+ <ReadMore>Learn more about [emoji](#emoji)</ReadMore>
```
- Updates our `<RecipeLinks>` component styles to match `<ReadMore>` more closely
- Updates a few instances of the 📚 pattern to use Starlight’s `<LinkCard>` component instead where that felt more appropriate
> Add `<ReadMore>` component

- src/content/docs/en/recipes/i18n.mdx
This PR adds [Paraglide](https://inlang.com/c/astro) to the community libraries in the i18n recipie.
Paraglide plays really well with islands due to it's treeshakeable output. It only ships messages for an island if they are actually used, making it a great fit for translating interactive components and site shells. The resulting bundle can be as small as 120bytes, depending on the message and number of languages.
The Paraglide team is also committed to maintaining good Astro [guides](https://inlang.com/g/utqgkmzp/guide-lorissigrist-buildAGlobalAstroApp)  and [examples](https://github.com/opral/monorepo/tree/main/inlang/source-code/paraglide/paraglide-js-adapter-astro/example).
> Add Paraglide to i18n community libraries

- src/content/docs/es/concepts/why-astro.mdx
I corrected the text "Creemos firmemento" to "Creemos firmemente"
> i18n(es): Fix typo in `why-astro.mdx`

- src/content/docs/ko/reference/errors/invalid-content-entry-slug-error.mdx
- add `invalid-content-entry-slug-error.mdx`
- Closes #
> i18n(ko-KR): add `invalid-content-entry-slug-error.mdx`

- src/components/BackendGuidesNav.astro
- src/components/CMSGuidesNav.astro
- src/components/DeployGuidesNav.astro
- src/components/IntegrationsNav.astro
- src/components/MigrationGuidesNav.astro
- src/components/NavGrid/Card.astro
- src/components/NavGrid/CardsNav.astro
- src/components/NavGrid/Grid.astro
- src/components/RecipesNav.astro
This PR refactors our card nav components. Mostly this should be a subtle visual change but it also removes a fair bit of CSS which is fun. Because this is used in a lot of different contexts, it should still be double checked thoroughly in case I missed something somewhere.
A couple of higher profile details:
- The SSR/static tag filtering mechanism in the [deploy guides nav](https://docs-git-dx-918-recipe-grid-astrodotbuild.vercel.app/en/guides/deploy/) has been removed. This was starting to get inaccessible and was perhaps offering less than we initially thought.
- The [more recipes cards](https://docs-git-dx-918-recipe-grid-astrodotbuild.vercel.app/en/recipes/) are now a slightly smaller font size to match the original docs redesign specs. Should help a bit with how noisy that grid is …
> Refactor card nav components

- src/content/docs/es/reference/errors/cant-render-page.mdx
- src/content/docs/es/reference/errors/missing-locale.mdx
- src/content/docs/es/reference/errors/unhandled-rejection.mdx
Translate `cant-render-page`, `missing-locale` & `unhandled-rejection`
> i18n(es): Translate `cant-render-page`, `missing-locale` & `unhandled-rejection`

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
It seems there is a typo suggesting that `.mdoc` files can be used inside the `pages` folder. After speaking with nate on Discord, it seems it should be `.astro`.
The makes the relevant change.
> typo: correct .mdoc extension to .astro

- .github/workflows/welcome-bot.yml
The welcome bot states that a preview will be available on Netlify, but it seems deploys are now done to Vercel.
> typo: fix a small typo in the welcome bot message

- src/content/docs/en/reference/adapter-reference.mdx
Documents new options in the adapter API being introduced in Astro 4.2
- https://github.com/withastro/astro/pull/9661
> Adapter enhancements in Astro 4.2

- src/content/docs/en/reference/integrations-reference.mdx
- src/content/docs/en/reference/publish-to-npm.mdx
1. Adding link to my integration template
2. Adding link to the discord server since we now have a dedicated channel
- Closes N/A
- Suggested label: improve documentation
> feat: update integrations related docs

- src/content/docs/en/guides/view-transitions.mdx
I believe the navigation triggering React component has a just very slightly confusing name and an unused prop which somewhat misguide the reader's attention
- Suggested label: Fix a confusing React component example
> Fix a confusing React component example

- src/content/docs/en/recipes/streaming-improve-page-performance.mdx
The code snippet has `<h2>` tags instead of `<h1>` so I updated the text to match.
- Closes #
> <h1> to <h2> to Match Code Snippet

- src/content/docs/es/guides/cms/kontent-ai.mdx
Fixed a problem with the highlighted block. This part was duplicated `astro title="src/pages/index.astro" ins={11-29}`
> i18n(es): update kontent-ai.mdx

- src/components/tutorial/MultipleChoice.astro
Update the MultipleChoice submit button style when hover
before
after
- Closes #
> Update the MultipleChoice submit button style

- src/content/docs/zh-cn/reference/error-reference.mdx
- src/content/docs/zh-cn/reference/errors/astro-glob-no-match.mdx
- src/content/docs/zh-cn/reference/errors/i18n-not-enabled.mdx
- src/content/docs/zh-cn/reference/errors/missing-index-for-internationalization.mdx
Update translate from #6623
Update files:
- [reference/error-reference.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/zh-cn/reference/error-reference.mdx)
- [reference/errors/astro-glob-no-match.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/zh-cn/reference/errors/astro-glob-no-match.mdx)
Create files:
- [reference/errors/i18n-not-enabled.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/zh-cn/reference/errors/i18n-not-enabled.mdx)
- [reference/errors/missing-index-for-internationalization.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/zh-cn/reference/errors/missing-index-for-internationalization.mdx)
- #6623
> i18n(zh-cn): Update translate from #6623

- src/content/docs/en/guides/integrations-guide/tailwind.mdx
This fixes the Tailwind's config extension that was still `.cjs` to use the correct format according to its export statement: `.mjs`
> Fix `tailwind.mdx` config extension

- package.json
- pnpm-lock.yaml
- This PR updates Astro and Starlight to the latest releases
- It also downgrades `sharp` back to 0.32.6 as the newest versions have been causing “Could not find Sharp.” errors
> Upgrade dependencies (and downgrade Sharp)

- src/components/starlight/MarkdownContent.astro
Because we wrap our heading elements in a `<div>` to support the layout of the anchor link icons, Starlight’s built-in `:not(heading) + heading` styles weren’t applying.
This PR adds back those spacing styles for less ugly pages 💅 
Click around several pages to see the difference, but here is one before/after comparison:
|--------|--------|
| ![Page with minimal spacing before headings](https://github.com/withastro/docs/assets/357379/ed2b07c3-4a85-4596-9f82-cdb789f1c0bb) | ![Page with more generous spacing before headings](https://github.com/withastro/docs/assets/357379/92bff1dd-f0d8-4475-9166-a37cfde1a9d7) |
> Fix headings spacing

- src/content/docs/ko/guides/prefetch.mdx
- update `prefetch.mdx`
- #6573
- Closes #
> i18n(ko-KR): update `prefetch.mdx`

- src/content/docs/en/basics/astro-components.mdx
We're [temporarily rolling back a feature](https://github.com/withastro/compiler/pull/963#pullrequestreview-1865102712) (dynamically generated slots) which we added docs for in #6440, so I removed its mention in the docs
> Revert "Update mention about dynamically generated slot names (#6440)"

- src/content/docs/en/guides/integrations-guide/netlify.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
Enabling `edgeMiddleware` will now involve a check to prevent anyone but the generated middleware from providing locals.
- https://github.com/withastro/astro/pull/9987
- https://github.com/withastro/astro/pull/10018
- https://github.com/withastro/adapters/pull/152
- https://github.com/withastro/adapters/pull/156
> document new behavior(vercel, netlify): edge middleware verification

- src/content/docs/en/guides/images.mdx
Adds explanation that md/mdx images are treated the same in CC as normal md/mdx
> explain images in cc are same as md/mdx images

- src/content/docs/ko/guides/deploy/deno.mdx
- update `deno.mdx`
- #6535
- Closes #
> i18n(ko-KR): update `deno.mdx`

- src/content/docs/en/reference/dev-toolbar-app-reference.mdx
- src/content/docs/es/reference/dev-toolbar-app-reference.mdx
- src/content/docs/ko/reference/dev-toolbar-app-reference.mdx
- src/content/docs/zh-cn/reference/dev-toolbar-app-reference.mdx
The event name `app-notification` does not exist and can be misleading to users, so change it to an event name that does exist.
> [i18nIgnore] Change event name

- src/content/docs/pt-br/reference/configuration-reference.mdx
fix pt-br translation about options of `scopedStyleStrategy`
The information about the `scopedStyleStrategy` option for `attribute` was wrong. And I improved the description of the `where` option
---
Discord user: jeff_drumgod
> [i18nIgnore] i18n(pt-br): fix information about `scopedStyleStrategy` config

- src/content/docs/zh-cn/guides/integrations-guide/node.mdx
Unify the style used in translation: 'Why Astro Node.js' should be translate to "为什么选择 Astro Node.js". 
This is a small correction.
> i18n(zh-CN): Fix incorrect translation text in `guides/integrations-guide/node.mdx` 

- src/components/starlight/Search.astro
Removes the `#_top` anchor from URLs in search results.
- Closes #6897
> Remove #_top anchor from search result URLs

- src/components/starlight/Search.astro
Remove legacy hash transformation (`#overview`) from `Search.astro`
- Related PR comment: https://github.com/withastro/docs/pull/6917#discussion_r1493470494
> Remove legacy hash transformation

- src/content/docs/en/guides/prefetch.mdx
This pull request adds missing semicolons in code examples within the section about prefetching. This follows the standard set in other sections, like [SSR Adapters](https://docs.astro.build/en/guides/server-side-rendering/#manual-install).
> Add missing semicolons in code examples

- src/content/docs/ja/guides/client-side-scripts.mdx
- Update client-side-scripts.mdx
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/client-side-scripts.mdx?since=2023-12-05T06:53:22.000Z)
- https://github.com/withastro/docs/pull/6267
> i18n(ja): Update client-side-scripts.mdx

- src/content/docs/es/reference/publish-to-npm.mdx
- Comments have been translated
- The bash section has been changed to the FileTree component.
- In the tip it has been changed so that the names are highlighted
- Closes #N/A
> i18n(es): update publish-to-npm.mdx

- src/i18n/en/nav.ts
I misunderstood how to update `nav.ts` for Japanese (ref. https://github.com/withastro/docs/pull/6985#issuecomment-1961828452). I also saw the same error in French translation.
To prevent incorrect data structure in `nav.ts` in the future, This adds a comment for translations in `en/nav.ts`.
/cc @Yan-Thomas 
- Closes #
> [i18nIgnore]: add a comment for translators on the data structure in localized `nav.ts` files

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
- src/content/docs/es/guides/integrations-guide/markdoc.mdx
- src/content/docs/fr/guides/integrations-guide/markdoc.mdx
- src/content/docs/ko/guides/integrations-guide/markdoc.mdx
- src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
Fixes the title of some example code in the Markdoc integration page that used the wrong extension.
> [i18nIgnore] Fix typo in Markdoc code sample title

- src/content/docs/es/guides/view-transitions.mdx
Fix typo in animation directive: change 'slice' to 'slide
> Fix typo in animation directive

- src/content/docs/es/guides/view-transitions.mdx
This commit removes a section in English that has already been translated.
> Remove redundant English section after translation

- src/content/docs/en/guides/styling.mdx
"How to set up LightningCSS w/ Astro"
LightningCSS is supported by Astro, and allows using several features that something like Sass might support but via current CSS without leaving old browsers behind. We should document how to set it up
- Closes #
Feel free to workshop / move this / update my PR, I just wanted to make sure it's documented *somewhere*
> Add LightningCSS to preprocessors

- src/content/docs/en/guides/cms/keystatic.mdx
The Keystatic integration was updated to support both `hybrid` and `server` output modes, so this PR updates the guide accordingly.
> Update keystatic Guide

- .github/actions/install/action.yml
- .github/workflows/ci.yml
- .github/workflows/discord-i18n-ping.yml
- .github/workflows/format.yml
- .github/workflows/nightly.yml
- .github/workflows/pr-labeler.yml
- .github/workflows/welcome-bot.yml
- src/content/docs/de/guides/deploy/aws.mdx
- src/content/docs/de/guides/deploy/deno.mdx
- src/content/docs/de/guides/deploy/github.mdx
- src/content/docs/en/guides/deploy/aws.mdx
- src/content/docs/en/guides/deploy/deno.mdx
- src/content/docs/en/guides/deploy/github.mdx
- src/content/docs/es/guides/deploy/aws.mdx
- src/content/docs/es/guides/deploy/deno.mdx
- src/content/docs/fr/guides/deploy/aws.mdx
- src/content/docs/fr/guides/deploy/deno.mdx
- src/content/docs/it/guides/deploy/deno.mdx
- src/content/docs/ja/guides/deploy/aws.mdx
- src/content/docs/ja/guides/deploy/deno.mdx
- src/content/docs/ja/guides/deploy/github.mdx
- src/content/docs/ko/guides/deploy/aws.mdx
- src/content/docs/ko/guides/deploy/deno.mdx
- src/content/docs/pt-br/guides/deploy/aws.mdx
- src/content/docs/pt-br/guides/deploy/deno.mdx
- src/content/docs/pt-br/guides/deploy/github.mdx
- src/content/docs/zh-cn/guides/deploy/aws.mdx
- src/content/docs/zh-cn/guides/deploy/deno.mdx
Get rid of those warnings:
In addition, I updated the action versions in the examples so that no warnings are issued when copying and pasting.
> [i18nIgnore] Updates deprecated Node.js 16 github actions

- src/content/docs/en/guides/ecommerce.mdx
This PR corrects an issue where the "handling overlay events" link in the `ecommerce.mdx` page was pointing to the same URL as "programmatically opening overlays". The incorrect link has been updated to point to the appropriate section in the Lemon.js documentation.
> Fix duplicate links in `ecommerce.mdx`

- src/content/docs/en/guides/ecommerce.mdx
I’ve noticed a small inconsistency in the Snipcart configuration section of the `ecommerce.mdx` page that could be slightly confusing to translators. The step numbering within the "Basic usage" subsection does not follow a sequential order. The current numbering sequence in the markdown is 1, 2, 4, 6. For clearer readability and future maintenance of the document, it may be beneficial to update the numbering to a sequential order: 1, 2, 3, 4.
I understand that when markdown is rendered, the list numbering is corrected automatically. However, for the ease of future documentation maintenance and clarity in the markdown source, adjusting the raw markdown numbers to be sequential could help reduce any potential confusion.
> Fix incorrect list numbering in `ecommerce.mdx`

- src/content/docs/en/tutorial/1-setup/2.mdx
fix: change step order for typescript and dependencies
Changed steps as per CLI actions
- Closes #
> fix: change step order for typescript and dependencies

- src/content/docs/zh-cn/reference/errors/middleware-cant-be-loaded.mdx
I've updated the latest Simplified Chinese translation from `middleware-cant-be-loaded.mdx`.
The latest changes in English docs is in: https://github.com/withastro/docs/commit/7db5cf519459d3ec3f730e385efa42f3c6f08267
- Closes #
> i18n(zh-cn): Update `middleware-cant-be-loaded.mdx`

- src/content/docs/zh-tw/concepts/islands.mdx
- src/content/docs/zh-tw/guides/migrate-to-astro.mdx
- Updates Traditional Chinese translation of `src/content/docs/zh-tw/concepts/islands.mdx`
- Fixes a broken link in `src/content/docs/zh-tw/guides/migrate-to-astro.mdx`
- ~~Closes #~~
> i18n(zh-tw): update `islands.mdx` translation

- src/content/docs/en/guides/view-transitions.mdx
A user on discord complained that the current text gives the impression that `transition:persist` would keep all states of an element, while he suffered from restarting animations.
He referred to this sentence, which he had taken out of context
> the [...] internal state [...] will not be reset when navigating back and forth across pages 
It might help to mention the known limitations.
> Adds a note about what internal state of elements can't be preserved by transition:persist

- src/content/docs/ja/guides/fonts.mdx
Fixed a broken link to the Fontsource font catalogue in the Japanese document.
No Issue has been created as it is only a fix for broken links.
- Suggested label: bug
In addition to the Japanese document, I found some broken links to other documents, but I didn't know whether I should put them in one PR or not, so I fixed only the links to the Japanese document. Additional corrections may be made in this PR if it is acceptable to publish them together.
> fix: fix broken link

- src/content/docs/en/guides/astro-db.mdx
There are a couple reasons I'd like to move the "columns" section after "tables:"
1. **Order of explanation.** It's impossible to describe a column without first describing a table, and this was clear from the preamble. It's also odd to show users all available column types before explaining how a table can be configured in the first place. By moving the column preamble into the "tables" section, and pushing the "columns" snippet below, the user is presented with the most minimal example for configuration before reading the details.
2. **Copy / paste warriors.** While watching a user walk through the docs ([t3dotgg](https://www.twitch.tv/theo)), they reached the "columns" section of the docs and naturally copied the snippet to build their config. Trouble is, this snippet includes a number …
> edit: move DB "Columns" section after "Tables"

- src/content/docs/ja/guides/deploy/netlify.mdx
- Update netlify.mdx.
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/deploy/netlify.mdx?since=2023-12-03T16:42:56.000Z)
- https://github.com/withastro/docs/pull/5977
- https://github.com/withastro/docs/pull/6267
- Closes #
> i18n(ja): Update netlify.mdx

- src/content/docs/ru/community-resources/content.mdx
This PR updates the Russian translation of the `routing.mdx` page, addressing outdated content identified by the Translation Tracker.
Related:
- #7449
> i18n(ru): Update `content.mdx` translation

- src/content/docs/en/guides/astro-db.mdx
- src/content/docs/ja/guides/astro-db.mdx
- src/content/docs/ko/guides/astro-db.mdx
- src/content/docs/ru/guides/astro-db.mdx
- src/content/docs/zh-cn/guides/astro-db.mdx
This PR updates a section of the Astro DB documentation. The section that shows how to delete a comment is incorrect. The `where` function doesn't accept a "raw" object, but we should always use the utility functions provided.
Reference: https://orm.drizzle.team/docs/sql#sql-in-where
Filed here https://github.com/withastro/astro/issues/10489
> [i18nIgnore] fix(db): use `where` correctly

- src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
> i18n(zh-cn): Update `vercel.mdx`

- src/content/docs/zh-cn/reference/error-reference.mdx
- src/content/docs/zh-cn/reference/errors/endpoint-did-not-return-aresponse.mdx
Update `endpoint-did-not-return-aresponse.mdx`
Update `error-reference.mdx`
- #7483
> i18n(zh-cn): Create `endpoint-did-not-return-aresponse.mdx`

- src/content/docs/en/guides/integrations-guide/db.mdx
There is `columns` key is missing. All the columns are not wrapped into the `columns` key and are directly used in the `defineTable` object
Discord Username: _withden
> updates indexes and foreignkeys example

- src/content/docs/en/guides/troubleshooting.mdx
This change introduces an alternative workaround for inlined scripts in the presence of Content-Security-Policy headers.
- "Closes": #2150
- Suggested label: `add new content`, `can of worms`
- Astro Discord username: castarco (Andreu)
> docs: add alt workaround for csp trouble with inline scripts

- src/content/docs/en/integrations/integrations.mdx
I believe [hookdeck.com](https://hookdeck.com) and [hookdeck.com/docs](https://hookdeck.com/docs) are good production examples of what's possible with Astro.
I'm `leggetter` in the Astro Discord.
Website
Docs
> Adds Hookdeck website and docs as an example production site

- src/content/docs/en/guides/integrations-guide/vercel.mdx
Added an example that shows how you would exclude dynamic routes from ISR.
- Closes # 
> Add dynamic routes example in isr.exclude for @astrojs/vercel integration

- src/content/docs/en/guides/cms/wordpress.mdx
Added the [Gato GraphQL](https://wordpress.org/plugins/gatographql/) plugin as another option for getting data from WordPress using GraphQL.
> Added Gato GraphQL as option for WordPress

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
- Restructure table-of-contents with clearer h2 sections. Before, everything was nested under Configuration. This breaks out related sections, and moves higher-traffic content (ex. how to use UI components) further up).
**Before | After**
- Closes #
> Rework Markdoc info hierarchy

- src/content/docs/en/reference/cli-reference.mdx
This PR removes the unused import of the Badge component from the `cli-reference.mdx` file as well as some extra line breaks. It also adds the code syntax to the `astro link` command at the end of the file, to match the other occurrences of commands inside the main text.
> fix: remove unused import and add missing syntax

- CONTRIBUTING.md
The `CONTRIBUTING.md` docs mention an `integrations-guides/` directory when the correct directory is `integrations-guide/`. This PR fixes that!
- Closes #
Discord username: `kanadg`
> [CONTRIBUTING.md] fix typo in directory path

- src/content/docs/fr/guides/integrations-guide/markdoc.mdx
Updating `guides/integration-guide/markdoc.mdx` from #7743
- Closes #
> i18n(fr): Updating `guides/integration-guide/markdoc.mdx` 

- .github/PULL_REQUEST_TEMPLATE.md
Adds one line to the PR template:
```
```
This won't catch all the PRs, but will be enough to stop some people from submitting to multiple languages at once.
This also doesn't explicitly say "Changes to English only.. etc." because I don't want anything too long that people won't read. ONE LANGUAGE is enough that some people will notice it, and it will improve some of the PRs we get before they're made.
> update PR template: changes in one language only

- src/content/docs/en/guides/integrations-guide/db.mdx
Update `indexes` configuration from an object to an array. Also note that index names are generated with a `name` property to override.
- Closes #
> edit: new indexes config

- src/content/docs/en/install/auto.mdx
This PR updates the minimum Node.js version.
> feat: update minimum Node.js version

- src/content/docs/en/guides/dev-toolbar.mdx
- src/content/docs/en/guides/internationalization.mdx
- src/content/docs/en/install/auto.mdx
- src/content/docs/en/reference/api-reference.mdx
- src/content/docs/en/reference/configuration-reference.mdx
- src/content/docs/en/reference/dev-toolbar-app-reference.mdx
- src/content/docs/en/reference/error-reference.mdx
- src/content/docs/en/reference/errors/incorrect-strategy-for-i18n.mdx
- src/content/docs/en/reference/errors/missing-middleware-for-internationalization.mdx
- src/content/docs/es/reference/configuration-reference.mdx
- src/content/docs/ja/reference/configuration-reference.mdx
- src/content/docs/ko/guides/internationalization.mdx
- src/content/docs/zh-cn/reference/configuration-reference.mdx
Co-authored-by: sarah11918 <sarah11918@users.noreply.github.com>
This updates the docs for the 4.6 minor from the following PRs:
#7844 
#7845 
#7720 
#7814 
#7749 
#7838
> 4.6.0 minor docs update

- src/content/docs/en/community-resources/content.mdx
- src/content/docs/en/guides/deploy/aws.mdx
Added the recent UNIQUE content I've been publishing involving Astro.
Confirmed by Sarah that this is the place where I may propose to add the *recipes*: https://discord.com/channels/830184174198718474/830184175176122389/1229477006979240016
- Closes #
> Recent Astro-first Community Resources

- src/content/docs/zh-cn/community-resources/content.mdx
> i18n(zh-cn): Update `content.mdx`

- src/content/docs/zh-cn/guides/deploy/aws.mdx
> i18n(zh-cn): Update `aws.mdx`

- src/content/docs/ko/guides/deploy/aws.mdx
- update `aws.mdx`
- #7902
- Closes #
> i18n(ko-KR): update `aws.mdx`

- src/content/docs/ko/community-resources/content.mdx
- update `content.mdx`
- #7902
- Closes #
> i18n(ko-KR): update `content.mdx`

- src/content/docs/zh-cn/guides/images.mdx
> i18n(zh-cn): Update `images.mdx`

- src/content/docs/es/reference/errors/missing-middleware-for-internationalization.mdx
- Adding `src/content/docs/es/reference/errors/missing-middleware-for-internationalization.mdx`
- Closes #
> i18n(es): Missing middleware for internationalization

- src/content/docs/en/guides/fonts.mdx
Since Variable Fonts in fontsource start with @fontsource-variable/, I thought it might be better to display `It will start with @fontsource/ or @fontsource-variable/ followed by the name of the font.` instead of the tip `It will start with @fontsource/ followed by the name of the font.`
- Closes # #7981 
> Update Fontsource tip to add @fontsource-variable scope

- src/content/docs/en/guides/deploy/aws.mdx
Updates a small typo on the `aws.mdx` guide.
> fix: Update `aws.mdx` typo

- src/content/docs/en/reference/cli-reference.mdx
Astro 4.7 adds a new preference: `checkUpdates`. We currently don't have a place where the list of preferences are listed, and in core we honestly don't add preferences all that often, so I figured just a small list in the CLI reference was good enough, happy to do something else, though.
> feat: add small mention of available preferences

- src/content/docs/en/reference/integrations-reference.mdx
While reading through the integration docs, I noticed that `astro:config:setup` appeared synchronous in the documentation, while the actual type allows a `Promise`.
> Fix typing mismatch in Integration API docs

- src/content/docs/es/recipes/making-toolbar-apps.mdx
- Making toolbar apps (spanish version)
> i18n(es): Making toolbar apps

- src/content/docs/fr/community-resources/content.mdx
- src/content/docs/fr/guides/deploy/aws.mdx
Update french translation for `aws.mdx` and `community-ressources/content.mdx` files with PR #7902 #7991 and and a few omissions.
> i18n(fr) Update french translation for `aws.mdx` and `content.mdx`

- src/content/docs/ko/guides/dev-toolbar.mdx
- src/content/docs/ko/recipes/making-toolbar-apps.mdx
- src/content/docs/ko/reference/cli-reference.mdx
- src/content/docs/ko/reference/dev-toolbar-app-reference.mdx
- create `making-toolbar-apps.mdx` 
- update `cli-reference.mdx`
- update `dev-toolbar-app-reference.mdx`
- update `dev-toolbar.mdx`
- #8002
- Closes #
> i18n(ko-KR): update `cli-reference.mdx`, `dev-toolbar-app-reference.mdx`, `dev-toolbar.mdx`, create `making-toolbar-apps.mdx` 

- src/content/docs/en/guides/backend/supabase.mdx
Register Button name - "Login" -> "Register"
Documentation - Supabase & Astro
https://docs.astro.build/en/guides/backend/supabase/
The current text is confusing, the register page's action should be register, currently it is login just like the login page
Currently the src/pages/signin.astro is:
```
<Layout title="Sign in">
<h1>Sign in</h1>
<p>New here? <a href="/register">Create an account</a></p>
<form action="/api/auth/signin" method="post">
<label for="email">Email</label>
<input type="email" name="email" id="email" />
<label for="password">Password</label>
<input type="password" name="password" id="password" />
<button type="submit">Login</button>
</form>
</Layout>
```
and src/pages/register.astro is:
```
---
import Layout from "../layouts/Layout.astro";
---
<Layout title="Register"> …
```
> Register Button name

- src/content/docs/ko/guides/backend/google-firebase.mdx
- update `google-firebase.mdx`
- #8014
- Closes #
> i18n(ko-KR): update `google-firebase.mdx`

- src/content/docs/ko/guides/server-side-rendering.mdx
- update `server-side-rendering.mdx`
- #8011
- Closes #
> i18n(ko-KR): update `server-side-rendering.mdx`

- src/content/docs/en/reference/integrations-reference.mdx
Removes an extra backtick ("\`")  character from a code snipper in `integrations-reference.mdx`
> Remove unnecessary character from integrations-reference.mdx

- src/content/docs/en/guides/deploy/zeabur.mdx
> Add Steps component to `zeabur.mdx`

- src/content/docs/en/guides/deploy/sst.mdx
> Add Steps component to `sst.mdx`

- src/content/docs/en/recipes/build-forms.mdx
> Add Steps component to `build-forms.mdx`

- src/content/docs/en/guides/deploy/vercel.mdx
> Add Steps component to `vercel.mdx`

- src/content/docs/en/recipes/sharing-state.mdx
> Add Steps component to `sharing-state.mdx`

- src/content/docs/en/guides/deploy/heroku.mdx
> Add Steps component to `heroku.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx
> Add Steps component to `from-nextjs.mdx`

- src/content/docs/en/guides/cms/hygraph.mdx
> Add Steps component to `hygraph.mdx`

- src/content/docs/en/guides/markdown-content.mdx
> Add Steps component to `markdown-content.mdx`

- src/content/docs/en/guides/cms/decap-cms.mdx
> Add Steps component to `decap-cms.mdx`

- src/content/docs/en/guides/deploy/flightcontrol.mdx
> Add Steps component to `flightcontrol.mdx`

- src/content/docs/en/guides/rss.mdx
Adds the `Steps` component to the "Setting up `@astrojs/rss`" section instructions in the `rss.mdx` guide.
> Add Steps component to `rss.mdx`

- src/content/docs/en/guides/cms/tina-cms.mdx
> Add Steps component to `tina-cms.mdx`

- src/content/docs/en/recipes/captcha.mdx
> Add Steps component to `captcha.mdx`

- src/content/docs/en/guides/deploy/flyio.mdx
> Add Steps component to `flyio.mdx`

- src/content/docs/en/guides/cms/cosmic.mdx
> Add Steps component to `cosmic.mdx`

- src/content/docs/en/recipes/external-links.mdx
> Add Steps component to `external-links.mdx`

- src/content/docs/en/guides/cms/strapi.mdx
> Add Steps component to `strapi.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx
> Add Steps component to `from-nuxtjs.mdx`

- src/content/docs/en/guides/upgrade-to/v3.mdx
> Add Steps component to `v3.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
> Add Steps component to `from-gatsby.mdx`

- src/content/docs/en/guides/upgrade-to/v1.mdx
> Add Steps component to `v1.mdx`

- src/content/docs/en/guides/deploy/google-cloud.mdx
> Add Steps component to `google-cloud.mdx`

- src/content/docs/en/guides/deploy/aws.mdx
> Add Steps component to `aws.mdx`

- src/content/docs/en/guides/cms/datocms.mdx
> Add Steps component to `datocms.mdx`

- src/content/docs/en/reference/publish-to-npm.mdx
> Add Steps component to `publish-to-npm.mdx`

- src/content/docs/en/guides/testing.mdx
> Add Steps component to `testing.mdx`

- src/content/docs/en/guides/cms/kontent-ai.mdx
> Add Steps component to `kontent-ai.mdx`

- src/content/docs/en/guides/server-side-rendering.mdx
> Add Steps component to `server-side-rendering.mdx`

- src/content/docs/en/guides/middleware.mdx
This pull request simplifies the code examples in the section about middleware. I have removed any destructoring of the `context` object to make it easier to understand where it is located in the code.
- Closes #7567
> Simplify middleware examples

- src/content/docs/en/guides/images.mdx
This adds an explicit note about no optimization for remote and `public/` images using the standard Markdown syntax.
- Closes #7539
> specify that remote images in `.md` are not optimized.

- src/content/docs/en/guides/deploy/netlify.mdx
The link to the Netlify blog post is now outdated, as the `functions` and `edge-functions` libraries no longer exist.
> Remove Outdated Link from `netlify.mdx`

- src/i18n/pl/ui.ts
Updates a few Polish translations and adds all missing ones in `ui.ts`.
> i18n(pl): update ui.ts

- src/content/docs/en/getting-started.mdx
This PR updates the main call-to-action link text in the docs landing page.
The current link reads “Get started”, but that is the same text as the CTA on https://astro.build/ which means users can be presented by two consecutive “Get started” choices.
The new link text is “Install Astro”, which is also a more precise description of the link destination as it points to the install guide.
> Update main CTA text in landing page

- config/sidebar.ts
- src/i18n/en/nav.ts
- src/i18n/translation-checkers.ts
Updates our utility function mapping our `nav.ts` files to Starlight’s sidebar config shape to support nesting and collapsing groups.
- Nesting/collapsing is controlled from `src/i18n/en/nav.ts`. Other languages continue to work the same way, providing just the key–value mapping of translations.
- Each heading (entries with `header: true`) can be marked as a nested group by adding `nested: true`.
- Each heading (entries with `header: true`) can be marked as collapsed by default by adding `collapsed: true`.
- I took a few shortcuts to keep this simple, which means nested groups have to be at the end of their containing group, i.e. the following is possible:
```
Parent group     ▼
|   Link 1
|   Link 2
|
|   Sub group    ▼
|   |   Link 3
|   |   Link 4
|
|   Other group  ▼
|   |   Link 5
| …
```
> Add support for nesting and collapsing sidebar groups

- src/content/docs/en/tutorial/1-setup/1.mdx
I updated the required Node version on the **Build a Blog** tutorial page to be in accordance with the [**Installation** docs page](https://docs.astro.build/en/install/auto/).
I checked the changelogs and noticed [the minor change in 4.6.0](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md#minor-changes-2) which seems to support this change (even though it has a little typo: `v20.0.3` should be `v20.3.0`).
> Update required Node version on Build a Blog tutorial page

- src/content/docs/en/reference/cli-reference.mdx
Added the flags that are missing from the current documentation for the `astro check` cli command
Currently, only the `--watch` flag is documented, however there are several other options available for the command (`--minimumSeverity` or `--preserveWatchOutput` for example)
- Closes #7542
> Add missing flags for the `astro check` command

- src/content/docs/en/guides/deploy/netlify.mdx
- src/content/docs/en/guides/deploy/render.mdx
- Update require nodejs version for netlify.mdx and render.mdx
- https://github.com/withastro/docs/pull/8217
> Update require nodejs version for netlify.mdx and render.mdx

- src/content/docs/en/guides/markdown-content.mdx
It appears that [Astro 4.5](https://github.com/withastro/astro/releases?q=4.5&expanded=true) stabilized dual theme support for Shiki and updated this property name. `experimentalThemes` did not work for me with `astro@4.8.0`.
> Update `shikiConfig.experimentalThemes` -> `shikiConfig.themes`

- src/content/docs/en/recipes/docker.mdx
This fixes npm warnings that I get using the current suggested Dockerfile, see warnings:
```
[linux/arm64 build-deps 1/1] 
RUN npm install --production=false
npm WARN config production Use `--omit=dev` instead.
RUN npm install --production
npm WARN config production Use `--omit=dev` instead.
```
- Closes #
> docker.mdx: use `--omit=dev` for npm over deprecated `--production`

- src/content/docs/en/guides/integrations-guide/lit.mdx
Added Lit with TypeScript usage example
When you want use TypeScript decorators in Lit component, need to enable `experimentalDecorators` in `tsconfig.json`
- Closes #
> Added Lit with decorators usage example

- src/content/docs/en/guides/cms/apostrophecms.mdx
- src/content/docs/en/guides/cms/umbraco.mdx
Update some links without absolute url
- Closes #
> Update some links without absolute url

- src/content/docs/zh-cn/guides/deploy/gitlab.mdx
- src/content/docs/zh-cn/guides/deploy/google-firebase.mdx
- add missed frontmatter
- Closes #
> i18n(zh-cn): add missed frontmatter

- src/content/docs/fr/guides/integrations-guide/mdx.mdx
- src/content/docs/fr/guides/integrations-guide/preact.mdx
- src/content/docs/fr/guides/integrations-guide/solid-js.mdx
- src/content/docs/fr/guides/integrations-guide/vercel.mdx
- src/content/docs/fr/guides/integrations-guide/vue.mdx
- src/content/docs/fr/guides/testing.mdx
- src/content/docs/fr/reference/error-reference.mdx
Signed-off-by: Thomas Bonnet <thomasbnt@protonmail.com>
Update some files from #8224. 
- [i18n(fr): Update](https://github.com/withastro/docs/commit/99a115f63124358edabac81b85ed39fbe30b9a57) [mdx.mdx](https://github.com/withastro/docs/commit/99a115f63124358edabac81b85ed39fbe30b9a57) 
- [i18n(fr): Update](https://github.com/withastro/docs/commit/9edec37dc172ccd1c330cc5c0b6dbd5eba89b17b) [preact.mdx](https://github.com/withastro/docs/commit/9edec37dc172ccd1c330cc5c0b6dbd5eba89b17b)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/04651fc63e40e6d7130a6dbd3635e95393bae3aa) [solid-js.mdx](https://github.com/withastro/docs/commit/04651fc63e40e6d7130a6dbd3635e95393bae3aa)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/779fd571bf919a1d840ab524541fa94b8b2b44df) …
> i18n(fr): Update some files from #8224

- src/content/docs/fr/reference/publish-to-npm.mdx
Update `publish-to-npm.mdx` file from #8167 (Steeeeeeeeps!)
- Closes #
> i18n(fr): Update `publish-to-npm.mdx` file from #8167 (Steeeeeeeeps!)

- src/content/docs/es/reference/errors/prerender-client-address-not-available.mdx
Translates error page `prerender-client-address-not-available`
- Closes # N/A
> i18n(es): add `prerender-client-address-not-available`

- src/content/docs/es/reference/errors/route-not-found.mdx
Translates error page `route-not-found`
- Closes # N/A
> i18n(es): add `route-not-found`

- src/content/docs/ru/tutorial/5-astro-api/4.mdx
A typo in the get code example - because of this I get the error "No API Route handler exists for the method "GET" for the route "/rss.xml". Found handlers: "Get" When building xml is not created. When editing from get to GET everything works.
- Closes #
> A typo in the code sample 4.mdx

- src/content/docs/zh-cn/guides/integrations-guide/lit.mdx
> i18n(zh-cn): Update `lit.mdx`

- src/content/docs/en/tutorial/3-components/1.mdx
The code wasn't referencing the previous state of `index.astro` from tutorial 2.
> fix minor detail in tutorial 3

- src/content/docs/en/tutorial/4-layouts/1.mdx
> change wording in tutorial

- src/content/docs/en/guides/testing.mdx
This adds headings for types of tests, and increases the heading level of each existing heading.
No text is changed, but content is reordered. (Playwright is moved up to be the first example in its section.)
Releasing this with 4.9 which is going to have changes to the Testing guide anyway, so this means only needing to update the page once for the translators!
> [testing.mdx] restructure page with test types as headings

- src/content/docs/en/guides/internationalization.mdx
- src/content/docs/en/guides/testing.mdx
- src/content/docs/en/reference/configuration-reference.mdx
- src/content/docs/en/reference/container-reference.mdx
- src/i18n/en/nav.ts
Adds the following PRs to docs to correspond to the 4.9 minor release:
#8285 
#8281 
#8367 
#8368 
... with my extra commits below! (Don't just follow the original PRs, there's more here!)
> 4.9.0 minor release docs

- src/content/docs/zh-cn/guides/integrations-guide/vue.mdx
> i18n(zh-cn): Update `vue.mdx`

- src/content/docs/zh-cn/guides/internationalization.mdx
Update `internationalization.mdx`
- #8369
> i18n(zh-cn): Update `internationalization.mdx`

- src/content/docs/zh-cn/guides/testing.mdx
i18n(zh-cn): Update `testing.mdx`
- #8369
> i18n(zh-cn): Update `testing.mdx`

- src/content/docs/ko/guides/testing.mdx
- update `testing.mdx`
- #8369
- Closes #
> i18n(ko-KR): update `testing.mdx`

- src/content/docs/en/guides/content-collections.mdx
the given method of "slicing" out the date part of a Date.toString() did give me some "Mon May 25" and not the expected 2024-05-25 I wanted.
Using the Date.toISOString() solved this for me.
See introductional description. It's simple as that.
- Closes #
> Fix content collection Date string example

- src/content/docs/en/reference/container-reference.mdx
This PR updates the container API, and documents the new way to load renderers.
> feat(container): document new way to load renderers

- src/content/docs/ko/guides/deploy/cloudflare.mdx
- update `cloudflare.mdx`
- #8421 
- Translate untranslated menu
- Closes #
> i18n(ko-KR): update `cloudflare.mdx`

- src/content/docs/en/guides/deploy/zerops.mdx
- It's supposed to be `pnpm-lock.yaml`, not `pnpm-lock.json`
- Closes #
> Minor: fix wrong cache file name in zerops.yml script

- src/content/docs/ko/reference/error-reference.mdx
- src/content/docs/ko/reference/errors/i18n-no-locale-found-in-path.mdx
- add `i18n-no-locale-found-in-path.mdx`
- #8477
- Closes #
> i18n(ko-KR): update `error-reference.mdx`

- src/content/docs/en/tutorial/5-astro-api/2.mdx
**Typo**
inconsistent backslash in title of code-block removed
dashes removed for YAML, since there is content "above"
> fix code block for consistency

- src/i18n/fr/nav.ts
Description (required)
Update translation in nav.ts
Related issues & labels (optional)
Suggested label: i18n
> i18n(fr): add missing translations in nav.ts

- src/content/docs/en/install-and-setup.mdx
Some tiny page edits, but mostly reorganizing content for the "scrollers" to put more common info up front and put less-used content lower on the page (even if it chronologically would come first in terms of the user path).
> [install-and-setup] reorg page content

- src/content/docs/zh-cn/reference/directives-reference.mdx
Translated a phrase at [模板指令参考 | Docs](https://docs.astro.build/zh-cn/reference/directives-reference/#%E9%80%9A%E7%94%A8%E6%8C%87%E4%BB%A4)
> `false`, `null`, or `undefined`: skipped
translated into:
> `false`, `null`, or `undefined`: 跳过
---
For more info see chat history
@ https://discord.com/channels/830184174198718474/973149689610371093/1250832177663443034
> i18n(zh-cn): update untranslate word in directives-reference.mdx

- src/content/docs/ko/tutorial/6-islands/3.mdx
- update `3.mdx`
- #8507
- Closes #
> i18n(ko-KR): update `3.mdx`

- src/components/tutorial/Option.astro
This fix an issue on forced mode, similar to this PR that was already merged https://github.com/withastro/docs/pull/933 
Before (No visual checked indicator):
After:
The starlight and doc website seems to have a great accessibility, great job on this!
- Suggested label:  a11y
> Fix checked indicator for Option component in forced colors

- src/content/docs/en/guides/content.mdx
Marks the "Authoring Content" page as `i18nReady: true` (I see what you did, `es`, `ja` and `zh-cn`!!  😉 )
Also polishes the content before most languages start translating it.
> [guides/content/] polished and ready for i18n!

- src/content/docs/zh-cn/tutorial/6-islands/3.mdx
update 6-islands/3.mdx
- Closes #
- https://github.com/withastro/docs/pull/8507
> i18n(zh-cn): update 6-islands/3.mdx

- src/content/docs/en/guides/deploy/zerops.mdx
- fix wrong link in `zerops.mdx`
- Closes #
> fix: wrong link in `zerops.mdx`

- src/content/docs/en/guides/middleware.mdx
Adding this to the description to clarify that when you use middleware on an on-demand rendered page, you will not have access to things like cookies/headers/...
- Closes #8264 
- Suggested label: Middleware
Discord: tledoux
> Clarify on demand rendering features for middleware

- src/content/docs/en/basics/astro-syntax.mdx
- src/content/docs/en/reference/directives-reference.mdx
I added additional information about `define:vars` directive on two pages:
* https://docs.astro.build/en/basics/astro-syntax/#dynamic-tags
The `define:vars` directive does not work with dynamic tags and I have seen some issues related to that on the main repository so I think it should be clarified.
* https://docs.astro.build/en/reference/directives-reference/#isinline
The statement was not exact since, as stated in #3165: using `define:vars` on `<style />` tag does not automatically apply the `is:inline` directive.
- Closes #6477.
- Suggested label: improve-documentation
ar_phi
(I'm not often connected... but I should get an email when mentioned if needed.)
> Add additional explanation about define:vars directive

- src/content/docs/zh-cn/basics/astro-syntax.mdx
- src/content/docs/zh-cn/reference/directives-reference.mdx
update `astro-syntax.mdx` & `directives-reference.mdx`
- https://github.com/withastro/docs/pull/8585
- Closes #
> i18n(zh-cn): update `astro-syntax.mdx` & `directives-reference.mdx`

- src/content/docs/zh-cn/tutorial/4-layouts/1.mdx
Update `4-layouts/1.mdx`
- https://github.com/withastro/docs/pull/8584
- Closes #
> i18n(zh-cn): Update `4-layouts/1.mdx`

- src/content/docs/en/guides/backend/sentry.mdx
- changed some code to make it more readable `sentry.mdx`
- use `PackageManagerTabs` component
- add tabs at codeblock
- Closes #
> fix: changed some code to make `sentry.mdx` more readable

- src/content/docs/ko/basics/astro-pages.mdx
- update `astro-pages.mdx`
- #8573
- Closes #
> i18n(ko-KR): update `astro-pages.mdx`

- package.json
- pnpm-lock.yaml
This PR updates Lunaria to `v0.1.1` which is important since it fixes a nasty regression in how we link to GitHub's source history.
> Update Lunaria to latest

- src/content/docs/en/basics/layouts.mdx
This PR adds a paragraph to the layout component page, explaining how `<script>` and `<style>` tags should be included in a component containing an `<html>` shell.
- Closes #8603 
- Suggested label: add new content
Discord: lukets4328
> add hint regarding style and script tag locations in layout components

- src/content/docs/ko/basics/layouts.mdx
- update `layouts.mdx`
- #8621
- Closes #
> i18n(ko-KR): update `layouts.mdx`

- src/content/docs/en/community-resources/content.mdx
[Bootstrap](https://getbootstrap.com/) is still one of the most popular CSS frameworks and I was surprised to not find a recipe on the Astro Docs. So after figuring out how to integrate it properly in Astro, I decided to write a recipe myself.
There is an [astro-bootstrap](https://astro-bootstrap.github.io/) integration, but this is not how I would recommend developers to use Bootstrap in Astro.
Astro Discord username: druettiger
> Add recipe to use Boostrap with Astro

- src/content/docs/zh-cn/reference/integrations-reference.mdx
missing a line of code.
- Closes #
> i18n(zh-cn): Fix typo in `integrations-reference.mdx`

- src/content/docs/fr/recipes/reading-time.mdx
* add Steps component from #8167
* make instructions consistent  (each bullet point should start with imperative or infinitive form and not a mix of both)
> i18n(fr): update reading-time recipe

- src/content/docs/en/reference/dev-toolbar-app-reference.mdx
The example has an error because of the missing comma; so if you copy & paste the example code to test, it won't work.
> example does not work, missing comma

- src/content/docs/fr/guides/internationalization.mdx
* Translate [Internationalization (i18n) Routing](https://docs.astro.build/en/guides/internationalization/) (`guides/internationalization.mdx`) in French (added in #5187)
> i18n(fr): add guides/internationalization.mdx

- src/content/docs/en/guides/astro-db.mdx
Changed `overtime` to `over time`. The first is appropriate as a noun ("They scored in overtime") while the second better fits the context ("Your table schema will change over time as your project grows.").
- Suggested label: [typo/link/grammar - quick fix!](https://github.com/withastro/docs/labels/typo%2Flink%2Fgrammar%20-%20quick%20fix%21)
> en-only - Typo fix from 'overtime' to 'over time'

- src/content/docs/en/guides/endpoints.mdx
This page was written before `hybrid` mode existed, and none of the examples or explanation on this page mentions needing `export const prerender = false` for server endpoints.
This PR adds that extra context to the paragraph introducing server endpoints, and also calls this out in the note that the examples need an on-demand rendered mode.
> [endpoints.mdx] update for hybrid mode

- src/components/starlight/Head.astro
- Fixes 404 tracking for in Fathom
- Fathom by default tracks page views using the URL of `<link rel="canonical">`
- Starlight injects a canonical like `/en/404/` or `/zh-cn/404/` for its 404 pages
- This PR tells Fathom to ignore the canonical for 404 pages so that 404 events are reported for the actual URL a user is visiting
> Fix Fathom 404 tracking

- src/content/docs/en/guides/view-transitions.mdx
Docs are not super clear on how to use `transition:persist-props`. Hopefully saying that it is an additional directive meant to be used together with `transition:persist` might help.
See https://github.com/withastro/astro/pull/10136.
> Make clear that transition:persist-props does not work without transition:persist

- src/content/docs/en/guides/markdown-content.mdx
Fixed broken reference links in the English docs. I also did it for the other languages but reverted since its mentioned that I should edit one language at a time. Is it a PR per language or a commit per language?
> Fix broken reference links in Markdown content guide

- src/content/docs/fr/guides/rss.mdx
We have some escape issues in `description` key with French in RSS Guide, that cause some highlighting problems:
> i18n(fr): Fix escaping typo in Rss guide

- src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx
* Add French translation for [Migrating from Next.js](https://docs.astro.build/en/guides/migrate-to-astro/from-nextjs/) (`migrate-to-astro/from-nextjs.mdx`), added in #2232
> i18n(fr): add migrate-to-astro/from-nextjs.mdx

- src/content/docs/zh-cn/guides/markdown-content.mdx
Update `markdown-content.mdx`
- #8728 
> i18n(zh-cn): Update `markdown-content.mdx`

- src/content/docs/ko/guides/markdown-content.mdx
- update `markdown-content.mdx`
- #8749
- Closes #
> i18n(ko-KR): update `markdown-content.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx
While translating this page in French (#8764), I noticed an error in a code block: the `del`/`add` attributes was not matching the sentence above ("*change the set of two curly braces to one set of curly braces*"): the line numbers should be incremented by one.
See the code diff in [Nuxt Local Variables to Astro](https://docs.astro.build/en/guides/migrate-to-astro/from-nuxtjs/#nuxt-local-variables-to-astro), it should be:
> fix(content): update code diff in migrate-to-astro/from-nuxtjs.mdx

- src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx
* Translate in French [Migrating from NuxtJS](https://docs.astro.build/en/guides/migrate-to-astro/from-nuxtjs/) (`migrate-to-astro/from-nuxtjs.mdx`) added in #2232
Since this page does not exist yet, I think we should wait for #8765 to be merged before (I'll update the translation once it's done) so I converted this PR as draft for now.
> i18n(fr): add migrate-to-astro/from-nuxtjs.mdx

- src/components/RecipeLinks.astro
- src/components/RecipesNav.astro
- src/content/config.ts
Adds a new schema property to recipe pages so that we can choose to display a full or alt title in our `RecipeNav` or `RecipeLinks` components
> Updated recipe pages schema and components

- src/content/docs/en/guides/cms/keystatic.mdx
This PR updates the Astro + Keystatic integration documentation to reflect a recent change in the Keystatic API. The `fields.document` field type has been deprecated and replaced with `fields.markdoc`.
Specifically, this PR modifies the following code snippet:
From:
```
content: fields.document({
label: 'Content',
formatting: true,
dividers: true,
links: true,
images: true,
}),
```
to: 
```
content: fields.markdoc({
label: 'Content',
}),
```
Reference Documentation: https://keystatic.com/docs/fields/document
- Closes #
Yes
amir_zezo2001  ( discord Username )
> Update Astro+Keystatic: document to markdoc field

- src/components/LeftSidebar/Sponsors.astro
Netlify has become our official deployment partner. We originally update sponsors with the standard homepage URL for the href but since then we have received a UTM link to replace this with. This PR updates that href URL.
> Update Netlify logo in left sidebar with UTM link

- src/content/docs/en/recipes/build-forms-api.mdx
- Fixes an import statement from the React snippet in `build-forms-api.mdx`, in order to get rid of TypeScript error
- Closes #8783
- Suggested label: `code snippet update`
> Fix an import statement in `build-forms-api.mdx`

- src/content/docs/en/guides/integrations-guide/cloudflare.mdx
As documented in the [Change Log](https://github.com/withastro/adapters/blob/main/packages/cloudflare/CHANGELOG.md) Version 11.0.0 contains a breaking change regarding a new default for the imageService.  This has been changed from 'passthrough' to 'compile'
- Suggested label: documentation
mark_57166
> Update Cloudflare Adapter Documentation - New imageService Default

- src/content/docs/en/guides/imports.mdx
- src/content/docs/en/guides/typescript.mdx
- src/content/docs/en/guides/upgrade-to/v1.mdx
- src/content/docs/en/reference/cli-reference.mdx
Remove all mentioned  `jsconfig`
- Closes https://github.com/withastro/docs/issues/8782
> Remove all mentioned  `jsconfig`

- src/content/docs/zh-cn/guides/imports.mdx
- src/content/docs/zh-cn/guides/typescript.mdx
- src/content/docs/zh-cn/reference/cli-reference.mdx
Update `cli-reference.mdx` & `imports.mdx` & `typescript.mdx`
- #8818 
> i18n(zh-cn): Update `cli-reference.mdx` & `imports.mdx` & `typescript.mdx`

- src/pages/open-graph/_fetchFont.ts
I forgot to add an environment variable on Netlify used for downloading our brand font for open graph images. This resulted in images building using Inter instead of Obviously as the headline font.
Example:
I have now fixed that in the Netlify dashboard, but the reason this error was possible was that we were still checking for a `VERCEL` environment variable before throwing errors. This PR updates this to check the equivalent `NETLIFY` variable instead.
I also considered using the more generic `CI` variable, but docs gets built a bunch of CI places that don’t need the custom font (our GitHub Actions, `withastro/astro` smoke tests, etc.), so I think we probably can’t.
> Fix environment variable check for Netlify

- src/pages/open-graph/_fetchFont.ts
Fixes errors with PRs from forks in Netlify preview deploys.
> Make check for `FONT_CREDENTIALS` less strict in preview deploys

- src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
- src/content/docs/fr/guides/integrations-guide/mdx.mdx
- src/content/docs/fr/guides/integrations-guide/vercel.mdx
- src/content/docs/fr/guides/markdown-content.mdx
- src/content/docs/fr/reference/configuration-reference.mdx
- src/content/docs/fr/reference/errors/config-legacy-key.mdx
* Add French translation for [Configuration reference](https://docs.astro.build/en/reference/configuration-reference/) (`reference/configuration-reference.mdx`)
* Add changes made in #8796
* Fix typo (see #8867)
> i18n(fr): add configuration-reference.mdx

- src/content/docs/fr/guides/images.mdx
- src/content/docs/fr/guides/markdown-content.mdx
- src/content/docs/fr/reference/integrations-reference.mdx
* Add changes from #8796 to French translations
Note: only `images.mdx`, `markdown-content` and `integrations-reference.mdx` are updated in this pull request because:
* `api-reference.mdx` is not yet translated
* `configuration-reference.mdx` is not yet merged so the changes have been added to #8837
* `cli-reference.mdx` is already updated in another PR, see #8830
> i18n(fr): update `images`, `markdown-content` and `integrations-reference`

- src/content/docs/fr/reference/error-reference.mdx
- src/content/docs/fr/reference/errors/env-invalid-variables.mdx
* Add changes made in #8835 to French translations of `error-reference.mdx` and `env-invalid-variables.mdx`
> i18n(fr): update error-reference.mdx & env-invalid-variables.mdx

- src/content/docs/en/reference/container-reference.mdx
This PR documents a API that was added to the container API
https://github.com/withastro/astro/pull/11486
> feat: document `addClientRenderer`

- src/content/docs/ko/guides/deploy/gitlab.mdx
- update `gitlab.mdx`
- #8811
- Closes #
> i18n(ko-KR): update `gitlab.mdx`

- src/components/CMSGuidesNav.astro
Alphabetize CMS guides' nav.
- Moves #8860 closer to closing
> CMS guides nav: sort alphabetically (part of #8860)

- src/content/docs/zh-cn/guides/deploy/gitlab.mdx
> i18n(zh-cn): Update `gitlab.mdx`

- src/util/getPageCategory.ts
This PR marks pages under `/guides/integrations-guide/*` as part of our “Learn” category for search purposes. This includes individual integration pages like `@astrojs/mdx` etc.
The category had previously been changed to “Recipes” when integration guides were grouped with our guides to deployment, CMS etc. but after the recent sidebar shuffle, restoring these to “Learn” makes sense.
Note that this change will only take effect after merging this PR and reindexing Algolia. That happens automatically every Monday, but we can run a manual reindex if this feels high enough priority.
> Fix search category for integration guides

- src/content/docs/en/reference/api-reference.mdx
Improve [`Astro.redirect` documentation](https://docs.astro.build/en/reference/api-reference/#astroredirect) in `api-reference.mdx`:
* Add `<Since />` (released in `0.25.0`, see https://github.com/withastro/astro/pull/2798)
* Add the function type
* Clarify differences between SSR and static output
- Closes #8917
- Suggested label: improve documentation
> fix(api-reference): improve Astro.redirect documentation

- src/content/docs/en/guides/routing.mdx
* Update `page.size` default (see https://github.com/withastro/astro/pull/11561)
* Add `page.url.first` and `page.url.last` to the Page interface (see https://github.com/withastro/astro/pull/11176)
* Add a `ReadMore` link to the API reference page
- Closes #8929
- Suggested label: improve-documentation
> fix(guides/routing): update Page interface and add link to API reference

- src/content/docs/en/basics/project-structure.mdx
We're working on ways to reorganize, or link to, the content in the "[Configuring Astro](https://docs.astro.build/en/guides/configuring-astro/)" guide.
As recommended by @sarah11918 in https://github.com/withastro/docs/issues/8918#issuecomment-2255579753, this PR will add the info on supported config file types from the "Configuring Astro" guide to the "[Project Structure](https://docs.astro.build/en/basics/project-structure/)" basics page. This will give new users a quick reference when they're learning how to set up their projects.
- https://github.com/withastro/docs/issues/8918
- Suggested label: [consistency/formatting](https://github.com/withastro/docs/labels/consistency%2Fformatting), [good first issue](https://github.com/withastro/docs/labels/good%20first%20issue) 
If you are a …
> Add config file types to Project Structure page

- src/content/docs/en/reference/api-reference.mdx
This PR partially addresses issue https://github.com/withastro/docs/issues/8855 by adding an example for named slot functions to the reference page for `Astro.slots.render()`
- Partially addresses: https://github.com/withastro/docs/issues/8855
> Add reference for named slot functions

- src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx
[docs] Simple typos in the FR page about Docusaurus migration guide.
> i18n(fr): Fix typos in docusaurus migration guide

- src/content/docs/fr/guides/content-collections.mdx
Update `guides/content-collections.mdx` from #8967
> i18n(fr): Update `guides/content-collections.mdx` from #8967

- src/content/docs/fr/reference/errors/actions-used-with-for-get-error.mdx
Add `reference/errors/actions-used-with-for-get-error.mdx` from #8967
> i18n(fr): Add `reference/errors/actions-used-with-for-get-error.mdx` from #8967

- src/content/docs/fr/reference/errors/action-query-string-invalid-error.mdx
Add `reference/errors/action-query-string-invalid-error.mdx` from #8967
> i18n(fr): Add `reference/errors/action-query-string-invalid-error.mdx` from #8967

- src/content/docs/en/guides/middleware.mdx
Fix typo in middleware.mdx
- Closes #
> Fix typo in middleware.mdx

- src/content/docs/en/guides/integrations-guide/sitemap.mdx
This PR updates the docs for the `@astrojs/sitemap` integration.
My main aim was to be able to link directly to the information about linking to the sitemap in `robots.txt` for https://github.com/withastro/starlight/pull/2083 (to avoid duplicating these docs in the Starlight docs).
But while there I realised this page is fairly dusty and could use a small refresh.
Reorganised, reworded, and re-prioritised things.
> Overhaul `@astrojs/sitemap` docs

- src/content/docs/fr/guides/imports.mdx
* Apply changes from #8981 to French translation of `guides/imports.mdx`
> i18n(fr): update `guides/imports.mdx`

- src/content/docs/fr/guides/middleware.mdx
* Fix typo in `guides/middleware.mdx`  (see #8994)
> i18n(fr): fix typo in `guides/middleware.mdx`

- src/content/docs/fr/guides/routing.mdx
* Fix typo in French translation of `guides/routing.mdx` (see #8993)
> i18n(fr): fix typo in `guides/routing.mdx`

- src/content/docs/zh-cn/guides/content-collections.mdx
update content-collections.mdx
- https://github.com/withastro/docs/pull/8967
> i18n(zh-cn): update `content-collections.mdx`

- src/content/docs/en/guides/integrations-guide/mdx.mdx
`rehype-minify-html` doesn't exist. Replace with equivalent module.
> Replace rehype-minify-html with rehype-preset-minify in mdx docs

- src/content/docs/zh-cn/guides/imports.mdx
> i18n(zh-cn): Update `imports.mdx`

- src/content/docs/en/guides/upgrade-to/v5.mdx
Documents Lit integration removal
https://github.com/withastro/astro/pull/11680
> Document Lit integration removal

- src/content/docs/en/guides/view-transitions.mdx
* Add missing closing quote in a code block `title`
Before:
After:
> fix(guides): typo in `view-transitions.mdx` code block title

- src/content/docs/en/reference/integrations-reference.mdx
Adds documentation for the new `astro:route:setup` hook based on the core PR below.
The main use of this new hook is to configure route options dynamically (in this case, only the `prerender` option for now). See the core PR for more info!
- Closes #
> Document new `astro:route:setup` hook

- src/components/starlight/Search.astro
This PR explicitly sets `attributesToHighlight` in the DocSearch client, which brings back categorisation of search results. Not 100% clear what changed on Algolia’s end to require this, but this should at least address the search issues users have been reporting.
Shout out to @levimichael for helping us out with this!
> Fix Algolia DocSearch result categorisation

- src/content/docs/fr/install-and-setup.mdx
* Apply changes from #9081 to French translation of `install-and-setup.mdx`
> i18n(fr): update `install-and-setup.mdx`

- src/content/docs/en/guides/view-transitions.mdx
It's always good to know that you can add `{once: true}` as an option to `addEventListener`.
But for the `astro:page-load` example, it's a deal-breaker. The whole point here is that the code runs every time the page loads, not just once.
While people can grasp this pretty quickly, Kapa was completely caught off guard and insisted on using `once: true` as a best practice ;-)
This came up in a discord discussion: https://discord.com/channels/830184174198718474/1075516604428857344/1273972688788000811
> Remove misleading reference to {once: true} from astro:page-load example

- src/content/docs/en/guides/content-collections.mdx
This PR addresses an issue in the [Content Collection](https://docs.astro.build/en/guides/content-collections/#the-astro-directory) docs where running the given command in the tip callout does not work on Bash shell - version `5.1.16(1)`. Executing the command as-is renders the newline sequence within the `.gitignore` file, i.e., `\n.astro`
We need to use the `-e` flag to tell `echo` to interpret backslashes. As a sidenote, the same command works fine on `ZSH` without any changes.
- Closes  Didn't find any existing issue for this.
- Suggested label: `code snippet update` and/or `improve documentation`
> fix: newline not being interpreted while adding .astro directory to gitignore file

- src/content/docs/en/guides/integrations-guide/netlify.mdx
Since v4, the Netlify adapter has used a single `@astrojs/netlify` import, rather than the separate `static` one. This was likely overlooked when the docs were updated in https://github.com/withastro/adapters/pull/84.
I tested the import like this works as described, so it’s a simple typo fix effectively.
> Fix import in Netlify adapter guide

- src/content/docs/en/guides/integrations-guide/solid-js.mdx
This PR fixes a typo in the `import` statement in the SolidJS integration guide. Specifically in the `devtools` section: https://docs.astro.build/en/guides/integrations-guide/solid-js/#devtools
- Closes #
Yes
discord: spitlbeans
> docs: fix import typo in solid-js integration guide

- src/content/docs/en/reference/configuration-reference.mdx
Fixes the documentation in the [Querying and rendering with the Content Layer API section](https://docs.astro.build/en/reference/configuration-reference/#querying-and-rendering-with-the-content-layer-api) section, where a variable named `entry` was used without a prior definition. It has been updated to correctly reference the `post` variable instead.
Username of Astro Discord: fbuireu
> docs: fix entry variable

- src/content/docs/en/guides/cms/strapi.mdx
The comment in the env file for the strapi integration started with `//` instead of `#`  and this change replaced it. 
- Closes #9189
> change comment starter in strapi.mdx

- src/content/docs/en/guides/routing.mdx
In v4.12 we added `page.url.first` and `page.url.last`. While they are documented, they aren't used in the routing guide.
This PR adds that
> feat: add use of `first` and `last` APIs to routing guide

- src/content/docs/en/guides/routing.mdx
Fix typo in `routing.mdx`
the hightlight RegExp now is including the keyword `first` and `last`.
Suggested label: `typo/link/grammar - quick fix!`
> Fix typo in `routing.mdx`

- src/content/docs/en/guides/astro-db.mdx
Fix the language tag from `env` to `dotenv` found on T&D
> Fix language tags on dotenv examples for Astro DB

- src/content/docs/en/guides/actions.mdx
- src/content/docs/en/reference/api-reference.mdx
- Fixes the Actions guide to say since v4.15
- Update the API reference description to better capture the actions featureset
- Add backticks to `astro:actions` on the API reference header
- Closes #
> Fix Actions version and API reference verbage

- src/content/docs/en/reference/api-reference.mdx
This PR improves the `defineAction()` reference docs to better describe the signature of the `handler()` option and mention the `context` argument.
Also took the liberty of removing the extra `<Since>` components on `handler` and `input` sections — felt excessive to add those when they are properties of `defineAction()`, which means they were added at the same time.
> Improve `handler()` reference docs

- src/content/docs/en/guides/astro-db.mdx
This PR adds a missing code block `ts` language identifier spotted today during Talking & Talking in the Astro DB guide.
[Preview direct link](https://deploy-preview-9262--astro-docs-2.netlify.app/en/guides/astro-db/#drizzle-orm)
Before:
After:
> Add missing code block language identifier in `guides/astro-db`

- src/content/docs/ko/guides/internationalization.mdx
- update `internationalization.mdx`
- #9224 
- Closes #
> i18n(ko-KR): update `internationalization.mdx`

- src/content/docs/zh-cn/reference/integrations-reference.mdx
Update `integrations-reference.mdx`
- #9224 
> i18n(zh-cn): Update `integrations-reference.mdx`

- src/content/docs/en/reference/cli-reference.mdx
- Updates the docs for the programmatic APIs for Astro commands `dev`, `build`, `preview` and `sync`.
- Document `DevServer`, the return type of `dev`
- Document `PreviewServer`, the return type of `preview`
- Found those mistakes and missing docs while working on the docs for https://github.com/Fryuni/inox-tools/pull/158
> Update docs for advanced APIs

- src/content/docs/fr/reference/cli-reference.mdx
* Add changes from #9308 to French translation of `cli-reference.mdx`
* Add missing space before colon for `Type` and `Default` in French translation (I also replaced `Défaut` with `Par défaut` because it seems more correct to me in French... and this is the syntax we use most often it seems).
> i18n(fr): update `cli-reference.mdx`

- src/content/docs/en/guides/client-side-scripts.mdx
Changed `constructor` to `connectedCallback`. It's less code and more correct.
The [custom elements spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance) explicitly recommends implementing setup logic in `connectedCallback` rather than the constructor. See also: https://nolanlawson.com/2024/01/13/web-component-gotcha-constructor-vs-connectedcallback/
- Suggested label: improve documentation
> use `connectedCallback` instead of `constructor`

- src/content/docs/zh-cn/tutorial/4-layouts/1.mdx
Update `tutorial/4-layouts/1.mdx`
- #9271 
> i18n(zh-cn): Update `tutorial/4-layouts/1.mdx`

- src/content/docs/en/basics/layouts.mdx
This lightly updates the `/basics/layouts.mdx` guide page to:
- Prepare for a rewrite of the existing Markdown page that will hold more of the Markdown-specific content (e.g. the removed code example of exported properties) so that the Layout page is less cluttered and mostly focused on the pattern
- Simplify by downplaying MDX and concentrating on Markdown (our built-in, first class citizen) (as the new Markdown page will, moving some content directly to the MDX page)
The only content temporarily *lost* in published docs as a result of this is the code example, but a version of that will exist in the new Markdown page, where it is more helpful and discoverable.
> Layouts page rewrite

- src/content/docs/en/basics/astro-pages.mdx
Removed a section linking to itself.
Took the opportunity to provide better, and future-proof, content collections nudging.
> Remove self-referential link in astro-pages.mdx

- src/content/docs/en/guides/integrations-guide/mdx.mdx
- src/content/docs/en/guides/markdown-content.mdx
- src/content/docs/en/guides/troubleshooting.mdx
Separates some content out from the Markdown page and puts it on the MDX page and the troubleshooting page.
I can't make the corresponding Markdown page changes here/yet because that's a lot of link resolving that I've already fixed on the beta docs branch. :smile:  
So that means this content will be duplicated until I can resolve them, but I think that's fine. It will give translators a chance to translate these early, and when the Markdown page is updated with content removed, it won't be a problem.
> [mdx] Adds usage information, taken out of the Markdown guide

- src/content/docs/en/reference/container-reference.mdx
- src/content/docs/en/reference/integrations-reference.mdx
- Lit integration was removed, a few mentions of it remained.
> Remove remaining references to Lit integration

- src/content/docs/zh-cn/reference/errors/astro-glob-used-outside.mdx
The file is up to date! (the English version's typo cause the translation status change in #6952 )
To make the `zh-cn` translation status change, I delete an empty line to be able to commit as #9389.
- #6952 
> i18n(zh-cn): Update `astro-glob-used-outside.mdx`

- src/content/docs/zh-cn/reference/configuration-reference.mdx
Update `configuration-reference.mdx`
To make the `zh-cn` translation status change, I review the doc and find other typos to commit.
- #9383 
> i18n(zh-cn): Update `configuration-reference.mdx`

- src/content/docs/en/reference/adapter-reference.mdx
While I was reading a PR related to `adapter-reference.mdx`, I thought we could update the format to be consistent with `configuration-reference.mdx` and `api-reference.mdx`. Since v5 is set to replace the current version, I thought it might be more useful to update directly to that branch.
* Add `Type:`, `Default:` and `Since` where appropriate
* I moved some types from the section heading to `Type:`
* Fix/Rename some types
* Fix some line numbers to highlight in code blocks
**A few hesitations:**
* Some properties are optional but are not explicitly marked with `undefined` as an accepted type. So in `Type:` I only put the accepted types (the property should not be added if it is `undefined`)
* `envGetSecret` is in the `Adapter features` section but the type in the `next` branch of …
> fix(v5): format `adapter-reference.mdx`

- src/content/docs/fr/reference/api-reference.mdx
* Update French version of `api-reference.mdx` with changes from #9422 and from #9261 (it seems we missed some updates)
> i18n(fr): update `api-reference.mdx`

- src/content/docs/en/guides/cms/craft-cms.mdx
This PR adds a new Community Resource link to the Craft CMS guide. The link is to a guide to building a static Astro site with the option of caching CMS content as an Astro content collection, which enables building Astro remotely even if Craft is local-only.
- Suggested label: add-new-content
> Craft CMS guide: add SSG guide w/ optional cache community resource

- src/content/docs/en/install-and-setup.mdx
Update the "Install from the CLI wizard" section, on step 2, where it says "If you skipped the `npm install` step during the CLI wizard..." to a more identifiable name reflecting the current CLI wizard, where it says "Install dependencies?" instead of "npm install" and to not be focused on npm since other package managers are available. I'm not 100% sure if the question mark should be present or not though.
Also, the backticks were removed since I believe this text would not be considered appropriate inside a code tag.
> fix: Update install-and-setup.mdx

- src/content/docs/pt-br/basics/astro-syntax.mdx
Update and review i18n/pt-br/basics/astro-syntax.mdx file
> i18n(pt-BR): update `astro-syntax.mdx`

- src/content/docs/en/guides/astro-db.mdx
Following the current instructions to create a Turso DB from the exported dump using `turso db create --from-dump` will create all the tables required for the data without Astro DB being aware of those tables.
This causes a conflict later on when trying to push the schema since, as far as Astro DB knows, it hasn't created any table in the new DB. Trying to create them again fails and leaves the DB in an inconsistent state.
> Update instructions to migrate from Studio to Turso

- src/content/docs/en/guides/deploy/fleek.mdx
Fix an ordered list numbering. (There were two number fours.)
It doesn't seem to affect the published page (the Steps component seems to fix the numbering). That said, it's best to fix the numbering now to avoid an error if `Steps` is ever changed.
- Suggested label: typo
> fix: update ordered list numbering in `guides/deploy/fleek.mdx`

- src/content/docs/en/guides/deploy/sst.mdx
Greetings Astronauts!
Updating the SST tutorial with snippets and links for SST v3.
> Update to SST v3

- src/content/docs/en/guides/integrations-guide/mdx.mdx
This removes mention of the frontmatter `layout` property available to MDX files from the MDX page so we can consolidate all mention of it to the Layouts page itself.
As we are not sure how much we want to promote this, leaving it to the Layouts page still makes the information prominently available without encouraging/assuming its use. Importing and using an Astro component as a layout is a more flexible option than the "magic" special property, so it will be easier to mention any limitations and caveats in just one place.
- Closes #9166 
While this PR itself isn't *exactly* what the issue asked for, I do think a few recent changes to this, the layouts and the markdown pages all combined will work together to prevent people trying to use named slots in MDX with the special frontmatter …
> [mdx] remove mention of layout frontmatter property

- src/content/docs/fr/guides/integrations-guide/mdx.mdx
* Add changes from #9474 to French translation of `integrations-guide/mdx.mdx`
* Remove a comment in a code block (removed in #8224)
> i18n(fr): update `integrations-guide/mdx.mdx`

- src/content/docs/fr/guides/deploy/clever-cloud.mdx
* Translate `guides/deploy/clever-cloud.mdx` in French (see #9030)
> [!NOTE]
> I translated the UI strings because Clever Cloud seems to be available in French, but I didn't check if the translation is the same as the UI because we need an account...
> i18n(fr): add `guides/deploy/clever-cloud.mdx`

- src/content/docs/en/guides/upgrade-to/v5.mdx
> feat: update upgrade guide

- src/content/docs/en/guides/cms/tina-cms.mdx
- src/content/docs/es/guides/cms/tina-cms.mdx
- src/content/docs/fr/guides/cms/tina-cms.mdx
- src/content/docs/ko/guides/cms/tina-cms.mdx
- src/content/docs/zh-cn/guides/cms/tina-cms.mdx
The URL used in [Tina CMS Themes section](https://docs.astro.build/en/guides/cms/tina-cms/#themes) appears to contain a typo or has been updated since it was added. The current URL results in a 500 error due to an extra hyphen. So I updated it in all languages.
- Closes #9510
- Suggested label: typo
> [i18nIgnore] fix: updates the URL of a Tina CMS theme example

- src/content/docs/fr/guides/framework-components.mdx
This PR fixes a broken link due to a markup issue in the French version of the `guides/framework-components` [page](https://docs.astro.build/fr/guides/framework-components/).
This PR does a few things:
- Fix the Markdown markup issue
- Move the link to only the "îles" word to match the [English version](https://docs.astro.build/en/guides/framework-components/) only linking the word "islands"
- `i` → `î` in the "îles" word to fix a typo
- Closes #
> i18n(fr): fix broken link in `guides/framework-components`

- src/content/docs/en/reference/image-service-reference.mdx
Local image services have a property `propertiesToHash` which is missing from the docs. This change adds it along with a short explanation of what it does and what it falls back to if not passed.
- Closes #9169 
- Suggested label: add new  content
> Add info about propertiesToHash to image-service-reference.mdx

- src/content/docs/en/recipes/modified-time.mdx
Add a note that informs users that some deployment platforms can cause issues with git history. 
Related discussion is here #8779 
- Closes #8779
> Add note in last modified time recipe

- src/content/docs/en/reference/directives-reference.mdx
adds note about `fallback` slot to `client:only` docs. copied directly from the suggestion in #8805
closes #8805
> docs: add note about client:only `fallback` slot

- src/content/docs/ko/guides/client-side-scripts.mdx
- update `client-side-scripts.mdx`
- #9519
- Closes #
> i18n(ko-KR): update `client-side-scripts.mdx`

- src/content/docs/pt-br/recipes/captcha.mdx
i18n(pt-BR): update `recipes/captcha.mdx` file
> i18n(pt-BR): update `recipes/captcha.mdx` file

- src/content/docs/en/guides/server-side-rendering.mdx
A code snippet has been updated in #9527 but not the lines to highlight. Since there is now an additional line, this should be `10` (`Astro.cookies.set`) not `9` (a blank line).
> fix: line highlighting in `server-side-rendering.mdx`

- src/content/docs/fr/guides/server-side-rendering.mdx
Update a code snippet in the French translation of `server-side-rendering.mdx` (see #9527 and #9533)
> i18n(fr): update `server-side-rendering.mdx`

- src/content/docs/ko/reference/directives-reference.mdx
- update `directives-reference.mdx`
- #9516
- Closes #
> i18n(ko-KR): update `directives-reference.mdx`

- src/content/docs/ko/recipes/modified-time.mdx
- update `modified-time.mdx`
- #9520
- Closes #
> i18n(ko-KR): update `modified-time.mdx`

- src/content/docs/en/guides/on-demand-rendering.mdx
Updates `on-demand-rendering.mdx` to match the changes from PR #9527 
> Updates on-demand-rendering.mdx

- src/content/docs/en/guides/actions.mdx
I believe addtoCard is a small spelling error and the correct name for the action should be addToCart. Sorry if I misunderstood.
- Closes #
> change action name from addToCard to addToCart

- src/content/docs/en/guides/routing.mdx
Added a missing word in the first sentence of the **rewrites** section in the routing guide on the en docs.
- Closes #
- Suggested label: typo/link/grammar - quick fix!, 4.0
> [i18nIgnore] Docs(en-only): Added missing word on routing guide

- src/content/docs/en/guides/markdown-content.mdx
Change is discussed in #9403 
I copied the @sarah11918 suggestion in my PR
- Closes #9403
> Clarify markdown flavor in Markdown Page

- src/content/docs/en/guides/migrate-to-astro/from-wordpress.mdx
Adds more resources to the list of community links on the Migrate to Wordpress page
> Update community WordPress resources

- src/content/docs/ko/reference/components-reference.mdx
- create `components-reference.mdx`
- Closes #
> i18n(ko-KR): create `components-reference.mdx`

- src/content/docs/en/guides/content-collections.mdx
- src/content/docs/en/guides/upgrade-to/v5.mdx
The restrictions on content layer collections in `src/content` no longer apply, so we can remove references to them.
- Closes #
> fix: remove outdated content folder info

- src/content/docs/en/guides/cms/builderio.mdx
This PR fixes the return format of the `posts.map()` function in the `getStaticPaths` method. The previous format was causing issues with [describe the problem if you know it].
- Updated the return statement in `posts.map()` to use parentheses instead of square brackets
- Removed an unnecessary nested array
> Fix posts.map() return format in getStaticPaths function

- src/content/docs/en/guides/media/cloudinary.mdx
The pnpm official documentation recommends using the `add` command instead of `install` when installing new packages as follows:
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
Currently it works the same without any differences, but the document clearly distinguishes these two commands.
This means that you have the flexibility to adapt to changes, such as changing or removing commands in future versions.
- fix wrong external link
- fix wrong inline code highlight
> fix: update `cloudinary.mdx`

- src/content/docs/en/guides/view-transitions.mdx
Add an example about executing scripts after page transitions 
Copied from Sarah's comment on #8000 
- Closes #8000
> Add example of script re-execution after transition

- src/content/docs/en/guides/on-demand-rendering.mdx
* Typo fix (`every`)
* Updates some code snippet due to some concerns about highlighting (I only updated from the previous/next example but maybe all examples should use the same format: either simple highlighting or `ins`)
* Updates the file name of a code snippet because the usage of `Astro.params` seemed wrong otherwise
* Adds a suggestion regarding `Astro.redirect` in `Response` subsection
- Suggested label: 5.0, 5.0.0-beta, code snippet update
> fix(5.0.0): nitpicking and suggestions regarding `on-demand-rendering.mdx`

- src/content/docs/en/guides/server-side-rendering.mdx
Following the discussion in #9673, I updated two sections regarding `Response` in `guides/server-side-rendering.mdx`. This is mostly code snippet updates to show the user that he can use `prerender = false` and that he can also return a `Response` using `Astro.redirect`.
> update a code snippet in `guides/server-side-rendering.mdx`

- src/content/docs/en/reference/api-reference.mdx
Based on a discussion in #9673, I updated the `Astro.params` section with the following changes:
* Move the code snippet under `In SSR builds,` to `In Static builds`
* Add a new code snippet under `In SSR builds` to show an example specific to SSR
- Suggested label:  code snippet update
> fix(api-reference): add a code snippet for Astro.params with SSR

- src/content/docs/fr/guides/rss.mdx
* Adds changes from #9601
* Removes `type: recipe` from the frontmatter (see #8239)
* Removes additional blank lines and reorganize imports to more easily compare changes in the file
* Fixes some typo (e.g. `fr-fr` [should be lowercase](https://www.rssboard.org/rss-language-codes))
* Rewords some sentences
> i18n(fr): update `guides/rss.mdx`

- src/content/docs/en/guides/imports.mdx
Fixes some typo in `guides/imports.mdx` (unwanted backtick, missing period, `paramaters` > `parameters`, and I think a missing `more` in `Read about`)
> fix(guides): typo in `guides/imports.mdx`

- src/content/docs/en/guides/internationalization.mdx
- src/content/docs/en/guides/upgrade-to/v4.mdx
Puts `locales` before `defaultLocale`
- Closes #
> feat(next): tweak i18n

- src/content/docs/en/install-and-setup.mdx
- update `install-and-setup.mdx` to make use of the `PackageManagerTabs` component.
- Suggested label: design
> docs: use `PackageManagerTabs` for `install-and-setup.mdx` code-blocks

- src/content/docs/en/guides/actions.mdx
Add the size limitation of cookies to the Astro Actions page - specifically the "Update the UI with a form action result" section - as this limitation can currently cause a the Action to silently fail.
Discord username: rstainsby
https://github.com/withastro/docs/issues/9766
Closes #9766
Suggested label: Improves Documentation
> docs: 9766 explain Astro Actions cookie size limitation

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
Originally posted in a [discord support question](https://discord.com/channels/830184174198718474/1298411077985370196/1298411077985370196):
As is, the docs instructions for creating a custom Markdoc image tag cause two failures. See [repro](https://stackblitz.com/edit/github-r72f4w?file=src%2Fcontent%2Fdocs%2Fintro.mdoc)
1. one complains about a missing Markdoc closing tag.
2. The other...
```
[ERROR] **src/content/docs/intro.mdoc** contains invalid content:
- Invalid attribute: 'width'
- Invalid attribute: 'height'
- Invalid attribute: 'caption'
```
...seems to be because the Markdoc image tag is configured in `markdoc.config.mjs` using only the default attributes for Markdoc's image tag, which don't include `width`, `height`, or `caption`. `console.log(nodes.image.attributes)` yields: …
> Add missing markdoc closing tag and image node attributes in "Create a custom Markdoc image tag"

- src/content/docs/en/reference/modules/astro-content.mdx
- update wrong codeblock in `astro-content.mdx`
- Closes #
> fix: wrong codeblock in `astro-content.mdx`

- src/content/docs/ko/guides/actions.mdx
- update `actions.mdx`
- #9687
- Closes #
> i18n(ko-KR): update `actions.mdx`

- src/content/docs/ko/guides/content-collections.mdx
- update `content-collections.mdx`
- #9687
- Closes #
> i18n(ko-KR): update `content-collections.mdx`

- src/content/docs/zh-cn/guides/actions.mdx
- src/content/docs/zh-cn/reference/errors/actions-returned-invalid-data-error.mdx
- src/content/docs/zh-cn/reference/modules/astro-actions.mdx
- add `astro-actions.mdx`
- update corresponding link in `actions.mdx` & `actions-returned-invalid-data-error.mdx`
- #9687
> i18n(zh-cn): add `astro-actions.mdx` and update `actions.mdx` & `actions-returned-invalid-data-error.mdx`

- src/content/docs/zh-cn/reference/modules/astro-assets.mdx
add `astro-assets.mdx`
- #9687 
- #9820 
> i18n(zh-cn): add `astro-assets.mdx`

- src/content/docs/en/guides/cms/craft-cms.mdx
Spotted during T&D: All other guides use ` & Astro` in their title, Craft CMS was the only exception. So I updated its title to be consistent with the others.
> fix: update Craft CMS title to be consistent with others guides

- src/content/docs/en/guides/astro-db.mdx
- src/content/docs/fr/guides/astro-db.mdx
- src/content/docs/ko/guides/astro-db.mdx
- src/content/docs/zh-cn/guides/astro-db.mdx
This PR updates the language identifier of various code blocks for environment variables or dotenv files. This was initially spotted a long time ago in a T&D session but only got around to fixing it now.
The `env` language identifier is not a [supported Shiki language ID](https://shiki.matsu.io/languages#languages) and `dotenv` is the correct language identifier for these code blocks.
These fixes 2 issues:
- Removes warning messages in the build logs for each invalid code block language:
```sh
[WARN] [astro-expressive-code] Found unknown code block language "env" in document "src/content/docs/en/guides/astro-db.mdx". Using "txt" instead. You can add custom languages using the "langs" config option.
```
- Adds proper syntax highlighting to the code blocks:
|        | Preview         |
| …
> [i18nIgnore] fix: code blocks `env` language identifier

- src/content/docs/de/basics/astro-syntax.mdx
- update `astro-syntax.mdx`
- #9888 
- Closes #
> i18n(de): update `astro-syntax.mdx`

- src/content/docs/en/tutorials/add-content-collections.mdx
Following a request for help on Discord, I saw that an import was missing in `tutorials/content-collections.mdx` for v5. In addition, I took the opportunity to update two other code snippets.
* **Step 5:** the `glob` loader import was missing
* **Step 8:** `MarkdownPostLayout` was imported when it is not needed at this step, so I removed it
* **Step 9:** `MarkdownPostLayout` is only used in this step, so I highlighted the import in addition to its use which is already highlighted
> fix(v5): add missing import in content collection tutorial

- src/content/docs/en/guides/middleware.mdx
While working with Ben on its rewrite of Astro Actions, I came across a technical limitation which can't be fixed.
I thought that it would be helpful to explain this limitation in case users try to encounter it.
> feat(middleware): more explanation for `next()` rewrite

- src/content/docs/en/guides/integrations-guide/alpinejs.mdx
`Alpine.js` examples link pointed to `latest` instead of `main`. This PR fixes it.
> fix `Alpine.js` examples link

- src/content/docs/fr/reference/configuration-reference.mdx
* Removes the blank line between the sentence and the list (see #9933)
Note: #9933 also fixes the escaping for \`\`\` but this was already fixed in the French translation (see #9934).
> i18n(fr): update `configuration-reference.mdx`

- lunaria/components.ts
- package.json
- pnpm-lock.yaml
This PR updates Lunaria to the latest prerelease version, which solves a few small bugs. Additionally, I fixed a link in the Lunaria dashboard, outdated files should get a link to their file contents vs a link to create a new file as it was happening (which should be reserved only when the file is missing)
- Closes #
> Update Lunaria version and fix dashboard link

- package.json
- pnpm-lock.yaml
- scripts/docgen.mjs
- scripts/error-docgen.mjs
Upgrades the jsdoc-api package, used in the docgen scripts. The current version has a bug that causes docgen to fail when a Mac tmp directory starts with an underscore. The latest version has a fix. It's a breaking change, so I've updated the usage too.
https://github.com/jsdoc2md/jsdoc-api/issues/19
https://github.com/jsdoc/jsdoc/issues/1712
- Closes #
> fix: upgrade jsdoc-api

- src/content/docs/zh-cn/reference/cli-reference.mdx
Update `cli-reference.mdx`
- #9895 
- #10018 
> i18n(zh-cn): Update `cli-reference.mdx`

- src/content/docs/en/guides/view-transitions.mdx
Hy @sarah11918 👋🏼, after some thinking I managed to come up with a imho minimal change to the example that ensures it's technically correct without introducing further complexity. The most challenging part was resisting the urge to add excessive explanation and background details below the example. 
Would you please rephrase the text as you see fit for docs?
I hope this approach works, but I would also be fine with just adding `transition:name="root"` to the example without additional context. 🤓 
Closes #9977
> Ensure that the transition:animate="none" example is technically correct

- src/content/docs/en/reference/modules/astro-actions.mdx
Update to the `astro-actions` page, adding documentation for `isActionError` and also correcting the error raised with `isInputError`.
As per [this discord chat](https://discord.com/channels/830184174198718474/853350631389265940/1308047322789318697) I am documenting the `isActionError` utility function. Furthermore, I am updating the documentation for `isInputError` that shows it checking for `ActionInputError` as is found in the [source code](https://github.com/withastro/astro/blob/f64934086e84966bcfd02b699d64a80cb8392fa2/packages/astro/src/actions/runtime/virtual/shared.ts#L107).
> Update to the `astro-actions` page, adding documentation for `isActionError`.

- src/content/docs/zh-cn/guides/integrations-guide/svelte.mdx
> i18n(zh-cn): Update `svelte.mdx`

- src/content/docs/en/guides/integrations-guide/mdx.mdx
Changes `posts` with `matches` in `mdx.mdx` file
- Closes #9985
> Fix incorrect reference in `mdx.mdx` file

- src/content/docs/en/guides/authentication.mdx
As per Lucia's home page, they are no longer building an auth library and the existing library is being deprecated.
This change removes Lucia from the suggested list of auth providers and is a documentation change only.
> Update authentication.mdx - remove Lucia

- CONTRIBUTING.md
The sentence "This document is has some basic information to get you started..." contains a grammatical error due to the incorrect combination of "is" and "has" in this context. The word "is" is unnecessary and disrupts the sentence's structure.
The correct phrase should simply be "has", as it properly indicates possession of the information.
> Fix grammatical error in Contributor Manual ("is has" → "has")

- src/content/docs/fr/reference/error-reference.mdx
- src/content/docs/fr/reference/errors/env-unsupported-get-secret.mdx
Adds a deprecation notice in the French translation of `reference/errors/env-unsupported-get-secret.mdx` and removes the link in `error-reference.mdx` (see #10071)
> i18n(fr): update `errors/env-unsupported-get-secret.mdx`

- astro.sidebar.ts
- src/content/docs/en/reference/experimental-flags/responsive-images.mdx
Creates a new experimental flag page for responsive images based on what was previously added to configuration-reference
Notably:
- ONLY covers the content from `experimental.resoponsiveImages` and not the `image.experimental*` features. (Is this how we want to do this? Leave those in regular configuration reference?)
- Links should fail until config reference merges with the `image.experimental*` properties. Will all work out tomorrow when I merge after feature release.
> add responsive images as an experimental flag page

- src/content/docs/en/guides/content-collections.mdx
As discussed on Discord, this PR adds back an equivalent of the [“Defining custom slugs”](https://docs.astro.build/en/guides/content-collections/#defining-custom-slugs) section in the current version of the docs for the content collections page in the v5 docs.
The content is based on the current version but updated to match the new changes related to the Content Layer API.
A few notes:
- It works with JSON files too.
- The sentence about `slug` being a special, reserved property name not allowed in `schema` is removed, as it is not true anymore.
- Not sure about the capitalization of IDs in the title.
- Closes #
- Suggested label: 5.0.0-beta
> Add content collection custom IDs section

- plugins/remark-fallback-lang.ts
This PR fixes the `remarkFallbackLang` remark plugin used to marks links to fallback language pages.
Repro:
1. Visit https://docs.astro.build/de/guides/cms/#kann-ich-astro-ohne-cms-nutzen
1. The `Inhalte zu erstellen` link should be marked and displayed as `Inhalte zu erstellen (EN)` as it's linking to a fallback language page in English.
The `Integration` link in the previous section is correctly not marked as it's linking to a page in German.
This plugin broke with Astro `4.0.0-beta.0` due to to all the updates to the unified, remark and rehype dependencies in https://github.com/withastro/astro/pull/9138. It looks like the issue is located either in `hast-util-raw` or the `parse5` tokenizer (used internally) and it requires a raw node to either include an element or a whitespace (e.g. …
> Fix fallback language remark plugin

- src/content/docs/en/tutorial/5-astro-api/1.mdx
- src/content/docs/en/tutorial/5-astro-api/2.mdx
- src/content/docs/en/tutorial/5-astro-api/3.mdx
- src/content/docs/en/tutorial/6-islands/4.mdx
I know we're not supposed to send PRs right now, but since I noticed some errors while I did the tutorial again (see https://github.com/withastro/blog-tutorial-demo/pull/33), I thought I'd make the necessary updates!
Updates the tutorial to:
* Add missing type annotations in the Unit 5 (final code snippet, code check-ins...)
* Fix a broken link in Unit 6
I haven't addressed `ThemeIcon.astro` because I don't know if it's necessary or not:
* when I follow the tutorial I don't see any error
* when I open `blog-tutorial-demo` I see Typescript errors...
- Suggested label: 5.0.0-beta, code snippet update, typo/link/grammar - quick fix!
Sorry for the wrong automatic labels... I forgot to use the `5.0.0` branch as base... 😅
> fix(v5): broken link and missing type annotations in tutorial

- src/content/docs/en/guides/actions.mdx
This adds the missing backticks to close the `src/middleware.ts` code block example in the [gate actions middleware documentation](https://5-0-0-beta.docs.astro.build/en/guides/actions/#gate-actions-from-middleware).
- Suggested label: `5.0.0-beta`
> fix: close gate actions middleware code block

- src/content/docs/en/guides/backend/google-firebase.mdx
- src/content/docs/en/guides/backend/supabase.mdx
- src/content/docs/en/guides/cms/kontent-ai.mdx
- src/content/docs/en/guides/cms/storyblok.mdx
- src/content/docs/en/guides/cms/strapi.mdx
- src/content/docs/en/guides/deploy/index.mdx
- src/content/docs/en/guides/integrations-guide/lit.mdx
- src/content/docs/en/guides/integrations-guide/preact.mdx
- src/content/docs/en/guides/integrations-guide/react.mdx
- src/content/docs/en/guides/integrations-guide/solid-js.mdx
- src/content/docs/en/guides/integrations-guide/svelte.mdx
- src/content/docs/en/guides/integrations-guide/vue.mdx
- src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/en/guides/migrate-to-astro/index.mdx
- src/content/docs/en/recipes/bun.mdx
- src/content/docs/en/reference/adapter-reference.mdx
- src/content/docs/en/reference/cli-reference.mdx
- src/content/docs/en/reference/image-service-reference.mdx
This updates a handful of wording (e.g. SSR mode) in English pages. No links are changed as they had already been edited to make link checker pass. This just chooses some places to use our more common wording.
Notably:
- does not update the config ref/error messages that are generated at source.
- does not update the API reference page since that's open in another PR and any adjustments can be made there before merging to avoid conflicts
> update some SSR wording

- src/components/starlight/Sidebar.astro
- src/components/tabs/TabPanel.astro
This is a follow-up to #9890 and cleans up some repeated markup to improve performance. The initial prototype included several repeated scripts and extra unnecessary DOM that these changes clear up.
WebPageTest before/after comparison: https://www.webpagetest.org/video/compare.php?tests=241202_BiDcYR_BZH,241202_BiDcVQ_BZN
https://github.com/user-attachments/assets/6796ea8c-48c9-4f09-a9fc-6d0c24248634
> Clean up v5 sidebar implementation

- src/content/docs/en/guides/upgrade-to/v5.mdx
This removes all mention of "beta 5" from the upgrade guide so that it conforms to a regular, major (stable) upgrade guide.
Also some tiny polishing.
TODO (either in this PR, or before the main 5.0.0 PR is merged)
> [upgrade guide] remove mentions of beta

- src/content/docs/en/guides/content-collections.mdx
Updates a broken link in `guides/content-collections.mdx`: The `content-layer` branch no longer exists in `withastro/blog-tutorial-demo` so the link should lead to https://github.com/withastro/blog-tutorial-demo/tree/content-collections/src/pages instead.
> fix: update a broken link in `guides/content-collections.mdx`

- src/content/docs/en/guides/integrations-guide/lit.mdx
remove unused import in `lit.mdx`
- Closes #
> fix: remove unused import in `lit.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx
- typo in `from-nextjs.mdx`
- Add link only to `import.meta.glob()` for consistency with other documentation.
- Change the link to `/en/guides/imports/#importmetaglob` for consistency with other documentation.
- Closes #
> fix: update link in `from-nextjs.mdx`

- src/content/docs/en/guides/upgrade-to/v5.mdx
As discussed on Discord, this PR adds a new section to the breaking changes of the v5 upgrade guide to document the removal of the `--typescript` flag from `create-astro`.
- Closes #
- Suggested label: 5.0
> Add `--typescript` flag removal to v5 upgrade guide

- src/content/docs/en/reference/cli-reference.mdx
Adds two changes to `cli-reference.mdx`:
* the comment above each command was still using "`start` script" instead of `dev` so I updated the comments
* Astro Env was still marked as experimental in the `astro sync` section so I removed that mention
> fix: remove experimental and update comments in `cli-reference.mdx`

- src/content/docs/en/guides/environment-variables.mdx
Fixes a link in `guides/environment-variables.mdx` by replacing a double slash with a single slash: `//en` > `/en`
> fix: update a link in `guides/environment-variables.mdx`

- src/content/docs/en/guides/images.mdx
Since v5, we cannot use `refine()` with the `image()` helper, so I updated an outdated example in `guides/images.mdx`.
I also slightly reworded the sentence above the code snippet because I believe this is no longer validated with Zod. But happy to revert or to reword if I'm wrong.
- Closes #10151
> fix: remove `image().refine` from a code snippet in `guides/images.mdx`

- .github/workflows/nightly.yml
- scripts/docgen.mjs
This PR removes the v5-beta workflows from our docgen CI scripts. These were running nightly to update our beta docs during the prerelease period, but are no longer needed (and fail because our v5 branches no longer exist).
I also updated a line logged in the config reference generation script that hadn’t been updated to match the new file location which we changed as part of v5.
> Cleanup docgen workflows post-v5 release

- src/content/docs/en/guides/typescript.mdx
Quick fix for misaligned `// ^?` typescript comments in the code example I updated in #10148.
|--------|--------|
| <img width="549" alt="Screenshot 2024-12-04 at 7 47 07 PM" src="https://github.com/user-attachments/assets/743b2b43-b1e5-4070-b493-73cfbf66c895"> | <img width="552" alt="Screenshot 2024-12-04 at 7 47 47 PM" src="https://github.com/user-attachments/assets/4ac5dc25-3a90-4f3a-9c00-e3e9d5a64984"> | 
- Follow-up to #10148
- Suggested label: **code snippet update**
> Hotfix for #10148: fix indentation in `^?` comments

- src/content/docs/en/guides/upgrade-to/v5.mdx
Updates the link to public-facing types to point to `main` branch (instead of `next`)
> Fix link to public types in upgrade guide

- src/content/docs/en/guides/content-collections.mdx
- src/content/docs/en/guides/upgrade-to/v5.mdx
- src/content/docs/en/tutorial/6-islands/4.mdx
To avoid confusion whether the editor automatically removes the character or ESlint displays a warning, I removed the useless escape character in the loader `pattern`.
- Related:
* #10152
* https://discord.com/channels/830184174198718474/853350631389265940/1314275896038785227
> fix: remove useless escape characters in `pattern`

- src/content/docs/en/guides/content-collections.mdx
Same as #10209 but with a different pattern:
I haven't noticed this pattern in the previous PR because I was looking for an exact matching... but I checked `"**\/*.md"` and `"**/*.md"` are both valid.
So, to avoid confusion whether the editor automatically removes the character or ESlint displays a warning, I removed the useless escape character in some loader patterns in `content-collections.mdx`.
> fix: remove useless escape character in `content-collections.mdx`

- src/content/docs/en/develop-and-build.mdx
I found that the link to the [TypeScript guide](https://docs.astro.build/en/guides/typescript/) in the [Configure your dev environment](https://docs.astro.build/en/develop-and-build/#configure-your-dev-environment) section of the Develop and Build page was wrong, so I fixed it.
Discord username: `heldinz`
> Fix link to TypeScript guide

- src/content/docs/en/tutorial/1-setup/2.mdx
Reorder the number of instruction list in `1-setup/2.mdx`
> fix: Reorder the number of instruction list in `1-setup/2.mdx`

- src/content/docs/en/guides/internationalization.mdx
Fixes a few nitpicks in `guides/internationalization.mdx`:
* in the `domains` section, the highlighting for inserted lines should be restricted to the `domains` property
* in the code snippet of `Custom locale paths`, the indent for `codes` was wrong
* in the `Create localized folders` section, missing backticks for a route (all other routes on the page are wrapped with backticks)
> fix: indent & line highlighting in `guides/internationalization.mdx`

- src/content/docs/en/guides/deploy/aws.mdx
The link `/en/guides/deploy/aws/#s3-static-website-hosting` can be shortened to just `#s3-static-website-hosting` because the heading is on the same page.
- Suggested label: link?
> feat(link): update link in `guides/deploy/aws` because it now links to same page [i18nIgnore]

- src/content/docs/en/install-and-setup.mdx
- src/content/docs/ko/install-and-setup.mdx
Modify the commands in the **Add integrations** section to correctly create a new project with React and Tailwind. 
Adjusted the syntax to ensure proper handling of multiple integrations with the `--add` flag.
FYI: https://docs.astro.build/en/install-and-setup/#add-integrations
- Closes #10278 
Discord username: `Taisei`
> [i18nIgnore] update command for `creating a new project with react and tailwind`

- src/content/docs/en/guides/integrations-guide/mdx.mdx
This PR removes an unnecessary backslash `\` character from a code example for the new content collection system.
This should be the last code example that used this character.
Discord user: anaxite
> fix: remove unnecessary `\` in code example

- src/content/docs/en/guides/imports.mdx
When used with `{ eager: true }`, [`import.meta.glob` no longer returns a promise](https://github.com/vitejs/vite/blob/ef7a6a35e6827b92445e5a0c2c0022616efc80dd/packages/vite/types/importGlob.d.ts#L66-L74) and thus no longer needs `await`.
- Closes #
> fix: remove unnecessary `await` before `import.meta.glob`

- src/content/docs/en/guides/imports.mdx
Fixes 2 more instances of `import.meta.glob`
> Additional import.meta.glob fixes

- src/content/docs/fr/guides/routing.mdx
Updates the French translation of `guides/routing.mdx` with:
* changes from #9240
* a small reword in `Naviguer entre les pages`
* some changes that seem to have been forgotten dating back to I don't know which PR... in `Routes Statiques`
> [!NOTE]
> Once again, the links to `api-reference.mdx` have not been updated. We'll do that at the same time than updating `api-reference.mdx`
> i18n(fr): update `guides/routing.mdx`

- src/content/docs/en/guides/integrations-guide/mdx.mdx
- src/content/docs/en/guides/markdown-content.mdx
- src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/en/guides/routing.mdx
- src/content/docs/en/reference/api-reference.mdx
- src/content/docs/en/tutorial/5-astro-api/1.mdx
- src/content/docs/en/tutorial/5-astro-api/2.mdx
- src/content/docs/en/tutorial/5-astro-api/3.mdx
- src/content/docs/en/tutorial/6-islands/4.mdx
- src/content/docs/fr/guides/integrations-guide/mdx.mdx
- src/content/docs/fr/guides/markdown-content.mdx
- src/content/docs/fr/guides/routing.mdx
- src/content/docs/ko/guides/imports.mdx
- src/content/docs/ko/guides/integrations-guide/mdx.mdx
- src/content/docs/ko/guides/markdown-content.mdx
- src/content/docs/ko/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/ko/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/ko/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/ko/guides/routing.mdx
- src/content/docs/ko/reference/api-reference.mdx
- src/content/docs/ko/tutorial/5-astro-api/1.mdx
- src/content/docs/ko/tutorial/5-astro-api/2.mdx
- src/content/docs/ko/tutorial/5-astro-api/3.mdx
- src/content/docs/ko/tutorial/6-islands/4.mdx
- src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
- src/content/docs/zh-cn/guides/markdown-content.mdx
Changes all occurrences in all languages of `await import.meta.glob('*', { eager: true });` to remove `await` as it is not needed.
> [i18nIgnore] remove `await` from `import.meta.glob()`

- src/content/docs/en/guides/deploy/google-cloud.mdx
Since Docker Hub is mentioned in the text above, I think it would make sense to include the Registry URL in the examples below...
- Closes #
> Add dockerhub URL to registry examples in Google Cloud Deploy Guide

- src/content/docs/fr/guides/imports.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-eleventy.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gitbook.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gridsome.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-hugo.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-jekyll.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-pelican.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-sveltekit.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-vuepress.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-wordpress.mdx
- src/content/docs/fr/guides/migrate-to-astro/index.mdx
Adds changes from #9240 to the French translations of:
* the `migrate-to` guides (including fixes from Junseong and #10332 )
* `guides/imports.mdx` (including #10140, #10310 and #10315)
> [!NOTE]
> I haven't updated some links in the `migrate-to` guides to avoid broken links:
> * those targeting `api-reference.mdx` 
> * those targeting `install-and-setup.mdx`
>
> I think it's better to do it while updating these files, but I can update them here if needed...
> i18n(fr): update `guides/imports.mdx` & `migrate-to` guides

- src/content/docs/en/tutorial/5-astro-api/1.mdx
- src/content/docs/ko/tutorial/5-astro-api/1.mdx
We have a remaining `await` in front of `Object.values` which is useless and makes the code snippets inconsistent across the tutorial, so I removed it.
- Related: #10332
> [I18nIgnore] fix(tutorial): remove a useless `await` in unit 5

- src/content/docs/en/guides/integrations-guide/mdx.mdx
* The code snippet in the `Using MDX with content collections` section had an unclosed function, so I fixed it
* There was a typo in the section heading `wth` > `with`
I don't know if other languages ​​than Korean are already up to date on this file, so I didn't included the changes on the Korean version.
- Suggested label: typo, code snippet update
> fix: malformed code snippet in `integrations-guide/mdx.mdx`

- src/content/docs/fr/guides/content-collections.mdx
Fix link l19 in `content-collections.mdx` about `#héritage-api-des-collections-de-contenu-v20`.
Because [CI link error  didn't show up](https://github.com/withastro/docs/actions/runs/12286425926) in the main branch, but we don't know why he doesn't tell us an error before merging [PR #10145](https://github.com/withastro/docs/pull/10145).
> i18n(fr): Fix link l19 in `content-collections.mdx`

- src/content/docs/en/tutorial/6-islands/4.mdx
> fix: rename wrong collection name 'posts' to 'blog'

- src/content/docs/en/reference/routing-reference.mdx
This PR fixes a code block which was missing the code fence, resulting in broken code highlights on the docs (see https://docs.astro.build/en/reference/routing-reference/#paginate)
> Add missing code fence

- src/components/starlight/Sidebar.astro
This PR fixes the occasion on which a tab panel ID conflicts with a page heading ID, so you cannot click to navigate to that specific heading from links.
For example, it currently occurs on the [`integrations` heading of Configuration Reference](https://docs.astro.build/en/reference/configuration-reference/#integrations), since we have a tab of the same name "Integrations" that gets the id `integrations`.
> Add prefix to tab panels IDs to avoid clashes

- src/content/docs/ko/reference/routing-reference.mdx
- update `routing-reference.mdx`
- #10352
- Closes #
> i18n(ko-KR): update `routing-reference.mdx`

- src/content/docs/fr/guides/view-transitions.mdx
Updates the French translation of `guides/view-transitions.mdx`:
* add changes from #9240 and #10277,
* make some `Transition de Vue` lowercase to match the English version,
* fix a wrongly translated inline code.
> i18n(fr): update `guides/view-transitions.mdx`

- src/content/docs/fr/guides/typescript.mdx
Updates the French translation of `guides/typescript.mdx`:
* add changes from #9240, #10148 and #10197
* fix some inline codes (no space before colon)
> i18n(fr): update `guides/typescript.mdx`

- src/content/docs/en/guides/content-collections.mdx
Fix english typo in `src/content/docs/en/guides/content-collections.mdx`
> [i18nIgnore] Fix typo in `content-collections.mdx`

- src/content/docs/fr/guides/styling.mdx
- src/content/docs/fr/guides/upgrade-to/v3.mdx
The file was marked as outdated due to #9240 but I added more changes:
* update the title to match the one updated in #9240
* fix a malformed aside (`:::noteStyles`)
* fix some typo and untranslated strings
* fix some mismatches between the English version and the translation (e.g. code snippet file path)
* make the translation of `scoped styles` consistent (we previously had `limités`, `délimités`, `scopés`, `étendues`, `codés`, etc. on the same page! I think the most accurate translation is `portée limitée` and this matches the one [used on Starlight docs](https://starlight.astro.build/fr/reference/overrides/#markdowncontent))
* improve the translation of `styling` to make it consistent with [Starlight docs](https://starlight.astro.build/fr/guides/css-and-tailwind/): `mise en forme` is …
> i18n(fr): update `guides/styling.mdx`

- src/content/docs/pt-br/reference/errors/no-adapter-installed-server-islands.mdx
translate content i18n pt-br/reference/errors/no-adapter-installed-server-islands.mdx
> i18n(pt-BR): create `reference/errors/no-adapter-installed-server-islands.mdx`

- src/content/docs/fr/guides/testing.mdx
The French translation of `guides/testing.mdx` was marked as outdated due to #9240 but the changes are not applicable (`island` > `islands`) so instead I updated the code snippets to make them consistent:
* a page to test was translated but the expectation was not translated
* a page to test and an expectation was both translated but in a different way...
> i18n(fr): update `guides/testing.mdx`

- src/content/docs/pt-br/reference/errors/missing-middleware-for-internationalization.mdx
translate content i18n pt-br/reference/errors/missing-middleware-for-internationalization.mdx
> i18n(pt-BR): create `reference/errors/missing-middleware-for-internationalization.mdx`

- src/content/docs/pt-br/reference/errors/content-loader-invalid-data-error.mdx
translate content i18n pt-br/reference/errors/content-loader-invalid-data-error.mdx
> i18n(pt-BR): create `reference/errors/content-loader-invalid-data-error.mdx`

- src/content/docs/pt-br/reference/errors/adapter-support-output-mismatch.mdx
i18n pt-br translate content /reference/errors/adapter-support-output-mismatch.mdx
> i18n(pt-BR): create `reference/errors/adapter-support-output-mismatch.mdx`

- src/content/docs/fr/reference/errors/get-static-paths-removed-rsshelper.mdx
The French translation of `errors/get-static-paths-removed-rsshelper.mdx` was marked as outdated because of #9240 but the links are already up to date... Instead I fixed the `title` which was wrongly translated.
> i18n(fr): update `errors/get-static-paths-removed-rsshelper.mdx`

- src/content/docs/en/guides/syntax-highlighting.mdx
The `markdown.syntaxHighlighting` option name has been corrected to the proper [`markdown.syntaxHighlight`](https://docs.astro.build/en/reference/configuration-reference/#markdown.syntaxHighlight).
- Closes #
> fix: correct markdown option name

- src/content/docs/fr/guides/images.mdx
Updates the French translation of `guides/images.mdx` with changes from #9240, #10149 and #10202
> i18n(fr): update `guides/images.mdx`

- src/content/docs/fr/reference/integrations-reference.mdx
Updates the `astro:build:setup` hook signature in the French translation of `integrations-reference.mdx` (see #10410)
> i18n(fr): update `integrations-reference.mdx`

- src/content/docs/en/guides/on-demand-rendering.mdx
- src/content/docs/en/guides/server-islands.mdx
This PR adds explicit mention that server islands require an adapter installed (in three places).
> Add need for adapter to server islands guide

- astro.sidebar.ts
- src/content/docs/en/guides/images.mdx
- src/content/docs/en/reference/error-reference.mdx
- src/content/docs/en/reference/errors/session-storage-init-error.mdx
- src/content/docs/en/reference/errors/session-storage-save-error.mdx
- src/content/docs/en/reference/experimental-flags/sessions.mdx
- src/content/docs/en/reference/modules/astro-actions.mdx
Minor release docs for 5.1.0
Includes:
#10377 - remote image caching
#10353 - `getActionPath()`
#10378 - experimental Sessions API
#10462 - Sessions error messages
> 5.1.0 Minor Docs

- src/content/docs/de/guides/imports.mdx
- src/content/docs/en/guides/imports.mdx
> Simplify link imports in `guides/imports.mdx`

- src/content/docs/fr/guides/images.mdx
- src/content/docs/fr/guides/imports.mdx
Update `guides/images.mdx` and `guides/imports.mdx`
> [!NOTE]
>  For `guides/imports.mdx` from #10451 : nothing was updated, because the link is already correct.
> i18n(fr): Update `guides/images.mdx` and `guides/imports.mdx`

- src/content/docs/en/reference/experimental-flags/sessions.mdx
Netlify blob example had `adapter` incorrectly nested in the `experimental`  property instead of at the root of the configuration object.
Discord: sledsworth
> Fix typo in configuration example for Netlify Blob sessions

- src/content/docs/fr/reference/modules/astro-actions.mdx
Update `reference/modules/astro-actions` from #10447
> i18n(fr): Update `reference/modules/astro-actions` from #10447

- src/content/docs/en/guides/server-islands.mdx
This PR includes a section about Caching Server Islands, as discussed on Talking and Doc'ing.
- Closes #10125 
- Suggested label: add new content
> Update server-islands.mdx to add caching section

- src/content/docs/en/reference/experimental-flags/sessions.mdx
I think I found a missing `s` after a third person: `session object`
> I'm writing [i18nIgnore] into the title, alto it would work with just `typo` because I think new translators have an easier job figuring out what changes were made to outdated translations if the more specific key word is included...
> typo in `reference/experimental-flags/session.mdx` [i18nIgnore]

- src/content/docs/en/guides/content-collections.mdx
With the advent of custom loaders in Astro v5, the "non-standard" data anti-use-case is invalid (yay!). This should be removed from documentation to prevent confusion :)
Discord Username: rayhanadev
- Closes #
- Suggested label: [improve documentation](https://github.com/withastro/docs/labels/improve%20documentation)
> docs(content-collections): remove stale anti-use-case

- src/content/docs/ko/guides/server-islands.mdx
- update `server-islands.mdx`
- #10466
- Closes #
> i18n(ko-KR): update `server-islands.mdx`

- src/content/docs/en/guides/upgrade-to/v5.mdx
Adds more detail to Step 2 of content collections upgrade to include:
- an updated pattern that would cover people with MDX collection entries
- more explicit text defining `pattern` and `base`, with a warning to update the examples given if necessary
> [v5 upgrade] include MDX in collections instructions

- src/content/docs/en/guides/actions.mdx
When calling an action from a server endpoint, an `await` is required or `data` and `error` will be `undefined`.
> fix: add wait to code sample

- src/content/docs/ko/guides/upgrade-to/v5.mdx
- update `v5.mdx`
- #10543
- Closes #
> i18n(ko-KR): update `v5.mdx`

- src/content/docs/zh-cn/guides/data-fetching.mdx
Update `data-fetching.mdx`
NOTE: To update the status of the Docs translation, I commit some change.
> i18n(zh-cn): Update `data-fetching.mdx`

- src/content/docs/zh-cn/recipes/sharing-state.mdx
Update `sharing-state.mdx`
- #9240
> i18n(zh-cn): Update `sharing-state.mdx`

- src/content/docs/zh-cn/reference/errors/invalid-content-entry-frontmatter-error.mdx
Update `invalid-content-entry-frontmatter-error.mdx`
- #9240
> i18n(zh-cn): Update `invalid-content-entry-frontmatter-error.mdx`

- src/content/docs/zh-cn/reference/errors/invalid-content-entry-slug-error.mdx
Update `invalid-content-entry-slug-error.mdx`
- #9240
> i18n(zh-cn): Update `invalid-content-entry-slug-error.mdx`

- src/content/docs/zh-cn/tutorial/2-pages/5.mdx
Update `2-pages/5.mdx`
NOTE: The doc itself is up-to-date, so I commit some indent to update the status of Docs translation.
> i18n(zh-cn): Update `2-pages/5.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx
This updates and unifies the three full "Migrate to Astro" guides that currently claim that content must live within `src`. This makes the sentence consistent in all three guides that this is not a restriction when using content collections.
Closes #10189
> [migration guides] update options for content location

- src/content/docs/en/guides/content-collections.mdx
This is the "quick fix" to at least get some minimal helpful/correct info into content collections but does not entirely solve 10147 (not linking so it won't close)
- Adds that collections can be YAML
- notes that we use `micromatch` for matching in `pattern`
> [content-collections] quick fixes

- src/content/docs/en/guides/routing.mdx
Adds the caveat:
For on-demand renderered routes, only one rest paramater using the spread notation may be used in the file name (e.g. `src/pages/[locale]/[...slug].astro` or `src/pages/[...locale]/[slug].astro`, but not `src/pages/[...locale]/[...slug].astro`).
- Closes #10468
> [routing.mdx] can't have multiple rest params for on-demand rendering

- src/content/docs/en/guides/content-collections.mdx
- src/content/docs/en/guides/markdown-content.mdx
Addresses an issue where it was difficult to find information about accessing headings data from Markdown content collections entries.
The page was written before collections, and therefore emphasized exported Markdown properties even though this information is only appropriate when importing Markdown files. More relevant information is available on the Contents Collections guide page, and in reference, but someone may first look at the Markdown guide even when their Markdown files are part of a collection.
This does not duplicate content found elsewhere, but attempts to:
- empahsize in multiple places that you may be working with Markdown that came from either a file import or a content collection (there's a difference!)
- adds more contextual links throughout, notably adds a link to the …
> [markdown-content] clearer distinction between imported Markdown and collections data

- package.json
- pnpm-lock.yaml
This PR reverts the Algolia Docsearch dependencies to 3.5.1
#10493 updated these to 3.8.2, which @hippotastic and @OliverSpeir reported introduced issues in Safari on iOS.
I’m not 100% sure what in that update would cause this and can’t reproduce myself, so opening this PR to see if a revert would help.
> Pin Algolia Docsearch to 3.5.1

- src/content/nav/es.ts
- Upgrade `es.ts` to fix a typo on the ¡ sign
Related issues & labels (optional)
> i18(es): fix typo in `es.ts`

- src/content/docs/fr/guides/content-collections.mdx
- src/content/docs/fr/guides/markdown-content.mdx
Updates the French translations of `guides/content-collections.mdx` and `guides/markdown-content.mdx` with changes from #10594
> i18n(fr): update `content-collections` & `markdown-content` guides

- src/content/docs/en/tutorial/6-islands/4.mdx
- src/content/docs/en/tutorial/6-islands/index.mdx
Removed key from checklist component in island tutorial.
https://github.com/withastro/docs/pull/10649#issuecomment-2577493567
> Removed key from checklist component in island tutorial.

- src/content/docs/ko/guides/cms/contentful.mdx
- update `contentful.mdx`
- #10679
- Closes #
> i18n(ko-KR): update `contentful.mdx`

- src/content/docs/ko/reference/errors/session-storage-init-error.mdx
- src/content/docs/ko/reference/errors/session-storage-save-error.mdx
- update `reference/errors/`
- #10680
- Closes #
> i18n(ko-KR): update `reference/errors/`

- src/content/docs/en/basics/layouts.mdx
- update `layouts.mdx`
- removed the wording that doesn't match the current version of Astro and modified the example code blocks.
- #10532
- Closes #
> docs: update `layouts.mdx`

- src/content/docs/fr/reference/errors/session-storage-init-error.mdx
- src/content/docs/fr/reference/errors/session-storage-save-error.mdx
Update `reference/errors/session-storage-init-error.mdx` and `reference/errors/session-storage-save-error.mdx` from #10680
> i18n(fr): Update `reference/errors/*`

- src/content/docs/zh-cn/guides/view-transitions.mdx
Update `view-transitions.mdx`
- #9240 
- #10277
> i18n(zh-cn): Update `view-transitions.mdx`

- src/content/docs/zh-cn/reference/legacy-flags.mdx
Add `legacy-flags.mdx`
- #9240
> i18n(zh-cn): Add `legacy-flags.mdx`

- src/content/docs/en/guides/fonts.mdx
- This PR updates the sidebar label for the fonts guide from “Using custom fonts” to “Fonts”
- Reasoning: I struggled to quickly find the page even though I was fairly certain it was in the “Build your UI” group. I suspect this is because the keyword is “fonts” but this is somewhat buried behind “using custom” which are not very specific. Given the context of other guides being labelled similarly as “Styles”, “Components”, etc., “Fonts” feels in keeping and helps make it more scannable.
|--------|--------|
| <img width="294" alt="build your UI sidebar group with using custom fonts item" src="https://github.com/user-attachments/assets/f71e3f6f-0505-4fa8-aff4-d174bbc9bdd6" /> | <img width="296" alt="build your UI sidebar group with fonts item" …
> Use a simpler label for fonts guide in the sidebar

- src/components/SourcePR.astro
- src/content/i18n-schema.ts
- src/content/i18n/en.yml
- src/content/i18n/zh-CN.yml
> Make `implementation PR` can be translated

- src/content/docs/zh-cn/reference/experimental-flags/content-intellisense.mdx
Add `content-intellisense.mdx`
- #9240
> i18n(zh-cn): Add `content-intellisense.mdx`

- src/content/docs/zh-cn/reference/experimental-flags/svg.mdx
Add `experimental-flags/svg.mdx`
- #9240
> i18n(zh-cn): Add `experimental-flags/svg.mdx`

- src/content/docs/en/tutorial/6-islands/2.mdx
This PR removes the redundant nullish coalescing operator (??) from the code that retrieves the theme from localStorage. The nullish coalescing operator is unnecessary in this context because the existence of the theme in localStorage is already checked.
- Suggested label: enhancement
> Removed redundant nullish coalescing operator

- src/content/docs/en/tutorial/5-astro-api/3.mdx
- src/content/docs/en/tutorial/6-islands/2.mdx
I followed the tutorial again to check the consistency between the tutorial and the `blog-tutorial-demo` repository (see https://github.com/withastro/blog-tutorial-demo/pull/39 and https://github.com/withastro/blog-tutorial-demo/pull/40). Almost everything looks good here, I only updated two things:
* Adds a missing `any` in the code check-in of unit 5-3 to prevent a Typescript error (if someone tries to replace his code) and to match what we had before.
* Fixes the line highlighting in unit 6-2 (I forgot to check that in #10719)
> fix: update two code snippets in the tutorial

- src/content/docs/ko/tutorial/5-astro-api/3.mdx
- src/content/docs/ko/tutorial/6-islands/2.mdx
- update `tutorial/`
- #10727
- Closes #
> i18n(ko-KR): update `tutorial/`

- src/content/docs/en/reference/routing-reference.mdx
When I translate `routing-reference.mdx`, I notice something duplicated and inconsistent in their descriptions, comparing to [v4](https://v4.docs.astro.build/en/reference/api-reference/#pageurlprev).
so I make changes in `routing-reference.mdx`:
- Remove duplicated `prop`: `page.url.first` & `page.url.last`.
- Make descriptions consistent.
> Remove duplicated `prop` in `routing-reference.mdx`

- src/content/docs/zh-cn/reference/experimental-flags/sessions.mdx
Add `sessions.mdx`
NOTE: Once #10736 is merge, the `CI/CheckLinks` will pass.
- #10447
- #10471
- #10483 
> i18n(zh-cn): Add `sessions.mdx`

- src/content/docs/en/guides/cms/payload.mdx
I added the link to the new and official PayloadCMS Astro integration example, that can be found on the PayloadCMS repository.
Yes
`albertogiunta`
> Add reference to the official example on the payload repo

- src/content/docs/fr/reference/error-reference.mdx
- src/content/docs/fr/reference/errors/content-loader-returns-invalid-id.mdx
Adds changes from #10770:
* Translates `content-loader-returns-invalid-id.mdx` in French
* Updates `error-reference.mdx` to add the new error
> i18n(fr): add `content-loader-returns-invalid-id.mdx`

- src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
This PR changes the bulleted list of community resources to `<LinkCard>` components in a `<CardGrid>` for the Migrate from Gatsby page.
If we like this, then we can accept PRs to update the other Migrate to Astro pages!
Note:
- Titles are the blog post / article titles
- Descriptions are the subtitle / description of the article if available. If not, I chose the earliest sentence(s) that seemed like a standalone subtitle/tagline/intro. So, we have some flexibility here (e.g. being more strategic about length).
Before:
After:
> [from-gatsby] use LinkCard for community resources

- src/content/docs/en/basics/astro-pages.mdx
A dot is missing in the end of a sentence.
- Closes #
> [i18nIgnore] fix: Add missing dot in `basics/astro-pages.mdx`

- src/content/docs/fr/guides/cms/drupal.mdx
Adds changes from #10756 to the French translation of `guides/cms/drupal.mdx` (replace some `created` vars with `date`).
> i18n(fr): update `guides/cms/drupal.mdx`

- src/content/docs/fr/guides/deploy/cloudflare.mdx
Adds changes from #10762 to the French translation of `guides/deploy/cloudflare.mdx`
> [!NOTE]
> I left the new label in English because I don't have a Cloudflare account so I don't know what is the translation. I tried to look for a screenshot of the dashboard translated in French... but no luck. And I guess the original version is not worse than a wrong translation... I mean `Calculer (Workers)` seems weird... but I don't use Cloudflare. So feel free to check if you have access to Cloudflare!
> i18n(fr): update `guides/deploy/cloudflare.mdx`

- src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
* Updates the French translation of `migrate-to-astro/from-gatsby.mdx` to uses `CardsList` (see #10781)
* Adds a new community resource (see #10793)
> i18n(fr): update `migrate-to-astro/from-gatsby.mdx`

- src/content/docs/en/reference/modules/astro-i18n.mdx
* Fixes the output displayed as comment for `getRelativeLocaleUrl("fr")` and `getAbsoluteLocaleUrl("fr")` (missing slash)
* Fixes the type for `getAbsoluteLocaleUrl()` (path is optional)
- Closes #10743
- Related https://github.com/withastro/astro/issues/13032
- Suggested label: `code snippet update` (and not sure which label matches the type update... `typo/link/grammar - quick fix!` I guess) ... Feel free to correct the labels 😄
> fix: outputs and type in `astro-i18n`

- src/content/docs/en/reference/experimental-flags/serialized-configuration.mdx
This PR updates the new experimental serialized configuration from `serializeManifest` to `serializeConfig`. The [docs](https://docs.astro.build/en/reference/experimental-flags/serialized-configuration/) says it's `serializeManifest`, but the [blog](https://astro.build/blog/astro-520/#experimental-astroconfig) and actual [source](https://github.com/withastro/astro/blob/3b10b97a4fecd1dfd959b160a07b5b8427fe40a7/packages/astro/src/manifest/virtual-module.ts#L38) is using `serializeConfig`.
> docs: fix new experimental serialized config option name

- src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
- src/content/docs/fr/guides/integrations-guide/netlify.mdx
- src/content/docs/fr/guides/integrations-guide/node.mdx
- src/content/docs/fr/guides/integrations-guide/vercel.mdx
Updates the `githubIntegrationURL` for Node, Netlify, Vercel and Cloudflare in the French translations (see #10898, #10900, #10901 and #10910).
> i18n(fr): update adapter links in `integrations-guide/*`

- src/content/docs/fr/reference/errors/cant-use-astro-config-module-error.mdx
Adds changes from #10926 to the French translation of `errors/cant-use-astro-config-module-error.mdx`.
> i18n(fr): update `errors/cant-use-astro-config-module-error.mdx`

- src/content/docs/fr/reference/integrations-reference.mdx
Fixes some anchors (Node links) in the French translation of `integrations-reference.mdx` (see #10924).
> i18n(fr): update links in `integrations-reference.mdx`

- src/content/docs/zh-cn/reference/errors/cant-use-astro-config-module-error.mdx
Update `cant-use-astro-config-module-error.mdx`
- #10926
> i18n(zh-cn): Update `cant-use-astro-config-module-error.mdx`

- src/components/DeployGuidesNav.astro
This matches the name in the left nav of deployment providers. Also, Firebase has multiple hosting products now - [Hosting](https://firebase.google.com/docs/hosting) and [App Hosting](https://firebase.google.com/docs/app-hosting), so this paves the way for a potential future App Hosting guide (I work on Firebase).
Preview link: https://deploy-preview-10949--astro-docs-2.netlify.app/en/guides/deploy/
- Suggested label: deployment
> Change "Firebase Hosting" to "Google Firebase"

- .github/workflows/nightly.yml
This PR updates the nightly auto-generated ci PR title for configuration reference docs to include the word "configuration."
We used to only have one action to pull in "reference" docs, but since we added the "error reference" docs separately, now we have "reference" and "error reference". 
I'm requesting that we instead use "configuration reference" and "error reference" so that I have an easier time telling them apart. 😅
> [nightly.yml] update PR title for ci config reference docs

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
- src/content/docs/en/recipes/modified-time.mdx
- src/content/docs/en/recipes/reading-time.mdx
- src/content/docs/en/recipes/tailwind-rendered-markdown.mdx
I notice that entries no longer have a `render()` method, so I replace `entry.render()` with `render(entry)` and update the import sentences as well in following `recipes/` & `integrations-guide`:
- `reading-time.mdx`
- `modified-time.mdx` (include `params` changed)
- `markdoc.mdx`
- `tailwind-rendered-markdown.mdx`
- #10521 
> Replace `entry.render()` with `render(entry)` in `recipes/` & `integrations-guide`

- src/content/docs/fr/guides/integrations-guide/markdoc.mdx
Fixes a heading in the French translation of `integrations-guide/markdoc.mdx`. It seems we have an inconsistency in wording and level compared to the English version.
The heading was added in #7744 ... we had a title but level 3 instead of level 2 and we missed the `advanced` part.
> i18n(fr): fix a heading in `integrations-guide/markdoc.mdx`

- src/content/docs/en/editor-setup.mdx
The link to the Astro extension in the Zed editor has changed, so I've updated it.
> fix: update zed extension link

- src/content/docs/pt-br/develop-and-build.mdx
add `develop-and-build.mdx` in Portuguese language
> i18n(pt-br): Add develop-and-build.mdx

- src/content/docs/ko/guides/cms/flotiq.mdx
- update `flotiq.mdx`
- #10994
- Closes #
> i18n(ko-KR): update `flotiq.mdx`

- src/content/docs/zh-cn/guides/cms/flotiq.mdx
> i18n(zh-cn): Update `flotiq.mdx`

- src/content/docs/en/guides/environment-variables.mdx
Updates the [`.env files` section](https://docs.astro.build/en/guides/environment-variables/#env-files) in `guides/environment-variables` to use the `PackageManagerTabs` component.
`npm` requires an extra `--` before any flag so the previous format was confusing for `npm` users.
- Closes #10935
> Use `PackageManagerTabs` for CLI commands in `guides/environment-variables`

- src/content/docs/en/editor-setup.mdx
- update the install and run CLI commands to respect the [Prettier documentation](https://prettier.io/docs/install).
- according to the [Prettier documentation](https://prettier.io/docs/configuration), the `JSON` format is the first to be documented. So I don't think it's necessary to use a different format.
if you have a different opinion on this, please let me know!
> fix: update prettier setup in `editor-setup.mdx`

- src/content/docs/en/guides/dev-toolbar.mdx
- The terms `development toolbar`, `developer toolbar`, and `dev toolbar`, which all mean the same thing, have been unified into `dev toolbar`, which is the most commonly used term in this document.
- Added missing spaces. Changed `enabled:true` to `enabled: true`
> fix: update `dev-toolbar.mdx`

- src/content/docs/en/guides/images.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
- src/content/docs/en/reference/cli-reference.mdx
- src/content/docs/en/reference/experimental-flags/responsive-images.mdx
- src/content/docs/en/reference/programmatic-reference.mdx
5.4.0 Minor docs including:
- #11019 
- #11021 
- #11051 
- #11060
- #11065
> 5.4.0 minor release docs

- src/content/docs/ko/reference/cli-reference.mdx
- update `cli-reference.mdx`
- #11067
- Closes #
> i18n(ko-KR): update `cli-reference.mdx`

- src/content/docs/en/reference/modules/astro-content.mdx
The `render()` function was previously annotated as `() => Promise<RenderedEntry>`, which is incorrect—it should take an `entry` parameter.  
This PR updates the type annotation to reflect the correct function signature:  
`(entry: CollectionEntry) => Promise<RenderedEntry>`.  
- Closes #11123
> fix: type annotation for `render()` in `astro:content`

- src/content/docs/fr/guides/syntax-highlighting.mdx
Adds changes from #11134 to the French translation of `guides/syntax-highlighting.mdx`.
> i18n(fr): update `guides/syntax-highlighting.mdx`

- src/content/docs/en/guides/content-collections.mdx
- src/content/docs/en/reference/modules/astro-content.mdx
Updates both `guides/content-collections` and `reference/modules/astro-content`:
* add explanations regarding the `reference()` output (#10774)
* add missing imports in code snippets
* update the `CollectionKey` example with I believe a more useful example (the previous example was basically the same thing as the built-in `getCollection` function... and using the same name so it could be a recursive function)
- Closes #10774
- Suggested label: improve or update documentation
> fix(content-collections): improve `reference()` docs and minor fixes

- src/content/docs/zh-cn/reference/experimental-flags/responsive-images.mdx
- #11067
- Experimental responsive images for Markdown
> i18n(zh-cn): update `responsive-images.mdx`

- src/content/docs/en/tutorial/4-layouts/2.mdx
- src/content/docs/en/tutorial/4-layouts/3.mdx
Since the change introduced by https://github.com/withastro/astro/pull/12231 in Astro 5, `<meta charset="utf-8" />` is no longer automatically added for Markdown files that use the `layout` frontmatter property. So users was facing a character encoding issue in unit 4 while checking the rendering of `MarkdownPostLayout` before nesting it in `BaseLayout`.
|Before|After|
|---|---|
|![tutorial-before](https://github.com/user-attachments/assets/b056c7de-7b7d-4d4c-b196-0469860fc09d)|![tutorial-after](https://github.com/user-attachments/assets/eee67e8f-443b-476e-9081-8665de4959bc)|
This PR:
* adds `<meta charset="utf-8" />` in [unit 4-2](https://docs.astro.build/en/tutorial/4-layouts/2/)
* adds a new step in [unit 4-3](https://docs.astro.build/en/tutorial/4-layouts/3/) to remove the `<meta …
> fix(tutorial): prevent character encoding issue in unit 4

- src/content/docs/fr/reference/error-reference.mdx
- src/content/docs/fr/reference/errors/actions-cant-be-loaded.mdx
Creates the French translation for `actions-cant-be-loaded.mdx` and updates the errors reference list. (see #11160)
> i18n(fr): add `reference/errors/actions-cant-be-loaded.mdx`

- src/content/docs/en/recipes/build-forms.mdx
This PR updates the Build Forms recipe to correct the suggestion about changing output to "server". The previous wording was misleading, and this update ensures clarity on rendering forms correctly.
- Closes #[10876](https://github.com/withastro/docs/issues/10876)
- Suggested label: good-first-issue
> fix(docs-10876): Fix incorrect suggestion about output: "server" in forms recipe

- src/content/docs/zh-cn/getting-started.mdx
- src/content/docs/zh-cn/guides/cms/buttercms.mdx
- src/content/docs/zh-cn/guides/cms/datocms.mdx
- src/content/docs/zh-cn/guides/cms/payload.mdx
Most files translate "headless CMS" as "无头 CMS" instead of keeping the original term. This PR unifies the translation to follow this practice.
> i18n(zh-CN): unify translation of "headless CMS"

- src/content/docs/en/reference/image-service-reference.mdx
This is a follow-up PR of the code PR https://github.com/withastro/astro/pull/13355
I added the new remote pattern utilities at the end of the page. I used the description that we have in the code as a starting point, and of course we can change them.
Questions:
- Do we want to provide an example?
- I used a code block to show the signature of the functions, instead of simple code words like we do for the hooks function. I felt that having more colour would help. Happy to change it and make this consistent.
As a tangent, Astro exposes **more functions** from the specifier `astro/assets/utils` that we don't document. However, I believe that **not all functions** are meant to be exposed to userland. I want to check with the team first, and then we can do follow-up PRs to add the missing …
> feat(assets): document remote utilities

- src/content/docs/en/guides/data-fetching.mdx
A typo was introduced by #11196 in a code snippet of `guides/data-fetching`. My bad, when reviewing, I didn't notice that it was an arrow function, so the semicolon produces invalid code. To avoid confusion, I reformatted the function to be on one line.
> fix(data-fetching): typo in a code snippet

- src/content/docs/fr/guides/deploy/deno.mdx
Adds changes from #11197 to the French translation of `guides/deploy/deno.mdx`.
> i18n(fr): update `guides/deploy/deno.mdx`

- scripts/docgen.mjs
This PR fixes a subtle issue with the docgen script used to generate our configuration reference.
The script uses `jsdoc-api` to parse JSDoc comments. This converts certain types to use JSDoc’s old-school Closure-style type notation. For example, `string[]` becomes `Array.<string>`, which looks a little odd these days with most people expecting TypeScript’s type syntax.
This PR adds a hotfix to remove the unexpected `.` in generic types like this fixing several instances of `Array.<...>` and `Record.<...>` in our config reference.
(I did not include the changes to the page itself in this PR as there are several things in flight there that will need handling anyway in #11212.)
H/T @ArmandPhilippot for spotting this issue
> Fixes type syntax generated by our config reference script

- src/content/docs/en/reference/image-service-reference.mdx
This fixes a few imports' formatting in the sample code blocks in the page for consistency's sake.
- Closes #
> Fix imports formatting in `image-service-reference.mdx`

- src/content/docs/en/reference/experimental-flags/heading-id-compat.mdx
Unless I'm missing something, there's no reason for [`experimental-flags/heading-id-compat`](https://docs.astro.build/en/reference/experimental-flags/heading-id-compat/) not to be translated. Currently this file does not appear in the [Lunaria dashboard](https://i18n.docs.astro.build/) (e.g. under `Français (fr)`). I think it's because the `i18nReady` property is missing in the frontmatter so I added it.
- Suggested label: i18n?
> fix: add missing frontmatter prop in `heading-id-compat.mdx` [i18nIgnore]

- src/content/docs/en/guides/cms/storyblok.mdx
I fixed an incorrect import statement in the Storyblok guide. The current code incorrectly imports Storyblok as a default export:
```js
import storyblok from "@storyblok/astro";
```
This causes an error as '@storyblok/astro' does not provide a default export. I've updated it to use the correct named import:
```js
import { storyblok } from "@storyblok/astro";
```
This change ensures the code example works correctly for users following the guide.
- Suggested label: `bug fix` `documentation`
> fix(guide/storyblok): adjust storyblok/astro import

- src/content/docs/fr/reference/experimental-flags/preserve-scripts-order.mdx
Creates the French translation of `experimental-flags/preserve-scripts-order` (see #11215).
> i18n(fr): add `experimental-flags/preserve-scripts-order.mdx`

- src/content/docs/en/reference/directives-reference.mdx
This is a tiny PR that fixes a heading level in the directives reference. The `timeout` heading is describing a parameter of the preceding `client:idle` heading but is at the same level currently. This PR nests that one level lower.
> Fix heading level in directives reference

- src/content/docs/pt-br/reference/errors/content-loader-returns-invalid-id.mdx
create i18n pt-br file docs/reference/errors/content-loader-returns-invalid-id.mdx
> i18n(pt-BR): translate reference/errors/content-loader-returns-invalid-id.mdx

- src/content/docs/pt-br/reference/errors/cant-use-astro-config-module-error.mdx
create file i18n pt-br docs/reference/errors/cant-use-astro-config-module-error.mdx
> i18n(pt-BR): translate reference/errors/cant-use-astro-config-module-error.mdx

- .github/renovate.json5
This PR adds renovate to this repository. 
It uses the same configuration of `withastro/astro`, less all the specific configurations of the repository.
The main reason for adding renovate is to keep the github actions pinned using their digest.
> chore: add renovate to repository

- .github/renovate.json5
As [discussed on Discord](https://discord.com/channels/830184174198718474/1351934638658027520/1351955002415124561), this PR prevents Renovate from updating the package manager in the `package.json` file.
- Closes #
> Disable Renovate package manager updates

- .github/renovate.json5
As [discussed on Discord](https://discord.com/channels/830184174198718474/1351934638658027520/1351976338038456462), this PR prevents Renovate from updating the Node version in the `.nvmrc` file.
- Closes #
> Disable Renovate `.nvmrc` updates

- .github/renovate.json5
As discussed today in Talking & Doc'ing, considering we are at the moment only using Renovate for GitHub Actions updates, we want to mostly rely on new pull requests rather than the dashboard.
This PR [disables](https://docs.renovatebot.com/key-concepts/dashboard/#how-to-disable-the-dashboard) the Renovate Dashboard.
- Closes #
> Disable Renovate Dashboard

- src/content/docs/en/guides/actions.mdx
if check was missing a `!`
Before the example would return a 403 if the user HAD a user-session cookie, instead of when the user didn't have it
discord: dar.io_19940
> Fix code in actions.mdx example

- src/content/docs/en/guides/styling.mdx
Previous docs state that scoped styles don't increase specificity which is inaccurate. Scoped styles will increase class specificity by 1.
The imported style in the second example will have a specificity of 0-0-2. This will not override the scoped style of 0-1-1. The example is updated to use an ID selector which will override the scoped style with its specificity of 1-0-0.
> Update scoped styles documentation in guides

- src/content/docs/fr/guides/client-side-scripts.mdx
- src/content/docs/fr/guides/view-transitions.mdx
- src/content/docs/fr/reference/directives-reference.mdx
I noticed a heading in the French version that shouldn't be in the ToC ([`Import local scripts`/`Importer des scripts locaux`](https://docs.astro.build/fr/guides/client-side-scripts/#importer-des-scripts-locaux)) so while fixing that, I also:
* translated some missing parts (mainly in code snippets)
* fixed some typo
* reworded some parts/headings to make reading smoother and more accurate (`processing` !== `bundling` so we shouldn't use `regroupement` but `traitement` for the scripts heading)
> i18n(fr): update `guides/client-side-scripts.mdx`

- src/content/docs/zh-cn/reference/configuration-reference.mdx
fix typo in `configuration-reference.mdx`
> i18n(zh-cn): fix typo in `configuration-reference.mdx`

- src/components/RightSidebar/LearnAstroAd.astro
This PR adds a `data-algolia-exclude` attribute to the Coding in Public Learn Astro banner ad so it doesn’t get indexed when Algolia crawls the docs.
This attribute has been set up in our Algolia crawler configuration, so that next time we run the crawler, it will be applied.
> Exclude Learn Astro ad from Algolia indexing

- src/content/docs/en/guides/deploy/cloudflare.mdx
Updates `deploy/cloudflare.mdx` to:
* fix a link (unwanted dot in markdown notation)
* update the steps numbers in `Cloudflare Workers` > `How to deploy with Wrangler` (they are fixed once rendered but might as well correct them in the file).
> fix: correct steps numbers and link format in `deploy/cloudflare`

- src/content/docs/en/reference/routing-reference.mdx
syntax mixing async/await and chained promise methods found in `routing-reference.mdx`
the change also conforms with the format of the `paginate()` sample which sits a few lines below
> docs: replace await.then() in `routing-reference.mdx`

- src/content/docs/en/guides/integrations-guide/markdoc.mdx
In Markdoc, the [`partial`](https://markdoc.dev/docs/partials) tag is a [self-closed tag](https://markdoc.dev/docs/tags) that should be closed with a `/`.
This PR updates the documentation to reflect that issue [spotted in Discord](https://discord.com/channels/830184174198718474/1075516604428857344/1358738618931220630).
- Closes #
> Fix Markdoc partial tag documentation

- src/components/starlight/PageSidebar.astro
- This PR adjusts CSS to prevent `LearnAstroAd` component from being cut off when the table of contents is long
- Closes #11378
- Suggested label: `design`
| ------ | ----- |
| ![long-toc-before](https://github.com/user-attachments/assets/42ea9beb-c282-49a6-9363-808215ebf66e) | ![long-toc-after](https://github.com/user-attachments/assets/f958d947-ecf8-4807-aa5f-7f01f988d969) |
> fix(css): prevent `LearnAstroAd` from being cut off when TOC is long

- src/content/docs/zh-cn/guides/configuring-astro.mdx
Added missing ``` marker in `configuring-astro.mdx`.
> i18n(zh-cn): fix missing code block closing tag in `configuring-astro.mdx`

- src/content/docs/es/reference/experimental-flags/heading-id-compat.mdx
> i18n(es): translate `heading-id-compat.mdx`

- src/content/docs/en/reference/image-service-reference.mdx
This PR documents the new function `emitImageMetadata`
> feat: document `emitImageMetadata`, deprecate `emitESMImage`

- src/content/docs/en/guides/integrations-guide/cloudflare.mdx
- src/content/docs/en/guides/sessions.mdx
- src/content/docs/en/reference/api-reference.mdx
This PR fixes the call of `Astro.session` and `ctx.session`. The `session` object *might* be `undefined`, so we need the `?` to gracefully handle its access.
> fix: change access signature to `Astro.session`

- src/content/docs/fr/reference/image-service-reference.mdx
Adds changes from #11401 to the French translation of `image-service-reference.mdx`.
> i18n(fr): update `image-service-reference.mdx`

- src/content/docs/en/tutorial/1-setup/2.mdx
Updates the tutorial installation instructions because they can now choose the minimal template directly from create astro and no longer need a flag to install it. Yay!
- Closes #10843
> [tutorial] update install commands for create astro

- src/content/docs/fr/reference/experimental-flags/fonts.mdx
Creates the French translation of `experimental-flags/fonts` added in #11444
> i18n(fr): add `experimental-flags/fonts.mdx`

- src/content/docs/en/reference/modules/astro-config.mdx
- src/content/docs/fr/reference/modules/astro-config.mdx
- src/content/docs/ko/reference/modules/astro-config.mdx
I noticed the typo while browsing the docs
- Closes #
> docs: fix typo of `srcDir`

- README.md
- scripts/lunaria.mts
- scripts/lunaria/components.ts
- Generates a `summary.svg` file as part of Lunaria builds that shows progress for each locale.
- Adds this with a link to our Lunaria dashboard to the README.
- To support reasonable display on both light and dark backgrounds, this uses a somewhat muted grey text colour. This colour has roughly a 10:1 contrast ratio against both black and white.
- On mobile screens the text will appear slightly small, but I tried to strike a balance between a decent display on desktop and mobile.
- We only build Lunaria on `main` so can’t really preview this PR but here are a few examples:
> Update README and add a summary of translation progress

- src/content/docs/en/reference/experimental-flags/fonts.mdx
Changes `@theme {}` instructions for tailwind to `@theme inline {}` per the tailwind docs:
<https://tailwindcss.com/docs/theme#referencing-other-variables>
- Closes #11490
> Fix: Adds inline to Fonts Tailwind v4 instructions

- .github/ISSUE_TEMPLATE/CONTENT.yml
- .github/ISSUE_TEMPLATE/config.yml
This helps to guide people to making discussions for topics that are not errors/incorrect statements to be fixed in docs. It emphasizes that improvements (not just new content) should be made as discussion topics, so that critical errors are easier to spot and triage.
> [issue template] improve distinction between issue and discussion topics

- src/content/docs/en/guides/imports.mdx
Updates the `Node.js builtins` section in `guides/imports` to fix an incorrect example and to improve the wordings:
* replace the example with the one provided by Fryuni in the issue
* reword the intro to avoid blaming people that use Node.js built-ins
* remove incorrect statement 
I don't think I was in this (these? 😅 ) T&D or I don't recall... so maybe the idea was to not mention adapters at all? I'm referring to this comment: https://github.com/withastro/docs/issues/7785#issuecomment-2371273677
Note: I'm not a native speaker but I believe `built-in`/`builtin` are the same... I used `built-in` because it seems to be the syntax used in other pages (I checked with Algolia). Should we update the heading as well?
- Closes #7785 (I think after a year it's time to close this one 😄 )
- …
> fix(guides/imports): update Node.js built-ins section

- src/content/docs/en/guides/cms/preprcms.mdx
- src/content/docs/en/guides/cms/strapi.mdx
- src/content/docs/en/guides/routing.mdx
I added a change to the “SSR Mode” topic, because an error occurred when I tried to create dynamic routes using SSR instead of SSG. The error in question complains about the lack of “getStaticPaths()” when I try to create the build with dynamic routes without a “getStaticPaths()”. The solution I found in programming communities was to add an extra line, disabling “pre-rendering” in conjunction with an integrated SSR adapter.
- Closes #
> Update routing.mdx to reflect the need for adapters and prerender binding in SSR mode

- src/content/docs/en/guides/integrations-guide/cloudflare.mdx
update cloudflare integration guide
> fix: update cloudflare integration guide

- src/content/docs/en/reference/cli-reference.mdx
Adds dev server hot keys in CLI `astro dev` reference.
- Closes #11516
- Suggested label: add new content
Discord Username: jonoyeong
> Document dev server hot keys in CLI reference

- src/content/docs/de/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/ko/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/zh-cn/guides/migrate-to-astro/from-create-react-app.mdx
This PR fixes incorrect `<style>` closing tags (`<style>` instead of `</style>`) in multiple documentation pages across different languages.  
I checked [i18n.docs.astro.build](https://i18n.docs.astro.build/) to ensure changes were only made to pages that were translated and needed fixing.  
No content was changed – only the HTML structure was corrected.
-   Suggested label: `fix`
> [i18nIgnore] Fixed a missing closing <style> tag

- src/content/docs/en/recipes/i18n.mdx
A code snippet in the `i18n` recipe was still using `slug` (legacy content collections) instead of `id` (content layer), so I replaced `page.slug` with `page.id`.
> fix(recipes/i18n): update code snippet to use collection `id`

- src/content/docs/ko/guides/integrations-guide/netlify.mdx
> i18n(ko-KR): update `netlify.mdx`

- src/content/docs/ko/guides/integrations-guide/node.mdx
> i18n(ko-KR): update `node.mdx`

- src/content/docs/ko/guides/integrations-guide/vercel.mdx
> i18n(ko-KR): update `vercel.mdx`

- src/content/docs/fr/guides/deploy/netlify.mdx
Adds changes from #11497 to the French translation of `guides/deploy/netlify.mdx`.
> i18n(fr): update `guides/deploy/netlify.mdx`

- src/content/docs/fr/reference/configuration-reference.mdx
- src/content/docs/fr/reference/experimental-flags/responsive-images.mdx
Adds changes from #11513 to the French translation of `experimental-flags/responsive-images.mdx`.
> i18n(fr): update `experimental-flags/responsive-images.mdx`

- src/content/docs/en/recipes/i18n.mdx
The code snippet didn't properly import `translatePath` that is actually returned from `useTranslatedPath`. This PR adds the proper usage.
- Closes #
> Fix `i18n.mdx` snippet missing import and correct usage

- src/content/docs/en/guides/deploy/cloudflare.mdx
Recommend using workers instead of pages for new projects deployed to cloudflare as per https://blog.cloudflare.com/full-stack-development-on-cloudflare-workers.
@sarah11918 thanks for flagging this!
> Add note to Cloudflare deploy guide about using Workers vs Pages

- src/content/docs/en/reference/experimental-flags/fonts.mdx
- Clarifies what unicodeRange does (feedback from Matt)
- Explains how to infer weight and style for the local provider. I'm not really happy about what I wrote because it's at the end of the section but it's important because it's teh default feedback welcome!
- Closes #
> feat(fonts): local inference

- src/content/docs/zh-cn/guides/client-side-scripts.mdx
Update `client-side-scripts.mdx`
- #11627 
> i18n(zh-cn): Update `client-side-scripts.mdx`

- src/content/docs/en/basics/astro-components.mdx
Updates the `basics/astro-components.mdx` file to:
* fix a broken syntax highlighting (noticed while updating the French file, in French this is broken... in English this is invisible)
|Before|After|
|---|---|
|![Broken syntax highlighting before](https://github.com/user-attachments/assets/9f4dd577-eb8d-4633-8219-f7713061fdc7)|![broken syntax highlighting after](https://github.com/user-attachments/assets/1e37eadd-6ad1-4b79-bf07-176c583e1783)|
* update a syntax highlighting because the example is describing using `slot` with `Fragment` so I think it could be useful to highlight the closing tag too:
|Before|After|
|---|---|
|![Incomplete syntax highlighting before](https://github.com/user-attachments/assets/b345e3f5-6fea-402f-8f89-5df90df2c647)|![Incomplete syntax highlighting …
> fix(astro-components): update syntax highlighting and add link

- src/content/docs/en/guides/routing.mdx
> [i18nIgnore] Update routing.mdx - removed unecessary comma

- src/content/docs/en/guides/cms/contentful.mdx
- src/content/docs/en/guides/cms/ghost.mdx
- src/content/docs/en/guides/cms/hashnode.mdx
- src/content/docs/en/guides/cms/preprcms.mdx
- src/content/docs/en/guides/cms/sitecore.mdx
- src/content/docs/en/guides/cms/statamic.mdx
- src/content/docs/en/guides/cms/strapi.mdx
- src/content/docs/en/guides/cms/umbraco.mdx
Updates some `guides/cms` pages to fix:
* some indentation in `<FileTree />` components (files wasn't under `src/` because of that)
* some code snippets title (we had an extra `"` before the title because the closing quote was missing)
* some code snippets languages
* a line marker in a code snippet to include the closing brace
* a typo in `sitecore.mdx`
In addition:
* in `preprcms.mdx`: rewrite the file trees because they were a bit off compared to what is described in the guide (ie. none of the files were under `src/`) and remove a leftover from #11501
* in `contentful.mdx`: replace `Server side rendering` with `On demand rendering` reusing the same wording used in Strapi.
I also noticed that [Keystatic](https://docs.astro.build/en/guides/cms/keystatic/#displaying-a-single-entry) uses …
> fix(guides/cms): update some FileTree and code snippets

- src/content/docs/fr/guides/cms/apostrophecms.mdx
Updates the French translation of `guides/cms/apostrophecms.mdx` to:
* fix some typo / indentation
* fix some bad translation (`message` instead of `article` for `posts`)
* translate `piece` consistently (we had both `pièce` and `morceau`... while the later sounds better, `piece` is an ApostropheCMS concept also used in the CLI... so I guess using `pièce` would be less confusing)
* rewords some parts (related to #11593)
> i18n(fr): update `guides/cms/apostrophecms.mdx`

- src/content/docs/fr/guides/cms/contentful.mdx
Updates the French translation of `guides/cms/contentful` with changes from:
* #11722 
* #11593
* replace `construction` with `compilation`
* replace `rendre` with `générer`
* replace `template` with `modèle`
* replace `paquetage` with `paquet`
* fix some bad translations (e.g. type, hacking)
* translate some untranslated parts
* reword some sentences to make the reading easier
> i18n(fr): update `guides/cms/contentful.mdx`

- src/content/docs/fr/guides/cms/statamic.mdx
Updates the French translation of `guides/cms/statamic.mdx` with changes from:
* #11722 (code snippet titles)
* #11593
* replace `rendre` with `restituer`
* add language after community links
* I don't know when the first sentence was updated but it didn't match (and yes, it seems `fichiers plats` is the expected translation... See [Grand dictionnaire terminologique of Quebec](https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8373984/fichier-plat) and I also found this on French websites)
> i18n(fr): update `guides/cms/statamic.mdx`

- src/content/docs/fr/guides/cms/strapi.mdx
Updates the French translation of `guides/cms/strapi.mdx`:
* with changes from #11722 (code snippets titles)
* to fix indentation in `FileTree`
* with changes related to #11593
* replace `construire` with other words when more appropriated
* replace `construction` with `compilation`
* replace `rendre` with more appropriate words
* replace `point d'accès` with `point de terminaison`
* use a consistent translation for `unwrap` (while we don't have an official translation for wrapper, this is commonly translated with `envelopper` - probably because of [Quebec recommandations](https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8871097/classe-enveloppante) - so `unwrap` would be `désenvelopper`)
* translate community links and add language after
> i18n(fr): update `guides/cms/strapi.mdx`

- src/content/docs/fr/guides/cms/builderio.mdx
- src/content/docs/fr/guides/cms/buttercms.mdx
- src/content/docs/fr/guides/cms/caisy.mdx
- src/content/docs/fr/guides/cms/cloudcannon.mdx
- src/content/docs/fr/guides/cms/cosmic.mdx
- src/content/docs/fr/guides/cms/craft-cms.mdx
- src/content/docs/fr/guides/cms/crystallize.mdx
- src/content/docs/fr/guides/cms/datocms.mdx
- src/content/docs/fr/guides/cms/directus.mdx
- src/content/docs/fr/guides/cms/drupal.mdx
- src/content/docs/fr/guides/cms/flotiq.mdx
- src/content/docs/fr/guides/cms/frontmatter-cms.mdx
- src/content/docs/fr/guides/cms/gitcms.mdx
- src/content/docs/fr/guides/cms/hygraph.mdx
- src/content/docs/fr/guides/cms/index.mdx
- src/content/docs/fr/guides/cms/keystatic.mdx
- src/content/docs/fr/guides/cms/keystonejs.mdx
- src/content/docs/fr/guides/cms/kontent-ai.mdx
- src/content/docs/fr/guides/cms/microcms.mdx
- src/content/docs/fr/guides/cms/payload.mdx
- src/content/docs/fr/guides/cms/prismic.mdx
- src/content/docs/fr/guides/cms/sanity.mdx
- src/content/docs/fr/guides/cms/spinal.mdx
- src/content/docs/fr/guides/cms/storyblok.mdx
- src/content/docs/fr/guides/cms/studiocms.mdx
- src/content/docs/fr/guides/cms/tina-cms.mdx
- src/content/docs/fr/guides/cms/wordpress.mdx
Improves the wording in the French translation of `guides/cms` (see #11593):
* fix bad translations (e.g. `message` instead of `article`)
* fix indentation in some `FileTree`
* replace `sans tête` with `headless`
* replace `crypter` with `chiffrer`
* replace `rendre` with `générer` / `restituer`
* replace `template` with `modèle`
* replace `construction` with `compiler`
* replace `cadre` with `framework`
* replace `style` with `mise en forme`
* replace `support` with `prise en charge`
* replace `fetch` with `récupération`
* replace `bundle` with `regroupement`
* replace `en` with `Anglais` in community links
* translate untranslated parts
* use French quotes instead of double quotes
* reword some sentences to make the reading easier
> i18n(fr): improve wording in remaining `guides/cms`

- src/content/docs/fr/guides/deploy/aws.mdx
- src/content/docs/fr/guides/deploy/azion.mdx
- src/content/docs/fr/guides/deploy/buddy.mdx
- src/content/docs/fr/guides/deploy/cleavr.mdx
- src/content/docs/fr/guides/deploy/clever-cloud.mdx
- src/content/docs/fr/guides/deploy/deno.mdx
- src/content/docs/fr/guides/deploy/edgio.mdx
- src/content/docs/fr/guides/deploy/fleek.mdx
- src/content/docs/fr/guides/deploy/flightcontrol.mdx
- src/content/docs/fr/guides/deploy/flyio.mdx
- src/content/docs/fr/guides/deploy/github.mdx
- src/content/docs/fr/guides/deploy/gitlab.mdx
- src/content/docs/fr/guides/deploy/google-cloud.mdx
- src/content/docs/fr/guides/deploy/google-firebase.mdx
- src/content/docs/fr/guides/deploy/heroku.mdx
- src/content/docs/fr/guides/deploy/index.mdx
- src/content/docs/fr/guides/deploy/kinsta.mdx
- src/content/docs/fr/guides/deploy/microsoft-azure.mdx
- src/content/docs/fr/guides/deploy/render.mdx
- src/content/docs/fr/guides/deploy/sst.mdx
- src/content/docs/fr/guides/deploy/stormkit.mdx
- src/content/docs/fr/guides/deploy/surge.mdx
- src/content/docs/fr/guides/deploy/vercel.mdx
- src/content/docs/fr/guides/deploy/zeabur.mdx
- src/content/docs/fr/guides/deploy/zerops.mdx
- src/content/docs/fr/guides/integrations-guide/netlify.mdx
- src/content/docs/fr/guides/integrations-guide/node.mdx
Improves the wording in the French translation of the remaining `guides/deploy` (see #11593):
* use infinitive form in title/headings
* replace `construction` with `compilation`
* `le CLI` > `la CLI`
* `endpoint` > `point de terminaison` (instead of `extrémité/accès`)
* `policy` > `stratégie`
* `package` > `paquet`
* `delivery` > `diffusion` instead of `livraison`
* replace `référentiel` with `dépôt`
* add or replace community links language
* `Node.js runtime` > `environnement d'exécution Node.js` (see [Node.js](https://nodejs.org/fr))
* translate some examples
* consistent use of imperative form in steps
* small rewording to make the reading easier
* update some parts to match the English version (ie. missing words or sentence parts)
> i18n(fr): improve the wording in the remaining `guides/deploy`

- src/content/docs/fr/guides/astro-db.mdx
- src/content/docs/fr/guides/environment-variables.mdx
- src/content/docs/fr/guides/integrations-guide/alpinejs.mdx
- src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
- src/content/docs/fr/guides/integrations-guide/db.mdx
- src/content/docs/fr/guides/integrations-guide/deno.mdx
- src/content/docs/fr/guides/integrations-guide/index.mdx
- src/content/docs/fr/guides/integrations-guide/markdoc.mdx
- src/content/docs/fr/guides/integrations-guide/mdx.mdx
- src/content/docs/fr/guides/integrations-guide/netlify.mdx
- src/content/docs/fr/guides/integrations-guide/node.mdx
- src/content/docs/fr/guides/integrations-guide/partytown.mdx
- src/content/docs/fr/guides/integrations-guide/preact.mdx
- src/content/docs/fr/guides/integrations-guide/react.mdx
- src/content/docs/fr/guides/integrations-guide/sitemap.mdx
- src/content/docs/fr/guides/integrations-guide/solid-js.mdx
- src/content/docs/fr/guides/integrations-guide/svelte.mdx
- src/content/docs/fr/guides/integrations-guide/tailwind.mdx
- src/content/docs/fr/guides/integrations-guide/vercel.mdx
- src/content/docs/fr/guides/integrations-guide/vue.mdx
Updates the French translations in `integrations-guide` to improve the wording (see #11593):
* replace `île` with `îlot`
* replace `plugin` with `module d'extension`
* replace `le CLI` with `la CLI`
* replace `construction` with `compilation` ou `génération`
* replace `référentiel`/`repo` with `dépôt`
* replace `rendre` with `effectuer le rendu`
* replace `cadre` with `framework`
* replace `styliser` with `mettre en forme`
* replace `support` with `prise en charge`
* replace the translation of `breaking` (change, schema) with `avec rupture de compatibilité`
* replace `drapeau`/`flags` with `option` (see [Wikipedia](https://fr.wikipedia.org/wiki/Interface_en_ligne_de_commande#Option))
* use infinitive form in headings
* reword some sentences to make the reading easier
* translate some …
> i18n(fr): improve the wording in `integrations-guide`

- src/content/docs/en/recipes/i18n.mdx
`astro-loader-i18n` is a **content loader** for internationalized content in [Astro](https://astro.build). It builds on top of Astro’s [`glob()` loader](https://docs.astro.build/en/reference/content-loader-reference/#glob-loader) and helps manage translations by detecting locales, mapping content, and enriching `getStaticPaths`.
It helps to translate routes, thus I want to add it to the community libraries. So far it's the only solution that uses a custom loader approach, compared to the other listed libraries.
> docs: add astro-loader-i18n to community libraries

- src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx
We had migration guides still referring to `getEntryBySlug` instead of `getEntry`, so I replaced the two references.
- Suggested label: `typo/link/grammar - quick fix!` (not really a typo but certainly a quick fix!)
> fix(migrate-to-astro): replace `getEntryBySlug` with `getEntry`

- src/content/docs/fr/guides/media/cloudinary.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-eleventy.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gitbook.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gridsome.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-hugo.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-jekyll.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-pelican.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-sveltekit.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-vuepress.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-wordpress.mdx
- src/content/docs/fr/guides/migrate-to-astro/index.mdx
Updates the French translations in `guides/migrate-to-astro` and `guides/media` (a single file) to improve the wording (see #11593):
* replace `sans tête` with `headless`
* replace `barrières de code` with `délimitateurs de code`
* replace `construit` with `créé`/`généré` in some places
* replace `construction` with `compilation`
* replace `template`  with `modèle`
* replace `île` with `îlot`
* replace `documents` with `documentation`
* replace `plugins` with `modules d'extension`
* replace `livraison` with `diffusion`
* replace `supporte` with `prend en charge`
* replace `actifs` with `ressources`
* replace `cadre` with `framework`
* replace `en` with `Anglais` in community links
* reword some sentences to make the reading easier
* add some changes to match the English version (missing …
> i18n(fr): improve the wording in `guides/migrate-to-astro`

- src/content/docs/fr/guides/upgrade-to/v3.mdx
- src/content/docs/fr/guides/upgrade-to/v4.mdx
Improves the wording in the French translation of `upgrade-to/v3.mdx` based on #11593 and #11795
* update the translation of `breaking changes`, `upgrade`, `deprecated`, `flag`
* replace `le CLI` with `la CLI`
* replace the translation of `build` where more appropriate
* small fixes and rewording to make the reading easier
> i18n(fr): improve the wording in `upgrade-to/v3.mdx`

- src/content/docs/fr/basics/astro-components.mdx
- src/content/docs/fr/editor-setup.mdx
- src/content/docs/fr/guides/backend/supabase.mdx
- src/content/docs/fr/guides/cms/frontmatter-cms.mdx
- src/content/docs/fr/guides/deploy/cloudflare.mdx
- src/content/docs/fr/guides/deploy/index.mdx
- src/content/docs/fr/guides/integrations-guide/db.mdx
- src/content/docs/fr/guides/integrations-guide/index.mdx
- src/content/docs/fr/guides/integrations-guide/node.mdx
- src/content/docs/fr/guides/integrations-guide/preact.mdx
- src/content/docs/fr/guides/integrations-guide/sitemap.mdx
- src/content/docs/fr/guides/media/cloudinary.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gridsome.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-pelican.mdx
- src/content/docs/fr/install-and-setup.mdx
- src/content/docs/fr/tutorial/2-pages/1.mdx
- src/content/docs/fr/tutorial/2-pages/2.mdx
- src/content/docs/fr/tutorial/2-pages/3.mdx
- src/content/docs/fr/tutorial/2-pages/4.mdx
- src/content/docs/fr/tutorial/3-components/1.mdx
- src/content/docs/fr/tutorial/3-components/4.mdx
- src/content/docs/fr/tutorial/6-islands/1.mdx
Sorry for the title not really explicit 😅 
This PR updates all the files already reviewed since #11593 to apply changes from the new i18n-guide update, see #11795
* replace `délimitateur` with `délimiteur`
* replace `support` with `prise en charge`
* remove `en direct` where it doesn't make sense
* update the use of `en ligne` for `inline` by either rewording the sentence or removing `en ligne` because I think the context is already clear no need to make the sentence cumbersome by repeating `dans le fichier`.
* reword a sentence in the Pelican guide to make reading smoother.
> i18n(fr): improve the wording in already updated files (second pass)

- src/content/docs/fr/guides/content-collections.mdx
- src/content/docs/fr/guides/upgrade-to/v5.mdx
- src/content/docs/fr/reference/integrations-reference.mdx
Improves the wording in the French translation of upgrade-to/v4.mdx based on #11593 and #11795
* update the translation of `breaking changes`, `upgrade`, `deprecated`, `flag`, `endpoint`
* replace the translation of `build` where more appropriate
* translate `plugins` and API names
* remove the translation of `glob`
* replace `itinéraires` with `routes`
* replace `import` with `importation`
* replace `endpoint`/`point d'arrivée` with `point de terminaison`
* replace `supporté` with `pris en charge`
* update the translation of the form submission message (doing a quick search it seems the message use `nouvel envoi`)
* small fixes and rewording to make the reading easier
And fixes links in other files following my changes
> i18n(fr): improve the wording in `upgrade-to/v5.mdx`

- src/content/docs/fr/guides/upgrade-to/v4.mdx
Improves the wording in the French translation of `upgrade-to/v4.mdx` based on #11593 and #11795
* update the translation of `breaking changes`, `upgrade`, `deprecated`, `flag`
* translate `plugins`
* replace the translation of `build` where more appropriate
* small rewording to make the reading easier
> [!NOTE]
> The broken links should be fixed once #11835 is merged: I applied the links updates on this PR to avoid a potential Git conflict while updating the branch since I also updated the paragraphs here.
> i18n(fr): improve the wording in `upgrade-to/v4.mdx`

- src/content/docs/ko/reference/adapter-reference.mdx
> i18n(ko-KR): update `adapter-reference.mdx`

- src/content/docs/zh-cn/reference/configuration-reference.mdx
- src/content/docs/zh-cn/reference/experimental-flags/responsive-images.mdx
Update `configuration-reference.mdx`
- #11787
> i18n(zh-cn): Update `configuration-reference.mdx` & `responsive-images.mdx`

- src/content/docs/zh-cn/reference/adapter-reference.mdx
Update `adapter-reference.mdx`
- #11826 
> i18n(zh-cn): Update `adapter-reference.mdx`

- src/content/docs/en/reference/experimental-flags/csp.mdx
This PR updates the CSP docs where view transitions via `ClientRouter` aren't supported anymore
> chore: update CSP docs for v5.9.2

- src/content/docs/en/recipes/build-forms.mdx
Adds a helpful comment `export const prerender = false; // Not needed in 'server' mode` to the form handling code examples in the build-forms recipe documentation.
This clarifies that pages handling forms need to be server-rendered (not pre-rendered at build time) to avoid the "Content-Type was not one of 'multipart/form-data' or
'application/x-www-form-urlencoded'" error that users have been encountering.
The comment follows the same pattern used in Astro's on-demand rendering documentation for consistency.
- Closes #11575
- Suggested label: `improve existing docs`
> fix: build forms recipe

- src/content/docs/fr/basics/astro-components.mdx
- src/content/docs/fr/guides/markdown-content.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
- src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx
- src/content/docs/fr/guides/styling.mdx
- src/content/docs/fr/tutorial/2-pages/4.mdx
- src/content/docs/fr/tutorial/2-pages/5.mdx
Following #11593 and #11795, updates the wording used in `guides/styling.mdx`:
* replace `styliser` with `mettre en forme` (+ fix links in other pages)
* replace `plugin` with `module d'extension`
* replace `supporter` with `prise en charge`
* replace `construire` with `compiler` where more appropriate
* replace `paquet` with `regroupement` for `bundle`
* replace `cette en-tête` with `cet en-tête` (it's [a masculine noun](https://www.larousse.fr/dictionnaires/francais/en-t%C3%AAte/29917))
* replace the translation of `inline` with something more meaningful than `en ligne` 
* fix some tiny mismatches with the English version
> i18n(fr): improve the wording in `guides/styling.mdx`

- src/content/docs/en/reference/experimental-flags/live-content-collections.mdx
This PR adds more explicit guidance re: on-demand rendering required to use live content collections. Includes:
- a prompt to make sure you have an adapter configured before adding the experimental feature
- the following standard line for opting out of prerendering on an individual page for any `.astro` code snippet:
```
export const prerender = false; // Not needed in 'server' mode
```
> on-demand rendering for experimental Live Content collections

- src/content/docs/en/reference/experimental-flags/live-content-collections.mdx
In `experimental-flags/live-content-collections`:
* Fixes an ordered list: The rendered list is incremented but the MDX file numbers all elements with 1.
* Uses a consistent verb tense in the same list:  Not sure if we should use `[They] run` or `[it] runs` for the verb tense but currently we have a mix between the two. I guess the plural form makes more sense since we don't use the singular in the opening sentence.
- Suggested label: `consistency/formatting`
> fix(live-content-collections): increment `ol` + consistent verb tense

- src/content/docs/fr/reference/experimental-flags/live-content-collections.mdx
Adds changes from #11920 and #11923 to the French translation of `experimental-flags/live-content-collections` (note: verb tense was already fixed in the translation).
> i18n(fr): update `experimental-flags/live-content-collections.mdx`

- src/content/docs/fr/reference/error-reference.mdx
- src/content/docs/fr/reference/errors/live-content-config-error.mdx
Adds the French translation of `errors/live-content-config-error` added in #11901 and fixed in #11915.
> i18n(fr): add `errors/live-content-config-error.mdx`

- src/content/docs/fr/reference/errors/live-content-config-error.mdx
Adds a blank line at the end of the French translation of `errors/live-content-config-error` to set it as up to date. The English version was updated in #11926 ... but this only adds empty lines at the end of the file.
> i18n(fr): update `errors/live-content-config-error.mdx`

- src/content/docs/en/reference/experimental-flags/live-content-collections.mdx
Adds a new field to experimental live collections. This is released in 5.10.1
- Closes #
> Add `cacheHint.lastModified` to live collections

- src/content/docs/fr/guides/content-collections.mdx
Adds changes from #11908 and #11944 to the French translation of `guides/content-collections`.
> i18n(fr): update `guides/content-collections`

- src/content/docs/fr/guides/server-islands.mdx
- src/content/docs/fr/guides/syntax-highlighting.mdx
Updates the French translations of `guides/server-islands` and `guides/syntax-highlighting` based on the [French i18n guide update](https://github.com/withastro/docs/blob/main/i18n-guides/fran%C3%A7ais.md):
* reword some parts to match the English version
* fix typo
* replace `support` with `pris en charge`
* replace `barrières` with `délimiteurs`
* replace `styliser` with `mettre en forme`
* replace the translation for `inline styles`/`inline code`
* replace `package` with `paquet`
> i18n(fr): improve the wording in `server-islands` & `syntax-highlighting`

- src/content/docs/en/guides/integrations-guide/netlify.mdx
- src/content/docs/en/guides/integrations-guide/node.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
This PR adds documentation of `experimentalStaticHeaders` for the Node.js adapter and Netlify adpater.
> feat: document experimental static headers

- src/components/tabs/TabPanel.astro
As this was brought up in today's T&D, this PR fixes a flash of invalid active tab in both the sidebar and the tutorial tracker (they both use the same component).
After investigating, it looks like Firefox refuses to animate when the `from` keyframe [only contains the `display: none;` property](https://github.com/withastro/docs/blob/2bf83d22e659c3acec7d46393c63a19c8ec7d8e1/src/components/tabs/TabPanel.astro#L37-L39) (even tho it should use a discrete animation type).
This PR adds `content-visibility: hidden;` to the `from` keyframe, which seems to trigger the animation correctly in Firefox and does not seem to change any other behavior.
- Closes #11611
> Fix Firefox sidebar content flash

- src/content/docs/fr/guides/integrations-guide/vercel.mdx
Adds changes from #11975 to the French translation of `integrations-guide/vercel.mdx`.
> i18n(fr): update `integrations-guide/vercel.mdx`

- src/content/docs/ja/guides/integrations-guide/react.mdx
This PR fixes a small Japanese typo in the React integration documentation.
- Closes #
- Suggested label: `documentation`, `typo`, `i18n`
> i18n(ja): correct Japanese typo in guides/integrations-guide/react.mdx

- src/content/docs/en/guides/prefetch.mdx
Astro´s `<ClientRouter />` component enables Astro´s prefetch feature by default.
Saying that _View Transitions_ set this default might be misleading.
- Closes #12021
> Reference `<ClientRouter />` component rather than view transitions on Prefetch page

- src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx
- src/content/docs/zh-cn/guides/integrations-guide/node.mdx
- src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
Update netlify.mdx、node.mdx、vercel.mdx
- https://github.com/withastro/docs/pull/11975
> i18n(zh-cn): Update netlify.mdx、node.mdx、vercel.mdx

- src/content/docs/en/guides/integrations-guide/netlify.mdx
Adds a reference to the Netlify `devFeatures`. See https://github.com/withastro/astro/pull/14078
- Closes #
> Add Netlify dev reference

- src/content/docs/en/guides/build-with-ai.mdx
As [reported on Mastodon](https://indieweb.social/@zero_gravitas/114864839962052827), even tho the MCP server Raycast install link used to work for me [earlier this afternoon](https://github.com/withastro/docs/pull/12019#issuecomment-3078754800) on `v1.100.0`, it looks like it's no longer working on [`v1.101.0`](https://www.raycast.com/changelog/1-101-0) ([released 10 hours ago](https://x.com/raycast/status/1945456589756043466) and which includes changes to both MCP server and Streamable HTTP support).
To temporarily address this, this PR updates the Raycast install link to use a proxy like the [Windsurf instructions do](https://docs.astro.build/en/guides/build-with-ai/#windsurf).
For reference, here is the new decoded URL:
```
{"name":"Astro …
```
> Update MCP server Raycast install link

- src/content/docs/ko/reference/errors/data-collection-entry-parse-error.mdx
- src/content/docs/ko/reference/errors/file-parser-not-found.mdx
> i18n(ko-KR): update `errors/`

- src/content/docs/ko/reference/experimental-flags/raw-env-values.mdx
> i18n(ko-KR): create `raw-env-values.mdx`

- src/content/docs/fr/reference/errors/data-collection-entry-parse-error.mdx
- src/content/docs/fr/reference/errors/file-parser-not-found.mdx
Adds changes from #12033 to the French translations of `errors/file-parser-not-found` and `errors/data-collection-entry-parse-error`.
> i18n(fr): update two `errors` reference

- src/content/docs/en/reference/content-loader-reference.mdx
Someone has spotted in the core repo (https://github.com/withastro/astro/pull/14096) that the use of `store.set`  in the code snippet used for `renderMarkdown` was incorrect. They have corrected the changelog, but we should fix it here as well.
The [DataStore set function](http://localhost:4321/en/reference/content-loader-reference/#set) only takes one argument.
> fix(content-loader-reference): update `store.set` usage in a snippet

- src/content/docs/en/guides/configuring-astro.mdx
- Corrected the example deployment domain from www.example/docs to www.example.com/docs
- Reworded the explanation about adding metadata to clarify the use of standard HTML <link> and <meta> tags
Suggested label: fix
> docs: fix example domain and improve clarity in config guide

- src/content/docs/fr/tutorial/0-introduction/index.mdx
- src/content/docs/fr/tutorial/1-setup/index.mdx
- src/content/docs/fr/tutorial/2-pages/index.mdx
- src/content/docs/fr/tutorial/3-components/index.mdx
- src/content/docs/fr/tutorial/4-layouts/index.mdx
- src/content/docs/fr/tutorial/5-astro-api/index.mdx
- src/content/docs/fr/tutorial/6-islands/4.mdx
- src/content/docs/fr/tutorial/6-islands/index.mdx
Adds changes from #12012 to the French translations of the tutorial.
Note:
* I reused the label defined in `i18n/fr.yml` as title for consistency and for the same reasons explained in https://github.com/withastro/docs/pull/12012#discussion_r2198259104
* I haven't replaced `Docs` with `Documentation` because all the auto-generated titles use `Docs`, so consistency again.
> i18n(fr): update `tutorial/*`

- package.json
- pnpm-lock.yaml
- scripts/lunaria/components.ts
- scripts/tuesday-bot.ts
This updates the Lunaria prerelease to the latest version (we were a few versions behind). This means there are a few refactors, new small features, and fixes (including one for the Netlify deploy)
Here's a dashboard upload you can test with these changes:
https://test-lunaria-fix.netlify.app/
Note: there are quite a few status changes between this and our current dashboard, from my investigation these all seem to be correct and related to fixes in how Lunaria directives are detected/applied.
For example, `ko` and `fr` both get a new outdated page from the 5.0 release PR, the `@lunaria-track:` directive didn't include localizations at *all*, so these files that had only link changes were marked as outdated in that PR and for some reason they weren't properly shown in the dashboard before. …
> Update Lunaria (Fixes Netlify deploy issue)

- src/content/docs/fr/reference/errors/only-response-can-be-returned.mdx
Updates the French translation of `errors/only-response-can-be-returned.mdx` to mark it as up to date. A link has been updated in #9240 both in the English and the French versions, so the file do not need changes.
> i18n(fr): update `errors/only-response-can-be-returned.mdx`

- src/content/docs/en/reference/modules/astro-actions.mdx
This PR adds documentation regarding date serialization in Astro actions, including an example for the following description:
_Actions use `JSON.stringify()` under the hood, which turns dates into their string representation. You can use z.coerce.date() instead._ 
Including this new example will help guide developers when they encounter issues with date interpolation.
- Closes #11644
- Suggested label: `improve or update documentation`
> Add instructions on date serialization at astro-actions.mdx

- src/content/docs/fr/guides/internationalization.mdx
- src/content/docs/fr/guides/middleware.mdx
Updates the French translation of `guides/middleware` to bring changes from the French i18n guide updates:
* replace `construction` with `compilation` where more appropriate
* replace `rendre` with `générer`
* replace `itinéraire` with `route`
* replace the translation for `type safety` (`sûreté du typage`)
* translate some examples
* use French quotes
* fix some mismatches with the English version (including the use of `on` when the original version do not use `we`)
* slightly reword some sentences to make the reading smoother (e.g. use the french word and the code version in parenthesis)
I also made some changes around the use of `middleware` (indefinite/definite article, plural). For example, middleware was the only one using an article in the nav so for consistency I removed it:
- …
> i18n(fr): improve the wording in `guides/middleware.mdx`

- src/content/docs/fr/guides/data-fetching.mdx
- src/content/docs/fr/guides/dev-toolbar.mdx
Updates the French translations of `guides/data-fetching.mdx` and `guides/dev-toolbar.mdx` to bring changes from the French i18n guide updates:
* replace `île` with `îlot`
* replace `construction` with `compilation` where more appropriate
* replace the translation for `fetch` (`recherche` > `récupération`)
* replace the translation for `to log` (ie. `se connecter` sounded odd)
* replace `drapeau` (`flag`) with `option`
* replace `(EN)` with `(Anglais)` for non translated links
* lowercase some words
* slightly rewords some sentences to make the reading smoother
> i18n(fr): improve the wording in `data-fetching` & `dev-toolbar`

- src/content/docs/fr/basics/astro-components.mdx
- src/content/docs/fr/guides/client-side-scripts.mdx
- src/content/docs/fr/guides/configuring-astro.mdx
- src/content/docs/fr/guides/upgrade-to/v5.mdx
Updates the French translations of `guides/client-side-scripts` and `guides/configuring-astro` with changes added to the French i18n guides:
* replace `construire` with `compiler` or `créer` where more appropriate
* replace `rendre` with `effectuer le rendu`
* replace `plugin` with `module d'extension`
* replace `supporté` with `pris en charge`
* replace `import` with `importation`
* replace `barrières` with `délimiteurs`
* fix some mismatches with the English version (e.g. plural)
> i18n(fr): improve the wording in `client-side-scripts` & `configuring-astro`

- src/content/docs/en/contribute.mdx
This adds an advanced GitHub search link to the contributing page which will let readers see all open issues across all the GitHub repos in the withastro organization that are labelled either "help wanted" or "good first issue".
> Add open issues tip to contributing page

- src/content/docs/en/guides/integrations-guide/partytown.mdx
When working on a complex site using Partytown, we found the need for proxying based on environment variables. We struggled a lot because we thought everything had to be passed through the integration config, but it turns out it can also come from `window.partytown`.
Anyways, here are the additions:
- Document that `config` is serialized which means you can't access things outside functions scopes. Not sure how to convey that functions are also serialized (ie. not converted to `null`)
- Document that you can also use `window.partytown`, with a real world example
- Closes #
> feat: clarify partytown config

- src/content/docs/en/recipes/rss.mdx
Adds additional context and guidance re: full post content in RSS feeds (what kinds of images are/aren't supported; things to consider; example to consult)
- Closes #10946
> context about limited full post content support in RSS

- src/content/docs/en/guides/cms/strapi.mdx
Updates the shape of the data returned from Strapi 5 per [Strapi's migration guide breaking changes](https://docs.strapi.io/cms/migration/v4-to-v5/breaking-changes/use-document-id)
Specifically:
- `id` is replaced by `documentId`
- there is no longer a nested `attributes` object for other data
This PR update the code blocks that show returned data and types, and additionally updates using the data in component templates because data is no longer on an `attributes` object.
According to the issue, there are other improvements that could be made for using Strapi 5 with Astro, but this at least updates the code blocks to show correct data.
- Closes #11907
> Updates CMS guide for Strapi 5

- src/content/docs/en/editor-setup.mdx
removed trailing comma in .prettierrc example config
- Closes #
> removed trailing comma in .prettierrc example config

- src/content/docs/en/guides/view-transitions.mdx
- src/content/docs/es/guides/view-transitions.mdx
- src/content/docs/fr/guides/view-transitions.mdx
- src/content/docs/ja/guides/view-transitions.mdx
- src/content/docs/ko/guides/view-transitions.mdx
- src/content/docs/ru/guides/view-transitions.mdx
- src/content/docs/zh-cn/guides/view-transitions.mdx
closes #12253
Uses the correct `localStorage.getItem()`.
Simplifies the `astro:before-swap` example in view-transitions to make it clearer and focused on the swap only.  
Removes `is:inline` and extra helper functions so readers can see the minimal working example.  
Old example:
```html
<script is:inline>
function setDarkMode(document) {
let theme = localStorage.darkMode ? "dark" : "light";
document.documentElement.dataset.theme = theme;
}
setDarkMode(document);
document.addEventListener("astro:before-swap", (event) => {
// Pass the incoming document to set the theme on it
setDarkMode(event.newDocument);
});
</script>
```
Updated example:
```html
<script>
document.addEventListener("astro:before-swap", (event) => {
event.newDocument.documentElement.dataset.theme = …
```
> clarify astro:before-swap example [i18nIgnore]

- src/content/docs/fr/guides/authentication.mdx
- src/content/docs/ja/guides/authentication.mdx
- src/content/docs/ko/guides/authentication.mdx
- src/content/docs/zh-cn/guides/authentication.mdx
#12261 didn't trigger a status change because the PR title contained `broken link`. So I updated all the translations with the broken link at once.
> [i18nIgnore] i18n(ja,ko,zh-cn,fr): update a broken link in `guides/authentication`

- src/content/docs/en/guides/integrations-guide/sitemap.mdx
This pull request adds documentation for the new `namespaces` configuration option to the sitemap integration guide. The update explains the purpose, type, and default values for this option, and provides a usage example.
**Sitemap integration documentation update:**
* Added a section describing the `namespaces` option, including its type, default values, and its role in controlling which XML namespaces are included during sitemap generation.
* Provided a code example in `astro.config.mjs` showing how to configure the `namespaces` option for the sitemap integration.
Updated docs for https://github.com/withastro/astro/pull/14285
- Closes #
> feat(sitemap): add configurable XML namespaces support

- src/content/docs/es/guides/backend/google-firebase.mdx
Update the `google-firebase.mdx` page in the Spanish documentation.
- [18614f0](https://github.com/withastro/docs/commit/18614f0c9a9f8cc1383b2e1db7dcbfa23427bfb6)
- [45a1170](https://github.com/withastro/docs/commit/45a117052d85d9a706e4095f1cb9ffb2b0bf2caa)
> i18n(es): update `google-firebase.mdx`

- src/content/docs/en/guides/cms/builderio.mdx
- src/content/docs/en/guides/cms/datocms.mdx
- src/content/docs/en/guides/cms/strapi.mdx
- src/content/docs/en/guides/environment-variables.mdx
- src/content/docs/en/guides/integrations-guide/alpinejs.mdx
- src/content/docs/en/guides/integrations-guide/cloudflare.mdx
- src/content/docs/en/guides/integrations-guide/netlify.mdx
- src/content/docs/en/guides/integrations-guide/vercel.mdx
- src/content/docs/en/guides/middleware.mdx
- src/content/docs/en/guides/sessions.mdx
- src/content/docs/en/guides/typescript.mdx
* Adds a new "Extending global types" section in `guides/typescript.mdx`:
* move `Extending windows & globalThis` as a subheading
* create a `Add non-standard attributes` subheading and move a part of `Built-in HTML attributes` in it
* create a new `Using imports` subheading (and its contents) to hopefully solve #11759 and all the similar issues we had
* Removes a duplicated link in "Import Aliases" (which I found confusing as a user and I don't think this is great for screen readers as well)
* Updates pages mentioning `.d.ts` files to add direct or indirect linking (when the environment variable guide might be more appropriate) to the new Typescript guide section.
I used `ReadMore` links for the CMS guides but I noticed we lack of consistency here: when linking to the environment …
> feat(typescript): extract extend global types to its own section

- src/content/docs/en/guides/images.mdx
This PR adds a section to the Images guide for the new `SvgComponent` type
> add SvgComponent type docs

- src/content/docs/en/guides/integrations-guide/react.mdx
Removes `experimental` from the functions 
Core PR: https://github.com/withastro/astro/pull/14386
> Update experimental React Actions helpers to stable

- astro.sidebar.ts
- src/content/docs/en/guides/images.mdx
- src/content/docs/en/guides/integrations-guide/react.mdx
- src/content/docs/en/reference/experimental-flags/fail-on-prerender-conflict.mdx
- src/content/docs/en/reference/experimental-flags/fonts.mdx
- src/content/docs/en/reference/routing-reference.mdx
Adds docs for the 5.14.0 minor release
- #12406
- #12316 
- #12345
- #12402
- #12237
> 5.14.0 minor release docs

- src/content/docs/en/reference/routing-reference.mdx
update wrong link in `routing-reference.mdx`
- Closes #
> fix: update wrong link in `routing-reference.mdx`

- src/content/docs/ko/reference/experimental-flags/fail-on-prerender-conflict.mdx
> i18n(ko-KR): create `fail-on-prerender-conflict.mdx`

- src/content/docs/zh-cn/guides/cms/storyblok.mdx
i18n(zh-cn): Update `storyblok.mdx`
- https://github.com/withastro/docs/pull/12433
> i18n(zh-cn): Update `storyblok.mdx`

- src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
- src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
- src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
- src/content/docs/zh-cn/guides/integrations-guide/solid-js.mdx
- src/content/docs/zh-cn/guides/integrations-guide/vue.mdx
Update some integrations-guide
- https://github.com/withastro/docs/pull/12319
> i18n(zh-cn): Update some integrations-guide

- src/content/docs/en/guides/upgrade-to/v6.mdx
Co-authored-by: Sarah Rainsberger <5098874+sarah11918@users.noreply.github.com>
I don't think docs need to be updated elsewhere because the things getting deprecated were already not documented anymore
- Closes #
> [v6] clean deprecated APIs

- src/content/docs/en/guides/endpoints.mdx
- src/content/docs/en/guides/upgrade-to/v6.mdx
Co-authored-by: Sarah Rainsberger <5098874+sarah11918@users.noreply.github.com>
- Closes #
> [v6] trailing slash never for endpoints with file extension

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
[Hacktoberfest](https://hacktoberfest.com/) is back for this year!
This PR add Hacktoberfest participation information to contributing guidelines and PR template (a revert revert of #9905)
- Suggested label: docs
Hacktoberfest participation 🎃
> docs: add Hacktoberfest participation information
