withastro/docs

src/content/docs/it/guides/backend/turso.mdx

translate `guides/backend/turso.mdx`
**Related issues & labels (optional)**

i18n(it): translate `guides/backend/turso.mdx`

---

src/content/docs/it/guides/backend/turso.mdx
src/content/docs/it/integrations/integrations.mdx

translate `integrations/integrations.mdx`
**Related issues & labels (optional)**

i18n(it): translate `integrations/integrations.mdx`

---

src/content/docs/zh-cn/guides/backend/turso.mdx

Translate `guides/backend/turso.mdx` to Chinese version.
None

i18n(zh-cn): Translate `guides/backend/turso.mdx`

---

src/content/docs/zh-cn/guides/cms.mdx

Update `guides/cms.mdx`
Upstream PR:
- #5499
- Closes #

i18n(zh-cn): Update `guides/cms.mdx`

---

src/content/docs/zh-cn/guides/backend.mdx

Update `guides/backend.mdx`
Upstream PR:
- #5499
- Closes #

i18n(zh-cn): Update `guides/backend.mdx`

---

src/content/docs/ko/guides/backend.mdx

- update `backend.mdx`
- #5499 
- Closes #

i18n(ko-KR): update `backend.mdx`

---

src/content/docs/en/guides/testing.mdx

Format `guides/testing.mdx` content

---

src/content/docs/zh-cn/recipes/modified-time.mdx

Update `recipes/modified-time.mdx`
Upstream PR:
- #5888
- Closes #

i18n(zh-cn): Update `recipes/modified-time.mdx`

---

src/i18n/zh-cn/ui.ts

Update `i18n/zh-cn/ui.ts`
Upstream PR:
- #5887 
- Closes #

i18n(zh-cn): Update `i18n/zh-cn/ui.ts`

---

src/content/docs/en/guides/cms/storyblok.mdx

Added file extension to avoid a missing specifier
Its missing the file extension causing a missing specifier.
code snippet update

Added missing file extension.

---

src/content/docs/en/guides/deploy/netlify.mdx

A warning message about @astrojs/netlify/functions folder is reported on the terminal when I run the build script.
See screenshot attached in the PR
- Closes #

docs: update Netlify import

---

src/content/docs/zh-cn/reference/adapter-reference.mdx
src/content/docs/zh-cn/reference/integrations-reference.mdx

Update `adapter-reference.mdx`
Upstream PR:
- #5955
- Closes #

i18n(zh-cn): Update `adapter-reference.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx

fix wrong CHANGELOG.md link in integrations guide(mdx --> tailwind's CHANGELOG.md)

fix wrong CHANGELOG.md link in integrations guide

---

src/content/docs/zh-cn/guides/deploy/netlify.mdx

Update `guides/deploy/netlify.mdx`
Upstream PRs:
- #5528 
- #5977
- Closes #

i18n(zh-cn): Update `guides/deploy/netlify.mdx`

---

src/content/docs/zh-cn/core-concepts/astro-components.mdx

Update `core-concepts/astro-components.mdx`
Upstream PR: #5968
- Closes #

i18n(zh-cn): Update `core-concepts/astro-components.mdx`

---

src/content/docs/en/guides/integrations-guide/solid-js.mdx

Updated documentation to include the resolution of a previously identified issue, which exhibited unusual behavior when mixing SolidJS and React.
- Closes #5995

Add information on Mixing SolidJS and React

---

src/content/docs/fr/core-concepts/layouts.mdx

Update french translation for layouts.mdx file with pr #5698

i18n(fr) Update `layouts.mdx`

---

src/content/docs/fr/guides/cms.mdx

Update French Translation for cms.mdx file with PR #2546 and #5499

i18n(fr) Update `cms.mdx`

---

src/content/docs/fr/core-concepts/project-structure.mdx

Update French translation of project-structure.mdx file with PR #5880

i18n(fr) Update `project-structure.mdx`

---

src/content/docs/fr/guides/content-collections.mdx

Update french translation for content-collections.mdx file with PR #5765

i18n(fr) Update `content-collections.mdx`

---

src/content/docs/fr/guides/deploy.mdx

Update French Translation for deploy.mdx file with PR #5732

i18n(fr) Update `deploy.mdx`

---

src/content/docs/fr/guides/cms/wordpress.mdx

Update French Translation for wordpress.mdx file with PR #5820 and #5872

i18n(fr) Update `wordpress.mdx`

---

src/content/docs/fr/guides/configuring-astro.mdx

Update French Translation for configuring-astro.mdx file with PR #5667 and #6006

i18n(fr) Update `configuring-astro.mdx`

---

src/content/docs/fr/core-concepts/astro-pages.mdx

Update French translation for astro-pages.mdx page with #5765
- Suggested label: i18n(fr)

i18n(fr) Update `astro-pages.mdx`

---

src/content/docs/fr/core-concepts/framework-components.mdx

Update french translation for `framework-components.mdx` file with PR #5499

i18n(fr) Update `framework-components.mdx`

---

src/content/docs/fr/core-concepts/sharing-state.mdx

Update French translation for sharing-state.mdx file with PR #5572 #5766 #5994

i18n(fr) Update `sharing-state.mdx`

---

src/content/docs/fr/guides/cms/storyblok.mdx

Update French Translation for storyblok.mdx file with PR #5872 and #5949

i18n(fr) Update `storyblok.mdx`

---

src/content/docs/fr/guides/backend.mdx

Update French Translation for backend.mdx file with PR #5499

i18n(fr) Update `backend.mdx`

---

src/content/docs/fr/core-concepts/routing.mdx

Update french translation for routing.mdx file with PR #5765

i18n(fr) Update `routing.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx

i18n(zh-cn): Update alpinejs.mdx

---

src/content/docs/ko/core-concepts/astro-components.mdx

- update `astro-components.mdx`
- #5968 
- Closes #

i18n(ko-KR): update `astro-components.mdx`

---

src/i18n/ko/nav.ts

- update `nav.ts`
- #5499 
- Closes #

i18n(ko-KR): update `nav.ts`

---

src/content/docs/ko/guides/configuring-astro.mdx

- update `configuring-astro.mdx`
- #6006 
- Closes #

i18n(ko-KR): update `configuring-astro.mdx`

---

src/i18n/ko/ui.ts

- update `ui.ts`
- #5887 
- Closes #

i18n(ko-KR): update `ui.ts`

---

src/content/docs/ko/guides/integrations-guide.mdx

- update `integrations-guide.mdx`
- #6018 
- Closes #

i18n(ko-KR): update `integrations-guide.mdx`

---

src/content/docs/fr/guides/integrations-guide/alpinejs.mdx

i18n(fr): Add `integrations-guide/alpinejs` in French language
- Linked to https://github.com/withastro/docs/issues/6052

i18n(fr): Add `integrations-guide/alpinejs` in French language

---

src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx

i18n(zh-cn): Update vercel.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx

i18n(zh-cn): Update mdx.mdx

---

src/content/docs/en/guides/backend/supabase.mdx

If you copy and paste the actual code, you will have the error: `Type "string" is not assignable to type "Provider".`
So I just changed the line 438 and 426 to fix the error :)
Before:
After:

Fix: Type "string" is not assignable to type "Provider".

---

src/content/docs/en/reference/cli-reference.mdx

Telemetry clear is now telemetry reset.

Telemetry clear is now telemetry reset.

---

src/content/docs/fr/guides/integrations-guide/lit.mdx

i18n(fr): Add `integrations-guide/lit` in French language
- Linked to https://github.com/withastro/docs/issues/6052

i18n(fr): Add `integrations-guide/lit` in French language

---

src/content/docs/fr/reference/errors/unsupported-config-transform-error.mdx

i18n(fr): Translate unsupported-config-transform-error.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/lit.mdx

Update lit.mdx
Update lit.mdx
- #5978

i18n(zh-cn): Update lit.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/vue.mdx

i18n(zh-cn): Update vue.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx

i18n(zh-cn): Update markdoc.mdx

---

src/content/docs/fr/guides/backend/turso.mdx

French translation of the turso.mdx

i18n(fr): translate turso.mdx

---

src/content/docs/en/reference/cli-reference.mdx

(New feature) Update the `--open` flag to document passing a URL string.
- Closes #

Update open flag string value behaviour

---

src/content/docs/zh-cn/guides/images.mdx

Update images.mdx
- https://github.com/withastro/docs/pull/6109

i18n(zh-cn): Update images.mdx

---

src/content/docs/en/guides/integrations-guide/vercel.mdx

Fix code block in vercel.mdx
- Closes #

[en-only] Fix code block

---

src/content/docs/es/guides/deploy/google-firebase.mdx

Fix typo in `google-firebase.mdx`

i18n(es): Fix typo in `google-firebase.mdx`

---

src/content/docs/en/guides/integrations-guide/sitemap.mdx

Change `sitemap-index.xml` to `sitemap-0.xml`

Update Astro website sitemap URL

---

src/content/docs/en/guides/deploy/google-firebase.mdx
src/content/docs/es/guides/deploy/google-firebase.mdx
src/content/docs/fr/guides/deploy/google-firebase.mdx
src/content/docs/zh-cn/guides/deploy/google-firebase.mdx

This PR updates the Firebase deploy guide for consistent formatting.
These files were also recently translated into es, fr, and zh-cn, so I fixed those as well. They are currently marked as updated [on the tracker](https://i18n.docs.astro.build/)

[i18nignore] Update formatting for `deploy/google-firebase.mdx`

---

src/content/docs/en/guides/cms/ghost.mdx

Add new community resource for Ghost CMS as well as a reference to the community resource in the section containing information about the [slug].astro page.  Thank you astro for such a great baseline of a platform!
Add new community resource for Ghost CMS as well as a reference to the community resource in the section containing information about making the [slug].astro page work in SSR mode. 
- Closes #

Add community Resource. Ghost CMS Docs page.

---

src/content/docs/en/reference/api-reference.mdx

- https://github.com/withastro/docs/pull/5765
- Closes #

Fix formatting of version tags in API reference

---

src/content/docs/zh-cn/guides/migrate-to-astro/from-pelican.mdx

Update from-pelican.mdx
- Closes #

i18n(zh-cn): Update from-pelican.mdx

---

src/content/docs/zh-cn/guides/rss.mdx

i18n(zh-cn): Update rss.mdx

---

src/content/docs/zh-cn/guides/cms/sitecore.mdx

i18n(zh-cn): Create sitecore.mdx

---

src/content/docs/es/guides/cms/sitecore.mdx

Create Spanish translation for sitecore.mdx file with PR #6164

i18n(es): Create `sitecore.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx

i18n(zh-cn): Update tailwind.mdx

---

src/content/docs/zh-cn/guides/middleware.mdx

i18n(zh-cn): Update middleware.mdx

---

src/content/docs/es/guides/integrations-guide/alpinejs.mdx

i18n(es): Update `alpinejs`

---

src/content/docs/es/recipes/i18n.mdx

Update Spanish translation for i18n.mdx file with PR #5973

 i18n(es): Update `i18n.mdx`

---

src/content/docs/es/guides/cms/ghost.mdx
src/content/docs/es/guides/configuring-astro.mdx
src/i18n/es/nav.ts

Update `nav.ts`, `ghost.mdx` & `configuring-astro.mdx` based on these commits: 
- 351178b6811ee404fa7dcf06b6698fe0df62f1af
- 5a83f6e56f2dd0c2998e138a14f2ce38af52c1b5
- 2eec07c0ebb48ff94070f8a1fb1563f88ed84d3d

i18n(es): Update `nav.ts`, `ghost.mdx` & `configuring-astro.mdx`

---

src/content/docs/es/guides/integrations-guide.mdx

i18n(es): Update `integrations-guide`

---

src/content/docs/en/guides/rss.mdx

Updates the RSS guide.
- Suggested label: merge-on-release
See https://github.com/withastro/astro/pull/9610

Update docs for withastro/astro#9610

---

src/content/docs/pt-br/guides/configuring-astro.mdx

Update the Portuguese translation of the Configuring Astro guide

i18n(pt-BR): Update `guides/configuring-astro`

---

src/content/docs/pt-br/guides/backend.mdx

Update the Portuguese translation of the backend guide

i18n(pt-BR): Update `guides/backend`

---

src/content/docs/it/core-concepts/routing.mdx

- fix route examples
- removed full stops from headings

i18n(it) Update routing.mdx

---

src/content/docs/ko/reference/error-reference.mdx

i18n(ko-KR): update `error-reference.mdx`

---

src/content/docs/ko/reference/errors/no-image-metadata.mdx

-  add `no-image-metadata.mdx`
- Closes #

i18n(ko-KR): add `no-image-metadata.mdx`

---

src/content/docs/ko/reference/errors/markdown-image-not-found.mdx

- add `markdown-image-not-found.mdx`
- Closes #

i18n(ko-KR): add `markdown-image-not-found.mdx`

---

src/content/docs/ko/reference/errors/could-not-transform-image.mdx

- add `could-not-transform-image.mdx`
- Closes #

i18n(ko-KR): add `could-not-transform-image.mdx`

---

src/content/docs/ko/reference/errors/response-sent-error.mdx

- add `response-sent-error.mdx`
- Closes #

i18n(ko-KR): add `response-sent-error.mdx`

---

src/content/docs/ko/reference/errors/middleware-no-data-or-next-called.mdx

- add `middleware-no-data-or-next-called.mdx`
- Closes #

i18n(ko-KR): add `middleware-no-data-or-next-called.mdx`

---

src/content/docs/ko/reference/errors/middleware-not-aresponse.mdx

- add `middleware-note-aresponse.mdx`
- Closes #

i18n(ko-KR): add `middleware-note-aresponse.mdx`

---

src/content/docs/zh-cn/reference/errors/unhandled-rejection.mdx

Create unhandled-rejection.mdx
- #6253

i18n(zh-cn): Create unhandled-rejection.mdx

---

src/content/docs/ko/guides/backend/tigris.mdx

i18n(ko-KR): add `tigris.mdx`

---

src/content/docs/ko/guides/backend/appwriteio.mdx

- add `appwriteio.mdx`
- Closes #

i18n(ko-KR): add `appwriteio.mdx`

---

src/content/docs/ko/guides/cms/spinal.mdx

i18n(ko-KR): add `spinal.mdx`

---

src/content/docs/zh-cn/reference/errors/missing-locale.mdx

Create missing-locale.mdx
- #6253

i18n(zh-cn): Create missing-locale.mdx

---

src/content/docs/zh-cn/reference/errors/cant-render-page.mdx

Create cant-render-page.mdx
- #6253

i18n(zh-cn): Create cant-render-page.mdx

---

src/content/docs/zh-cn/guides/backend/turso.mdx

i18n(zh-cn): Update turso.mdx

---

src/content/docs/ko/guides/backend/turso.mdx

- update `turso.mdx`
- #6319
- Closes #

i18n(ko-KR): update `turso.mdx`

---

src/content/docs/ko/reference/errors/unsupported-config-transform-error.mdx

- add `unsupported-config-transform-error.mdx`
- Closes #

i18n(ko-KR): add `unsupported-config-transform-error.mdx`

---

src/content/docs/ko/reference/errors/duplicate-content-entry-slug-error.mdx

- add `duplicate-content-entry-slug-error.mdx`
- Closes #

i18n(ko-KR): add `duplicate-content-entry-slug-error.mdx`

---

src/content/docs/ko/reference/errors/data-collection-entry-parse-error.mdx

- add `data-collection-entry-parse-error.mdx`
- Closes #

i18n(ko-KR): add `data-collection-entry-parse-error.mdx`

---

src/content/docs/ko/reference/errors/content-collection-type-mismatch-error.mdx

- add `content-collection-type-mismatch-error.mdx`
- Closes #

i18n(ko-KR): add `content-collection-type-mismatch-error.mdx`

---

src/content/docs/ko/reference/errors/collection-does-not-exist-error.mdx

- add `collection-does-not-exist-error.mdx`
- Closes #

i18n(ko-KR): add `collection-does-not-exist-error.mdx`

---

src/content/docs/ko/reference/errors/content-schema-contains-slug-error.mdx

- add `content-schema-contains-slug-error.mdx`
- Closes #

i18n(ko-KR): add `content-schema-contains-slug-error.mdx`

---

src/content/docs/ko/reference/errors/invalid-content-entry-frontmatter-error.mdx

- add `invalid-content-entry-frontmatter-error.mdx`
- Closes #

i18n(ko-KR): add `invalid-content-entry-frontmatter-error.mdx`

---

src/content/docs/ko/reference/errors/unknown-content-collection-error.mdx

- add `unknown-content-collection-error.mdx`
- Closes #

i18n(ko-KR): add `unknown-content-collection-error.mdx`

---

src/content/docs/ko/reference/errors/generate-content-types-error.mdx

- add `generate-content-types-error.mdx`
- Closes #

i18n(ko-KR): add `generate-content-types-error.mdx`

---

src/content/docs/ko/reference/errors/unknown-clierror.mdx

- add `unknown-clierror.mdx`
- Closes #

i18n(ko-KR): add `unknown-clierror.mdx`

---

src/content/docs/ko/reference/errors/config-legacy-key.mdx

- add `config-legacy-key.mdx`
- Closes #

i18n(ko-KR): add `config-legacy-key.mdx`

---

src/content/docs/ko/reference/errors/config-not-found.mdx

- add `config-not-found.mdx`
- Closes #

i18n(ko-KR): add `config-not-found.mdx`

---

src/content/docs/ko/reference/errors/unknown-config-error.mdx

- add `unknown-config-error.mdx`
- Closes #

i18n(ko-KR): add `unknown-config-error.mdx`

---

src/content/docs/ko/reference/errors/mdx-integration-missing-error.mdx

- add `mdx-integration-missing-error.mdx`
- Closes #

i18n(ko-KR): add `mdx-integration-missing-error.mdx`

---

src/content/docs/ko/guides/cms/crystallize.mdx

add `crystallize.mdx`
- Closes #

i18n(ko-KR): add `crystallize.mdx`

---

src/content/docs/ko/guides/cms/directus.mdx

- add `directus.mdx`
- Closes #

i18n(ko-KR): add `directus.mdx`

---

src/content/docs/ko/reference/errors/csssyntax-error.mdx

- add `csssyntax-error.mdx`
- Closes #

i18n(ko-KR): add `csssyntax-error.mdx`

---

src/content/docs/ko/reference/errors/unknown-csserror.mdx

- add `unknown-csserror.mdx`
- Closes #

i18n(ko-KR): add `unknown-csserror.mdx`

---

src/content/docs/ko/reference/errors/failed-to-load-module-ssr.mdx

- add `failed-to-load-module-ssr.mdx`
- Closes #

i18n(ko-KR): add `failed-to-load-module-ssr.mdx`

---

src/content/docs/ko/reference/errors/unknown-vite-error.mdx

- add `unknown-vite-error.mdx`
- Closes #

i18n(ko-KR): add `unknown-vite-error.mdx`

---

src/content/docs/ko/reference/errors/invalid-dynamic-route.mdx

- add `invalid-dynamic-route.mdx`
- Closes #

i18n(ko-KR): add `invalid-dynamic-route.mdx`

---

src/content/docs/ko/reference/errors/redirect-with-no-location.mdx

- add `redirect-with-no-location.mdx`
- Closes #

i18n(ko-KR): add `redirect-with-no-location.mdx`

---

src/content/docs/ko/reference/errors/astro-glob-no-match.mdx

-  add `astro-glob-no-match.mdx`
- Closes #

i18n(ko-KR): add `astro-glob-no-match.mdx`

---

src/content/docs/ko/reference/errors/astro-glob-used-outside.mdx

- add `astro-glob-used-outside.mdx`
- Closes #

i18n(ko-KR): add `astro-glob-used-outside.mdx`

---

src/content/docs/ko/reference/errors/local-image-used-wrongly.mdx

- add `local-image-used-wrongly.mdx`
- Closes #

i18n(ko-KR): add `local-image-used-wrongly.mdx`

---

src/content/docs/ko/reference/errors/middleware-cant-be-loaded.mdx

- add `middleware-cant-be-loaded.mdx`
- Closes #

i18n(ko-KR): add `middleware-cant-be-loaded.mdx`

---

src/content/docs/ko/reference/errors/locals-not-an-object.mdx

- add `locals-not-an-object.mdx`
- Closes #

i18n(ko-KR): add `locals-not-an-object.mdx`

---

src/i18n/fr/ui.ts

Update french traskation for `ui.ts` with PR #5887

i18n(fr) Update `ui.ts`

---

src/content/docs/fr/guides/backend/turso.mdx

Update french translation of turso file with last PR #6162 #6319

i18n(fr) Update `turso.mdx`

---

src/content/docs/fr/guides/cms/ghost.mdx

Update french translation for ghost file with PR #6167

i18n(fr) Update `ghost.mdx`

---

src/content/docs/fr/guides/integrations-guide/markdoc.mdx
src/content/docs/fr/guides/integrations-guide/mdx.mdx
src/content/docs/fr/guides/integrations-guide/vercel.mdx

Update french translation for `markdoc.mdx` file with PR #6267

i18n(fr) Update `markdoc.mdx`, `mdx.mdx`, `vercel.mdx`

---

src/content/docs/fr/recipes/sharing-state.mdx

i18n(fr) `sharing-state.mdx` just for tracker

---

src/content/docs/fr/guides/deploy/zeabur.mdx

Add french translation for `zeabur.mdx`

i18n(fr) Add french translation for `zeabur.mdx`

---

src/content/docs/fr/recipes/bun.mdx

Add frech translation for Bun file

i18n(fr) Add `bun.mdx`

---

src/content/docs/fr/recipes/call-endpoints.mdx

Add french translation for call-endpoint file

i18n(fr) Add `call-endpoints.mdx`

---

src/content/docs/fr/recipes/dynamically-importing-images.mdx

Add french translation for dynamically-importing-images file.
I have a doubt on the L100 for `throw` translation.

i18n(fr) Add `dynamically-importing-images.mdx`

---

src/content/docs/fr/guides/integrations-guide/prefetch.mdx
src/content/docs/fr/guides/prefetch.mdx

Add french translation for prefetch file.

i18n(fr) Add `prefetch.mdx`

---

src/content/docs/es/core-concepts/astro-components.mdx
src/content/docs/es/core-concepts/astro-pages.mdx
src/content/docs/es/core-concepts/framework-components.mdx

Update `astro-components`, `astro-pages` & `framework-components` based on this commit e788cb13c48ac5b08556123f1cffb603d2d8e1ca

i18n(es): Update `astro-components`, `astro-pages` & `framework-components`

---

src/content/docs/es/core-concepts/layouts.mdx
src/content/docs/es/core-concepts/routing.mdx
src/content/docs/es/editor-setup.mdx

Update `layouts`, `routing` & `editor-setup` based on this commit e788cb13c48ac5b08556123f1cffb603d2d8e1ca

i18n(es): Update `layouts`, `routing` & `editor-setup`

---

src/content/docs/ko/reference/errors/cant-render-page.mdx

- add `cant-render-page.mdx`
- Closes #

i18n(ko-KR): add `cant-render-page.mdx`

---

src/content/docs/ko/reference/errors/locals-not-serializable.mdx

- add `locals-not-serializable.mdx`
- Closes #

i18n(ko-KR): add `locals-not-serializable.mdx`

---

src/content/docs/ko/reference/errors/markdown-content-schema-validation-error.mdx

-  add `markdown-content-schema-validation-error.mdx`
- Closes #

i18n(ko-KR): add `markdown-content-schema-validation-error.mdx`

---

src/content/docs/ko/reference/errors/missing-locale.mdx

- add `missing-locale.mdx`
- Closes #

i18n(ko-KR): add `missing-locale.mdx`

---

src/content/docs/ko/reference/errors/unhandled-rejection.mdx

- add `unhandled-rejection.mdx`
- Closes #

i18n(ko-KR): add `unhandled-rejection.mdx`

---

src/content/docs/es/recipes/dynamically-importing-images.mdx

Update dynamically-importing-images.mdx
(This is my first time contributing to this project, and I made this with love. Any feedback is welcome.)
- Closes #

i18n(es): Update `dynamically-importing-images.mdx` translation

---

src/content/docs/es/recipes/build-forms-api.mdx

Update `build-forms-api.mdx`  translation to es. 
It changed the order step in the recipe, and there was an additional step that was missing translation.
- Closes #

i18n(es): Update `build-forms-api.mdx` translation

---

src/content/docs/zh-cn/guides/cms/apostrophecms.mdx

Create apostrophecms.mdx
- #5969

i18n(zh-cn): Create apostrophecms.mdx

---

src/content/docs/zh-cn/guides/cms/ghost.mdx

i18n(zh-cn): Update ghost.mdx

---

src/content/docs/en/guides/integrations-guide/vercel.mdx
src/content/docs/ko/guides/deploy/deno.mdx
src/content/docs/ko/guides/deploy/vercel.mdx
src/content/docs/ko/guides/integrations-guide/vercel.mdx
src/content/docs/ko/reference/api-reference.mdx
src/content/docs/ko/reference/configuration-reference.mdx

- add `/deploy/vercel.mdx`, 
- add `/integrations-guide/vercel.mdx`, 
- edit link `/reference/configuration-reference.mdx`
- edit indent `/deploy/deno.mdx`
- edit indent `/reference/api-reference.mdx`
also edit
- `/en/guide/integrations-guide/vercel.mdx`, 
- Closes #

i18n(ko-KR): add `deploy/vercel.mdx` & `integrations-guide/vercel.mdx` , edit `deploy/deno.mdx` & `reference/api-reference.mdx`

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

Update cloudflare.mdx typo

---

src/content/docs/zh-cn/guides/markdown-content.mdx

Update markdown-content.mdx
- #6402

i18n(zh-cn): Update markdown-content.mdx

---

src/content/docs/zh-cn/core-concepts/astro-components.mdx

Update astro-components.mdx
- #6440

i18n(zh-cn): Update astro-components.mdx

---

src/content/docs/es/core-concepts/routing.mdx

Update `routing` based on this commit c5c074b15f9f89d0750462f22f77045aac6045c5

i18n(es): Update `routing`

---

src/content/docs/es/guides/integrations-guide/netlify.mdx

Updates `netlify` based on this commit based on these commits 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02, 77f7641deafd36f0f463c7f895d62da0082908aa & 8443f7c1e3af2c967e8c2d57182da30c3a34ac2b

i18n(es): Update `netlify`

---

src/content/docs/es/guides/integrations-guide/node.mdx

Updates `node` based on this commit 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02

i18n(es): Update `node`

---

src/content/docs/es/guides/integrations-guide/partytown.mdx

Updates `partytown` based on this commit 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02

i18n(es): Update `partytown`

---

src/content/docs/es/guides/integrations-guide/preact.mdx

Updates `preact` based on this commit 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02

i18n(es): Update `preact`

---

src/content/docs/es/guides/integrations-guide/react.mdx

Update `react` based on this commit 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02

i18n(es): Update `react`

---

src/content/docs/es/guides/migrate-to-astro/from-docusaurus.mdx

Update `from-docusaurus` based on this commit 1e7623f22db73548d78354335c8e2a966acf6c61

i18n(es): Update `from-docusaurus`

---

src/content/docs/es/reference/directives-reference.mdx
src/content/docs/es/reference/integrations-reference.mdx
src/content/docs/es/tutorials/add-content-collections.mdx

`directives-reference.mdx` https://github.com/withastro/docs/commit/5d46e8af4bd507449fd62950c8c625e388b367c9
`integrations-reference.mdx` https://github.com/withastro/docs/commit/f7dfaca362a26e9af529030f6ca52b6acb9d08e5
`add-content-collections.mdx` https://github.com/withastro/docs/commit/7b505c36266f4e5e394fc3e229369d3506ad2725

i18n(es): Update `directives-reference.mdx`, `integrations-reference.mdx` & `add-content-collections.mdx`

---

src/content/docs/fr/guides/cms/apostrophecms.mdx
src/content/docs/fr/guides/cms/contentful.mdx

Add `guides/cms/apostrophecms` and `guides/cms/contentful` in French language

i18n(fr): Add `guides/cms/apostrophecms` and `guides/cms/contentful` in French language

---

src/content/docs/en/guides/integrations-guide/sitemap.mdx

- switch "under considering" to "under consideration"
Just fixing a mini typo in the docs

docs(typo): fix flow

---

src/content/docs/es/guides/view-transitions.mdx

Fix typo in `view-transitions.mdx`

i18n(es): Fix typo in `view-transitions.mdx`

---

src/content/docs/zh-cn/tutorial/1-setup/3.mdx

i18n(zh-cn): Update 3.mdx

---

src/content/docs/ko/editor-setup.mdx

- update `editor-setup.mdx`
- #6532
- Closes #

i18n(ko-KR): update `editor-setup.mdx`

---

src/content/docs/ko/tutorial/1-setup/3.mdx

- update `tutorial/1-setup/3.mdx`
- #6522
- Closes #

i18n(ko-KR): update `tutorial/1-setup/3.mdx`

---

src/content/docs/ko/guides/view-transitions.mdx

- update `view-transitions.mdx`
- #6505
- Closes #

i18n(ko-KR): update `view-transitions.mdx`

---

src/content/docs/en/guides/backend/supabase.mdx

This PR marks the `supabase.mdx` file as `i18nReady`.

[i18nIgnore] Make `supabase.mdx` ready for translation

---

src/content/docs/ko/guides/migrate-to-astro/from-vuepress.mdx

- add `from-vuepress.mdx`
- Closes #

i18n(ko-KR): add `from-vuepress.mdx`

---

src/content/docs/zh-cn/recipes/streaming-improve-page-performance.mdx

Update streaming-improve-page-performance.mdx
- #6548

i18n(zh-cn): Update streaming-improve-page-performance.mdx

---

src/content/docs/ko/recipes/streaming-improve-page-performance.mdx

- update `streaming-improve-page-performance.mdx`
- #6548
- Closes #

i18n(ko-KR): update `streaming-improve-page-performance.mdx`

---

src/content/docs/es/guides/cms/sanity.mdx

`sanity.mdx` has been updated to be consistent with the English documentation.

i18n(es): update sanity.mdx

---

src/content/docs/es/guides/integrations-guide/sitemap.mdx

Updates `sitemap` based on these commits 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02, 342f1420e9b20d2a38beb45399129b54240e005d, da7664d70284ad39139549b818e9c14e2abf520f & 44a958c1f4acabab79ee3550b9117d4485955ea8
- Closes N/A

i18n(es): Update `sitemap`

---

src/content/docs/fr/core-concepts/astro-components.mdx
src/content/docs/fr/core-concepts/routing.mdx
src/content/docs/fr/editor-setup.mdx
src/content/docs/fr/guides/cms/ghost.mdx
src/content/docs/fr/guides/integrations-guide/vercel.mdx
src/content/docs/fr/guides/markdown-content.mdx
src/content/docs/fr/recipes/streaming-improve-page-performance.mdx
src/content/docs/fr/reference/directives-reference.mdx
src/content/docs/fr/reference/publish-to-npm.mdx
src/content/docs/fr/tutorial/1-setup/3.mdx
src/content/docs/fr/tutorials/add-content-collections.mdx

Update french translation for all outdated files

i18n(fr) Update french translation for all outdated file

---

src/content/docs/ko/guides/cms/contentful.mdx

- add `contentful.mdx`
- Closes #

i18n(ko-KR): add `contentful.mdx`

---

src/content/docs/ko/guides/cms/hygraph.mdx

- add `hygraph.mdx`
- Closes #

i18n(ko-KR): add `hygraph.mdx`

---

src/content/docs/ko/guides/cms/statamic.mdx

- add `statamic.mdx`
- Closes #

i18n(ko-KR): add `statamic.mdx`

---

src/content/docs/ko/guides/cms/wordpress.mdx

- add `wordpress.mdx`
- Closes #

i18n(ko-KR): add `wordpress.mdx`

---

src/content/docs/es/guides/integrations-guide/solid-js.mdx

Updates `solid-js` based on these commits 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02, 18a21132075abd00923325d38b6857076524d577, 29885a48868fe92c970cfc789167951c686f572b, 27cd3bb82e4543844703d456a89852d09b703390 & 58e1da0415dca383b7f528b47f24e5658ef50317
- Closes N/A 

i18n(es): Update `solid-js`

---

src/content/docs/es/guides/integrations-guide/svelte.mdx

Updates `svelte` based on this commit 9ecadb8fe8d7a309ca8d06ceae2dcaf578feaf02 
- Closes N/A

i18n(es): Update `svelte`

---

src/content/docs/es/guides/integrations-guide/vercel.mdx

- Content has been updated to be consistent with the English documentation.
- Added `PackageManagerTabs`, `Since` and `ReadMore` components.
- Fixed problem with highlighted elements.

i18n(es): update vercel.mdx

---

src/content/docs/es/guides/rss.mdx

Updates `rss` based on these commits a14c803b796dee20fa34a086159cc736d13acbd0 & 09a2136ebfef7a89d7e141a7fcfd9db6d4557b1a
- Closes # N/A

i18n(es): Update `rss`

---

src/content/docs/es/guides/server-side-rendering.mdx

Update `server-side-rendering` based on this commit c25d1472620d41a85631f22e38f5666cc5e85fa5
- Closes # N/A 

i18n(es): Update `server-side-rendering`

---

src/content/docs/zh-cn/guides/prefetch.mdx

i18n(zh-cn): Update prefetch.mdx

---

src/content/docs/zh-cn/tutorials/add-content-collections.mdx

Update add-content-collections.mdx
- #6569

i18n(zh-cn): Update add-content-collections.mdx

---

src/content/docs/ko/guides/cms/datocms.mdx

- add `datocms.mdx`
- Closes #

i18n(ko-KR): add `datocms.mdx`

---

src/content/docs/ko/guides/cms/tina-cms.mdx

- add `tina-cms.mdx`
- Closes #

i18n(ko-KR): add `tina-cms.mdx`

---

src/content/docs/ko/guides/cms/frontmatter-cms.mdx

- add `frontmatter-cms.mdx`
- Closes #

i18n(ko-KR): add `frontmatter-cms.mdx`

---

src/content/docs/ko/guides/cms/ghost.mdx

i18n(ko-KR): add `ghost.mdx`

---

src/content/docs/ko/guides/deploy/github.mdx

i18n(ko-KR): add `github.mdx`

---

src/content/docs/ko/guides/deploy/cloudflare.mdx

-  add `cloudflare.mdx`
- Closes #

i18n(ko-KR): add `cloudflare.mdx`

---

src/content/docs/es/guides/integrations-guide/sitemap.mdx

- Problems with highlighted parts have been solved.

i18n(es): update `sitemap.mdx`

---

src/content/docs/ko/guides/deploy/netlify.mdx
src/content/docs/ko/reference/configuration-reference.mdx

-  add `netlify.mdx`
- Closes #

i18n(ko-KR): add `netlify.mdx`

---

src/content/docs/ko/guides/cms/strapi.mdx

i18n(ko-KR): add `strapi.mdx`

---

src/content/docs/ko/guides/backend/google-firebase.mdx

- add `google-firebase.mdx`
- Closes #

i18n(ko-KR): add `google-firebase.mdx`

---

src/content/docs/ko/guides/cms/storyblok.mdx

- add `storyblok.mdx`
- Closes #

i18n(ko-KR): add `storyblok.mdx`

---

src/content/docs/ko/guides/cms/kontent-ai.mdx

- add `kontent-ai.mdx`
- Closes #

i18n(ko-KR): add `kontent-ai.mdx`

---

src/content/docs/zh-cn/tutorial/6-islands/1.mdx

i18n(zh-cn): Update 1.mdx

---

src/content/docs/zh-cn/reference/errors/cant-render-page.mdx
src/content/docs/zh-cn/reference/errors/get-static-paths-removed-rsshelper.mdx
src/content/docs/zh-cn/reference/errors/missing-locale.mdx
src/content/docs/zh-cn/reference/errors/unhandled-rejection.mdx

Update errors pages yaml title. errors pages yaml title should not be translated.
- Closes #

i18n(zh-cn): Update errors pages yaml title

---

src/content/docs/ko/guides/deploy/aws.mdx

i18n(ko-KR): add `aws.mdx`

---

src/content/docs/ko/guides/integrations-guide/partytown.mdx

- add `partytown.mdx`
- Closes #

i18n(ko-KR): add `partytown.mdx`

---

src/content/docs/ko/core-concepts/astro-pages.mdx
src/content/docs/ko/guides/integrations-guide/mdx.mdx

i18n(ko-KR): add `mdx.mdx`

---

src/content/docs/ko/guides/integrations-guide/sitemap.mdx

- add `sitemap.mdx`
- Closes #

i18n(ko-KR): add `sitemap.mdx`

---

src/content/docs/ko/guides/integrations-guide/tailwind.mdx

- add `tailwind.mdx`
- Closes #

i18n(ko-KR): add `tailwind.mdx`

---

src/content/docs/es/recipes.mdx
src/i18n/es/nav.ts

Updates `recipes.mdx` & `nav.ts` based on this commit 606493bd0e01daff617354f46f3933627f9340e0
- Closes # N/A

i18n(es): Update `recipes.mdx` & `nav.ts`

---

src/content/docs/es/guides/styling.mdx

Updates `styling` based on this commit e788cb13c48ac5b08556123f1cffb603d2d8e1ca
- Closes # N/A

i18n(es): Update `styling`

---

vercel.json

Redirects for all the changes made during the Talking and Doc'ing today on #6620

Add redirect for moved and renamed files

---

src/content/docs/es/guides/deploy/kinsta.mdx

Fixed the spacing problem in the tip blocks.

i18n(es): update kinsta.mdx

---

src/content/docs/en/guides/typescript.mdx

Fixes a typo with the Button import in the new ComponentProps docs

[typescript.mdx] Button import typo fix

---

src/content/docs/ko/guides/integrations-guide/sitemap.mdx

- update `sitemap.mdx`
- #6692
- Closes #

i18n(ko-KR): update `sitemap.mdx`

---

src/content/docs/ko/reference/error-reference.mdx
src/content/docs/ko/reference/errors/no-prerendered-routes-with-domains.mdx

…tes-with-domains.mdx`
- update `error-reference.mdx` 
- add `no-prerendered-routes-with-domains.mdx`
- #6727
- Closes #

i18n(ko-KR): update `error-reference.mdx` and add `no-prerendered-routes-with-domains.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/sitemap.mdx

- Update sitemap.mdx
- Closes #
- https://github.com/withastro/docs/pull/6692

i18n(zh-cn): Update sitemap.mdx

---

src/content/docs/zh-cn/community-resources/talks.mdx

- Update talks.mdx
- https://github.com/withastro/docs/pull/6728

i18n(zh-cn): Update talks.mdx

---

src/content/docs/es/community-resources/talks.mdx

i18n(es): Add `talks.mdx`

---

src/content/docs/es/reference/integrations-reference.mdx

Update `integrations-reference.mdx` #6733

i18n(es): Update integrations-reference.mdx

---

src/content/docs/fr/community-resources/talks.mdx
src/content/docs/fr/guides/integrations-guide/sitemap.mdx
src/content/docs/fr/guides/typescript.mdx
src/content/docs/fr/reference/error-reference.mdx
src/content/docs/fr/reference/errors/no-prerendered-routes-with-domains.mdx

Update and add (if necessary) last outated file with last PRs

i18n(fr) Update french translation for all last update files

---

src/content/docs/fr/guides/backend/appwriteio.mdx
src/content/docs/fr/guides/backend/supabase.mdx
src/content/docs/fr/guides/backend/tigris.mdx

Add french translation for `appwriteio.mdx` & `supabase.mdx` & `tigris.mdx`

i18n(fr) Add french transltion for Backend file

---

src/content/docs/fr/guides/cms/builderio.mdx
src/content/docs/fr/guides/cms/caisy.mdx
src/content/docs/fr/guides/cms/cloudcannon.mdx
src/content/docs/fr/guides/cms/crystallize.mdx
src/content/docs/fr/guides/cms/decap-cms.mdx
src/content/docs/fr/guides/cms/directus.mdx
src/content/docs/fr/guides/cms/keystatic.mdx
src/content/docs/fr/guides/cms/keystonejs.mdx
src/content/docs/fr/guides/cms/microcms.mdx
src/content/docs/fr/guides/cms/payload.mdx
src/content/docs/fr/guides/cms/preprcms.mdx
src/content/docs/fr/guides/cms/prismic.mdx
src/content/docs/fr/guides/cms/sanity.mdx
src/content/docs/fr/guides/cms/spinal.mdx

Add french translation for CMS files.

i18n(fr) Add all file in CMS folder

---

src/content/docs/en/reference/api-reference.mdx

Fixes a typo spotted in `api-reference`
- Closes # N/A
- Suggested label: documentation

fix: typo in `api-reference`

---

src/content/docs/ko/guides/migrate-to-astro/from-gatsby.mdx

- update `from-gatsby.mdx`
- #6769
- Closes #

i18n(ko-KR): update `from-gatsby.mdx`

---

src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx

Update from-gatsby.mdx
- #6769

i18n(zh-cn): Update from-gatsby.mdx

---

src/content/docs/zh-cn/basics/astro-components.mdx

Update astro-components.mdx
- #6440

i18n(zh-cn): Update `astro-components.mdx`

---

src/content/docs/fr/basics/astro-components.mdx

i18n(fr) Update french translation for `astro-components.mdx`

---

src/content/docs/fr/basics/rendering-modes.mdx
src/content/docs/fr/guides/server-side-rendering.mdx

Add french translation for `server-side-rendering.mdx`

i18n(fr) Add french translation for `server-side-rendering.mdx`

---

src/content/docs/en/community-resources/talks.mdx
src/content/docs/fr/community-resources/talks.mdx
src/content/docs/ko/community-resources/talks.mdx
src/content/docs/zh-cn/community-resources/talks.mdx

Ryan's last name has been corrected in all currently available languages.

[i18nIgnore] Corrected Ryan's name in all current languages

---

.github/ISSUE_TEMPLATE/BUGS.yml
.github/ISSUE_TEMPLATE/CONTENT.yml
.github/ISSUE_TEMPLATE/REQUEST.yml

Fixes #6550.
I also added it to another, similar template.

chore: add astro.new to relevant issue templates

---

src/content/docs/en/guides/cms/storyblok.mdx

Update from below:
```js
import StoryblokComponent from '@storyblok/astro/components/StoryblokComponent.astro';
```
to this:
```js
import StoryblokComponent from "@storyblok/astro/StoryblokComponent.astro";
```
- Suggested label: docs fix

Update StoryblokComponent import source path on tutorial

---

src/content/docs/en/guides/integrations-guide/tailwind.mdx

- add missing import to example to prevent errors when copying code snippet
- Closes #
Yes?!

fix: add missing import to example

---

src/content/docs/pt-br/community-resources/talks.mdx

Translates the page Tallks from the new community resource section to pt-br.
- Closes #

i18n(pt-br): translate communtiy-resources/talks

---

src/content/docs/ko/guides/cms/payload.mdx

- add `payload.mdx`
- Closes #

i18n(ko-KR): add `payload.mdx`

---

src/content/docs/ko/guides/cms/keystatic.mdx

- add `keystatic.mdx`
- Closes #

i18n(ko-KR): add `keystatic.mdx`

---

src/content/docs/ko/guides/cms/builderio.mdx

- add `builderio.mdx`
- Closes #

i18n(ko-KR): add `builderio.mdx`

---

src/content/docs/fr/recipes/i18n.mdx

Add `recipes/i18n` in French language
- Suggested label: I18n

i18n(fr): Add `recipes/i18n` in French language

---

src/content/docs/fr/guides/view-transitions.mdx
src/content/docs/fr/tutorials/add-view-transitions.mdx
src/i18n/fr/README.md

Add `guides/view-transitions` in French language

i18n(fr): Add `guides/view-transitions` in French language

---

src/content/docs/es/guides/integrations-guide/tailwind.mdx

Imports have been updated. #6831

i18n(es): update tailwind.mdx

---

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx

Adds another blog post to the Community Resources section: Migrating from Gatsby to Astro. (Yes, I intentionally added this at the TOP of the list because it's recent, referring to v4)
Also fixes the link in the aside that was hard-coded from before we switched to content collections!

[from-gatsby.mdx] Adds community resource and fixes link

---

src/content/docs/ko/community-resources/talks.mdx

- update `talk.mdx`
- #6814
- Closes #

i18n(ko-KR): update `talk.mdx`

---

src/content/docs/ko/guides/cms/storyblok.mdx

- update `storyblok.mdx`
- #6815
- Closes #

i18n(ko-KR): update `storyblok.mdx`

---

src/content/docs/ko/guides/cms/strapi.mdx

- update `strapi.mdx`
- #6762
- Closes #

i18n(ko-KR): update `strapi.mdx`

---

src/content/docs/ko/guides/content-collections.mdx

- update `content-collections.mdx`
- #6718
- Closes #

i18n(ko-KR): update `content-collections.mdx`

---

src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx

The new community resources link has been added and the problem with the edit link has been fixed. #6833

i18n(es): Add blog article link for migrating from Gatsby to Astro

---

src/content/docs/es/guides/cms/strapi.mdx

- Updated `strapi.mdx` 
- #6762

i18n(es): update strapi.mdx

---

src/content/docs/en/reference/dev-toolbar-app-reference.mdx
src/content/docs/es/reference/dev-toolbar-app-reference.mdx
src/content/docs/ko/reference/dev-toolbar-app-reference.mdx
src/content/docs/zh-cn/reference/dev-toolbar-app-reference.mdx

Remov `file-search` as it was duplicated in the same content.

[i18nIgnore] Remove duplicate content

---

src/content/docs/en/guides/fonts.mdx

Updates the Tailwind snippet in our fonts guide to `.mjs`.
- Closes #6880

Update tailwind fonts snippet

---

src/content/docs/zh-cn/guides/content-collections.mdx

- Update content-collections.mdx
- https://github.com/withastro/docs/pull/6718

i18n(zh-cn): Update content-collections.mdx

---

src/content/docs/zh-cn/guides/cms/storyblok.mdx

- Update storyblok.mdx
- https://github.com/withastro/docs/pull/6815

i18n(zh-cn): Update storyblok.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx

Update and add missing content to `guides/integrations-guide/tailwind.mdx`
Upstream PRs:
- #5974
- #6831
- Closes #

i18n(zh-cn): Update `guides/integrations-guide/tailwind.mdx`

---

src/content/docs/zh-cn/guides/deploy/aws.mdx

Update `guides/deploy/aws.mdx`
Upstream PR: #6533
- Closes #

i18n(zh-cn): Update `guides/deploy/aws.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx

Update `guides/integrations-guide/markdoc.mdx`
Upstream PRs:
- #6431
- #6829
- Closes #

i18n(zh-cn): Update `guides/integrations-guide/markdoc.mdx`

---

src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx

Update `guides/migrate-to-astro/from-gatsby.mdx`
Upstream PR:
- #6833
- Closes #

i18n(zh-cn): Update `guides/migrate-to-astro/from-gatsby.mdx`

---

src/content/docs/zh-cn/guides/fonts.mdx

i18n(zh-cn): Update `fonts.mdx`

---

src/content/docs/zh-cn/guides/deploy/deno.mdx

i18n(zh-cn): Update `deno.mdx`

---

src/content/docs/zh-cn/reference/errors/failed-to-fetch-remote-image-dimensions.mdx

Create `failed-to-fetch-remote-image-dimensions.mdx`
- #6896

i18n(zh-cn): Create `failed-to-fetch-remote-image-dimensions.mdx`

---

src/content/docs/zh-cn/guides/cms/strapi.mdx

- Update strapi.mdx
- https://github.com/withastro/docs/pull/6762

i18n(zh-cn): Update strapi.mdx

---

src/content/docs/zh-tw/getting-started.mdx

- Updates `src/content/docs/zh-tw/getting-started.mdx`
- ~~Closes #~~

i18n(zh-tw): update `getting-started.mdx` translation

---

src/content/docs/en/guides/backend/xata.mdx
src/content/docs/es/guides/backend/xata.mdx
src/content/docs/fr/guides/backend/xata.mdx
src/content/docs/it/guides/backend/xata.mdx
src/content/docs/ja/guides/backend/xata.mdx
src/content/docs/ko/guides/backend/xata.mdx
src/content/docs/zh-cn/guides/backend/xata.mdx

- Xata renamed their Astro starter to <https://github.com/xataio/examples/tree/main/apps/getting-started-astro>
- this PR updates old Xata Astro Starter link

[i18nIgnore] update Xata Astro Starter Link

---

src/content/docs/pt-br/tutorial/3-components/3.mdx
src/content/docs/pt-br/tutorial/3-components/4.mdx

Update tutorial 3-components translation to pt-br
- Closes #

i18n(pt-br): update tutorial 3-components

---

src/content/docs/pt-br/tutorial/2-pages/1.mdx

Update tutorial 2-pages translation to pt-br
- Closes #

i18n(pt-br): update tutorial 2-pages

---

src/content/docs/pt-br/tutorial/4-layouts/2.mdx

Update tutorial 4-layouts translation to pt-br
- Closes #

i18n(pt-br): update tutorial 4-layouts

---

src/content/docs/pt-br/tutorial/6-islands/1.mdx
src/content/docs/pt-br/tutorial/6-islands/2.mdx

Update tutorial 6-islands translation to pt-br
- Closes #

i18n(pt-br): update tutorial 6-islands

---

src/content/docs/es/reference/errors/missing-image-dimension.mdx

Updates `missing-image-dimension`
- Closes # N/A

i18n(es): update `missing-image-dimension`

---

src/content/docs/es/guides/prefetch.mdx

Updates `prefetch`
- Closes # N/A

i18n(es): update `prefetch`

---

src/content/docs/zh-cn/guides/fonts.mdx
src/content/docs/zh-cn/guides/prefetch.mdx

i18n(zh-cn): Update `prefetch.mdx`

---

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx

- Add another guide about migrating from Gatsby to Astro
- Translating a single sentence
- Closes #

Add post with migration from Gatsby to Astro

---

src/content/docs/es/guides/migrate-to-astro/from-gatsby.mdx

- Adding spanish translation to latest migration link added
- Missing translation for a sentence
- Closes #

i18n(es): Link to another Gatsby migration to Astro and missing translation

---

src/content/docs/es/guides/typescript.mdx

The file has been updated based on the following pull request #6950

i18n(es): update typescript.mdx

---

src/content/docs/pt-br/guides/fonts.mdx

i18n(pt-br): Update fonts.mdx translation
- Closes #

i18n(pt-br): Update fonts.mdx translation

---

src/i18n/pt-br/nav.ts

i18n(pt-br): update nav.ts
- Closes #

i18n(pt-br): update nav.ts

---

src/content/docs/en/guides/integrations-guide.mdx

This pull request adds missing semicolons in code examples to make them consistent with the rest of the docs.

Add missing semicolons in code examples

---

src/content/docs/en/guides/deploy/github.mdx

Updating the code sample in the deployment guide for [GitHub Pages](https://docs.astro.build/en/guides/deploy/github/) to reflect the most up-to-date guidance.

Update GitHub Actions deploy guide

---

src/content/docs/zh-cn/tutorial/4-layouts/2.mdx
src/content/docs/zh-cn/tutorial/4-layouts/3.mdx
src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx

Fix format pubDate in tutorials
Upstream PR: #6900
- Closes #

i18n(zh-cn): Fix format pubDate in tutorials

---

src/content/docs/zh-cn/guides/integrations-guide.mdx

Update `guides/integrations-guide.mdx`
Upstream PR: #6973
- Closes #

i18n(zh-cn): Update `guides/integrations-guide.mdx`

---

src/content/docs/zh-cn/guides/markdown-content.mdx

Update `guides/markdown-content.mdx`
Upstream PR: #6960
- Closes #

i18n(zh-cn): Update `guides/markdown-content.mdx`

---

src/content/docs/en/community-resources/talks.mdx

- adds [Ema's SSR Talk](https://portal.gitnation.org/contents/you-dont-know-how-to-ssr) from DevOps.Js Conf 2024
- Suggested label: `community resource`

add Ema's DevOps.Js Conf 2024 talk

---

src/content/docs/zh-cn/recipes/captcha.mdx

i18n(zh-cn): Update captcha.mdx

---

src/content/docs/zh-cn/guides/framework-components.mdx

Update framework-components.mdx
- #7034

i18n(zh-cn): Update framework-components.mdx

---

src/content/docs/zh-cn/guides/integrations-guide.mdx

Update integrations-guide.mdx
- #7033

i18n(zh-cn): Update integrations-guide.mdx

---

src/content/docs/es/guides/integrations-guide.mdx

Updated based on the following pull request #7033

i18n(es): Update integrations-guide.mdx

---

src/content/docs/es/recipes/captcha.mdx

Updated based on the following pull request #6860

i18n(es): update captcha.mdx

---

src/content/docs/es/community-resources/talks.mdx

Description (required)
Update talks.mdx
Related issues & labels (optional)
- #7026

i18n(es): Update talks.mdx

---

src/content/docs/ja/guides/prefetch.mdx

- Update prefetch.mdx.
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/prefetch.mdx?since=2024-02-06T15:59:50.000Z)
- https://github.com/withastro/docs/pull/6939

i18n(ja): Update prefetch.mdx

---

src/content/docs/ja/guides/styling.mdx

- i18n(ja): Update styling.mdx.
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/styling.mdx?since=2023-10-14T11:59:46.000Z)
- https://github.com/withastro/docs/pull/5765
- https://github.com/withastro/docs/pull/6267

i18n(ja): Update styling.mdx

---

src/content/docs/ja/guides/upgrade-to/v2.mdx

- Update v2.mdx.
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/upgrade-to/v2.mdx?since=2023-06-06T17:30:53.000Z)
- https://github.com/withastro/docs/pull/3353
- https://github.com/withastro/docs/pull/5215

i18n(ja): Update v2.mdx

---

src/content/docs/zh-cn/guides/fonts.mdx

i18n(zh-cn): Update fonts.mdx

---

src/content/docs/zh-cn/guides/styling.mdx

i18n(zh-cn): Update styling.mdx

---

src/content/docs/zh-cn/guides/cms/preprcms.mdx

i18n(zh-cn): Update preprcms.mdx

---

src/content/docs/zh-cn/guides/cms/keystatic.mdx

Update `guides/cms/keystatic.mdx`
Upstream PR: #7067
- Closes #

i18n(zh-cn): Update `guides/cms/keystatic.mdx`

---

src/content/docs/es/guides/cms/keystatic.mdx

Updates `keystatic` 
- Closes # N/A

i18n(es): update `keystatic`

---

src/content/docs/es/guides/cms/preprcms.mdx

Updates `preprcms`
- Closes # N/A

i18n(es): update `preprcms`

---

src/content/docs/es/guides/cms/strapi.mdx

Updates `strapi`
- Closes # N/A

i18n(es): update `strapi`

---

src/content/docs/es/guides/fonts.mdx

Updates `fonts`
- Closes # N/A

i18n(es): update `fonts`

---

src/content/docs/es/guides/framework-components.mdx

Updates `framework-components`
- Closes # N/A

i18n(es): updates `framework-components`

---

src/content/docs/es/reference/errors/middleware-cant-be-loaded.mdx

Updates `middleware-cant-be-loaded`
- Closes # N/A

i18n(es): update `middleware-cant-be-lodaded`

---

src/content/docs/es/guides/ecommerce.mdx

Translate `ecommerce`
- Closes #N/A

i18n(es): translate `ecommerce`

---

src/content/docs/en/guides/ecommerce.mdx

- Fix typos.
- Format code for consistency.
- Use `"` for wrapping html attribute values.
- Remove unnecessary line breaks.
- etc.

Fix typos and format code in ecommerce.mdx

---

src/content/docs/ru/community-resources/content.mdx

This PR updates the links in  `content.mdx` file, addressing outdated content flagged on the Translation Tracker.
Related:
- #7110

i18n(ru): Update `content.mdx`

---

src/content/docs/fr/guides/styling.mdx

I definitely want my hacktoberfest t-shirt for this one
- Closes #

i18n(fr): Fix vite import link missing a parenthesis in styling.mdx [i18nIgnore]

---

src/content/docs/es/guides/deploy/google-cloud.mdx

i18n(es): update google-cloud.mdx

---

src/content/docs/es/guides/ecommerce.mdx

i18n(es): update ecommerce.mdx

---

src/content/docs/es/guides/rss.mdx

i18n(es): update rss.mdx

---

src/content/docs/es/community-resources/content.mdx

i18n(es): Update content.mdx

---

src/content/docs/es/reference/directives-reference.mdx

The `set:html` section has been updated

i18n(es): Update directives-reference.mdx

---

src/content/docs/en/guides/ecommerce.mdx

- fix typo in `ecommerce.mdx`
- Closes #

fix: typo in `ecommerce.mdx`

---

src/content/docs/en/guides/fonts.mdx

Corrected the numbering to be sequential (1, 2, etc. ) for improved readability and ease of future maintenance.

Fix incorrect list numbering in `fonts.mdx`

---

src/content/docs/ko/guides/markdown-content.mdx

- update `markdown-content.mdx`
- #6960
- Closes #

i18n(ko-KR): update `markdown-content.mdx`

---

src/content/docs/ko/guides/middleware.mdx

- update `middleware.mdx`
- #7045
- Closes #

i18n(ko-KR): update `middleware.mdx`

---

src/content/docs/ko/guides/prefetch.mdx

- update `prefetch.mdx`
- #6939
- Closes #

i18n(ko-KR): update `prefetch.mdx`

---

src/content/docs/ko/guides/rss.mdx

- update `rss.mdx`
- #7108
- Closes #

i18n(ko-KR): update `rss.mdx`

---

src/content/docs/ko/guides/styling.mdx

-  update `styling.mdx`
- #7051 
- #7126
- Closes #

i18n(ko-KR): update `styling.mdx`

---

src/content/docs/ko/guides/fonts.mdx

- update `fonts.mdx`
- #6883 
- #7011 
- #7163
- Closes #

i18n(ko-KR): update `fonts.mdx`

---

src/content/docs/ko/guides/images.mdx
src/content/docs/ko/reference/errors/missing-image-dimension.mdx

- update `images.mdx`
- #6797 
- #6959 
- #7141
- Closes #

i18n(ko-KR): update `images.mdx`

---

src/content/docs/zh-cn/reference/api-reference.mdx

Update `reference/api-reference.mdx` code example
Upstream PR: #7148
- Closes #

i18n(zh-cn): Update `reference/api-reference.mdx` code example

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

https://github.com/withastro/adapters/pull/179 introduces [Service bindings](https://developers.cloudflare.com/workers/configuration/bindings/about-service-bindings/) to the `@astrojs/cloudflare` adapter. This PR adds a simple example about the new type `service` to both the runtime example and the `wrangler.toml`.
`F0rrce`

Add docs for Cloudflare service bindings

---

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx

Update `cloudflare.mdx`
- #7143

i18n(zh-cn): Update `cloudflare.mdx`

---

src/content/docs/ru/tutorial/2-pages/3.mdx

This PR updates the Russian translation of the ` /tutorial/2-pages/3.mdx` page, addressing outdated content identified by the Translation Tracker.

i18n(ru): Update `/tutorial/2-pages/3.mdx` translation

---

src/content/docs/zh-cn/tutorial/4-layouts/3.mdx
src/content/docs/zh-cn/tutorial/5-astro-api/1.mdx

update some translation to make it more fluent.
- Closes #

i18n(zh-cn): Update `4-layouts/3.mdx` and `5-astro-api/1.mdx` in `tutorial`

---

src/content/docs/ko/guides/cms/keystatic.mdx

- update `keystatic.mdx`
- #7067
- Closes #

i18n(ko-KR): update `keystatic.mdx`

---

src/content/docs/ko/guides/deploy/google-cloud.mdx

- update `google-cloud.mdx`
- #7118
- Closes #

i18n(ko-KR): update `google-cloud.mdx`

---

src/content/docs/ko/guides/integrations-guide/cloudflare.mdx

- update `cloudflare.mdx`
- #7143
- Closes #

i18n(ko-KR): update `cloudflare.mdx`

---

src/content/docs/ko/guides/integrations-guide/lit.mdx

- update `lit.mdx`
- #6859
- Closes #

i18n(ko-KR): update `lit.mdx`

---

src/content/docs/ko/guides/integrations-guide/vercel.mdx

- update `vercel.mdx`
- #6914
- Closes #

i18n(ko-KR): update `vercel.mdx`

---

src/content/docs/zh-tw/editor-setup.mdx

i18n(zh-tw): Update editor-setup.mdx

---

src/content/docs/ko/tutorial/1-setup/2.mdx
src/content/docs/ko/tutorial/4-layouts/2.mdx
src/content/docs/ko/tutorial/4-layouts/3.mdx
src/content/docs/ko/tutorial/5-astro-api/3.mdx

- update `tutorial/`
- update `1-setup/2.mdx`
- update `4-layout/2.mdx`
- update `4-layout/3.mdx`
- update `5-astro-api/3.mdx`
- #7159
- #6900
- Closes #

i18n(ko-KR): update `tutorial/`

---

src/content/docs/es/guides/authentication.mdx

i18n(es): update authentication.mdx

---

src/content/docs/ko/guides/authentication.mdx

- update `authentication.mdx`
- #7147
- Closes #

i18n(ko-KR): update `authentication.mdx`

---

src/content/docs/es/guides/images.mdx

Content updated to be in sync with English documentation

i18n(es): update images.mdx

---

src/content/docs/es/guides/integrations-guide/lit.mdx

Updated `lit.mdx` according to english translation.

i18n(es): Update lit.mdx

---

src/content/docs/en/guides/astro-db.mdx

Typo in page description, affecting OG image

Update astro-db.mdx description

---

src/util/isSubPage.ts

Fixes a highlighting bug in the docs sidebar
|---|---|
| <img width="274" alt="image" src="https://github.com/withastro/docs/assets/357379/a3808937-f1c1-496d-9213-0d6513c41b27"> | <img width="276" alt="image" src="https://github.com/withastro/docs/assets/357379/03e351a7-e4cf-404e-9cf3-06109b8942ab"> |

Fix sidebar highlighting for studio recipe

---

src/content/docs/en/guides/astro-db.mdx

Users will receive an error running `astro link` before logging in. This ensures users are aware of `astro login` before trying to create a new project from the CLI.
- Closes #

edit: mention `astro login` on DB create project instructions

---

src/content/docs/zh-cn/guides/cms/strapi.mdx

i18n(zh-cn): Update `strapi.mdx`

---

src/content/docs/zh-cn/reference/configuration-reference.mdx

Update `reference/configuration-reference.mdx`
Upstream PR: #7364
- Closes #

i18n(zh-cn): Update `reference/configuration-reference.mdx`

---

src/content/docs/zh-cn/guides/cms/ghost.mdx

i18n(zh-cn): Update `ghost.mdx`

---

src/content/docs/zh-cn/guides/astro-db.mdx

Update `astro-db.mdx`
- #7377 
- #7378

i18n(zh-cn): Update `astro-db.mdx`

---

src/content/docs/en/community-resources/content.mdx

Updates [Community Educational Content](https://docs.astro.build/en/community-resources/content/#recipes-and-guides) page to include an Astro DB section and a link to my article on [how to create a guestbook](https://ryantrimble.com/blog/creating-a-guestbook-with-astro-db/) using Astro DB.
This was suggested by @sarah11918 on [Mastodon](https://elk.zone/mastodon.social/@sarah11918/112106675024765805) 
- Closes #
Yes
If you are a member of the Astro Discord, please add your username in the description so we can welcome you there!
mrtrimble
https://astro.build/chat

update: community resources -  adds astro db section, includes link

---

src/content/docs/zh-cn/guides/content-collections.mdx

The Chinese translation of this document mentions two 'astro/tsconfigs/strictest'.

i18n(zh-cn): fix typo in the Chinese docs.

---

src/content/docs/zh-cn/community-resources/content.mdx

i18n(zh-cn): Update `content.mdx`

---

src/content/docs/ko/community-resources/content.mdx

- update `content.mdx`
- #7449
- Closes #

i18n(ko-KR): update `content.mdx`

---

src/content/docs/zh-cn/guides/deploy/cloudflare.mdx

Update `cloudflare.mdx`
- #7414

i18n(zh-cn): Update `deploy/cloudflare.mdx`

---

src/content/docs/zh-tw/contribute.mdx

- Translates `src/content/docs/en/contribute.mdx` into Traditional Chinese
- Adds `src/content/docs/zh-tw/contribute.mdx`
- ~~Closes #~~

i18n(zh-tw): add `contribute.mdx` translation

---

src/content/docs/en/community-resources/talks.mdx

- adds fred's latest podcast about astro:db on [ShopTalk](<https://shoptalkshow.com/607/>)
- Suggested label: community-resource

add fred's podcast about `astro:db`

---

src/content/docs/zh-cn/community-resources/talks.mdx

i18n(zh-cn): Update `talks.mdx`

---

src/content/docs/zh-cn/guides/authentication.mdx

Update `authentication.mdx`
- #7465

i18n(zh-cn): Update `authentication.mdx`

---

src/content/docs/zh-cn/tutorials/add-view-transitions.mdx

an awkward expression
the sentence “中网站” is in a wrong order, change it into “网站中”
- Suggested label:  i18n

i18n(zh-cn): Update add-view-transitions.mdx

---

src/content/docs/ko/tutorials/add-view-transitions.mdx

- update `add-view-transitions.mdx`
- #7468
- Closes #

i18n(ko-KR): update `add-view-transitions.mdx`

---

src/content/docs/ko/tutorials/add-content-collections.mdx

- update `add-content-collections.mdx`
- #7459
- Closes #

i18n(ko-KR): update `add-content-collections.mdx`

---

src/content/docs/en/reference/publish-to-npm.mdx

Updates the Discord channel name
- Suggested label: low effort

fix: update discord channel name

---

src/content/docs/en/community-resources/talks.mdx

- add fuzzybear's talk from [EdinburghJS - Mar 2024 Meetup](https://www.youtube.com/watch?v=G6S2RsDo1fI)
- Suggested label: community-resource
> The link text is trimmed as opposed to the Youtube title (I hope Daniel will let me off the hook this time 🙏)

add fuzzybear's talk

---

src/content/docs/zh-cn/reference/publish-to-npm.mdx

Update `publish-to-npm.mdx`
- #7497

i18n(zh-cn): Update `publish-to-npm.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx

i18n(zh-cn): Update `netlify.mdx`

---

src/content/docs/zh-cn/guides/cms/contentful.mdx

- i18n(zh-cn): fix typo in contentful.mdx
- Closes #

i18n(zh-cn): fix typo in contentful.mdx

---

src/content/docs/zh-cn/guides/backend/google-firebase.mdx

fix typo in  google-firebase.mdx 
- Closes #

i18n(zh-cn): fix typo in  google-firebase.mdx

---

src/content/docs/zh-cn/guides/deploy/github.mdx

i18n(zh-cn): Update `github.mdx`

---

src/content/docs/en/community-resources/content.mdx

Adds a new Recipe "How to build a View Counter with Astro DB" to the community recipes page.

add new Astro DB community recipe

---

src/content/docs/fr/guides/cms/strapi.mdx

Update `guides/cms/strapi.mdx` from https://github.com/withastro/docs/commit/c569ada482bfd28a4ad6a40d0b99ec4b95223fb6

i18n(fr): Update `guides/cms/strapi.mdx`

---

src/content/docs/fr/guides/cms/ghost.mdx

Update `guides/cms/ghost.mdx` from https://github.com/withastro/docs/commit/4f59bbb61712a18c8e240cbbb7af1fa08d1a6b09

i18n(fr): Update `guides/cms/ghost.mdx`

---

src/content/docs/fr/guides/authentication.mdx

Update `guides/authentication.mdx` from https://github.com/withastro/docs/commit/3cf557da77f08350bfe3f75e933be17929e244e1

i18n(fr): Update `guides/authentication.mdx`

---

src/content/docs/fr/guides/deploy/github.mdx

Update `guides/deploy/github` from https://github.com/withastro/docs/commit/76c97f7fa29839ac31a77aae4180f691e5fe4077

i18n(fr): Update `guides/deploy/github`

---

src/content/docs/fr/guides/integrations-guide/netlify.mdx

Update `guides/integrations-guide/netlify` from https://github.com/withastro/docs/commit/88585762e74a691ecdc2186267ff8e05b583eaed

i18n(fr): Update `guides/integrations-guide/netlify`

---

src/content/docs/fr/guides/server-side-rendering.mdx

Update `guides/server-side-rendering` from https://github.com/withastro/docs/commit/d87ec754a6e0e6d31bc13aedfd711eaef5600bfa

i18n(fr): Update `guides/server-side-rendering`

---

src/content/docs/fr/install/auto.mdx

Update `install/auto` from https://github.com/withastro/docs/commit/22893542921126333cd1c125c91626dfb999bdb4

i18n(fr): Update `install/auto`

---

src/content/docs/zh-cn/guides/server-side-rendering.mdx
src/content/docs/zh-cn/reference/integrations-reference.mdx

…erence.mdx`
Update `server-side-rendering.mdx` and `integrations-reference.mdx`
- #7498

i18n(zh-cn): Update `server-side-rendering.mdx` and `integrations-reference.mdx`

---

src/content/docs/zh-cn/guides/troubleshooting.mdx

Update `troubleshooting.mdx`
- #7603

i18n(zh-cn): Update `troubleshooting.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/db.mdx

i18n(zh-cn): Update `db.mdx`

---

src/content/docs/ko/guides/server-side-rendering.mdx

- update `server-side-rendering.mdx`
- #7498
- Closes #

i18n(ko-KR): update `server-side-rendering.mdx`

---

src/content/docs/zh-cn/integrations/integrations.mdx

Update `integrations.mdx`
- #7628

i18n(zh-cn): Update `integrations.mdx`

---

src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx

i18n(zh-cn): Update `vercel.mdx`

---

src/content/docs/zh-cn/guides/aliases.mdx

i18n(zh-cn): Update `aliases.mdx`

---

src/content/docs/zh-cn/basics/astro-syntax.mdx

i18n(zh-cn): Update `Hello` translation in `astro-syntax.mdx`

---

src/content/docs/en/guides/deploy.mdx

Add steps component in deploy.mdx
- Closes #

Add steps component in deploy.mdx

---

src/content/docs/en/guides/prefetch.mdx

Add steps component in prefetch.mdx
- Closes #

Add steps component in prefetch.mdx

---

src/content/docs/en/guides/dev-toolbar.mdx

Update link in `dev-toolbar.mdx`
- Closes #

Update link in `dev-toolbar.mdx`

---

src/content/docs/en/guides/view-transitions.mdx

Add steps component in view-transitions.mdx

Add steps component in view-transitions.mdx

---

src/content/docs/zh-cn/guides/deploy.mdx

i18n(zh-cn): Update `deploy.mdx`

---

src/content/docs/ko/guides/deploy.mdx

- update `deploy.mdx`
- #7649
- Closes #

i18n(ko-KR): update `deploy.mdx`

---

src/content/docs/zh-cn/guides/view-transitions.mdx

Update `view-transitions.mdx`
- #7647

i18n(zh-cn): Update `view-transitions.mdx`

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

- fix typo in `integrations-guide/cloudflare.mdx`
- Closes #

docs: fix typo in `integrations-guide/cloudflare.mdx`

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

- as discussed on Discord
- Closes #

improves section about routes

---

src/content/docs/en/guides/integrations-guide.mdx

Add Steps component to integrations-guide.mdx
- Closes #

Add Steps component to integrations-guide.mdx

---

src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx

Change 'NextLink' to 'NuxtLink' 
- Closes #

Change 'NextLink' to 'NuxtLink'

---

src/content/docs/zh-cn/guides/dev-toolbar.mdx

Update `dev-toolbar.mdx`
- #7646

i18n(zh-cn): Update `dev-toolbar.mdx`

---

src/content/docs/fr/guides/integrations-guide/vercel.mdx

Update`guides/integrations-guide/vercel` from https://github.com/withastro/docs/commit/8c0a62ab13095370729a18c6262ed0b8dd5207af
- Closes #

i18n(fr): Update`guides/integrations-guide/vercel`

---

src/content/docs/ko/guides/aliases.mdx

- update `aliases.mdx`
- #6986
- Closes #

i18n(ko-KR): update `aliases.mdx`

---

src/content/docs/ko/guides/deploy/cloudflare.mdx

- update `deploy/cloudflare.mdx`
- #7592
- Closes #

i18n(ko-KR): update `deploy/cloudflare.mdx`

---

src/content/docs/ko/integrations/integrations.mdx

- update `integrations.mdx`
- #7628
- Closes #

i18n(ko-KR): update `integrations.mdx`

---

src/content/docs/zh-cn/guides/styling.mdx

i18n(zh-cn): Update `styling.mdx`

---

src/content/docs/en/guides/integrations-guide/tailwind.mdx

Two out of three of the given examples are a bit outdated so I added my open source theme for a state of the art tailwind starter integration theme.
discord: nicdun

Added up to date theme example for simple tailwind integration.

---

src/content/docs/ja/tutorial/4-layouts/1.mdx
src/content/docs/ja/tutorial/4-layouts/2.mdx
src/content/docs/ja/tutorial/4-layouts/3.mdx
src/content/docs/ja/tutorial/4-layouts/index.mdx

- Update tutorial/4-layouts
- diff
- 1.mdx
- https://github.com/withastro/docs/pull/7496
- 2.mdx
- https://github.com/withastro/docs/pull/6900
- https://github.com/withastro/docs/pull/7496
- 3.mdx
- https://github.com/withastro/docs/pull/6900
- https://github.com/withastro/docs/pull/7496
- index.mdx
- https://github.com/withastro/docs/pull/4753
- Closes #

i18n(ja): Update tutorial/4-layouts

---

src/content/docs/ja/tutorial/3-components/1.mdx
src/content/docs/ja/tutorial/3-components/2.mdx
src/content/docs/ja/tutorial/3-components/3.mdx
src/content/docs/ja/tutorial/3-components/4.mdx
src/content/docs/ja/tutorial/3-components/index.mdx

- Update tutorial/3-components
- diff
- 1.mdx
- https://github.com/withastro/docs/pull/5254
- https://github.com/withastro/docs/pull/7496
- 2.mdx
- https://github.com/withastro/docs/pull/7496
- 3.mdx
- https://github.com/withastro/docs/pull/5254
- https://github.com/withastro/docs/pull/7496
- index.mdx
- https://github.com/withastro/docs/pull/4753
- Closes #

i18n(ja): Update tutorial/3-components

---

src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx

i18n(zh-cn): Update `tailwind.mdx`

---

src/content/docs/zh-cn/guides/middleware.mdx

A small chinese word `不全` is wrong, just fix it into correctly :).
My discord user name is QingXia_Ela

i18n(zh-cn): Update `middleware.mdx`

---

src/content/docs/en/upgrade-astro.mdx

This PR adds a new paragraph that explains how Astro will manage the support and upgrade of the Node.js versions.
I took the opportunity to add also a paragraph around our extended maintenance

feat: better explanation of the Node.js policy

---

src/content/docs/zh-cn/guides/images.mdx

i18n(zh-cn): Update `images.mdx`

---

src/content/docs/ko/guides/integrations-guide/tailwind.mdx

- update `tailwind.mdx`
- #7717
- Closes #

i18n(ko-KR): update `tailwind.mdx`

---

src/content/docs/en/guides/integrations-guide/markdoc.mdx

- Add documentation for Markdoc partials. These allow you to reuse content and reference by relative file path.
- Closes #

markdoc partials

---

src/content/docs/ko/guides/migrate-to-astro/from-create-react-app.mdx

- update `from-create-react-app.mdx`
- #7741
- Closes #

i18n(ko-KR): update `from-create-react-app.mdx`

---

src/content/docs/es/community-resources/content.mdx

- ISR has been added based on the update [`f5fd4ef`](https://github.com/withastro/docs/commit/f5fd4ef178ab70f553341cce7dcfe9916d2ea525)
[`7246ce8`](https://github.com/withastro/astro-docs/commit/7246ce8fca067b8f03abf48081a6a52bf63eab67)

i18n(es): community-resources/content.mdx

---

src/content/docs/es/guides/backend/supabase.mdx

Updates `supabase` based on this commit bd7a112a5a39053b94c63ac707e61e452317e537
- Closes # N/A

i18n(es): update `supabase.mdx`

---

src/content/docs/fr/guides/integrations-guide/tailwind.mdx

Updating `guides/integration-guide/tailwind.mdx` from https://github.com/withastro/docs/pull/7717
- Closes #

i18n(fr): Updating `guides/integration-guide/tailwind.mdx` 

---

src/content/docs/es/upgrade-astro.mdx

- **i18n First version in spanish**
- **i18n Updating links**

i18n(es): src/content/docs/es/upgrade-astro.mdx

---

src/content/docs/es/guides/integrations-guide/tailwind.mdx

Updates `tailwind` based on this commit bebf1cf5f18a647b97fcb8c81b63ae683f481868
- Closes # N/A

i18n(es): update `tailwind`

---

src/content/docs/zh-cn/reference/cli-reference.mdx

Update `cli-reference.mdx`
- #7771

i18n(zh-cn): Update `cli-reference.mdx`

---

src/content/docs/zh-cn/guides/backend/supabase.mdx

i18n(zh-cn): Update `supabase.mdx`

---

src/content/docs/en/guides/dev-toolbar.mdx

Little typo "toobar" in `dev-toolbar.mdx` line 43.
- Closes #

Fix: Little typo "toobar" in `dev-toolbar.mdx` [i18nIgnore]

---

src/content/docs/es/guides/prefetch.mdx

- Adding Steps component to prefetch.mdx (Spanish)
- Closes #

i18n(es): Adding Steps component to prefetch.mdx

---

src/content/docs/ko/reference/cli-reference.mdx

- update `cli-reference.mdx`
- #7771
- Closes #

i18n(ko-KR): update `cli-reference.mdx`

---

src/content/docs/en/guides/internationalization.mdx

Fixing a small docs bug in the internationalisation domains config demo.

fix(docs): internationalisation domains config demo

---

src/content/docs/zh-cn/guides/cms.mdx

i18n(zh-cn): Update `cms.mdx`

---

src/content/docs/zh-cn/guides/deploy/flyio.mdx

i18n(zh-cn): Create `flyio.mdx`

---

src/content/docs/de/tutorial/3-components/index.mdx

Add the German translation for `tutorial/3-components/index` (using the English version for reference)
Freu mich über jedes Feedback :)
Discord: Maxframe

i18n(de): add `tutorial/3-components/index`

---

src/content/docs/fr/guides/cms.mdx

Update `guides/cms.mdx` from #7752 and fix some err typo
- Closes #

i18n(fr): Update `guides/cms.mdx` from #7752

---

src/content/docs/zh-cn/guides/content-collections.mdx

Update `content-collections.mdx`
- #7460

i18n(zh-cn): Update `content-collections.mdx`

---

src/content/docs/es/guides/fonts.mdx

i18n(es): Adding step components to fonts.mdx

---

src/content/docs/zh-cn/guides/markdown-content.mdx

Update `markdown-content.mdx`
- #7462

i18n(zh-cn): Update `markdown-content.mdx`

---

.github/actions/install/action.yml
.github/workflows/lunaria.yml
lunaria.config.json
package.json
pnpm-lock.yaml
scripts/tuesday-bot.ts

This PR does two main things:
- Updates our Lunaria version to latest (I checked and no status differences were found between deploy vs local)
- Adds the Lunaria Action (it will now give internationalization insights on every PR to main)
I've also made our Setup Node use Node 20 instead of 18 since that's what I used for the Lunaria Action in my tests, I suppose that won't break anything (hopefully)

Update Lunaria to latest and add Action

---

.github/workflows/lunaria.yml

This PR removes a duplicate step in the GitHub Action

Fix duplicate step

---

src/content/docs/zh-cn/install/auto.mdx

i18n(zh-cn): Update `auto.mdx`

---

src/content/docs/zh-cn/reference/dev-toolbar-app-reference.mdx

Update `dev-toolbar-app-reference.mdx`
- #7846

i18n(zh-cn): Update `dev-toolbar-app-reference.mdx`

---

src/content/docs/zh-cn/reference/error-reference.mdx

Update `error-reference.mdx`
- #7846

i18n(zh-cn): Update `error-reference.mdx`

---

src/content/docs/es/install/auto.mdx

- Updating `auto.mdx` in spanish
- Closes #

i18n(es): Updating and translating node versions in auto.mdx

---

src/content/docs/en/community-resources/content.mdx

Update a typo at the content.mdx file

fix: Update content.mdx typo

---

src/content/docs/en/guides/cms/wordpress.mdx

The url for Soft Hard System is no longer working and redirects to some kind of advertisements network and no longer seems the intended url.
- Closes # N/A
- Suggested label: bug 
Jep! Let me know if I need to follow any specifics.

Removed url Soft Hard System that is no longer working

---

src/content/docs/fr/guides/backend/supabase.mdx

Updating `guides/backend/supabase.mdx` from #7767
- Closes #

i18n(fr): Updating `guides/backend/supabase.mdx` from #7767

---

src/content/docs/es/guides/backend/google-firebase.mdx

i18n(es): Updating Firebase Realtime Database

---

src/content/docs/fr/guides/dev-toolbar.mdx

Updating `guides/toolbar.mdx` from #7846
- Closes #
- Suggested label: i18N

i18n(fr): Updating `guides/toolbar.mdx` from #7846

---

src/content/docs/fr/install/auto.mdx

Updating `install/auto.mdx` from #7846
- Closes #

i18n(fr): Updating `install/auto.mdx` from #7846

---

src/content/docs/fr/reference/errors/no-prerendered-routes-with-domains.mdx

Updating `reference/errors/no-prerendered-routes-with-domains.mdx.mdx` from #7846
- Closes #

i18n(fr): Updating `reference/errors/no-prerendered-routes-with-domains.mdx`

---

src/content/docs/zh-cn/guides/cms/wordpress.mdx

Update `wordpress.mdx`
- #7886

i18n(zh-cn): Update `wordpress.mdx`

---

src/content/docs/zh-cn/guides/backend/google-firebase.mdx

Update `google-firebase.mdx`
- #7890

i18n(zh-cn): Update `google-firebase.mdx`

---

src/content/docs/es/guides/dev-toolbar.mdx

Updates `dev-toolbar` based on this commit 71de23ab285806bcd3cd0d3b88889fcb7ee2892d
- Closes # N/A

i18n(es): update `dev-toolbar`

---

src/content/docs/es/guides/integrations-guide/db.mdx

Updates db based on this commit 4d5c2e08d033055d0691fdf4ae5c975ec0409464
- Closes # N/A 

i18n(es): update `db`

---

src/content/docs/pt-br/guides/cms.mdx

Updates the pt-BR translation of the `cms.mdx` guide file.

i18n(pt-BR): Update `cms.mdx` translation

---

src/content/docs/ko/guides/cms/wordpress.mdx

- update `wordpress.mdx`
- #7886
- Closes #

i18n(ko-KR): update `wordpress.mdx`

---

src/content/docs/ko/guides/backend/google-firebase.mdx

- update `google-firebase.mdx`
- #7890
- Closes #

i18n(ko-KR): update `google-firebase.mdx`

---

src/content/docs/pt-br/community-resources/content.mdx

Updates the pt-br translation of the community content `content.mdx` file.

i18n(pt-BR): Update `content.mdx` translation

---

src/content/docs/zh-cn/guides/client-side-scripts.mdx

“using a UI framework”直译为“不使用一个”读起来会很奇怪。调整语序使其更容易理解。

i18n(zh-cn): Refine the sentence for better Chinese grammar

---

src/content/docs/es/guides/cms/wordpress.mdx

- Removing a dead link from the Wordpress guide (spanish)
- Closes #

i18n(es): Removing dead link from wordpress docs

---

src/content/docs/zh-cn/concepts/why-astro.mdx

make the highlight features more explicit, update why-astro.mdx
- Closes #

i18n(zh-CN): make the highlight features more explicit, update why-astro.mdx

---

package.json
pnpm-lock.yaml

The latest version of `astro` and `@astrojs/sitemap` offer some fixes that improve performance.

chore: update Astro to latest

---

src/content/docs/es/community-resources/content.mdx
src/content/docs/es/guides/deploy/aws.mdx

Updates `community-resources/content` and `aws` based on this commit a25061b514459689ed4f56843aab9d237b610a79
- Closes # N/A

i18n(es): update `community-resources/content` and `aws`

---

src/content/docs/es/guides/migrate-to-astro/from-nuxtjs.mdx

Updates `from-nuxtjs` based on this commit faa26f712fdb1c4fb46215acbf3ba1ff4017a7fd
- Closes # N/A

i18n(es): update `from-nuxtjs`

---

src/content/docs/es/guides/view-transitions.mdx

Updates `view-transitions` based on this commit 0dd134b2afaebc678798904fdb69bda464ee953e
- Closes # N/A

i18n(es): update `view-transitions`

---

src/content/docs/zh-cn/guides/deploy/flyio.mdx

i18n(zh-cn): Update `flyio.mdx`

---

src/content/docs/en/install/manual.mdx

- Updates the prerequisite Node.js versions in `manual.mdx`, so that they're consistent with `auto.mdx`
- #7846

Update the prerequisite Node.js versions in `manual.mdx`

---

package.json
pnpm-lock.yaml

Upgrades to the latest Astro patch.
- Related to https://github.com/withastro/docs/pull/7535. In order to verify that issue we need a new version of Astro in `main`.

Upgrade Astro version

---

src/content/docs/zh-tw/install/auto.mdx

- Updates `auto.mdx` in Traditional Chinese
- Related to https://github.com/withastro/docs/pull/7846
- ~~Closes #~~

i18n(zh-TW): update `auto.mdx`

---

src/content/docs/ko/install/manual.mdx

- update `manual.mdx`
- #7933
- Closes #

i18n(ko-KR): update `manual.mdx`

---

src/content/docs/zh-cn/install/manual.mdx

i18n(zh-cn): Update `manual.mdx`

---

src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx

Add missing spaces.
Urls does not require s in Chinese.
- Closes #

i18n(zh-cn): Update `from-vuepress.mdx`

---

src/content/docs/es/reference/cli-reference.mdx

Updates `cli-reference` based on this commit 93eee3038c79602752353fd2d9ed5df7feec11ca
- Closes # N/A

i18n(es): update `cli-reference`

---

src/content/docs/es/install/manual.mdx

Updates `manual` based on this commit 025a634b694a7c3da36b6c76032139e18a8088b5
- Closes # N/A

i18n(es): update `manual`

---

src/content/docs/es/reference/errors/no-prerendered-routes-with-domains.mdx

Updates `no-prerendered-routes-with-domains` based on this commit 71de23ab285806bcd3cd0d3b88889fcb7ee2892d
- Closes # N/A

i18n(es): update `no-prerendered-routes-with-domains`

---

astro.config.ts

- #7940 revealed there are still a few bugs with content collection caching
- This PR disables the caching for now so we can merge #7940 and reduce or OG image cache size in preparation for CC caching working

Disable content collection cache

---

src/content/docs/en/guides/internationalization.mdx

Fixes a typo/formatting error in a code block within the internationalisation guide.

Fix code block spacing in internationalisation guide

---

src/content/docs/ko/guides/internationalization.mdx

- update `internationlization.mdx`
- #7962
- Closes #

i18n(ko-KR): update `internationlization.mdx`

---

src/content/docs/en/community-resources/content.mdx

Add Spanish Astro 3.0 intro course
Add a Spanish "Astro 3 from scratch" course by @midudev

Add Spanish course on Docs

---

src/content/docs/de/tutorial/3-components/3.mdx

Add the German translation for `tutorial/3-components/3.mdx` (using the English version for reference)
Freu mich as always über jedes Feedback :P
Discord: Maxframe

i18n(de): add `tutorial/3-components/3`

---

src/content/docs/ko/guides/deploy/microsoft-azure.mdx

- update `microsoft-azure.mdx`
- #7955
- Closes #

i18n(ko-KR): update `microsoft-azure.mdx`

---

src/content/docs/zh-cn/guides/deploy/microsoft-azure.mdx

Update `microsoft-azure.mdx`
- #7955

i18n(zh-cn): Update `microsoft-azure.mdx`

---

src/content/docs/zh-cn/guides/testing.mdx

i18n(zh-cn): Update `testing.mdx`

---

src/content/docs/ko/guides/testing.mdx

- update `testing.mdx`
- #7859
- Closes #

i18n(ko-KR): update `testing.mdx`

---

src/content/docs/zh-cn/reference/integrations-reference.mdx

Update `integrations-reference.mdx`
- #7986

i18n(zh-cn): Update `integrations-reference.mdx`

---

src/content/docs/ko/reference/integrations-reference.mdx

- update `integrations-reference.mdx`
- #7986
- Closes #

i18n(ko-KR): update `integrations-reference.mdx`

---

src/content/docs/ja/guides/fonts.mdx

- Update fonts.mdx
- [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/fonts.mdx?since=2024-04-23T10:08:36.000Z)
- #7982 
- Closes #

i18n(ja): Update fonts.mdx

---

src/content/docs/fr/guides/integrations-guide.mdx

Update french translation for `integrations-guide.mdx` file with PR #7673

i18n(fr) Update french translation for `integrations-guide.mdx`

---

src/content/docs/fr/guides/deploy.mdx

i18n(fr) Update French Translation for `deploy.mdx` file with PR #7649

i18n(fr) Update French Translation for `deploy.mdx`

---

src/content/docs/fr/guides/cms/wordpress.mdx

Update french translation for `wordpress.mdx` file with PR #7886

i18n(fr) Update french translation for `wordpress.mdx`

---

src/content/docs/fr/guides/backend/google-firebase.mdx

Update french translation for `google-firebase.mdx` file with PR #7860

i18n(fr) Update french translation for `google-firebase.mdx`

---

src/content/docs/fr/community-resources/content.mdx

Update French translation for `content.mdx` file with PR #7984

i18n[FR] Update French translation for `content.mdx` file

---

src/content/docs/fr/guides/rss.mdx

Update French translation for `rss.mdx` file with PR #7878

i18n(fr) Update French translation for `rss.mdx`

---

src/content/docs/fr/guides/deploy/microsoft-azure.mdx

Update french translation for `microsoft-azure.mdx` file with PR #7955

i18n(fr) Update french translation for `microsoft-azure.mdx`

---

src/content/docs/fr/guides/content-collections.mdx

Update french translation for `content-collections.mdx` file with PR #7460

i18n(fr) Update french translation for `content-collections.mdx`

---

src/content/docs/fr/guides/images.mdx

Update french translation `images.mdx` file with PR #7856

i18n(fr) Update french translation `images.mdx`

---

src/content/docs/fr/guides/fonts.mdx

Update french translation for `fonts.mdx` file with PR #7982 and few omission

i18n(fr) Update french translation for `fonts.mdx`

---

src/content/docs/fr/guides/markdown-content.mdx

Update French translation `markdown-content.mdx` file with PR #7462

i18n(fr) Update French translation `markdown-content.mdx`

---

src/content/docs/ar/getting-started.mdx

I translated `getting-started.mdx`.
Before:
After:

i18n(ar): Update `getting-started.mdx`

---

src/content/docs/zh-cn/guides/rss.mdx

i18n(zh-cn): remove duplicated translation in rss.mdx

---

src/content/docs/es/recipes/dynamically-importing-images.mdx

i18n(es): Remove duplicated altText 

---

src/content/docs/ko/guides/backend/supabase.mdx

- update `supabase.mdx`
- #8129
- Closes #

i18n(ko-KR): update `supabase.mdx`

---

src/content/docs/ko/reference/errors/astro-glob-used-outside.mdx

- update `astro-glob-outside.mdx`
- Add a little more detailed explanation
- Closes #

i18n(ko-KR): update `astro-glob-outside.mdx`

---

src/content/docs/en/recipes/add-yaml-support.mdx

Add Steps component to `add-yaml-support.mdx`

---

src/content/docs/en/guides/deploy/stormkit.mdx

Add Steps component to `stormkit.mdx`

---

src/content/docs/en/guides/middleware.mdx

Add Steps component to `middleware.mdx`

---

src/content/docs/en/guides/deploy/deno.mdx

Add Steps component to `deno.mdx`

---

src/content/docs/en/guides/deploy/microsoft-azure.mdx

Add Steps component to `microsoft-azure.mdx`

---

src/content/docs/en/recipes/reading-time.mdx

Add Steps component to `reading-times.mdx`

---

src/content/docs/en/guides/cms/preprcms.mdx

Add Steps component to `preprcms.mdx`

---

src/content/docs/en/recipes/docker.mdx

Add Steps component to `docker.mdx`

---

src/content/docs/en/guides/upgrade-to/v2.mdx

Add Steps component to `v2.mdx`

---

src/content/docs/en/guides/deploy/surge.mdx

Add Steps component to `surge.mdx`

---

src/content/docs/en/guides/deploy/kinsta.mdx

Add Steps component to `kinsta.mdx`

---

src/content/docs/en/guides/deploy/netlify.mdx

Add Steps component to `netlify.mdx`

---

src/content/docs/en/guides/cms/sitecore.mdx

Add Steps component to `sitecore.mdx`

---

src/content/docs/en/guides/ecommerce.mdx

Add Steps component to `ecommerce.mdx`

---

src/content/docs/en/recipes/build-forms-api.mdx

Add Steps component to `build-forms-api.mdx`

---

src/content/docs/en/guides/integrations-guide/markdoc.mdx

Add Steps component to `markdoc.mdx`

---

src/content/docs/en/guides/deploy/cloudflare.mdx

Add Steps component to `cloudfare.mdx`

---

src/content/docs/en/guides/deploy/edgio.mdx

Add Steps component to `edgio.mdx`

---

src/content/docs/en/recipes/call-endpoints.mdx

Add Steps component to `call-endpoint.mdx`

---

src/content/docs/en/recipes/tailwind-rendered-markdown.mdx

Add Steps component to `tailwind-rendered-markdown.mdx`

---

src/content/docs/en/recipes/i18n.mdx

Add Steps component to `i18n.mdx`

---

src/content/docs/en/guides/cms/storyblok.mdx

Add Steps component to `storyblok.mdx`

---

src/content/docs/en/guides/cms/spinal.mdx

Add Steps component to `spinal.mdx`

---

src/content/docs/en/recipes/build-custom-img-component.mdx

Add Steps component to `build-custom-img-component.mdx`

---

src/content/docs/en/guides/deploy/google-firebase.mdx

Add Steps component to `google-firebase.mdx`

---

src/content/docs/en/guides/deploy/cleavr.mdx

Add Steps component to `cleavr.mdx`

---

src/content/docs/en/guides/deploy/render.mdx

Add Steps component to `render.mdx`

---

src/content/docs/en/guides/cms/contentful.mdx

Add Steps component to `contentful.mdx`

---

src/content/docs/en/recipes/modified-time.mdx

Add Steps component to `modified-time.mdx`

---

src/content/docs/en/guides/cms/payload.mdx

Add Steps component to `payload.mdx`

---

src/content/docs/en/reference/directives-reference.mdx

Added an Oxford comma that was personally driving sarah insane
(also corrected similar to similarly)
- Suggested label: docs

[i18nIgnore] Update directives-reference.mdx/added a comma

---

src/content/docs/zh-cn/recipes/bun.mdx

- Update bun.mdx
- Closes #
- https://github.com/withastro/docs/pull/8183

i18n(zh-cn): Update bun.mdx

---

src/content/docs/zh-cn/guides/integrations-guide/react.mdx

- Update react.mdx
- https://github.com/withastro/docs/pull/8038
- Closes #

i18n(zh-cn): Update react.mdx

---

src/content/docs/zh-cn/guides/cms/cosmic.mdx

- Use `Steps` in cosmic.mdx
- Translate `Themes` to `主题`
- https://github.com/withastro/docs/pull/8082
- Closes #

i18n(zh-cn): Update cosmic.mdx

---

src/content/docs/en/recipes/sharing-state-islands.mdx

This pull request improves the Frequently Asked Questions part on the section about Nano Stores and state sharing.
- Closes #7936

Improve Nano Store FAQ

---

src/content/docs/zh-cn/tutorial/4-layouts/1.mdx
src/content/docs/zh-cn/tutorial/6-islands/2.mdx
src/content/docs/zh-cn/tutorials/add-view-transitions.mdx

Update zh-cn content to keep consistent with en.
- Closes #

i18n(zh-cn): fix inconsistencies with the en doc [i18nIgnore]

---

src/content/docs/zh-cn/guides/data-fetching.mdx

Update `data-fetching.mdx`
- #8210

i18n(zh-cn): Update `data-fetching.mdx`

---

src/content/docs/en/guides/integrations-guide/mdx.mdx
src/content/docs/en/guides/integrations-guide/preact.mdx
src/content/docs/en/guides/integrations-guide/solid-js.mdx
src/content/docs/en/guides/integrations-guide/vercel.mdx
src/content/docs/en/guides/integrations-guide/vue.mdx
src/content/docs/en/guides/testing.mdx
src/content/docs/en/reference/configuration-reference.mdx
src/content/docs/en/reference/dev-toolbar-app-reference.mdx
src/content/docs/en/reference/error-reference.mdx
src/content/docs/en/reference/errors/prerender-client-address-not-available.mdx
src/content/docs/en/reference/errors/route-not-found.mdx

This PR includes the individual PRs for the 4.8.0 minor release:
- #8050 
- #8150 
- #8151 
- #8164 
- #8188 
- #8189 
- #8192 
- #8219 
- #8220 
- #8234

4.8.0 minor release docs

---

src/content/docs/zh-cn/recipes/sharing-state-islands.mdx

Update `sharing-state-islands.mdx`
- #8223

i18n(zh-cn): Update `sharing-state-islands.mdx`

---

src/content/docs/zh-cn/guides/framework-components.mdx

- Update translation of `modifier`, from `修改器`to `修饰符`
- Closes #

i18n(zh-cn): Update translation in framework-components.mdx

---

src/content/docs/zh-cn/getting-started.mdx

- Update the getting-started bannber
- Closes #

i18n(zh-cn): Astro together is coming

---

src/content/docs/zh-cn/getting-started.mdx

Update `getting-started.mdx`
- #8222

i18n(zh-cn): Update `getting-started.mdx`

---

src/content/docs/zh-cn/tutorial/1-setup/1.mdx

Update `1-setup/1.mdx`
- #8258

i18n(zh-cn): Update `1-setup/1.mdx`

---

src/content/docs/zh-cn/guides/deploy/netlify.mdx
src/content/docs/zh-cn/guides/deploy/render.mdx

Update content about upstream #8233
- #8233

i18n(zh-cn): Update content about upstream #8233

---

src/content/docs/en/guides/cms/builderio.mdx

.
fixed typo in example footer
I needed to change map to flatMap in the example blogpost article page. (astro 4.8)
- Closes #

Change map to flatMap in Builder.io example.

---

src/content/docs/fr/tutorial/1-setup/1.mdx

Update `tutorial/1-setup/1.mdx` from #8258
- Closes #

i18n(fr): Update `tutorial/1-setup/1.mdx` from #8258

---

src/content/docs/fr/guides/middleware.mdx

Update `guides/middleware.mdx` file from #8176
- Closes #

i18n(fr): Update `guides/middleware.mdx` file from #8176

---

src/content/docs/en/recipes/external-links.mdx
src/content/docs/fr/guides/ecommerce.mdx
src/content/docs/fr/guides/rss.mdx
src/content/docs/fr/recipes/add-yaml-support.mdx
src/content/docs/fr/recipes/build-custom-img-component.mdx
src/content/docs/fr/recipes/build-forms-api.mdx
src/content/docs/fr/recipes/build-forms.mdx
src/content/docs/fr/recipes/call-endpoints.mdx
src/content/docs/fr/recipes/captcha.mdx
src/content/docs/fr/recipes/docker.mdx
src/content/docs/fr/recipes/dynamically-importing-images.mdx
src/content/docs/fr/recipes/external-links.mdx
src/content/docs/fr/recipes/i18n.mdx
src/content/docs/fr/recipes/modified-time.mdx
src/content/docs/fr/recipes/sharing-state.mdx
src/content/docs/fr/recipes/tailwind-rendered-markdown.mdx

Update a bunch of file from #8167 (STEPS)
This is the continuation of [this PR about Steps](https://github.com/withastro/docs/pull/8208).
- Closes #

i18n(fr): Update a bunch of file from #8167 (STEPS)

---

src/content/docs/fr/recipes/bun.mdx

Update `bun.mdx` from #8183
- Closes #

i18n(fr): Update `bun.mdx` from #8183

---

src/content/docs/zh-cn/editor-setup.mdx

Update `editor-setup.mdx`
- #8238

i18n(zh-cn): Update `editor-setup.mdx`

---

src/content/docs/zh-cn/guides/cms/apostrophecms.mdx
src/content/docs/zh-cn/guides/cms/umbraco.mdx

Update content about upstream #8231
- #8231

i18n(zh-cn): Update content about upstream #8231

---

src/content/docs/zh-cn/guides/cms/builderio.mdx

Update `builderio.mdx`
- #8259

i18n(zh-cn): Update `builderio.mdx`

---

src/content/docs/zh-cn/recipes/docker.mdx

i18n(zh-cn): Update `docker.mdx`

---

src/content/docs/zh-cn/reference/error-reference.mdx
src/content/docs/zh-cn/reference/errors/actions-without-server-output-error.mdx

Update `actions-without-server-output-error.mdx`
Update `error-reference.mdx`
- #8283

i18n(zh-cn): Update content about upstream #8283

---

src/content/docs/es/guides/deploy/github.mdx

Change "con" for "with" in the Github action
GitHub Action doesn't work well with "con" in Spanish.
- Closes #

i18n(es): Update github.mdx [i18nIgnore]

---

src/content/docs/en/community-resources/content.mdx

Please can our new Udemy course be added to the list of "Courses and Tutorials" ? As huge fans of Astro, we hope the course contributes in some small way to the community.

Update content.mdx to include new Astro course

---

src/content/docs/en/reference/container-reference.mdx

This PR fixes all of the changes requested in the Astro Discord Community. 
- Closes: Issues listed in the screenshot above.
- Suggested label:  #Docs, #SmallChange, #English 
By @SnowDingo, Discord: Snowdingo

[en] Fixed issues in container reference page. 

---

src/content/docs/zh-cn/reference/api-reference.mdx

Update `api-reference.mdx`
- #8373

i18n(zh-cn): Update `api-reference.mdx`

---

src/content/docs/zh-cn/reference/configuration-reference.mdx

Update `configuration-reference.mdx`
- #8369

i18n(zh-cn): Update `configuration-reference.mdx`

---

src/i18n/zh-cn/nav.ts

i18n(zh-cn): Update `nav.ts`

---

src/content/docs/ko/reference/configuration-reference.mdx

- update `configuration-reference.mdx`
- #8369
- Closes #

i18n(ko-KR): update `configuration-reference.mdx`

---

src/content/docs/ko/reference/api-reference.mdx

- update `api-reference.mdx`
- #8373
- Closes #

i18n(ko-KR): update `api-reference.mdx`

---

src/content/docs/zh-cn/tutorial/5-astro-api/4.mdx

i18n(zh-cn): Update `4.mdx`

---

src/content/docs/ko/reference/errors/server-only-module.mdx

- add `server-only-module.mdx`
- Closes #

i18n(ko-KR): add `server-only-module.mdx`

---

src/content/docs/ko/reference/errors/rewrite-encountered-an-error.mdx

- add `rewrite-encountered-an-error.mdx`
- Closes #

i18n(ko-KR): add `rewrite-encountered-an-error.mdx`

---

src/content/docs/ko/reference/errors/invalid-rewrite404.mdx

- add `invalid-rewrite404.mdx`
- Closes #

i18n(ko-KR): add `invalid-rewrite404.mdx`

---

src/content/docs/ko/reference/errors/env-invalid-variables.mdx

- add `env-invalid-variables.mdx`
- Closes #

i18n(ko-KR): add `env-invalid-variables.mdx`

---

src/content/docs/ko/reference/errors/env-invalid-variable.mdx

- add `env-invalid-variable.mdx`
- Closes #

i18n(ko-KR): add `env-invalid-variable.mdx`

---

src/content/docs/en/basics/rendering-modes.mdx

Added a link from Rendering modes page to SSR adapters in prep for this page possibly no longer being in the main sidebar

better linkage to SSR adapters page

---

src/content/docs/en/guides/cms/apostrophecms.mdx

Updates link text that read "here"

Fix vague link description in ApostropheCMS

---

src/content/docs/ko/guides/astro-db.mdx

- update `astro-db.mdx`
- #8478
- Closes #

i18n(ko-KR): update `astro-db.mdx`

---

src/content/docs/ko/tutorial/5-astro-api/2.mdx

- update `2.mdx`
- #8489
- Closes #

i18n(ko-KR): update `2.mdx`

---

src/content/docs/zh-cn/tutorial/2-pages/2.mdx
src/content/docs/zh-cn/tutorial/4-layouts/2.mdx

- update `2-pages/2.mdx` & `4-layouts/2.mdx`
- https://github.com/withastro/docs/pull/8318
- Closes #

i18n(zh-cn): update `2-pages/2.mdx` & `4-layouts/2.mdx`

---

src/content/docs/zh-cn/tutorial/5-astro-api/2.mdx

- update `5-astro-api/2.mdx`
- https://github.com/withastro/docs/pull/8489
- Closes #

i18n(zh-cn): update `5-astro-api/2.mdx`

---

src/content/docs/zh-cn/guides/routing.mdx

- update `routing.mdx`
- Closes #
- https://github.com/withastro/docs/pull/8472

i18n(zh-cn): update `routing.mdx`

---

src/content/docs/zh-cn/guides/cms/apostrophecms.mdx

update `apostrophecms.mdx`
- https://github.com/withastro/docs/pull/8480

i18n(zh-cn): update `apostrophecms.mdx`

---

src/content/docs/en/install-and-setup.mdx

- Promotes the dev toolbar link higher in the install and setup page

Promote Dev Toolbar Link

---

src/content/docs/zh-tw/getting-started.mdx

- Updates `getting-started.mdx`
- #8410

i18n(zh-tw): update `getting-started.mdx`

---

src/content/docs/en/guides/environment-variables.mdx

Add explanation about Vite environment variables being replaced at build time
closes #8509

Add explanation about Vite environment variables being replaced at build time

---

src/content/docs/ko/reference/errors/rewrite-with-body-used.mdx

- add `rewrite-with-body-used.mdx`
- Closes #

i18n(ko-KR): add `rewrite-with-body-used.mdx`

---

src/content/docs/ko/guides/environment-variables.mdx

- update `environment-variables.mdx`
- #8533
- Closes #

i18n(ko-KR): update `environment-variables.mdx`

---

src/content/docs/en/install-and-setup.mdx

Fix incorrect link in `install-and-setup.mdx`
- Closes #

Fix incorrect link in `install-and-setup.mdx`

---

src/content/docs/en/tutorial/2-pages/2.mdx
src/content/docs/en/tutorial/4-layouts/2.mdx

Aligning images alt attribute description to https://github.com/withastro/docs/blob/94f0befa5fb070ffe8d0ce7f9ecaefcd9088f96d/src/content/docs/en/tutorial/2-pages/2.mdx?plain=1#L53
- Closes #

align images alt attribute description

---

src/content/docs/ko/install-and-setup.mdx

- add `install-and-setup.mdx`
- #8545
- Closes #

i18n(ko-KR): add `install-and-setup.mdx`

---

src/content/docs/zh-cn/tutorial/5-astro-api/1.mdx

update 5-astro-api/1.mdx
- https://github.com/withastro/docs/pull/8191
- Closes #

i18n(zh-cn): update 5-astro-api/1.mdx

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

Fix typo in cloudflare.mdx

---

src/content/docs/zh-cn/recipes/i18n.mdx

Update `i18n.mdx`
- https://github.com/withastro/docs/pull/8583
- Closes #

i18n(zh-cn): Update `i18n.mdx`

---

src/content/docs/zh-cn/guides/backend.mdx

Update `backend.mdx`
- https://github.com/withastro/docs/pull/8450
- Closes #

i18n(zh-cn): Update `backend.mdx`

---

src/content/docs/en/guides/environment-variables.mdx

To help with search results and discoverability for `astro:env`, adds a link from the main Environment Variables guide.

[environment-variables.mdx] link to `astro:env`

---

src/util/isSubPage.ts

This PR updates the sidebar item to be highlighted when viewing a recipe, since the list of recipes now lives on a different page.

sidebar nav highlighting for recipes

---

src/content/docs/zh-cn/basics/layouts.mdx

Update `layouts.mdx`
- https://github.com/withastro/docs/pull/8621

i18n(zh-cn): Update `layouts.mdx`

---

src/content/docs/es/guides/astro-db.mdx

Updates `astro-db`
- Closes # N/A

i18n(es): update `astro-db`

---

src/content/docs/es/basics/layouts.mdx

Updated a paragraph removing a duplicated word.
- Closes #
Discord: @juanprq

i18n(es): Update layouts.mdx [i18nIgnore]

---

src/content/docs/en/guides/integrations-guide/preact.mdx

This PR is a very small change to update the name of the Preact tutorial
see https://github.com/withastro/docs/pull/8624#issuecomment-2186511512

chore: update preact tutorial name

---

src/content/docs/zh-cn/guides/integrations-guide/preact.mdx

update `preact.mdx`
- https://github.com/withastro/docs/pull/8644

i18n(zh-cn): update `preact.mdx`

---

src/content/docs/zh-cn/guides/cms/directus.mdx

update `directus.mdx`
- https://github.com/withastro/docs/pull/8647

i18n(zh-cn): update `directus.mdx`

---

src/content/docs/zh-cn/guides/rss.mdx

update `rss.mdx`
- https://github.com/withastro/docs/pull/8632

i18n(zh-cn): update `rss.mdx`

---

src/content/docs/fr/community-resources/content.mdx

i18n(fr): Update `community-resources/content.mdx`

i18n(fr): Update `community-resources/content.mdx`

---

src/content/docs/zh-cn/guides/upgrade-to/v3.mdx

update `v3.mdx`
- https://github.com/withastro/docs/pull/8659

i18n(zh-cn): update `v3.mdx`

---

src/content/docs/ko/guides/upgrade-to/v3.mdx

- update `v3.mdx`
- #8659
- Closes #

i18n(ko-KR): update `v3.mdx`

---

src/content/docs/fr/community-resources/talks.mdx

Update `community-resources/talks.mdx` from #8371

i18n(fr): Update `community-resources/talks.mdx` from #8371

---

src/content/docs/fr/getting-started.mdx

i18n(fr): Update `getting-started.mdx` from #8239 (because links are already written)

i18n(fr): Update `getting-started.mdx` from #8239 

---

src/content/docs/fr/reference/error-reference.mdx

Update `reference/error-reference.mdx` from #8439

i18n(fr): Update `reference/error-reference.mdx` from #8439

---

src/content/docs/fr/guides/backend/sentry.mdx

Add `guides/backend/sentry.mdx` :tada:

i18n(fr): Add `guides/backend/sentry.mdx` :tada:

---

src/content/docs/fr/basics/project-structure.mdx
src/content/docs/fr/guides/deploy/render.mdx
src/content/docs/fr/install-and-setup.mdx
src/content/docs/fr/recipes/bun.mdx
src/content/docs/fr/reference/cli-reference.mdx

* Translate [install-and-setup.mdx](https://docs.astro.build/en/install-and-setup/) (added in #8415) in French

i18n(fr): add install-and-setup.mdx

---

src/content/docs/en/tutorials/add-view-transitions.mdx

Fix view transitions tutorial

---

src/content/docs/fr/guides/content.mdx

* Translate [Authoring Content](https://docs.astro.build/en/guides/content/) (`guides/content.mdx`) in French (it was added a while ago in #1394)

i18n(fr): add guides/content.mdx

---

src/content/docs/fr/guides/content-collections.mdx

* Add translation for the the tip added in #8649
* Improve some wording
* Replace `collecte` occurences with `collections` (they don't have the same meaning)
* Fix spelling
* Remove space before `:` when referring to code (English syntax) and add missing space before `:` when it comes to French content
* Add missing translation

i18n(fr): update content-collections.mdx

---

src/content/docs/ko/reference/dev-toolbar-app-reference.mdx

- update `dev-toolbar-app-reference.mdx`
- #8706
- Closes #

i18n(ko-KR): update `dev-toolbar-app-reference.mdx`

---

src/content/docs/zh-cn/tutorials/add-view-transitions.mdx

Update `add-view-transitions.mdx`
- #8707 
- https://github.com/withastro/docs/pull/7677
- https://github.com/withastro/docs/pull/8723

i18n(zh-cn): Update `add-view-transitions.mdx`

---

src/content/docs/zh-cn/guides/endpoints.mdx

Update `endpoints.mdx`
- #8721 

i18n(zh-cn): Update `endpoints.mdx`

---

src/content/docs/en/guides/deploy/zerops.mdx

- Added video links of one click deploy for both ssr and ssg
- Closes #

Add video links in zerops guide

---

src/content/docs/en/guides/markdown-content.mdx

Added an example of how the plugin works.
- Confusing examples @ https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
- Sarah asked me to do a PR.
English
- Closes #

markdown plugin changes

---

src/content/docs/fr/guides/endpoints.mdx

Add `guides/endpoints.mdx` from #8721

i18n(fr): Add `guides/endpoints.mdx` from #8721

---

src/content/docs/ko/guides/endpoints.mdx

- update `endpoints.mdx`
- #8721
- Closes #

i18n(ko-KR): update `endpoints.mdx`

---

src/content/docs/ko/guides/deploy/zerops.mdx

- update `zerops.mdx`
- #8727
- Closes #

i18n(ko-KR): update `zerops.mdx`

---

src/content/docs/ko/recipes/i18n.mdx

- update `i18n.mdx`
- #8645
- Closes #

i18n(ko-KR): update `i18n.mdx`

---

src/content/docs/fr/recipes/i18n.mdx

Update `recipes/i18n.mdx` from #8645

i18n(fr): Update `recipes/i18n.mdx` from #8645

---

src/content/docs/fr/guides/markdown-content.mdx

Add `guides/markdown-content.mdx` from #8728

i18n(fr): Add `guides/markdown-content.mdx` from #8728

---

src/content/docs/fr/guides/cms/hashnode.mdx

i18n(fr): Add `guides/cms/hashnode.mdx`

---

src/content/docs/fr/guides/cms/umbraco.mdx

i18n(fr): Add `guides/cms/umbraco.mdx`

---

src/content/docs/fr/guides/deploy/render.mdx

Update `render.mdx` from #8746

i18n(fr): Update `render.mdx` from #8746

---

src/content/docs/fr/tutorials/add-view-transitions.mdx

* Add updates made to `tutorials/add-view-transitions.mdx` in #8707
* Replace `page "About"` with `page "À propos"` (since the other ones are translated)
* Translate a missing `Update to Astro v4.x` comment
* Add a space before colon inside comments written in French
* Remove some extra indent on new lines (it was messing with syntax highlighting)

i18n(fr): update tutorials/add-view-transitions.mdx

---

src/content/docs/fr/guides/testing.mdx

* Update the Cypress link updated in #8704
* Fix a typo
* Replace "Configurez un `baseUrl`" with "Configurer `baseUrl`" in Tips title (I think "un baseUrl" sounds weird in French)
* Remove space before colon in code samples (this is not French syntax)
* Translate VScode extension link
**Note:** If you checked the page in a live preview of the documentation website, you may see an issue with the Tips title. It has been reported in #8711 and tracked in https://github.com/withastro/starlight/discussions/1915.

i18n(fr): update guides/testing.mdx

---

src/content/docs/zh-cn/guides/deploy/zerops.mdx

i18n(zh-cn): Update `zerops.mdx`

---

src/content/docs/zh-cn/guides/deploy/render.mdx

i18n(zh-cn): Update `render.mdx`

---

src/content/docs/fr/guides/view-transitions.mdx

Update `guides/view-transitions.mdx` from #8740

i18n(fr): Update `guides/view-transitions.mdx` from #8740

---

src/content/docs/ko/guides/deploy/render.mdx

- update `render.mdx`
- #8746
- Closes #

i18n(ko-KR): update `render.mdx`

---

src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx

* Add French translation for [Migrating from Gatsby](https://docs.astro.build/en/guides/migrate-to-astro/from-gatsby/) (`migrate-to-astro/from-gatsby.mdx`) added in #2232

i18n(fr): add migrate-to-astro/from-gatsby.mdx

---

src/content/docs/ko/guides/migrate-to-astro/from-nuxtjs.mdx

- update `from-nuxtjs.mdx`
- #8765
- Closes #

i18n(ko-KR): update `from-nuxtjs.mdx`

---

src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx

Update `from-nuxtjs.mdx`
- https://github.com/withastro/docs/pull/8765

i18n(zh-cn):Update `from-nuxtjs.mdx`

---

src/content/docs/fr/guides/deploy/stormkit.mdx

Add `guides/deploy/stormkit.mdx` in French language

i18n(fr): Add `guides/deploy/stormkit.mdx` in French language

---

src/content/docs/en/guides/integrations-guide/cloudflare.mdx

[i18nIgnore] Fix Spelling typo on Cloudflare

---

src/content/docs/fr/guides/cms/keystatic.mdx

* Add changes from #8797 in French translation of `guides/cms/keystatic.mdx`

i18n(fr): update guides/cms/keystatic.mdx

---

src/content/docs/zh-cn/guides/cms/keystatic.mdx

Update `keystatic.mdx`
- #8797 

i18n(zh-cn): Update `keystatic.mdx`

---

src/content/docs/zh-cn/recipes/build-forms-api.mdx

Update `build-forms-api.mdx`
- #8801 

i18n(zh-cn): Update `build-forms-api.mdx`

---

src/content/docs/ko/recipes/build-forms-api.mdx

- update `build-forms-api.mdx`
- #8801
- Closes #

i18n(ko-KR): update `build-forms-api.mdx`

---

src/content/docs/fr/recipes/build-forms-api.mdx

* Add changes made in #8801 to French translation of `recipes/build-forms-api.mdx`

i18n(fr): update recipes/build-forms-api.mdx

---

src/content/docs/fr/guides/integrations-guide/cloudflare.mdx

Update French translation of `integrations-guide/cloudflare.mdx` with the following changes:
* Fix a paragraph because of a typo in the English version (see #8785) and some untranslated or missing words in French version
* Update new imageService default (from #8804)

i18n(fr): update integrations-guide/cloudflare.mdx

---

src/content/docs/en/reference/cli-reference.mdx

Docs for https://github.com/withastro/astro/pull/11482, just a small new flag to disable the implicit astro sync

feat: add new flag for astro check

---

src/content/docs/en/community-resources/content.mdx

Link to "Creating A Pagination Component With Astro"

Add community recipe

---

src/content/docs/es/tutorial/2-pages/index.mdx

i18n(es): Update index.mdx

---

src/content/docs/es/tutorial/2-pages/2.mdx

i18n(es): Update 2.mdx [i18nIgnore]

---

src/content/docs/ko/guides/ecommerce.mdx

- update `ecommerce.mdx`
- #8822
- Closes #

i18n(ko-KR): update `ecommerce.mdx`

---

src/content/docs/ko/guides/migrate-to-astro/from-pelican.mdx

- update `from-pelican.mdx`
- #8812
- Closes #

i18n(ko-KR): update `from-pelican.mdx`

---

src/content/docs/ko/guides/cms/craft-cms.mdx

- create `craft-cms.mdx`
- Closes #

i18n(ko-KR): create `craft-cms.mdx`

---

src/content/docs/fr/guides/typescript.mdx

* Update code sample (see #8836)

i18n(fr): update `guides/typescript.mdx`
