withastro/docs

src/content/docs/fr/guides/migrate-to-astro/from-pelican.mdx
* Add a new paragraph to `migrate-to-astro/from-pelican.mdx` (see #8812)
=> i18n(fr): update `migrate-to-astro/from-pelican.mdx`

src/content/docs/fr/guides/ecommerce.mdx
* Add a new community resource (see #8822)
=> i18n(fr): update guides/ecommerce.mdx

src/content/docs/fr/guides/deploy/gitlab.mdx
* Update Gitlab deployment guide (see #8811)
=> i18n(fr): update `guides/deploy/gitlab.mdx`

src/content/docs/fr/guides/backend/supabase.mdx
* Add changes from #8799 to French translation of `guides/backend/supabase.mdx`
* Translate all `FileTree` titles (even if they seem unused currently)
=> i18n(fr): update `guides/backend/supabase.mdx`

src/content/docs/fr/guides/cms/craft-cms.mdx
* Translate in French the [new guide for Craft CMS](https://docs.astro.build/en/guides/cms/craft-cms/) (`guides/cms/craft-cms.mdx`), see #8858
=> i18n(fr): add `guides/cms/craft-cms.mdx`

src/content/docs/zh-cn/guides/typescript.mdx
Update `typescript.mdx`
- #8836 
=> i18n(zh-cn): Update `typescript.mdx`

src/content/docs/zh-cn/guides/ecommerce.mdx
Update `ecommerce.mdx`
- #8822 
=> i18n(zh-cn): Update `ecommerce.mdx`

src/components/BackendGuidesNav.astro
Alphabetize back end guides' nav.
- Moves #8860 closer to closing
=> Backend guides nav: sort alphabetically (part of #8860)

src/components/MigrationGuidesNav.astro
Alphabetize migration guides' nav.
- Moves #8860 closer to closing
=> Migration guides nav: sort alphabetically (part of #8860)

src/content/docs/fr/guides/routing.mdx
* Apply changes from #8894 to French translation of `guides/routing.mdx`
=> i18n(fr): update `guides/routing.mdx`

src/content/docs/zh-cn/guides/cms/craft-cms.mdx
=> i18n(zh-cn): add `craft-cms.mdx`

src/content/docs/zh-cn/guides/migrate-to-astro/from-pelican.mdx
Update `from-pelican.mdx`
- #8812 
=> i18n(zh-cn): Update `from-pelican.mdx`

src/content/docs/zh-cn/guides/data-fetching.mdx
add a whitespace to break url and ')'
=> i18n(zh-cn): fix broken link in `data-fetching.mdx`

src/content/docs/en/guides/authentication.mdx
This PR adds [Clerk and Astro integration](https://clerk.com/docs/quickstarts/astro) to Authentication guide
=> Add Clerk Astro guide

src/content/docs/fr/tutorial/5-astro-api/2.mdx
Update `tutorial/5-astro-api/2.mdx` from #8907
- Linked PR : https://github.com/withastro/docs/pull/8907
=> i18n(fr): Update `tutorial/5-astro-api/2.mdx` from #8907

src/content/docs/fr/recipes/making-toolbar-apps.mdx, src/content/docs/fr/reference/dev-toolbar-app-reference.mdx
Add `reference/dev-toolbar-reference.mdx`
=> i18n(fr): Add `reference/dev-toolbar-reference.mdx`

src/content/docs/en/install-and-setup.mdx
This PR adds information about the browsers Astro supports by default through Vite.
=> Add information about browser compatibility to Installation guide

src/content/docs/en/guides/routing.mdx
there is a comment typo.
`next` => `last`
=> Fix typo in `routing.mdx`

src/content/docs/zh-cn/install-and-setup.mdx
Update `install-and-setup.mdx`
- #8942
=> i18n(zh-cn): Update `install-and-setup.mdx`

src/content/docs/ko/install-and-setup.mdx
- update `install-and-setup.mdx`
- #8942
- Closes #
=> i18n(ko-KR): update `install-and-setup.mdx`

src/content/docs/ko/guides/routing.mdx
- update `routing.mdx`
- #8941
- Closes #
=> i18n(ko-KR): update `routing.mdx`

.github/workflows/welcome-bot.yml
PRs deploy previews to Netlify now
=> ci(welcome-bot): update reference from Vercel to Netlify

src/content/docs/ko/basics/project-structure.mdx
- update `project-structure.mdx`
- #8953
- Closes #
=> i18n(ko-KR): update `project-structure.mdx`

src/content/docs/fr/reference/errors/rewrite-with-body-used.mdx
Update `reference/errors/rewrite-with-body-used.mdx` from #8967
=> i18n(fr): Update `reference/errors/rewrite-with-body-used.mdx` from #8967

src/content/docs/fr/reference/errors/rewrite-encountered-an-error.mdx
Update `reference/errors/rewrite-encountered-an-error.mdx` from #8967
=> i18n(fr): Update `reference/errors/rewrite-encountered-an-error.mdx` from #8967

src/content/docs/fr/basics/astro-components.mdx
There is a little typo in the french version doc 
I haven't opened an issue because it's a very small fix 🙏
=> docs: fix typo

src/content/docs/en/guides/routing.mdx
fix typo path in routing.mdx
- Closes #
=> fix typo path in routing.mdx

src/content/docs/fr/guides/content-collections.mdx
* Apply changes from #8988 to French translation of `guides/content-collections.mdx`
=> i18n(fr): update `guides/content-collections.mdx`

src/content/docs/ko/guides/imports.mdx
- update `imports.mdx`
- #8981
- Closes #
=> i18n(ko-KR): update `imports.mdx`

src/content/docs/fr/reference/error-reference.mdx, src/content/docs/fr/reference/errors/action-called-from-server-error.mdx
-  Add `reference/errors/action-called-from-server-error.mdx`
- [i18n(fr): Update reference/error-reference.mdx](https://github.com/withastro/docs/commit/162ec42a9251a959994ebbdd322596a26a95373d)
=> i18n(fr): Add `reference/errors/action-called-from-server-error.mdx`

src/content/docs/fr/reference/api-reference.mdx
* Apply changes from #8943 to French translation of `api-reference.mdx`
* Reword a few sentences to make reading easier.
* Apply fix (missing brackets) from #9006
=> i18n(fr): update `api-reference.mdx`

src/content/docs/ko/reference/configuration-reference.mdx, src/content/docs/ko/reference/error-reference.mdx, src/content/docs/ko/reference/errors/action-called-from-server-error.mdx, src/content/docs/ko/reference/errors/action-query-string-invalid-error.mdx, src/content/docs/ko/reference/errors/actions-used-with-for-get-error.mdx, src/content/docs/ko/reference/errors/rewrite-encountered-an-error.mdx, src/content/docs/ko/reference/errors/rewrite-with-body-used.mdx
- update `configuration-reference.mdx`
- update `/reference/errors/`
- #8967
- #8999
- Closes #
=> i18n(ko-KR): update `configuration-reference.mdx`, `error-reference.mdx`, `/reference/errors/`

src/content/docs/en/guides/typescript.mdx
This adds some content and new headings to the TypeScript setup section to allow easier direct linking to different concepts.
- Closes #9010
=> Improve TypeScript "setup" section

src/content/docs/en/guides/integrations-guide/alpinejs.mdx
Added a small line of text to clarify Alpine components do not need a client directive
- Closes #9013
=> Updates alpinejs.mdx

src/content/docs/fr/guides/integrations-guide/alpinejs.mdx
Update `guides/integrations-guide/alpinejs.mdx` from #9014
=> i18n(fr): Update `guides/integrations-guide/alpinejs.mdx` from #9014

src/content/docs/fr/guides/typescript.mdx
Update `guides/typescript.mdx` from #9011
=> i18n(fr): Update `guides/typescript.mdx` from #9011

src/content/docs/ko/guides/integrations-guide/alpinejs.mdx
- update `alpinejs.mdx`
- #9014
- Closes #
=> i18n(ko-KR): update `alpinejs.mdx`

src/content/docs/ko/guides/deploy/netlify.mdx
- update `netlify.mdx`
- #8952
- Closes #
=> i18n(ko-KR): update `netlify.mdx`

src/content/docs/fr/guides/integrations-guide/mdx.mdx
* Apply changes from #9027 to French translation of `integrations-guide/mdx.mdx`
=> i18n(fr): update `integrations-guide/mdx.mdx`

src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
=> i18n(zh-cn): Update `mdx.mdx`

src/content/docs/ko/guides/integrations-guide/mdx.mdx
- update `mdx.mdx`
- #9027
- Closes #
=> i18n(ko-KR): update `mdx.mdx`

src/content/docs/en/guides/client-side-scripts.mdx
=> Capitalized "javascript"

src/content/docs/en/guides/cms/craft-cms.mdx
This PR adds a new Community Resource link to the Craft CMS guide. The link is to a guide to building a static Astro site with data fetched dynamically in dev and once during build.
- Suggested label: add-new-content
=> Craft CMS guide: add SSG guide community resource

src/content/docs/fr/guides/cms/craft-cms.mdx
* Add new community resource link to French translation of `guides/cms/craft-cms.mdx` (see #9055)
=> i18n(fr): update `guides/cms/craft-cms.mdx`

src/content/docs/fr/reference/configuration-reference.mdx
* Apply changes from #9053 to French translation of `configuration-reference.mdx`
=> i18n(fr): update `configuration-reference.mdx`

src/content/docs/fr/guides/view-transitions.mdx
* Apply changes from #9017 to French translation of `guides/view-transitions.mdx`
* Fix typo in a code block title, see #9071
=> i18n(fr): update `guides/view-transitions.mdx`

src/content/docs/fr/guides/markdown-content.mdx
* Apply changes from #9074 to French translation of `guides/markdown-content.mdx`
=> i18n(fr): update `guides/markdown-content.mdx`

src/content/docs/ko/reference/errors/unknown-filesystem-error.mdx
- create `unknown-filesystem-error.mdx`
- #9081
- Closes #
=> i18n(ko-KR): create `unknown-filesystem-error.mdx`

src/content/docs/ko/reference/errors/get-entry-deprecation-error.mdx
- create `get-entry-deprecation-error.mdx`
- #9081
- Closes #
=> i18n(ko-KR): create `get-entry-deprecation-error.mdx`

src/content/docs/ko/basics/astro-syntax.mdx
- update `astro-syntax.mdx`
- #9082
- Closes #
=> i18n(ko-KR): update `astro-syntax.mdx`

src/content/docs/zh-cn/basics/astro-syntax.mdx
Update `astro-syntax.mdx`
- #9082 
=> i18n(zh-cn): Update `astro-syntax.mdx`

src/content/docs/fr/reference/integrations-reference.mdx
* Add changes from #9081 to French translation of `integrations-reference.mdx`
* Translate `Custom hooks` heading
* Add a missing space in a section already translated
=> i18n(fr): update `integrations-reference.mdx`

src/content/docs/fr/reference/cli-reference.mdx, src/content/docs/fr/reference/configuration-reference.mdx
* Add changes from #9081 to French translation of `cli-reference.mdx`
* Translate in French the `experimental.contentIntellisense` and `experimental.contentLayer` sections in `configuration-reference.mdx` (see #9081)
=> i18n(fr): update `cli-reference.mdx` & `configuration-reference.mdx`

src/content/docs/fr/guides/integrations-guide/netlify.mdx
* Fix an import statement (see #9162)
* Remove a heading (removed in an old PR, see #7375)
=> i18n(fr): update `integrations-guide/netlify.mdx`

src/content/docs/fr/guides/media.mdx, src/content/docs/fr/guides/media/cloudinary.mdx, src/i18n/fr/nav.ts, src/i18n/fr/ui.ts
* Add new pages and nav item from #9182:
* Add `guides/media.mdx`
* Add `guides/media/cloudinary.mdx`
* Update `i18n/fr/nav.ts`
* Update `i18n/fr/ui.ts`
Note: I had doubts about the translation of `stubs`, but [Wikipedia](https://fr.wikipedia.org/wiki/Bouchon_(informatique)) translates it with `bouchons` so I chose the same term.
=> i18n(fr): add `guides/media.mdx` & `guides/media/cloudinary.mdx`

src/content/docs/ko/guides/media/cloudinary.mdx
- create `cloudinary.mdx`
- Closes #
=> i18n(ko-KR): create `cloudinary.mdx`

src/content/docs/ko/guides/media.mdx
- create `media.mdx`
- Closes #
=> i18n(ko-KR): create `media.mdx`

src/content/docs/fr/reference/error-reference.mdx, src/content/docs/fr/reference/errors/actions-returned-invalid-data-error.mdx
* Add French translation for the new `actions-returned-invalid-data-error.mdx` file (see #9207)
* Update `error-reference.mdx` list
=> i18n(fr): add `actions-returned-invalid-data-error.mdx`

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
Added a link to my blog post about migrating a massive site which was too much for Gatsby and making it work with Astro. Think it has some interesting info for people in a similar situation.
=> Add another blog post on migrating Gatsby to Astro

src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx
* Add a new blog post in community resources (see #9205)
=> i18n(fr): update `migrate-to-astro/from-gatsby.mdx`

src/content/docs/ko/reference/errors/actions-returned-invalid-data-error.mdx
- create `actions-returned-invalid-data-error.mdx`
- Closes #
=> i18n(ko-KR): create `actions-returned-invalid-data-error.mdx`

src/i18n/pt-br/ui.ts
include missing entry in i18n/pt-br/ui.ts
=> i18n(pt-BR): Update `ui.ts` translation

src/i18n/pt-br/nav.ts
include missing entry in i18n/pt-br/nav.ts
=> i18n(pt-BR): Update `nav.ts` translation

src/content/docs/pt-br/guides/media.mdx
include missing i18n/pt-br/guides/media.mdx file
=> i18n(pt-BR): Translate `guides/media.mdx`

src/content/docs/pt-br/guides/typescript.mdx
Update the translation of i18n/guides/typescript.mdx
=> i18n(pt-BR): Update `guides/typescript.mdx` translation

src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
Update `from-gatsby.mdx`
- #9205 
=> i18n(zh-cn): Update `from-gatsby.mdx`

src/i18n/zh-cn/nav.ts, src/i18n/zh-cn/ui.ts
Update `ui.ts` & `nav.ts`
- #9182
=> i18n(zh-cn): Update `ui.ts` & `nav.ts`

astro.config.ts, package.json, pnpm-lock.yaml, src/content/docs/en/guides/actions.mdx, src/content/docs/en/guides/astro-db.mdx, src/content/docs/en/guides/internationalization.mdx, src/content/docs/en/guides/view-transitions.mdx, src/content/docs/en/reference/api-reference.mdx, src/content/docs/en/reference/configuration-reference.mdx, src/content/docs/en/reference/directives-reference.mdx, src/content/docs/en/reference/integrations-reference.mdx, src/i18n/en/nav.ts
Minor release docs for 4.15.0 which includes the following PRs:
#8955 
#8980 
#9084 
#9110 
#9130 
#9133 
#9216
=> 4.15.0 Minor release docs

src/content/docs/en/guides/actions.mdx
Small typo fix in the Astro Actions docs: `validaton` -> `validation` (notice the added `i`)
N/A
- Closes #
=> `actions.mdx`: fix small typo

src/content/docs/fr/guides/view-transitions.mdx, src/content/docs/fr/reference/api-reference.mdx
* Add Actions section in `api-reference.mdx` (see #9224 and #9254)
* Add View Transitions section in `api-reference.mdx` (see #9174)
* Add changes from #9261 to Actions `handler` in `api-reference.mdx`
* Add `Building a custom swap function` section in `guides/view-transitions.mdx` (see #9224, added to this PR to avoid a broken link)
=> i18n(fr): update `api-reference.mdx` and `guides/view-transitions.mdx`

src/content/docs/fr/guides/internationalization.mdx
* Add changes from #9224 to `Fallback` section in `guides/internationalization.mdx`
>[!IMPORTANT]
> The broken link should be fixed when #9246 is merged!
=> i18n(fr): update `guides/internationalization.mdx`

src/content/docs/fr/reference/error-reference.mdx, src/content/docs/fr/reference/errors/action-called-from-server-error.mdx, src/content/docs/fr/reference/errors/action-not-found-error.mdx, src/content/docs/fr/reference/errors/action-query-string-invalid-error.mdx, src/content/docs/fr/reference/errors/actions-returned-invalid-data-error.mdx, src/content/docs/fr/reference/errors/env-invalid-variable.mdx, src/content/docs/fr/reference/errors/invalid-rewrite404.mdx, src/content/docs/fr/reference/errors/locals-not-serializable.mdx, src/content/docs/fr/reference/errors/markdown-content-schema-validation-error.mdx
* Update Actions errors (see #9236)
* Add deprecated notice on some errors (see #9157)
> [!IMPORTANT]
> Both broken links should be fixed when #9260 is merged!
=> i18n(fr): update errors references

src/content/docs/fr/guides/astro-db.mdx
* Update French version of `guides/astro-db.mdx` with changes from #9224, #9243 and #9262
=> i18n(fr): update `guides/astro-db.mdx`

src/content/docs/fr/guides/integrations-guide/node.mdx, src/content/docs/fr/guides/integrations-guide/vercel.mdx
* Update `githubIntegrationURL` frontmatter property in `integrations-guide/node.mdx` and `integrations-guide/vercel.mdx` (see #9258 and #9257)
=> i18n(fr): update `githubIntegrationURL` in `node.mdx` & `vercel.mdx`

src/content/docs/ko/reference/errors/action-called-from-server-error.mdx, src/content/docs/ko/reference/errors/action-not-found-error.mdx, src/content/docs/ko/reference/errors/action-query-string-invalid-error.mdx, src/content/docs/ko/reference/errors/actions-returned-invalid-data-error.mdx
- update `errors/`
- #9236
- create `action-not-found-error.mdx`
- Closes #
=> i18n(ko-KR): update `errors/`

src/content/docs/ko/guides/integrations-guide/node.mdx
- update `node.mdx`
- #9258
- Closes #
=> i18n(ko-KR): update `node.mdx`

src/content/docs/fr/reference/error-reference.mdx
* Remove some errors from the list in `error-reference.mdx` (see #9284)
=> i18n(fr): update `error-reference.mdx`

src/content/docs/zh-cn/guides/integrations-guide/node.mdx, src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
update `vercel.mdx` & `node.ndx`
- https://github.com/withastro/docs/pull/9258
- https://github.com/withastro/docs/pull/9257
=> i18n(zh-cn): update `vercel.mdx` & `node.ndx`

src/content/docs/zh-cn/reference/directives-reference.mdx
update `directives-reference.mdx`
- https://github.com/withastro/docs/pull/9224
=> i18n(zh-cn): update `directives-reference.mdx`

src/content/docs/pt-br/guides/prefetch.mdx
update translation of i18n/guides/prefetch.mdx
=> i18n(pt-BR): Update `guides/prefetch.mdx` file

src/content/docs/en/guides/deploy/github.mdx, src/content/docs/es/guides/deploy/github.mdx, src/content/docs/fr/guides/deploy/github.mdx, src/content/docs/ko/guides/deploy/github.mdx, src/content/docs/zh-cn/guides/deploy/github.mdx
withastro/action has been upgraded to [v3](https://github.com/withastro/action/pull/58). If we still follow the current documentation to deploy to github, it will fail.
- Closes #
=> [i18nIgnore] update github deploy action for `github.mdx`

src/content/docs/zh-cn/guides/internationalization.mdx, src/content/docs/zh-cn/reference/cli-reference.mdx, src/content/docs/zh-cn/reference/configuration-reference.mdx
update `configuration-reference.mdx` & `internationalization.mdx`
- https://github.com/withastro/docs/pull/9224
- https://github.com/withastro/docs/pull/9237
- https://github.com/withastro/docs/pull/9274
=> i18n(zh-cn): update `configuration-reference.mdx` & `internationalization.mdx`

src/content/docs/pt-br/recipes/add-yaml-support.mdx
Create /pt-br/recipes/add-yaml-support-mdx file
=> i18n(pt-BR): Create `recipes/add-yaml-support.mdx`

src/content/docs/en/guides/internationalization.mdx
fix typo in  `internationalization.mdx`
- Closes #
=> fix typo in  `internationalization.mdx`

src/content/docs/en/reference/api-reference.mdx
=> feat(next): context.isPrerendered

src/i18n/pt-br/nav.ts
=> i18n(pt-BR): Update `nav.ts`

src/content/docs/fr/guides/client-side-scripts.mdx
=> i18n(fr): update `client-side-scripts.mdx`

src/content/docs/fr/tutorial/4-layouts/1.mdx
* Add changes from #9271
* Rephrase some sentences to avoid redundancy (`mise en page de page`)
* Rephrase a sentence referring to a file (`dans` seems more appropriate than `à`)
=> i18n(fr): update `tutorial/4-layouts/1.mdx`

src/content/docs/pt-br/reference/error-reference.mdx
Update i18n/pt-br/reference/error-reference.mdx
=> i18n(pt-BR): Update `reference/error-reference.mdx`

src/content/docs/zh-cn/guides/client-side-scripts.mdx
i18n(zh-cn): Update `client-side-scripts.mdx`
- #9314
=> i18n(zh-cn): Update `client-side-scripts.mdx`

src/content/docs/ko/guides/client-side-scripts.mdx
- update `client-side-scripts.mdx`
- #9314
- Closes #
=> i18n(ko-KR): update `client-side-scripts.mdx`

src/content/docs/ko/tutorial/4-layouts/1.mdx
- update `tutorial/4-layout/1.mdx`
- #9271
- Closes #
=> i18n(ko-KR): update `tutorial/4-layout/1.mdx`

src/content/docs/ko/guides/migrate-to-astro.mdx
- update `migrate-to-astro.mdx`
- #9344
- Closes #
=> i18n(ko-KR): update `migrate-to-astro.mdx`

src/content/docs/fr/guides/deploy/azion.mdx
* Translate Azion guide in French (see #9327)
> [!NOTE]
> I did not translate the terms in bold since they seem to me to be UI strings and Azion is not available in French!
=> i18n(fr): add `guides/deploy/azion.mdx`

src/content/docs/ko/guides/deploy/azion.mdx
- create `azion.mdx`
- Closes #
=> i18n(ko-KR): create `azion.mdx`

src/content/docs/en/guides/markdown-content.mdx
Wraps two pieces of existing content in "tips" for emphasis. (No change to the content itself, but one paragraph does move up higher in the section!)
Also removes a note with a link to content collections in preparation for content reorganizing.
=> Add call outs to Markdown page

src/content/docs/en/guides/upgrade-to/v5.mdx
https://github.com/withastro/astro/pull/11978
- Closes #
=> feat: injectRoute PR

src/content/docs/zh-cn/reference/errors/actions-used-with-for-get-error.mdx
Update `actions-used-with-for-get-error.mdx`
- #9165
=> i18n(zh-cn): Update `actions-used-with-for-get-error.mdx`

src/content/docs/en/reference/configuration-reference.mdx
Fixes broken Content Layer API RFC link.
=> Fix broken Content Layer API RFC link

scripts/docgen.mjs
Update the docgen script to point to the new types location.
=> Update github url for 5.0

src/content/docs/en/guides/middleware.mdx, src/content/docs/en/reference/api-reference.mdx
=> feat(next): overriden locals note

src/content/docs/zh-cn/basics/layouts.mdx, src/content/docs/zh-cn/guides/markdown-content.mdx, src/content/docs/zh-cn/guides/migrate-to-astro.mdx, src/content/docs/zh-cn/recipes/modified-time.mdx, src/content/docs/zh-cn/recipes/reading-time.mdx, src/content/docs/zh-cn/reference/api-reference.mdx, src/content/docs/zh-cn/tutorial/4-layouts/2.mdx
=> i18n(zh-cn): Update `layouts.mdx` & `markdown-content.mdx` & referenced links

src/content/docs/de/guides/deploy/deno.mdx, src/content/docs/en/guides/deploy/deno.mdx, src/content/docs/en/guides/integrations-guide/deno.mdx, src/content/docs/es/guides/deploy/deno.mdx, src/content/docs/es/guides/integrations-guide/deno.mdx, src/content/docs/fr/guides/deploy/deno.mdx, src/content/docs/fr/guides/integrations-guide/deno.mdx, src/content/docs/it/guides/deploy/deno.mdx, src/content/docs/ja/guides/deploy/deno.mdx, src/content/docs/ko/guides/deploy/deno.mdx, src/content/docs/ko/guides/integrations-guide/deno.mdx, src/content/docs/pt-br/guides/deploy/deno.mdx, src/content/docs/pt-br/guides/integrations-guide/deno.mdx, src/content/docs/zh-cn/guides/deploy/deno.mdx, src/content/docs/zh-cn/guides/integrations-guide/deno.mdx
change the maintainers astro to deno.
@deno/astro-adapter
https://github.com/denoland/deno-astro-adapter/issues/10#issuecomment-2084923656
- Closes #
=> rename @astrojs/deno to @deno/astro-adapter [i18nIgnore]

src/content/docs/en/getting-started.mdx, src/content/docs/en/guides/content-collections.mdx, src/content/docs/en/upgrade-astro.mdx
Add banners/callouts for 5.0 beta to 3 pages.
**After merging, update the beta branch, adding a commit to revert this pr**
=> Add 5.0 banners

src/content/docs/ko/getting-started.mdx
- update `getting-started.mdx`
- #9387
- Closes #
=> i18n(ko-KR): update `getting-started.mdx`

src/content/docs/en/guides/astro-db.mdx
- Add a "migrate to turso" recipe for Astro Studio users
=> Turso migration

src/content/docs/ko/upgrade-astro.mdx
- update `upgrade-astro.mdx`
- #9387
- Closes #
=> i18n(ko-KR): update `upgrade-astro.mdx`

src/content/docs/fr/getting-started.mdx, src/content/docs/fr/guides/content-collections.mdx, src/content/docs/fr/upgrade-astro.mdx
Add banners to French versions of `getting-started.mdx`, `update-astro.mdx` and `guides/content-collections.mdx`. (see #9387)
=> i18n(fr): add Astro 5 banners in French version

src/content/docs/en/reference/api-reference.mdx
- Update `input` type to be any `ZodType`
- Add subheading for input validation when accepting form inputs
- Add discriminated union example
- Closes #
=> Actions: add detailed form input validation reference

src/content/docs/hi/getting-started.mdx
Add Astro v5 banner to Hindi version of `getting-started.mdx`
Related issues
[9387](https://github.com/withastro/docs/pull/9387)
**NOTE WHEN MERGING**
**After merging, update the beta branch, adding a commit to revert this pr**
=> i18n(hi): add Astro v5 banner in Hindi

astro.config.ts
Fixes the editLink on pages to point to the beta branch on GitHub
- Closes #
=> Fix beta docs editLink base url

src/content/docs/pt-br/editor-setup.mdx
Update and review `i18n/pt-br/editor-setup.mdx` file
=> i18n(pt-BR): update `editor-setup.mdx`

src/content/docs/ko/guides/deploy/fleek.mdx
- create `fleek.mdx`
- Closes #
=> i18n(ko-KR): create `fleek.mdx`

src/content/docs/fr/guides/astro-db.mdx
Add changes from #9468 to French translation of `guides/astro-db.mdx`
=> i18n(fr): update `guides/astro-db.mx`

src/content/docs/fr/guides/deploy/fleek.mdx
Translate in French `guides/deploy/fleek.mdx` (see #9457 and #9471 for the ordered list numbering)
=> i18n(fr): add `guides/deploy/fleek.mdx`

src/content/docs/ko/guides/deploy/sst.mdx
- update `sst.mdx`
- #9475
- Closes #
=> i18n(ko-KR): update `sst.mdx`

src/content/docs/en/guides/content-collections.mdx
Removed the word "to": "This lets you ~~to~~ render HTML for things like links to your content (using the content `slug`) or information about your content (using the `data` property)."
- Closes #
=> Fix grammar in content-collections.mdx [i18nIgnore]

src/content/docs/fr/guides/deploy/sst.mdx
Add changes from #9475 and #9479 to French translation of `guides/deploy/sst.mdx`
=> i18n(fr): update `guides/deploy/sst.mdx`

src/content/docs/en/reference/integrations-reference.mdx
=> feat: createCodegenDir

src/content/docs/fr/reference/configuration-reference.mdx
Update `reference/configuration-reference.mdx` from #9487
=> i18n(fr): Update `reference/configuration-reference.mdx` from #9487

src/content/docs/ko/guides/deploy/clever-cloud.mdx
- create `clever-cloud.mdx`
- Closes #
=> i18n(ko-KR): create `clever-cloud.mdx`

src/content/docs/en/reference/container-reference.mdx
1. To add missing whitespace at L169 before `}`
1. To use multilines for >1 object property at L188, to match the code styles in other examples
1. To remove `"` for object properties at L188, L210, and L211
1. To remove redundant `,` at L211 and L226, to match the code styles in other examples
1. To use lowercased `x` in specifying custom header at L260
1. To add missing `;` at L314, L319, L325, and L330
1. To add missing code comment at L367, predicted by AI (feel free to update that if needed)
N/A
- Suggested label : `improve documentation`
=> docs: update container-reference.mdx

src/content/docs/fr/reference/image-service-reference.mdx
Update `reference/image-service-reference.mdx` from #9505
=> i18n(fr): Update `reference/image-service-reference.mdx` from #9505

src/content/docs/ko/reference/image-service-reference.mdx
- update `image-service-reference.mdx`
- #9505
- Closes #
=> i18n(ko-KR): update `image-service-reference.mdx`

src/content/docs/en/guides/client-side-scripts.mdx
Adds the recommended text provided by @sarah11918 from issue #9037
- Closes #9037 
- Suggested label: Add new content
=> Updates client-side-scripts.mdx

src/content/docs/en/guides/server-side-rendering.mdx
Updated the code under the Cookies section of the server-side-rendering page per issue #8612
- Closes #8612
=> Updates server-side-rendering.mdx

src/content/docs/fr/guides/client-side-scripts.mdx
Update `guides/client-side-scripts.mdx` from #9519
I'm participating to the Hacktoberfest!
=> i18n(fr): Update `guides/client-side-scripts.mdx` from #9519

src/content/docs/pt-br/tutorial/0-introduction/1.mdx
update i18n/pt-br/tutorial/0-introduction/1.mdx file
=> i18n(pt-BR): update `tutorial/0-introduction/1.mdx` file

src/content/docs/pt-br/tutorial/4-layouts/1.mdx, src/content/docs/pt-br/tutorial/4-layouts/2.mdx
update i18n/pt-br/tutorial/4-layout/1.mdx file
update i18n/pt-br/tutorial/4-layout/2.mdx file
=> i18n(pt-BR): update `tutorial/4-layout` files

src/components/tutorial/FeedbackButton.astro
This PR styles the feedback form's submit button as per Astro's [design standards](https://www.figma.com/file/GrDkcguAR7tSWPFuLVDixq/Theme---Starlight-Docs?type=design&node-id=454-34754&mode=design&t=FMXLtlWkDCNniwh2-4 ). It is discussed in detail in #8194.
- Closes #8194 
- Suggested label: design
=> Fix 'Submit Feedback' button style

src/content/docs/en/guides/routing.mdx, src/content/docs/en/guides/upgrade-to/v5.mdx
This PR documents a new behaviour that changed in Astro v5
=> feat: document decoding of params

src/content/docs/fr/recipes/modified-time.mdx
Translate the note added in #9520 in the French translation of `recipes/modified-time.mdx`.
=> i18n(fr): update `recipes/modified-time.mdx`

src/content/docs/ko/guides/migrate-to-astro/from-wordpress.mdx
- update `from-wordpress.mdx`
- #9576
- Closes #
=> i18n(ko-KR): update `from-wordpress.mdx`

src/content/docs/fr/guides/backend/supabase.mdx
Adds changes from #9541 to the French translation of `guides/backend/supabase.mdx`
=> i18n(fr): update `backend/supabase.mdx`

src/content/docs/fr/reference/publish-to-npm.mdx
* Renames `Collection` to `Categories` and adds other changes from #9571
* Adds a new category from #9598
* Adds changes from #3457 (it seems that this PR has been forgotten)
* Replaces all `Paquet` occurrences with `paquet` (it's not a proper noun)
=> i18n(fr): update `publish-to-npm.mdx`

src/content/docs/fr/guides/migrate-to-astro/from-wordpress.mdx
Adds new community resources (see #9576)
=> i18n(fr): update `migrate-to-astro/from-wordpress.mdx`

src/content/docs/pt-br/community-resources/talks.mdx
update i18n/pt-br/community-resources/talks.mdx file
=> i18n(pt-BR): update `community-resources/talks.mdx` file

src/content/docs/pt-br/tutorial/5-astro-api/1.mdx, src/content/docs/pt-br/tutorial/5-astro-api/2.mdx, src/content/docs/pt-br/tutorial/5-astro-api/4.mdx
update i18n/pt-br/tutorial/5-astro-api/1.mdx
update i18n/pt-br/tutorial/5-astro-api/2.mdx
update i18n/pt-br/tutorial/5-astro-api/4.mdx
=> i18n(pt-BR): update `tutorial/5-astro-api` files

src/content/docs/pt-br/reference/publish-to-npm.mdx
update i18n/pt-br/reference/publish-to-npm.mdx file
=> i18n(pt-BR): update `reference/publish-to-npm.mdx` file

src/content/docs/pt-br/guides/integrations-guide/vue.mdx
create i18n/pt-br/guides/integrations-guide/vue.mdx file
=> i18n(pt-BR): create `guides/integrations-guide/vue.mdx` file

src/content/docs/ko/guides/cms/builderio.mdx
- update `builderio.mdx`
- #9611
- Closes #
=> i18n(ko-KR): update `builderio.mdx`

src/content/docs/en/guides/markdown-content.mdx, src/content/docs/en/reference/configuration-reference.mdx
4.16.0 Minor release (aka the Toronto release)
Short and sweet!
Includes: 
- #9615 
- #9453
=> 4.16.0 Minor release docs

src/content/docs/zh-cn/guides/integrations-guide/sitemap.mdx
=> i18n(zh-cn): Update `sitemap.mdx`

src/content/docs/fr/guides/routing.mdx, src/content/docs/fr/reference/api-reference.mdx
* Updates French translations for `api-reference.mdx` and `guides/routing.mdx` (see #9488)
* Rephrases a comment in a code snippet of `guides/routing.mdx` that looks strange
=> i18n(fr): update `api-reference.mdx` and `guides/routing.mdx`

src/content/docs/fr/guides/integrations-guide/sitemap.mdx
Update `guides/integrations-guide/sitemap.mdx` from #8840
=> i18n(fr): Update `guides/integrations-guide/sitemap.mdx` from #8840

src/content/docs/fr/guides/cms/builderio.mdx
Update `guides/cms/builderio.mdx` from #9611
=> i18n(fr): Update `guides/cms/builderio.mdx` from #9611

src/content/docs/fr/guides/markdown-content.mdx
Update `guides/markdown-content.mdx` from #9618
=> i18n(fr): Update `guides/markdown-content.mdx` from #9618

src/content/docs/pt-br/recipes/build-custom-img-component.mdx
create i18n/pt-br/recipes/build-custom-img-component.mdx file
=> i18n(pt-BR): create `recipes/build-custom-img-component.mdx` file

src/content/docs/pt-br/recipes/build-forms.mdx
create i18n/pt-br/recipes/build-forms.mdx file
=> i18n(pt-BR): create `recipes/build-forms.mdx` file

src/content/docs/pt-br/recipes/bun.mdx
create i18n/pt-br/recipes/bun.mdx file
=> i18n(pt-BR): create `recipes/bun.mdx` file

src/content/docs/pt-br/recipes/streaming-improve-page-performance.mdx
create i18n/pt-br/recipes/streaming-improve-page-performance.mdx
=> i18n(pt-BR): create `recipes/streaming-improve-page-performance.mdx`

src/content/docs/en/guides/rss.mdx
Add links to the `@astrojs/rss` README for a complete configuration reference.
- Link from the step-by-step guide to call out all config options
- Link from the `items` rendering guide to call out the items reference
- Related: https://github.com/withastro/astro/pull/12157
=> RSS: Add config reference links

src/content/docs/pt-br/recipes/modified-time.mdx
create i18n/pt-br/recipes/modified-time.mdx
=> i18n(pt-BR): create `recipes/modified-time.mdx` file

src/content/docs/pt-br/guides/deploy/google-cloud.mdx, src/content/docs/pt-br/recipes/docker.mdx
create i18n/pt-br/recipes/docker.mdx file
=> i18n(pt-BR): create `recipes/docker.mdx` file

src/content/docs/zh-cn/reference/image-service-reference.mdx
Update `image-service-reference.mdx`
- #9505
=> i18n(zh-cn): Update `image-service-reference.mdx`

src/content/docs/ko/guides/cms/drupal.mdx
- create `drupal.mdx`
- Closes #
=> i18n(ko-KR): create `drupal.mdx`

src/content/docs/ko/guides/cms/umbraco.mdx
- update `umbraco.mdx`
- #9603
- Closes #
=> i18n(ko-KR): update `umbraco.mdx`

src/content/docs/zh-cn/guides/deploy/cloudflare.mdx
我看别的地方都写对了，就这边没写对，写成登陆了
- Closes #
=> i18n(zh-cn): fix typo in cloudflare.mdx

src/content/docs/en/guides/cms/drupal.mdx
* Update external links related to authentication (some of them led to a 404 error)
* Fix some typo
- Suggested label: typo/link/grammar and 3rd-party guide
=> fix: broken external links in `guides/cms/drupal.mdx`

src/content/docs/fr/guides/cms/drupal.mdx
* Translate in French the new Drupal guide (see #9492)
* Fix typo and external links (see #9682)
=> i18n(fr): add `guides/cms/drupal.mdx`

src/content/docs/zh-cn/guides/cms/umbraco.mdx
=> i18n(zh-cn): Update `umbraco.mdx`

src/content/docs/en/reference/container-reference.mdx
=> revert: commit `9776117`

src/content/docs/en/guides/media.mdx
Revised a sentence grammar in the 'headless DAM' sentence in the documentation for clarity.
The 'because' was confusing.
Yes ☺️ This is hopefully a valid hactoberfest update.
Do let me know if I have incorrectly labeled.
Many thanks,
Adam
=> Adam prendergast patch 1

src/content/docs/en/guides/astro-db.mdx
Update code snippet in `astro-db.mdx`
Before:
After:
- Closes #
=> Update code snippet in `astro-db.mdx`

src/content/docs/fr/guides/media/cloudinary.mdx
Adds changes from #9550 and #9659 to the French translation of `guides/media/cloudinary.mdx`
=> i18n(fr): update `guides/media/cloudinary.mdx`

src/content/docs/en/guides/cms/drupal.mdx
- Update the highlighter to show the line of code.
- Add some missing punctuation.
- Fix the ordinal number.
=> fix: syntax highlighting and ponctuation in `drupal.mdx`

src/content/docs/en/guides/migrate-to-astro/from-wordpress.mdx
Added link to Wordpress Migration Tool
- Closes #
- Suggested label: hacktoberfest-accepted
=> Updated community resources by adding link

src/content/docs/zh-cn/guides/media.mdx
=> i18n(zh-cn): Update `media.mdx`

src/content/docs/zh-cn/guides/migrate-to-astro/from-wordpress.mdx
Update `from-wordpress.mdx`
- #9721 
=> i18n(zh-cn): Update `from-wordpress.mdx`

src/i18n/de/nav.ts, src/i18n/en/nav.ts, src/i18n/zh-cn/nav.ts
#9465 merged and did not update language trackers for the new nav bar items. This is a trivial change so we can update status!
=> Update nav.ts for tracker

src/content/docs/en/tutorials/add-content-collections.mdx
Fix incorrect prop destructuring in tutorial example.
- Closes #
- Suggested label:  tutorial
=> Fix incorrect prop destructuring in tutorial

src/content/docs/fr/tutorials/add-view-transitions.mdx
Fixes line highlighting in a code snippet of `tutorials/add-view-transitions.mdx` (see #9749)
=> i18n(fr): fix line highlighting in `add-view-transitions.mdx`

src/content/docs/pt-br/guides/backend/turso.mdx
create i18n/pt-br/guides/backend/turso.mdx file
=> i18n(pt-BR): create `guides/backend/turso.mdx` file

src/content/docs/fr/guides/integrations-guide/markdoc.mdx
Update `guides/integrations-guide/markdoc.mdx` from #9776
I'm participating to the **Hacktoberfest 2024**!
=> i18n(fr): Update `guides/integrations-guide/markdoc.mdx` from #9776

src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
update `markdoc.mdx`
- https://github.com/withastro/docs/pull/9776
=> i18n(zh-cn): update `markdoc.mdx`

src/content/docs/en/guides/routing.mdx
Document the routes used internally by Astro that will override any user and integration routes.
- https://github.com/withastro/astro/pull/12263#pullrequestreview-2381408289
=> Document reserved routes

src/content/docs/fr/guides/routing.mdx
Update `guides/routing.mdx` from #9769
I'm participating to the **Hacktoberfest 2024**!
=> i18n(fr): Update `guides/routing.mdx` from #9769

src/content/docs/en/guides/routing.mdx
- fix typo in `routing.mdx`
- Closes #
=> fix: typo in `routing.mdx`

src/content/docs/zh-cn/guides/actions.mdx
update `actions.mdx`
- https://github.com/withastro/docs/pull/9781
=> i18n(zh-cn): update `actions.mdx`

src/content/docs/en/guides/deploy/fleek.mdx
The link in this current guide has a link that leads to a 404 page due to a recent docs update, but, this commit fixes that issue.
- Suggested label: typo/link/grammar
=> feat: update fleek.mdx link

src/content/docs/en/reference/modules/astro-actions.mdx
- remove unused link in `astro-actions.mdx`
- Closes #
=> fix: remove unused link in `astro-actions.mdx`

src/content/docs/en/reference/modules/astro-assets.mdx
- fix wrong link in `astro-assets.mdx`
- Closes #
=> fix: update wrong link in `astro-assets.mdx`

src/content/docs/ko/guides/deploy/fleek.mdx
- update `fleek.mdx`
- #9800
- Closes #
=> i18n(ko-KR): update `fleek.mdx`

src/content/docs/ko/guides/internationalization.mdx
- update `internationalization.mdx`
- #9687
- Closes #
=> i18n(ko-KR): update `internationalization.mdx`

src/content/docs/ko/reference/modules/astro-i18n.mdx
- create `astro-i18n.mdx`
- Closes #
=> i18n(ko-KR): create `astro-i18n.mdx`

src/content/docs/ko/reference/modules/astro-middleware.mdx
- create `astro-middleware.mdx`
- Closes #
=> i18n(ko-KR): create `astro-middleware.mdx`

src/content/docs/ko/reference/modules/astro-transitions.mdx
- create `astro-transitions.mdx`
- Closes #
=> i18n(ko-KR): create `astro-transitions.mdx`

src/content/docs/ko/reference/modules/astro-actions.mdx
- create `astro-actions.mdx`
- #9819
- Closes #
=> i18n(ko-KR): create `astro-actions.mdx`

src/content/docs/ko/reference/modules/astro-assets.mdx
- create `astro-assets.mdx`
- #9820
- Closes #
=> i18n(ko-KR): create `astro-assets.mdx`

src/content/docs/ko/reference/modules/astro-content.mdx
- create `astro-content.mdx`
- #9821
- Closes #
=> i18n(ko-KR): create `astro-content.mdx`

src/content/docs/ko/reference/errors/actions-returned-invalid-data-error.mdx
- update `actions-returned-invalid-data-error.mdx`
- #9687
- Closes #
=> i18n(ko-KR): update `actions-returned-invalid-data-error.mdx`

src/i18n/ja/nav.ts
=> i18n(ja): Update nav.ts

src/content/docs/ja/guides/content-collections.mdx
- Update content-collections.mdx.
- https://github.com/withastro/docs/pull/9387
=> i18n(ja): Update content-collections.mdx

src/content/docs/pt-br/guides/deploy/fleek.mdx
update link in i18n docs/pt-br/guides/deploy/fleek.mdx file
=> i18n(pt-BR): update link in `fleek.mdx`

src/content/docs/ko/reference/errors/missing-sharp.mdx
- update `missing-sharp.mdx`
- #9801
- Closes #
=> i18n(ko-KR): update `missing-sharp.mdx`

src/content/docs/zh-cn/reference/errors/missing-sharp.mdx
Update `missing-sharp.mdx`
- #9801 
=> i18n(zh-cn): Update `missing-sharp.mdx`

src/content/docs/ko/reference/modules/astro-assets.mdx
- update `astro-assets.mdx`
- #9801
- Closes #
=> i18n(ko-KR): update `astro-assets.mdx`

src/content/docs/ko/guides/migrate-to-astro/from-nextjs.mdx
- update `from-nextjs.mdx`
- #9801
- Closes #
=> i18n(ko-KR): update `from-nextjs.mdx`

src/content/docs/ko/reference/errors/image-missing-alt.mdx
- update `image-missing-alt.mdx`
- #9801
- Closes #
=> i18n(ko-KR): update `image-missing-alt.mdx`

src/content/docs/ko/reference/errors/missing-image-dimension.mdx
- update `missing-image-dimension.mdx`
- #9801
- Closes #
=> i18n(ko-KR): update `missing-image-dimension.mdx`

src/content/docs/zh-cn/tutorial/4-layouts/1.mdx
Update `4-layouts/1.mdx`
- #9882 
=> i18n(zh-cn): Update `4-layouts/1.mdx`

src/content/docs/zh-cn/guides/cms/craft-cms.mdx
Update `craft-cms.mdx`
- #9899 
=> i18n(zh-cn): Update `craft-cms.mdx`

src/content/docs/fr/guides/cms/craft-cms.mdx
Updates the title of `guides/cms/craft-cms.mdx` in the French translation to be consistent with other CMS guides (see #9899)
=> i18n(fr): update title of `guides/cms/craft-cms.mdx`

src/content/docs/ko/guides/cms/craft-cms.mdx
- update `craft-cms.mdx`
- #9899
- Closes #
=> i18n(ko-KR): update `craft-cms.mdx`

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Hacktoberfest is over! Reverts withastro/docs#9517
=> Revert "Add Hacktoberfest note in PR template and in the contributing file"

src/content/i18n-schema.ts, src/content/i18n/ar.yml, src/content/i18n/de.yml, src/content/i18n/en.yml, src/content/i18n/es.yml, src/content/i18n/fr.yml, src/content/i18n/hi.yml, src/content/i18n/it.yml, src/content/i18n/ja.yml, src/content/i18n/ko.yml, src/content/i18n/pl.yml, src/content/i18n/pt-BR.yml, src/content/i18n/ru.yml, src/content/i18n/zh-CN.yml, src/content/i18n/zh-TW.yml
> [!note]
> These changes target Chris' PR: #9896
This PR fixes an ["issue" I mentioned in Chris' PR](https://github.com/withastro/docs/pull/9896#issuecomment-2456897026). It:
* Removes the unused keys in the translation files (it seems to me that the english one is already up to date)
* Fixes a typo `voccabulary` >  `vocabulary`  (a remnant of the previous file)
@delucis I had started to create comments to suggest the lines to delete... Finally I told myself that a PR would be faster! And less “polluting” (3 comments per file... 39 comments in total 😅 ).
=> fix: consistent translation files in PR #9896

src/content/docs/fr/guides/troubleshooting.mdx
[i18n(fr): Update](https://github.com/withastro/docs/commit/4b17ed5aa1f1c824b0f8da487603eacb1151fcfc) [guides/troubleshooting.mdx](https://github.com/withastro/docs/commit/4b17ed5aa1f1c824b0f8da487603eacb1151fcfc) [from](https://github.com/withastro/docs/commit/4b17ed5aa1f1c824b0f8da487603eacb1151fcfc) https://github.com/withastro/docs/pull/9888
=> i18n(fr): Update `guides/troubleshooting.mdx` from #9888

src/content/docs/fr/community-resources/content.mdx
[i18n(fr): Update](https://github.com/withastro/docs/commit/ccc8ff32fbeecbcfe89fbc5d463a7685d4cde313) [community-resources/content.mdx](https://github.com/withastro/docs/commit/ccc8ff32fbeecbcfe89fbc5d463a7685d4cde313) [from](https://github.com/withastro/docs/commit/ccc8ff32fbeecbcfe89fbc5d463a7685d4cde313) https://github.com/withastro/docs/pull/9900
=> i18n(fr): Update `community-resources/content.mdx` from #9900

src/content/docs/fr/basics/astro-syntax.mdx
[i18n(fr): Update](https://github.com/withastro/docs/commit/75082542793389e2e99d7e2e162d784a339ef723) [basics/astro-syntax.mdx](https://github.com/withastro/docs/commit/75082542793389e2e99d7e2e162d784a339ef723) [from](https://github.com/withastro/docs/commit/75082542793389e2e99d7e2e162d784a339ef723) https://github.com/withastro/docs/pull/9888
=> i18n(fr): Update `basics/astro-syntax.mdx` from #9888

src/content/docs/fr/guides/markdown-content.mdx, src/content/docs/fr/guides/upgrade-to/v1.mdx
[i18n(fr): Update](https://github.com/withastro/docs/commit/45c79871ea60540ce9947f2829c18ffc1ea1ef72) [guides/markdown-content.mdx](https://github.com/withastro/docs/commit/45c79871ea60540ce9947f2829c18ffc1ea1ef72) [from](https://github.com/withastro/docs/commit/45c79871ea60540ce9947f2829c18ffc1ea1ef72) https://github.com/withastro/docs/pull/9888
> [!NOTE]
> Merge #9934 before this one. Links are broken.
=> i18n(fr): Update `guides/markdown-content.mdx` from #9888

src/content/docs/zh-cn/recipes/bun.mdx
Update `bun.mdx`
- add missing link
- update outdated headings, description and code block
- #9913 
=> i18n(zh-cn): Update `bun.mdx`

src/content/docs/fr/recipes/bun.mdx
Adds a new community resource in the French translation of `recipes/bun.mdx` (see #9913)
=> i18n(fr): update `recipes/bun.mdx`

src/i18n/de/nav.ts
- update `nav.ts`
- #9888 
- #9900 
- Closes #
=> i18n(de): update `nav.ts`

src/content/docs/en/tutorial/6-islands/3.mdx
Add a button to share tutorial achievement on Bluesky
- Closes # #9968 
- Suggested label:  add new content
=> Add a button to share tutorial achievement on Bluesky

src/content/docs/zh-cn/tutorial/6-islands/3.mdx
=> i18n(zh-cn): Update `3.mdx`

src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx
Update `alpinejs.mdx`
- #9944 
=> i18n(zh-cn): Update `alpinejs.mdx`

src/content/docs/en/recipes/streaming-improve-page-performance.mdx
This pull request includes a small change to `src/content/docs/en/recipes/streaming-improve-page-performance.mdx` file. The change updated the code to personData.results[0].name.first to correctly access the first name of the first item within the results array. This change aligns with the actual structure of the returned data, allowing the code to work as intended.
This [link](https://stackblitz.com/edit/withastro-astro-4kjfro?file=src%2Fpages%2Findex.astro) shows both the current approach and the proposed one:
- `src/pages/index.astro` contains the proposed working code.
- `src/pages/current.astro` contains the current/original code throwing an error.
I checked all the other code snippets in this page and they all work fine.
- Closes #
I could not find any.
"code …
=> Update code snippet in streaming-improve-page-performance.mdx

src/content/docs/fr/tutorial/6-islands/3.mdx
Updates the French translation of `tutorial/6-islands/3.mdx`:
* Adds a "Share with Bluesky" button (see #9969)
* Translates the "Share with" buttons
* Fixes the `src/pages/about.astro` code snippet: the variable names were translated whereas they are not on the other pages (e.g. https://docs.astro.build/fr/tutorial/2-pages/3/) and due to the translation the example was invalid (missing quotes around `passe-temps` for example). So, to be consistent, I put the names back in their English version.
=> i18n(fr): update `tutorial/6-islands/3.mdx`

src/content/docs/zh-cn/recipes/streaming-improve-page-performance.mdx
Update `streaming-improve-page-performance.mdx`
- #9979 
=> i18n(zh-cn): Update `streaming-improve-page-performance.mdx`

src/content/docs/ko/tutorial/6-islands/3.mdx
- update `/tutorial/6-islands/3.mdx`
- #9969
- Closes #
=> i18n(ko-KR): update `/tutorial/6-islands/3.mdx`

src/content/docs/ko/guides/cms/hashnode.mdx
- update `hashnode.mdx`
- #10003
- Closes #
=> i18n(ko-KR): update `hashnode.mdx`

src/content/docs/ko/guides/actions.mdx
- update `actions.mdx`
- #10005
- Closes #
=> i18n(ko-KR): update `actions.mdx`

src/content/docs/zh-cn/guides/cms/hashnode.mdx
Update `hashnode.mdx`
- #10003 
=> i18n(zh-cn): Update `hashnode.mdx`

src/content/docs/fr/recipes/i18n.mdx
Adds a new community resource in the French translation of `recipes/i18n.mdx` (see #9780)
=> i18n(fr): update `recipes/i18n.mdx`

src/content/docs/fr/guides/actions.mdx
Translates in French the new section of `guides/actions.mdx` added in #10005
=> i18n(fr): update `guides/actions.mdx`

src/content/docs/fr/guides/cms/hashnode.mdx
Adds changes from #10003 to the French translation of `guides/cms/hashnode.mdx`.
=> i18n(fr): update `guides/cms/hashnode.mdx`

src/content/docs/ko/recipes/analyze-bundle-size.mdx
- create `analyze-bundle-size.mdx`
- Closes #
=> i18n(ko-KR): create `analyze-bundle-size.mdx`

.github/workflows/ci.yml, .github/workflows/lunaria.yml
Run CI & Lunaria on all pull requests.
=> Run CI on all PRs

src/content/docs/en/community-resources/content.mdx
Adding a community recipe : streaming a file, using an actual stream to avoid bloating the RAM by copying the file.
- Closes #
=> Add file streaming community recipe

src/content/docs/fr/guides/view-transitions.mdx
Update `guides/view-transitions.mdx` from #10038
- Closes #
=> i18n(fr): Update `guides/view-transitions.mdx` from #10038

package.json, pnpm-lock.yaml
This PR updates some of our dependencies, cherry picking a commit initially made as part of #9890 to get those updates available generally.
=> Update Astro, Starlight, Astro check + sitemap integration

src/content/docs/en/tutorial/1-setup/2.mdx, src/content/docs/en/tutorial/3-components/4.mdx, src/content/docs/en/tutorial/5-astro-api/1.mdx, src/content/docs/en/tutorial/5-astro-api/2.mdx, src/content/docs/en/tutorial/5-astro-api/3.mdx, src/content/docs/en/tutorial/6-islands/4.mdx, src/content/docs/en/tutorial/7-collections/index.mdx
> [!warning]
> This PR targets Sarah's PR #10035!
Following the discussion in #10025, this PR:
* Generalizes instructions for `create astro` in Unit 1
* Fixes Typescript error (`ts(2531)`) in Unit 3
* Fixes Typescript errors (`ts(18046)`) in Unit 5
* Fixes Typescript error (`ts(7006)`)  in Unit 5
* Removes `astro sync` command in Unit 7 and extended Unit 6
* Adds missing import for `render` in Unit 7 and extended Unit 6
Note for @sarah11918: I didn't directly suggest the changes on your PR since I can't add suggestions on unmodified parts. And it might be easier to review.
Except, my point 8, I think I covered everything. But:
* I still think there might be an "issue" with point 8 so **before merging**, please [read my detailed explanation](https://github.com/withastro/docs/issues/10025#is …
=> fix(v5): update tutorial

src/content/docs/zh-cn/guides/authentication.mdx
Update authentication.mdx
- https://github.com/withastro/docs/pull/10064
=> i18n(zh-cn): Update authentication.mdx

src/content/docs/zh-cn/reference/error-reference.mdx, src/content/docs/zh-cn/reference/errors/env-unsupported-get-secret.mdx
Update error-reference
- https://github.com/withastro/docs/pull/10071
=> i18n(zh-cn): Update error-reference

src/content/docs/ko/reference/errors/env-unsupported-get-secret.mdx
- update `env-unsupported-get-secret.mdx`
- #10071
- Closes #
=> i18n(ko-KR): update `env-unsupported-get-secret.mdx`

src/content/docs/en/guides/integrations-guide/mdx.mdx, src/content/docs/fr/guides/integrations-guide/mdx.mdx, src/content/docs/ko/guides/integrations-guide/mdx.mdx, src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
resolves incorrect module referred extending discussions from #10065
- Closes #9985
=> [i18ignore] fix incorrect module in `mdx.mdx`

src/content/docs/de/editor-setup.mdx
- update `editor-setup.mdx`
- #6532 
- #8238 
- #8563 
- #9073
=> i18n(de): Update `editor-setup.mdx`

src/content/docs/zh-cn/recipes/analyze-bundle-size.mdx
Add `analyze-bundle-size.mdx`
- #9974 
=> i18n(zh-cn): Add `analyze-bundle-size.mdx`

src/content/docs/en/concepts/islands.mdx
[Katie Sylor-Miller's Twitter](https://twitter.com/ksylor) doesn't seem to exist anymore, so I replace the link with [her website](https://sylormiller.com/).
=> fix: Replace the link to the non-existent Twitter account with a new link

src/content/docs/de/concepts/islands.mdx
- update `concepts/islands.mdx`
- #10088
=> i18n(de): update `concepts/islands.mdx`

src/content/docs/fr/concepts/islands.mdx
Updates an outdated link in the French translation of `concepts/islands.mdx` (see #10088)
=> i18n(fr): update link in `concepts/islands.mdx`

src/content/docs/en/editor-setup.mdx, src/content/docs/en/guides/cms/builderio.mdx, src/content/docs/en/guides/migrate-to-astro/from-docusaurus.mdx, src/content/docs/en/guides/migrate-to-astro/from-eleventy.mdx, src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/en/guides/migrate-to-astro/from-gitbook.mdx, src/content/docs/en/guides/migrate-to-astro/from-gridsome.mdx, src/content/docs/en/guides/migrate-to-astro/from-hugo.mdx, src/content/docs/en/guides/migrate-to-astro/from-jekyll.mdx, src/content/docs/en/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/en/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/en/guides/migrate-to-astro/from-pelican.mdx, src/content/docs/en/guides/migrate-to-astro/from-sveltekit.mdx, src/content/docs/en/guides/migrate-to-astro/from-vuepress.mdx, src/content/docs/en/guides/migrate-to-astro/from-wordpress.mdx, src/content/docs/en/tutorial/0-introduction/index.mdx, src/content/docs/en/tutorial/1-setup/5.mdx, src/content/docs/en/tutorial/1-setup/index.mdx, src/content/docs/en/tutorial/6-islands/3.mdx
This PR adds IDX instructions for the tutorial, and also updates places where we list which online options are available from astro.new
=> updates for IDX content

src/content/docs/en/install-and-setup.mdx
Gotta keep up with Node!
This would follow our pattern for documenting current prerequisite versions of Node. Edit as necessary!
=> Update supported versions of Node

src/content/docs/en/guides/migrate-to-astro/from-create-react-app.mdx
typo in `from-create-react-app.mdx`
- Closes #
=> fix: typo in `from-create-react-app.mdx`

src/content/docs/en/guides/migrate-to-astro/from-gridsome.mdx
typo in `from-gridsome.mdx`
- Closes #
=> fix: typo in `from-gridsome.mdx`

src/content/docs/fr/reference/dev-toolbar-app-reference.mdx
Adds changes from #9240 to the French translation of `reference/dev-toolbar-app-reference.mdx`.
=> i18n(fr): update `reference/dev-toolbar-app-reference.mdx`

src/content/docs/fr/reference/astro-syntax.mdx
Adds changes from #9240 to the French translation of `reference/astro-syntax.mdx`.
=> i18n(fr): update `reference/astro-syntax.mdx`

src/content/docs/ko/develop-and-build.mdx
- create `develop-and-build.mdx`
- #9240
- #10214
- Closes #
=> i18n(ko-KR): create `develop-and-build.mdx`

src/content/docs/zh-cn/tutorial/0-introduction/1.mdx
Update `0-introduction/1.mdx`
Note: To change the status of translation tracker, I commit a letter space, so we can use it happily.
- Closes #
=> i18n(zh-cn): Update `0-introduction/1.mdx`

src/content/docs/en/guides/markdown-content.mdx
=> Fix call of render function in doc example

src/content/docs/ko/reference/content-loader-reference.mdx, src/content/docs/ko/reference/modules/astro-content.mdx
- create `content-loader-reference.mdx`
- update `astro-content.mdx`
- #9240
- Closes #
=> i18n(ko-KR): create `content-loader-reference.mdx` and `astro-content.mdx`

src/content/docs/fr/guides/deploy/aws.mdx, src/content/docs/fr/guides/deploy/azion.mdx, src/content/docs/fr/guides/deploy/buddy.mdx, src/content/docs/fr/guides/deploy/cleavr.mdx, src/content/docs/fr/guides/deploy/clever-cloud.mdx, src/content/docs/fr/guides/deploy/cloudflare.mdx, src/content/docs/fr/guides/deploy/deno.mdx, src/content/docs/fr/guides/deploy/edgio.mdx, src/content/docs/fr/guides/deploy/fleek.mdx, src/content/docs/fr/guides/deploy/flightcontrol.mdx, src/content/docs/fr/guides/deploy/flyio.mdx, src/content/docs/fr/guides/deploy/github.mdx, src/content/docs/fr/guides/deploy/gitlab.mdx, src/content/docs/fr/guides/deploy/google-cloud.mdx, src/content/docs/fr/guides/deploy/google-firebase.mdx, src/content/docs/fr/guides/deploy/heroku.mdx, src/content/docs/fr/guides/deploy/index.mdx, src/content/docs/fr/guides/deploy/kinsta.mdx, src/content/docs/fr/guides/deploy/microsoft-azure.mdx, src/content/docs/fr/guides/deploy/netlify.mdx, src/content/docs/fr/guides/deploy/render.mdx, src/content/docs/fr/guides/deploy/sst.mdx, src/content/docs/fr/guides/deploy/stormkit.mdx, src/content/docs/fr/guides/deploy/surge.mdx, src/content/docs/fr/guides/deploy/vercel.mdx, src/content/docs/fr/guides/deploy/zeabur.mdx, src/content/docs/fr/guides/deploy/zerops.mdx
Update `guides/deploy/*` from #9240
=> i18n(fr): Update `guides/deploy/*` from #9240

src/content/docs/fr/guides/media/cloudinary.mdx, src/content/docs/fr/guides/media/index.mdx
Update `guides/media/*` from #9240 :
=> i18n(fr): Update `guides/media/*` from #9240

src/content/docs/fr/tutorial/0-introduction/1.mdx, src/content/docs/fr/tutorial/0-introduction/index.mdx, src/content/docs/fr/tutorial/1-setup/2.mdx, src/content/docs/fr/tutorial/1-setup/5.mdx, src/content/docs/fr/tutorial/1-setup/index.mdx, src/content/docs/fr/tutorial/2-pages/3.mdx, src/content/docs/fr/tutorial/2-pages/4.mdx, src/content/docs/fr/tutorial/2-pages/5.mdx, src/content/docs/fr/tutorial/3-components/4.mdx, src/content/docs/fr/tutorial/5-astro-api/1.mdx, src/content/docs/fr/tutorial/5-astro-api/2.mdx, src/content/docs/fr/tutorial/5-astro-api/3.mdx, src/content/docs/fr/tutorial/5-astro-api/4.mdx, src/content/docs/fr/tutorial/5-astro-api/index.mdx, src/content/docs/fr/tutorial/6-islands/2.mdx, src/content/docs/fr/tutorial/6-islands/3.mdx, src/content/docs/fr/tutorial/6-islands/4.mdx, src/content/docs/fr/tutorial/6-islands/index.mdx
Updates the French translation of the tutorial with changes from #9240, #10223, #10332 and #10342
=> i18n(fr): update `tutorial/*`

src/content/docs/ko/guides/cms/cloudcannon.mdx
- update `cloudcannon.mdx`
- #10335
- Closes #
=> i18n(ko-KR): update `cloudcannon.mdx`

src/content/docs/fr/install-and-setup.mdx
Updates the French translation of `install-and-setup.mdx` (see #9240, #10144 and #10303)
=> i18n(fr): update `install-and-setup.mdx`

src/content/docs/ko/tutorial/6-islands/4.mdx
- update `tutorial/6-islands/4.mdx`
- #10347
- Closes #
=> i18n(ko-KR): update `tutorial/6-islands/4.mdx`

src/content/docs/fr/recipes/analyze-bundle-size.mdx, src/content/docs/fr/recipes/build-forms-api.mdx, src/content/docs/fr/recipes/build-forms.mdx, src/content/docs/fr/recipes/bun.mdx, src/content/docs/fr/recipes/call-endpoints.mdx, src/content/docs/fr/recipes/captcha.mdx, src/content/docs/fr/recipes/docker.mdx, src/content/docs/fr/recipes/i18n.mdx, src/content/docs/fr/recipes/index.mdx, src/content/docs/fr/recipes/rss.mdx, src/content/docs/fr/recipes/sharing-state-islands.mdx, src/content/docs/fr/recipes/sharing-state.mdx
Updates the French translations of the `recipes` with changes from #9240
=> i18n(fr): update all the `recipes`

src/content/docs/fr/editor-setup.mdx, src/content/docs/fr/getting-started.mdx
Adds changes from #9240 to the French translations of:
* `getting-started.mdx` (description and banner, the rest is already up to date)
* `editor-setup.mdx` (IDX link, the rest is already up to date)
=> i18n(fr): update `getting-started.mdx` and `editor-setup.mdx`

src/content/docs/pt-br/reference/errors/server-only-module.mdx
translate content i18n pt-br/reference/errors/server-only-module.mdx
=> i18n(pt-BR): create `reference/errors/server-only-module.mdx`

src/content/docs/pt-br/reference/errors/route-not-found.mdx
translate content i18n pt-br/reference/errors/route-not-found.mdx
=> i18n(pt-BR): create `reference/errors/route-not-found.mdx`

src/content/docs/pt-br/reference/errors/rewrite-encountered-an-error.mdx
translate content i18n pt-br/reference/errors/rewrite-encountered-an-error.mdx
=> i18n(pt-BR): create `reference/errors/rewrite-encountered-an-error.mdx`

src/content/docs/pt-br/reference/errors/content-entry-data-error.mdx
translate content i18n pt-br/reference/errors/content-entry-data-error.mdx
=> i18n(pt-BR): create `reference/errors/content-entry-data-error.mdx`

src/content/docs/pt-br/reference/errors/invalid-content-entry-data-error.mdx
translate content i18n pt-br/reference/errors/invalid-content-entry-data-error.mdx
=> i18n(pt-BR): create `reference/errors/invalid-content-entry-data-error.mdx`

src/content/docs/pt-br/reference/errors/forbidden-rewrite.mdx
translate content i18n pt-br/reference/errors/forbidden-rewrite.mdx
=> i18n(pt-BR): create `reference/errors/forbidden-rewrite.mdx`

src/content/docs/zh-cn/guides/configuring-astro.mdx
Update `configuring-astro.mdx`
- #9240 
=> i18n(zh-cn): Update `configuring-astro.mdx`

src/content/docs/zh-cn/guides/backend/appwriteio.mdx, src/content/docs/zh-cn/guides/backend/google-firebase.mdx, src/content/docs/zh-cn/guides/backend/index.mdx, src/content/docs/zh-cn/guides/backend/neon.mdx, src/content/docs/zh-cn/guides/backend/sentry.mdx, src/content/docs/zh-cn/guides/backend/supabase.mdx, src/content/docs/zh-cn/guides/backend/turso.mdx, src/content/docs/zh-cn/guides/backend/xata.mdx
Update backend pages
- https://github.com/withastro/docs/pull/9240/
=> i18n(zh-cn): Update backend pages

src/content/docs/pt-br/guides/deploy/fleek.mdx
update file i18n pt-br/guides/deploy/fleek.mdx
=> i18n(pt-BR): update `guides/deploy/fleek.mdx`

src/content/docs/pt-br/guides/cms/sanity.mdx
translate content i18n pt-br/guides/cms/sanity.mdx
=> i18n(pt-BR): create `guides/cms/sanity.mdx`

src/content/docs/fr/tutorial/6-islands/4.mdx
Fixes a code snippet in the French translation of `tutorial/6-islands/4.mdx` (see #10347)
=> i18n(fr): fix code snippet in `tutorial/6-islands/4.mdx`

src/content/docs/fr/recipes/rss.mdx
Fixes two code snippets in the French translation of `recipes/rss.mdx` (see #10367)
=> i18n(fr): update code snippets in `recipes/rss.mdx`

src/content/docs/ko/guides/on-demand-rendering.mdx
- update `on-demand-rendering.mdx`
- #10418
- Closes #
=> i18n(ko-KR): update `on-demand-rendering.mdx`

src/content/docs/ko/guides/server-islands.mdx
- update `server-islands.mdx`
- #10418
- Closes #
=> i18n(ko-KR): update `server-islands.mdx`

src/content/docs/ko/guides/syntax-highlighting.mdx
- update `syntax-highlighting.mdx`
- #10419
- Closes #
=> i18n(ko-KR): update `syntax-highlighting.mdx`

src/content/docs/ko/guides/upgrade-to/v5.mdx
- update `v5.mdx`
- #10370
- Closes #
=> i18n(ko-KR): update `v5.mdx`

src/content/docs/fr/guides/upgrade-to/v5.mdx
Updates the French translation of `guides/upgrade-to/v5.mdx` with changes from #10370
=> i18n(fr): update `guides/upgrade-to/v5.mdx`

src/content/docs/fr/guides/framework-components.mdx
Updates the French translation of `guides/framework-components.mdx` with changes from #9240
=> i18n(fr): update `guides/framework-components.mdx`

src/content/docs/fr/guides/client-side-scripts.mdx
* Updates the French translation of `guides/client-side-scripts.mdx` with changes from #9240
* Fixes a typo
=> i18n(fr): update `guides/client-side-scripts.mdx`

src/content/docs/ko/reference/modules/astro-actions.mdx
- update `astro-actions.mdx`
- #10447
- Closes #
=> i18n(ko-KR): update `astro-actions.mdx`

src/content/docs/en/reference/experimental-flags/sessions.mdx
- fix typo in `session.mdx`
- Closes #
=> fix wrong casing name in `sessions.mdx`

src/content/docs/en/guides/integrations-guide/index.mdx
When I translated the `guides/integration-guide/index.mdx` page I noticed some "inconsistencies" (mostly missing dots and Steps) but maybe it's intended not to use Steps in some scenarios. Please let me know if you would like to have such changes, I can delete some changes if only the missing dots are what you wish for!
=> feat(`integration-guide`): make some changes to the `guides/integration-guide/index.mdx`

src/content/docs/en/guides/images.mdx
- update link in `images.mdx`
- Closes #
=> fix: update link in `images.mdx`

src/content/docs/en/reference/cli-reference.mdx
This PR adds a small explanation for the `--force` flag
=> feat: add `--force` flag doc

src/content/docs/fr/guides/integrations-guide/index.mdx
Update `guides/integrations-guide/index.mdx` from #10448
=> i18n(fr): Update `guides/integrations-guide/index.mdx` from #10448

src/content/docs/fr/tutorial/3-components/1.mdx
Update `tutorial/3-components/1.mdx` from #10476 
> [!NOTE]
> Nothing changed, but removing Blanks component and add a little space
=> i18n(fr): Update `tutorial/3-components/1.mdx` from #10476 

src/content/docs/fr/guides/images.mdx
Updates a link referring to the same page in the French translation of `guides/images.mdx` (see #10482)
=> i18n(fr): update link in `guides/images.mdx`

src/content/docs/fr/reference/cli-reference.mdx
Adds the new `--force` section in the French translation of `cli-reference.mdx` (see #10489)
=> i18n(fr): update `cli-reference.mdx`

src/content/docs/zh-cn/guides/cms/contentful.mdx
Update `contentful.mdx`
- #9240
=> i18n(zh-cn): Update `contentful.mdx`

src/content/docs/zh-cn/reference/errors/action-called-from-server-error.mdx, src/content/docs/zh-cn/reference/errors/client-address-not-available.mdx, src/content/docs/zh-cn/reference/errors/get-static-paths-expected-params.mdx, src/content/docs/zh-cn/reference/errors/get-static-paths-invalid-route-param.mdx, src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx, src/content/docs/zh-cn/reference/errors/i18n-not-enabled.mdx, src/content/docs/zh-cn/reference/errors/invalid-get-static-path-param.mdx, src/content/docs/zh-cn/reference/errors/invalid-get-static-paths-entry.mdx, src/content/docs/zh-cn/reference/errors/invalid-get-static-paths-return.mdx, src/content/docs/zh-cn/reference/errors/no-matching-static-path-found.mdx, src/content/docs/zh-cn/reference/errors/prerender-client-address-not-available.mdx, src/content/docs/zh-cn/reference/errors/prerender-dynamic-endpoint-path-collide.mdx, src/content/docs/zh-cn/reference/errors/redirect-with-no-location.mdx, src/content/docs/zh-cn/reference/errors/rewrite-with-body-used.mdx, src/content/docs/zh-cn/reference/errors/static-client-address-not-available.mdx, src/content/docs/zh-cn/reference/errors/static-redirect-not-available.mdx, src/content/docs/zh-cn/reference/errors/unknown-content-collection-error.mdx
Update some error pages
- #9240
=> i18n(zh-cn): Update some error pages

src/content/docs/zh-cn/guides/migrate-to-astro/from-create-react-app.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
Update some migrate guides
- #9240
=> i18n(zh-cn): Update some migrate guides

src/content/docs/zh-cn/recipes/call-endpoints.mdx
Update `call-endpoints.mdx`
- #9240
=> i18n(zh-cn): Update `call-endpoints.mdx`

src/content/docs/zh-cn/guides/upgrade-to/v3.mdx, src/content/docs/zh-cn/guides/upgrade-to/v4.mdx
i18n(zh-cn): Update `v4.mdx`
- #9240
=> i18n(zh-cn): Update `v4.mdx`

src/content/docs/es/develop-and-build.mdx
Translates `develop-and-build.mdx` to spanish.
=> i18n(es): Update develop-and-build.mdx

src/content/docs/zh-cn/guides/imports.mdx
=> i18n(zh-cn): Update `imports.mdx`

src/content/docs/zh-cn/guides/internationalization.mdx
Update  `internationalization.mdx`
- #9240
- #10269
=> i18n(zh-cn): Update  `internationalization.mdx`

src/content/docs/zh-cn/reference/modules/astro-i18n.mdx
=> i18n(zh-cn): Update `astro-i18n.mdx`

src/content/docs/zh-cn/guides/cms/keystatic.mdx
=> i18n(zh-cn): Update Keystatic

src/content/docs/zh-cn/reference/errors/content-schema-contains-slug-error.mdx
Update `content-schema-contains-slug-error.mdx`
- #9240
=> i18n(zh-cn): Update `content-schema-contains-slug-error.mdx`

src/content/docs/zh-cn/guides/upgrade-to/v2.mdx, src/content/docs/zh-cn/guides/upgrade-to/v4.mdx
Update upgrade guides for Astro v2 and v4
- Closes #
=> i18n(zh-cn): Update upgrade guides for Astro v2 and v4

src/content/docs/zh-cn/guides/migrate-to-astro/from-gridsome.mdx
Update `from-gridsome.mdx`
- Closes #
=> i18n(zh-cn): Update `from-gridsome.mdx`

src/content/docs/zh-cn/reference/modules/astro-actions.mdx
Update astro-actions.mdx
- #9240
- #10447
=> i18n(zh-cn): Update astro-actions.mdx

src/content/docs/zh-cn/reference/modules/astro-content.mdx
Update astro-content.mdx
- #9240
=> i18n(zh-cn): Update astro-content.mdx

src/content/docs/ko/recipes/reading-time.mdx
- update `reading-time.mdx`
- #10521
- Closes #
=> i18n(ko-KR): update `reading-time.mdx`

src/content/docs/fr/recipes/reading-time.mdx
Update `recipes/reading-time.mdx` from #10521
=> i18n(fr): Update `recipes/reading-time.mdx` from #10521

src/content/docs/fr/guides/upgrade-to/v5.mdx
Update `guides/upgrade-to/v5.mdx` from #10543
=> i18n(fr): Update `guides/upgrade-to/v5.mdx` from #10543

src/content/docs/fr/guides/actions.mdx
Update `guides/actions.mdx` from #10544
=> i18n(fr): Update `guides/actions.mdx` from #10544

src/content/docs/zh-cn/guides/integrations-guide/index.mdx
Update `integrations-guide/index.mdx`
- #10448 
=> i18n(zh-cn): Update `integrations-guide/index.mdx`

src/content/docs/zh-cn/guides/framework-components.mdx
Update `framework-components.mdx`
- #9240 
=> i18n(zh-cn): Update `framework-components.mdx`

src/content/docs/zh-cn/recipes/captcha.mdx
Update `captcha.mdx`
NOTE: To change the status of Docs translation, I commit some indent.
- #9240 
=> i18n(zh-cn): Update `captcha.mdx`

src/content/docs/zh-cn/reference/errors/get-static-paths-removed-rsshelper.mdx
Update `get-static-paths-removed-rsshelper.mdx`
NOTE: To change the status of Docs translation, I commit an indent.
- #9240
=> i18n(zh-cn): Update `get-static-paths-removed-rsshelper.mdx`

src/content/docs/zh-cn/reference/errors/env-invalid-variables.mdx
Update `env-invalid-variables.mdx`
- #9240
=> i18n(zh-cn): Update `env-invalid-variables.mdx`

src/content/docs/zh-cn/recipes/reading-time.mdx
Update `reading-time.mdx`
- #10521 
=> i18n(zh-cn): Update `reading-time.mdx`

src/content/docs/zh-cn/recipes/index.mdx
Update `recipes/index.mdx`
- #9240 
=> i18n(zh-cn): Update `recipes/index.mdx`

src/content/docs/zh-cn/reference/errors/actions-without-server-output-error.mdx
Update `actions-without-server-output-error.mdx`
- #9240
=> i18n(zh-cn): Update `actions-without-server-output-error.mdx`

src/content/docs/zh-cn/tutorial/3-components/4.mdx
Update `3-components/4.mdx`
- #9240
=> i18n(zh-cn): Update `3-components/4.mdx`

src/content/docs/zh-cn/tutorial/3-components/1.mdx
Update `3-components/1.mdx`
- #10476 
=> i18n(zh-cn): Update `3-components/1.mdx`

src/content/docs/en/guides/integrations-guide/vercel.mdx
Updates our wording for enabling Vercel analytics since their own docs show different methods depending on their package version.
- Closes #10375
=> [vercel.mdx] update for `@vercel/analytics` changes

src/content/docs/zh-cn/tutorial/5-astro-api/index.mdx
Update `5-astro-api/index.mdx`
- #9240
=> i18n(zh-cn): Update `5-astro-api/index.mdx`

src/content/docs/zh-cn/tutorial/5-astro-api/4.mdx
Update `5-astro-api/4.mdx`
NOTE: The doc itself is up-to-date, I update the frontmatter to change the status of Docs translation.
- Closes #
=> i18n(zh-cn): Update `5-astro-api/4.mdx`

src/content/docs/zh-cn/tutorial/6-islands/2.mdx
Update `6-islands/2.mdx`
- #9240
=> i18n(zh-cn): Update `6-islands/2.mdx`

src/content/docs/ko/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/ko/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/ko/guides/migrate-to-astro/from-nuxtjs.mdx
- update `migrate-to-astro/from-gatsby`
- update `migrate-to-astro/from-nextjs`
- update `migrate-to-astro/from-nuxtjs`
- #10597
- Closes #
=> i18n(ko-KR): update `migrate-to-astro/`

src/content/docs/zh-cn/tutorial/5-astro-api/1.mdx
Update `5-astro-api/1.mdx`
- #9240
=> i18n(zh-cn): Update `5-astro-api/1.mdx`

src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx
Update `5-astro-api/3.mdx`
- #9240
=> i18n(zh-cn): Update `5-astro-api/3.mdx`

src/content/docs/zh-cn/tutorial/6-islands/3.mdx
Update `6-islands/3.mdx`
- #9240
=> i18n(zh-cn): Update `6-islands/3.mdx`

src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx
Updates the French translations of some guides in `migrate-to-astro` with changes from #10597
=> i18n(fr): update `guides/migrate-to-astro/*`

src/content/docs/fr/guides/integrations-guide/vercel.mdx
* Updates the French translation of `integrations-guide/vercel.mdx` with changes from #10596
* Adds missing space before colons
=> i18n(fr): update `integrations-guide/vercel.mdx`

src/content/docs/ko/guides/cms/contentful.mdx
- update `contentful.mdx`
- #10620
- Closes #
=> i18n(ko-KR): update `contentful.mdx`

src/content/docs/en/guides/content-collections.mdx
Fix `micromatch` link in `content-collections.mdx`
- Closes #
=> Fix `micromatch` link in `content-collections.mdx`

src/content/docs/fr/guides/integrations-guide/alpinejs.mdx, src/content/docs/fr/guides/integrations-guide/preact.mdx, src/content/docs/fr/guides/integrations-guide/react.mdx, src/content/docs/fr/guides/integrations-guide/solid-js.mdx, src/content/docs/fr/guides/integrations-guide/svelte.mdx, src/content/docs/fr/guides/integrations-guide/vue.mdx
Updates the French translation of some integrations guides to apply the changes made in #10608
=> i18n(fr): update some integrations guides

src/content/i18n/ko.yml
- update `ko.yml`
- #10621
- Closes #
=> i18n(ko-KR): update `ko.yml`

src/content/docs/en/tutorial/6-islands/4.mdx
Added checklist component to the optional content collection tutorial.
Checklist message
**I can use content collections to manage groups of similar content for better performance and organization.**
Discord username: kannansuresh
=> Added checklist component to the optional content collection tutorial.

src/content/docs/zh-cn/tutorial/6-islands/index.mdx
Update `6-islands/index.mdx`
- #10655
=> i18n(zh-cn): Update `6-islands/index.mdx`

src/content/docs/ko/tutorial/6-islands/index.mdx
- update `tutorial/6-islands/index.mdx`
- #10655
- Closes #
=> i18n(ko-KR): update `tutorial/6-islands/index.mdx`

src/content/docs/ar/basics/layouts.mdx
* translate content i18n ar/basics/layouts.mdx
=> i18n(ar): create ar/basics/layouts

src/content/i18n/zh-TW.yml
Update `zh-TW.yml` translation.
- Relates to #10621
=> i18n(zh-tw): update `zh-TW.yml`

src/content/docs/zh-cn/tutorial/1-setup/index.mdx
Update `1-setup/index.mdx`
- #9240
=> i18n(zh-cn): Update `1-setup/index.mdx`

src/content/docs/en/guides/cms/contentful.mdx
A code snippet has been updated in #10620 but not the highlighting: a new line was added so the line numbers no longer match.
=> fix: code snippet highlighting in `cms/contentful.mdx`

src/content/docs/ko/guides/cms/strapi.mdx
Update `strapi.mdx` code file name
`src/kov.d.ts` -> `src/env.d.ts`
discord username : `obtuse_triangle`
- Closes #
=> [i18nIgnore] i18n(ko-KR): Update `strapi.mdx` code file name

src/content/docs/en/guides/migrate-to-astro/from-gridsome.mdx
I've added my blog post link to the community resources. It was suggested by Sarah Rainsberger here: https://github.com/withastro/roadmap/discussions/521#discussioncomment-11772687
- Closes #
I have an account on Astro Discord, but I'm not active there. My display name is Tamás Hajas, and my nickname(?) is eccego.
=> Update the Community resources section of from-gridsome.mdx

src/content/docs/fr/guides/markdown-content.mdx
Update `guides/markdown-content.mdx` from #10670
=> i18n(fr): Update `guides/markdown-content.mdx` from #10670

src/content/docs/fr/basics/layouts.mdx
Removes a sentence in the French translation of `basics/layouts.mdx` (see #10690)
=> i18n(fr): update `basics/layouts/mdx`

src/content/docs/zh-cn/reference/errors/session-storage-init-error.mdx, src/content/docs/zh-cn/reference/errors/session-storage-save-error.mdx
Update errors page
- https://github.com/withastro/docs/pull/10680
=> i18n(zh-cn): Update errors page

src/content/docs/ko/guides/migrate-to-astro/from-gridsome.mdx
- update `from-gridsome.mdx`
- #10691
- Closes #
=> i18n(ko-KR): update `from-gridsome.mdx`

src/content/docs/zh-cn/reference/modules/astro-env.mdx
=> i18n(zh-cn): add `astro-env.mdx`

src/content/docs/zh-cn/reference/experimental-flags/index.mdx
Add `experimental-flags/index.mdx`
- #9240
=> i18n(zh-cn): Add `experimental-flags/index.mdx`

src/content/i18n/fr.yml
Update `i18n/fr.yml` from #10715
```diff
+ # Upgrade guide
+ upgrade.implementationPR: 'Implémentation du PR : '
``` 
=> i18n(fr): Update `i18n/fr.yml` from #10715

src/content/docs/fr/guides/fonts.mdx
Update `guides/fonts.mdx` from #10717
```diff
+ sidebar:
+   label: Fonts
``` 
=> i18n(fr): Update `guides/fonts.mdx` from #10717

src/content/i18n/fr.yml
Update `guides/fonts.mdx` from #10717 (fix #10721)
=> i18n(fr): Update `guides/fonts.mdx` from #10717 (fix #10721)

src/content/docs/fr/tutorial/6-islands/2.mdx
Update `tutorial/6-islands/2.mdx` from #10719
=> i18n(fr): Update `tutorial/6-islands/2.mdx` from #10719

src/content/docs/ko/tutorial/6-islands/2.mdx
- update `tutorial/6-islands/2.mdx`
- #10719
- Closes #
=> i18n(ko-KR): update `tutorial/6-islands/2.mdx`

src/content/docs/zh-cn/reference/experimental-flags/responsive-images.mdx
Add `responsive-images.mdx`
- #9240
=> i18n(zh-cn): Add `responsive-images.mdx`

src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx, src/content/docs/zh-cn/tutorial/6-islands/2.mdx
Update two tutorial docs:
- `5-astro-api/3.mdx`
- `6-islands/2.mdx`
- #10727
=> i18n(zh-cn): Update two tutorial docs

src/content/docs/fr/reference/modules/astro-content.mdx
Update `reference/modules/astro-content.mdx` from #10688
=> i18n(fr): Update `reference/modules/astro-content.mdx` from #10688

src/content/docs/ko/guides/content-collections.mdx, src/content/docs/ko/reference/content-loader-reference.mdx, src/content/docs/zh-cn/tutorial/5-astro-api/3.mdx, src/content/docs/zh-cn/tutorial/6-islands/2.mdx
- update `content-collections.mdx`
- update `content-loader-reference.mdx`
- update `astro-content.mdx`
- #10688 
- #10710
=> i18n(ko-KR): update documents about content collections

src/content/docs/en/guides/deploy/github.mdx
Added a GitHub pages deployment example. 
- Closes #
=> Added github pages deployment example

src/content/docs/zh-cn/guides/endpoints.mdx, src/content/docs/zh-cn/guides/routing.mdx, src/content/docs/zh-cn/reference/api-reference.mdx, src/content/docs/zh-cn/reference/routing-reference.mdx
Add `routing-reference.mdx`
NOTE: To make the status of docs translation update correctly, please merge #10746 first.
- #9240 
- #10352
=> i18n(zh-cn): Add `routing-reference.mdx`

src/content/docs/zh-cn/guides/cms/drupal.mdx
=> i18n(zh-cn): Update `drupal.mdx`

src/content/docs/ko/guides/cms/drupal.mdx
- update `drupal.mdx`
- #10756
- Closes #
=> i18n(ko-KR): update `drupal.mdx`

src/content/docs/zh-cn/guides/content-collections.mdx, src/content/docs/zh-cn/reference/content-loader-reference.mdx, src/content/docs/zh-cn/reference/modules/astro-content.mdx
- Add `content-loader-reference.mdx`
- Update `content-collections.mdx`
- Update `astro-content.mdx`
- #9240
- #10688
- #10710
=> i18n(zh-cn): Add `content-loader-reference.mdx` & Update related docs

src/content/docs/ko/guides/deploy/github.mdx
- update `github.mdx`
- #10753
- Closes #
=> i18n(ko-KR): update `github.mdx`

src/content/docs/fr/guides/deploy/github.mdx
Adds an example link to the French translation of `guides/deploy/github.mdx` (see #10753).
=> i18n(fr): add example link in `guides/deploy/github.mdx`

src/content/docs/en/guides/deploy/cloudflare.mdx
Updates to match actual cloudflare UI
- Closes #
=> Update cloudflare deploy docs

src/content/docs/ko/guides/cms/payload.mdx
- update `payload.mdx`
- #10759
- Closes #
=> i18n(ko-KR): update `payload.mdx`

src/content/docs/ko/reference/error-reference.mdx, src/content/docs/ko/reference/errors/content-loader-returns-invalid-id.mdx
- add `content-loader-returns-invalid-id.mdx`
- #10770
- Closes #
=> i18n(ko-KR): update documents about errors

src/content/docs/fr/guides/cms/payload.mdx
* Adds a new community resource link to `guides/cms/payload.mdx` (see #10759)
* Rewords another community resource link (the word order seemed incorrect in French)
=> i18n(fr): add a new community resource to `guides/cms/payload.mdx`

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
Adds a new article about switching from Gatsby to Astro.
=> [from-gatsby] community article

src/content/docs/fr/guides/upgrade-to/v5.mdx
Adds changes from #10731 to the French translation of `upgrade-to/v5.mdx`.
=> i18n(fr): update `upgrade-to/v5.mdx`

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
This adds another "Migrate from Gatsby" blog post, and additionally reorders posts for better matching pairs in the grid.
(I searched through all featured blog posts in our past What's New monthly showcase posts for any Gatsby resources we might have missed, and found this one.)
=> [from-gatsby] another older community resource added

src/content/docs/fr/reference/modules/astro-i18n.mdx
Update `reference/modules/astro-i18n.mdx` from #10797
=> i18n(fr): Update `reference/modules/astro-i18n.mdx` from #10797

src/content/docs/ko/reference/modules/astro-i18n.mdx
- update `astro-i18n.mdx`
- #10797
- Closes #
=> i18n(ko-KR): update `astro-i18n.mdx`

src/content/docs/ko/guides/integrations-guide/react.mdx
- update `react.mdx`
- #10761
- Closes #
=> i18n(ko-KR): update `react.mdx`

src/content/docs/fr/guides/integrations-guide/react.mdx
Adds a new section to the French translation of `integrations-guide/react.mdx` (see #10761)
=> i18n(fr): update `integrations-guide/react.mdx`

src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx
I did the polite thing and didn't put my article at the top of the list 😄
=> Added my "Gatsby to Astro" migration article

src/content/docs/zh-cn/recipes/tailwind-rendered-markdown.mdx
Update `tailwind-rendered-markdown.mdx`
- #10826
=> i18n(zh-cn): Update `tailwind-rendered-markdown.mdx`

src/content/docs/fr/reference/api-reference.mdx, src/content/docs/fr/reference/integrations-reference.mdx
* Adds changes from #10826 to the French translations of `api-reference.mdx` and `integrations-reference.mdx`
* Small reword in `integrations-reference.mdx` (`Caractéristiques` sounded weird for `sitemap` I think)
=> i18n(fr): update `api-reference.mdx` & `integrations-reference.mdx`

src/content/docs/en/reference/experimental-flags/serialized-configuration.mdx
This PR changes the formatting of the code in this page to be more consistent with other pages.
- Closes #
=> Fix code formatting in `serialized-configuration.mdx`

src/content/docs/fr/guides/styling.mdx
Adds changes from #10826 to the French translation of `guides/styling.mdx`.
=> i18n(fr): update `guides/styling.mdx`

src/content/docs/fr/recipes/tailwind-rendered-markdown.mdx
Adds changes from #10826 to the French translation of `recipes/tailwind-rendered-markdown.mdx`.
=> i18n(fr): update `recipes/tailwind-rendered-markdown.mdx`

src/content/docs/zh-cn/guides/authentication.mdx
Update `authentication.mdx`
- #10882
=> i8n(zh-cn): Update `authentication.mdx`

src/content/docs/fr/guides/deploy/cloudflare.mdx
Adds changes from #10790 to the French translation of `guides/deploy/cloudflare.mdx`.
=> i18n(fr): update `guides/deploy/cloudflare.mdx`

src/content/docs/zh-tw/editor-setup.mdx
Update `editor-setup.mdx`.
- Relates to #10894
=> i18n(zh-tw): update `editor-setup.mdx`

src/content/docs/en/guides/integrations-guide/node.mdx
Update the GitHub URL of the Node.js adapter
https://github.com/withastro/astro/pull/13141
This PR should be merged once the code PR is merged
=> chore: update github node adapter URL

src/content/docs/zh-cn/guides/integrations-guide/netlify.mdx, src/content/docs/zh-cn/guides/integrations-guide/node.mdx
Update `integration-guide/`:
- `netlify.mdx`
- `node.mdx`
- #10898
- #10900
=> i18n(zh-cn): Update `integration-guide/`

src/content/docs/zh-cn/reference/experimental-flags/serialized-configuration.mdx
Update `serialized-configuration.mdx`
- #10875
=> i18n(zh-cn): Update `serialized-configuration.mdx`

src/content/docs/en/guides/integrations-guide/cloudflare.mdx
This PR update the github URL of the cloudflare adapter
This PR needs to be merged after https://github.com/withastro/astro/pull/13150 is merged
=> chore: update github cloudflare adapter URL

src/content/docs/fr/guides/upgrade-to/v5.mdx
Updates a code snippet in the French translation of `upgrade-to/v5.mdx` (see #10822)
=> i18n(fr): update code snippet in `upgrade-to/v5.mdx`

src/content/docs/zh-cn/guides/integrations-guide/cloudflare.mdx, src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
Update following docs:
- `integrations-guide/cloudflare.mdx`
- `integrations-guide/vercel.mdx`
- #10901
- #10910
=> i18n(zh-cn): Update `integrations-guide/`

src/content/docs/zh-cn/guides/upgrade-to/v5.mdx
Update `v5.mdx` & comments in code block
- #10822
=> i18n(zh-cn): Update `v5.mdx`

src/content/docs/en/guides/endpoints.mdx
Adds a line to the endpoint docs describing https://github.com/withastro/astro/pull/13210
- Closes #
=> Document new HEAD handling

src/content/docs/en/guides/endpoints.mdx, src/content/docs/en/guides/integrations-guide/netlify.mdx, src/content/docs/en/reference/configuration-reference.mdx, src/content/docs/en/reference/error-reference.mdx, src/content/docs/en/reference/errors/session-config-missing-error.mdx, src/content/docs/en/reference/errors/session-config-without-flag-error.mdx, src/content/docs/en/reference/errors/session-without-supported-adapter-output-error.mdx, src/content/docs/en/reference/experimental-flags/sessions.mdx
Includes the following PRs
#10760 
#10915 
#10947 
#10952 
#10953
=> 5.3.0 Minor release docs

src/content/docs/ko/reference/error-reference.mdx, src/content/docs/ko/reference/errors/session-config-missing-error.mdx, src/content/docs/ko/reference/errors/session-config-without-flag-error.mdx, src/content/docs/ko/reference/errors/session-without-supported-adapter-output-error.mdx
- update `error-reference.mdx` and `errors/`
- #10950
- Closes #
=> i18n(ko-KR): update `error-reference.mdx` and `errors/`

src/content/docs/en/guides/integrations-guide/netlify.mdx
update code highlighting in `netlify.mdx`
=> fix: update code highlighting

src/content/docs/fr/guides/integrations-guide/markdoc.mdx, src/content/docs/fr/recipes/modified-time.mdx, src/content/docs/fr/recipes/reading-time.mdx, src/content/docs/fr/recipes/tailwind-rendered-markdown.mdx
Updates code snippets in the French translations of some recipes and `integrations-guide/markdoc.mdx` (see #10962)
=> i18n(fr): update code snippets in recipes and `markdoc.mdx`

src/content/docs/fr/guides/content-collections.mdx
Fixes a malformed code snippet in the French translation of `guides/content-collections.mdx` (see #10963)
=> i18n(fr): update code snippet in `guides/content-collections.mdx`

src/content/docs/ko/recipes/tailwind-rendered-markdown.mdx
- update `tailwind-rendered-markdown.mdx`
- #10962
- Closes #
=> i18n(ko-KR): update `tailwind-rendered-markdown.mdx`

src/content/docs/ko/recipes/modified-time.mdx
- update `modified-time.mdx`
- #10962
- Closes #
=> i18n(ko-KR): update `modified-time.mdx`

src/content/docs/fr/reference/experimental-flags/sessions.mdx
Adds changes from #10950 to the French translation of `experimental-flags/sessions.mdx`.
=> i18n(fr): update `experimental-flags/sessions.mdx`

src/content/docs/ko/reference/experimental-flags/sessions.mdx
- update `sessions.mdx`
- #10950
- Closes #
=> i18n(ko-KR): update `sessions.mdx`

src/content/docs/fr/guides/middleware.mdx
Updates a code snippet in the French translation of `guides/middleware.mdx` with changes from #10986
=> i18n(fr): update code snippet in `guides/middleware.mdx`

src/content/docs/en/guides/testing.mdx
- replace `pnpm dlx create-*` with `pnpm crete`.
- use the CLIs used in the official documentation for each technology as much as possible.
- update text that was not rendering because it was written in the wrong place.
=> fix: update cli commands in `testing.mdx`

src/content/docs/en/guides/integrations-guide/cloudflare.mdx
fix link pointing to removed heading.
=> fix: update link pointing to removed heading

src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
Updates a link in the French translation of `integrations-guide/cloudflare` (see #10992)
=> i18n(fr): update a link in `integrations-guide/cloudflare.mdx`

src/content/docs/fr/editor-setup.mdx
Updates an outdated link in the French translation of `editor-setup.mdx` (see #10991)
=> i18n(fr): update link in `editor-setup.mdx`

src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx, src/content/docs/zh-cn/recipes/modified-time.mdx, src/content/docs/zh-cn/recipes/reading-time.mdx, src/content/docs/zh-cn/recipes/tailwind-rendered-markdown.mdx
Update `render(entry)` function in `recipes/` & `integrations-guide.mdx`
- #10962 
=> i18n(zh-cn): Update `render(entry)` function in `recipes/` & `markdoc.mdx`

src/content/docs/fr/guides/testing.mdx
Updates some CLI commands in the French translation of `guides/testing` (see #10993).
=> i18n(fr): update CLI commands in `guides/testings.mdx`

src/content/docs/en/concepts/islands.mdx
The avatar is located in the header, not the heading, so I fix it.
=> fix: update a word in `islands.mdx`

src/content/docs/fr/guides/cms/flotiq.mdx
Updates the French translation of `cms/flotiq.mdx`:
* add UTM tags (see #10994)
* two slight reword to improve the translation
=> i18n(fr): add UTM tags to `cms/flotiq.mdx`

src/content/docs/en/install-and-setup.mdx
update incorrect indentation and whitespace and case sensitivity
=> fix: update `install-and-setup.mdx`

src/content/docs/fr/guides/troubleshooting.mdx
Updates two links in the French translation of `guides/troubleshooting.mdx` (see #11026).
=> i18n(fr): update links in `guides/troubleshooting.mdx`

src/content/docs/ko/basics/astro-components.mdx, src/content/docs/ko/basics/project-structure.mdx, src/content/docs/ko/upgrade-astro.mdx
update `astro-components.mdx` and `project-structure.mdx`
=> i18n(ko-KR): update `astro-components.mdx` and `project-structure.mdx`

src/content/docs/fr/guides/environment-variables.mdx
Adds changes from #11055 to the French translation of `guides/environment-variables.mdx`.
=> i18n(fr): update code snippet in `guide/environment-variables.mdx`

src/content/docs/fr/basics/astro-components.mdx
Adds changes from #11053 to the French translation of `basics/astro-components.mdx`.
=> i18n(fr): update `basics/astro-components.mdx`

src/content/docs/en/guides/configuring-astro.mdx
- Remove unnecessary whitespace
- Update comments in codeblocks
The comments in the codeblock have been updated. If you have any feedback on this, please let me know!
[](url)
=> fix: update `configuring-astro.mdx`

src/content/docs/fr/guides/configuring-astro.mdx
Update `guides/configuring-astro` from #11063
=> i18n(fr): Update `guides/configuring-astro` from #11063

src/content/docs/fr/editor-setup.mdx
Update `editor-setup` from #11064
=> i18n(fr): Update `editor-setup` from #11064

src/content/docs/zh-cn/guides/environment-variables.mdx
Update `environment-variables.mdx`
- #11055
=> i18n(zh-cn): Update `environment-variables.mdx`

src/content/docs/ko/guides/dev-toolbar.mdx
=> i18n(ko-KR): update `dev-toolbar.mdx`

src/content/docs/fr/tutorial/5-astro-api/2.mdx
Updates the highlighting in a code snippet of `tutorial/5-astro-api/2.mdx` (see #11077).
=> i18n(fr): update code snippet in `tutorial/5-astro-api/2.mdx`

src/content/docs/ko/tutorial/5-astro-api/2.mdx
- update `tutorial/5-astro-api/2.mdx`
- #11077
- Closes #
=> i18n(ko-KR): update `tutorial/5-astro-api/2.mdx`

src/content/docs/fr/guides/dev-toolbar.mdx
Updates the French translation of `guides/dev-toolbar.mdx`:
* add some changes from #11075 (most of the `dev toolbar` use was already consistent)
* use French quotes
* fix a typo
=> i18n(fr): update `guides/dev-toolbar.mdx`

src/content/docs/fr/guides/images.mdx
Updates the French translation of `guides/images.mdx`:
* add changes from #11067
* translate all the `alt` attributes and a comment to be consistent
* reword a heading (using `vs` is fine when it's on its own but here we have `Choisir` before... this sounds weird IMO)
* reword a title in a code snippet
=> i18n(fr): update `guides/images.mdx`

src/content/docs/zh-tw/basics/astro-components.mdx
Update `basics/astro-components.mdx` translation.
- Relates to #11053
=> i18n(zh-tw): update `basics/astro-components.mdx`

src/content/docs/ko/reference/experimental-flags/responsive-images.mdx
- update `responsive-images.mdx`
- #11067
- Closes #
=> i18n(ko-KR): update `responsive-images.mdx`

src/content/docs/en/guides/deploy/microsoft-azure.mdx
I've added an article which describes in detail how you can deploy an Astro site to Azure from a GitHub Actions workflow by using the Azure Static Web Apps CLI.
- Closes #
=> Added a new resource for deploying to Azure Static Web Apps

src/content/docs/es/guides/backend/neon.mdx
=> i18n(es): Translate `neon.mdx`

src/content/docs/en/reference/experimental-flags/sessions.mdx
Adds a section for the new session data type feature. Merge when https://github.com/withastro/astro/pull/13320 is released
- Closes #
=> fix: add session data types section

src/content/docs/fr/guides/deploy/microsoft-azure.mdx
* Adds a new community resource to the French translation of `guides/deploy/microsoft-azure.mdx` (see #11105).
* Adds `(en)` next to the links to be consistent with the other pages
=> i18n(fr): update `guides/deploy/microsoft-azure.mdx`

src/content/docs/en/guides/typescript.mdx
- Update codeblocks, whitespaces for better readability
- Fix typos
- Closes #
=> fix: update `typescript.mdx`

src/content/docs/en/guides/deploy/zerops.mdx, src/content/docs/es/guides/deploy/zerops.mdx, src/content/docs/fr/guides/deploy/zerops.mdx, src/content/docs/ko/guides/deploy/zerops.mdx, src/content/docs/pt-br/guides/deploy/zerops.mdx, src/content/docs/zh-cn/guides/deploy/zerops.mdx
The current doc link for zerops yml is broken as zerops docs routes were recently changed.
- Closes #
=> Fix Broken Link in Zerops Guide

src/content/docs/en/guides/environment-variables.mdx, src/content/docs/ko/guides/cms/kontent-ai.mdx, src/content/docs/ko/guides/environment-variables.mdx
- Update whitespace for readability and uniformity
- Update [Vite installation command](https://github.com/withastro/docs/compare/main...jsparkdev:0302-ko?expand=1#diff-e5afe89538d79a61ba763693ce8702800a5489beac44d3c5be2317ee73924c0fR151) to respect [Vite's documentation](https://vite.dev/guide/#manual-installation)
- Update missing inline code to improve readability
- Update mixing of double and single quotes to double quotes for consistency
- Update to match updated English documentation
- Additional updates for improved translations
- Update broken links
=> fix: update `environment-variables.mdx`

src/content/docs/fr/reference/modules/astro-content.mdx
Fixes a type in the French translation of `reference/modules/astro-content.mdx` (see #11127).
=> i18n(fr): fix type in `reference/modules/astro-content.mdx`

src/content/docs/ko/reference/modules/astro-content.mdx
- update `astro-content.mdx`
- #11127
- Closes #
=> i18n(ko-KR): update `astro-content.mdx`

src/content/docs/en/guides/syntax-highlighting.mdx
This PR adds more details to the Shiki customization section in the Astro documentation as described in #11103:
- Adds a few more relevant links to the Shiki documentation
- Document `--astro-code-` CSS variables when using the `css-variables` theme
- Closes #11103
- Suggested label: improve or update documentation
=> Add details to Shiki customization section

src/content/docs/zh-cn/reference/programmatic-reference.mdx
- #11067
- new programmatic APIs and options
=> i18n(zh-cn): update `programmatic-reference.mdx`

src/content/docs/zh-cn/basics/astro-pages.mdx
=> i18n(zh-cn): update `astro-pages.mdx`

src/content/docs/fr/basics/astro-pages.mdx
Adds changes from #11137 to the French translation of `basics/astro-pages` and fixes some typos.
=> i18n(fr): update `basics/astro-pages.mdx`

src/content/docs/zh-cn/guides/content-collections.mdx, src/content/docs/zh-cn/reference/modules/astro-content.mdx
=> i18n(zh-cn): update `content-collections.mdx` and `astro-content.mdx`

src/content/docs/fr/guides/content-collections.mdx, src/content/docs/fr/reference/modules/astro-content.mdx
Adds changes from #11146 to the French translations of `guides/content-collections` and `reference/modules/astro-content`.
=> i18n(fr): update `guides/content-collections` & `modules/astro-content`

src/content/docs/en/guides/routing.mdx
- Update codeblocks
- Update whitespace and double quotes
- Add inline code 
I removed lines [316](https://github.com/withastro/docs/pull/11156/files#diff-d5e3bc536d8257c16397086fee639a17012a6127b4cc1e8321a1034136fecf9dL316) and [366](https://github.com/withastro/docs/pull/11156/files#diff-d5e3bc536d8257c16397086fee639a17012a6127b4cc1e8321a1034136fecf9dL366) as they were not needed, but let me know if you have any other ideas.
=> fix: update `routing.mdx`

src/content/docs/zh-cn/tutorial/4-layouts/2.mdx, src/content/docs/zh-cn/tutorial/4-layouts/3.mdx
=> i18n(zh-cn): Update `4-layouts/`

src/content/docs/ko/reference/error-reference.mdx, src/content/docs/ko/reference/errors/actions-cant-be-loaded.mdx
…ence.mdx`
- create `actions-cant-be-loaded.mdx`
- #11160
=> i18n(ko-KR): create `actions-cant-be-loaded.mdx`

src/content/docs/en/guides/data-fetching.mdx
- Added inline code to improve readability and updated codeblocks.
- Added links to provide additional information.
- Removed unnecessary whitespace.
=> fix: update `data-fetching.mdx`

src/content/docs/fr/guides/data-fetching.mdx
* Adds changes from #11176 to the French translation of `guides/data-fetching.mdx`.
* Rewords `points d'extrémité` en `points de terminaison` to be consistent with the [French title for Endpoints](https://docs.astro.build/fr/guides/endpoints/).
=> i18n(fr): update `guides/data-fetching.mdx`

src/content/docs/ko/recipes/build-forms.mdx
- update `build-forms.mdx`
- #11186
=> i18n(ko-KR): update `build-forms.mdx`

src/content/docs/en/concepts/islands.mdx, src/content/docs/en/guides/configuring-astro.mdx, src/content/docs/en/guides/data-fetching.mdx, src/content/docs/en/guides/dev-toolbar.mdx, src/content/docs/en/guides/environment-variables.mdx, src/content/docs/en/guides/routing.mdx, src/content/docs/en/guides/typescript.mdx, src/content/docs/en/install-and-setup.mdx
- Added missing double quotes, semicolons.
- Removed unnecessary `async` keyword.
- Fixed incorrect code highlighting.
- Updated invalid whitespace.
- Formatted code to improve readability.
=> fix: update some codeblocks

src/content/docs/fr/concepts/islands.mdx, src/content/docs/fr/guides/configuring-astro.mdx, src/content/docs/fr/guides/data-fetching.mdx, src/content/docs/fr/guides/dev-toolbar.mdx, src/content/docs/fr/guides/environment-variables.mdx, src/content/docs/fr/guides/routing.mdx, src/content/docs/fr/guides/typescript.mdx, src/content/docs/fr/install-and-setup.mdx
Adds changes from #11196 and #11200 to the French translation of various files: mainly code snippets updates (semicolon, quotes, highlighting).
=> i18n(fr): update code blocks formatting in various files

src/content/docs/ko/guides/data-fetching.mdx
- update `data-fetching.mdx`
- #11200
=> i18n(ko-KR): update `data-fetching.mdx`

src/content/docs/fr/reference/image-service-reference.mdx
Adds changes from #11158 to the French translation of `image-service-reference.mdx`.
=> i18n(fr): update `image-service-reference.mdx`

src/content/docs/fr/reference/image-service-reference.mdx
Adds changes from #11214 to the French translation of `image-service-reference.mdx`.
=> i18n(fr): update formatting in `image-service-reference.mdx`

src/content/docs/en/guides/endpoints.mdx
- Fixed typos and links.
- Updated code blocks.
=> fix: update `endpoints.mdx`

src/content/docs/ko/reference/configuration-reference.mdx, src/content/docs/ko/reference/experimental-flags/heading-id-compat.mdx, src/content/docs/ko/reference/experimental-flags/preserve-scripts-order.mdx
- update `configuration-reference.mdx`
- create `heading-id-compat.mdx`
- create `preserve-scripts-order.mdx`
- #11215
=> i18n(ko-KR): update `configuration-reference.mdx` and create files

src/content/docs/fr/guides/endpoints.mdx
Adds changes from #11221 to the French translation of `guides/endpoints.mdx` (+ a few rewords).
=> i18n(fr): update `guides/endpoints.mdx`

src/content/docs/pt-br/recipes/analyze-bundle-size.mdx
translate i18n content pt-br recipes/analyze-bundle-size.mdx
=> i18n(pt-BR): translate `recipes/analyze-bundle-size.mdx`

src/content/docs/en/reference/image-service-reference.mdx
This PR adds the documentation of the rest to the utility functions for image assets. 
Related code PR: https://github.com/withastro/astro/pull/13367/files
=> feat(assets): document more utilities

src/content/docs/fr/guides/cms/storyblok.mdx
Updates the French translation of `guides/cms/storyblok.mdx`:
* add changes from #11230
* small rewords
* fix some indentation (asides and code blocks was misaligned in lists)
* translate some comments
=> i18n(fr): update `guides/cms/storyblok.mdx`

src/content/docs/zh-cn/guides/migrate-to-astro/from-hugo.mdx
Update `from-hugo.mdx`
- #11244
=> i18n(zh-cn): Update `from-hugo.mdx`

src/content/docs/ko/guides/migrate-to-astro/from-hugo.mdx
- update `from-hugo.mdx`
- #11244
=> i18n(ko-KR): update `from-hugo.mdx`

src/content/docs/pt-br/reference/errors/actions-cant-be-loaded.mdx
create file i18n pt-br docs/reference/errors/actions-cant-be-loaded.mdx
=> i18n(pt-BR): translate reference/errors/actions-cant-be-loaded.mdx

src/content/docs/fr/reference/directives-reference.mdx
Adds changes from #11257 to the French translation of `directives-reference.mdx`.
=> i18n(fr): update heading level in `directives-reference.mdx`

src/content/docs/ko/reference/directives-reference.mdx
- update `directives-reference.mdx`
- #11257
=> i18n(ko-KR): update `directives-reference.mdx`

src/content/docs/fr/recipes/add-yaml-support.mdx
Updates the French translation of `recipes/add-yaml-support`:
* add changes from #11252 (update yarn command)
* reword the first sentence
* fix a typo to be consistent (infinitive vs imperative)
=> i18n(fr): update `recipes/add-yaml-support.mdx`

src/content/docs/ko/recipes/add-yaml-support.mdx
- update `add-yaml-support.mdx`
- #11252
=> i18n(ko-KR): update `add-yaml-support.mdx`

src/content/docs/zh-cn/recipes/add-yaml-support.mdx
Update `add-yaml-support.mdx`
- #11252
=> i18n(zh-cn): Update `add-yaml-support.mdx`

src/content/docs/en/guides/environment-variables.mdx
For https://github.com/withastro/astro/pull/13444
- Closes #
=> feat: remove cloudflare env limitation

src/content/docs/zh-cn/reference/experimental-flags/heading-id-compat.mdx
=> i18n(zh-cn): add `heading-id-compat.mdx`

src/content/docs/fr/guides/actions.mdx
Fixes a code snippet in the French translation of `guides/actions.mdx` (see #11296).
=> i18n(fr): update code snippet in `guides/actions.mdx`

src/content/docs/ko/guides/actions.mdx, src/content/docs/ko/reference/image-service-reference.mdx
=> i18n(ko-KR): update `actions.mdx` and `image-service-reference.mdx`

src/content/docs/ko/reference/errors/prerender-client-address-not-available.mdx
=> i18n(ko-KR): update `prerender-client-address-not-available.mdx`

src/content/docs/ko/guides/cms/studiocms.mdx
=> i18n(ko-KR): create `studiocms.mdx`

src/content/docs/ko/reference/modules/astro-env.mdx
=> i18n(ko-KR): update `astro-env.mdx`

src/content/docs/zh-cn/reference/modules/astro-env.mdx
Update `astro-env.mdx`
- #10913 
=> i18n(zh-cn): Update `astro-env.mdx`

src/content/docs/fr/reference/modules/astro-env.mdx
Fixes the import in the French translation of `reference/modules/astro-env` (see #10913).
=> i18n(fr): update import in `reference/modules/astro-env.mdx`

src/content/docs/fr/recipes/rss.mdx
Fixes a code snippet in the French translation of `recipes/rss.mdx` (see #11318).
=> i18n(fr): update code snippet in `recipes/rss.mdx`

src/content/docs/ko/guides/cms/gitcms.mdx
=> i18n(ko-KR): create `gitcms.mdx`

src/content/docs/fr/guides/cms/gitcms.mdx
Creates the French translation of `guides/cms/gitcms` added in #11235
=> i18n(fr): create `guides/cms/gitcms.mdx`

src/content/docs/pt-br/reference/legacy-flags.mdx
create i18n pt-br file docs/reference/legacy-flags.mdx
=> i18n(pt-BR): translate `reference/legacy-flags.mdx`

src/content/docs/zh-cn/guides/cms/gitcms.mdx
=> i18n(zh-cn): Add `gitcms.mdx`

src/content/docs/en/reference/experimental-flags/sessions.mdx
Adds the session.load() method to the experimental flag docs
- Closes #
=> Add session.load

src/content/docs/en/reference/experimental-flags/svg.mdx
Corresponding docs for experimental SVG API feature removals
=> Update svg reference for removed features

src/content/docs/en/guides/prefetch.mdx, src/content/docs/en/reference/adapter-reference.mdx, src/content/docs/en/reference/experimental-flags/sessions.mdx, src/content/docs/en/reference/experimental-flags/svg.mdx
Docs for 5.6.0 release
Includes:
- #11256 
- #11250 
- #11347 
- #11348
=> 5.6.0 Minor release docs

src/content/docs/en/guides/deploy/cloudflare.mdx, src/content/docs/en/guides/integrations-guide/cloudflare.mdx
This PR updates the Cloudflare deploy guide and integration docs to cover [Workers](https://developers.cloudflare.com/workers/static-assets/) as well as Pages.
- Closes #
=> Update Cloudflare deploy/integration docs to mention Workers Assets

src/content/docs/zh-cn/guides/cms/studiocms.mdx
=> i18n(zh-cn): Add `studiocms.mdx`

src/content/docs/ko/concepts/why-astro.mdx, src/content/docs/ko/getting-started.mdx, src/content/docs/ko/guides/integrations-guide/index.mdx, src/content/docs/ko/guides/migrate-to-astro/from-create-react-app.mdx, src/content/docs/ko/guides/styling.mdx, src/content/docs/ko/install-and-setup.mdx, src/content/docs/ko/reference/integrations-reference.mdx, src/content/docs/ko/reference/programmatic-reference.mdx, src/content/docs/ko/upgrade-astro.mdx
=> i18n(ko-KR): update tailwindcss links and sections

src/content/docs/en/reference/adapter-reference.mdx
- Add inline codeblock to improve readability
=> fix: add inline codeblock to filenames in `adapter-reference`

src/content/docs/en/guides/deploy/cloudflare.mdx
- Add whitespace to improve readability
- Update invalid indentation in codeblocks
=> fix: update indent and spaces in `guides/deploy/cloudflare.mdx`

src/content/docs/ko/reference/adapter-reference.mdx
=> i18n(ko-KR): update `adapter-reference.mdx`

src/content/docs/ko/reference/routing-reference.mdx
=> i18n(ko-KR): update `routing-reference.mdx`

src/content/docs/fr/guides/integrations-guide/markdoc.mdx
Adds changes from #11379 to the French translation of `integrations-guide/markdoc.mdx`.
=> i18n(fr): update `integrations-guide/markdoc.mdx`

src/content/docs/fr/reference/routing-reference.mdx
Adds changes from #11365 to the French translation of `routing-reference.mdx`.
=> i18n(fr): update code snippet in `routing-reference.mdx`

src/content/docs/zh-cn/reference/experimental-flags/svg.mdx
=> i18n(zh-cn): Update `svg.mdx`

src/content/docs/zh-cn/reference/routing-reference.mdx
Update `routing-reference.mdx`
- #11365 
=> i18n(zh-cn): Update `routing-reference.mdx`

src/content/docs/ko/guides/cms/directus.mdx, src/content/docs/ko/guides/cms/drupal.mdx, src/content/docs/ko/guides/cms/flotiq.mdx, src/content/docs/ko/guides/cms/ghost.mdx, src/content/docs/ko/guides/cms/wordpress.mdx
=> i18n(ko-KR): update `/guides/cms/`

src/content/docs/es/concepts/why-astro.mdx
Update `concepts/why-astro.mdx`. Just a word!
- [3cdd846](https://github.com/withastro/docs/commit/3cdd846b6610dab87bef106e04ce426561579c4f)
=> i18n(es): update `why-astro.mdx`

src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx, src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx, src/content/docs/fr/guides/migrate-to-astro/from-eleventy.mdx, src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/fr/guides/migrate-to-astro/from-gitbook.mdx, src/content/docs/fr/guides/migrate-to-astro/from-gridsome.mdx, src/content/docs/fr/guides/migrate-to-astro/from-hugo.mdx, src/content/docs/fr/guides/migrate-to-astro/from-jekyll.mdx, src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/fr/guides/migrate-to-astro/from-nuxtjs.mdx, src/content/docs/fr/guides/migrate-to-astro/from-pelican.mdx, src/content/docs/fr/guides/migrate-to-astro/from-sveltekit.mdx, src/content/docs/fr/guides/migrate-to-astro/from-vuepress.mdx, src/content/docs/fr/guides/migrate-to-astro/from-wordpress.mdx
Adds changes from #11376 to the French translations of `migrate-to-astro/from` guides.
=> i18n(fr): update `migrate-to-astro/from` guides to use cards list

src/content/docs/fr/guides/cms/directus.mdx, src/content/docs/fr/guides/cms/drupal.mdx, src/content/docs/fr/guides/cms/ghost.mdx, src/content/docs/fr/guides/cms/wordpress.mdx
Adds changes from #11376 to the French translation of some `guides/cms`.
=> i18n(fr): update some `guides/cms` to use cards list

src/content/docs/es/guides/cms/studiocms.mdx
=> i18n(es): translate `studiocms.mdx`

src/content/docs/es/guides/cms/gitcms.mdx
Translate file to spanish
- Closes #
=> i18n(es): translate `gitcms.mdx`

src/content/docs/es/basics/astro-pages.mdx
Update `basics/astro-pages.mdx`
- [8a9c32f](https://github.com/withastro/docs/commit/8a9c32f2ce087db64f052e5ce8fd18216c057924)
- [c3888a9](https://github.com/withastro/docs/commit/c3888a9da7b8508b840ead9f168907901a010e72)
- [45a1170](https://github.com/withastro/docs/commit/45a117052d85d9a706e4095f1cb9ffb2b0bf2caa)
=> i18n(es): update `astro-pages.mdx`

src/content/docs/es/editor-setup.mdx
Update `editor-setup.mdx`
- [f5e2d7f](https://github.com/withastro/docs/commit/f5e2d7f886120a68828b847465f66c1b8fb45062)
- [73b928f](https://github.com/withastro/docs/commit/73b928fcf333d7fb45047a7b4f4ac4794380415d)
- [3993bfa](https://github.com/withastro/docs/commit/3993bfa0ff86e7228165f2c34c1b75bde3190457)
=> i18n(es): update `editor-setup.mdx`

src/content/docs/es/getting-started.mdx
Update `getting-started.mdx`
- [3cdd846](https://github.com/withastro/docs/commit/3cdd846b6610dab87bef106e04ce426561579c4f)
- [45a1170](https://github.com/withastro/docs/commit/45a117052d85d9a706e4095f1cb9ffb2b0bf2caa)
=> i18n(es): update `getting-started.mdx`

src/content/docs/es/guides/deploy/azion.mdx
=> i18n(es): translate `azion.mdx`

src/content/docs/es/guides/deploy/clever-cloud.mdx
=> i18n(es): translate `clever-cloud.mdx`

src/content/docs/en/guides/deploy/clever-cloud.mdx
Links to Clever Cloud documentation have changed. This PR updates them.
Note: there are existing redirections in the meantime. 
- Closes #
=> doc: update clever cloud link

src/content/docs/ko/guides/deploy/clever-cloud.mdx
=> i18n(ko-KR): update `clever-cloud.mdx`

src/content/docs/ko/reference/error-reference.mdx, src/content/docs/ko/reference/errors/cannot-extract-font-type.mdx, src/content/docs/ko/reference/errors/cannot-fetch-font-file.mdx, src/content/docs/ko/reference/errors/cannot-load-font-provider.mdx, src/content/docs/ko/reference/errors/cant-use-astro-config-module-error.mdx, src/content/docs/ko/reference/errors/experimental-fonts-not-enabled.mdx, src/content/docs/ko/reference/errors/font-family-not-found.mdx, src/content/docs/ko/reference/errors/session-without-supported-adapter-output-error.mdx
=> i18n(ko-KR): update `errors/` and `error-reference.mdx`

src/content/docs/ko/reference/modules/astro-config.mdx
=> i18n(ko-KR): update `astro-config.mdx`

src/content/docs/ko/guides/integrations-guide/cloudflare.mdx, src/content/docs/ko/guides/integrations-guide/netlify.mdx, src/content/docs/ko/guides/integrations-guide/node.mdx, src/content/docs/ko/guides/integrations-guide/vercel.mdx, src/content/docs/ko/reference/configuration-reference.mdx
- update `vercel.mdx`
- update `node.mdx`
- update `netlify.mdx`
- update `cloudflare.mdx`
- update `configuration-reference.mdx`
- #11444
- #11460
=> i18n(ko-KR): update Korean documents

src/content/docs/fr/reference/modules/astro-config.mdx
Creates the French translation of `reference/modules/astro-config.mdx` added in #11444
=> i18n(fr): create `reference/modules/astro-config.mdx`

src/content/docs/ko/guides/sessions.mdx
=> i18n(ko-KR): create `sessions.mdx`

src/content/docs/ko/reference/experimental-flags/fonts.mdx
=> i18n(ko-KR): create `fonts.mdx`

src/content/docs/zh-cn/guides/deploy/clever-cloud.mdx
Update `clever-cloud.mdx`
- #11448 
=> i18n(zh-cn): Update `clever-cloud.mdx`

src/content/docs/fr/guides/deploy/clever-cloud.mdx
Updates the external links in the French translation of `guides/deploy/clever-cloud.mdx` (see #11448).
=> i18n(fr): update links in `guides/deploy/clever-cloud.mdx`

src/content/docs/ko/tutorial/1-setup/2.mdx
=> i18n(ko-KR): update `tutorial/1-setup/2.mdx`

src/content/docs/fr/tutorial/1-setup/2.mdx
Adds changes from #11480 to the French translation of `tutorial/1-setup/2.mdx`.
=> i18n(fr): update `tutorial/1-setup/2.mdx`

src/content/docs/fr/reference/modules/astro-content.mdx
Adds changes from #11333 and #11435 to the French translation of `modules/astro-content.mdx`.
=> i18n(fr): update `modules/astro-content.mdx`

src/content/docs/fr/guides/fonts.mdx
Adds changes from #11444 to the French translation of `guides/fonts.mdx`.
=> i18n(fr): update `guides/fonts.mdx`

src/content/docs/fr/guides/sessions.mdx
Creates the French translation of `guides/sessions.mdx` added in #11444 and updated in #11460
> [!IMPORTANT]
> Links should be fixed after #11464 is merged!
=> i18n(fr): create `guides/sessions.mdx`

src/content/docs/fr/reference/experimental-flags/fonts.mdx
Adds changes from #11470 to the French translation of `experimental-flags/fonts`.
=> i18n(fr): update `experimental-flags/fonts.mdx`

src/content/docs/zh-cn/guides/cms/flotiq.mdx
Update `flotiq.mdx`
To respect the use of `x` in title by contributor, I left it as untranslated. Maybe other translators have more suitable way to deal with it, I'm all ears.
- #11396
=> i18n(zh-cn): Update `flotiq.mdx`

src/content/docs/fr/guides/imports.mdx
Adds changes from #11508 to the French translation of `guides/imports.mdx`.
=> i18n(fr): update `guides/imports.mdx`

src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
Adds changes from #11506 to the French translation of `integrations-guide/cloudflare.mdx`.
=> i18n(fr): update `integrations-guide/cloudflare.mdx`

src/content/docs/fr/reference/errors/unsupported-external-redirect.mdx
Adds changes from #11545 to the French translation of `errors/unsupported-external-redirect.mdx`.
=> i18n(fr): update `errors/unsupported-external-redirect.mdx`

src/content/docs/ko/guides/deploy/cloudflare.mdx, src/content/docs/ko/guides/deploy/netlify.mdx, src/content/docs/ko/guides/deploy/vercel.mdx, src/content/docs/ko/reference/configuration-reference.mdx
=> i18n(ko-KR): update `deploy/`

src/content/docs/ko/reference/errors/unsupported-external-redirect.mdx
=> i18n(ko-KR): update `unsupported-external-redirect.mdx`

src/content/docs/fr/guides/integrations-guide/node.mdx
Adds changes from #11497 to the French translation of `integrations-guide/node.mdx`.
=> i18n(fr): update `integrations-guide/node.mdx`

src/content/docs/fr/guides/deploy/vercel.mdx
Adds changes from #11497 to the French translation of `guides/deploy/vercel.mdx`.
=> i18n(fr): update `guides/deploy/vercel.mdx`

src/content/docs/ja/getting-started.mdx
Matches latest English source (see: 3cdd846b6610dab87bef106e04ce426561579c4f)
- Closes #
=> i18n(ja): Update `getting-started.mdx` 

src/content/docs/fr/recipes/i18n.mdx
Adds changes from #11587 to the French translation of `recipes/i18n.mdx`.
=> i18n(fr): update code snippet in `recipes/i18n.mdx`

src/content/docs/en/guides/backend/xata.mdx
`XATA_TOKEN_API` to `XATA_API_KEY` 
- Closes #
=> Fix `guides/backend/xata.mdx`

src/content/docs/ko/guides/backend/xata.mdx
=> i18n(ko-KR): update `xata.mdx`

src/content/docs/fr/guides/backend/xata.mdx
Adds changes from #11602 to the French translation of `guides/backend/xata.mdx`.
=> i18n(fr): update `guides/backend/xata.mdx`

src/content/docs/zh-cn/guides/backend/xata.mdx
=> i18n(zh-cn): Update `xata.mdx`

src/content/docs/zh-cn/reference/modules/astro-assets.mdx
Update `astro-assets.mdx`
- #11586 
=> i18n(zh-cn): Update `astro-assets.mdx`

src/content/docs/zh-cn/reference/errors/unsupported-external-redirect.mdx
Update `unsupported-external-redirect.mdx`
- #11545
=> i18n(zh-cn): Update `unsupported-external-redirect.mdx`

src/content/docs/en/reference/modules/astro-config.mdx
Add proper import for the `astro:config/server` section in `astro-config.mdx`
username: `notjb`
=> Fix import for the `astro:config/server` section in `astro-config.mdx`

src/content/docs/pt-br/reference/modules/astro-config.mdx
translate to brazilian portuguese
- Closes #
It's my first PR ever made, so I'm not sure if this should be commented or not.
My discord username is lyingcap and I've joined the discord server recently.
=> i18n(pt): translate `astro-config.mdx`

src/content/docs/en/reference/experimental-flags/fonts.mdx
=> fix: update `fonts.mdx`

src/content/docs/fr/reference/modules/astro-config.mdx
Adds changes from #11634 to the French translation of `modules/astro-config.mdx`.
=> i18n(fr): update code snippet in `modules/astro-config.mdx`

src/content/docs/pt-br/reference/modules/astro-config.mdx
=> i18n(pt-BR): update code snippet in `astro-config.mdx`

src/content/docs/zh-cn/reference/modules/astro-config.mdx
Update `astro-config.mdx`
- #11634
=> i18n(zh-cn): Update `astro-config.mdx`

src/content/docs/fr/basics/astro-components.mdx, src/content/docs/fr/basics/layouts.mdx, src/content/docs/fr/guides/framework-components.mdx, src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx, src/content/docs/fr/guides/migrate-to-astro/from-docusaurus.mdx, src/content/docs/fr/guides/migrate-to-astro/from-gatsby.mdx, src/content/docs/fr/guides/migrate-to-astro/from-nextjs.mdx, src/content/docs/fr/reference/astro-syntax.mdx, src/content/docs/fr/reference/errors/reserved-slot-name.mdx, src/content/docs/fr/tutorial/4-layouts/1.mdx
Updates the French translation of `basics/astro-components.mdx` to:
* improve the translation based on the updated i18n guide (see #11593) + fix links in other files because of updated headings
* add changes from #11657
=> i18n(fr): update `basics/astro components`

src/content/docs/ru/reference/modules/astro-i18n.mdx
Adds a translation of `ru/reference/modules/astro-i18n.mdx` page
=> i18n(ru): Add new `reference/modules/astro-i18n.mdx` translation

src/content/docs/ko/guides/deploy/aws.mdx
=> i18n(ko-KR): update `aws.mdx`

src/content/docs/fr/guides/cms/decap-cms.mdx
Updates the French translation of `guides/cms/decap-cms` with changes from:
* #6800 (some changes from this PR was missing)
* #10117 (we missed this PR...)
* #11593 (improves the wording + translates some untranslated UI strings)
=> i18n(fr): update `guides/cms/decap-cms.mdx`

src/content/docs/fr/guides/backend/google-firebase.mdx, src/content/docs/fr/guides/backend/index.mdx, src/content/docs/fr/guides/backend/neon.mdx, src/content/docs/fr/guides/backend/sentry.mdx, src/content/docs/fr/guides/backend/supabase.mdx, src/content/docs/fr/guides/backend/turso.mdx, src/content/docs/fr/guides/backend/xata.mdx
Updates the French translation of `guides/backend` to:
* add changes from #11711 to `turso.mdx`
* fix inline code (quotes were used instead of inline code in some places)
* fix some typo
* fix some translation errors (e.g. `enregistrer` instead of `connecter`)
* replace double quotes with French quotes
* update the text case
* use infinitive form instead of imperative form in headings
* translate some examples
* use a consistent translation across the docs (see #11593):
* replace `endpoint`/`point d'accès` with `point de terminaison`
* replace `le CLI` with `la CLI`
* add the link language after community/official resources
=> i18n(fr): update `guides/backend`

src/content/docs/ko/guides/cms/contentful.mdx, src/content/docs/ko/guides/cms/ghost.mdx, src/content/docs/ko/guides/cms/hashnode.mdx, src/content/docs/ko/guides/cms/preprcms.mdx, src/content/docs/ko/guides/cms/sitecore.mdx, src/content/docs/ko/guides/cms/statamic.mdx, src/content/docs/ko/guides/cms/strapi.mdx, src/content/docs/ko/guides/cms/umbraco.mdx
=> i18n(ko-KR): update `cms/`

src/content/docs/fr/guides/cms/preprcms.mdx
Update the French translation of `guides/cms/preprcms.mdx` with changes from:
* #6983 (the first sentence wasn't updated)
* #11722
* #11593
*  translate some missing parts
* reword some sentences to make the reading easier in French
=> i18n(fr): update `guides/cms/preprcms.mdx`

src/content/docs/fr/guides/cms/sitecore.mdx
Updates the French translation of `guides/cms/sitecore.mdx` with changes from:
* #11722 (fix typo)
* #11593 (add language after community links + tiny reword/translation update)
=> i18n(fr): update `guides/cms/sitecore.mdx`

src/content/docs/fr/guides/cms/umbraco.mdx
Updates the French translation of `guides/cms/umbraco.mdx` with changes from:
* #11722 (code snippets language)
* #11593
* replace `extraction` with `récupération` (fetch)
* replace double quotes with French quotes
* add some non breaking space to prevent punctuation (or emoticon) to be isolated on a new line
* replace `en` with `Anglais` in community links
* small rewords to make the reading easier
=> i18n(fr): update `guides/cms/umbraco.mdx`

src/content/docs/en/guides/deploy/cloudflare.mdx, src/content/docs/en/guides/deploy/netlify.mdx, src/content/docs/en/install-and-setup.mdx, src/content/docs/en/tutorial/1-setup/1.mdx
Minor release docs for 5.8.0
Includes: 
-  #11692 
Yes, that's it! 😄
=> 5.8.0 minor release docs

src/content/docs/fr/install-and-setup.mdx, src/content/docs/fr/tutorial/1-setup/1.mdx
Adds changes from #11735 to the French translations of `install-and-setup.mdx` and `tutorial/1-setup/1.mdx`.
=> i18n(fr): update `install-and-setup.mdx` and `tutorial/1-setup/1.mdx`

src/content/docs/zh-cn/guides/backend/turso.mdx
=> i18n(zh-cn): Update `turso.mdx`

src/content/docs/zh-cn/guides/cms/contentful.mdx, src/content/docs/zh-cn/guides/cms/ghost.mdx, src/content/docs/zh-cn/guides/cms/hashnode.mdx, src/content/docs/zh-cn/guides/cms/preprcms.mdx, src/content/docs/zh-cn/guides/cms/sitecore.mdx, src/content/docs/zh-cn/guides/cms/statamic.mdx, src/content/docs/zh-cn/guides/cms/strapi.mdx, src/content/docs/zh-cn/guides/cms/umbraco.mdx
=> i18n(zh-cn): Update `cms/`

src/content/docs/en/reference/modules/astro-actions.mdx
Updates zod checkbox validation syntax as per [#13820](https://github.com/withastro/astro/issues/13820#issuecomment-2894219006) .
- Closes #11734 
- Suggested label: `code snippet update`
=> Update astro:actions checkbox validation

src/content/docs/fr/reference/modules/astro-actions.mdx
i18n(fr): Update `reference/modules/astro-actions` from #11761
- Closes #
=> i18n(fr): Update `reference/modules/astro-actions` from #11761

src/content/docs/en/guides/sessions.mdx
Removed Currently from the sessions wording. 
- Closes #11788 
=> Removed currently

src/content/docs/fr/guides/sessions.mdx
Adds changes from #11789 to the French translation of `guides/sessions`.
=> i18n(fr): update `guides/sessions.mdx`

src/content/docs/fr/tutorial/5-astro-api/4.mdx
Adds changes from #11810 to the French translation of `tutorial/5-astro-api/4.mdx`.
=> i18n(fr): update `tutorial/5-astro-api/4.mdx`

src/content/docs/ko/reference/experimental-flags/csp.mdx
=> i18n(ko-KR): create `csp.mdx`

src/content/docs/zh-cn/guides/server-islands.mdx
Update `server-islands.mdx`
- #11751
=> i18n(zh-cn): Update `server-islands.mdx`

src/content/docs/zh-cn/reference/error-reference.mdx, src/content/docs/zh-cn/reference/errors/csp-not-enabled.mdx
Update `error-reference.mdx` and related docs
- #11826 
=> i18n(zh-cn): Update `error-reference.mdx` and related docs

src/content/docs/ko/guides/integrations-guide/alpinejs.mdx, src/content/docs/ko/guides/integrations-guide/markdoc.mdx, src/content/docs/ko/guides/integrations-guide/mdx.mdx, src/content/docs/ko/guides/integrations-guide/partytown.mdx, src/content/docs/ko/guides/integrations-guide/preact.mdx, src/content/docs/ko/guides/integrations-guide/react.mdx, src/content/docs/ko/guides/integrations-guide/sitemap.mdx, src/content/docs/ko/guides/integrations-guide/solid-js.mdx, src/content/docs/ko/guides/integrations-guide/svelte.mdx, src/content/docs/ko/guides/integrations-guide/vercel.mdx, src/content/docs/ko/guides/integrations-guide/vue.mdx
updates small contents in `integrations-guide/`
=> i18n(ko-KR): update `integrations-guide/`

src/content/docs/fr/recipes/build-forms.mdx
Adds changes from #11872 to the French translation of `recipes/build-forms.mdx`.
=> i18n(fr): update `recipes/build-forms.mdx`

src/content/docs/fr/reference/experimental-flags/csp.mdx
Translates in French the file `experimental-flags/csp.mdx` added in #11826 and updated in #11850 and #11868
=> i18n(fr): add `experimental-flags/csp.mdx`

src/content/docs/en/reference/experimental-flags/csp.mdx
This PR does two things:
- it updates some examples where the URLs aren't supposed to have apostrophes
- updates some APIs, to be in line with https://github.com/withastro/astro/pull/13931
=> fix(csp): code examples

src/content/docs/ko/reference/experimental-flags/csp.mdx
=> i18n(ko-KR): update `csp.mdx`

src/content/docs/en/reference/adapter-reference.mdx
update indent and typo in `adapter-reference.mdx`
=> fix: update codeblock in `adapter-reference.mdx`

src/content/docs/en/guides/integrations-guide/cloudflare.mdx
- small update in `cloudflare.mdx`
=> fix: update `cloudflare.mdx`

src/content/docs/ko/reference/experimental-flags/live-content-collections.mdx
- #11901
- #11910
- #11920
- #11923
=> i18n(ko-KR): add `live-content-collections.mdx`

src/content/docs/ko/reference/errors/live-content-config-error.mdx
=> i18n(ko-KR): update `live-content-config-error.mdx`

src/content/docs/ko/guides/images.mdx, src/content/docs/ko/reference/configuration-reference.mdx, src/content/docs/ko/reference/modules/astro-assets.mdx
- #11901 
- #11911
Updates `configuration-reference.mdx`, `images.mdx`, `astro-assets.mdx`
=> i18n(ko-KR): update `configuration-reference.mdx`, images docs

src/content/docs/en/guides/content-collections.mdx
update codeblock in `content-collection.mdx`
=> fix: update codeblock in `content-collection.mdx`

src/content/docs/fr/basics/astro-components.mdx
Adds changes from #11900 to the French translation of `basics/astro-components`.
=> i18n(fr): update `basics/astro-components`

src/content/docs/fr/reference/experimental-flags/live-content-collections.mdx
Adds changes from #11954 to the French translation of `experimental-flags/live-content-collections`.
=> i18n(fr): update `experimental-flags/live-content-collections`

src/content/docs/ko/guides/cms/sitepins.mdx
=> i18n(ko-KR): create `sitepins.mdx`

src/content/docs/en/guides/build-with-ai.mdx
Adds zed.dev instructions for adding the astro mcp server. Feel free to push to this PR to adjust to your liking, I've just built this in fashion after the Windsurf instructions.
https://zed.dev/docs/ai/mcp
- Closes #
=> Add basic guide for MCP with Zed editor

src/content/docs/fr/guides/build-with-ai.mdx
Adds the French translation of `guides/build-with-ai.mdx` added in #12019 and updated in #12037, #12035 and #12036.
=> i18n(fr): add `guides/build-with-ai.mdx`

src/content/docs/en/guides/build-with-ai.mdx
Adds a generic manual configuration section, because many tools use the same format.
Also adds Gemini CLI and Claude Code GitHub Action
- Closes #
=> Add more MCP sections

src/content/docs/fr/reference/content-loader-reference.mdx
i18n(fr): Update `content-loader-reference` from #12056
- Closes #
=> i18n(fr): Update `content-loader-reference` from #12056

src/content/docs/en/guides/view-transitions.mdx
The example for custom swap functions seemed to be missing a line.
=> add missing event listener boiler plate

src/content/docs/fr/guides/view-transitions.mdx
Adds changes from #12095 to the French translation of `guides/view-transitions.mdx`.
=> i18n(fr): update code snippet in `guides/view-transitions.mdx`

src/content/docs/en/guides/migrate-to-astro/from-docusaurus.mdx
grammar
Changed from "to" to "with" in sentence "Both Astro and Docusaurus support MDX pages. You should be able to use your existing .mdx files to Astro". Changed for sake of grammatical correctness.
- Closes #
=> Update from-docusaurus.mdx; en-only

src/content/docs/en/editor-setup.mdx
This adds some missing tools that appeared since the last time this page was edited. I additionally tweaked a few small things, see comments.
=> feat(editor): Added some tools and tweaks to the editor setup apge

src/content/docs/es/recipes/index.mdx
=> i18n(es): update recipes/index.mdx

src/content/docs/es/editor-setup.mdx
https://github.com/withastro/docs/commits/main/src/content/docs/en/editor-setup.mdx?since=2025-04-13T20:20:41.000Z
- Closes #
=> i18n(es): update editor-setup page

src/content/docs/ko/guides/integrations-guide/db.mdx
=> i18n(ko-KR): update `db.mdx`

src/content/docs/es/contribute.mdx
La traducción de issue suele ser algo complicada, para mi la mejor traducción seria "problema" (es mas facil de entender), pero hay varios sinonimos
- Closes #
=> i18n(es): update contribute guide

src/content/docs/es/guides/prefetch.mdx
Changes since https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/prefetch.mdx?since=2024-04-08T11:25:44.000Z
- Closes #
=> i18n(es): update prefetch guide

src/content/docs/en/guides/integrations-guide/alpinejs.mdx
Fixed typo in AlpineJS integration sample.
=> Fix import in integration sample

src/content/docs/fr/guides/integrations-guide/alpinejs.mdx
Adds changes from #12247 to the French translation of `integrations-guide/alpinejs`.
=> i18n(fr): update `integrations-guide/alpinejs`

src/content/docs/en/guides/authentication.mdx
fixes #12260
Just broken link fix. 
- Closes #12260 
discord: 2u841r
=> fix: update broken link to correct URL

src/content/docs/fr/guides/deploy/railway.mdx
Adds the French translation of `guides/deploy/railway` added in #12268
=> i18n(fr): translate `guides/deploy/railway.mdx`

src/content/docs/fr/guides/integrations-guide/sitemap.mdx
Adds changes from #12304 to the French translation of `integrations-guide/sitemap`.
=> i18n(fr): update `integrations-guide/sitemap.mdx`

src/content/docs/en/guides/authentication.mdx
Add adapter prerequisite to auth-astro docs.
- Closes #12271
First contribution!
=> Fixes #12271 with adapter prerequisite missing from auth-astro

src/content/docs/en/reference/experimental-flags/fonts.mdx
Fix to a broken link to the experimental Fonts API RFC.
- Closes #
- Suggested label: fix
=> Fix broken link to the fonts RFC

src/content/docs/es/guides/backend/prisma-postgres.mdx
Create the `prisma-postgres.mdx` page in the Spanish documentation.
- Original [page](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/backend/prisma-postgres.mdx)
=> i18n(es): create `prisma-postgres.mdx`

src/content/docs/es/guides/cms/sitepins.mdx
Create the `sitepins.mdx` page in the Spanish documentation.
- [Original page](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/cms/sitepins.mdx)
=> i18n(es): create `sitepins.mdx`

src/content/docs/es/guides/deploy/cloudray.mdx
Create the `cloudray.mdx` page in the Spanish documentation.
- [Original page](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/cloudray.mdx)
=> i18n(es): create `cloudray.mdx`

src/content/docs/es/upgrade-astro.mdx
Update the `upgrade-astro.mdx` page in the Spanish documentation.
- [3cdd846](https://github.com/withastro/docs/commit/3cdd846b6610dab87bef106e04ce426561579c4f#diff-5963da07070d6cac124699479c46c876d6cc7b9e971ed4c8981a13d506d31c88)
- [81ae90d](https://github.com/withastro/docs/commit/81ae90dba4dbdffac48b8d0978ab0b59c3b47304)
=> i18n(es): update `upgrade-astro.mdx`

src/content/docs/fr/reference/configuration-reference.mdx
Adds changes from #12399 to the French translation of `configuration-reference.mdx`.
> [!NOTE]
> I guess #12405 might take some time to be merged/closed. To be up to date in case other changes happen, I think we can merge this one.
=> i18n(fr): update links in `configuration-reference.mdx`

src/content/docs/ar/contribute.mdx
Update contribute changes by [commit](https://github.com/withastro/docs/commit/d59b45a7fa33c5142b311cc46f98d676310763be) 'Add open issues tip to contributing page'.
- Closes #
=> i18n(ar): update contribute.mdx

src/content/docs/en/guides/cms/storyblok.mdx
Hi, from the Storyblok DX team, we have archived the storyblok-astro in favor of a monorepo. This PR updates the repo link to the correct package and includes additional official documentation from Storyblok. 
- Closes #
=> docs: update Storyblok astro resources

src/content/docs/fr/reference/errors/response-sent-error.mdx
Adds changes from #12443 to the French translation of `errors/response-sent-error.mdx`
=> i18n(fr): update `errors/response-sent-error.mdx`

src/content/docs/fr/guides/cms/storyblok.mdx
Adds changes from #12433 to the French translation of `guides/cms/storyblok`.
=> i18n(fr): update `cms/storyblok.mdx`

src/content/docs/de/concepts/why-astro.mdx
Update German translation of `why-astro.mdx`
- [All changes since 17.12.2024
](https://git-diff-viewer.trueberryless.org/diff?repo=withastro%2Fdocs&file=src%2Fcontent%2Fdocs%2Fen%2Fconcepts%2Fwhy-astro.mdx&since=2024-12-17)
- https://github.com/withastro/docs/pull/11279
=> i18n(de): update why-astro.mdx

src/content/i18n/de.yml
Update German translation of the UI strings.
- [all changes since 26.06.2025](https://git-diff-viewer.trueberryless.org/diff?repo=withastro%2Fdocs&file=src%2Fcontent%2Fi18n%2Fen.yml&since=2025-06-26) 
- https://github.com/withastro/docs/pull/12012
- https://github.com/withastro/docs/pull/12227
=> i18n(de): update de.yml

src/content/docs/fr/reference/cli-reference.mdx
i18n(fr): Update `reference/cli-reference.mdx` from #12495
=> i18n(fr): Update `reference/cli-reference.mdx` from #12495

src/content/docs/fr/reference/container-reference.mdx
i18n(fr): Add `reference/container-reference.mdx` in French language :tada:
I participate to the Hacktoberfest 2025! 👻
=> i18n(fr): Add `reference/container-reference.mdx`

src/content/docs/fr/reference/container-reference.mdx
Adds changes from #12511 to the French translation of `container-reference.mdx`.
=> i18n(fr): update `container-reference.mdx`
